#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  scalar_t__ PFNGLVIEWPORTINDEXEDFVPROC ;
typedef  scalar_t__ PFNGLVIEWPORTINDEXEDFPROC ;
typedef  scalar_t__ PFNGLVIEWPORTARRAYVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBLPOINTERPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBL4DVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBL4DPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBL3DVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBL3DPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBL2DVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBL2DPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBL1DVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBL1DPROC ;
typedef  scalar_t__ PFNGLVALIDATEPROGRAMPIPELINEPROC ;
typedef  scalar_t__ PFNGLUSEPROGRAMSTAGESPROC ;
typedef  scalar_t__ PFNGLSHADERBINARYPROC ;
typedef  scalar_t__ PFNGLSCISSORINDEXEDVPROC ;
typedef  scalar_t__ PFNGLSCISSORINDEXEDPROC ;
typedef  scalar_t__ PFNGLSCISSORARRAYVPROC ;
typedef  scalar_t__ PFNGLRELEASESHADERCOMPILERPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX4X3DVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX4X2DVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX4FVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX4DVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX3X4DVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX3FVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX3DVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX2X4DVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX2FVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX2DVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM4UIVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM4UIPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM4IVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM4IPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM4FVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM4FPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM4DVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM4DPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM3UIVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM3UIPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM3IVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM3IPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM3FVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM3FPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM3DVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM3DPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM2UIVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM2UIPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM2IVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM2IPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM2FVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM2FPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM2DVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM2DPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM1UIVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM1UIPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM1IVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM1IPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM1FVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM1FPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM1DVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM1DPROC ;
typedef  scalar_t__ PFNGLPROGRAMPARAMETERIPROC ;
typedef  scalar_t__ PFNGLPROGRAMBINARYPROC ;
typedef  scalar_t__ PFNGLISPROGRAMPIPELINEPROC ;
typedef  scalar_t__ PFNGLGETVERTEXATTRIBLDVPROC ;
typedef  scalar_t__ PFNGLGETSHADERPRECISIONFORMATPROC ;
typedef  scalar_t__ PFNGLGETPROGRAMPIPELINEIVPROC ;
typedef  scalar_t__ PFNGLGETPROGRAMPIPELINEINFOLOGPROC ;
typedef  scalar_t__ PFNGLGETPROGRAMBINARYPROC ;
typedef  scalar_t__ PFNGLGETFLOATI_VPROC ;
typedef  scalar_t__ PFNGLGETDOUBLEI_VPROC ;
typedef  scalar_t__ PFNGLGENPROGRAMPIPELINESPROC ;
typedef  scalar_t__ PFNGLDEPTHRANGEINDEXEDPROC ;
typedef  scalar_t__ PFNGLDEPTHRANGEFPROC ;
typedef  scalar_t__ PFNGLDEPTHRANGEARRAYVPROC ;
typedef  scalar_t__ PFNGLDELETEPROGRAMPIPELINESPROC ;
typedef  scalar_t__ PFNGLCREATESHADERPROGRAMVPROC ;
typedef  scalar_t__ PFNGLCLEARDEPTHFPROC ;
typedef  scalar_t__ PFNGLBINDPROGRAMPIPELINEPROC ;
typedef  scalar_t__ PFNGLACTIVESHADERPROGRAMPROC ;
typedef  scalar_t__ (* GLADloadproc ) (char*) ;

/* Variables and functions */
 int /*<<< orphan*/  GLAD_GL_VERSION_4_1 ; 
 scalar_t__ glad_glActiveShaderProgram ; 
 scalar_t__ glad_glBindProgramPipeline ; 
 scalar_t__ glad_glClearDepthf ; 
 scalar_t__ glad_glCreateShaderProgramv ; 
 scalar_t__ glad_glDeleteProgramPipelines ; 
 scalar_t__ glad_glDepthRangeArrayv ; 
 scalar_t__ glad_glDepthRangeIndexed ; 
 scalar_t__ glad_glDepthRangef ; 
 scalar_t__ glad_glGenProgramPipelines ; 
 scalar_t__ glad_glGetDoublei_v ; 
 scalar_t__ glad_glGetFloati_v ; 
 scalar_t__ glad_glGetProgramBinary ; 
 scalar_t__ glad_glGetProgramPipelineInfoLog ; 
 scalar_t__ glad_glGetProgramPipelineiv ; 
 scalar_t__ glad_glGetShaderPrecisionFormat ; 
 scalar_t__ glad_glGetVertexAttribLdv ; 
 scalar_t__ glad_glIsProgramPipeline ; 
 scalar_t__ glad_glProgramBinary ; 
 scalar_t__ glad_glProgramParameteri ; 
 scalar_t__ glad_glProgramUniform1d ; 
 scalar_t__ glad_glProgramUniform1dv ; 
 scalar_t__ glad_glProgramUniform1f ; 
 scalar_t__ glad_glProgramUniform1fv ; 
 scalar_t__ glad_glProgramUniform1i ; 
 scalar_t__ glad_glProgramUniform1iv ; 
 scalar_t__ glad_glProgramUniform1ui ; 
 scalar_t__ glad_glProgramUniform1uiv ; 
 scalar_t__ glad_glProgramUniform2d ; 
 scalar_t__ glad_glProgramUniform2dv ; 
 scalar_t__ glad_glProgramUniform2f ; 
 scalar_t__ glad_glProgramUniform2fv ; 
 scalar_t__ glad_glProgramUniform2i ; 
 scalar_t__ glad_glProgramUniform2iv ; 
 scalar_t__ glad_glProgramUniform2ui ; 
 scalar_t__ glad_glProgramUniform2uiv ; 
 scalar_t__ glad_glProgramUniform3d ; 
 scalar_t__ glad_glProgramUniform3dv ; 
 scalar_t__ glad_glProgramUniform3f ; 
 scalar_t__ glad_glProgramUniform3fv ; 
 scalar_t__ glad_glProgramUniform3i ; 
 scalar_t__ glad_glProgramUniform3iv ; 
 scalar_t__ glad_glProgramUniform3ui ; 
 scalar_t__ glad_glProgramUniform3uiv ; 
 scalar_t__ glad_glProgramUniform4d ; 
 scalar_t__ glad_glProgramUniform4dv ; 
 scalar_t__ glad_glProgramUniform4f ; 
 scalar_t__ glad_glProgramUniform4fv ; 
 scalar_t__ glad_glProgramUniform4i ; 
 scalar_t__ glad_glProgramUniform4iv ; 
 scalar_t__ glad_glProgramUniform4ui ; 
 scalar_t__ glad_glProgramUniform4uiv ; 
 scalar_t__ glad_glProgramUniformMatrix2dv ; 
 scalar_t__ glad_glProgramUniformMatrix2fv ; 
 scalar_t__ glad_glProgramUniformMatrix2x3dv ; 
 scalar_t__ glad_glProgramUniformMatrix2x3fv ; 
 scalar_t__ glad_glProgramUniformMatrix2x4dv ; 
 scalar_t__ glad_glProgramUniformMatrix2x4fv ; 
 scalar_t__ glad_glProgramUniformMatrix3dv ; 
 scalar_t__ glad_glProgramUniformMatrix3fv ; 
 scalar_t__ glad_glProgramUniformMatrix3x2dv ; 
 scalar_t__ glad_glProgramUniformMatrix3x2fv ; 
 scalar_t__ glad_glProgramUniformMatrix3x4dv ; 
 scalar_t__ glad_glProgramUniformMatrix3x4fv ; 
 scalar_t__ glad_glProgramUniformMatrix4dv ; 
 scalar_t__ glad_glProgramUniformMatrix4fv ; 
 scalar_t__ glad_glProgramUniformMatrix4x2dv ; 
 scalar_t__ glad_glProgramUniformMatrix4x2fv ; 
 scalar_t__ glad_glProgramUniformMatrix4x3dv ; 
 scalar_t__ glad_glProgramUniformMatrix4x3fv ; 
 scalar_t__ glad_glReleaseShaderCompiler ; 
 scalar_t__ glad_glScissorArrayv ; 
 scalar_t__ glad_glScissorIndexed ; 
 scalar_t__ glad_glScissorIndexedv ; 
 scalar_t__ glad_glShaderBinary ; 
 scalar_t__ glad_glUseProgramStages ; 
 scalar_t__ glad_glValidateProgramPipeline ; 
 scalar_t__ glad_glVertexAttribL1d ; 
 scalar_t__ glad_glVertexAttribL1dv ; 
 scalar_t__ glad_glVertexAttribL2d ; 
 scalar_t__ glad_glVertexAttribL2dv ; 
 scalar_t__ glad_glVertexAttribL3d ; 
 scalar_t__ glad_glVertexAttribL3dv ; 
 scalar_t__ glad_glVertexAttribL4d ; 
 scalar_t__ glad_glVertexAttribL4dv ; 
 scalar_t__ glad_glVertexAttribLPointer ; 
 scalar_t__ glad_glViewportArrayv ; 
 scalar_t__ glad_glViewportIndexedf ; 
 scalar_t__ glad_glViewportIndexedfv ; 

__attribute__((used)) static void load_GL_VERSION_4_1(GLADloadproc load) {
	if(!GLAD_GL_VERSION_4_1) return;
	glad_glReleaseShaderCompiler = (PFNGLRELEASESHADERCOMPILERPROC)load("glReleaseShaderCompiler");
	glad_glShaderBinary = (PFNGLSHADERBINARYPROC)load("glShaderBinary");
	glad_glGetShaderPrecisionFormat = (PFNGLGETSHADERPRECISIONFORMATPROC)load("glGetShaderPrecisionFormat");
	glad_glDepthRangef = (PFNGLDEPTHRANGEFPROC)load("glDepthRangef");
	glad_glClearDepthf = (PFNGLCLEARDEPTHFPROC)load("glClearDepthf");
	glad_glGetProgramBinary = (PFNGLGETPROGRAMBINARYPROC)load("glGetProgramBinary");
	glad_glProgramBinary = (PFNGLPROGRAMBINARYPROC)load("glProgramBinary");
	glad_glProgramParameteri = (PFNGLPROGRAMPARAMETERIPROC)load("glProgramParameteri");
	glad_glUseProgramStages = (PFNGLUSEPROGRAMSTAGESPROC)load("glUseProgramStages");
	glad_glActiveShaderProgram = (PFNGLACTIVESHADERPROGRAMPROC)load("glActiveShaderProgram");
	glad_glCreateShaderProgramv = (PFNGLCREATESHADERPROGRAMVPROC)load("glCreateShaderProgramv");
	glad_glBindProgramPipeline = (PFNGLBINDPROGRAMPIPELINEPROC)load("glBindProgramPipeline");
	glad_glDeleteProgramPipelines = (PFNGLDELETEPROGRAMPIPELINESPROC)load("glDeleteProgramPipelines");
	glad_glGenProgramPipelines = (PFNGLGENPROGRAMPIPELINESPROC)load("glGenProgramPipelines");
	glad_glIsProgramPipeline = (PFNGLISPROGRAMPIPELINEPROC)load("glIsProgramPipeline");
	glad_glGetProgramPipelineiv = (PFNGLGETPROGRAMPIPELINEIVPROC)load("glGetProgramPipelineiv");
	glad_glProgramUniform1i = (PFNGLPROGRAMUNIFORM1IPROC)load("glProgramUniform1i");
	glad_glProgramUniform1iv = (PFNGLPROGRAMUNIFORM1IVPROC)load("glProgramUniform1iv");
	glad_glProgramUniform1f = (PFNGLPROGRAMUNIFORM1FPROC)load("glProgramUniform1f");
	glad_glProgramUniform1fv = (PFNGLPROGRAMUNIFORM1FVPROC)load("glProgramUniform1fv");
	glad_glProgramUniform1d = (PFNGLPROGRAMUNIFORM1DPROC)load("glProgramUniform1d");
	glad_glProgramUniform1dv = (PFNGLPROGRAMUNIFORM1DVPROC)load("glProgramUniform1dv");
	glad_glProgramUniform1ui = (PFNGLPROGRAMUNIFORM1UIPROC)load("glProgramUniform1ui");
	glad_glProgramUniform1uiv = (PFNGLPROGRAMUNIFORM1UIVPROC)load("glProgramUniform1uiv");
	glad_glProgramUniform2i = (PFNGLPROGRAMUNIFORM2IPROC)load("glProgramUniform2i");
	glad_glProgramUniform2iv = (PFNGLPROGRAMUNIFORM2IVPROC)load("glProgramUniform2iv");
	glad_glProgramUniform2f = (PFNGLPROGRAMUNIFORM2FPROC)load("glProgramUniform2f");
	glad_glProgramUniform2fv = (PFNGLPROGRAMUNIFORM2FVPROC)load("glProgramUniform2fv");
	glad_glProgramUniform2d = (PFNGLPROGRAMUNIFORM2DPROC)load("glProgramUniform2d");
	glad_glProgramUniform2dv = (PFNGLPROGRAMUNIFORM2DVPROC)load("glProgramUniform2dv");
	glad_glProgramUniform2ui = (PFNGLPROGRAMUNIFORM2UIPROC)load("glProgramUniform2ui");
	glad_glProgramUniform2uiv = (PFNGLPROGRAMUNIFORM2UIVPROC)load("glProgramUniform2uiv");
	glad_glProgramUniform3i = (PFNGLPROGRAMUNIFORM3IPROC)load("glProgramUniform3i");
	glad_glProgramUniform3iv = (PFNGLPROGRAMUNIFORM3IVPROC)load("glProgramUniform3iv");
	glad_glProgramUniform3f = (PFNGLPROGRAMUNIFORM3FPROC)load("glProgramUniform3f");
	glad_glProgramUniform3fv = (PFNGLPROGRAMUNIFORM3FVPROC)load("glProgramUniform3fv");
	glad_glProgramUniform3d = (PFNGLPROGRAMUNIFORM3DPROC)load("glProgramUniform3d");
	glad_glProgramUniform3dv = (PFNGLPROGRAMUNIFORM3DVPROC)load("glProgramUniform3dv");
	glad_glProgramUniform3ui = (PFNGLPROGRAMUNIFORM3UIPROC)load("glProgramUniform3ui");
	glad_glProgramUniform3uiv = (PFNGLPROGRAMUNIFORM3UIVPROC)load("glProgramUniform3uiv");
	glad_glProgramUniform4i = (PFNGLPROGRAMUNIFORM4IPROC)load("glProgramUniform4i");
	glad_glProgramUniform4iv = (PFNGLPROGRAMUNIFORM4IVPROC)load("glProgramUniform4iv");
	glad_glProgramUniform4f = (PFNGLPROGRAMUNIFORM4FPROC)load("glProgramUniform4f");
	glad_glProgramUniform4fv = (PFNGLPROGRAMUNIFORM4FVPROC)load("glProgramUniform4fv");
	glad_glProgramUniform4d = (PFNGLPROGRAMUNIFORM4DPROC)load("glProgramUniform4d");
	glad_glProgramUniform4dv = (PFNGLPROGRAMUNIFORM4DVPROC)load("glProgramUniform4dv");
	glad_glProgramUniform4ui = (PFNGLPROGRAMUNIFORM4UIPROC)load("glProgramUniform4ui");
	glad_glProgramUniform4uiv = (PFNGLPROGRAMUNIFORM4UIVPROC)load("glProgramUniform4uiv");
	glad_glProgramUniformMatrix2fv = (PFNGLPROGRAMUNIFORMMATRIX2FVPROC)load("glProgramUniformMatrix2fv");
	glad_glProgramUniformMatrix3fv = (PFNGLPROGRAMUNIFORMMATRIX3FVPROC)load("glProgramUniformMatrix3fv");
	glad_glProgramUniformMatrix4fv = (PFNGLPROGRAMUNIFORMMATRIX4FVPROC)load("glProgramUniformMatrix4fv");
	glad_glProgramUniformMatrix2dv = (PFNGLPROGRAMUNIFORMMATRIX2DVPROC)load("glProgramUniformMatrix2dv");
	glad_glProgramUniformMatrix3dv = (PFNGLPROGRAMUNIFORMMATRIX3DVPROC)load("glProgramUniformMatrix3dv");
	glad_glProgramUniformMatrix4dv = (PFNGLPROGRAMUNIFORMMATRIX4DVPROC)load("glProgramUniformMatrix4dv");
	glad_glProgramUniformMatrix2x3fv = (PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC)load("glProgramUniformMatrix2x3fv");
	glad_glProgramUniformMatrix3x2fv = (PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC)load("glProgramUniformMatrix3x2fv");
	glad_glProgramUniformMatrix2x4fv = (PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC)load("glProgramUniformMatrix2x4fv");
	glad_glProgramUniformMatrix4x2fv = (PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC)load("glProgramUniformMatrix4x2fv");
	glad_glProgramUniformMatrix3x4fv = (PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC)load("glProgramUniformMatrix3x4fv");
	glad_glProgramUniformMatrix4x3fv = (PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC)load("glProgramUniformMatrix4x3fv");
	glad_glProgramUniformMatrix2x3dv = (PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC)load("glProgramUniformMatrix2x3dv");
	glad_glProgramUniformMatrix3x2dv = (PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC)load("glProgramUniformMatrix3x2dv");
	glad_glProgramUniformMatrix2x4dv = (PFNGLPROGRAMUNIFORMMATRIX2X4DVPROC)load("glProgramUniformMatrix2x4dv");
	glad_glProgramUniformMatrix4x2dv = (PFNGLPROGRAMUNIFORMMATRIX4X2DVPROC)load("glProgramUniformMatrix4x2dv");
	glad_glProgramUniformMatrix3x4dv = (PFNGLPROGRAMUNIFORMMATRIX3X4DVPROC)load("glProgramUniformMatrix3x4dv");
	glad_glProgramUniformMatrix4x3dv = (PFNGLPROGRAMUNIFORMMATRIX4X3DVPROC)load("glProgramUniformMatrix4x3dv");
	glad_glValidateProgramPipeline = (PFNGLVALIDATEPROGRAMPIPELINEPROC)load("glValidateProgramPipeline");
	glad_glGetProgramPipelineInfoLog = (PFNGLGETPROGRAMPIPELINEINFOLOGPROC)load("glGetProgramPipelineInfoLog");
	glad_glVertexAttribL1d = (PFNGLVERTEXATTRIBL1DPROC)load("glVertexAttribL1d");
	glad_glVertexAttribL2d = (PFNGLVERTEXATTRIBL2DPROC)load("glVertexAttribL2d");
	glad_glVertexAttribL3d = (PFNGLVERTEXATTRIBL3DPROC)load("glVertexAttribL3d");
	glad_glVertexAttribL4d = (PFNGLVERTEXATTRIBL4DPROC)load("glVertexAttribL4d");
	glad_glVertexAttribL1dv = (PFNGLVERTEXATTRIBL1DVPROC)load("glVertexAttribL1dv");
	glad_glVertexAttribL2dv = (PFNGLVERTEXATTRIBL2DVPROC)load("glVertexAttribL2dv");
	glad_glVertexAttribL3dv = (PFNGLVERTEXATTRIBL3DVPROC)load("glVertexAttribL3dv");
	glad_glVertexAttribL4dv = (PFNGLVERTEXATTRIBL4DVPROC)load("glVertexAttribL4dv");
	glad_glVertexAttribLPointer = (PFNGLVERTEXATTRIBLPOINTERPROC)load("glVertexAttribLPointer");
	glad_glGetVertexAttribLdv = (PFNGLGETVERTEXATTRIBLDVPROC)load("glGetVertexAttribLdv");
	glad_glViewportArrayv = (PFNGLVIEWPORTARRAYVPROC)load("glViewportArrayv");
	glad_glViewportIndexedf = (PFNGLVIEWPORTINDEXEDFPROC)load("glViewportIndexedf");
	glad_glViewportIndexedfv = (PFNGLVIEWPORTINDEXEDFVPROC)load("glViewportIndexedfv");
	glad_glScissorArrayv = (PFNGLSCISSORARRAYVPROC)load("glScissorArrayv");
	glad_glScissorIndexed = (PFNGLSCISSORINDEXEDPROC)load("glScissorIndexed");
	glad_glScissorIndexedv = (PFNGLSCISSORINDEXEDVPROC)load("glScissorIndexedv");
	glad_glDepthRangeArrayv = (PFNGLDEPTHRANGEARRAYVPROC)load("glDepthRangeArrayv");
	glad_glDepthRangeIndexed = (PFNGLDEPTHRANGEINDEXEDPROC)load("glDepthRangeIndexed");
	glad_glGetFloati_v = (PFNGLGETFLOATI_VPROC)load("glGetFloati_v");
	glad_glGetDoublei_v = (PFNGLGETDOUBLEI_VPROC)load("glGetDoublei_v");
}