#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  scalar_t__ PFNGLVERTEXARRAYVERTEXOFFSETEXTPROC ;
typedef  scalar_t__ PFNGLVERTEXARRAYVERTEXBINDINGDIVISOREXTPROC ;
typedef  scalar_t__ PFNGLVERTEXARRAYVERTEXATTRIBOFFSETEXTPROC ;
typedef  scalar_t__ PFNGLVERTEXARRAYVERTEXATTRIBLOFFSETEXTPROC ;
typedef  scalar_t__ PFNGLVERTEXARRAYVERTEXATTRIBLFORMATEXTPROC ;
typedef  scalar_t__ PFNGLVERTEXARRAYVERTEXATTRIBIOFFSETEXTPROC ;
typedef  scalar_t__ PFNGLVERTEXARRAYVERTEXATTRIBIFORMATEXTPROC ;
typedef  scalar_t__ PFNGLVERTEXARRAYVERTEXATTRIBFORMATEXTPROC ;
typedef  scalar_t__ PFNGLVERTEXARRAYVERTEXATTRIBDIVISOREXTPROC ;
typedef  scalar_t__ PFNGLVERTEXARRAYVERTEXATTRIBBINDINGEXTPROC ;
typedef  scalar_t__ PFNGLVERTEXARRAYTEXCOORDOFFSETEXTPROC ;
typedef  scalar_t__ PFNGLVERTEXARRAYSECONDARYCOLOROFFSETEXTPROC ;
typedef  scalar_t__ PFNGLVERTEXARRAYNORMALOFFSETEXTPROC ;
typedef  scalar_t__ PFNGLVERTEXARRAYMULTITEXCOORDOFFSETEXTPROC ;
typedef  scalar_t__ PFNGLVERTEXARRAYINDEXOFFSETEXTPROC ;
typedef  scalar_t__ PFNGLVERTEXARRAYFOGCOORDOFFSETEXTPROC ;
typedef  scalar_t__ PFNGLVERTEXARRAYEDGEFLAGOFFSETEXTPROC ;
typedef  scalar_t__ PFNGLVERTEXARRAYCOLOROFFSETEXTPROC ;
typedef  scalar_t__ PFNGLVERTEXARRAYBINDVERTEXBUFFEREXTPROC ;
typedef  scalar_t__ PFNGLUNMAPNAMEDBUFFEREXTPROC ;
typedef  scalar_t__ PFNGLTEXTURESUBIMAGE3DEXTPROC ;
typedef  scalar_t__ PFNGLTEXTURESUBIMAGE2DEXTPROC ;
typedef  scalar_t__ PFNGLTEXTURESUBIMAGE1DEXTPROC ;
typedef  scalar_t__ PFNGLTEXTURESTORAGE3DMULTISAMPLEEXTPROC ;
typedef  scalar_t__ PFNGLTEXTURESTORAGE3DEXTPROC ;
typedef  scalar_t__ PFNGLTEXTURESTORAGE2DMULTISAMPLEEXTPROC ;
typedef  scalar_t__ PFNGLTEXTURESTORAGE2DEXTPROC ;
typedef  scalar_t__ PFNGLTEXTURESTORAGE1DEXTPROC ;
typedef  scalar_t__ PFNGLTEXTURERENDERBUFFEREXTPROC ;
typedef  scalar_t__ PFNGLTEXTUREPARAMETERIVEXTPROC ;
typedef  scalar_t__ PFNGLTEXTUREPARAMETERIUIVEXTPROC ;
typedef  scalar_t__ PFNGLTEXTUREPARAMETERIIVEXTPROC ;
typedef  scalar_t__ PFNGLTEXTUREPARAMETERIEXTPROC ;
typedef  scalar_t__ PFNGLTEXTUREPARAMETERFVEXTPROC ;
typedef  scalar_t__ PFNGLTEXTUREPARAMETERFEXTPROC ;
typedef  scalar_t__ PFNGLTEXTUREPAGECOMMITMENTEXTPROC ;
typedef  scalar_t__ PFNGLTEXTUREIMAGE3DEXTPROC ;
typedef  scalar_t__ PFNGLTEXTUREIMAGE2DEXTPROC ;
typedef  scalar_t__ PFNGLTEXTUREIMAGE1DEXTPROC ;
typedef  scalar_t__ PFNGLTEXTUREBUFFERRANGEEXTPROC ;
typedef  scalar_t__ PFNGLTEXTUREBUFFEREXTPROC ;
typedef  scalar_t__ PFNGLPUSHCLIENTATTRIBDEFAULTEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX4X3FVEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX4X3DVEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX4X2FVEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX4X2DVEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX4FVEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX4DVEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX3X4FVEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX3X4DVEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX3X2FVEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX3X2DVEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX3FVEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX3DVEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX2X4FVEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX2X4DVEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX2X3FVEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX2X3DVEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX2FVEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX2DVEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM4UIVEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM4UIEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM4IVEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM4IEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM4FVEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM4FEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM4DVEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM4DEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM3UIVEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM3UIEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM3IVEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM3IEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM3FVEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM3FEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM3DVEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM3DEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM2UIVEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM2UIEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM2IVEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM2IEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM2FVEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM2FEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM2DVEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM2DEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM1UIVEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM1UIEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM1IVEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM1IEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM1FVEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM1FEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM1DVEXTPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM1DEXTPROC ;
typedef  scalar_t__ PFNGLNAMEDRENDERBUFFERSTORAGEMULTISAMPLEEXTPROC ;
typedef  scalar_t__ PFNGLNAMEDRENDERBUFFERSTORAGEMULTISAMPLECOVERAGEEXTPROC ;
typedef  scalar_t__ PFNGLNAMEDRENDERBUFFERSTORAGEEXTPROC ;
typedef  scalar_t__ PFNGLNAMEDPROGRAMSTRINGEXTPROC ;
typedef  scalar_t__ PFNGLNAMEDPROGRAMLOCALPARAMETERSI4UIVEXTPROC ;
typedef  scalar_t__ PFNGLNAMEDPROGRAMLOCALPARAMETERSI4IVEXTPROC ;
typedef  scalar_t__ PFNGLNAMEDPROGRAMLOCALPARAMETERS4FVEXTPROC ;
typedef  scalar_t__ PFNGLNAMEDPROGRAMLOCALPARAMETERI4UIVEXTPROC ;
typedef  scalar_t__ PFNGLNAMEDPROGRAMLOCALPARAMETERI4UIEXTPROC ;
typedef  scalar_t__ PFNGLNAMEDPROGRAMLOCALPARAMETERI4IVEXTPROC ;
typedef  scalar_t__ PFNGLNAMEDPROGRAMLOCALPARAMETERI4IEXTPROC ;
typedef  scalar_t__ PFNGLNAMEDPROGRAMLOCALPARAMETER4FVEXTPROC ;
typedef  scalar_t__ PFNGLNAMEDPROGRAMLOCALPARAMETER4FEXTPROC ;
typedef  scalar_t__ PFNGLNAMEDPROGRAMLOCALPARAMETER4DVEXTPROC ;
typedef  scalar_t__ PFNGLNAMEDPROGRAMLOCALPARAMETER4DEXTPROC ;
typedef  scalar_t__ PFNGLNAMEDFRAMEBUFFERTEXTURELAYEREXTPROC ;
typedef  scalar_t__ PFNGLNAMEDFRAMEBUFFERTEXTUREFACEEXTPROC ;
typedef  scalar_t__ PFNGLNAMEDFRAMEBUFFERTEXTUREEXTPROC ;
typedef  scalar_t__ PFNGLNAMEDFRAMEBUFFERTEXTURE3DEXTPROC ;
typedef  scalar_t__ PFNGLNAMEDFRAMEBUFFERTEXTURE2DEXTPROC ;
typedef  scalar_t__ PFNGLNAMEDFRAMEBUFFERTEXTURE1DEXTPROC ;
typedef  scalar_t__ PFNGLNAMEDFRAMEBUFFERRENDERBUFFEREXTPROC ;
typedef  scalar_t__ PFNGLNAMEDFRAMEBUFFERPARAMETERIEXTPROC ;
typedef  scalar_t__ PFNGLNAMEDCOPYBUFFERSUBDATAEXTPROC ;
typedef  scalar_t__ PFNGLNAMEDBUFFERSUBDATAEXTPROC ;
typedef  scalar_t__ PFNGLNAMEDBUFFERSTORAGEEXTPROC ;
typedef  scalar_t__ PFNGLNAMEDBUFFERDATAEXTPROC ;
typedef  scalar_t__ PFNGLMULTITEXSUBIMAGE3DEXTPROC ;
typedef  scalar_t__ PFNGLMULTITEXSUBIMAGE2DEXTPROC ;
typedef  scalar_t__ PFNGLMULTITEXSUBIMAGE1DEXTPROC ;
typedef  scalar_t__ PFNGLMULTITEXRENDERBUFFEREXTPROC ;
typedef  scalar_t__ PFNGLMULTITEXPARAMETERIVEXTPROC ;
typedef  scalar_t__ PFNGLMULTITEXPARAMETERIUIVEXTPROC ;
typedef  scalar_t__ PFNGLMULTITEXPARAMETERIIVEXTPROC ;
typedef  scalar_t__ PFNGLMULTITEXPARAMETERIEXTPROC ;
typedef  scalar_t__ PFNGLMULTITEXPARAMETERFVEXTPROC ;
typedef  scalar_t__ PFNGLMULTITEXPARAMETERFEXTPROC ;
typedef  scalar_t__ PFNGLMULTITEXIMAGE3DEXTPROC ;
typedef  scalar_t__ PFNGLMULTITEXIMAGE2DEXTPROC ;
typedef  scalar_t__ PFNGLMULTITEXIMAGE1DEXTPROC ;
typedef  scalar_t__ PFNGLMULTITEXGENIVEXTPROC ;
typedef  scalar_t__ PFNGLMULTITEXGENIEXTPROC ;
typedef  scalar_t__ PFNGLMULTITEXGENFVEXTPROC ;
typedef  scalar_t__ PFNGLMULTITEXGENFEXTPROC ;
typedef  scalar_t__ PFNGLMULTITEXGENDVEXTPROC ;
typedef  scalar_t__ PFNGLMULTITEXGENDEXTPROC ;
typedef  scalar_t__ PFNGLMULTITEXENVIVEXTPROC ;
typedef  scalar_t__ PFNGLMULTITEXENVIEXTPROC ;
typedef  scalar_t__ PFNGLMULTITEXENVFVEXTPROC ;
typedef  scalar_t__ PFNGLMULTITEXENVFEXTPROC ;
typedef  scalar_t__ PFNGLMULTITEXCOORDPOINTEREXTPROC ;
typedef  scalar_t__ PFNGLMULTITEXBUFFEREXTPROC ;
typedef  scalar_t__ PFNGLMATRIXTRANSLATEFEXTPROC ;
typedef  scalar_t__ PFNGLMATRIXTRANSLATEDEXTPROC ;
typedef  scalar_t__ PFNGLMATRIXSCALEFEXTPROC ;
typedef  scalar_t__ PFNGLMATRIXSCALEDEXTPROC ;
typedef  scalar_t__ PFNGLMATRIXROTATEFEXTPROC ;
typedef  scalar_t__ PFNGLMATRIXROTATEDEXTPROC ;
typedef  scalar_t__ PFNGLMATRIXPUSHEXTPROC ;
typedef  scalar_t__ PFNGLMATRIXPOPEXTPROC ;
typedef  scalar_t__ PFNGLMATRIXORTHOEXTPROC ;
typedef  scalar_t__ PFNGLMATRIXMULTTRANSPOSEFEXTPROC ;
typedef  scalar_t__ PFNGLMATRIXMULTTRANSPOSEDEXTPROC ;
typedef  scalar_t__ PFNGLMATRIXMULTFEXTPROC ;
typedef  scalar_t__ PFNGLMATRIXMULTDEXTPROC ;
typedef  scalar_t__ PFNGLMATRIXLOADTRANSPOSEFEXTPROC ;
typedef  scalar_t__ PFNGLMATRIXLOADTRANSPOSEDEXTPROC ;
typedef  scalar_t__ PFNGLMATRIXLOADIDENTITYEXTPROC ;
typedef  scalar_t__ PFNGLMATRIXLOADFEXTPROC ;
typedef  scalar_t__ PFNGLMATRIXLOADDEXTPROC ;
typedef  scalar_t__ PFNGLMATRIXFRUSTUMEXTPROC ;
typedef  scalar_t__ PFNGLMAPNAMEDBUFFERRANGEEXTPROC ;
typedef  scalar_t__ PFNGLMAPNAMEDBUFFEREXTPROC ;
typedef  scalar_t__ PFNGLISENABLEDINDEXEDEXTPROC ;
typedef  scalar_t__ PFNGLGETVERTEXARRAYPOINTERVEXTPROC ;
typedef  scalar_t__ PFNGLGETVERTEXARRAYPOINTERI_VEXTPROC ;
typedef  scalar_t__ PFNGLGETVERTEXARRAYINTEGERVEXTPROC ;
typedef  scalar_t__ PFNGLGETVERTEXARRAYINTEGERI_VEXTPROC ;
typedef  scalar_t__ PFNGLGETTEXTUREPARAMETERIVEXTPROC ;
typedef  scalar_t__ PFNGLGETTEXTUREPARAMETERIUIVEXTPROC ;
typedef  scalar_t__ PFNGLGETTEXTUREPARAMETERIIVEXTPROC ;
typedef  scalar_t__ PFNGLGETTEXTUREPARAMETERFVEXTPROC ;
typedef  scalar_t__ PFNGLGETTEXTURELEVELPARAMETERIVEXTPROC ;
typedef  scalar_t__ PFNGLGETTEXTURELEVELPARAMETERFVEXTPROC ;
typedef  scalar_t__ PFNGLGETTEXTUREIMAGEEXTPROC ;
typedef  scalar_t__ PFNGLGETPOINTERI_VEXTPROC ;
typedef  scalar_t__ PFNGLGETPOINTERINDEXEDVEXTPROC ;
typedef  scalar_t__ PFNGLGETNAMEDRENDERBUFFERPARAMETERIVEXTPROC ;
typedef  scalar_t__ PFNGLGETNAMEDPROGRAMSTRINGEXTPROC ;
typedef  scalar_t__ PFNGLGETNAMEDPROGRAMLOCALPARAMETERIUIVEXTPROC ;
typedef  scalar_t__ PFNGLGETNAMEDPROGRAMLOCALPARAMETERIIVEXTPROC ;
typedef  scalar_t__ PFNGLGETNAMEDPROGRAMLOCALPARAMETERFVEXTPROC ;
typedef  scalar_t__ PFNGLGETNAMEDPROGRAMLOCALPARAMETERDVEXTPROC ;
typedef  scalar_t__ PFNGLGETNAMEDPROGRAMIVEXTPROC ;
typedef  scalar_t__ PFNGLGETNAMEDFRAMEBUFFERPARAMETERIVEXTPROC ;
typedef  scalar_t__ PFNGLGETNAMEDFRAMEBUFFERATTACHMENTPARAMETERIVEXTPROC ;
typedef  scalar_t__ PFNGLGETNAMEDBUFFERSUBDATAEXTPROC ;
typedef  scalar_t__ PFNGLGETNAMEDBUFFERPOINTERVEXTPROC ;
typedef  scalar_t__ PFNGLGETNAMEDBUFFERPARAMETERIVEXTPROC ;
typedef  scalar_t__ PFNGLGETMULTITEXPARAMETERIVEXTPROC ;
typedef  scalar_t__ PFNGLGETMULTITEXPARAMETERIUIVEXTPROC ;
typedef  scalar_t__ PFNGLGETMULTITEXPARAMETERIIVEXTPROC ;
typedef  scalar_t__ PFNGLGETMULTITEXPARAMETERFVEXTPROC ;
typedef  scalar_t__ PFNGLGETMULTITEXLEVELPARAMETERIVEXTPROC ;
typedef  scalar_t__ PFNGLGETMULTITEXLEVELPARAMETERFVEXTPROC ;
typedef  scalar_t__ PFNGLGETMULTITEXIMAGEEXTPROC ;
typedef  scalar_t__ PFNGLGETMULTITEXGENIVEXTPROC ;
typedef  scalar_t__ PFNGLGETMULTITEXGENFVEXTPROC ;
typedef  scalar_t__ PFNGLGETMULTITEXGENDVEXTPROC ;
typedef  scalar_t__ PFNGLGETMULTITEXENVIVEXTPROC ;
typedef  scalar_t__ PFNGLGETMULTITEXENVFVEXTPROC ;
typedef  scalar_t__ PFNGLGETINTEGERINDEXEDVEXTPROC ;
typedef  scalar_t__ PFNGLGETFRAMEBUFFERPARAMETERIVEXTPROC ;
typedef  scalar_t__ PFNGLGETFLOATI_VEXTPROC ;
typedef  scalar_t__ PFNGLGETFLOATINDEXEDVEXTPROC ;
typedef  scalar_t__ PFNGLGETDOUBLEI_VEXTPROC ;
typedef  scalar_t__ PFNGLGETDOUBLEINDEXEDVEXTPROC ;
typedef  scalar_t__ PFNGLGETCOMPRESSEDTEXTUREIMAGEEXTPROC ;
typedef  scalar_t__ PFNGLGETCOMPRESSEDMULTITEXIMAGEEXTPROC ;
typedef  scalar_t__ PFNGLGETBOOLEANINDEXEDVEXTPROC ;
typedef  scalar_t__ PFNGLGENERATETEXTUREMIPMAPEXTPROC ;
typedef  scalar_t__ PFNGLGENERATEMULTITEXMIPMAPEXTPROC ;
typedef  scalar_t__ PFNGLFRAMEBUFFERREADBUFFEREXTPROC ;
typedef  scalar_t__ PFNGLFRAMEBUFFERDRAWBUFFERSEXTPROC ;
typedef  scalar_t__ PFNGLFRAMEBUFFERDRAWBUFFEREXTPROC ;
typedef  scalar_t__ PFNGLFLUSHMAPPEDNAMEDBUFFERRANGEEXTPROC ;
typedef  scalar_t__ PFNGLENABLEVERTEXARRAYEXTPROC ;
typedef  scalar_t__ PFNGLENABLEVERTEXARRAYATTRIBEXTPROC ;
typedef  scalar_t__ PFNGLENABLEINDEXEDEXTPROC ;
typedef  scalar_t__ PFNGLENABLECLIENTSTATEINDEXEDEXTPROC ;
typedef  scalar_t__ PFNGLENABLECLIENTSTATEIEXTPROC ;
typedef  scalar_t__ PFNGLDISABLEVERTEXARRAYEXTPROC ;
typedef  scalar_t__ PFNGLDISABLEVERTEXARRAYATTRIBEXTPROC ;
typedef  scalar_t__ PFNGLDISABLEINDEXEDEXTPROC ;
typedef  scalar_t__ PFNGLDISABLECLIENTSTATEINDEXEDEXTPROC ;
typedef  scalar_t__ PFNGLDISABLECLIENTSTATEIEXTPROC ;
typedef  scalar_t__ PFNGLCOPYTEXTURESUBIMAGE3DEXTPROC ;
typedef  scalar_t__ PFNGLCOPYTEXTURESUBIMAGE2DEXTPROC ;
typedef  scalar_t__ PFNGLCOPYTEXTURESUBIMAGE1DEXTPROC ;
typedef  scalar_t__ PFNGLCOPYTEXTUREIMAGE2DEXTPROC ;
typedef  scalar_t__ PFNGLCOPYTEXTUREIMAGE1DEXTPROC ;
typedef  scalar_t__ PFNGLCOPYMULTITEXSUBIMAGE3DEXTPROC ;
typedef  scalar_t__ PFNGLCOPYMULTITEXSUBIMAGE2DEXTPROC ;
typedef  scalar_t__ PFNGLCOPYMULTITEXSUBIMAGE1DEXTPROC ;
typedef  scalar_t__ PFNGLCOPYMULTITEXIMAGE2DEXTPROC ;
typedef  scalar_t__ PFNGLCOPYMULTITEXIMAGE1DEXTPROC ;
typedef  scalar_t__ PFNGLCOMPRESSEDTEXTURESUBIMAGE3DEXTPROC ;
typedef  scalar_t__ PFNGLCOMPRESSEDTEXTURESUBIMAGE2DEXTPROC ;
typedef  scalar_t__ PFNGLCOMPRESSEDTEXTURESUBIMAGE1DEXTPROC ;
typedef  scalar_t__ PFNGLCOMPRESSEDTEXTUREIMAGE3DEXTPROC ;
typedef  scalar_t__ PFNGLCOMPRESSEDTEXTUREIMAGE2DEXTPROC ;
typedef  scalar_t__ PFNGLCOMPRESSEDTEXTUREIMAGE1DEXTPROC ;
typedef  scalar_t__ PFNGLCOMPRESSEDMULTITEXSUBIMAGE3DEXTPROC ;
typedef  scalar_t__ PFNGLCOMPRESSEDMULTITEXSUBIMAGE2DEXTPROC ;
typedef  scalar_t__ PFNGLCOMPRESSEDMULTITEXSUBIMAGE1DEXTPROC ;
typedef  scalar_t__ PFNGLCOMPRESSEDMULTITEXIMAGE3DEXTPROC ;
typedef  scalar_t__ PFNGLCOMPRESSEDMULTITEXIMAGE2DEXTPROC ;
typedef  scalar_t__ PFNGLCOMPRESSEDMULTITEXIMAGE1DEXTPROC ;
typedef  scalar_t__ PFNGLCLIENTATTRIBDEFAULTEXTPROC ;
typedef  scalar_t__ PFNGLCLEARNAMEDBUFFERSUBDATAEXTPROC ;
typedef  scalar_t__ PFNGLCLEARNAMEDBUFFERDATAEXTPROC ;
typedef  scalar_t__ PFNGLCHECKNAMEDFRAMEBUFFERSTATUSEXTPROC ;
typedef  scalar_t__ PFNGLBINDMULTITEXTUREEXTPROC ;
typedef  scalar_t__ (* GLADloadproc ) (char*) ;

/* Variables and functions */
 int /*<<< orphan*/  GLAD_GL_EXT_direct_state_access ; 
 scalar_t__ glad_glBindMultiTextureEXT ; 
 scalar_t__ glad_glCheckNamedFramebufferStatusEXT ; 
 scalar_t__ glad_glClearNamedBufferDataEXT ; 
 scalar_t__ glad_glClearNamedBufferSubDataEXT ; 
 scalar_t__ glad_glClientAttribDefaultEXT ; 
 scalar_t__ glad_glCompressedMultiTexImage1DEXT ; 
 scalar_t__ glad_glCompressedMultiTexImage2DEXT ; 
 scalar_t__ glad_glCompressedMultiTexImage3DEXT ; 
 scalar_t__ glad_glCompressedMultiTexSubImage1DEXT ; 
 scalar_t__ glad_glCompressedMultiTexSubImage2DEXT ; 
 scalar_t__ glad_glCompressedMultiTexSubImage3DEXT ; 
 scalar_t__ glad_glCompressedTextureImage1DEXT ; 
 scalar_t__ glad_glCompressedTextureImage2DEXT ; 
 scalar_t__ glad_glCompressedTextureImage3DEXT ; 
 scalar_t__ glad_glCompressedTextureSubImage1DEXT ; 
 scalar_t__ glad_glCompressedTextureSubImage2DEXT ; 
 scalar_t__ glad_glCompressedTextureSubImage3DEXT ; 
 scalar_t__ glad_glCopyMultiTexImage1DEXT ; 
 scalar_t__ glad_glCopyMultiTexImage2DEXT ; 
 scalar_t__ glad_glCopyMultiTexSubImage1DEXT ; 
 scalar_t__ glad_glCopyMultiTexSubImage2DEXT ; 
 scalar_t__ glad_glCopyMultiTexSubImage3DEXT ; 
 scalar_t__ glad_glCopyTextureImage1DEXT ; 
 scalar_t__ glad_glCopyTextureImage2DEXT ; 
 scalar_t__ glad_glCopyTextureSubImage1DEXT ; 
 scalar_t__ glad_glCopyTextureSubImage2DEXT ; 
 scalar_t__ glad_glCopyTextureSubImage3DEXT ; 
 scalar_t__ glad_glDisableClientStateIndexedEXT ; 
 scalar_t__ glad_glDisableClientStateiEXT ; 
 scalar_t__ glad_glDisableIndexedEXT ; 
 scalar_t__ glad_glDisableVertexArrayAttribEXT ; 
 scalar_t__ glad_glDisableVertexArrayEXT ; 
 scalar_t__ glad_glEnableClientStateIndexedEXT ; 
 scalar_t__ glad_glEnableClientStateiEXT ; 
 scalar_t__ glad_glEnableIndexedEXT ; 
 scalar_t__ glad_glEnableVertexArrayAttribEXT ; 
 scalar_t__ glad_glEnableVertexArrayEXT ; 
 scalar_t__ glad_glFlushMappedNamedBufferRangeEXT ; 
 scalar_t__ glad_glFramebufferDrawBufferEXT ; 
 scalar_t__ glad_glFramebufferDrawBuffersEXT ; 
 scalar_t__ glad_glFramebufferReadBufferEXT ; 
 scalar_t__ glad_glGenerateMultiTexMipmapEXT ; 
 scalar_t__ glad_glGenerateTextureMipmapEXT ; 
 scalar_t__ glad_glGetBooleanIndexedvEXT ; 
 scalar_t__ glad_glGetCompressedMultiTexImageEXT ; 
 scalar_t__ glad_glGetCompressedTextureImageEXT ; 
 scalar_t__ glad_glGetDoubleIndexedvEXT ; 
 scalar_t__ glad_glGetDoublei_vEXT ; 
 scalar_t__ glad_glGetFloatIndexedvEXT ; 
 scalar_t__ glad_glGetFloati_vEXT ; 
 scalar_t__ glad_glGetFramebufferParameterivEXT ; 
 scalar_t__ glad_glGetIntegerIndexedvEXT ; 
 scalar_t__ glad_glGetMultiTexEnvfvEXT ; 
 scalar_t__ glad_glGetMultiTexEnvivEXT ; 
 scalar_t__ glad_glGetMultiTexGendvEXT ; 
 scalar_t__ glad_glGetMultiTexGenfvEXT ; 
 scalar_t__ glad_glGetMultiTexGenivEXT ; 
 scalar_t__ glad_glGetMultiTexImageEXT ; 
 scalar_t__ glad_glGetMultiTexLevelParameterfvEXT ; 
 scalar_t__ glad_glGetMultiTexLevelParameterivEXT ; 
 scalar_t__ glad_glGetMultiTexParameterIivEXT ; 
 scalar_t__ glad_glGetMultiTexParameterIuivEXT ; 
 scalar_t__ glad_glGetMultiTexParameterfvEXT ; 
 scalar_t__ glad_glGetMultiTexParameterivEXT ; 
 scalar_t__ glad_glGetNamedBufferParameterivEXT ; 
 scalar_t__ glad_glGetNamedBufferPointervEXT ; 
 scalar_t__ glad_glGetNamedBufferSubDataEXT ; 
 scalar_t__ glad_glGetNamedFramebufferAttachmentParameterivEXT ; 
 scalar_t__ glad_glGetNamedFramebufferParameterivEXT ; 
 scalar_t__ glad_glGetNamedProgramLocalParameterIivEXT ; 
 scalar_t__ glad_glGetNamedProgramLocalParameterIuivEXT ; 
 scalar_t__ glad_glGetNamedProgramLocalParameterdvEXT ; 
 scalar_t__ glad_glGetNamedProgramLocalParameterfvEXT ; 
 scalar_t__ glad_glGetNamedProgramStringEXT ; 
 scalar_t__ glad_glGetNamedProgramivEXT ; 
 scalar_t__ glad_glGetNamedRenderbufferParameterivEXT ; 
 scalar_t__ glad_glGetPointerIndexedvEXT ; 
 scalar_t__ glad_glGetPointeri_vEXT ; 
 scalar_t__ glad_glGetTextureImageEXT ; 
 scalar_t__ glad_glGetTextureLevelParameterfvEXT ; 
 scalar_t__ glad_glGetTextureLevelParameterivEXT ; 
 scalar_t__ glad_glGetTextureParameterIivEXT ; 
 scalar_t__ glad_glGetTextureParameterIuivEXT ; 
 scalar_t__ glad_glGetTextureParameterfvEXT ; 
 scalar_t__ glad_glGetTextureParameterivEXT ; 
 scalar_t__ glad_glGetVertexArrayIntegeri_vEXT ; 
 scalar_t__ glad_glGetVertexArrayIntegervEXT ; 
 scalar_t__ glad_glGetVertexArrayPointeri_vEXT ; 
 scalar_t__ glad_glGetVertexArrayPointervEXT ; 
 scalar_t__ glad_glIsEnabledIndexedEXT ; 
 scalar_t__ glad_glMapNamedBufferEXT ; 
 scalar_t__ glad_glMapNamedBufferRangeEXT ; 
 scalar_t__ glad_glMatrixFrustumEXT ; 
 scalar_t__ glad_glMatrixLoadIdentityEXT ; 
 scalar_t__ glad_glMatrixLoadTransposedEXT ; 
 scalar_t__ glad_glMatrixLoadTransposefEXT ; 
 scalar_t__ glad_glMatrixLoaddEXT ; 
 scalar_t__ glad_glMatrixLoadfEXT ; 
 scalar_t__ glad_glMatrixMultTransposedEXT ; 
 scalar_t__ glad_glMatrixMultTransposefEXT ; 
 scalar_t__ glad_glMatrixMultdEXT ; 
 scalar_t__ glad_glMatrixMultfEXT ; 
 scalar_t__ glad_glMatrixOrthoEXT ; 
 scalar_t__ glad_glMatrixPopEXT ; 
 scalar_t__ glad_glMatrixPushEXT ; 
 scalar_t__ glad_glMatrixRotatedEXT ; 
 scalar_t__ glad_glMatrixRotatefEXT ; 
 scalar_t__ glad_glMatrixScaledEXT ; 
 scalar_t__ glad_glMatrixScalefEXT ; 
 scalar_t__ glad_glMatrixTranslatedEXT ; 
 scalar_t__ glad_glMatrixTranslatefEXT ; 
 scalar_t__ glad_glMultiTexBufferEXT ; 
 scalar_t__ glad_glMultiTexCoordPointerEXT ; 
 scalar_t__ glad_glMultiTexEnvfEXT ; 
 scalar_t__ glad_glMultiTexEnvfvEXT ; 
 scalar_t__ glad_glMultiTexEnviEXT ; 
 scalar_t__ glad_glMultiTexEnvivEXT ; 
 scalar_t__ glad_glMultiTexGendEXT ; 
 scalar_t__ glad_glMultiTexGendvEXT ; 
 scalar_t__ glad_glMultiTexGenfEXT ; 
 scalar_t__ glad_glMultiTexGenfvEXT ; 
 scalar_t__ glad_glMultiTexGeniEXT ; 
 scalar_t__ glad_glMultiTexGenivEXT ; 
 scalar_t__ glad_glMultiTexImage1DEXT ; 
 scalar_t__ glad_glMultiTexImage2DEXT ; 
 scalar_t__ glad_glMultiTexImage3DEXT ; 
 scalar_t__ glad_glMultiTexParameterIivEXT ; 
 scalar_t__ glad_glMultiTexParameterIuivEXT ; 
 scalar_t__ glad_glMultiTexParameterfEXT ; 
 scalar_t__ glad_glMultiTexParameterfvEXT ; 
 scalar_t__ glad_glMultiTexParameteriEXT ; 
 scalar_t__ glad_glMultiTexParameterivEXT ; 
 scalar_t__ glad_glMultiTexRenderbufferEXT ; 
 scalar_t__ glad_glMultiTexSubImage1DEXT ; 
 scalar_t__ glad_glMultiTexSubImage2DEXT ; 
 scalar_t__ glad_glMultiTexSubImage3DEXT ; 
 scalar_t__ glad_glNamedBufferDataEXT ; 
 scalar_t__ glad_glNamedBufferStorageEXT ; 
 scalar_t__ glad_glNamedBufferSubDataEXT ; 
 scalar_t__ glad_glNamedCopyBufferSubDataEXT ; 
 scalar_t__ glad_glNamedFramebufferParameteriEXT ; 
 scalar_t__ glad_glNamedFramebufferRenderbufferEXT ; 
 scalar_t__ glad_glNamedFramebufferTexture1DEXT ; 
 scalar_t__ glad_glNamedFramebufferTexture2DEXT ; 
 scalar_t__ glad_glNamedFramebufferTexture3DEXT ; 
 scalar_t__ glad_glNamedFramebufferTextureEXT ; 
 scalar_t__ glad_glNamedFramebufferTextureFaceEXT ; 
 scalar_t__ glad_glNamedFramebufferTextureLayerEXT ; 
 scalar_t__ glad_glNamedProgramLocalParameter4dEXT ; 
 scalar_t__ glad_glNamedProgramLocalParameter4dvEXT ; 
 scalar_t__ glad_glNamedProgramLocalParameter4fEXT ; 
 scalar_t__ glad_glNamedProgramLocalParameter4fvEXT ; 
 scalar_t__ glad_glNamedProgramLocalParameterI4iEXT ; 
 scalar_t__ glad_glNamedProgramLocalParameterI4ivEXT ; 
 scalar_t__ glad_glNamedProgramLocalParameterI4uiEXT ; 
 scalar_t__ glad_glNamedProgramLocalParameterI4uivEXT ; 
 scalar_t__ glad_glNamedProgramLocalParameters4fvEXT ; 
 scalar_t__ glad_glNamedProgramLocalParametersI4ivEXT ; 
 scalar_t__ glad_glNamedProgramLocalParametersI4uivEXT ; 
 scalar_t__ glad_glNamedProgramStringEXT ; 
 scalar_t__ glad_glNamedRenderbufferStorageEXT ; 
 scalar_t__ glad_glNamedRenderbufferStorageMultisampleCoverageEXT ; 
 scalar_t__ glad_glNamedRenderbufferStorageMultisampleEXT ; 
 scalar_t__ glad_glProgramUniform1dEXT ; 
 scalar_t__ glad_glProgramUniform1dvEXT ; 
 scalar_t__ glad_glProgramUniform1fEXT ; 
 scalar_t__ glad_glProgramUniform1fvEXT ; 
 scalar_t__ glad_glProgramUniform1iEXT ; 
 scalar_t__ glad_glProgramUniform1ivEXT ; 
 scalar_t__ glad_glProgramUniform1uiEXT ; 
 scalar_t__ glad_glProgramUniform1uivEXT ; 
 scalar_t__ glad_glProgramUniform2dEXT ; 
 scalar_t__ glad_glProgramUniform2dvEXT ; 
 scalar_t__ glad_glProgramUniform2fEXT ; 
 scalar_t__ glad_glProgramUniform2fvEXT ; 
 scalar_t__ glad_glProgramUniform2iEXT ; 
 scalar_t__ glad_glProgramUniform2ivEXT ; 
 scalar_t__ glad_glProgramUniform2uiEXT ; 
 scalar_t__ glad_glProgramUniform2uivEXT ; 
 scalar_t__ glad_glProgramUniform3dEXT ; 
 scalar_t__ glad_glProgramUniform3dvEXT ; 
 scalar_t__ glad_glProgramUniform3fEXT ; 
 scalar_t__ glad_glProgramUniform3fvEXT ; 
 scalar_t__ glad_glProgramUniform3iEXT ; 
 scalar_t__ glad_glProgramUniform3ivEXT ; 
 scalar_t__ glad_glProgramUniform3uiEXT ; 
 scalar_t__ glad_glProgramUniform3uivEXT ; 
 scalar_t__ glad_glProgramUniform4dEXT ; 
 scalar_t__ glad_glProgramUniform4dvEXT ; 
 scalar_t__ glad_glProgramUniform4fEXT ; 
 scalar_t__ glad_glProgramUniform4fvEXT ; 
 scalar_t__ glad_glProgramUniform4iEXT ; 
 scalar_t__ glad_glProgramUniform4ivEXT ; 
 scalar_t__ glad_glProgramUniform4uiEXT ; 
 scalar_t__ glad_glProgramUniform4uivEXT ; 
 scalar_t__ glad_glProgramUniformMatrix2dvEXT ; 
 scalar_t__ glad_glProgramUniformMatrix2fvEXT ; 
 scalar_t__ glad_glProgramUniformMatrix2x3dvEXT ; 
 scalar_t__ glad_glProgramUniformMatrix2x3fvEXT ; 
 scalar_t__ glad_glProgramUniformMatrix2x4dvEXT ; 
 scalar_t__ glad_glProgramUniformMatrix2x4fvEXT ; 
 scalar_t__ glad_glProgramUniformMatrix3dvEXT ; 
 scalar_t__ glad_glProgramUniformMatrix3fvEXT ; 
 scalar_t__ glad_glProgramUniformMatrix3x2dvEXT ; 
 scalar_t__ glad_glProgramUniformMatrix3x2fvEXT ; 
 scalar_t__ glad_glProgramUniformMatrix3x4dvEXT ; 
 scalar_t__ glad_glProgramUniformMatrix3x4fvEXT ; 
 scalar_t__ glad_glProgramUniformMatrix4dvEXT ; 
 scalar_t__ glad_glProgramUniformMatrix4fvEXT ; 
 scalar_t__ glad_glProgramUniformMatrix4x2dvEXT ; 
 scalar_t__ glad_glProgramUniformMatrix4x2fvEXT ; 
 scalar_t__ glad_glProgramUniformMatrix4x3dvEXT ; 
 scalar_t__ glad_glProgramUniformMatrix4x3fvEXT ; 
 scalar_t__ glad_glPushClientAttribDefaultEXT ; 
 scalar_t__ glad_glTextureBufferEXT ; 
 scalar_t__ glad_glTextureBufferRangeEXT ; 
 scalar_t__ glad_glTextureImage1DEXT ; 
 scalar_t__ glad_glTextureImage2DEXT ; 
 scalar_t__ glad_glTextureImage3DEXT ; 
 scalar_t__ glad_glTexturePageCommitmentEXT ; 
 scalar_t__ glad_glTextureParameterIivEXT ; 
 scalar_t__ glad_glTextureParameterIuivEXT ; 
 scalar_t__ glad_glTextureParameterfEXT ; 
 scalar_t__ glad_glTextureParameterfvEXT ; 
 scalar_t__ glad_glTextureParameteriEXT ; 
 scalar_t__ glad_glTextureParameterivEXT ; 
 scalar_t__ glad_glTextureRenderbufferEXT ; 
 scalar_t__ glad_glTextureStorage1DEXT ; 
 scalar_t__ glad_glTextureStorage2DEXT ; 
 scalar_t__ glad_glTextureStorage2DMultisampleEXT ; 
 scalar_t__ glad_glTextureStorage3DEXT ; 
 scalar_t__ glad_glTextureStorage3DMultisampleEXT ; 
 scalar_t__ glad_glTextureSubImage1DEXT ; 
 scalar_t__ glad_glTextureSubImage2DEXT ; 
 scalar_t__ glad_glTextureSubImage3DEXT ; 
 scalar_t__ glad_glUnmapNamedBufferEXT ; 
 scalar_t__ glad_glVertexArrayBindVertexBufferEXT ; 
 scalar_t__ glad_glVertexArrayColorOffsetEXT ; 
 scalar_t__ glad_glVertexArrayEdgeFlagOffsetEXT ; 
 scalar_t__ glad_glVertexArrayFogCoordOffsetEXT ; 
 scalar_t__ glad_glVertexArrayIndexOffsetEXT ; 
 scalar_t__ glad_glVertexArrayMultiTexCoordOffsetEXT ; 
 scalar_t__ glad_glVertexArrayNormalOffsetEXT ; 
 scalar_t__ glad_glVertexArraySecondaryColorOffsetEXT ; 
 scalar_t__ glad_glVertexArrayTexCoordOffsetEXT ; 
 scalar_t__ glad_glVertexArrayVertexAttribBindingEXT ; 
 scalar_t__ glad_glVertexArrayVertexAttribDivisorEXT ; 
 scalar_t__ glad_glVertexArrayVertexAttribFormatEXT ; 
 scalar_t__ glad_glVertexArrayVertexAttribIFormatEXT ; 
 scalar_t__ glad_glVertexArrayVertexAttribIOffsetEXT ; 
 scalar_t__ glad_glVertexArrayVertexAttribLFormatEXT ; 
 scalar_t__ glad_glVertexArrayVertexAttribLOffsetEXT ; 
 scalar_t__ glad_glVertexArrayVertexAttribOffsetEXT ; 
 scalar_t__ glad_glVertexArrayVertexBindingDivisorEXT ; 
 scalar_t__ glad_glVertexArrayVertexOffsetEXT ; 

__attribute__((used)) static void load_GL_EXT_direct_state_access(GLADloadproc load) {
	if(!GLAD_GL_EXT_direct_state_access) return;
	glad_glMatrixLoadfEXT = (PFNGLMATRIXLOADFEXTPROC)load("glMatrixLoadfEXT");
	glad_glMatrixLoaddEXT = (PFNGLMATRIXLOADDEXTPROC)load("glMatrixLoaddEXT");
	glad_glMatrixMultfEXT = (PFNGLMATRIXMULTFEXTPROC)load("glMatrixMultfEXT");
	glad_glMatrixMultdEXT = (PFNGLMATRIXMULTDEXTPROC)load("glMatrixMultdEXT");
	glad_glMatrixLoadIdentityEXT = (PFNGLMATRIXLOADIDENTITYEXTPROC)load("glMatrixLoadIdentityEXT");
	glad_glMatrixRotatefEXT = (PFNGLMATRIXROTATEFEXTPROC)load("glMatrixRotatefEXT");
	glad_glMatrixRotatedEXT = (PFNGLMATRIXROTATEDEXTPROC)load("glMatrixRotatedEXT");
	glad_glMatrixScalefEXT = (PFNGLMATRIXSCALEFEXTPROC)load("glMatrixScalefEXT");
	glad_glMatrixScaledEXT = (PFNGLMATRIXSCALEDEXTPROC)load("glMatrixScaledEXT");
	glad_glMatrixTranslatefEXT = (PFNGLMATRIXTRANSLATEFEXTPROC)load("glMatrixTranslatefEXT");
	glad_glMatrixTranslatedEXT = (PFNGLMATRIXTRANSLATEDEXTPROC)load("glMatrixTranslatedEXT");
	glad_glMatrixFrustumEXT = (PFNGLMATRIXFRUSTUMEXTPROC)load("glMatrixFrustumEXT");
	glad_glMatrixOrthoEXT = (PFNGLMATRIXORTHOEXTPROC)load("glMatrixOrthoEXT");
	glad_glMatrixPopEXT = (PFNGLMATRIXPOPEXTPROC)load("glMatrixPopEXT");
	glad_glMatrixPushEXT = (PFNGLMATRIXPUSHEXTPROC)load("glMatrixPushEXT");
	glad_glClientAttribDefaultEXT = (PFNGLCLIENTATTRIBDEFAULTEXTPROC)load("glClientAttribDefaultEXT");
	glad_glPushClientAttribDefaultEXT = (PFNGLPUSHCLIENTATTRIBDEFAULTEXTPROC)load("glPushClientAttribDefaultEXT");
	glad_glTextureParameterfEXT = (PFNGLTEXTUREPARAMETERFEXTPROC)load("glTextureParameterfEXT");
	glad_glTextureParameterfvEXT = (PFNGLTEXTUREPARAMETERFVEXTPROC)load("glTextureParameterfvEXT");
	glad_glTextureParameteriEXT = (PFNGLTEXTUREPARAMETERIEXTPROC)load("glTextureParameteriEXT");
	glad_glTextureParameterivEXT = (PFNGLTEXTUREPARAMETERIVEXTPROC)load("glTextureParameterivEXT");
	glad_glTextureImage1DEXT = (PFNGLTEXTUREIMAGE1DEXTPROC)load("glTextureImage1DEXT");
	glad_glTextureImage2DEXT = (PFNGLTEXTUREIMAGE2DEXTPROC)load("glTextureImage2DEXT");
	glad_glTextureSubImage1DEXT = (PFNGLTEXTURESUBIMAGE1DEXTPROC)load("glTextureSubImage1DEXT");
	glad_glTextureSubImage2DEXT = (PFNGLTEXTURESUBIMAGE2DEXTPROC)load("glTextureSubImage2DEXT");
	glad_glCopyTextureImage1DEXT = (PFNGLCOPYTEXTUREIMAGE1DEXTPROC)load("glCopyTextureImage1DEXT");
	glad_glCopyTextureImage2DEXT = (PFNGLCOPYTEXTUREIMAGE2DEXTPROC)load("glCopyTextureImage2DEXT");
	glad_glCopyTextureSubImage1DEXT = (PFNGLCOPYTEXTURESUBIMAGE1DEXTPROC)load("glCopyTextureSubImage1DEXT");
	glad_glCopyTextureSubImage2DEXT = (PFNGLCOPYTEXTURESUBIMAGE2DEXTPROC)load("glCopyTextureSubImage2DEXT");
	glad_glGetTextureImageEXT = (PFNGLGETTEXTUREIMAGEEXTPROC)load("glGetTextureImageEXT");
	glad_glGetTextureParameterfvEXT = (PFNGLGETTEXTUREPARAMETERFVEXTPROC)load("glGetTextureParameterfvEXT");
	glad_glGetTextureParameterivEXT = (PFNGLGETTEXTUREPARAMETERIVEXTPROC)load("glGetTextureParameterivEXT");
	glad_glGetTextureLevelParameterfvEXT = (PFNGLGETTEXTURELEVELPARAMETERFVEXTPROC)load("glGetTextureLevelParameterfvEXT");
	glad_glGetTextureLevelParameterivEXT = (PFNGLGETTEXTURELEVELPARAMETERIVEXTPROC)load("glGetTextureLevelParameterivEXT");
	glad_glTextureImage3DEXT = (PFNGLTEXTUREIMAGE3DEXTPROC)load("glTextureImage3DEXT");
	glad_glTextureSubImage3DEXT = (PFNGLTEXTURESUBIMAGE3DEXTPROC)load("glTextureSubImage3DEXT");
	glad_glCopyTextureSubImage3DEXT = (PFNGLCOPYTEXTURESUBIMAGE3DEXTPROC)load("glCopyTextureSubImage3DEXT");
	glad_glBindMultiTextureEXT = (PFNGLBINDMULTITEXTUREEXTPROC)load("glBindMultiTextureEXT");
	glad_glMultiTexCoordPointerEXT = (PFNGLMULTITEXCOORDPOINTEREXTPROC)load("glMultiTexCoordPointerEXT");
	glad_glMultiTexEnvfEXT = (PFNGLMULTITEXENVFEXTPROC)load("glMultiTexEnvfEXT");
	glad_glMultiTexEnvfvEXT = (PFNGLMULTITEXENVFVEXTPROC)load("glMultiTexEnvfvEXT");
	glad_glMultiTexEnviEXT = (PFNGLMULTITEXENVIEXTPROC)load("glMultiTexEnviEXT");
	glad_glMultiTexEnvivEXT = (PFNGLMULTITEXENVIVEXTPROC)load("glMultiTexEnvivEXT");
	glad_glMultiTexGendEXT = (PFNGLMULTITEXGENDEXTPROC)load("glMultiTexGendEXT");
	glad_glMultiTexGendvEXT = (PFNGLMULTITEXGENDVEXTPROC)load("glMultiTexGendvEXT");
	glad_glMultiTexGenfEXT = (PFNGLMULTITEXGENFEXTPROC)load("glMultiTexGenfEXT");
	glad_glMultiTexGenfvEXT = (PFNGLMULTITEXGENFVEXTPROC)load("glMultiTexGenfvEXT");
	glad_glMultiTexGeniEXT = (PFNGLMULTITEXGENIEXTPROC)load("glMultiTexGeniEXT");
	glad_glMultiTexGenivEXT = (PFNGLMULTITEXGENIVEXTPROC)load("glMultiTexGenivEXT");
	glad_glGetMultiTexEnvfvEXT = (PFNGLGETMULTITEXENVFVEXTPROC)load("glGetMultiTexEnvfvEXT");
	glad_glGetMultiTexEnvivEXT = (PFNGLGETMULTITEXENVIVEXTPROC)load("glGetMultiTexEnvivEXT");
	glad_glGetMultiTexGendvEXT = (PFNGLGETMULTITEXGENDVEXTPROC)load("glGetMultiTexGendvEXT");
	glad_glGetMultiTexGenfvEXT = (PFNGLGETMULTITEXGENFVEXTPROC)load("glGetMultiTexGenfvEXT");
	glad_glGetMultiTexGenivEXT = (PFNGLGETMULTITEXGENIVEXTPROC)load("glGetMultiTexGenivEXT");
	glad_glMultiTexParameteriEXT = (PFNGLMULTITEXPARAMETERIEXTPROC)load("glMultiTexParameteriEXT");
	glad_glMultiTexParameterivEXT = (PFNGLMULTITEXPARAMETERIVEXTPROC)load("glMultiTexParameterivEXT");
	glad_glMultiTexParameterfEXT = (PFNGLMULTITEXPARAMETERFEXTPROC)load("glMultiTexParameterfEXT");
	glad_glMultiTexParameterfvEXT = (PFNGLMULTITEXPARAMETERFVEXTPROC)load("glMultiTexParameterfvEXT");
	glad_glMultiTexImage1DEXT = (PFNGLMULTITEXIMAGE1DEXTPROC)load("glMultiTexImage1DEXT");
	glad_glMultiTexImage2DEXT = (PFNGLMULTITEXIMAGE2DEXTPROC)load("glMultiTexImage2DEXT");
	glad_glMultiTexSubImage1DEXT = (PFNGLMULTITEXSUBIMAGE1DEXTPROC)load("glMultiTexSubImage1DEXT");
	glad_glMultiTexSubImage2DEXT = (PFNGLMULTITEXSUBIMAGE2DEXTPROC)load("glMultiTexSubImage2DEXT");
	glad_glCopyMultiTexImage1DEXT = (PFNGLCOPYMULTITEXIMAGE1DEXTPROC)load("glCopyMultiTexImage1DEXT");
	glad_glCopyMultiTexImage2DEXT = (PFNGLCOPYMULTITEXIMAGE2DEXTPROC)load("glCopyMultiTexImage2DEXT");
	glad_glCopyMultiTexSubImage1DEXT = (PFNGLCOPYMULTITEXSUBIMAGE1DEXTPROC)load("glCopyMultiTexSubImage1DEXT");
	glad_glCopyMultiTexSubImage2DEXT = (PFNGLCOPYMULTITEXSUBIMAGE2DEXTPROC)load("glCopyMultiTexSubImage2DEXT");
	glad_glGetMultiTexImageEXT = (PFNGLGETMULTITEXIMAGEEXTPROC)load("glGetMultiTexImageEXT");
	glad_glGetMultiTexParameterfvEXT = (PFNGLGETMULTITEXPARAMETERFVEXTPROC)load("glGetMultiTexParameterfvEXT");
	glad_glGetMultiTexParameterivEXT = (PFNGLGETMULTITEXPARAMETERIVEXTPROC)load("glGetMultiTexParameterivEXT");
	glad_glGetMultiTexLevelParameterfvEXT = (PFNGLGETMULTITEXLEVELPARAMETERFVEXTPROC)load("glGetMultiTexLevelParameterfvEXT");
	glad_glGetMultiTexLevelParameterivEXT = (PFNGLGETMULTITEXLEVELPARAMETERIVEXTPROC)load("glGetMultiTexLevelParameterivEXT");
	glad_glMultiTexImage3DEXT = (PFNGLMULTITEXIMAGE3DEXTPROC)load("glMultiTexImage3DEXT");
	glad_glMultiTexSubImage3DEXT = (PFNGLMULTITEXSUBIMAGE3DEXTPROC)load("glMultiTexSubImage3DEXT");
	glad_glCopyMultiTexSubImage3DEXT = (PFNGLCOPYMULTITEXSUBIMAGE3DEXTPROC)load("glCopyMultiTexSubImage3DEXT");
	glad_glEnableClientStateIndexedEXT = (PFNGLENABLECLIENTSTATEINDEXEDEXTPROC)load("glEnableClientStateIndexedEXT");
	glad_glDisableClientStateIndexedEXT = (PFNGLDISABLECLIENTSTATEINDEXEDEXTPROC)load("glDisableClientStateIndexedEXT");
	glad_glGetFloatIndexedvEXT = (PFNGLGETFLOATINDEXEDVEXTPROC)load("glGetFloatIndexedvEXT");
	glad_glGetDoubleIndexedvEXT = (PFNGLGETDOUBLEINDEXEDVEXTPROC)load("glGetDoubleIndexedvEXT");
	glad_glGetPointerIndexedvEXT = (PFNGLGETPOINTERINDEXEDVEXTPROC)load("glGetPointerIndexedvEXT");
	glad_glEnableIndexedEXT = (PFNGLENABLEINDEXEDEXTPROC)load("glEnableIndexedEXT");
	glad_glDisableIndexedEXT = (PFNGLDISABLEINDEXEDEXTPROC)load("glDisableIndexedEXT");
	glad_glIsEnabledIndexedEXT = (PFNGLISENABLEDINDEXEDEXTPROC)load("glIsEnabledIndexedEXT");
	glad_glGetIntegerIndexedvEXT = (PFNGLGETINTEGERINDEXEDVEXTPROC)load("glGetIntegerIndexedvEXT");
	glad_glGetBooleanIndexedvEXT = (PFNGLGETBOOLEANINDEXEDVEXTPROC)load("glGetBooleanIndexedvEXT");
	glad_glCompressedTextureImage3DEXT = (PFNGLCOMPRESSEDTEXTUREIMAGE3DEXTPROC)load("glCompressedTextureImage3DEXT");
	glad_glCompressedTextureImage2DEXT = (PFNGLCOMPRESSEDTEXTUREIMAGE2DEXTPROC)load("glCompressedTextureImage2DEXT");
	glad_glCompressedTextureImage1DEXT = (PFNGLCOMPRESSEDTEXTUREIMAGE1DEXTPROC)load("glCompressedTextureImage1DEXT");
	glad_glCompressedTextureSubImage3DEXT = (PFNGLCOMPRESSEDTEXTURESUBIMAGE3DEXTPROC)load("glCompressedTextureSubImage3DEXT");
	glad_glCompressedTextureSubImage2DEXT = (PFNGLCOMPRESSEDTEXTURESUBIMAGE2DEXTPROC)load("glCompressedTextureSubImage2DEXT");
	glad_glCompressedTextureSubImage1DEXT = (PFNGLCOMPRESSEDTEXTURESUBIMAGE1DEXTPROC)load("glCompressedTextureSubImage1DEXT");
	glad_glGetCompressedTextureImageEXT = (PFNGLGETCOMPRESSEDTEXTUREIMAGEEXTPROC)load("glGetCompressedTextureImageEXT");
	glad_glCompressedMultiTexImage3DEXT = (PFNGLCOMPRESSEDMULTITEXIMAGE3DEXTPROC)load("glCompressedMultiTexImage3DEXT");
	glad_glCompressedMultiTexImage2DEXT = (PFNGLCOMPRESSEDMULTITEXIMAGE2DEXTPROC)load("glCompressedMultiTexImage2DEXT");
	glad_glCompressedMultiTexImage1DEXT = (PFNGLCOMPRESSEDMULTITEXIMAGE1DEXTPROC)load("glCompressedMultiTexImage1DEXT");
	glad_glCompressedMultiTexSubImage3DEXT = (PFNGLCOMPRESSEDMULTITEXSUBIMAGE3DEXTPROC)load("glCompressedMultiTexSubImage3DEXT");
	glad_glCompressedMultiTexSubImage2DEXT = (PFNGLCOMPRESSEDMULTITEXSUBIMAGE2DEXTPROC)load("glCompressedMultiTexSubImage2DEXT");
	glad_glCompressedMultiTexSubImage1DEXT = (PFNGLCOMPRESSEDMULTITEXSUBIMAGE1DEXTPROC)load("glCompressedMultiTexSubImage1DEXT");
	glad_glGetCompressedMultiTexImageEXT = (PFNGLGETCOMPRESSEDMULTITEXIMAGEEXTPROC)load("glGetCompressedMultiTexImageEXT");
	glad_glMatrixLoadTransposefEXT = (PFNGLMATRIXLOADTRANSPOSEFEXTPROC)load("glMatrixLoadTransposefEXT");
	glad_glMatrixLoadTransposedEXT = (PFNGLMATRIXLOADTRANSPOSEDEXTPROC)load("glMatrixLoadTransposedEXT");
	glad_glMatrixMultTransposefEXT = (PFNGLMATRIXMULTTRANSPOSEFEXTPROC)load("glMatrixMultTransposefEXT");
	glad_glMatrixMultTransposedEXT = (PFNGLMATRIXMULTTRANSPOSEDEXTPROC)load("glMatrixMultTransposedEXT");
	glad_glNamedBufferDataEXT = (PFNGLNAMEDBUFFERDATAEXTPROC)load("glNamedBufferDataEXT");
	glad_glNamedBufferSubDataEXT = (PFNGLNAMEDBUFFERSUBDATAEXTPROC)load("glNamedBufferSubDataEXT");
	glad_glMapNamedBufferEXT = (PFNGLMAPNAMEDBUFFEREXTPROC)load("glMapNamedBufferEXT");
	glad_glUnmapNamedBufferEXT = (PFNGLUNMAPNAMEDBUFFEREXTPROC)load("glUnmapNamedBufferEXT");
	glad_glGetNamedBufferParameterivEXT = (PFNGLGETNAMEDBUFFERPARAMETERIVEXTPROC)load("glGetNamedBufferParameterivEXT");
	glad_glGetNamedBufferPointervEXT = (PFNGLGETNAMEDBUFFERPOINTERVEXTPROC)load("glGetNamedBufferPointervEXT");
	glad_glGetNamedBufferSubDataEXT = (PFNGLGETNAMEDBUFFERSUBDATAEXTPROC)load("glGetNamedBufferSubDataEXT");
	glad_glProgramUniform1fEXT = (PFNGLPROGRAMUNIFORM1FEXTPROC)load("glProgramUniform1fEXT");
	glad_glProgramUniform2fEXT = (PFNGLPROGRAMUNIFORM2FEXTPROC)load("glProgramUniform2fEXT");
	glad_glProgramUniform3fEXT = (PFNGLPROGRAMUNIFORM3FEXTPROC)load("glProgramUniform3fEXT");
	glad_glProgramUniform4fEXT = (PFNGLPROGRAMUNIFORM4FEXTPROC)load("glProgramUniform4fEXT");
	glad_glProgramUniform1iEXT = (PFNGLPROGRAMUNIFORM1IEXTPROC)load("glProgramUniform1iEXT");
	glad_glProgramUniform2iEXT = (PFNGLPROGRAMUNIFORM2IEXTPROC)load("glProgramUniform2iEXT");
	glad_glProgramUniform3iEXT = (PFNGLPROGRAMUNIFORM3IEXTPROC)load("glProgramUniform3iEXT");
	glad_glProgramUniform4iEXT = (PFNGLPROGRAMUNIFORM4IEXTPROC)load("glProgramUniform4iEXT");
	glad_glProgramUniform1fvEXT = (PFNGLPROGRAMUNIFORM1FVEXTPROC)load("glProgramUniform1fvEXT");
	glad_glProgramUniform2fvEXT = (PFNGLPROGRAMUNIFORM2FVEXTPROC)load("glProgramUniform2fvEXT");
	glad_glProgramUniform3fvEXT = (PFNGLPROGRAMUNIFORM3FVEXTPROC)load("glProgramUniform3fvEXT");
	glad_glProgramUniform4fvEXT = (PFNGLPROGRAMUNIFORM4FVEXTPROC)load("glProgramUniform4fvEXT");
	glad_glProgramUniform1ivEXT = (PFNGLPROGRAMUNIFORM1IVEXTPROC)load("glProgramUniform1ivEXT");
	glad_glProgramUniform2ivEXT = (PFNGLPROGRAMUNIFORM2IVEXTPROC)load("glProgramUniform2ivEXT");
	glad_glProgramUniform3ivEXT = (PFNGLPROGRAMUNIFORM3IVEXTPROC)load("glProgramUniform3ivEXT");
	glad_glProgramUniform4ivEXT = (PFNGLPROGRAMUNIFORM4IVEXTPROC)load("glProgramUniform4ivEXT");
	glad_glProgramUniformMatrix2fvEXT = (PFNGLPROGRAMUNIFORMMATRIX2FVEXTPROC)load("glProgramUniformMatrix2fvEXT");
	glad_glProgramUniformMatrix3fvEXT = (PFNGLPROGRAMUNIFORMMATRIX3FVEXTPROC)load("glProgramUniformMatrix3fvEXT");
	glad_glProgramUniformMatrix4fvEXT = (PFNGLPROGRAMUNIFORMMATRIX4FVEXTPROC)load("glProgramUniformMatrix4fvEXT");
	glad_glProgramUniformMatrix2x3fvEXT = (PFNGLPROGRAMUNIFORMMATRIX2X3FVEXTPROC)load("glProgramUniformMatrix2x3fvEXT");
	glad_glProgramUniformMatrix3x2fvEXT = (PFNGLPROGRAMUNIFORMMATRIX3X2FVEXTPROC)load("glProgramUniformMatrix3x2fvEXT");
	glad_glProgramUniformMatrix2x4fvEXT = (PFNGLPROGRAMUNIFORMMATRIX2X4FVEXTPROC)load("glProgramUniformMatrix2x4fvEXT");
	glad_glProgramUniformMatrix4x2fvEXT = (PFNGLPROGRAMUNIFORMMATRIX4X2FVEXTPROC)load("glProgramUniformMatrix4x2fvEXT");
	glad_glProgramUniformMatrix3x4fvEXT = (PFNGLPROGRAMUNIFORMMATRIX3X4FVEXTPROC)load("glProgramUniformMatrix3x4fvEXT");
	glad_glProgramUniformMatrix4x3fvEXT = (PFNGLPROGRAMUNIFORMMATRIX4X3FVEXTPROC)load("glProgramUniformMatrix4x3fvEXT");
	glad_glTextureBufferEXT = (PFNGLTEXTUREBUFFEREXTPROC)load("glTextureBufferEXT");
	glad_glMultiTexBufferEXT = (PFNGLMULTITEXBUFFEREXTPROC)load("glMultiTexBufferEXT");
	glad_glTextureParameterIivEXT = (PFNGLTEXTUREPARAMETERIIVEXTPROC)load("glTextureParameterIivEXT");
	glad_glTextureParameterIuivEXT = (PFNGLTEXTUREPARAMETERIUIVEXTPROC)load("glTextureParameterIuivEXT");
	glad_glGetTextureParameterIivEXT = (PFNGLGETTEXTUREPARAMETERIIVEXTPROC)load("glGetTextureParameterIivEXT");
	glad_glGetTextureParameterIuivEXT = (PFNGLGETTEXTUREPARAMETERIUIVEXTPROC)load("glGetTextureParameterIuivEXT");
	glad_glMultiTexParameterIivEXT = (PFNGLMULTITEXPARAMETERIIVEXTPROC)load("glMultiTexParameterIivEXT");
	glad_glMultiTexParameterIuivEXT = (PFNGLMULTITEXPARAMETERIUIVEXTPROC)load("glMultiTexParameterIuivEXT");
	glad_glGetMultiTexParameterIivEXT = (PFNGLGETMULTITEXPARAMETERIIVEXTPROC)load("glGetMultiTexParameterIivEXT");
	glad_glGetMultiTexParameterIuivEXT = (PFNGLGETMULTITEXPARAMETERIUIVEXTPROC)load("glGetMultiTexParameterIuivEXT");
	glad_glProgramUniform1uiEXT = (PFNGLPROGRAMUNIFORM1UIEXTPROC)load("glProgramUniform1uiEXT");
	glad_glProgramUniform2uiEXT = (PFNGLPROGRAMUNIFORM2UIEXTPROC)load("glProgramUniform2uiEXT");
	glad_glProgramUniform3uiEXT = (PFNGLPROGRAMUNIFORM3UIEXTPROC)load("glProgramUniform3uiEXT");
	glad_glProgramUniform4uiEXT = (PFNGLPROGRAMUNIFORM4UIEXTPROC)load("glProgramUniform4uiEXT");
	glad_glProgramUniform1uivEXT = (PFNGLPROGRAMUNIFORM1UIVEXTPROC)load("glProgramUniform1uivEXT");
	glad_glProgramUniform2uivEXT = (PFNGLPROGRAMUNIFORM2UIVEXTPROC)load("glProgramUniform2uivEXT");
	glad_glProgramUniform3uivEXT = (PFNGLPROGRAMUNIFORM3UIVEXTPROC)load("glProgramUniform3uivEXT");
	glad_glProgramUniform4uivEXT = (PFNGLPROGRAMUNIFORM4UIVEXTPROC)load("glProgramUniform4uivEXT");
	glad_glNamedProgramLocalParameters4fvEXT = (PFNGLNAMEDPROGRAMLOCALPARAMETERS4FVEXTPROC)load("glNamedProgramLocalParameters4fvEXT");
	glad_glNamedProgramLocalParameterI4iEXT = (PFNGLNAMEDPROGRAMLOCALPARAMETERI4IEXTPROC)load("glNamedProgramLocalParameterI4iEXT");
	glad_glNamedProgramLocalParameterI4ivEXT = (PFNGLNAMEDPROGRAMLOCALPARAMETERI4IVEXTPROC)load("glNamedProgramLocalParameterI4ivEXT");
	glad_glNamedProgramLocalParametersI4ivEXT = (PFNGLNAMEDPROGRAMLOCALPARAMETERSI4IVEXTPROC)load("glNamedProgramLocalParametersI4ivEXT");
	glad_glNamedProgramLocalParameterI4uiEXT = (PFNGLNAMEDPROGRAMLOCALPARAMETERI4UIEXTPROC)load("glNamedProgramLocalParameterI4uiEXT");
	glad_glNamedProgramLocalParameterI4uivEXT = (PFNGLNAMEDPROGRAMLOCALPARAMETERI4UIVEXTPROC)load("glNamedProgramLocalParameterI4uivEXT");
	glad_glNamedProgramLocalParametersI4uivEXT = (PFNGLNAMEDPROGRAMLOCALPARAMETERSI4UIVEXTPROC)load("glNamedProgramLocalParametersI4uivEXT");
	glad_glGetNamedProgramLocalParameterIivEXT = (PFNGLGETNAMEDPROGRAMLOCALPARAMETERIIVEXTPROC)load("glGetNamedProgramLocalParameterIivEXT");
	glad_glGetNamedProgramLocalParameterIuivEXT = (PFNGLGETNAMEDPROGRAMLOCALPARAMETERIUIVEXTPROC)load("glGetNamedProgramLocalParameterIuivEXT");
	glad_glEnableClientStateiEXT = (PFNGLENABLECLIENTSTATEIEXTPROC)load("glEnableClientStateiEXT");
	glad_glDisableClientStateiEXT = (PFNGLDISABLECLIENTSTATEIEXTPROC)load("glDisableClientStateiEXT");
	glad_glGetFloati_vEXT = (PFNGLGETFLOATI_VEXTPROC)load("glGetFloati_vEXT");
	glad_glGetDoublei_vEXT = (PFNGLGETDOUBLEI_VEXTPROC)load("glGetDoublei_vEXT");
	glad_glGetPointeri_vEXT = (PFNGLGETPOINTERI_VEXTPROC)load("glGetPointeri_vEXT");
	glad_glNamedProgramStringEXT = (PFNGLNAMEDPROGRAMSTRINGEXTPROC)load("glNamedProgramStringEXT");
	glad_glNamedProgramLocalParameter4dEXT = (PFNGLNAMEDPROGRAMLOCALPARAMETER4DEXTPROC)load("glNamedProgramLocalParameter4dEXT");
	glad_glNamedProgramLocalParameter4dvEXT = (PFNGLNAMEDPROGRAMLOCALPARAMETER4DVEXTPROC)load("glNamedProgramLocalParameter4dvEXT");
	glad_glNamedProgramLocalParameter4fEXT = (PFNGLNAMEDPROGRAMLOCALPARAMETER4FEXTPROC)load("glNamedProgramLocalParameter4fEXT");
	glad_glNamedProgramLocalParameter4fvEXT = (PFNGLNAMEDPROGRAMLOCALPARAMETER4FVEXTPROC)load("glNamedProgramLocalParameter4fvEXT");
	glad_glGetNamedProgramLocalParameterdvEXT = (PFNGLGETNAMEDPROGRAMLOCALPARAMETERDVEXTPROC)load("glGetNamedProgramLocalParameterdvEXT");
	glad_glGetNamedProgramLocalParameterfvEXT = (PFNGLGETNAMEDPROGRAMLOCALPARAMETERFVEXTPROC)load("glGetNamedProgramLocalParameterfvEXT");
	glad_glGetNamedProgramivEXT = (PFNGLGETNAMEDPROGRAMIVEXTPROC)load("glGetNamedProgramivEXT");
	glad_glGetNamedProgramStringEXT = (PFNGLGETNAMEDPROGRAMSTRINGEXTPROC)load("glGetNamedProgramStringEXT");
	glad_glNamedRenderbufferStorageEXT = (PFNGLNAMEDRENDERBUFFERSTORAGEEXTPROC)load("glNamedRenderbufferStorageEXT");
	glad_glGetNamedRenderbufferParameterivEXT = (PFNGLGETNAMEDRENDERBUFFERPARAMETERIVEXTPROC)load("glGetNamedRenderbufferParameterivEXT");
	glad_glNamedRenderbufferStorageMultisampleEXT = (PFNGLNAMEDRENDERBUFFERSTORAGEMULTISAMPLEEXTPROC)load("glNamedRenderbufferStorageMultisampleEXT");
	glad_glNamedRenderbufferStorageMultisampleCoverageEXT = (PFNGLNAMEDRENDERBUFFERSTORAGEMULTISAMPLECOVERAGEEXTPROC)load("glNamedRenderbufferStorageMultisampleCoverageEXT");
	glad_glCheckNamedFramebufferStatusEXT = (PFNGLCHECKNAMEDFRAMEBUFFERSTATUSEXTPROC)load("glCheckNamedFramebufferStatusEXT");
	glad_glNamedFramebufferTexture1DEXT = (PFNGLNAMEDFRAMEBUFFERTEXTURE1DEXTPROC)load("glNamedFramebufferTexture1DEXT");
	glad_glNamedFramebufferTexture2DEXT = (PFNGLNAMEDFRAMEBUFFERTEXTURE2DEXTPROC)load("glNamedFramebufferTexture2DEXT");
	glad_glNamedFramebufferTexture3DEXT = (PFNGLNAMEDFRAMEBUFFERTEXTURE3DEXTPROC)load("glNamedFramebufferTexture3DEXT");
	glad_glNamedFramebufferRenderbufferEXT = (PFNGLNAMEDFRAMEBUFFERRENDERBUFFEREXTPROC)load("glNamedFramebufferRenderbufferEXT");
	glad_glGetNamedFramebufferAttachmentParameterivEXT = (PFNGLGETNAMEDFRAMEBUFFERATTACHMENTPARAMETERIVEXTPROC)load("glGetNamedFramebufferAttachmentParameterivEXT");
	glad_glGenerateTextureMipmapEXT = (PFNGLGENERATETEXTUREMIPMAPEXTPROC)load("glGenerateTextureMipmapEXT");
	glad_glGenerateMultiTexMipmapEXT = (PFNGLGENERATEMULTITEXMIPMAPEXTPROC)load("glGenerateMultiTexMipmapEXT");
	glad_glFramebufferDrawBufferEXT = (PFNGLFRAMEBUFFERDRAWBUFFEREXTPROC)load("glFramebufferDrawBufferEXT");
	glad_glFramebufferDrawBuffersEXT = (PFNGLFRAMEBUFFERDRAWBUFFERSEXTPROC)load("glFramebufferDrawBuffersEXT");
	glad_glFramebufferReadBufferEXT = (PFNGLFRAMEBUFFERREADBUFFEREXTPROC)load("glFramebufferReadBufferEXT");
	glad_glGetFramebufferParameterivEXT = (PFNGLGETFRAMEBUFFERPARAMETERIVEXTPROC)load("glGetFramebufferParameterivEXT");
	glad_glNamedCopyBufferSubDataEXT = (PFNGLNAMEDCOPYBUFFERSUBDATAEXTPROC)load("glNamedCopyBufferSubDataEXT");
	glad_glNamedFramebufferTextureEXT = (PFNGLNAMEDFRAMEBUFFERTEXTUREEXTPROC)load("glNamedFramebufferTextureEXT");
	glad_glNamedFramebufferTextureLayerEXT = (PFNGLNAMEDFRAMEBUFFERTEXTURELAYEREXTPROC)load("glNamedFramebufferTextureLayerEXT");
	glad_glNamedFramebufferTextureFaceEXT = (PFNGLNAMEDFRAMEBUFFERTEXTUREFACEEXTPROC)load("glNamedFramebufferTextureFaceEXT");
	glad_glTextureRenderbufferEXT = (PFNGLTEXTURERENDERBUFFEREXTPROC)load("glTextureRenderbufferEXT");
	glad_glMultiTexRenderbufferEXT = (PFNGLMULTITEXRENDERBUFFEREXTPROC)load("glMultiTexRenderbufferEXT");
	glad_glVertexArrayVertexOffsetEXT = (PFNGLVERTEXARRAYVERTEXOFFSETEXTPROC)load("glVertexArrayVertexOffsetEXT");
	glad_glVertexArrayColorOffsetEXT = (PFNGLVERTEXARRAYCOLOROFFSETEXTPROC)load("glVertexArrayColorOffsetEXT");
	glad_glVertexArrayEdgeFlagOffsetEXT = (PFNGLVERTEXARRAYEDGEFLAGOFFSETEXTPROC)load("glVertexArrayEdgeFlagOffsetEXT");
	glad_glVertexArrayIndexOffsetEXT = (PFNGLVERTEXARRAYINDEXOFFSETEXTPROC)load("glVertexArrayIndexOffsetEXT");
	glad_glVertexArrayNormalOffsetEXT = (PFNGLVERTEXARRAYNORMALOFFSETEXTPROC)load("glVertexArrayNormalOffsetEXT");
	glad_glVertexArrayTexCoordOffsetEXT = (PFNGLVERTEXARRAYTEXCOORDOFFSETEXTPROC)load("glVertexArrayTexCoordOffsetEXT");
	glad_glVertexArrayMultiTexCoordOffsetEXT = (PFNGLVERTEXARRAYMULTITEXCOORDOFFSETEXTPROC)load("glVertexArrayMultiTexCoordOffsetEXT");
	glad_glVertexArrayFogCoordOffsetEXT = (PFNGLVERTEXARRAYFOGCOORDOFFSETEXTPROC)load("glVertexArrayFogCoordOffsetEXT");
	glad_glVertexArraySecondaryColorOffsetEXT = (PFNGLVERTEXARRAYSECONDARYCOLOROFFSETEXTPROC)load("glVertexArraySecondaryColorOffsetEXT");
	glad_glVertexArrayVertexAttribOffsetEXT = (PFNGLVERTEXARRAYVERTEXATTRIBOFFSETEXTPROC)load("glVertexArrayVertexAttribOffsetEXT");
	glad_glVertexArrayVertexAttribIOffsetEXT = (PFNGLVERTEXARRAYVERTEXATTRIBIOFFSETEXTPROC)load("glVertexArrayVertexAttribIOffsetEXT");
	glad_glEnableVertexArrayEXT = (PFNGLENABLEVERTEXARRAYEXTPROC)load("glEnableVertexArrayEXT");
	glad_glDisableVertexArrayEXT = (PFNGLDISABLEVERTEXARRAYEXTPROC)load("glDisableVertexArrayEXT");
	glad_glEnableVertexArrayAttribEXT = (PFNGLENABLEVERTEXARRAYATTRIBEXTPROC)load("glEnableVertexArrayAttribEXT");
	glad_glDisableVertexArrayAttribEXT = (PFNGLDISABLEVERTEXARRAYATTRIBEXTPROC)load("glDisableVertexArrayAttribEXT");
	glad_glGetVertexArrayIntegervEXT = (PFNGLGETVERTEXARRAYINTEGERVEXTPROC)load("glGetVertexArrayIntegervEXT");
	glad_glGetVertexArrayPointervEXT = (PFNGLGETVERTEXARRAYPOINTERVEXTPROC)load("glGetVertexArrayPointervEXT");
	glad_glGetVertexArrayIntegeri_vEXT = (PFNGLGETVERTEXARRAYINTEGERI_VEXTPROC)load("glGetVertexArrayIntegeri_vEXT");
	glad_glGetVertexArrayPointeri_vEXT = (PFNGLGETVERTEXARRAYPOINTERI_VEXTPROC)load("glGetVertexArrayPointeri_vEXT");
	glad_glMapNamedBufferRangeEXT = (PFNGLMAPNAMEDBUFFERRANGEEXTPROC)load("glMapNamedBufferRangeEXT");
	glad_glFlushMappedNamedBufferRangeEXT = (PFNGLFLUSHMAPPEDNAMEDBUFFERRANGEEXTPROC)load("glFlushMappedNamedBufferRangeEXT");
	glad_glNamedBufferStorageEXT = (PFNGLNAMEDBUFFERSTORAGEEXTPROC)load("glNamedBufferStorageEXT");
	glad_glClearNamedBufferDataEXT = (PFNGLCLEARNAMEDBUFFERDATAEXTPROC)load("glClearNamedBufferDataEXT");
	glad_glClearNamedBufferSubDataEXT = (PFNGLCLEARNAMEDBUFFERSUBDATAEXTPROC)load("glClearNamedBufferSubDataEXT");
	glad_glNamedFramebufferParameteriEXT = (PFNGLNAMEDFRAMEBUFFERPARAMETERIEXTPROC)load("glNamedFramebufferParameteriEXT");
	glad_glGetNamedFramebufferParameterivEXT = (PFNGLGETNAMEDFRAMEBUFFERPARAMETERIVEXTPROC)load("glGetNamedFramebufferParameterivEXT");
	glad_glProgramUniform1dEXT = (PFNGLPROGRAMUNIFORM1DEXTPROC)load("glProgramUniform1dEXT");
	glad_glProgramUniform2dEXT = (PFNGLPROGRAMUNIFORM2DEXTPROC)load("glProgramUniform2dEXT");
	glad_glProgramUniform3dEXT = (PFNGLPROGRAMUNIFORM3DEXTPROC)load("glProgramUniform3dEXT");
	glad_glProgramUniform4dEXT = (PFNGLPROGRAMUNIFORM4DEXTPROC)load("glProgramUniform4dEXT");
	glad_glProgramUniform1dvEXT = (PFNGLPROGRAMUNIFORM1DVEXTPROC)load("glProgramUniform1dvEXT");
	glad_glProgramUniform2dvEXT = (PFNGLPROGRAMUNIFORM2DVEXTPROC)load("glProgramUniform2dvEXT");
	glad_glProgramUniform3dvEXT = (PFNGLPROGRAMUNIFORM3DVEXTPROC)load("glProgramUniform3dvEXT");
	glad_glProgramUniform4dvEXT = (PFNGLPROGRAMUNIFORM4DVEXTPROC)load("glProgramUniform4dvEXT");
	glad_glProgramUniformMatrix2dvEXT = (PFNGLPROGRAMUNIFORMMATRIX2DVEXTPROC)load("glProgramUniformMatrix2dvEXT");
	glad_glProgramUniformMatrix3dvEXT = (PFNGLPROGRAMUNIFORMMATRIX3DVEXTPROC)load("glProgramUniformMatrix3dvEXT");
	glad_glProgramUniformMatrix4dvEXT = (PFNGLPROGRAMUNIFORMMATRIX4DVEXTPROC)load("glProgramUniformMatrix4dvEXT");
	glad_glProgramUniformMatrix2x3dvEXT = (PFNGLPROGRAMUNIFORMMATRIX2X3DVEXTPROC)load("glProgramUniformMatrix2x3dvEXT");
	glad_glProgramUniformMatrix2x4dvEXT = (PFNGLPROGRAMUNIFORMMATRIX2X4DVEXTPROC)load("glProgramUniformMatrix2x4dvEXT");
	glad_glProgramUniformMatrix3x2dvEXT = (PFNGLPROGRAMUNIFORMMATRIX3X2DVEXTPROC)load("glProgramUniformMatrix3x2dvEXT");
	glad_glProgramUniformMatrix3x4dvEXT = (PFNGLPROGRAMUNIFORMMATRIX3X4DVEXTPROC)load("glProgramUniformMatrix3x4dvEXT");
	glad_glProgramUniformMatrix4x2dvEXT = (PFNGLPROGRAMUNIFORMMATRIX4X2DVEXTPROC)load("glProgramUniformMatrix4x2dvEXT");
	glad_glProgramUniformMatrix4x3dvEXT = (PFNGLPROGRAMUNIFORMMATRIX4X3DVEXTPROC)load("glProgramUniformMatrix4x3dvEXT");
	glad_glTextureBufferRangeEXT = (PFNGLTEXTUREBUFFERRANGEEXTPROC)load("glTextureBufferRangeEXT");
	glad_glTextureStorage1DEXT = (PFNGLTEXTURESTORAGE1DEXTPROC)load("glTextureStorage1DEXT");
	glad_glTextureStorage2DEXT = (PFNGLTEXTURESTORAGE2DEXTPROC)load("glTextureStorage2DEXT");
	glad_glTextureStorage3DEXT = (PFNGLTEXTURESTORAGE3DEXTPROC)load("glTextureStorage3DEXT");
	glad_glTextureStorage2DMultisampleEXT = (PFNGLTEXTURESTORAGE2DMULTISAMPLEEXTPROC)load("glTextureStorage2DMultisampleEXT");
	glad_glTextureStorage3DMultisampleEXT = (PFNGLTEXTURESTORAGE3DMULTISAMPLEEXTPROC)load("glTextureStorage3DMultisampleEXT");
	glad_glVertexArrayBindVertexBufferEXT = (PFNGLVERTEXARRAYBINDVERTEXBUFFEREXTPROC)load("glVertexArrayBindVertexBufferEXT");
	glad_glVertexArrayVertexAttribFormatEXT = (PFNGLVERTEXARRAYVERTEXATTRIBFORMATEXTPROC)load("glVertexArrayVertexAttribFormatEXT");
	glad_glVertexArrayVertexAttribIFormatEXT = (PFNGLVERTEXARRAYVERTEXATTRIBIFORMATEXTPROC)load("glVertexArrayVertexAttribIFormatEXT");
	glad_glVertexArrayVertexAttribLFormatEXT = (PFNGLVERTEXARRAYVERTEXATTRIBLFORMATEXTPROC)load("glVertexArrayVertexAttribLFormatEXT");
	glad_glVertexArrayVertexAttribBindingEXT = (PFNGLVERTEXARRAYVERTEXATTRIBBINDINGEXTPROC)load("glVertexArrayVertexAttribBindingEXT");
	glad_glVertexArrayVertexBindingDivisorEXT = (PFNGLVERTEXARRAYVERTEXBINDINGDIVISOREXTPROC)load("glVertexArrayVertexBindingDivisorEXT");
	glad_glVertexArrayVertexAttribLOffsetEXT = (PFNGLVERTEXARRAYVERTEXATTRIBLOFFSETEXTPROC)load("glVertexArrayVertexAttribLOffsetEXT");
	glad_glTexturePageCommitmentEXT = (PFNGLTEXTUREPAGECOMMITMENTEXTPROC)load("glTexturePageCommitmentEXT");
	glad_glVertexArrayVertexAttribDivisorEXT = (PFNGLVERTEXARRAYVERTEXATTRIBDIVISOREXTPROC)load("glVertexArrayVertexAttribDivisorEXT");
}