#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  scalar_t__ PFNGLVERTEXATTRIBS4UBVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBS4SVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBS4FVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBS4DVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBS3SVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBS3FVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBS3DVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBS2SVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBS2FVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBS2DVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBS1SVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBS1FVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBS1DVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBPOINTERNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4UBVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4UBNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4SVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4SNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4FVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4FNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4DVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4DNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB3SVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB3SNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB3FVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB3FNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB3DVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB3DNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB2SVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB2SNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB2FVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB2FNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB2DVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB2DNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB1SVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB1SNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB1FVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB1FNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB1DVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB1DNVPROC ;
typedef  scalar_t__ PFNGLTRACKMATRIXNVPROC ;
typedef  scalar_t__ PFNGLREQUESTRESIDENTPROGRAMSNVPROC ;
typedef  scalar_t__ PFNGLPROGRAMPARAMETERS4FVNVPROC ;
typedef  scalar_t__ PFNGLPROGRAMPARAMETERS4DVNVPROC ;
typedef  scalar_t__ PFNGLPROGRAMPARAMETER4FVNVPROC ;
typedef  scalar_t__ PFNGLPROGRAMPARAMETER4FNVPROC ;
typedef  scalar_t__ PFNGLPROGRAMPARAMETER4DVNVPROC ;
typedef  scalar_t__ PFNGLPROGRAMPARAMETER4DNVPROC ;
typedef  scalar_t__ PFNGLLOADPROGRAMNVPROC ;
typedef  scalar_t__ PFNGLISPROGRAMNVPROC ;
typedef  scalar_t__ PFNGLGETVERTEXATTRIBPOINTERVNVPROC ;
typedef  scalar_t__ PFNGLGETVERTEXATTRIBIVNVPROC ;
typedef  scalar_t__ PFNGLGETVERTEXATTRIBFVNVPROC ;
typedef  scalar_t__ PFNGLGETVERTEXATTRIBDVNVPROC ;
typedef  scalar_t__ PFNGLGETTRACKMATRIXIVNVPROC ;
typedef  scalar_t__ PFNGLGETPROGRAMSTRINGNVPROC ;
typedef  scalar_t__ PFNGLGETPROGRAMPARAMETERFVNVPROC ;
typedef  scalar_t__ PFNGLGETPROGRAMPARAMETERDVNVPROC ;
typedef  scalar_t__ PFNGLGETPROGRAMIVNVPROC ;
typedef  scalar_t__ PFNGLGENPROGRAMSNVPROC ;
typedef  scalar_t__ PFNGLEXECUTEPROGRAMNVPROC ;
typedef  scalar_t__ PFNGLDELETEPROGRAMSNVPROC ;
typedef  scalar_t__ PFNGLBINDPROGRAMNVPROC ;
typedef  scalar_t__ PFNGLAREPROGRAMSRESIDENTNVPROC ;
typedef  scalar_t__ (* GLADloadproc ) (char*) ;

/* Variables and functions */
 int /*<<< orphan*/  GLAD_GL_NV_vertex_program ; 
 scalar_t__ glad_glAreProgramsResidentNV ; 
 scalar_t__ glad_glBindProgramNV ; 
 scalar_t__ glad_glDeleteProgramsNV ; 
 scalar_t__ glad_glExecuteProgramNV ; 
 scalar_t__ glad_glGenProgramsNV ; 
 scalar_t__ glad_glGetProgramParameterdvNV ; 
 scalar_t__ glad_glGetProgramParameterfvNV ; 
 scalar_t__ glad_glGetProgramStringNV ; 
 scalar_t__ glad_glGetProgramivNV ; 
 scalar_t__ glad_glGetTrackMatrixivNV ; 
 scalar_t__ glad_glGetVertexAttribPointervNV ; 
 scalar_t__ glad_glGetVertexAttribdvNV ; 
 scalar_t__ glad_glGetVertexAttribfvNV ; 
 scalar_t__ glad_glGetVertexAttribivNV ; 
 scalar_t__ glad_glIsProgramNV ; 
 scalar_t__ glad_glLoadProgramNV ; 
 scalar_t__ glad_glProgramParameter4dNV ; 
 scalar_t__ glad_glProgramParameter4dvNV ; 
 scalar_t__ glad_glProgramParameter4fNV ; 
 scalar_t__ glad_glProgramParameter4fvNV ; 
 scalar_t__ glad_glProgramParameters4dvNV ; 
 scalar_t__ glad_glProgramParameters4fvNV ; 
 scalar_t__ glad_glRequestResidentProgramsNV ; 
 scalar_t__ glad_glTrackMatrixNV ; 
 scalar_t__ glad_glVertexAttrib1dNV ; 
 scalar_t__ glad_glVertexAttrib1dvNV ; 
 scalar_t__ glad_glVertexAttrib1fNV ; 
 scalar_t__ glad_glVertexAttrib1fvNV ; 
 scalar_t__ glad_glVertexAttrib1sNV ; 
 scalar_t__ glad_glVertexAttrib1svNV ; 
 scalar_t__ glad_glVertexAttrib2dNV ; 
 scalar_t__ glad_glVertexAttrib2dvNV ; 
 scalar_t__ glad_glVertexAttrib2fNV ; 
 scalar_t__ glad_glVertexAttrib2fvNV ; 
 scalar_t__ glad_glVertexAttrib2sNV ; 
 scalar_t__ glad_glVertexAttrib2svNV ; 
 scalar_t__ glad_glVertexAttrib3dNV ; 
 scalar_t__ glad_glVertexAttrib3dvNV ; 
 scalar_t__ glad_glVertexAttrib3fNV ; 
 scalar_t__ glad_glVertexAttrib3fvNV ; 
 scalar_t__ glad_glVertexAttrib3sNV ; 
 scalar_t__ glad_glVertexAttrib3svNV ; 
 scalar_t__ glad_glVertexAttrib4dNV ; 
 scalar_t__ glad_glVertexAttrib4dvNV ; 
 scalar_t__ glad_glVertexAttrib4fNV ; 
 scalar_t__ glad_glVertexAttrib4fvNV ; 
 scalar_t__ glad_glVertexAttrib4sNV ; 
 scalar_t__ glad_glVertexAttrib4svNV ; 
 scalar_t__ glad_glVertexAttrib4ubNV ; 
 scalar_t__ glad_glVertexAttrib4ubvNV ; 
 scalar_t__ glad_glVertexAttribPointerNV ; 
 scalar_t__ glad_glVertexAttribs1dvNV ; 
 scalar_t__ glad_glVertexAttribs1fvNV ; 
 scalar_t__ glad_glVertexAttribs1svNV ; 
 scalar_t__ glad_glVertexAttribs2dvNV ; 
 scalar_t__ glad_glVertexAttribs2fvNV ; 
 scalar_t__ glad_glVertexAttribs2svNV ; 
 scalar_t__ glad_glVertexAttribs3dvNV ; 
 scalar_t__ glad_glVertexAttribs3fvNV ; 
 scalar_t__ glad_glVertexAttribs3svNV ; 
 scalar_t__ glad_glVertexAttribs4dvNV ; 
 scalar_t__ glad_glVertexAttribs4fvNV ; 
 scalar_t__ glad_glVertexAttribs4svNV ; 
 scalar_t__ glad_glVertexAttribs4ubvNV ; 

__attribute__((used)) static void load_GL_NV_vertex_program(GLADloadproc load) {
	if(!GLAD_GL_NV_vertex_program) return;
	glad_glAreProgramsResidentNV = (PFNGLAREPROGRAMSRESIDENTNVPROC)load("glAreProgramsResidentNV");
	glad_glBindProgramNV = (PFNGLBINDPROGRAMNVPROC)load("glBindProgramNV");
	glad_glDeleteProgramsNV = (PFNGLDELETEPROGRAMSNVPROC)load("glDeleteProgramsNV");
	glad_glExecuteProgramNV = (PFNGLEXECUTEPROGRAMNVPROC)load("glExecuteProgramNV");
	glad_glGenProgramsNV = (PFNGLGENPROGRAMSNVPROC)load("glGenProgramsNV");
	glad_glGetProgramParameterdvNV = (PFNGLGETPROGRAMPARAMETERDVNVPROC)load("glGetProgramParameterdvNV");
	glad_glGetProgramParameterfvNV = (PFNGLGETPROGRAMPARAMETERFVNVPROC)load("glGetProgramParameterfvNV");
	glad_glGetProgramivNV = (PFNGLGETPROGRAMIVNVPROC)load("glGetProgramivNV");
	glad_glGetProgramStringNV = (PFNGLGETPROGRAMSTRINGNVPROC)load("glGetProgramStringNV");
	glad_glGetTrackMatrixivNV = (PFNGLGETTRACKMATRIXIVNVPROC)load("glGetTrackMatrixivNV");
	glad_glGetVertexAttribdvNV = (PFNGLGETVERTEXATTRIBDVNVPROC)load("glGetVertexAttribdvNV");
	glad_glGetVertexAttribfvNV = (PFNGLGETVERTEXATTRIBFVNVPROC)load("glGetVertexAttribfvNV");
	glad_glGetVertexAttribivNV = (PFNGLGETVERTEXATTRIBIVNVPROC)load("glGetVertexAttribivNV");
	glad_glGetVertexAttribPointervNV = (PFNGLGETVERTEXATTRIBPOINTERVNVPROC)load("glGetVertexAttribPointervNV");
	glad_glIsProgramNV = (PFNGLISPROGRAMNVPROC)load("glIsProgramNV");
	glad_glLoadProgramNV = (PFNGLLOADPROGRAMNVPROC)load("glLoadProgramNV");
	glad_glProgramParameter4dNV = (PFNGLPROGRAMPARAMETER4DNVPROC)load("glProgramParameter4dNV");
	glad_glProgramParameter4dvNV = (PFNGLPROGRAMPARAMETER4DVNVPROC)load("glProgramParameter4dvNV");
	glad_glProgramParameter4fNV = (PFNGLPROGRAMPARAMETER4FNVPROC)load("glProgramParameter4fNV");
	glad_glProgramParameter4fvNV = (PFNGLPROGRAMPARAMETER4FVNVPROC)load("glProgramParameter4fvNV");
	glad_glProgramParameters4dvNV = (PFNGLPROGRAMPARAMETERS4DVNVPROC)load("glProgramParameters4dvNV");
	glad_glProgramParameters4fvNV = (PFNGLPROGRAMPARAMETERS4FVNVPROC)load("glProgramParameters4fvNV");
	glad_glRequestResidentProgramsNV = (PFNGLREQUESTRESIDENTPROGRAMSNVPROC)load("glRequestResidentProgramsNV");
	glad_glTrackMatrixNV = (PFNGLTRACKMATRIXNVPROC)load("glTrackMatrixNV");
	glad_glVertexAttribPointerNV = (PFNGLVERTEXATTRIBPOINTERNVPROC)load("glVertexAttribPointerNV");
	glad_glVertexAttrib1dNV = (PFNGLVERTEXATTRIB1DNVPROC)load("glVertexAttrib1dNV");
	glad_glVertexAttrib1dvNV = (PFNGLVERTEXATTRIB1DVNVPROC)load("glVertexAttrib1dvNV");
	glad_glVertexAttrib1fNV = (PFNGLVERTEXATTRIB1FNVPROC)load("glVertexAttrib1fNV");
	glad_glVertexAttrib1fvNV = (PFNGLVERTEXATTRIB1FVNVPROC)load("glVertexAttrib1fvNV");
	glad_glVertexAttrib1sNV = (PFNGLVERTEXATTRIB1SNVPROC)load("glVertexAttrib1sNV");
	glad_glVertexAttrib1svNV = (PFNGLVERTEXATTRIB1SVNVPROC)load("glVertexAttrib1svNV");
	glad_glVertexAttrib2dNV = (PFNGLVERTEXATTRIB2DNVPROC)load("glVertexAttrib2dNV");
	glad_glVertexAttrib2dvNV = (PFNGLVERTEXATTRIB2DVNVPROC)load("glVertexAttrib2dvNV");
	glad_glVertexAttrib2fNV = (PFNGLVERTEXATTRIB2FNVPROC)load("glVertexAttrib2fNV");
	glad_glVertexAttrib2fvNV = (PFNGLVERTEXATTRIB2FVNVPROC)load("glVertexAttrib2fvNV");
	glad_glVertexAttrib2sNV = (PFNGLVERTEXATTRIB2SNVPROC)load("glVertexAttrib2sNV");
	glad_glVertexAttrib2svNV = (PFNGLVERTEXATTRIB2SVNVPROC)load("glVertexAttrib2svNV");
	glad_glVertexAttrib3dNV = (PFNGLVERTEXATTRIB3DNVPROC)load("glVertexAttrib3dNV");
	glad_glVertexAttrib3dvNV = (PFNGLVERTEXATTRIB3DVNVPROC)load("glVertexAttrib3dvNV");
	glad_glVertexAttrib3fNV = (PFNGLVERTEXATTRIB3FNVPROC)load("glVertexAttrib3fNV");
	glad_glVertexAttrib3fvNV = (PFNGLVERTEXATTRIB3FVNVPROC)load("glVertexAttrib3fvNV");
	glad_glVertexAttrib3sNV = (PFNGLVERTEXATTRIB3SNVPROC)load("glVertexAttrib3sNV");
	glad_glVertexAttrib3svNV = (PFNGLVERTEXATTRIB3SVNVPROC)load("glVertexAttrib3svNV");
	glad_glVertexAttrib4dNV = (PFNGLVERTEXATTRIB4DNVPROC)load("glVertexAttrib4dNV");
	glad_glVertexAttrib4dvNV = (PFNGLVERTEXATTRIB4DVNVPROC)load("glVertexAttrib4dvNV");
	glad_glVertexAttrib4fNV = (PFNGLVERTEXATTRIB4FNVPROC)load("glVertexAttrib4fNV");
	glad_glVertexAttrib4fvNV = (PFNGLVERTEXATTRIB4FVNVPROC)load("glVertexAttrib4fvNV");
	glad_glVertexAttrib4sNV = (PFNGLVERTEXATTRIB4SNVPROC)load("glVertexAttrib4sNV");
	glad_glVertexAttrib4svNV = (PFNGLVERTEXATTRIB4SVNVPROC)load("glVertexAttrib4svNV");
	glad_glVertexAttrib4ubNV = (PFNGLVERTEXATTRIB4UBNVPROC)load("glVertexAttrib4ubNV");
	glad_glVertexAttrib4ubvNV = (PFNGLVERTEXATTRIB4UBVNVPROC)load("glVertexAttrib4ubvNV");
	glad_glVertexAttribs1dvNV = (PFNGLVERTEXATTRIBS1DVNVPROC)load("glVertexAttribs1dvNV");
	glad_glVertexAttribs1fvNV = (PFNGLVERTEXATTRIBS1FVNVPROC)load("glVertexAttribs1fvNV");
	glad_glVertexAttribs1svNV = (PFNGLVERTEXATTRIBS1SVNVPROC)load("glVertexAttribs1svNV");
	glad_glVertexAttribs2dvNV = (PFNGLVERTEXATTRIBS2DVNVPROC)load("glVertexAttribs2dvNV");
	glad_glVertexAttribs2fvNV = (PFNGLVERTEXATTRIBS2FVNVPROC)load("glVertexAttribs2fvNV");
	glad_glVertexAttribs2svNV = (PFNGLVERTEXATTRIBS2SVNVPROC)load("glVertexAttribs2svNV");
	glad_glVertexAttribs3dvNV = (PFNGLVERTEXATTRIBS3DVNVPROC)load("glVertexAttribs3dvNV");
	glad_glVertexAttribs3fvNV = (PFNGLVERTEXATTRIBS3FVNVPROC)load("glVertexAttribs3fvNV");
	glad_glVertexAttribs3svNV = (PFNGLVERTEXATTRIBS3SVNVPROC)load("glVertexAttribs3svNV");
	glad_glVertexAttribs4dvNV = (PFNGLVERTEXATTRIBS4DVNVPROC)load("glVertexAttribs4dvNV");
	glad_glVertexAttribs4fvNV = (PFNGLVERTEXATTRIBS4FVNVPROC)load("glVertexAttribs4fvNV");
	glad_glVertexAttribs4svNV = (PFNGLVERTEXATTRIBS4SVNVPROC)load("glVertexAttribs4svNV");
	glad_glVertexAttribs4ubvNV = (PFNGLVERTEXATTRIBS4UBVNVPROC)load("glVertexAttribs4ubvNV");
}