#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */
typedef  struct TYPE_8__   TYPE_3__ ;
typedef  struct TYPE_7__   TYPE_2__ ;
typedef  struct TYPE_6__   TYPE_1__ ;

/* Type definitions */
typedef  int uint16_t ;
typedef  int /*<<< orphan*/  esp_err_t ;
struct TYPE_7__ {int /*<<< orphan*/  act; int /*<<< orphan*/  pid; int /*<<< orphan*/  sig; } ;
typedef  TYPE_2__ btc_msg_t ;
struct TYPE_6__ {int icon; } ;
struct TYPE_8__ {TYPE_1__ cfg_local_icon; } ;
typedef  TYPE_3__ btc_ble_gap_args_t ;

/* Variables and functions */
 int /*<<< orphan*/  BTC_GAP_BLE_ACT_CONFIG_LOCAL_ICON ; 
 int /*<<< orphan*/  BTC_PID_GAP_BLE ; 
 int /*<<< orphan*/  BTC_SIG_API_CALL ; 
 int /*<<< orphan*/  BT_STATUS_SUCCESS ; 
#define  ESP_BLE_APPEARANCE_BLOOD_PRESSURE_ARM 185 
#define  ESP_BLE_APPEARANCE_BLOOD_PRESSURE_WRIST 184 
#define  ESP_BLE_APPEARANCE_CYCLING_CADENCE 183 
#define  ESP_BLE_APPEARANCE_CYCLING_COMPUTER 182 
#define  ESP_BLE_APPEARANCE_CYCLING_POWER 181 
#define  ESP_BLE_APPEARANCE_CYCLING_SPEED 180 
#define  ESP_BLE_APPEARANCE_CYCLING_SPEED_CADENCE 179 
#define  ESP_BLE_APPEARANCE_GENERIC_BARCODE_SCANNER 178 
#define  ESP_BLE_APPEARANCE_GENERIC_BLOOD_PRESSURE 177 
#define  ESP_BLE_APPEARANCE_GENERIC_CLOCK 176 
#define  ESP_BLE_APPEARANCE_GENERIC_COMPUTER 175 
#define  ESP_BLE_APPEARANCE_GENERIC_CONTINUOUS_GLUCOSE_MONITOR 174 
#define  ESP_BLE_APPEARANCE_GENERIC_CYCLING 173 
#define  ESP_BLE_APPEARANCE_GENERIC_DISPLAY 172 
#define  ESP_BLE_APPEARANCE_GENERIC_EYEGLASSES 171 
#define  ESP_BLE_APPEARANCE_GENERIC_GLUCOSE 170 
#define  ESP_BLE_APPEARANCE_GENERIC_HEART_RATE 169 
#define  ESP_BLE_APPEARANCE_GENERIC_HID 168 
#define  ESP_BLE_APPEARANCE_GENERIC_INSULIN_PUMP 167 
#define  ESP_BLE_APPEARANCE_GENERIC_KEYRING 166 
#define  ESP_BLE_APPEARANCE_GENERIC_MEDIA_PLAYER 165 
#define  ESP_BLE_APPEARANCE_GENERIC_MEDICATION_DELIVERY 164 
#define  ESP_BLE_APPEARANCE_GENERIC_OUTDOOR_SPORTS 163 
#define  ESP_BLE_APPEARANCE_GENERIC_PERSONAL_MOBILITY_DEVICE 162 
#define  ESP_BLE_APPEARANCE_GENERIC_PHONE 161 
#define  ESP_BLE_APPEARANCE_GENERIC_PULSE_OXIMETER 160 
#define  ESP_BLE_APPEARANCE_GENERIC_REMOTE 159 
#define  ESP_BLE_APPEARANCE_GENERIC_TAG 158 
#define  ESP_BLE_APPEARANCE_GENERIC_THERMOMETER 157 
#define  ESP_BLE_APPEARANCE_GENERIC_WALKING 156 
#define  ESP_BLE_APPEARANCE_GENERIC_WATCH 155 
#define  ESP_BLE_APPEARANCE_GENERIC_WEIGHT 154 
#define  ESP_BLE_APPEARANCE_HEART_RATE_BELT 153 
#define  ESP_BLE_APPEARANCE_HID_BARCODE_SCANNER 152 
#define  ESP_BLE_APPEARANCE_HID_CARD_READER 151 
#define  ESP_BLE_APPEARANCE_HID_DIGITAL_PEN 150 
#define  ESP_BLE_APPEARANCE_HID_DIGITIZER_TABLET 149 
#define  ESP_BLE_APPEARANCE_HID_GAMEPAD 148 
#define  ESP_BLE_APPEARANCE_HID_JOYSTICK 147 
#define  ESP_BLE_APPEARANCE_HID_KEYBOARD 146 
#define  ESP_BLE_APPEARANCE_HID_MOUSE 145 
#define  ESP_BLE_APPEARANCE_INSULIN_PEN 144 
#define  ESP_BLE_APPEARANCE_INSULIN_PUMP_DURABLE_PUMP 143 
#define  ESP_BLE_APPEARANCE_INSULIN_PUMP_PATCH_PUMP 142 
#define  ESP_BLE_APPEARANCE_MOBILITY_SCOOTER 141 
#define  ESP_BLE_APPEARANCE_OUTDOOR_SPORTS_LOCATION 140 
#define  ESP_BLE_APPEARANCE_OUTDOOR_SPORTS_LOCATION_AND_NAV 139 
#define  ESP_BLE_APPEARANCE_OUTDOOR_SPORTS_LOCATION_POD 138 
#define  ESP_BLE_APPEARANCE_OUTDOOR_SPORTS_LOCATION_POD_AND_NAV 137 
#define  ESP_BLE_APPEARANCE_POWERED_WHEELCHAIR 136 
#define  ESP_BLE_APPEARANCE_PULSE_OXIMETER_FINGERTIP 135 
#define  ESP_BLE_APPEARANCE_PULSE_OXIMETER_WRIST 134 
#define  ESP_BLE_APPEARANCE_SPORTS_WATCH 133 
#define  ESP_BLE_APPEARANCE_THERMOMETER_EAR 132 
#define  ESP_BLE_APPEARANCE_UNKNOWN 131 
#define  ESP_BLE_APPEARANCE_WALKING_IN_SHOE 130 
#define  ESP_BLE_APPEARANCE_WALKING_ON_HIP 129 
#define  ESP_BLE_APPEARANCE_WALKING_ON_SHOE 128 
 int /*<<< orphan*/  ESP_BLUEDROID_STATUS_CHECK (int /*<<< orphan*/ ) ; 
 int /*<<< orphan*/  ESP_BLUEDROID_STATUS_ENABLED ; 
 int /*<<< orphan*/  ESP_ERR_INVALID_ARG ; 
 int /*<<< orphan*/  ESP_FAIL ; 
 int /*<<< orphan*/  ESP_OK ; 
 int /*<<< orphan*/  btc_transfer_context (TYPE_2__*,TYPE_3__*,int,int /*<<< orphan*/ *) ; 

esp_err_t esp_ble_gap_config_local_icon (uint16_t icon)
{
    esp_err_t ret;
    btc_msg_t msg;
    btc_ble_gap_args_t arg;

    ESP_BLUEDROID_STATUS_CHECK(ESP_BLUEDROID_STATUS_ENABLED);

    switch (icon) {
    case ESP_BLE_APPEARANCE_GENERIC_PHONE:
    case ESP_BLE_APPEARANCE_GENERIC_COMPUTER:
    case ESP_BLE_APPEARANCE_GENERIC_REMOTE:
    case ESP_BLE_APPEARANCE_GENERIC_THERMOMETER:
    case ESP_BLE_APPEARANCE_THERMOMETER_EAR:
    case ESP_BLE_APPEARANCE_GENERIC_HEART_RATE:
    case ESP_BLE_APPEARANCE_HEART_RATE_BELT:
    case ESP_BLE_APPEARANCE_GENERIC_BLOOD_PRESSURE:
    case ESP_BLE_APPEARANCE_BLOOD_PRESSURE_ARM:
    case ESP_BLE_APPEARANCE_BLOOD_PRESSURE_WRIST:
    case ESP_BLE_APPEARANCE_GENERIC_PULSE_OXIMETER:
    case ESP_BLE_APPEARANCE_PULSE_OXIMETER_FINGERTIP:
    case ESP_BLE_APPEARANCE_PULSE_OXIMETER_WRIST:
    case ESP_BLE_APPEARANCE_GENERIC_GLUCOSE:
    case ESP_BLE_APPEARANCE_GENERIC_WEIGHT:
    case ESP_BLE_APPEARANCE_GENERIC_WALKING:
    case ESP_BLE_APPEARANCE_WALKING_IN_SHOE:
    case ESP_BLE_APPEARANCE_WALKING_ON_SHOE:
    case ESP_BLE_APPEARANCE_WALKING_ON_HIP:
    case ESP_BLE_APPEARANCE_GENERIC_WATCH:
    case ESP_BLE_APPEARANCE_SPORTS_WATCH:
    case ESP_BLE_APPEARANCE_GENERIC_EYEGLASSES:
    case ESP_BLE_APPEARANCE_GENERIC_DISPLAY:
    case ESP_BLE_APPEARANCE_GENERIC_MEDIA_PLAYER:
    case ESP_BLE_APPEARANCE_GENERIC_BARCODE_SCANNER:
    case ESP_BLE_APPEARANCE_HID_BARCODE_SCANNER:
    case ESP_BLE_APPEARANCE_GENERIC_HID:
    case ESP_BLE_APPEARANCE_HID_KEYBOARD:
    case ESP_BLE_APPEARANCE_HID_MOUSE:
    case ESP_BLE_APPEARANCE_HID_JOYSTICK:
    case ESP_BLE_APPEARANCE_HID_GAMEPAD:
    case ESP_BLE_APPEARANCE_HID_DIGITIZER_TABLET:
    case ESP_BLE_APPEARANCE_HID_CARD_READER:
    case ESP_BLE_APPEARANCE_HID_DIGITAL_PEN:
    case ESP_BLE_APPEARANCE_UNKNOWN:
    case ESP_BLE_APPEARANCE_GENERIC_CLOCK:
    case ESP_BLE_APPEARANCE_GENERIC_TAG:
    case ESP_BLE_APPEARANCE_GENERIC_KEYRING:
    case ESP_BLE_APPEARANCE_GENERIC_CYCLING:
    case ESP_BLE_APPEARANCE_CYCLING_COMPUTER:
    case ESP_BLE_APPEARANCE_CYCLING_SPEED:
    case ESP_BLE_APPEARANCE_CYCLING_CADENCE:
    case ESP_BLE_APPEARANCE_CYCLING_POWER:
    case ESP_BLE_APPEARANCE_CYCLING_SPEED_CADENCE:
    case ESP_BLE_APPEARANCE_GENERIC_PERSONAL_MOBILITY_DEVICE:
    case ESP_BLE_APPEARANCE_POWERED_WHEELCHAIR:
    case ESP_BLE_APPEARANCE_MOBILITY_SCOOTER:
    case ESP_BLE_APPEARANCE_GENERIC_CONTINUOUS_GLUCOSE_MONITOR:
    case ESP_BLE_APPEARANCE_GENERIC_INSULIN_PUMP:
    case ESP_BLE_APPEARANCE_INSULIN_PUMP_DURABLE_PUMP:
    case ESP_BLE_APPEARANCE_INSULIN_PUMP_PATCH_PUMP:
    case ESP_BLE_APPEARANCE_INSULIN_PEN:
    case ESP_BLE_APPEARANCE_GENERIC_MEDICATION_DELIVERY:
    case ESP_BLE_APPEARANCE_GENERIC_OUTDOOR_SPORTS:
    case ESP_BLE_APPEARANCE_OUTDOOR_SPORTS_LOCATION:
    case ESP_BLE_APPEARANCE_OUTDOOR_SPORTS_LOCATION_AND_NAV:
    case ESP_BLE_APPEARANCE_OUTDOOR_SPORTS_LOCATION_POD:
    case ESP_BLE_APPEARANCE_OUTDOOR_SPORTS_LOCATION_POD_AND_NAV:
        msg.sig = BTC_SIG_API_CALL;
        msg.pid = BTC_PID_GAP_BLE;
        msg.act = BTC_GAP_BLE_ACT_CONFIG_LOCAL_ICON;
        arg.cfg_local_icon.icon = icon;
        ret = (btc_transfer_context(&msg, &arg, sizeof(btc_ble_gap_args_t), NULL) == BT_STATUS_SUCCESS ? ESP_OK : ESP_FAIL);
        break;
    default:
        ret = ESP_ERR_INVALID_ARG;
        break;
    }
    return ret;
}