#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  int /*<<< orphan*/  __le32 ;

/* Variables and functions */
 int /*<<< orphan*/  SVCMAP (int /*<<< orphan*/ ,int /*<<< orphan*/ ,size_t) ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_11AC ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_4_WIRE_COEX_SUPPORT ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_AP_DFS ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_AP_PS_DETECT_OUT_OF_SYNC ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_AP_UAPSD ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_ATF ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_AUX_CHAN_LOAD_INTF ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_AUX_SPECTRAL_INTF ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_BCN_FILTER ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_BCN_MISS_OFFLOAD ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_BEACON_OFFLOAD ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_BLOCKACK ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_BSS_CHANNEL_INFO_64 ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_BTCOEX ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_BTCOEX_DUTY_CYCLE ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_BURST ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_CHATTER ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_CHECK_CAL_VERSION ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_COEX_FREQAVOID ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_COEX_GPIO ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_CSA_OFFLOAD ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_DBGLOG_WARN2 ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_EARLY_RX ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_ENHANCED_PROXY_STA ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_EXTENDED_NSS_SUPPORT ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_EXT_RES_CFG_SUPPORT ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_FORCE_FW_HANG ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_GPIO ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_GTK_OFFLOAD ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_HOST_DFS_CHECK_SUPPORT ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_HTT_MGMT_TX_COMP_VALID_FLAGS ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_IRAM_TIDS ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_MESH_11S ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_MESH_NON_11S ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_PACKET_POWER_SAVE ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_PEER_CACHING ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_PEER_STATS ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_PERIODIC_CHAN_STAT_SUPPORT ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_PER_PACKET_SW_ENCRYPT ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_PHYERR ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_PROG_GPIO_BAND_SELECT ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_RATECTRL ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_RATECTRL_CACHE ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_REPORT_AIRTIME ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_RESTRT_CHNL_SUPPORT ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_ROAM_OFFLOAD ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_RTT ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_RTT_RESPONDER_ROLE ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_SCAN_OFFLOAD ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_SCAN_SCH ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_SMART_ANTENNA_HW_SUPPORT ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_SMART_ANTENNA_SW_SUPPORT ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_SMART_LOGGING_SUPPORT ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_STA_ADVANCED_PWRSAVE ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_STA_KEEP_ALIVE ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_STA_PWRSAVE ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_STA_UAPSD_BASIC_AUTO_TRIG ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_STA_UAPSD_VAR_AUTO_TRIG ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_TDLS ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_TDLS_CONN_TRACKER_IN_HOST_MODE ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_TDLS_EXPLICIT_MODE_ONLY ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_TDLS_OFFCHAN ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_TDLS_UAPSD_BUFFER_STA ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_TDLS_UAPSD_SLEEP_STA ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_TDLS_WIDER_BANDWIDTH ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_TPC_STATS_FINAL ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_TT ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_TX_DATA_ACK_RSSI ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_TX_ENCAP ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_TX_MODE_DYNAMIC ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_TX_MODE_PUSH_ONLY ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_TX_MODE_PUSH_PULL ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_TX_PWR_PER_PEER ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_VDEV_DIFFERENT_BEACON_INTERVAL_SUPPORT ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_VDEV_DISABLE_4_ADDR_SRC_LRN_SUPPORT ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_VDEV_RX_FILTER ; 
 int /*<<< orphan*/  WMI_10_4_SERVICE_WOW ; 
 int /*<<< orphan*/  WMI_SERVICE_11AC ; 
 int /*<<< orphan*/  WMI_SERVICE_4_WIRE_COEX_SUPPORT ; 
 int /*<<< orphan*/  WMI_SERVICE_AP_DFS ; 
 int /*<<< orphan*/  WMI_SERVICE_AP_PS_DETECT_OUT_OF_SYNC ; 
 int /*<<< orphan*/  WMI_SERVICE_AP_UAPSD ; 
 int /*<<< orphan*/  WMI_SERVICE_ATF ; 
 int /*<<< orphan*/  WMI_SERVICE_AUX_CHAN_LOAD_INTF ; 
 int /*<<< orphan*/  WMI_SERVICE_AUX_SPECTRAL_INTF ; 
 int /*<<< orphan*/  WMI_SERVICE_BCN_FILTER ; 
 int /*<<< orphan*/  WMI_SERVICE_BCN_MISS_OFFLOAD ; 
 int /*<<< orphan*/  WMI_SERVICE_BEACON_OFFLOAD ; 
 int /*<<< orphan*/  WMI_SERVICE_BLOCKACK ; 
 int /*<<< orphan*/  WMI_SERVICE_BSS_CHANNEL_INFO_64 ; 
 int /*<<< orphan*/  WMI_SERVICE_BTCOEX ; 
 int /*<<< orphan*/  WMI_SERVICE_BTCOEX_DUTY_CYCLE ; 
 int /*<<< orphan*/  WMI_SERVICE_BURST ; 
 int /*<<< orphan*/  WMI_SERVICE_CHATTER ; 
 int /*<<< orphan*/  WMI_SERVICE_CHECK_CAL_VERSION ; 
 int /*<<< orphan*/  WMI_SERVICE_COEX_FREQAVOID ; 
 int /*<<< orphan*/  WMI_SERVICE_COEX_GPIO ; 
 int /*<<< orphan*/  WMI_SERVICE_CSA_OFFLOAD ; 
 int /*<<< orphan*/  WMI_SERVICE_DBGLOG_WARN2 ; 
 int /*<<< orphan*/  WMI_SERVICE_EARLY_RX ; 
 int /*<<< orphan*/  WMI_SERVICE_ENHANCED_PROXY_STA ; 
 int /*<<< orphan*/  WMI_SERVICE_EXTENDED_NSS_SUPPORT ; 
 int /*<<< orphan*/  WMI_SERVICE_EXT_RES_CFG_SUPPORT ; 
 int /*<<< orphan*/  WMI_SERVICE_FORCE_FW_HANG ; 
 int /*<<< orphan*/  WMI_SERVICE_GPIO ; 
 int /*<<< orphan*/  WMI_SERVICE_GTK_OFFLOAD ; 
 int /*<<< orphan*/  WMI_SERVICE_HOST_DFS_CHECK_SUPPORT ; 
 int /*<<< orphan*/  WMI_SERVICE_HTT_MGMT_TX_COMP_VALID_FLAGS ; 
 int /*<<< orphan*/  WMI_SERVICE_IRAM_TIDS ; 
 int /*<<< orphan*/  WMI_SERVICE_MESH_11S ; 
 int /*<<< orphan*/  WMI_SERVICE_MESH_NON_11S ; 
 int /*<<< orphan*/  WMI_SERVICE_PACKET_POWER_SAVE ; 
 int /*<<< orphan*/  WMI_SERVICE_PEER_CACHING ; 
 int /*<<< orphan*/  WMI_SERVICE_PEER_STATS ; 
 int /*<<< orphan*/  WMI_SERVICE_PERIODIC_CHAN_STAT_SUPPORT ; 
 int /*<<< orphan*/  WMI_SERVICE_PER_PACKET_SW_ENCRYPT ; 
 int /*<<< orphan*/  WMI_SERVICE_PHYERR ; 
 int /*<<< orphan*/  WMI_SERVICE_PROG_GPIO_BAND_SELECT ; 
 int /*<<< orphan*/  WMI_SERVICE_RATECTRL ; 
 int /*<<< orphan*/  WMI_SERVICE_RATECTRL_CACHE ; 
 int /*<<< orphan*/  WMI_SERVICE_REPORT_AIRTIME ; 
 int /*<<< orphan*/  WMI_SERVICE_RESTRT_CHNL_SUPPORT ; 
 int /*<<< orphan*/  WMI_SERVICE_ROAM_OFFLOAD ; 
 int /*<<< orphan*/  WMI_SERVICE_RTT ; 
 int /*<<< orphan*/  WMI_SERVICE_RTT_RESPONDER_ROLE ; 
 int /*<<< orphan*/  WMI_SERVICE_SCAN_OFFLOAD ; 
 int /*<<< orphan*/  WMI_SERVICE_SCAN_SCH ; 
 int /*<<< orphan*/  WMI_SERVICE_SMART_ANTENNA_HW_SUPPORT ; 
 int /*<<< orphan*/  WMI_SERVICE_SMART_ANTENNA_SW_SUPPORT ; 
 int /*<<< orphan*/  WMI_SERVICE_SMART_LOGGING_SUPPORT ; 
 int /*<<< orphan*/  WMI_SERVICE_STA_ADVANCED_PWRSAVE ; 
 int /*<<< orphan*/  WMI_SERVICE_STA_KEEP_ALIVE ; 
 int /*<<< orphan*/  WMI_SERVICE_STA_PWRSAVE ; 
 int /*<<< orphan*/  WMI_SERVICE_STA_UAPSD_BASIC_AUTO_TRIG ; 
 int /*<<< orphan*/  WMI_SERVICE_STA_UAPSD_VAR_AUTO_TRIG ; 
 int /*<<< orphan*/  WMI_SERVICE_TDLS ; 
 int /*<<< orphan*/  WMI_SERVICE_TDLS_CONN_TRACKER_IN_HOST_MODE ; 
 int /*<<< orphan*/  WMI_SERVICE_TDLS_EXPLICIT_MODE_ONLY ; 
 int /*<<< orphan*/  WMI_SERVICE_TDLS_OFFCHAN ; 
 int /*<<< orphan*/  WMI_SERVICE_TDLS_UAPSD_BUFFER_STA ; 
 int /*<<< orphan*/  WMI_SERVICE_TDLS_UAPSD_SLEEP_STA ; 
 int /*<<< orphan*/  WMI_SERVICE_TDLS_WIDER_BANDWIDTH ; 
 int /*<<< orphan*/  WMI_SERVICE_TPC_STATS_FINAL ; 
 int /*<<< orphan*/  WMI_SERVICE_TT ; 
 int /*<<< orphan*/  WMI_SERVICE_TX_DATA_ACK_RSSI ; 
 int /*<<< orphan*/  WMI_SERVICE_TX_ENCAP ; 
 int /*<<< orphan*/  WMI_SERVICE_TX_MODE_DYNAMIC ; 
 int /*<<< orphan*/  WMI_SERVICE_TX_MODE_PUSH_ONLY ; 
 int /*<<< orphan*/  WMI_SERVICE_TX_MODE_PUSH_PULL ; 
 int /*<<< orphan*/  WMI_SERVICE_TX_PWR_PER_PEER ; 
 int /*<<< orphan*/  WMI_SERVICE_VDEV_DIFFERENT_BEACON_INTERVAL_SUPPORT ; 
 int /*<<< orphan*/  WMI_SERVICE_VDEV_DISABLE_4_ADDR_SRC_LRN_SUPPORT ; 
 int /*<<< orphan*/  WMI_SERVICE_VDEV_RX_FILTER ; 
 int /*<<< orphan*/  WMI_SERVICE_WOW ; 

__attribute__((used)) static inline void wmi_10_4_svc_map(const __le32 *in, unsigned long *out,
				    size_t len)
{
	SVCMAP(WMI_10_4_SERVICE_BEACON_OFFLOAD,
	       WMI_SERVICE_BEACON_OFFLOAD, len);
	SVCMAP(WMI_10_4_SERVICE_SCAN_OFFLOAD,
	       WMI_SERVICE_SCAN_OFFLOAD, len);
	SVCMAP(WMI_10_4_SERVICE_ROAM_OFFLOAD,
	       WMI_SERVICE_ROAM_OFFLOAD, len);
	SVCMAP(WMI_10_4_SERVICE_BCN_MISS_OFFLOAD,
	       WMI_SERVICE_BCN_MISS_OFFLOAD, len);
	SVCMAP(WMI_10_4_SERVICE_STA_PWRSAVE,
	       WMI_SERVICE_STA_PWRSAVE, len);
	SVCMAP(WMI_10_4_SERVICE_STA_ADVANCED_PWRSAVE,
	       WMI_SERVICE_STA_ADVANCED_PWRSAVE, len);
	SVCMAP(WMI_10_4_SERVICE_AP_UAPSD,
	       WMI_SERVICE_AP_UAPSD, len);
	SVCMAP(WMI_10_4_SERVICE_AP_DFS,
	       WMI_SERVICE_AP_DFS, len);
	SVCMAP(WMI_10_4_SERVICE_11AC,
	       WMI_SERVICE_11AC, len);
	SVCMAP(WMI_10_4_SERVICE_BLOCKACK,
	       WMI_SERVICE_BLOCKACK, len);
	SVCMAP(WMI_10_4_SERVICE_PHYERR,
	       WMI_SERVICE_PHYERR, len);
	SVCMAP(WMI_10_4_SERVICE_BCN_FILTER,
	       WMI_SERVICE_BCN_FILTER, len);
	SVCMAP(WMI_10_4_SERVICE_RTT,
	       WMI_SERVICE_RTT, len);
	SVCMAP(WMI_10_4_SERVICE_RATECTRL,
	       WMI_SERVICE_RATECTRL, len);
	SVCMAP(WMI_10_4_SERVICE_WOW,
	       WMI_SERVICE_WOW, len);
	SVCMAP(WMI_10_4_SERVICE_RATECTRL_CACHE,
	       WMI_SERVICE_RATECTRL_CACHE, len);
	SVCMAP(WMI_10_4_SERVICE_IRAM_TIDS,
	       WMI_SERVICE_IRAM_TIDS, len);
	SVCMAP(WMI_10_4_SERVICE_BURST,
	       WMI_SERVICE_BURST, len);
	SVCMAP(WMI_10_4_SERVICE_SMART_ANTENNA_SW_SUPPORT,
	       WMI_SERVICE_SMART_ANTENNA_SW_SUPPORT, len);
	SVCMAP(WMI_10_4_SERVICE_GTK_OFFLOAD,
	       WMI_SERVICE_GTK_OFFLOAD, len);
	SVCMAP(WMI_10_4_SERVICE_SCAN_SCH,
	       WMI_SERVICE_SCAN_SCH, len);
	SVCMAP(WMI_10_4_SERVICE_CSA_OFFLOAD,
	       WMI_SERVICE_CSA_OFFLOAD, len);
	SVCMAP(WMI_10_4_SERVICE_CHATTER,
	       WMI_SERVICE_CHATTER, len);
	SVCMAP(WMI_10_4_SERVICE_COEX_FREQAVOID,
	       WMI_SERVICE_COEX_FREQAVOID, len);
	SVCMAP(WMI_10_4_SERVICE_PACKET_POWER_SAVE,
	       WMI_SERVICE_PACKET_POWER_SAVE, len);
	SVCMAP(WMI_10_4_SERVICE_FORCE_FW_HANG,
	       WMI_SERVICE_FORCE_FW_HANG, len);
	SVCMAP(WMI_10_4_SERVICE_SMART_ANTENNA_HW_SUPPORT,
	       WMI_SERVICE_SMART_ANTENNA_HW_SUPPORT, len);
	SVCMAP(WMI_10_4_SERVICE_GPIO,
	       WMI_SERVICE_GPIO, len);
	SVCMAP(WMI_10_4_SERVICE_STA_UAPSD_BASIC_AUTO_TRIG,
	       WMI_SERVICE_STA_UAPSD_BASIC_AUTO_TRIG, len);
	SVCMAP(WMI_10_4_SERVICE_STA_UAPSD_VAR_AUTO_TRIG,
	       WMI_SERVICE_STA_UAPSD_VAR_AUTO_TRIG, len);
	SVCMAP(WMI_10_4_SERVICE_STA_KEEP_ALIVE,
	       WMI_SERVICE_STA_KEEP_ALIVE, len);
	SVCMAP(WMI_10_4_SERVICE_TX_ENCAP,
	       WMI_SERVICE_TX_ENCAP, len);
	SVCMAP(WMI_10_4_SERVICE_AP_PS_DETECT_OUT_OF_SYNC,
	       WMI_SERVICE_AP_PS_DETECT_OUT_OF_SYNC, len);
	SVCMAP(WMI_10_4_SERVICE_EARLY_RX,
	       WMI_SERVICE_EARLY_RX, len);
	SVCMAP(WMI_10_4_SERVICE_ENHANCED_PROXY_STA,
	       WMI_SERVICE_ENHANCED_PROXY_STA, len);
	SVCMAP(WMI_10_4_SERVICE_TT,
	       WMI_SERVICE_TT, len);
	SVCMAP(WMI_10_4_SERVICE_ATF,
	       WMI_SERVICE_ATF, len);
	SVCMAP(WMI_10_4_SERVICE_PEER_CACHING,
	       WMI_SERVICE_PEER_CACHING, len);
	SVCMAP(WMI_10_4_SERVICE_COEX_GPIO,
	       WMI_SERVICE_COEX_GPIO, len);
	SVCMAP(WMI_10_4_SERVICE_AUX_SPECTRAL_INTF,
	       WMI_SERVICE_AUX_SPECTRAL_INTF, len);
	SVCMAP(WMI_10_4_SERVICE_AUX_CHAN_LOAD_INTF,
	       WMI_SERVICE_AUX_CHAN_LOAD_INTF, len);
	SVCMAP(WMI_10_4_SERVICE_BSS_CHANNEL_INFO_64,
	       WMI_SERVICE_BSS_CHANNEL_INFO_64, len);
	SVCMAP(WMI_10_4_SERVICE_EXT_RES_CFG_SUPPORT,
	       WMI_SERVICE_EXT_RES_CFG_SUPPORT, len);
	SVCMAP(WMI_10_4_SERVICE_MESH_NON_11S,
	       WMI_SERVICE_MESH_NON_11S, len);
	SVCMAP(WMI_10_4_SERVICE_RESTRT_CHNL_SUPPORT,
	       WMI_SERVICE_RESTRT_CHNL_SUPPORT, len);
	SVCMAP(WMI_10_4_SERVICE_PEER_STATS,
	       WMI_SERVICE_PEER_STATS, len);
	SVCMAP(WMI_10_4_SERVICE_MESH_11S,
	       WMI_SERVICE_MESH_11S, len);
	SVCMAP(WMI_10_4_SERVICE_PERIODIC_CHAN_STAT_SUPPORT,
	       WMI_SERVICE_PERIODIC_CHAN_STAT_SUPPORT, len);
	SVCMAP(WMI_10_4_SERVICE_TX_MODE_PUSH_ONLY,
	       WMI_SERVICE_TX_MODE_PUSH_ONLY, len);
	SVCMAP(WMI_10_4_SERVICE_TX_MODE_PUSH_PULL,
	       WMI_SERVICE_TX_MODE_PUSH_PULL, len);
	SVCMAP(WMI_10_4_SERVICE_TX_MODE_DYNAMIC,
	       WMI_SERVICE_TX_MODE_DYNAMIC, len);
	SVCMAP(WMI_10_4_SERVICE_VDEV_RX_FILTER,
	       WMI_SERVICE_VDEV_RX_FILTER, len);
	SVCMAP(WMI_10_4_SERVICE_BTCOEX,
	       WMI_SERVICE_BTCOEX, len);
	SVCMAP(WMI_10_4_SERVICE_CHECK_CAL_VERSION,
	       WMI_SERVICE_CHECK_CAL_VERSION, len);
	SVCMAP(WMI_10_4_SERVICE_DBGLOG_WARN2,
	       WMI_SERVICE_DBGLOG_WARN2, len);
	SVCMAP(WMI_10_4_SERVICE_BTCOEX_DUTY_CYCLE,
	       WMI_SERVICE_BTCOEX_DUTY_CYCLE, len);
	SVCMAP(WMI_10_4_SERVICE_4_WIRE_COEX_SUPPORT,
	       WMI_SERVICE_4_WIRE_COEX_SUPPORT, len);
	SVCMAP(WMI_10_4_SERVICE_EXTENDED_NSS_SUPPORT,
	       WMI_SERVICE_EXTENDED_NSS_SUPPORT, len);
	SVCMAP(WMI_10_4_SERVICE_PROG_GPIO_BAND_SELECT,
	       WMI_SERVICE_PROG_GPIO_BAND_SELECT, len);
	SVCMAP(WMI_10_4_SERVICE_SMART_LOGGING_SUPPORT,
	       WMI_SERVICE_SMART_LOGGING_SUPPORT, len);
	SVCMAP(WMI_10_4_SERVICE_TDLS,
	       WMI_SERVICE_TDLS, len);
	SVCMAP(WMI_10_4_SERVICE_TDLS_OFFCHAN,
	       WMI_SERVICE_TDLS_OFFCHAN, len);
	SVCMAP(WMI_10_4_SERVICE_TDLS_UAPSD_BUFFER_STA,
	       WMI_SERVICE_TDLS_UAPSD_BUFFER_STA, len);
	SVCMAP(WMI_10_4_SERVICE_TDLS_UAPSD_SLEEP_STA,
	       WMI_SERVICE_TDLS_UAPSD_SLEEP_STA, len);
	SVCMAP(WMI_10_4_SERVICE_TDLS_CONN_TRACKER_IN_HOST_MODE,
	       WMI_SERVICE_TDLS_CONN_TRACKER_IN_HOST_MODE, len);
	SVCMAP(WMI_10_4_SERVICE_TDLS_EXPLICIT_MODE_ONLY,
	       WMI_SERVICE_TDLS_EXPLICIT_MODE_ONLY, len);
	SVCMAP(WMI_10_4_SERVICE_TDLS_WIDER_BANDWIDTH,
	       WMI_SERVICE_TDLS_WIDER_BANDWIDTH, len);
	SVCMAP(WMI_10_4_SERVICE_HTT_MGMT_TX_COMP_VALID_FLAGS,
	       WMI_SERVICE_HTT_MGMT_TX_COMP_VALID_FLAGS, len);
	SVCMAP(WMI_10_4_SERVICE_HOST_DFS_CHECK_SUPPORT,
	       WMI_SERVICE_HOST_DFS_CHECK_SUPPORT, len);
	SVCMAP(WMI_10_4_SERVICE_TPC_STATS_FINAL,
	       WMI_SERVICE_TPC_STATS_FINAL, len);
	SVCMAP(WMI_10_4_SERVICE_TX_DATA_ACK_RSSI,
	       WMI_SERVICE_TX_DATA_ACK_RSSI, len);
	SVCMAP(WMI_10_4_SERVICE_VDEV_DIFFERENT_BEACON_INTERVAL_SUPPORT,
	       WMI_SERVICE_VDEV_DIFFERENT_BEACON_INTERVAL_SUPPORT, len);
	SVCMAP(WMI_10_4_SERVICE_VDEV_DISABLE_4_ADDR_SRC_LRN_SUPPORT,
	       WMI_SERVICE_VDEV_DISABLE_4_ADDR_SRC_LRN_SUPPORT, len);
	SVCMAP(WMI_10_4_SERVICE_RTT_RESPONDER_ROLE,
	       WMI_SERVICE_RTT_RESPONDER_ROLE, len);
	SVCMAP(WMI_10_4_SERVICE_PER_PACKET_SW_ENCRYPT,
	       WMI_SERVICE_PER_PACKET_SW_ENCRYPT, len);
	SVCMAP(WMI_10_4_SERVICE_REPORT_AIRTIME,
	       WMI_SERVICE_REPORT_AIRTIME, len);
	SVCMAP(WMI_10_4_SERVICE_TX_PWR_PER_PEER,
	       WMI_SERVICE_TX_PWR_PER_PEER, len);
}