#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  int u32 ;
struct qed_ptt {int dummy; } ;
struct qed_hwfn {int dummy; } ;

/* Variables and functions */
 int /*<<< orphan*/  DP_INFO (struct qed_hwfn*,char*,int) ; 
 int EINVAL ; 
#define  ETH_TRANSCEIVER_TYPE_1000BASET 167 
#define  ETH_TRANSCEIVER_TYPE_100G_ACC 166 
#define  ETH_TRANSCEIVER_TYPE_100G_AOC 165 
#define  ETH_TRANSCEIVER_TYPE_100G_CR4 164 
#define  ETH_TRANSCEIVER_TYPE_100G_ER4 163 
#define  ETH_TRANSCEIVER_TYPE_100G_LR4 162 
#define  ETH_TRANSCEIVER_TYPE_100G_SR4 161 
#define  ETH_TRANSCEIVER_TYPE_10G_ACC 160 
#define  ETH_TRANSCEIVER_TYPE_10G_BASET 159 
#define  ETH_TRANSCEIVER_TYPE_10G_ER 158 
#define  ETH_TRANSCEIVER_TYPE_10G_LR 157 
#define  ETH_TRANSCEIVER_TYPE_10G_LRM 156 
#define  ETH_TRANSCEIVER_TYPE_10G_PCC 155 
#define  ETH_TRANSCEIVER_TYPE_10G_SR 154 
#define  ETH_TRANSCEIVER_TYPE_1G_ACC 153 
#define  ETH_TRANSCEIVER_TYPE_1G_LX 152 
#define  ETH_TRANSCEIVER_TYPE_1G_PCC 151 
#define  ETH_TRANSCEIVER_TYPE_1G_SX 150 
#define  ETH_TRANSCEIVER_TYPE_25G_ACC_L 149 
#define  ETH_TRANSCEIVER_TYPE_25G_ACC_M 148 
#define  ETH_TRANSCEIVER_TYPE_25G_ACC_S 147 
#define  ETH_TRANSCEIVER_TYPE_25G_AOC 146 
#define  ETH_TRANSCEIVER_TYPE_25G_CA_L 145 
#define  ETH_TRANSCEIVER_TYPE_25G_CA_N 144 
#define  ETH_TRANSCEIVER_TYPE_25G_CA_S 143 
#define  ETH_TRANSCEIVER_TYPE_25G_LR 142 
#define  ETH_TRANSCEIVER_TYPE_25G_SR 141 
#define  ETH_TRANSCEIVER_TYPE_40G_CR4 140 
#define  ETH_TRANSCEIVER_TYPE_40G_LR4 139 
#define  ETH_TRANSCEIVER_TYPE_40G_SR4 138 
#define  ETH_TRANSCEIVER_TYPE_4x10G 137 
#define  ETH_TRANSCEIVER_TYPE_4x25G_CR 136 
#define  ETH_TRANSCEIVER_TYPE_MULTI_RATE_10G_40G_CR 135 
#define  ETH_TRANSCEIVER_TYPE_MULTI_RATE_10G_40G_LR 134 
#define  ETH_TRANSCEIVER_TYPE_MULTI_RATE_10G_40G_SR 133 
#define  ETH_TRANSCEIVER_TYPE_MULTI_RATE_40G_100G_AOC 132 
#define  ETH_TRANSCEIVER_TYPE_MULTI_RATE_40G_100G_CR 131 
#define  ETH_TRANSCEIVER_TYPE_MULTI_RATE_40G_100G_LR 130 
#define  ETH_TRANSCEIVER_TYPE_MULTI_RATE_40G_100G_SR 129 
#define  ETH_TRANSCEIVER_TYPE_XLPPI 128 
 int NVM_CFG1_PORT_DRV_SPEED_CAPABILITY_MASK_10G ; 
 int NVM_CFG1_PORT_DRV_SPEED_CAPABILITY_MASK_1G ; 
 int NVM_CFG1_PORT_DRV_SPEED_CAPABILITY_MASK_20G ; 
 int NVM_CFG1_PORT_DRV_SPEED_CAPABILITY_MASK_25G ; 
 int NVM_CFG1_PORT_DRV_SPEED_CAPABILITY_MASK_40G ; 
 int NVM_CFG1_PORT_DRV_SPEED_CAPABILITY_MASK_50G ; 
 int NVM_CFG1_PORT_DRV_SPEED_CAPABILITY_MASK_BB_100G ; 
 int qed_is_transceiver_ready (int,int) ; 
 int qed_mcp_get_transceiver_data (struct qed_hwfn*,struct qed_ptt*,int*,int*) ; 

int qed_mcp_trans_speed_mask(struct qed_hwfn *p_hwfn,
			     struct qed_ptt *p_ptt, u32 *p_speed_mask)
{
	u32 transceiver_type, transceiver_state;
	int ret;

	ret = qed_mcp_get_transceiver_data(p_hwfn, p_ptt, &transceiver_state,
					   &transceiver_type);
	if (ret)
		return ret;

	if (qed_is_transceiver_ready(transceiver_state, transceiver_type) ==
				     false)
		return -EINVAL;

	switch (transceiver_type) {
	case ETH_TRANSCEIVER_TYPE_1G_LX:
	case ETH_TRANSCEIVER_TYPE_1G_SX:
	case ETH_TRANSCEIVER_TYPE_1G_PCC:
	case ETH_TRANSCEIVER_TYPE_1G_ACC:
	case ETH_TRANSCEIVER_TYPE_1000BASET:
		*p_speed_mask = NVM_CFG1_PORT_DRV_SPEED_CAPABILITY_MASK_1G;
		break;
	case ETH_TRANSCEIVER_TYPE_10G_SR:
	case ETH_TRANSCEIVER_TYPE_10G_LR:
	case ETH_TRANSCEIVER_TYPE_10G_LRM:
	case ETH_TRANSCEIVER_TYPE_10G_ER:
	case ETH_TRANSCEIVER_TYPE_10G_PCC:
	case ETH_TRANSCEIVER_TYPE_10G_ACC:
	case ETH_TRANSCEIVER_TYPE_4x10G:
		*p_speed_mask = NVM_CFG1_PORT_DRV_SPEED_CAPABILITY_MASK_10G;
		break;
	case ETH_TRANSCEIVER_TYPE_40G_LR4:
	case ETH_TRANSCEIVER_TYPE_40G_SR4:
	case ETH_TRANSCEIVER_TYPE_MULTI_RATE_10G_40G_SR:
	case ETH_TRANSCEIVER_TYPE_MULTI_RATE_10G_40G_LR:
		*p_speed_mask = NVM_CFG1_PORT_DRV_SPEED_CAPABILITY_MASK_40G |
		    NVM_CFG1_PORT_DRV_SPEED_CAPABILITY_MASK_10G;
		break;
	case ETH_TRANSCEIVER_TYPE_100G_AOC:
	case ETH_TRANSCEIVER_TYPE_100G_SR4:
	case ETH_TRANSCEIVER_TYPE_100G_LR4:
	case ETH_TRANSCEIVER_TYPE_100G_ER4:
	case ETH_TRANSCEIVER_TYPE_100G_ACC:
		*p_speed_mask =
		    NVM_CFG1_PORT_DRV_SPEED_CAPABILITY_MASK_BB_100G |
		    NVM_CFG1_PORT_DRV_SPEED_CAPABILITY_MASK_25G;
		break;
	case ETH_TRANSCEIVER_TYPE_25G_SR:
	case ETH_TRANSCEIVER_TYPE_25G_LR:
	case ETH_TRANSCEIVER_TYPE_25G_AOC:
	case ETH_TRANSCEIVER_TYPE_25G_ACC_S:
	case ETH_TRANSCEIVER_TYPE_25G_ACC_M:
	case ETH_TRANSCEIVER_TYPE_25G_ACC_L:
		*p_speed_mask = NVM_CFG1_PORT_DRV_SPEED_CAPABILITY_MASK_25G;
		break;
	case ETH_TRANSCEIVER_TYPE_25G_CA_N:
	case ETH_TRANSCEIVER_TYPE_25G_CA_S:
	case ETH_TRANSCEIVER_TYPE_25G_CA_L:
	case ETH_TRANSCEIVER_TYPE_4x25G_CR:
		*p_speed_mask = NVM_CFG1_PORT_DRV_SPEED_CAPABILITY_MASK_25G |
		    NVM_CFG1_PORT_DRV_SPEED_CAPABILITY_MASK_10G |
		    NVM_CFG1_PORT_DRV_SPEED_CAPABILITY_MASK_1G;
		break;
	case ETH_TRANSCEIVER_TYPE_40G_CR4:
	case ETH_TRANSCEIVER_TYPE_MULTI_RATE_10G_40G_CR:
		*p_speed_mask = NVM_CFG1_PORT_DRV_SPEED_CAPABILITY_MASK_40G |
		    NVM_CFG1_PORT_DRV_SPEED_CAPABILITY_MASK_10G |
		    NVM_CFG1_PORT_DRV_SPEED_CAPABILITY_MASK_1G;
		break;
	case ETH_TRANSCEIVER_TYPE_100G_CR4:
	case ETH_TRANSCEIVER_TYPE_MULTI_RATE_40G_100G_CR:
		*p_speed_mask =
		    NVM_CFG1_PORT_DRV_SPEED_CAPABILITY_MASK_BB_100G |
		    NVM_CFG1_PORT_DRV_SPEED_CAPABILITY_MASK_50G |
		    NVM_CFG1_PORT_DRV_SPEED_CAPABILITY_MASK_40G |
		    NVM_CFG1_PORT_DRV_SPEED_CAPABILITY_MASK_25G |
		    NVM_CFG1_PORT_DRV_SPEED_CAPABILITY_MASK_20G |
		    NVM_CFG1_PORT_DRV_SPEED_CAPABILITY_MASK_10G |
		    NVM_CFG1_PORT_DRV_SPEED_CAPABILITY_MASK_1G;
		break;
	case ETH_TRANSCEIVER_TYPE_MULTI_RATE_40G_100G_SR:
	case ETH_TRANSCEIVER_TYPE_MULTI_RATE_40G_100G_LR:
	case ETH_TRANSCEIVER_TYPE_MULTI_RATE_40G_100G_AOC:
		*p_speed_mask =
		    NVM_CFG1_PORT_DRV_SPEED_CAPABILITY_MASK_BB_100G |
		    NVM_CFG1_PORT_DRV_SPEED_CAPABILITY_MASK_40G |
		    NVM_CFG1_PORT_DRV_SPEED_CAPABILITY_MASK_25G |
		    NVM_CFG1_PORT_DRV_SPEED_CAPABILITY_MASK_10G;
		break;
	case ETH_TRANSCEIVER_TYPE_XLPPI:
		*p_speed_mask = NVM_CFG1_PORT_DRV_SPEED_CAPABILITY_MASK_40G;
		break;
	case ETH_TRANSCEIVER_TYPE_10G_BASET:
		*p_speed_mask = NVM_CFG1_PORT_DRV_SPEED_CAPABILITY_MASK_10G |
		    NVM_CFG1_PORT_DRV_SPEED_CAPABILITY_MASK_1G;
		break;
	default:
		DP_INFO(p_hwfn, "Unknown transceiver type 0x%x\n",
			transceiver_type);
		*p_speed_mask = 0xff;
		break;
	}

	return 0;
}