#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  scalar_t__ u8 ;
typedef  scalar_t__ u32 ;
typedef  int u16 ;
struct mlx5_core_dev {int dummy; } ;

/* Variables and functions */
 int EINVAL ; 
 int EIO ; 
#define  MLX5_CMD_OP_2ERR_QP 302 
#define  MLX5_CMD_OP_2RST_QP 301 
#define  MLX5_CMD_OP_ACCESS_REG 300 
#define  MLX5_CMD_OP_ADD_VXLAN_UDP_DPORT 299 
#define  MLX5_CMD_OP_ALLOC_FLOW_COUNTER 298 
#define  MLX5_CMD_OP_ALLOC_MEMIC 297 
#define  MLX5_CMD_OP_ALLOC_MODIFY_HEADER_CONTEXT 296 
#define  MLX5_CMD_OP_ALLOC_PACKET_REFORMAT_CONTEXT 295 
#define  MLX5_CMD_OP_ALLOC_PD 294 
#define  MLX5_CMD_OP_ALLOC_Q_COUNTER 293 
#define  MLX5_CMD_OP_ALLOC_TRANSPORT_DOMAIN 292 
#define  MLX5_CMD_OP_ALLOC_UAR 291 
#define  MLX5_CMD_OP_ALLOC_XRCD 290 
#define  MLX5_CMD_OP_ARM_DCT_FOR_KEY_VIOLATION 289 
#define  MLX5_CMD_OP_ARM_MONITOR_COUNTER 288 
#define  MLX5_CMD_OP_ARM_RQ 287 
#define  MLX5_CMD_OP_ARM_XRC_SRQ 286 
#define  MLX5_CMD_OP_ARM_XRQ 285 
#define  MLX5_CMD_OP_ATTACH_TO_MCG 284 
#define  MLX5_CMD_OP_CONFIG_INT_MODERATION 283 
#define  MLX5_CMD_OP_CREATE_CQ 282 
#define  MLX5_CMD_OP_CREATE_DCT 281 
#define  MLX5_CMD_OP_CREATE_EQ 280 
#define  MLX5_CMD_OP_CREATE_FLOW_GROUP 279 
#define  MLX5_CMD_OP_CREATE_FLOW_TABLE 278 
#define  MLX5_CMD_OP_CREATE_GENERAL_OBJECT 277 
#define  MLX5_CMD_OP_CREATE_LAG 276 
#define  MLX5_CMD_OP_CREATE_MKEY 275 
#define  MLX5_CMD_OP_CREATE_PSV 274 
#define  MLX5_CMD_OP_CREATE_QOS_PARA_VPORT 273 
#define  MLX5_CMD_OP_CREATE_QP 272 
#define  MLX5_CMD_OP_CREATE_RMP 271 
#define  MLX5_CMD_OP_CREATE_RQ 270 
#define  MLX5_CMD_OP_CREATE_RQT 269 
#define  MLX5_CMD_OP_CREATE_SCHEDULING_ELEMENT 268 
#define  MLX5_CMD_OP_CREATE_SQ 267 
#define  MLX5_CMD_OP_CREATE_SRQ 266 
#define  MLX5_CMD_OP_CREATE_TIR 265 
#define  MLX5_CMD_OP_CREATE_TIS 264 
#define  MLX5_CMD_OP_CREATE_UCTX 263 
#define  MLX5_CMD_OP_CREATE_UMEM 262 
#define  MLX5_CMD_OP_CREATE_VPORT_LAG 261 
#define  MLX5_CMD_OP_CREATE_XRC_SRQ 260 
#define  MLX5_CMD_OP_CREATE_XRQ 259 
#define  MLX5_CMD_OP_DEALLOC_FLOW_COUNTER 258 
#define  MLX5_CMD_OP_DEALLOC_MEMIC 257 
#define  MLX5_CMD_OP_DEALLOC_MODIFY_HEADER_CONTEXT 256 
#define  MLX5_CMD_OP_DEALLOC_PACKET_REFORMAT_CONTEXT 255 
#define  MLX5_CMD_OP_DEALLOC_PD 254 
#define  MLX5_CMD_OP_DEALLOC_Q_COUNTER 253 
#define  MLX5_CMD_OP_DEALLOC_TRANSPORT_DOMAIN 252 
#define  MLX5_CMD_OP_DEALLOC_UAR 251 
#define  MLX5_CMD_OP_DEALLOC_XRCD 250 
#define  MLX5_CMD_OP_DELETE_FLOW_TABLE_ENTRY 249 
#define  MLX5_CMD_OP_DELETE_L2_TABLE_ENTRY 248 
#define  MLX5_CMD_OP_DELETE_VXLAN_UDP_DPORT 247 
#define  MLX5_CMD_OP_DESTROY_CQ 246 
#define  MLX5_CMD_OP_DESTROY_DCT 245 
#define  MLX5_CMD_OP_DESTROY_EQ 244 
#define  MLX5_CMD_OP_DESTROY_FLOW_GROUP 243 
#define  MLX5_CMD_OP_DESTROY_FLOW_TABLE 242 
#define  MLX5_CMD_OP_DESTROY_GENERAL_OBJECT 241 
#define  MLX5_CMD_OP_DESTROY_LAG 240 
#define  MLX5_CMD_OP_DESTROY_MKEY 239 
#define  MLX5_CMD_OP_DESTROY_PSV 238 
#define  MLX5_CMD_OP_DESTROY_QOS_PARA_VPORT 237 
#define  MLX5_CMD_OP_DESTROY_QP 236 
#define  MLX5_CMD_OP_DESTROY_RMP 235 
#define  MLX5_CMD_OP_DESTROY_RQ 234 
#define  MLX5_CMD_OP_DESTROY_RQT 233 
#define  MLX5_CMD_OP_DESTROY_SCHEDULING_ELEMENT 232 
#define  MLX5_CMD_OP_DESTROY_SQ 231 
#define  MLX5_CMD_OP_DESTROY_SRQ 230 
#define  MLX5_CMD_OP_DESTROY_TIR 229 
#define  MLX5_CMD_OP_DESTROY_TIS 228 
#define  MLX5_CMD_OP_DESTROY_UCTX 227 
#define  MLX5_CMD_OP_DESTROY_UMEM 226 
#define  MLX5_CMD_OP_DESTROY_VPORT_LAG 225 
#define  MLX5_CMD_OP_DESTROY_XRC_SRQ 224 
#define  MLX5_CMD_OP_DESTROY_XRQ 223 
#define  MLX5_CMD_OP_DETACH_FROM_MCG 222 
#define  MLX5_CMD_OP_DISABLE_HCA 221 
#define  MLX5_CMD_OP_DRAIN_DCT 220 
#define  MLX5_CMD_OP_ENABLE_HCA 219 
#define  MLX5_CMD_OP_FPGA_CREATE_QP 218 
#define  MLX5_CMD_OP_FPGA_DESTROY_QP 217 
#define  MLX5_CMD_OP_FPGA_MODIFY_QP 216 
#define  MLX5_CMD_OP_FPGA_QUERY_QP 215 
#define  MLX5_CMD_OP_FPGA_QUERY_QP_COUNTERS 214 
#define  MLX5_CMD_OP_GEN_EQE 213 
#define  MLX5_CMD_OP_GET_DROPPED_PACKET_LOG 212 
#define  MLX5_CMD_OP_INIT2INIT_QP 211 
#define  MLX5_CMD_OP_INIT2RTR_QP 210 
#define  MLX5_CMD_OP_INIT_HCA 209 
#define  MLX5_CMD_OP_MAD_IFC 208 
#define  MLX5_CMD_OP_MANAGE_PAGES 207 
#define  MLX5_CMD_OP_MODIFY_CONG_PARAMS 206 
#define  MLX5_CMD_OP_MODIFY_CONG_STATUS 205 
#define  MLX5_CMD_OP_MODIFY_CQ 204 
#define  MLX5_CMD_OP_MODIFY_ESW_VPORT_CONTEXT 203 
#define  MLX5_CMD_OP_MODIFY_FLOW_TABLE 202 
#define  MLX5_CMD_OP_MODIFY_GENERAL_OBJECT 201 
#define  MLX5_CMD_OP_MODIFY_HCA_VPORT_CONTEXT 200 
#define  MLX5_CMD_OP_MODIFY_LAG 199 
#define  MLX5_CMD_OP_MODIFY_NIC_VPORT_CONTEXT 198 
#define  MLX5_CMD_OP_MODIFY_RMP 197 
#define  MLX5_CMD_OP_MODIFY_RQ 196 
#define  MLX5_CMD_OP_MODIFY_RQT 195 
#define  MLX5_CMD_OP_MODIFY_SCHEDULING_ELEMENT 194 
#define  MLX5_CMD_OP_MODIFY_SQ 193 
#define  MLX5_CMD_OP_MODIFY_TIR 192 
#define  MLX5_CMD_OP_MODIFY_TIS 191 
#define  MLX5_CMD_OP_MODIFY_VPORT_STATE 190 
#define  MLX5_CMD_OP_MODIFY_XRQ 189 
#define  MLX5_CMD_OP_NOP 188 
#define  MLX5_CMD_OP_PAGE_FAULT_RESUME 187 
#define  MLX5_CMD_OP_QUERY_ADAPTER 186 
#define  MLX5_CMD_OP_QUERY_CONG_PARAMS 185 
#define  MLX5_CMD_OP_QUERY_CONG_STATISTICS 184 
#define  MLX5_CMD_OP_QUERY_CONG_STATUS 183 
#define  MLX5_CMD_OP_QUERY_CQ 182 
#define  MLX5_CMD_OP_QUERY_DCT 181 
#define  MLX5_CMD_OP_QUERY_EQ 180 
#define  MLX5_CMD_OP_QUERY_ESW_FUNCTIONS 179 
#define  MLX5_CMD_OP_QUERY_ESW_VPORT_CONTEXT 178 
#define  MLX5_CMD_OP_QUERY_FLOW_COUNTER 177 
#define  MLX5_CMD_OP_QUERY_FLOW_GROUP 176 
#define  MLX5_CMD_OP_QUERY_FLOW_TABLE 175 
#define  MLX5_CMD_OP_QUERY_FLOW_TABLE_ENTRY 174 
#define  MLX5_CMD_OP_QUERY_GENERAL_OBJECT 173 
#define  MLX5_CMD_OP_QUERY_HCA_CAP 172 
#define  MLX5_CMD_OP_QUERY_HCA_VPORT_CONTEXT 171 
#define  MLX5_CMD_OP_QUERY_HCA_VPORT_GID 170 
#define  MLX5_CMD_OP_QUERY_HCA_VPORT_PKEY 169 
#define  MLX5_CMD_OP_QUERY_ISSI 168 
#define  MLX5_CMD_OP_QUERY_L2_TABLE_ENTRY 167 
#define  MLX5_CMD_OP_QUERY_LAG 166 
#define  MLX5_CMD_OP_QUERY_MAD_DEMUX 165 
#define  MLX5_CMD_OP_QUERY_MKEY 164 
#define  MLX5_CMD_OP_QUERY_NIC_VPORT_CONTEXT 163 
#define  MLX5_CMD_OP_QUERY_PAGES 162 
#define  MLX5_CMD_OP_QUERY_QP 161 
#define  MLX5_CMD_OP_QUERY_Q_COUNTER 160 
#define  MLX5_CMD_OP_QUERY_RATE_LIMIT 159 
#define  MLX5_CMD_OP_QUERY_RMP 158 
#define  MLX5_CMD_OP_QUERY_ROCE_ADDRESS 157 
#define  MLX5_CMD_OP_QUERY_RQ 156 
#define  MLX5_CMD_OP_QUERY_RQT 155 
#define  MLX5_CMD_OP_QUERY_SCHEDULING_ELEMENT 154 
#define  MLX5_CMD_OP_QUERY_SPECIAL_CONTEXTS 153 
#define  MLX5_CMD_OP_QUERY_SQ 152 
#define  MLX5_CMD_OP_QUERY_SRQ 151 
#define  MLX5_CMD_OP_QUERY_TIR 150 
#define  MLX5_CMD_OP_QUERY_TIS 149 
#define  MLX5_CMD_OP_QUERY_VNIC_ENV 148 
#define  MLX5_CMD_OP_QUERY_VPORT_COUNTER 147 
#define  MLX5_CMD_OP_QUERY_VPORT_STATE 146 
#define  MLX5_CMD_OP_QUERY_XRC_SRQ 145 
#define  MLX5_CMD_OP_QUERY_XRQ 144 
#define  MLX5_CMD_OP_RELEASE_XRQ_ERROR 143 
#define  MLX5_CMD_OP_RST2INIT_QP 142 
#define  MLX5_CMD_OP_RTR2RTS_QP 141 
#define  MLX5_CMD_OP_RTS2RTS_QP 140 
#define  MLX5_CMD_OP_SET_FLOW_TABLE_ENTRY 139 
#define  MLX5_CMD_OP_SET_FLOW_TABLE_ROOT 138 
#define  MLX5_CMD_OP_SET_HCA_CAP 137 
#define  MLX5_CMD_OP_SET_ISSI 136 
#define  MLX5_CMD_OP_SET_L2_TABLE_ENTRY 135 
#define  MLX5_CMD_OP_SET_MAD_DEMUX 134 
#define  MLX5_CMD_OP_SET_MONITOR_COUNTER 133 
#define  MLX5_CMD_OP_SET_PP_RATE_LIMIT 132 
#define  MLX5_CMD_OP_SET_ROCE_ADDRESS 131 
#define  MLX5_CMD_OP_SQD_RTS_QP 130 
#define  MLX5_CMD_OP_SQERR2RTS_QP 129 
#define  MLX5_CMD_OP_TEARDOWN_HCA 128 
 int MLX5_CMD_STAT_OK ; 
 scalar_t__ MLX5_DRIVER_STATUS_ABORTED ; 
 scalar_t__ MLX5_DRIVER_SYND ; 
 int /*<<< orphan*/  mlx5_core_err (struct mlx5_core_dev*,char*,int) ; 

__attribute__((used)) static int mlx5_internal_err_ret_value(struct mlx5_core_dev *dev, u16 op,
				       u32 *synd, u8 *status)
{
	*synd = 0;
	*status = 0;

	switch (op) {
	case MLX5_CMD_OP_TEARDOWN_HCA:
	case MLX5_CMD_OP_DISABLE_HCA:
	case MLX5_CMD_OP_MANAGE_PAGES:
	case MLX5_CMD_OP_DESTROY_MKEY:
	case MLX5_CMD_OP_DESTROY_EQ:
	case MLX5_CMD_OP_DESTROY_CQ:
	case MLX5_CMD_OP_DESTROY_QP:
	case MLX5_CMD_OP_DESTROY_PSV:
	case MLX5_CMD_OP_DESTROY_SRQ:
	case MLX5_CMD_OP_DESTROY_XRC_SRQ:
	case MLX5_CMD_OP_DESTROY_XRQ:
	case MLX5_CMD_OP_DESTROY_DCT:
	case MLX5_CMD_OP_DEALLOC_Q_COUNTER:
	case MLX5_CMD_OP_DESTROY_SCHEDULING_ELEMENT:
	case MLX5_CMD_OP_DESTROY_QOS_PARA_VPORT:
	case MLX5_CMD_OP_DEALLOC_PD:
	case MLX5_CMD_OP_DEALLOC_UAR:
	case MLX5_CMD_OP_DETACH_FROM_MCG:
	case MLX5_CMD_OP_DEALLOC_XRCD:
	case MLX5_CMD_OP_DEALLOC_TRANSPORT_DOMAIN:
	case MLX5_CMD_OP_DELETE_VXLAN_UDP_DPORT:
	case MLX5_CMD_OP_DELETE_L2_TABLE_ENTRY:
	case MLX5_CMD_OP_DESTROY_LAG:
	case MLX5_CMD_OP_DESTROY_VPORT_LAG:
	case MLX5_CMD_OP_DESTROY_TIR:
	case MLX5_CMD_OP_DESTROY_SQ:
	case MLX5_CMD_OP_DESTROY_RQ:
	case MLX5_CMD_OP_DESTROY_RMP:
	case MLX5_CMD_OP_DESTROY_TIS:
	case MLX5_CMD_OP_DESTROY_RQT:
	case MLX5_CMD_OP_DESTROY_FLOW_TABLE:
	case MLX5_CMD_OP_DESTROY_FLOW_GROUP:
	case MLX5_CMD_OP_DELETE_FLOW_TABLE_ENTRY:
	case MLX5_CMD_OP_DEALLOC_FLOW_COUNTER:
	case MLX5_CMD_OP_2ERR_QP:
	case MLX5_CMD_OP_2RST_QP:
	case MLX5_CMD_OP_MODIFY_NIC_VPORT_CONTEXT:
	case MLX5_CMD_OP_MODIFY_FLOW_TABLE:
	case MLX5_CMD_OP_SET_FLOW_TABLE_ENTRY:
	case MLX5_CMD_OP_SET_FLOW_TABLE_ROOT:
	case MLX5_CMD_OP_DEALLOC_PACKET_REFORMAT_CONTEXT:
	case MLX5_CMD_OP_DEALLOC_MODIFY_HEADER_CONTEXT:
	case MLX5_CMD_OP_FPGA_DESTROY_QP:
	case MLX5_CMD_OP_DESTROY_GENERAL_OBJECT:
	case MLX5_CMD_OP_DEALLOC_MEMIC:
	case MLX5_CMD_OP_PAGE_FAULT_RESUME:
	case MLX5_CMD_OP_QUERY_ESW_FUNCTIONS:
		return MLX5_CMD_STAT_OK;

	case MLX5_CMD_OP_QUERY_HCA_CAP:
	case MLX5_CMD_OP_QUERY_ADAPTER:
	case MLX5_CMD_OP_INIT_HCA:
	case MLX5_CMD_OP_ENABLE_HCA:
	case MLX5_CMD_OP_QUERY_PAGES:
	case MLX5_CMD_OP_SET_HCA_CAP:
	case MLX5_CMD_OP_QUERY_ISSI:
	case MLX5_CMD_OP_SET_ISSI:
	case MLX5_CMD_OP_CREATE_MKEY:
	case MLX5_CMD_OP_QUERY_MKEY:
	case MLX5_CMD_OP_QUERY_SPECIAL_CONTEXTS:
	case MLX5_CMD_OP_CREATE_EQ:
	case MLX5_CMD_OP_QUERY_EQ:
	case MLX5_CMD_OP_GEN_EQE:
	case MLX5_CMD_OP_CREATE_CQ:
	case MLX5_CMD_OP_QUERY_CQ:
	case MLX5_CMD_OP_MODIFY_CQ:
	case MLX5_CMD_OP_CREATE_QP:
	case MLX5_CMD_OP_RST2INIT_QP:
	case MLX5_CMD_OP_INIT2RTR_QP:
	case MLX5_CMD_OP_RTR2RTS_QP:
	case MLX5_CMD_OP_RTS2RTS_QP:
	case MLX5_CMD_OP_SQERR2RTS_QP:
	case MLX5_CMD_OP_QUERY_QP:
	case MLX5_CMD_OP_SQD_RTS_QP:
	case MLX5_CMD_OP_INIT2INIT_QP:
	case MLX5_CMD_OP_CREATE_PSV:
	case MLX5_CMD_OP_CREATE_SRQ:
	case MLX5_CMD_OP_QUERY_SRQ:
	case MLX5_CMD_OP_ARM_RQ:
	case MLX5_CMD_OP_CREATE_XRC_SRQ:
	case MLX5_CMD_OP_QUERY_XRC_SRQ:
	case MLX5_CMD_OP_ARM_XRC_SRQ:
	case MLX5_CMD_OP_CREATE_XRQ:
	case MLX5_CMD_OP_QUERY_XRQ:
	case MLX5_CMD_OP_ARM_XRQ:
	case MLX5_CMD_OP_CREATE_DCT:
	case MLX5_CMD_OP_DRAIN_DCT:
	case MLX5_CMD_OP_QUERY_DCT:
	case MLX5_CMD_OP_ARM_DCT_FOR_KEY_VIOLATION:
	case MLX5_CMD_OP_QUERY_VPORT_STATE:
	case MLX5_CMD_OP_MODIFY_VPORT_STATE:
	case MLX5_CMD_OP_QUERY_ESW_VPORT_CONTEXT:
	case MLX5_CMD_OP_MODIFY_ESW_VPORT_CONTEXT:
	case MLX5_CMD_OP_QUERY_NIC_VPORT_CONTEXT:
	case MLX5_CMD_OP_QUERY_ROCE_ADDRESS:
	case MLX5_CMD_OP_SET_ROCE_ADDRESS:
	case MLX5_CMD_OP_QUERY_HCA_VPORT_CONTEXT:
	case MLX5_CMD_OP_MODIFY_HCA_VPORT_CONTEXT:
	case MLX5_CMD_OP_QUERY_HCA_VPORT_GID:
	case MLX5_CMD_OP_QUERY_HCA_VPORT_PKEY:
	case MLX5_CMD_OP_QUERY_VNIC_ENV:
	case MLX5_CMD_OP_QUERY_VPORT_COUNTER:
	case MLX5_CMD_OP_ALLOC_Q_COUNTER:
	case MLX5_CMD_OP_QUERY_Q_COUNTER:
	case MLX5_CMD_OP_SET_MONITOR_COUNTER:
	case MLX5_CMD_OP_ARM_MONITOR_COUNTER:
	case MLX5_CMD_OP_SET_PP_RATE_LIMIT:
	case MLX5_CMD_OP_QUERY_RATE_LIMIT:
	case MLX5_CMD_OP_CREATE_SCHEDULING_ELEMENT:
	case MLX5_CMD_OP_QUERY_SCHEDULING_ELEMENT:
	case MLX5_CMD_OP_MODIFY_SCHEDULING_ELEMENT:
	case MLX5_CMD_OP_CREATE_QOS_PARA_VPORT:
	case MLX5_CMD_OP_ALLOC_PD:
	case MLX5_CMD_OP_ALLOC_UAR:
	case MLX5_CMD_OP_CONFIG_INT_MODERATION:
	case MLX5_CMD_OP_ACCESS_REG:
	case MLX5_CMD_OP_ATTACH_TO_MCG:
	case MLX5_CMD_OP_GET_DROPPED_PACKET_LOG:
	case MLX5_CMD_OP_MAD_IFC:
	case MLX5_CMD_OP_QUERY_MAD_DEMUX:
	case MLX5_CMD_OP_SET_MAD_DEMUX:
	case MLX5_CMD_OP_NOP:
	case MLX5_CMD_OP_ALLOC_XRCD:
	case MLX5_CMD_OP_ALLOC_TRANSPORT_DOMAIN:
	case MLX5_CMD_OP_QUERY_CONG_STATUS:
	case MLX5_CMD_OP_MODIFY_CONG_STATUS:
	case MLX5_CMD_OP_QUERY_CONG_PARAMS:
	case MLX5_CMD_OP_MODIFY_CONG_PARAMS:
	case MLX5_CMD_OP_QUERY_CONG_STATISTICS:
	case MLX5_CMD_OP_ADD_VXLAN_UDP_DPORT:
	case MLX5_CMD_OP_SET_L2_TABLE_ENTRY:
	case MLX5_CMD_OP_QUERY_L2_TABLE_ENTRY:
	case MLX5_CMD_OP_CREATE_LAG:
	case MLX5_CMD_OP_MODIFY_LAG:
	case MLX5_CMD_OP_QUERY_LAG:
	case MLX5_CMD_OP_CREATE_VPORT_LAG:
	case MLX5_CMD_OP_CREATE_TIR:
	case MLX5_CMD_OP_MODIFY_TIR:
	case MLX5_CMD_OP_QUERY_TIR:
	case MLX5_CMD_OP_CREATE_SQ:
	case MLX5_CMD_OP_MODIFY_SQ:
	case MLX5_CMD_OP_QUERY_SQ:
	case MLX5_CMD_OP_CREATE_RQ:
	case MLX5_CMD_OP_MODIFY_RQ:
	case MLX5_CMD_OP_QUERY_RQ:
	case MLX5_CMD_OP_CREATE_RMP:
	case MLX5_CMD_OP_MODIFY_RMP:
	case MLX5_CMD_OP_QUERY_RMP:
	case MLX5_CMD_OP_CREATE_TIS:
	case MLX5_CMD_OP_MODIFY_TIS:
	case MLX5_CMD_OP_QUERY_TIS:
	case MLX5_CMD_OP_CREATE_RQT:
	case MLX5_CMD_OP_MODIFY_RQT:
	case MLX5_CMD_OP_QUERY_RQT:

	case MLX5_CMD_OP_CREATE_FLOW_TABLE:
	case MLX5_CMD_OP_QUERY_FLOW_TABLE:
	case MLX5_CMD_OP_CREATE_FLOW_GROUP:
	case MLX5_CMD_OP_QUERY_FLOW_GROUP:
	case MLX5_CMD_OP_QUERY_FLOW_TABLE_ENTRY:
	case MLX5_CMD_OP_ALLOC_FLOW_COUNTER:
	case MLX5_CMD_OP_QUERY_FLOW_COUNTER:
	case MLX5_CMD_OP_ALLOC_PACKET_REFORMAT_CONTEXT:
	case MLX5_CMD_OP_ALLOC_MODIFY_HEADER_CONTEXT:
	case MLX5_CMD_OP_FPGA_CREATE_QP:
	case MLX5_CMD_OP_FPGA_MODIFY_QP:
	case MLX5_CMD_OP_FPGA_QUERY_QP:
	case MLX5_CMD_OP_FPGA_QUERY_QP_COUNTERS:
	case MLX5_CMD_OP_CREATE_GENERAL_OBJECT:
	case MLX5_CMD_OP_MODIFY_GENERAL_OBJECT:
	case MLX5_CMD_OP_QUERY_GENERAL_OBJECT:
	case MLX5_CMD_OP_CREATE_UCTX:
	case MLX5_CMD_OP_DESTROY_UCTX:
	case MLX5_CMD_OP_CREATE_UMEM:
	case MLX5_CMD_OP_DESTROY_UMEM:
	case MLX5_CMD_OP_ALLOC_MEMIC:
	case MLX5_CMD_OP_MODIFY_XRQ:
	case MLX5_CMD_OP_RELEASE_XRQ_ERROR:
		*status = MLX5_DRIVER_STATUS_ABORTED;
		*synd = MLX5_DRIVER_SYND;
		return -EIO;
	default:
		mlx5_core_err(dev, "Unknown FW command (%d)\n", op);
		return -EINVAL;
	}
}