#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */

/* Variables and functions */
 int /*<<< orphan*/  fprintf (int /*<<< orphan*/ ,char*) ; 
 int /*<<< orphan*/  stderr ; 
 int /*<<< orphan*/  stdout ; 

void
usage(int printlong)
{

	fprintf(printlong ? stdout : stderr,
"usage:  camcontrol <command>  [device id][generic args][command args]\n"
"        camcontrol devlist    [-b] [-v]\n"
"        camcontrol periphlist [dev_id][-n dev_name] [-u unit]\n"
"        camcontrol tur        [dev_id][generic args]\n"
"        camcontrol inquiry    [dev_id][generic args] [-D] [-S] [-R]\n"
"        camcontrol identify   [dev_id][generic args] [-v]\n"
"        camcontrol reportluns [dev_id][generic args] [-c] [-l] [-r report]\n"
"        camcontrol readcap    [dev_id][generic args] [-b] [-h] [-H] [-N]\n"
"                              [-q] [-s] [-l]\n"
"        camcontrol start      [dev_id][generic args]\n"
"        camcontrol stop       [dev_id][generic args]\n"
"        camcontrol load       [dev_id][generic args]\n"
"        camcontrol eject      [dev_id][generic args]\n"
"        camcontrol reprobe    [dev_id][generic args]\n"
"        camcontrol rescan     <all | bus[:target:lun] | dev_id>\n"
"        camcontrol reset      <all | bus[:target:lun] | dev_id>\n"
"        camcontrol defects    [dev_id][generic args] <-f format> [-P][-G]\n"
"                              [-q][-s][-S offset][-X]\n"
"        camcontrol modepage   [dev_id][generic args] <-m page | -l>\n"
"                              [-P pagectl][-e | -b][-d]\n"
"        camcontrol cmd        [dev_id][generic args]\n"
"                              <-a cmd [args] | -c cmd [args]>\n"
"                              [-d] [-f] [-i len fmt|-o len fmt [args]] [-r fmt]\n"
"        camcontrol smpcmd     [dev_id][generic args]\n"
"                              <-r len fmt [args]> <-R len fmt [args]>\n"
"        camcontrol smprg      [dev_id][generic args][-l]\n"
"        camcontrol smppc      [dev_id][generic args] <-p phy> [-l]\n"
"                              [-o operation][-d name][-m rate][-M rate]\n"
"                              [-T pp_timeout][-a enable|disable]\n"
"                              [-A enable|disable][-s enable|disable]\n"
"                              [-S enable|disable]\n"
"        camcontrol smpphylist [dev_id][generic args][-l][-q]\n"
"        camcontrol smpmaninfo [dev_id][generic args][-l]\n"
"        camcontrol debug      [-I][-P][-T][-S][-X][-c]\n"
"                              <all|dev_id|bus[:target[:lun]]|off>\n"
"        camcontrol tags       [dev_id][generic args] [-N tags] [-q] [-v]\n"
"        camcontrol negotiate  [dev_id][generic args] [-a][-c]\n"
"                              [-D <enable|disable>][-M mode][-O offset]\n"
"                              [-q][-R syncrate][-v][-T <enable|disable>]\n"
"                              [-U][-W bus_width]\n"
"        camcontrol format     [dev_id][generic args][-q][-r][-w][-y]\n"
"        camcontrol sanitize   [dev_id][generic args]\n"
"                              [-a overwrite|block|crypto|exitfailure]\n"
"                              [-c passes][-I][-P pattern][-q][-U][-r][-w]\n"
"                              [-y]\n"
"        camcontrol idle       [dev_id][generic args][-t time]\n"
"        camcontrol standby    [dev_id][generic args][-t time]\n"
"        camcontrol sleep      [dev_id][generic args]\n"
"        camcontrol powermode  [dev_id][generic args]\n"
"        camcontrol apm        [dev_id][generic args][-l level]\n"
"        camcontrol aam        [dev_id][generic args][-l level]\n"
"        camcontrol fwdownload [dev_id][generic args] <-f fw_image> [-q]\n"
"                              [-s][-y]\n"
"        camcontrol security   [dev_id][generic args]\n"
"                              <-d pwd | -e pwd | -f | -h pwd | -k pwd>\n"
"                              [-l <high|maximum>] [-q] [-s pwd] [-T timeout]\n"
"                              [-U <user|master>] [-y]\n"
"        camcontrol hpa        [dev_id][generic args] [-f] [-l] [-P] [-p pwd]\n"
"                              [-q] [-s max_sectors] [-U pwd] [-y]\n"
"        camcontrol ama        [dev_id][generic args] [-f] [-q] [-s max_sectors]\n"
"        camcontrol persist    [dev_id][generic args] <-i action|-o action>\n"
"                              [-a][-I tid][-k key][-K sa_key][-p][-R rtp]\n"
"                              [-s scope][-S][-T type][-U]\n"
"        camcontrol attrib     [dev_id][generic args] <-r action|-w attr>\n"
"                              [-a attr_num][-c][-e elem][-F form1,form1]\n"
"                              [-p part][-s start][-T type][-V vol]\n"
"        camcontrol opcodes    [dev_id][generic args][-o opcode][-s SA]\n"
"                              [-N][-T]\n"
"        camcontrol zone       [dev_id][generic args]<-c cmd> [-a] [-l LBA]\n"
"                              [-o rep_opts] [-P print_opts]\n"
"        camcontrol epc        [dev_id][generic_args]<-c cmd> [-d] [-D] [-e]\n"
"                              [-H] [-p power_cond] [-P] [-r rst_src] [-s]\n"
"                              [-S power_src] [-T timer]\n"
"        camcontrol timestamp  [dev_id][generic_args] <-r [-f format|-m|-U]>|\n"
"                              <-s <-f format -T time | -U >>\n"
"        camcontrol devtype    [dev_id]\n"
"                              \n"
"        camcontrol help\n");
	if (!printlong)
		return;
	fprintf(stdout,
"Specify one of the following options:\n"
"devlist     list all CAM devices\n"
"periphlist  list all CAM peripheral drivers attached to a device\n"
"tur         send a test unit ready to the named device\n"
"inquiry     send a SCSI inquiry command to the named device\n"
"identify    send a ATA identify command to the named device\n"
"reportluns  send a SCSI report luns command to the device\n"
"readcap     send a SCSI read capacity command to the device\n"
"start       send a Start Unit command to the device\n"
"stop        send a Stop Unit command to the device\n"
"load        send a Start Unit command to the device with the load bit set\n"
"eject       send a Stop Unit command to the device with the eject bit set\n"
"reprobe     update capacity information of the given device\n"
"rescan      rescan all buses, the given bus, bus:target:lun or device\n"
"reset       reset all buses, the given bus, bus:target:lun or device\n"
"defects     read the defect list of the specified device\n"
"modepage    display or edit (-e) the given mode page\n"
"cmd         send the given SCSI command, may need -i or -o as well\n"
"smpcmd      send the given SMP command, requires -o and -i\n"
"smprg       send the SMP Report General command\n"
"smppc       send the SMP PHY Control command, requires -p\n"
"smpphylist  display phys attached to a SAS expander\n"
"smpmaninfo  send the SMP Report Manufacturer Info command\n"
"debug       turn debugging on/off for a bus, target, or lun, or all devices\n"
"tags        report or set the number of transaction slots for a device\n"
"negotiate   report or set device negotiation parameters\n"
"format      send the SCSI FORMAT UNIT command to the named device\n"
"sanitize    send the SCSI SANITIZE command to the named device\n"
"idle        send the ATA IDLE command to the named device\n"
"standby     send the ATA STANDBY command to the named device\n"
"sleep       send the ATA SLEEP command to the named device\n"
"powermode   send the ATA CHECK POWER MODE command to the named device\n"
"fwdownload  program firmware of the named device with the given image\n"
"security    report or send ATA security commands to the named device\n"
"persist     send the SCSI PERSISTENT RESERVE IN or OUT commands\n"
"attrib      send the SCSI READ or WRITE ATTRIBUTE commands\n"
"opcodes     send the SCSI REPORT SUPPORTED OPCODES command\n"
"zone        manage Zoned Block (Shingled) devices\n"
"epc         send ATA Extended Power Conditions commands\n"
"timestamp   report or set the device's timestamp\n"
"devtype     report the type of device\n"
"help        this message\n"
"Device Identifiers:\n"
"bus:target        specify the bus and target, lun defaults to 0\n"
"bus:target:lun    specify the bus, target and lun\n"
"deviceUNIT        specify the device name, like \"da4\" or \"cd2\"\n"
"Generic arguments:\n"
"-v                be verbose, print out sense information\n"
"-t timeout        command timeout in seconds, overrides default timeout\n"
"-n dev_name       specify device name, e.g. \"da\", \"cd\"\n"
"-u unit           specify unit number, e.g. \"0\", \"5\"\n"
"-E                have the kernel attempt to perform SCSI error recovery\n"
"-C count          specify the SCSI command retry count (needs -E to work)\n"
"-Q task_attr      specify ordered, simple or head tag type for SCSI cmds\n"
"modepage arguments:\n"
"-l                list all available mode pages\n"
"-m page           specify the mode page to view or edit\n"
"-e                edit the specified mode page\n"
"-b                force view to binary mode\n"
"-d                disable block descriptors for mode sense\n"
"-P pgctl          page control field 0-3\n"
"defects arguments:\n"
"-f format         specify defect list format (block, bfi or phys)\n"
"-G                get the grown defect list\n"
"-P                get the permanent defect list\n"
"inquiry arguments:\n"
"-D                get the standard inquiry data\n"
"-S                get the serial number\n"
"-R                get the transfer rate, etc.\n"
"reportluns arguments:\n"
"-c                only report a count of available LUNs\n"
"-l                only print out luns, and not a count\n"
"-r <reporttype>   specify \"default\", \"wellknown\" or \"all\"\n"
"readcap arguments\n"
"-b                only report the blocksize\n"
"-h                human readable device size, base 2\n"
"-H                human readable device size, base 10\n"
"-N                print the number of blocks instead of last block\n"
"-q                quiet, print numbers only\n"
"-s                only report the last block/device size\n"
"cmd arguments:\n"
"-c cdb [args]     specify the SCSI CDB\n"
"-i len fmt        specify input data and input data format\n"
"-o len fmt [args] specify output data and output data fmt\n"
"smpcmd arguments:\n"
"-r len fmt [args] specify the SMP command to be sent\n"
"-R len fmt [args] specify SMP response format\n"
"smprg arguments:\n"
"-l                specify the long response format\n"
"smppc arguments:\n"
"-p phy            specify the PHY to operate on\n"
"-l                specify the long request/response format\n"
"-o operation      specify the phy control operation\n"
"-d name           set the attached device name\n"
"-m rate           set the minimum physical link rate\n"
"-M rate           set the maximum physical link rate\n"
"-T pp_timeout     set the partial pathway timeout value\n"
"-a enable|disable enable or disable SATA slumber\n"
"-A enable|disable enable or disable SATA partial phy power\n"
"-s enable|disable enable or disable SAS slumber\n"
"-S enable|disable enable or disable SAS partial phy power\n"
"smpphylist arguments:\n"
"-l                specify the long response format\n"
"-q                only print phys with attached devices\n"
"smpmaninfo arguments:\n"
"-l                specify the long response format\n"
"debug arguments:\n"
"-I                CAM_DEBUG_INFO -- scsi commands, errors, data\n"
"-T                CAM_DEBUG_TRACE -- routine flow tracking\n"
"-S                CAM_DEBUG_SUBTRACE -- internal routine command flow\n"
"-c                CAM_DEBUG_CDB -- print out SCSI CDBs only\n"
"tags arguments:\n"
"-N tags           specify the number of tags to use for this device\n"
"-q                be quiet, don't report the number of tags\n"
"-v                report a number of tag-related parameters\n"
"negotiate arguments:\n"
"-a                send a test unit ready after negotiation\n"
"-c                report/set current negotiation settings\n"
"-D <arg>          \"enable\" or \"disable\" disconnection\n"
"-M mode           set ATA mode\n"
"-O offset         set command delay offset\n"
"-q                be quiet, don't report anything\n"
"-R syncrate       synchronization rate in MHz\n"
"-T <arg>          \"enable\" or \"disable\" tagged queueing\n"
"-U                report/set user negotiation settings\n"
"-W bus_width      set the bus width in bits (8, 16 or 32)\n"
"-v                also print a Path Inquiry CCB for the controller\n"
"format arguments:\n"
"-q                be quiet, don't print status messages\n"
"-r                run in report only mode\n"
"-w                don't send immediate format command\n"
"-y                don't ask any questions\n"
"sanitize arguments:\n"
"-a operation      operation mode: overwrite, block, crypto or exitfailure\n"
"-c passes         overwrite passes to perform (1 to 31)\n"
"-I                invert overwrite pattern after each pass\n"
"-P pattern        path to overwrite pattern file\n"
"-q                be quiet, don't print status messages\n"
"-r                run in report only mode\n"
"-U                run operation in unrestricted completion exit mode\n"
"-w                don't send immediate sanitize command\n"
"-y                don't ask any questions\n"
"idle/standby arguments:\n"
"-t <arg>          number of seconds before respective state.\n"
"fwdownload arguments:\n"
"-f fw_image       path to firmware image file\n"
"-q                don't print informational messages, only errors\n"
"-s                run in simulation mode\n"
"-v                print info for every firmware segment sent to device\n"
"-y                don't ask any questions\n"
"security arguments:\n"
"-d pwd            disable security using the given password for the selected\n"
"                  user\n"
"-e pwd            erase the device using the given pwd for the selected user\n"
"-f                freeze the security configuration of the specified device\n"
"-h pwd            enhanced erase the device using the given pwd for the\n"
"                  selected user\n"
"-k pwd            unlock the device using the given pwd for the selected\n"
"                  user\n"
"-l <high|maximum> specifies which security level to set: high or maximum\n"
"-q                be quiet, do not print any status messages\n"
"-s pwd            password the device (enable security) using the given\n"
"                  pwd for the selected user\n"
"-T timeout        overrides the timeout (seconds) used for erase operation\n"
"-U <user|master>  specifies which user to set: user or master\n"
"-y                don't ask any questions\n"
"hpa arguments:\n"
"-f                freeze the HPA configuration of the device\n"
"-l                lock the HPA configuration of the device\n"
"-P                make the HPA max sectors persist\n"
"-p pwd            Set the HPA configuration password required for unlock\n"
"                  calls\n"
"-q                be quiet, do not print any status messages\n"
"-s sectors        configures the maximum user accessible sectors of the\n"
"                  device\n"
"-U pwd            unlock the HPA configuration of the device\n"
"-y                don't ask any questions\n"
"ama arguments:\n"
"-f                freeze the AMA configuration of the device\n"
"-q                be quiet, do not print any status messages\n"
"-s sectors        configures the maximum user accessible sectors of the\n"
"                  device\n"
"persist arguments:\n"
"-i action         specify read_keys, read_reservation, report_cap, or\n"
"                  read_full_status\n"
"-o action         specify register, register_ignore, reserve, release,\n"
"                  clear, preempt, preempt_abort, register_move, replace_lost\n"
"-a                set the All Target Ports (ALL_TG_PT) bit\n"
"-I tid            specify a Transport ID, e.g.: sas,0x1234567812345678\n"
"-k key            specify the Reservation Key\n"
"-K sa_key         specify the Service Action Reservation Key\n"
"-p                set the Activate Persist Through Power Loss bit\n"
"-R rtp            specify the Relative Target Port\n"
"-s scope          specify the scope: lun, extent, element or a number\n"
"-S                specify Transport ID for register, requires -I\n"
"-T res_type       specify the reservation type: read_shared, wr_ex, rd_ex,\n"
"                  ex_ac, wr_ex_ro, ex_ac_ro, wr_ex_ar, ex_ac_ar\n"
"-U                unregister the current initiator for register_move\n"
"attrib arguments:\n"
"-r action         specify attr_values, attr_list, lv_list, part_list, or\n"
"                  supp_attr\n"
"-w attr           specify an attribute to write, one -w argument per attr\n"
"-a attr_num       only display this attribute number\n"
"-c                get cached attributes\n"
"-e elem_addr      request attributes for the given element in a changer\n"
"-F form1,form2    output format, comma separated list: text_esc, text_raw,\n"
"                  nonascii_esc, nonascii_trim, nonascii_raw, field_all,\n"
"                  field_none, field_desc, field_num, field_size, field_rw\n"
"-p partition      request attributes for the given partition\n"
"-s start_attr     request attributes starting at the given number\n"
"-T elem_type      specify the element type (used with -e)\n"
"-V logical_vol    specify the logical volume ID\n"
"opcodes arguments:\n"
"-o opcode         specify the individual opcode to list\n"
"-s service_action specify the service action for the opcode\n"
"-N                do not return SCSI error for unsupported SA\n"
"-T                request nominal and recommended timeout values\n"
"zone arguments:\n"
"-c cmd            required: rz, open, close, finish, or rwp\n"
"-a                apply the action to all zones\n"
"-l LBA            specify the zone starting LBA\n"
"-o rep_opts       report zones options: all, empty, imp_open, exp_open,\n"
"                  closed, full, ro, offline, reset, nonseq, nonwp\n"
"-P print_opt      report zones printing:  normal, summary, script\n"
"epc arguments:\n"
"-c cmd            required: restore, goto, timer, state, enable, disable,\n"
"                  source, status, list\n"
"-d                disable power mode (timer, state)\n"
"-D                delayed entry (goto)\n"
"-e                enable power mode (timer, state)\n"
"-H                hold power mode (goto)\n"
"-p power_cond     Idle_a, Idle_b, Idle_c, Standby_y, Standby_z (timer,\n"
"                  state, goto)\n"
"-P                only display power mode (status)\n"
"-r rst_src        restore settings from: default, saved (restore)\n"
"-s                save mode (timer, state, restore)\n"
"-S power_src      set power source: battery, nonbattery (source)\n"
"-T timer          set timer, seconds, .1 sec resolution (timer)\n"
"timestamp arguments:\n"
"-r                report the timestamp of the device\n"
"-f format         report the timestamp of the device with the given\n"
"                  strftime(3) format string\n"
"-m                report the timestamp of the device as milliseconds since\n"
"                  January 1st, 1970\n"
"-U                report the time with UTC instead of the local time zone\n"
"-s                set the timestamp of the device\n"
"-f format         the format of the time string passed into strptime(3)\n"
"-T time           the time value passed into strptime(3)\n"
"-U                set the timestamp of the device to UTC time\n"
);
}