#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  int u64 ;
typedef  int u32 ;
typedef  int s64 ;
typedef  enum v4l2_ctrl_type { ____Placeholder_v4l2_ctrl_type } v4l2_ctrl_type ;

/* Variables and functions */
#define  V4L2_CID_3A_LOCK 337 
#define  V4L2_CID_AUDIO_BALANCE 336 
#define  V4L2_CID_AUDIO_BASS 335 
#define  V4L2_CID_AUDIO_COMPRESSION_ATTACK_TIME 334 
#define  V4L2_CID_AUDIO_COMPRESSION_ENABLED 333 
#define  V4L2_CID_AUDIO_COMPRESSION_GAIN 332 
#define  V4L2_CID_AUDIO_COMPRESSION_RELEASE_TIME 331 
#define  V4L2_CID_AUDIO_COMPRESSION_THRESHOLD 330 
#define  V4L2_CID_AUDIO_LIMITER_DEVIATION 329 
#define  V4L2_CID_AUDIO_LIMITER_ENABLED 328 
#define  V4L2_CID_AUDIO_LIMITER_RELEASE_TIME 327 
#define  V4L2_CID_AUDIO_LOUDNESS 326 
#define  V4L2_CID_AUDIO_MUTE 325 
#define  V4L2_CID_AUDIO_TREBLE 324 
#define  V4L2_CID_AUDIO_VOLUME 323 
#define  V4L2_CID_AUTOBRIGHTNESS 322 
#define  V4L2_CID_AUTOGAIN 321 
#define  V4L2_CID_AUTO_EXPOSURE_BIAS 320 
#define  V4L2_CID_AUTO_FOCUS_RANGE 319 
#define  V4L2_CID_AUTO_FOCUS_START 318 
#define  V4L2_CID_AUTO_FOCUS_STATUS 317 
#define  V4L2_CID_AUTO_FOCUS_STOP 316 
#define  V4L2_CID_AUTO_N_PRESET_WHITE_BALANCE 315 
#define  V4L2_CID_AUTO_WHITE_BALANCE 314 
#define  V4L2_CID_BG_COLOR 313 
#define  V4L2_CID_BLUE_BALANCE 312 
#define  V4L2_CID_BRIGHTNESS 311 
#define  V4L2_CID_CAMERA_CLASS 310 
#define  V4L2_CID_CHROMA_AGC 309 
#define  V4L2_CID_CHROMA_GAIN 308 
#define  V4L2_CID_COLORFX 307 
#define  V4L2_CID_COLOR_KILLER 306 
#define  V4L2_CID_CONTRAST 305 
#define  V4L2_CID_DEINTERLACING_MODE 304 
#define  V4L2_CID_DETECT_CLASS 303 
#define  V4L2_CID_DETECT_MD_GLOBAL_THRESHOLD 302 
#define  V4L2_CID_DETECT_MD_MODE 301 
#define  V4L2_CID_DETECT_MD_REGION_GRID 300 
#define  V4L2_CID_DETECT_MD_THRESHOLD_GRID 299 
#define  V4L2_CID_DO_WHITE_BALANCE 298 
#define  V4L2_CID_DV_CLASS 297 
#define  V4L2_CID_DV_RX_IT_CONTENT_TYPE 296 
#define  V4L2_CID_DV_RX_POWER_PRESENT 295 
#define  V4L2_CID_DV_RX_RGB_RANGE 294 
#define  V4L2_CID_DV_TX_EDID_PRESENT 293 
#define  V4L2_CID_DV_TX_HOTPLUG 292 
#define  V4L2_CID_DV_TX_IT_CONTENT_TYPE 291 
#define  V4L2_CID_DV_TX_MODE 290 
#define  V4L2_CID_DV_TX_RGB_RANGE 289 
#define  V4L2_CID_DV_TX_RXSENSE 288 
#define  V4L2_CID_EXPOSURE_AUTO 287 
#define  V4L2_CID_EXPOSURE_AUTO_PRIORITY 286 
#define  V4L2_CID_EXPOSURE_METERING 285 
#define  V4L2_CID_FLASH_CHARGE 284 
#define  V4L2_CID_FLASH_CLASS 283 
#define  V4L2_CID_FLASH_FAULT 282 
#define  V4L2_CID_FLASH_LED_MODE 281 
#define  V4L2_CID_FLASH_READY 280 
#define  V4L2_CID_FLASH_STROBE 279 
#define  V4L2_CID_FLASH_STROBE_SOURCE 278 
#define  V4L2_CID_FLASH_STROBE_STATUS 277 
#define  V4L2_CID_FLASH_STROBE_STOP 276 
#define  V4L2_CID_FM_RX_CLASS 275 
#define  V4L2_CID_FM_TX_CLASS 274 
#define  V4L2_CID_FOCUS_AUTO 273 
#define  V4L2_CID_FOCUS_RELATIVE 272 
#define  V4L2_CID_GAMMA 271 
#define  V4L2_CID_HFLIP 270 
#define  V4L2_CID_HUE 269 
#define  V4L2_CID_HUE_AUTO 268 
#define  V4L2_CID_ILLUMINATORS_1 267 
#define  V4L2_CID_ILLUMINATORS_2 266 
#define  V4L2_CID_IMAGE_PROC_CLASS 265 
#define  V4L2_CID_IMAGE_SOURCE_CLASS 264 
#define  V4L2_CID_IMAGE_STABILIZATION 263 
#define  V4L2_CID_IRIS_RELATIVE 262 
#define  V4L2_CID_ISO_SENSITIVITY 261 
#define  V4L2_CID_ISO_SENSITIVITY_AUTO 260 
#define  V4L2_CID_JPEG_ACTIVE_MARKER 259 
#define  V4L2_CID_JPEG_CHROMA_SUBSAMPLING 258 
#define  V4L2_CID_JPEG_CLASS 257 
#define  V4L2_CID_LINK_FREQ 256 
#define  V4L2_CID_MIN_BUFFERS_FOR_CAPTURE 255 
#define  V4L2_CID_MIN_BUFFERS_FOR_OUTPUT 254 
#define  V4L2_CID_MPEG_AUDIO_AC3_BITRATE 253 
#define  V4L2_CID_MPEG_AUDIO_CRC 252 
#define  V4L2_CID_MPEG_AUDIO_DEC_MULTILINGUAL_PLAYBACK 251 
#define  V4L2_CID_MPEG_AUDIO_DEC_PLAYBACK 250 
#define  V4L2_CID_MPEG_AUDIO_EMPHASIS 249 
#define  V4L2_CID_MPEG_AUDIO_ENCODING 248 
#define  V4L2_CID_MPEG_AUDIO_L1_BITRATE 247 
#define  V4L2_CID_MPEG_AUDIO_L2_BITRATE 246 
#define  V4L2_CID_MPEG_AUDIO_L3_BITRATE 245 
#define  V4L2_CID_MPEG_AUDIO_MODE 244 
#define  V4L2_CID_MPEG_AUDIO_MODE_EXTENSION 243 
#define  V4L2_CID_MPEG_AUDIO_MUTE 242 
#define  V4L2_CID_MPEG_AUDIO_SAMPLING_FREQ 241 
#define  V4L2_CID_MPEG_CLASS 240 
#define  V4L2_CID_MPEG_STREAM_TYPE 239 
#define  V4L2_CID_MPEG_STREAM_VBI_FMT 238 
#define  V4L2_CID_MPEG_VIDEO_ASPECT 237 
#define  V4L2_CID_MPEG_VIDEO_BITRATE_MODE 236 
#define  V4L2_CID_MPEG_VIDEO_B_FRAMES 235 
#define  V4L2_CID_MPEG_VIDEO_DECODER_MPEG4_DEBLOCK_FILTER 234 
#define  V4L2_CID_MPEG_VIDEO_DECODER_SLICE_INTERFACE 233 
#define  V4L2_CID_MPEG_VIDEO_DEC_FRAME 232 
#define  V4L2_CID_MPEG_VIDEO_DEC_PTS 231 
#define  V4L2_CID_MPEG_VIDEO_ENCODING 230 
#define  V4L2_CID_MPEG_VIDEO_FORCE_KEY_FRAME 229 
#define  V4L2_CID_MPEG_VIDEO_FRAME_RC_ENABLE 228 
#define  V4L2_CID_MPEG_VIDEO_FWHT_PARAMS 227 
#define  V4L2_CID_MPEG_VIDEO_GOP_CLOSURE 226 
#define  V4L2_CID_MPEG_VIDEO_H264_8X8_TRANSFORM 225 
#define  V4L2_CID_MPEG_VIDEO_H264_DECODE_MODE 224 
#define  V4L2_CID_MPEG_VIDEO_H264_DECODE_PARAMS 223 
#define  V4L2_CID_MPEG_VIDEO_H264_ENTROPY_MODE 222 
#define  V4L2_CID_MPEG_VIDEO_H264_FMO_MAP_TYPE 221 
#define  V4L2_CID_MPEG_VIDEO_H264_LEVEL 220 
#define  V4L2_CID_MPEG_VIDEO_H264_LOOP_FILTER_MODE 219 
#define  V4L2_CID_MPEG_VIDEO_H264_PPS 218 
#define  V4L2_CID_MPEG_VIDEO_H264_PROFILE 217 
#define  V4L2_CID_MPEG_VIDEO_H264_SCALING_MATRIX 216 
#define  V4L2_CID_MPEG_VIDEO_H264_SEI_FP_ARRANGEMENT_TYPE 215 
#define  V4L2_CID_MPEG_VIDEO_H264_SLICE_PARAMS 214 
#define  V4L2_CID_MPEG_VIDEO_H264_SPS 213 
#define  V4L2_CID_MPEG_VIDEO_H264_START_CODE 212 
#define  V4L2_CID_MPEG_VIDEO_H264_VUI_SAR_ENABLE 211 
#define  V4L2_CID_MPEG_VIDEO_H264_VUI_SAR_IDC 210 
#define  V4L2_CID_MPEG_VIDEO_HEADER_MODE 209 
#define  V4L2_CID_MPEG_VIDEO_HEVC_HIER_CODING_TYPE 208 
#define  V4L2_CID_MPEG_VIDEO_HEVC_LEVEL 207 
#define  V4L2_CID_MPEG_VIDEO_HEVC_LOOP_FILTER_MODE 206 
#define  V4L2_CID_MPEG_VIDEO_HEVC_PROFILE 205 
#define  V4L2_CID_MPEG_VIDEO_HEVC_REFRESH_TYPE 204 
#define  V4L2_CID_MPEG_VIDEO_HEVC_SIZE_OF_LENGTH_FIELD 203 
#define  V4L2_CID_MPEG_VIDEO_HEVC_TIER 202 
#define  V4L2_CID_MPEG_VIDEO_MB_RC_ENABLE 201 
#define  V4L2_CID_MPEG_VIDEO_MPEG2_LEVEL 200 
#define  V4L2_CID_MPEG_VIDEO_MPEG2_PROFILE 199 
#define  V4L2_CID_MPEG_VIDEO_MPEG2_QUANTIZATION 198 
#define  V4L2_CID_MPEG_VIDEO_MPEG2_SLICE_PARAMS 197 
#define  V4L2_CID_MPEG_VIDEO_MPEG4_LEVEL 196 
#define  V4L2_CID_MPEG_VIDEO_MPEG4_PROFILE 195 
#define  V4L2_CID_MPEG_VIDEO_MPEG4_QPEL 194 
#define  V4L2_CID_MPEG_VIDEO_MULTI_SLICE_MODE 193 
#define  V4L2_CID_MPEG_VIDEO_MUTE 192 
#define  V4L2_CID_MPEG_VIDEO_MV_H_SEARCH_RANGE 191 
#define  V4L2_CID_MPEG_VIDEO_MV_V_SEARCH_RANGE 190 
#define  V4L2_CID_MPEG_VIDEO_PULLDOWN 189 
#define  V4L2_CID_MPEG_VIDEO_REPEAT_SEQ_HEADER 188 
#define  V4L2_CID_MPEG_VIDEO_VP8_FRAME_HEADER 187 
#define  V4L2_CID_MPEG_VIDEO_VP8_PROFILE 186 
#define  V4L2_CID_MPEG_VIDEO_VP9_PROFILE 185 
#define  V4L2_CID_MPEG_VIDEO_VPX_GOLDEN_FRAME_SEL 184 
#define  V4L2_CID_MPEG_VIDEO_VPX_NUM_PARTITIONS 183 
#define  V4L2_CID_MPEG_VIDEO_VPX_NUM_REF_FRAMES 182 
#define  V4L2_CID_PAN_RELATIVE 181 
#define  V4L2_CID_PAN_RESET 180 
#define  V4L2_CID_PILOT_TONE_DEVIATION 179 
#define  V4L2_CID_PILOT_TONE_ENABLED 178 
#define  V4L2_CID_PILOT_TONE_FREQUENCY 177 
#define  V4L2_CID_PIXEL_RATE 176 
#define  V4L2_CID_POWER_LINE_FREQUENCY 175 
#define  V4L2_CID_PRIVACY 174 
#define  V4L2_CID_RDS_RECEPTION 173 
#define  V4L2_CID_RDS_RX_MUSIC_SPEECH 172 
#define  V4L2_CID_RDS_RX_PS_NAME 171 
#define  V4L2_CID_RDS_RX_PTY 170 
#define  V4L2_CID_RDS_RX_RADIO_TEXT 169 
#define  V4L2_CID_RDS_RX_TRAFFIC_ANNOUNCEMENT 168 
#define  V4L2_CID_RDS_RX_TRAFFIC_PROGRAM 167 
#define  V4L2_CID_RDS_TX_ALT_FREQS 166 
#define  V4L2_CID_RDS_TX_ALT_FREQS_ENABLE 165 
#define  V4L2_CID_RDS_TX_ARTIFICIAL_HEAD 164 
#define  V4L2_CID_RDS_TX_COMPRESSED 163 
#define  V4L2_CID_RDS_TX_DEVIATION 162 
#define  V4L2_CID_RDS_TX_DYNAMIC_PTY 161 
#define  V4L2_CID_RDS_TX_MONO_STEREO 160 
#define  V4L2_CID_RDS_TX_MUSIC_SPEECH 159 
#define  V4L2_CID_RDS_TX_PS_NAME 158 
#define  V4L2_CID_RDS_TX_RADIO_TEXT 157 
#define  V4L2_CID_RDS_TX_TRAFFIC_ANNOUNCEMENT 156 
#define  V4L2_CID_RDS_TX_TRAFFIC_PROGRAM 155 
#define  V4L2_CID_RED_BALANCE 154 
#define  V4L2_CID_RF_TUNER_BANDWIDTH 153 
#define  V4L2_CID_RF_TUNER_BANDWIDTH_AUTO 152 
#define  V4L2_CID_RF_TUNER_CLASS 151 
#define  V4L2_CID_RF_TUNER_IF_GAIN 150 
#define  V4L2_CID_RF_TUNER_IF_GAIN_AUTO 149 
#define  V4L2_CID_RF_TUNER_LNA_GAIN 148 
#define  V4L2_CID_RF_TUNER_LNA_GAIN_AUTO 147 
#define  V4L2_CID_RF_TUNER_MIXER_GAIN 146 
#define  V4L2_CID_RF_TUNER_MIXER_GAIN_AUTO 145 
#define  V4L2_CID_RF_TUNER_PLL_LOCK 144 
#define  V4L2_CID_RF_TUNER_RF_GAIN 143 
#define  V4L2_CID_ROTATE 142 
#define  V4L2_CID_SATURATION 141 
#define  V4L2_CID_SCENE_MODE 140 
#define  V4L2_CID_SHARPNESS 139 
#define  V4L2_CID_TEST_PATTERN 138 
#define  V4L2_CID_TILT_RELATIVE 137 
#define  V4L2_CID_TILT_RESET 136 
#define  V4L2_CID_TUNE_ANTENNA_CAPACITOR 135 
#define  V4L2_CID_TUNE_DEEMPHASIS 134 
#define  V4L2_CID_TUNE_POWER_LEVEL 133 
#define  V4L2_CID_TUNE_PREEMPHASIS 132 
#define  V4L2_CID_USER_CLASS 131 
#define  V4L2_CID_VFLIP 130 
#define  V4L2_CID_WIDE_DYNAMIC_RANGE 129 
#define  V4L2_CID_ZOOM_RELATIVE 128 
 int V4L2_CTRL_FLAG_EXECUTE_ON_WRITE ; 
 int V4L2_CTRL_FLAG_MODIFY_LAYOUT ; 
 int V4L2_CTRL_FLAG_READ_ONLY ; 
 int V4L2_CTRL_FLAG_SLIDER ; 
 int V4L2_CTRL_FLAG_UPDATE ; 
 int V4L2_CTRL_FLAG_VOLATILE ; 
 int V4L2_CTRL_FLAG_WRITE_ONLY ; 
 int V4L2_CTRL_TYPE_BITMASK ; 
 int V4L2_CTRL_TYPE_BOOLEAN ; 
 int V4L2_CTRL_TYPE_BUTTON ; 
 int V4L2_CTRL_TYPE_CTRL_CLASS ; 
 int V4L2_CTRL_TYPE_FWHT_PARAMS ; 
 int V4L2_CTRL_TYPE_H264_DECODE_PARAMS ; 
 int V4L2_CTRL_TYPE_H264_PPS ; 
 int V4L2_CTRL_TYPE_H264_SCALING_MATRIX ; 
 int V4L2_CTRL_TYPE_H264_SLICE_PARAMS ; 
 int V4L2_CTRL_TYPE_H264_SPS ; 
 int V4L2_CTRL_TYPE_INTEGER ; 
 int V4L2_CTRL_TYPE_INTEGER64 ; 
 int V4L2_CTRL_TYPE_INTEGER_MENU ; 
 int V4L2_CTRL_TYPE_MENU ; 
 int V4L2_CTRL_TYPE_MPEG2_QUANTIZATION ; 
 int V4L2_CTRL_TYPE_MPEG2_SLICE_PARAMS ; 
 int V4L2_CTRL_TYPE_STRING ; 
 int V4L2_CTRL_TYPE_U16 ; 
 int V4L2_CTRL_TYPE_U32 ; 
 int V4L2_CTRL_TYPE_U8 ; 
 int V4L2_CTRL_TYPE_VP8_FRAME_HEADER ; 
 char* v4l2_ctrl_get_name (int) ; 

void v4l2_ctrl_fill(u32 id, const char **name, enum v4l2_ctrl_type *type,
		    s64 *min, s64 *max, u64 *step, s64 *def, u32 *flags)
{
	*name = v4l2_ctrl_get_name(id);
	*flags = 0;

	switch (id) {
	case V4L2_CID_AUDIO_MUTE:
	case V4L2_CID_AUDIO_LOUDNESS:
	case V4L2_CID_AUTO_WHITE_BALANCE:
	case V4L2_CID_AUTOGAIN:
	case V4L2_CID_HFLIP:
	case V4L2_CID_VFLIP:
	case V4L2_CID_HUE_AUTO:
	case V4L2_CID_CHROMA_AGC:
	case V4L2_CID_COLOR_KILLER:
	case V4L2_CID_AUTOBRIGHTNESS:
	case V4L2_CID_MPEG_AUDIO_MUTE:
	case V4L2_CID_MPEG_VIDEO_MUTE:
	case V4L2_CID_MPEG_VIDEO_GOP_CLOSURE:
	case V4L2_CID_MPEG_VIDEO_PULLDOWN:
	case V4L2_CID_EXPOSURE_AUTO_PRIORITY:
	case V4L2_CID_FOCUS_AUTO:
	case V4L2_CID_PRIVACY:
	case V4L2_CID_AUDIO_LIMITER_ENABLED:
	case V4L2_CID_AUDIO_COMPRESSION_ENABLED:
	case V4L2_CID_PILOT_TONE_ENABLED:
	case V4L2_CID_ILLUMINATORS_1:
	case V4L2_CID_ILLUMINATORS_2:
	case V4L2_CID_FLASH_STROBE_STATUS:
	case V4L2_CID_FLASH_CHARGE:
	case V4L2_CID_FLASH_READY:
	case V4L2_CID_MPEG_VIDEO_DECODER_MPEG4_DEBLOCK_FILTER:
	case V4L2_CID_MPEG_VIDEO_DECODER_SLICE_INTERFACE:
	case V4L2_CID_MPEG_VIDEO_FRAME_RC_ENABLE:
	case V4L2_CID_MPEG_VIDEO_MB_RC_ENABLE:
	case V4L2_CID_MPEG_VIDEO_H264_8X8_TRANSFORM:
	case V4L2_CID_MPEG_VIDEO_H264_VUI_SAR_ENABLE:
	case V4L2_CID_MPEG_VIDEO_MPEG4_QPEL:
	case V4L2_CID_MPEG_VIDEO_REPEAT_SEQ_HEADER:
	case V4L2_CID_WIDE_DYNAMIC_RANGE:
	case V4L2_CID_IMAGE_STABILIZATION:
	case V4L2_CID_RDS_RECEPTION:
	case V4L2_CID_RF_TUNER_LNA_GAIN_AUTO:
	case V4L2_CID_RF_TUNER_MIXER_GAIN_AUTO:
	case V4L2_CID_RF_TUNER_IF_GAIN_AUTO:
	case V4L2_CID_RF_TUNER_BANDWIDTH_AUTO:
	case V4L2_CID_RF_TUNER_PLL_LOCK:
	case V4L2_CID_RDS_TX_MONO_STEREO:
	case V4L2_CID_RDS_TX_ARTIFICIAL_HEAD:
	case V4L2_CID_RDS_TX_COMPRESSED:
	case V4L2_CID_RDS_TX_DYNAMIC_PTY:
	case V4L2_CID_RDS_TX_TRAFFIC_ANNOUNCEMENT:
	case V4L2_CID_RDS_TX_TRAFFIC_PROGRAM:
	case V4L2_CID_RDS_TX_MUSIC_SPEECH:
	case V4L2_CID_RDS_TX_ALT_FREQS_ENABLE:
	case V4L2_CID_RDS_RX_TRAFFIC_ANNOUNCEMENT:
	case V4L2_CID_RDS_RX_TRAFFIC_PROGRAM:
	case V4L2_CID_RDS_RX_MUSIC_SPEECH:
		*type = V4L2_CTRL_TYPE_BOOLEAN;
		*min = 0;
		*max = *step = 1;
		break;
	case V4L2_CID_ROTATE:
		*type = V4L2_CTRL_TYPE_INTEGER;
		*flags |= V4L2_CTRL_FLAG_MODIFY_LAYOUT;
		break;
	case V4L2_CID_MPEG_VIDEO_MV_H_SEARCH_RANGE:
	case V4L2_CID_MPEG_VIDEO_MV_V_SEARCH_RANGE:
		*type = V4L2_CTRL_TYPE_INTEGER;
		break;
	case V4L2_CID_MPEG_VIDEO_FORCE_KEY_FRAME:
	case V4L2_CID_PAN_RESET:
	case V4L2_CID_TILT_RESET:
	case V4L2_CID_FLASH_STROBE:
	case V4L2_CID_FLASH_STROBE_STOP:
	case V4L2_CID_AUTO_FOCUS_START:
	case V4L2_CID_AUTO_FOCUS_STOP:
	case V4L2_CID_DO_WHITE_BALANCE:
		*type = V4L2_CTRL_TYPE_BUTTON;
		*flags |= V4L2_CTRL_FLAG_WRITE_ONLY |
			  V4L2_CTRL_FLAG_EXECUTE_ON_WRITE;
		*min = *max = *step = *def = 0;
		break;
	case V4L2_CID_POWER_LINE_FREQUENCY:
	case V4L2_CID_MPEG_AUDIO_SAMPLING_FREQ:
	case V4L2_CID_MPEG_AUDIO_ENCODING:
	case V4L2_CID_MPEG_AUDIO_L1_BITRATE:
	case V4L2_CID_MPEG_AUDIO_L2_BITRATE:
	case V4L2_CID_MPEG_AUDIO_L3_BITRATE:
	case V4L2_CID_MPEG_AUDIO_AC3_BITRATE:
	case V4L2_CID_MPEG_AUDIO_MODE:
	case V4L2_CID_MPEG_AUDIO_MODE_EXTENSION:
	case V4L2_CID_MPEG_AUDIO_EMPHASIS:
	case V4L2_CID_MPEG_AUDIO_CRC:
	case V4L2_CID_MPEG_AUDIO_DEC_PLAYBACK:
	case V4L2_CID_MPEG_AUDIO_DEC_MULTILINGUAL_PLAYBACK:
	case V4L2_CID_MPEG_VIDEO_ENCODING:
	case V4L2_CID_MPEG_VIDEO_ASPECT:
	case V4L2_CID_MPEG_VIDEO_BITRATE_MODE:
	case V4L2_CID_MPEG_STREAM_TYPE:
	case V4L2_CID_MPEG_STREAM_VBI_FMT:
	case V4L2_CID_EXPOSURE_AUTO:
	case V4L2_CID_AUTO_FOCUS_RANGE:
	case V4L2_CID_COLORFX:
	case V4L2_CID_AUTO_N_PRESET_WHITE_BALANCE:
	case V4L2_CID_TUNE_PREEMPHASIS:
	case V4L2_CID_FLASH_LED_MODE:
	case V4L2_CID_FLASH_STROBE_SOURCE:
	case V4L2_CID_MPEG_VIDEO_HEADER_MODE:
	case V4L2_CID_MPEG_VIDEO_MULTI_SLICE_MODE:
	case V4L2_CID_MPEG_VIDEO_H264_ENTROPY_MODE:
	case V4L2_CID_MPEG_VIDEO_H264_LEVEL:
	case V4L2_CID_MPEG_VIDEO_H264_LOOP_FILTER_MODE:
	case V4L2_CID_MPEG_VIDEO_H264_PROFILE:
	case V4L2_CID_MPEG_VIDEO_H264_VUI_SAR_IDC:
	case V4L2_CID_MPEG_VIDEO_H264_SEI_FP_ARRANGEMENT_TYPE:
	case V4L2_CID_MPEG_VIDEO_H264_FMO_MAP_TYPE:
	case V4L2_CID_MPEG_VIDEO_H264_DECODE_MODE:
	case V4L2_CID_MPEG_VIDEO_H264_START_CODE:
	case V4L2_CID_MPEG_VIDEO_MPEG2_LEVEL:
	case V4L2_CID_MPEG_VIDEO_MPEG2_PROFILE:
	case V4L2_CID_MPEG_VIDEO_MPEG4_LEVEL:
	case V4L2_CID_MPEG_VIDEO_MPEG4_PROFILE:
	case V4L2_CID_JPEG_CHROMA_SUBSAMPLING:
	case V4L2_CID_ISO_SENSITIVITY_AUTO:
	case V4L2_CID_EXPOSURE_METERING:
	case V4L2_CID_SCENE_MODE:
	case V4L2_CID_DV_TX_MODE:
	case V4L2_CID_DV_TX_RGB_RANGE:
	case V4L2_CID_DV_TX_IT_CONTENT_TYPE:
	case V4L2_CID_DV_RX_RGB_RANGE:
	case V4L2_CID_DV_RX_IT_CONTENT_TYPE:
	case V4L2_CID_TEST_PATTERN:
	case V4L2_CID_DEINTERLACING_MODE:
	case V4L2_CID_TUNE_DEEMPHASIS:
	case V4L2_CID_MPEG_VIDEO_VPX_GOLDEN_FRAME_SEL:
	case V4L2_CID_MPEG_VIDEO_VP8_PROFILE:
	case V4L2_CID_MPEG_VIDEO_VP9_PROFILE:
	case V4L2_CID_DETECT_MD_MODE:
	case V4L2_CID_MPEG_VIDEO_HEVC_PROFILE:
	case V4L2_CID_MPEG_VIDEO_HEVC_LEVEL:
	case V4L2_CID_MPEG_VIDEO_HEVC_HIER_CODING_TYPE:
	case V4L2_CID_MPEG_VIDEO_HEVC_REFRESH_TYPE:
	case V4L2_CID_MPEG_VIDEO_HEVC_SIZE_OF_LENGTH_FIELD:
	case V4L2_CID_MPEG_VIDEO_HEVC_TIER:
	case V4L2_CID_MPEG_VIDEO_HEVC_LOOP_FILTER_MODE:
		*type = V4L2_CTRL_TYPE_MENU;
		break;
	case V4L2_CID_LINK_FREQ:
		*type = V4L2_CTRL_TYPE_INTEGER_MENU;
		break;
	case V4L2_CID_RDS_TX_PS_NAME:
	case V4L2_CID_RDS_TX_RADIO_TEXT:
	case V4L2_CID_RDS_RX_PS_NAME:
	case V4L2_CID_RDS_RX_RADIO_TEXT:
		*type = V4L2_CTRL_TYPE_STRING;
		break;
	case V4L2_CID_ISO_SENSITIVITY:
	case V4L2_CID_AUTO_EXPOSURE_BIAS:
	case V4L2_CID_MPEG_VIDEO_VPX_NUM_PARTITIONS:
	case V4L2_CID_MPEG_VIDEO_VPX_NUM_REF_FRAMES:
		*type = V4L2_CTRL_TYPE_INTEGER_MENU;
		break;
	case V4L2_CID_USER_CLASS:
	case V4L2_CID_CAMERA_CLASS:
	case V4L2_CID_MPEG_CLASS:
	case V4L2_CID_FM_TX_CLASS:
	case V4L2_CID_FLASH_CLASS:
	case V4L2_CID_JPEG_CLASS:
	case V4L2_CID_IMAGE_SOURCE_CLASS:
	case V4L2_CID_IMAGE_PROC_CLASS:
	case V4L2_CID_DV_CLASS:
	case V4L2_CID_FM_RX_CLASS:
	case V4L2_CID_RF_TUNER_CLASS:
	case V4L2_CID_DETECT_CLASS:
		*type = V4L2_CTRL_TYPE_CTRL_CLASS;
		/* You can neither read not write these */
		*flags |= V4L2_CTRL_FLAG_READ_ONLY | V4L2_CTRL_FLAG_WRITE_ONLY;
		*min = *max = *step = *def = 0;
		break;
	case V4L2_CID_BG_COLOR:
		*type = V4L2_CTRL_TYPE_INTEGER;
		*step = 1;
		*min = 0;
		/* Max is calculated as RGB888 that is 2^24 */
		*max = 0xFFFFFF;
		break;
	case V4L2_CID_FLASH_FAULT:
	case V4L2_CID_JPEG_ACTIVE_MARKER:
	case V4L2_CID_3A_LOCK:
	case V4L2_CID_AUTO_FOCUS_STATUS:
	case V4L2_CID_DV_TX_HOTPLUG:
	case V4L2_CID_DV_TX_RXSENSE:
	case V4L2_CID_DV_TX_EDID_PRESENT:
	case V4L2_CID_DV_RX_POWER_PRESENT:
		*type = V4L2_CTRL_TYPE_BITMASK;
		break;
	case V4L2_CID_MIN_BUFFERS_FOR_CAPTURE:
	case V4L2_CID_MIN_BUFFERS_FOR_OUTPUT:
		*type = V4L2_CTRL_TYPE_INTEGER;
		*flags |= V4L2_CTRL_FLAG_READ_ONLY;
		break;
	case V4L2_CID_MPEG_VIDEO_DEC_PTS:
		*type = V4L2_CTRL_TYPE_INTEGER64;
		*flags |= V4L2_CTRL_FLAG_VOLATILE | V4L2_CTRL_FLAG_READ_ONLY;
		*min = *def = 0;
		*max = 0x1ffffffffLL;
		*step = 1;
		break;
	case V4L2_CID_MPEG_VIDEO_DEC_FRAME:
		*type = V4L2_CTRL_TYPE_INTEGER64;
		*flags |= V4L2_CTRL_FLAG_VOLATILE | V4L2_CTRL_FLAG_READ_ONLY;
		*min = *def = 0;
		*max = 0x7fffffffffffffffLL;
		*step = 1;
		break;
	case V4L2_CID_PIXEL_RATE:
		*type = V4L2_CTRL_TYPE_INTEGER64;
		*flags |= V4L2_CTRL_FLAG_READ_ONLY;
		break;
	case V4L2_CID_DETECT_MD_REGION_GRID:
		*type = V4L2_CTRL_TYPE_U8;
		break;
	case V4L2_CID_DETECT_MD_THRESHOLD_GRID:
		*type = V4L2_CTRL_TYPE_U16;
		break;
	case V4L2_CID_RDS_TX_ALT_FREQS:
		*type = V4L2_CTRL_TYPE_U32;
		break;
	case V4L2_CID_MPEG_VIDEO_MPEG2_SLICE_PARAMS:
		*type = V4L2_CTRL_TYPE_MPEG2_SLICE_PARAMS;
		break;
	case V4L2_CID_MPEG_VIDEO_MPEG2_QUANTIZATION:
		*type = V4L2_CTRL_TYPE_MPEG2_QUANTIZATION;
		break;
	case V4L2_CID_MPEG_VIDEO_FWHT_PARAMS:
		*type = V4L2_CTRL_TYPE_FWHT_PARAMS;
		break;
	case V4L2_CID_MPEG_VIDEO_H264_SPS:
		*type = V4L2_CTRL_TYPE_H264_SPS;
		break;
	case V4L2_CID_MPEG_VIDEO_H264_PPS:
		*type = V4L2_CTRL_TYPE_H264_PPS;
		break;
	case V4L2_CID_MPEG_VIDEO_H264_SCALING_MATRIX:
		*type = V4L2_CTRL_TYPE_H264_SCALING_MATRIX;
		break;
	case V4L2_CID_MPEG_VIDEO_H264_SLICE_PARAMS:
		*type = V4L2_CTRL_TYPE_H264_SLICE_PARAMS;
		break;
	case V4L2_CID_MPEG_VIDEO_H264_DECODE_PARAMS:
		*type = V4L2_CTRL_TYPE_H264_DECODE_PARAMS;
		break;
	case V4L2_CID_MPEG_VIDEO_VP8_FRAME_HEADER:
		*type = V4L2_CTRL_TYPE_VP8_FRAME_HEADER;
		break;
	default:
		*type = V4L2_CTRL_TYPE_INTEGER;
		break;
	}
	switch (id) {
	case V4L2_CID_MPEG_AUDIO_ENCODING:
	case V4L2_CID_MPEG_AUDIO_MODE:
	case V4L2_CID_MPEG_VIDEO_BITRATE_MODE:
	case V4L2_CID_MPEG_VIDEO_B_FRAMES:
	case V4L2_CID_MPEG_STREAM_TYPE:
		*flags |= V4L2_CTRL_FLAG_UPDATE;
		break;
	case V4L2_CID_AUDIO_VOLUME:
	case V4L2_CID_AUDIO_BALANCE:
	case V4L2_CID_AUDIO_BASS:
	case V4L2_CID_AUDIO_TREBLE:
	case V4L2_CID_BRIGHTNESS:
	case V4L2_CID_CONTRAST:
	case V4L2_CID_SATURATION:
	case V4L2_CID_HUE:
	case V4L2_CID_RED_BALANCE:
	case V4L2_CID_BLUE_BALANCE:
	case V4L2_CID_GAMMA:
	case V4L2_CID_SHARPNESS:
	case V4L2_CID_CHROMA_GAIN:
	case V4L2_CID_RDS_TX_DEVIATION:
	case V4L2_CID_AUDIO_LIMITER_RELEASE_TIME:
	case V4L2_CID_AUDIO_LIMITER_DEVIATION:
	case V4L2_CID_AUDIO_COMPRESSION_GAIN:
	case V4L2_CID_AUDIO_COMPRESSION_THRESHOLD:
	case V4L2_CID_AUDIO_COMPRESSION_ATTACK_TIME:
	case V4L2_CID_AUDIO_COMPRESSION_RELEASE_TIME:
	case V4L2_CID_PILOT_TONE_DEVIATION:
	case V4L2_CID_PILOT_TONE_FREQUENCY:
	case V4L2_CID_TUNE_POWER_LEVEL:
	case V4L2_CID_TUNE_ANTENNA_CAPACITOR:
	case V4L2_CID_RF_TUNER_RF_GAIN:
	case V4L2_CID_RF_TUNER_LNA_GAIN:
	case V4L2_CID_RF_TUNER_MIXER_GAIN:
	case V4L2_CID_RF_TUNER_IF_GAIN:
	case V4L2_CID_RF_TUNER_BANDWIDTH:
	case V4L2_CID_DETECT_MD_GLOBAL_THRESHOLD:
		*flags |= V4L2_CTRL_FLAG_SLIDER;
		break;
	case V4L2_CID_PAN_RELATIVE:
	case V4L2_CID_TILT_RELATIVE:
	case V4L2_CID_FOCUS_RELATIVE:
	case V4L2_CID_IRIS_RELATIVE:
	case V4L2_CID_ZOOM_RELATIVE:
		*flags |= V4L2_CTRL_FLAG_WRITE_ONLY |
			  V4L2_CTRL_FLAG_EXECUTE_ON_WRITE;
		break;
	case V4L2_CID_FLASH_STROBE_STATUS:
	case V4L2_CID_AUTO_FOCUS_STATUS:
	case V4L2_CID_FLASH_READY:
	case V4L2_CID_DV_TX_HOTPLUG:
	case V4L2_CID_DV_TX_RXSENSE:
	case V4L2_CID_DV_TX_EDID_PRESENT:
	case V4L2_CID_DV_RX_POWER_PRESENT:
	case V4L2_CID_DV_RX_IT_CONTENT_TYPE:
	case V4L2_CID_RDS_RX_PTY:
	case V4L2_CID_RDS_RX_PS_NAME:
	case V4L2_CID_RDS_RX_RADIO_TEXT:
	case V4L2_CID_RDS_RX_TRAFFIC_ANNOUNCEMENT:
	case V4L2_CID_RDS_RX_TRAFFIC_PROGRAM:
	case V4L2_CID_RDS_RX_MUSIC_SPEECH:
		*flags |= V4L2_CTRL_FLAG_READ_ONLY;
		break;
	case V4L2_CID_RF_TUNER_PLL_LOCK:
		*flags |= V4L2_CTRL_FLAG_VOLATILE;
		break;
	}
}