#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  int /*<<< orphan*/  u_long ;

/* Variables and functions */
#define  OSIOCGIFADDR 260 
#define  OSIOCGIFBRDADDR 259 
#define  OSIOCGIFCONF32 258 
#define  OSIOCGIFCONF64 257 
#define  OSIOCGIFDSTADDR 256 
#define  OSIOCGIFNETMASK 255 
#define  SIOCADDMULTI 254 
#define  SIOCAIFADDR 253 
#define  SIOCAIFAGENTID 252 
#define  SIOCARPIPLL 251 
#define  SIOCAUTOADDR 250 
#define  SIOCAUTONETMASK 249 
#define  SIOCDELMULTI 248 
#define  SIOCDIFADDR 247 
#define  SIOCDIFAGENTID 246 
#define  SIOCDIFPHYADDR 245 
#define  SIOCGASSOCIDS32 244 
#define  SIOCGASSOCIDS64 243 
#define  SIOCGCONNIDS32 242 
#define  SIOCGCONNIDS64 241 
#define  SIOCGCONNINFO32 240 
#define  SIOCGCONNINFO64 239 
#define  SIOCGCONNORDER 238 
#define  SIOCGDRVSPEC32 237 
#define  SIOCGDRVSPEC64 236 
#define  SIOCGECNMODE 235 
#define  SIOCGIF2KCL 234 
#define  SIOCGIFADDR 233 
#define  SIOCGIFAGENTDATA32 232 
#define  SIOCGIFAGENTDATA64 231 
#define  SIOCGIFAGENTIDS32 230 
#define  SIOCGIFAGENTIDS64 229 
#define  SIOCGIFAGENTLIST32 228 
#define  SIOCGIFAGENTLIST64 227 
#define  SIOCGIFALTMTU 226 
#define  SIOCGIFASYNCMAP 225 
#define  SIOCGIFBOND 224 
#define  SIOCGIFBRDADDR 223 
#define  SIOCGIFCAP 222 
#define  SIOCGIFCONF32 221 
#define  SIOCGIFCONF64 220 
#define  SIOCGIFDELEGATE 219 
#define  SIOCGIFDESC 218 
#define  SIOCGIFDEVMTU 217 
#define  SIOCGIFDSTADDR 216 
#define  SIOCGIFEFLAGS 215 
#define  SIOCGIFEXPENSIVE 214 
#define  SIOCGIFFLAGS 213 
#define  SIOCGIFFUNCTIONALTYPE 212 
#define  SIOCGIFGENERIC 211 
#define  SIOCGIFGETRTREFCNT 210 
#define  SIOCGIFINTERFACESTATE 209 
#define  SIOCGIFKPI 208 
#define  SIOCGIFLINKPARAMS 207 
#define  SIOCGIFLINKQUALITYMETRIC 206 
#define  SIOCGIFLLADDR 205 
#define  SIOCGIFLOG 204 
#define  SIOCGIFLOWINTERNET 203 
#define  SIOCGIFLOWPOWER 202 
#define  SIOCGIFMEDIA32 201 
#define  SIOCGIFMEDIA64 200 
#define  SIOCGIFMETRIC 199 
#define  SIOCGIFMTU 198 
#define  SIOCGIFNETMASK 197 
#define  SIOCGIFNETSIGNATURE 196 
#define  SIOCGIFOPPORTUNISTIC 195 
#define  SIOCGIFPDSTADDR 194 
#define  SIOCGIFPHYS 193 
#define  SIOCGIFPROBECONNECTIVITY 192 
#define  SIOCGIFPROTOLIST32 191 
#define  SIOCGIFPROTOLIST64 190 
#define  SIOCGIFPSRCADDR 189 
#define  SIOCGIFQUEUESTATS 188 
#define  SIOCGIFSTATUS 187 
#define  SIOCGIFTHROTTLE 186 
#define  SIOCGIFTIMESTAMPENABLED 185 
#define  SIOCGIFTYPE 184 
#define  SIOCGIFVLAN 183 
#define  SIOCGIFWAKEFLAGS 182 
#define  SIOCGPPPCSTATS 181 
#define  SIOCGPPPSTATS 180 
#define  SIOCGQOSMARKINGENABLED 179 
#define  SIOCGQOSMARKINGMODE 178 
#define  SIOCGSTARTDELAY 177 
#define  SIOCIFCREATE 176 
#define  SIOCIFCREATE2 175 
#define  SIOCIFDESTROY 174 
#define  SIOCIFGCLONERS32 173 
#define  SIOCIFGCLONERS64 172 
#define  SIOCPROTOATTACH 171 
#define  SIOCPROTODETACH 170 
#define  SIOCRSLVMULTI 169 
#define  SIOCSCONNORDER 168 
#define  SIOCSDRVSPEC32 167 
#define  SIOCSDRVSPEC64 166 
#define  SIOCSECNMODE 165 
#define  SIOCSETROUTERMODE 164 
#define  SIOCSIF2KCL 163 
#define  SIOCSIFADDR 162 
#define  SIOCSIFALTMTU 161 
#define  SIOCSIFASYNCMAP 160 
#define  SIOCSIFBOND 159 
#define  SIOCSIFBRDADDR 158 
#define  SIOCSIFCAP 157 
#define  SIOCSIFDESC 156 
#define  SIOCSIFDISABLEOUTPUT 155 
#define  SIOCSIFDSTADDR 154 
#define  SIOCSIFEXPENSIVE 153 
#define  SIOCSIFFLAGS 152 
#define  SIOCSIFGENERIC 151 
#define  SIOCSIFINTERFACESTATE 150 
#define  SIOCSIFKPI 149 
#define  SIOCSIFLINKPARAMS 148 
#define  SIOCSIFLLADDR 147 
#define  SIOCSIFLOG 146 
#define  SIOCSIFLOWINTERNET 145 
#define  SIOCSIFLOWPOWER 144 
#define  SIOCSIFMEDIA 143 
#define  SIOCSIFMETRIC 142 
#define  SIOCSIFMTU 141 
#define  SIOCSIFNETMASK 140 
#define  SIOCSIFNETSIGNATURE 139 
#define  SIOCSIFOPPORTUNISTIC 138 
#define  SIOCSIFORDER 137 
#define  SIOCSIFPHYADDR 136 
#define  SIOCSIFPHYS 135 
#define  SIOCSIFPROBECONNECTIVITY 134 
#define  SIOCSIFTHROTTLE 133 
#define  SIOCSIFTIMESTAMPDISABLE 132 
#define  SIOCSIFTIMESTAMPENABLE 131 
#define  SIOCSIFVLAN 130 
#define  SIOCSQOSMARKINGENABLED 129 
#define  SIOCSQOSMARKINGMODE 128 

__attribute__((used)) static __attribute__((unused)) void
ifioctl_cassert(void)
{
	/*
	 * This is equivalent to _CASSERT() and the compiler wouldn't
	 * generate any instructions, thus for compile time only.
	 */
	switch ((u_long)0) {
	case 0:

	/* bsd/net/if_ppp.h */
	case SIOCGPPPSTATS:
	case SIOCGPPPCSTATS:

#if INET6
	/* bsd/netinet6/in6_var.h */
	case SIOCSIFADDR_IN6:
	case SIOCGIFADDR_IN6:
	case SIOCSIFDSTADDR_IN6:
	case SIOCSIFNETMASK_IN6:
	case SIOCGIFDSTADDR_IN6:
	case SIOCGIFNETMASK_IN6:
	case SIOCDIFADDR_IN6:
	case SIOCAIFADDR_IN6_32:
	case SIOCAIFADDR_IN6_64:
	case SIOCSIFPHYADDR_IN6_32:
	case SIOCSIFPHYADDR_IN6_64:
	case SIOCGIFPSRCADDR_IN6:
	case SIOCGIFPDSTADDR_IN6:
	case SIOCGIFAFLAG_IN6:
	case SIOCGDRLST_IN6_32:
	case SIOCGDRLST_IN6_64:
	case SIOCGPRLST_IN6_32:
	case SIOCGPRLST_IN6_64:
	case OSIOCGIFINFO_IN6:
	case SIOCGIFINFO_IN6:
	case SIOCSNDFLUSH_IN6:
	case SIOCGNBRINFO_IN6_32:
	case SIOCGNBRINFO_IN6_64:
	case SIOCSPFXFLUSH_IN6:
	case SIOCSRTRFLUSH_IN6:
	case SIOCGIFALIFETIME_IN6:
	case SIOCSIFALIFETIME_IN6:
	case SIOCGIFSTAT_IN6:
	case SIOCGIFSTAT_ICMP6:
	case SIOCSDEFIFACE_IN6_32:
	case SIOCSDEFIFACE_IN6_64:
	case SIOCGDEFIFACE_IN6_32:
	case SIOCGDEFIFACE_IN6_64:
	case SIOCSIFINFO_FLAGS:
	case SIOCSSCOPE6:
	case SIOCGSCOPE6:
	case SIOCGSCOPE6DEF:
	case SIOCSIFPREFIX_IN6:
	case SIOCGIFPREFIX_IN6:
	case SIOCDIFPREFIX_IN6:
	case SIOCAIFPREFIX_IN6:
	case SIOCCIFPREFIX_IN6:
	case SIOCSGIFPREFIX_IN6:
	case SIOCPROTOATTACH_IN6_32:
	case SIOCPROTOATTACH_IN6_64:
	case SIOCPROTODETACH_IN6:
	case SIOCLL_START_32:
	case SIOCLL_START_64:
	case SIOCLL_STOP:
	case SIOCAUTOCONF_START:
	case SIOCAUTOCONF_STOP:
	case SIOCSETROUTERMODE_IN6:
	case SIOCLL_CGASTART_32:
	case SIOCLL_CGASTART_64:
	case SIOCGIFCGAPREP_IN6:
	case SIOCSIFCGAPREP_IN6:
#endif /* INET6 */

	/* bsd/sys/sockio.h */
	case SIOCSIFADDR:
	case OSIOCGIFADDR:
	case SIOCSIFDSTADDR:
	case OSIOCGIFDSTADDR:
	case SIOCSIFFLAGS:
	case SIOCGIFFLAGS:
	case OSIOCGIFBRDADDR:
	case SIOCSIFBRDADDR:
	case OSIOCGIFCONF32:
	case OSIOCGIFCONF64:
	case OSIOCGIFNETMASK:
	case SIOCSIFNETMASK:
	case SIOCGIFMETRIC:
	case SIOCSIFMETRIC:
	case SIOCDIFADDR:
	case SIOCAIFADDR:

	case SIOCGIFADDR:
	case SIOCGIFDSTADDR:
	case SIOCGIFBRDADDR:
	case SIOCGIFCONF32:
	case SIOCGIFCONF64:
	case SIOCGIFNETMASK:
	case SIOCAUTOADDR:
	case SIOCAUTONETMASK:
	case SIOCARPIPLL:

	case SIOCADDMULTI:
	case SIOCDELMULTI:
	case SIOCGIFMTU:
	case SIOCSIFMTU:
	case SIOCGIFPHYS:
	case SIOCSIFPHYS:
	case SIOCSIFMEDIA:
	case SIOCGIFMEDIA32:
	case SIOCGIFMEDIA64:
	case SIOCSIFGENERIC:
	case SIOCGIFGENERIC:
	case SIOCRSLVMULTI:

	case SIOCSIFLLADDR:
	case SIOCGIFSTATUS:
	case SIOCSIFPHYADDR:
	case SIOCGIFPSRCADDR:
	case SIOCGIFPDSTADDR:
	case SIOCDIFPHYADDR:

	case SIOCGIFDEVMTU:
	case SIOCSIFALTMTU:
	case SIOCGIFALTMTU:
	case SIOCSIFBOND:
	case SIOCGIFBOND:

	case SIOCPROTOATTACH:
	case SIOCPROTODETACH:

	case SIOCSIFCAP:
	case SIOCGIFCAP:

	case SIOCIFCREATE:
	case SIOCIFDESTROY:
	case SIOCIFCREATE2:

	case SIOCSDRVSPEC32:
	case SIOCGDRVSPEC32:
	case SIOCSDRVSPEC64:
	case SIOCGDRVSPEC64:

	case SIOCSIFVLAN:
	case SIOCGIFVLAN:

	case SIOCIFGCLONERS32:
	case SIOCIFGCLONERS64:

	case SIOCGIFASYNCMAP:
	case SIOCSIFASYNCMAP:
#if CONFIG_MACF_NET
	case SIOCGIFMAC:
	case SIOCSIFMAC:
#endif /* CONFIG_MACF_NET */
	case SIOCSIFKPI:
	case SIOCGIFKPI:

	case SIOCGIFWAKEFLAGS:

	case SIOCGIFGETRTREFCNT:
	case SIOCGIFLINKQUALITYMETRIC:
	case SIOCSIFOPPORTUNISTIC:
	case SIOCGIFOPPORTUNISTIC:
	case SIOCSETROUTERMODE:
	case SIOCGIFEFLAGS:
	case SIOCSIFDESC:
	case SIOCGIFDESC:
	case SIOCSIFLINKPARAMS:
	case SIOCGIFLINKPARAMS:
	case SIOCGIFQUEUESTATS:
	case SIOCSIFTHROTTLE:
	case SIOCGIFTHROTTLE:

	case SIOCGASSOCIDS32:
	case SIOCGASSOCIDS64:
	case SIOCGCONNIDS32:
	case SIOCGCONNIDS64:
	case SIOCGCONNINFO32:
	case SIOCGCONNINFO64:
	case SIOCSCONNORDER:
	case SIOCGCONNORDER:

	case SIOCSIFLOG:
	case SIOCGIFLOG:
	case SIOCGIFDELEGATE:
	case SIOCGIFLLADDR:
	case SIOCGIFTYPE:
	case SIOCGIFEXPENSIVE:
	case SIOCSIFEXPENSIVE:
	case SIOCGIF2KCL:
	case SIOCSIF2KCL:
	case SIOCGSTARTDELAY:

	case SIOCAIFAGENTID:
	case SIOCDIFAGENTID:
	case SIOCGIFAGENTIDS32:
	case SIOCGIFAGENTIDS64:
	case SIOCGIFAGENTDATA32:
	case SIOCGIFAGENTDATA64:

	case SIOCSIFINTERFACESTATE:
	case SIOCGIFINTERFACESTATE:
	case SIOCSIFPROBECONNECTIVITY:
	case SIOCGIFPROBECONNECTIVITY:

	case SIOCGIFFUNCTIONALTYPE:
	case SIOCSIFNETSIGNATURE:
	case SIOCGIFNETSIGNATURE:

	case SIOCGECNMODE:
	case SIOCSECNMODE:

	case SIOCSIFORDER:

	case SIOCSQOSMARKINGMODE:
	case SIOCSQOSMARKINGENABLED:
	case SIOCGQOSMARKINGMODE:
	case SIOCGQOSMARKINGENABLED:

	case SIOCSIFTIMESTAMPENABLE:
	case SIOCSIFTIMESTAMPDISABLE:
	case SIOCGIFTIMESTAMPENABLED:

	case SIOCSIFDISABLEOUTPUT:

	case SIOCGIFAGENTLIST32:
	case SIOCGIFAGENTLIST64:

	case SIOCSIFLOWINTERNET:
	case SIOCGIFLOWINTERNET:

#if INET6
	case SIOCGIFNAT64PREFIX:
	case SIOCSIFNAT64PREFIX:

	case SIOCGIFCLAT46ADDR:
#endif /* INET6 */

	case SIOCGIFPROTOLIST32:
	case SIOCGIFPROTOLIST64:

	case SIOCGIFLOWPOWER:
	case SIOCSIFLOWPOWER:
		;
	}
}