#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  scalar_t__ u8 ;
typedef  scalar_t__ u32 ;
typedef  int u16 ;
struct mlx5_core_dev {int dummy; } ;

/* Variables and functions */
 int EINVAL ; 
 int EIO ; 
#define  MLX5_CMD_OP_2ERR_QP 257 
#define  MLX5_CMD_OP_2RST_QP 256 
#define  MLX5_CMD_OP_ACCESS_REG 255 
#define  MLX5_CMD_OP_ADD_VXLAN_UDP_DPORT 254 
#define  MLX5_CMD_OP_ALLOC_PD 253 
#define  MLX5_CMD_OP_ALLOC_Q_COUNTER 252 
#define  MLX5_CMD_OP_ALLOC_TRANSPORT_DOMAIN 251 
#define  MLX5_CMD_OP_ALLOC_UAR 250 
#define  MLX5_CMD_OP_ALLOC_XRCD 249 
#define  MLX5_CMD_OP_ARM_DCT_FOR_KEY_VIOLATION 248 
#define  MLX5_CMD_OP_ARM_RQ 247 
#define  MLX5_CMD_OP_ARM_XRC_SRQ 246 
#define  MLX5_CMD_OP_ATTACH_TO_MCG 245 
#define  MLX5_CMD_OP_CONFIG_INT_MODERATION 244 
#define  MLX5_CMD_OP_CREATE_CQ 243 
#define  MLX5_CMD_OP_CREATE_DCT 242 
#define  MLX5_CMD_OP_CREATE_EQ 241 
#define  MLX5_CMD_OP_CREATE_FLOW_GROUP 240 
#define  MLX5_CMD_OP_CREATE_FLOW_TABLE 239 
#define  MLX5_CMD_OP_CREATE_MKEY 238 
#define  MLX5_CMD_OP_CREATE_PSV 237 
#define  MLX5_CMD_OP_CREATE_QP 236 
#define  MLX5_CMD_OP_CREATE_RMP 235 
#define  MLX5_CMD_OP_CREATE_RQ 234 
#define  MLX5_CMD_OP_CREATE_RQT 233 
#define  MLX5_CMD_OP_CREATE_SQ 232 
#define  MLX5_CMD_OP_CREATE_SRQ 231 
#define  MLX5_CMD_OP_CREATE_TIR 230 
#define  MLX5_CMD_OP_CREATE_TIS 229 
#define  MLX5_CMD_OP_CREATE_XRC_SRQ 228 
#define  MLX5_CMD_OP_DEALLOC_PD 227 
#define  MLX5_CMD_OP_DEALLOC_Q_COUNTER 226 
#define  MLX5_CMD_OP_DEALLOC_TRANSPORT_DOMAIN 225 
#define  MLX5_CMD_OP_DEALLOC_UAR 224 
#define  MLX5_CMD_OP_DEALLOC_XRCD 223 
#define  MLX5_CMD_OP_DELETE_FLOW_TABLE_ENTRY 222 
#define  MLX5_CMD_OP_DELETE_L2_TABLE_ENTRY 221 
#define  MLX5_CMD_OP_DELETE_VXLAN_UDP_DPORT 220 
#define  MLX5_CMD_OP_DESTROY_CQ 219 
#define  MLX5_CMD_OP_DESTROY_DCT 218 
#define  MLX5_CMD_OP_DESTROY_EQ 217 
#define  MLX5_CMD_OP_DESTROY_FLOW_GROUP 216 
#define  MLX5_CMD_OP_DESTROY_FLOW_TABLE 215 
#define  MLX5_CMD_OP_DESTROY_MKEY 214 
#define  MLX5_CMD_OP_DESTROY_PSV 213 
#define  MLX5_CMD_OP_DESTROY_QP 212 
#define  MLX5_CMD_OP_DESTROY_RMP 211 
#define  MLX5_CMD_OP_DESTROY_RQ 210 
#define  MLX5_CMD_OP_DESTROY_RQT 209 
#define  MLX5_CMD_OP_DESTROY_SQ 208 
#define  MLX5_CMD_OP_DESTROY_SRQ 207 
#define  MLX5_CMD_OP_DESTROY_TIR 206 
#define  MLX5_CMD_OP_DESTROY_TIS 205 
#define  MLX5_CMD_OP_DESTROY_XRC_SRQ 204 
#define  MLX5_CMD_OP_DETACH_FROM_MCG 203 
#define  MLX5_CMD_OP_DISABLE_HCA 202 
#define  MLX5_CMD_OP_DRAIN_DCT 201 
#define  MLX5_CMD_OP_ENABLE_HCA 200 
#define  MLX5_CMD_OP_GEN_EQE 199 
#define  MLX5_CMD_OP_GET_DROPPED_PACKET_LOG 198 
#define  MLX5_CMD_OP_INIT2INIT_QP 197 
#define  MLX5_CMD_OP_INIT2RTR_QP 196 
#define  MLX5_CMD_OP_INIT_HCA 195 
#define  MLX5_CMD_OP_MAD_IFC 194 
#define  MLX5_CMD_OP_MANAGE_PAGES 193 
#define  MLX5_CMD_OP_MODIFY_CONG_PARAMS 192 
#define  MLX5_CMD_OP_MODIFY_CONG_STATUS 191 
#define  MLX5_CMD_OP_MODIFY_CQ 190 
#define  MLX5_CMD_OP_MODIFY_ESW_VPORT_CONTEXT 189 
#define  MLX5_CMD_OP_MODIFY_FLOW_TABLE 188 
#define  MLX5_CMD_OP_MODIFY_HCA_VPORT_CONTEXT 187 
#define  MLX5_CMD_OP_MODIFY_NIC_VPORT_CONTEXT 186 
#define  MLX5_CMD_OP_MODIFY_RMP 185 
#define  MLX5_CMD_OP_MODIFY_RQ 184 
#define  MLX5_CMD_OP_MODIFY_RQT 183 
#define  MLX5_CMD_OP_MODIFY_SQ 182 
#define  MLX5_CMD_OP_MODIFY_TIR 181 
#define  MLX5_CMD_OP_MODIFY_TIS 180 
#define  MLX5_CMD_OP_MODIFY_VPORT_STATE 179 
#define  MLX5_CMD_OP_NOP 178 
#define  MLX5_CMD_OP_PAGE_FAULT_RESUME 177 
#define  MLX5_CMD_OP_QUERY_ADAPTER 176 
#define  MLX5_CMD_OP_QUERY_CONG_PARAMS 175 
#define  MLX5_CMD_OP_QUERY_CONG_STATISTICS 174 
#define  MLX5_CMD_OP_QUERY_CONG_STATUS 173 
#define  MLX5_CMD_OP_QUERY_CQ 172 
#define  MLX5_CMD_OP_QUERY_DCT 171 
#define  MLX5_CMD_OP_QUERY_EQ 170 
#define  MLX5_CMD_OP_QUERY_ESW_VPORT_CONTEXT 169 
#define  MLX5_CMD_OP_QUERY_FLOW_GROUP 168 
#define  MLX5_CMD_OP_QUERY_FLOW_TABLE 167 
#define  MLX5_CMD_OP_QUERY_FLOW_TABLE_ENTRY 166 
#define  MLX5_CMD_OP_QUERY_HCA_CAP 165 
#define  MLX5_CMD_OP_QUERY_HCA_VPORT_CONTEXT 164 
#define  MLX5_CMD_OP_QUERY_HCA_VPORT_GID 163 
#define  MLX5_CMD_OP_QUERY_HCA_VPORT_PKEY 162 
#define  MLX5_CMD_OP_QUERY_ISSI 161 
#define  MLX5_CMD_OP_QUERY_L2_TABLE_ENTRY 160 
#define  MLX5_CMD_OP_QUERY_MAD_DEMUX 159 
#define  MLX5_CMD_OP_QUERY_MKEY 158 
#define  MLX5_CMD_OP_QUERY_NIC_VPORT_CONTEXT 157 
#define  MLX5_CMD_OP_QUERY_PAGES 156 
#define  MLX5_CMD_OP_QUERY_QP 155 
#define  MLX5_CMD_OP_QUERY_Q_COUNTER 154 
#define  MLX5_CMD_OP_QUERY_RMP 153 
#define  MLX5_CMD_OP_QUERY_ROCE_ADDRESS 152 
#define  MLX5_CMD_OP_QUERY_RQ 151 
#define  MLX5_CMD_OP_QUERY_RQT 150 
#define  MLX5_CMD_OP_QUERY_SPECIAL_CONTEXTS 149 
#define  MLX5_CMD_OP_QUERY_SQ 148 
#define  MLX5_CMD_OP_QUERY_SRQ 147 
#define  MLX5_CMD_OP_QUERY_TIR 146 
#define  MLX5_CMD_OP_QUERY_TIS 145 
#define  MLX5_CMD_OP_QUERY_VNIC_ENV 144 
#define  MLX5_CMD_OP_QUERY_VPORT_COUNTER 143 
#define  MLX5_CMD_OP_QUERY_VPORT_STATE 142 
#define  MLX5_CMD_OP_QUERY_XRC_SRQ 141 
#define  MLX5_CMD_OP_RST2INIT_QP 140 
#define  MLX5_CMD_OP_RTR2RTS_QP 139 
#define  MLX5_CMD_OP_RTS2RTS_QP 138 
#define  MLX5_CMD_OP_SET_FLOW_TABLE_ENTRY 137 
#define  MLX5_CMD_OP_SET_FLOW_TABLE_ROOT 136 
#define  MLX5_CMD_OP_SET_HCA_CAP 135 
#define  MLX5_CMD_OP_SET_ISSI 134 
#define  MLX5_CMD_OP_SET_L2_TABLE_ENTRY 133 
#define  MLX5_CMD_OP_SET_MAD_DEMUX 132 
#define  MLX5_CMD_OP_SET_ROCE_ADDRESS 131 
#define  MLX5_CMD_OP_SQD_RTS_QP 130 
#define  MLX5_CMD_OP_SQERR2RTS_QP 129 
#define  MLX5_CMD_OP_TEARDOWN_HCA 128 
 int MLX5_CMD_STAT_OK ; 
 scalar_t__ MLX5_DRIVER_STATUS_ABORTED ; 
 scalar_t__ MLX5_DRIVER_SYND ; 
 int /*<<< orphan*/  mlx5_core_err (struct mlx5_core_dev*,char*,int) ; 

__attribute__((used)) static int mlx5_internal_err_ret_value(struct mlx5_core_dev *dev, u16 op,
				       u32 *synd, u8 *status)
{
	*synd = 0;
	*status = 0;

	switch (op) {
	case MLX5_CMD_OP_TEARDOWN_HCA:
	case MLX5_CMD_OP_DISABLE_HCA:
	case MLX5_CMD_OP_MANAGE_PAGES:
	case MLX5_CMD_OP_DESTROY_MKEY:
	case MLX5_CMD_OP_DESTROY_EQ:
	case MLX5_CMD_OP_DESTROY_CQ:
	case MLX5_CMD_OP_DESTROY_QP:
	case MLX5_CMD_OP_DESTROY_PSV:
	case MLX5_CMD_OP_DESTROY_SRQ:
	case MLX5_CMD_OP_DESTROY_XRC_SRQ:
	case MLX5_CMD_OP_DESTROY_DCT:
	case MLX5_CMD_OP_DEALLOC_Q_COUNTER:
	case MLX5_CMD_OP_DEALLOC_PD:
	case MLX5_CMD_OP_DEALLOC_UAR:
	case MLX5_CMD_OP_DETACH_FROM_MCG:
	case MLX5_CMD_OP_DEALLOC_XRCD:
	case MLX5_CMD_OP_DEALLOC_TRANSPORT_DOMAIN:
	case MLX5_CMD_OP_DELETE_VXLAN_UDP_DPORT:
	case MLX5_CMD_OP_DELETE_L2_TABLE_ENTRY:
	case MLX5_CMD_OP_DESTROY_TIR:
	case MLX5_CMD_OP_DESTROY_SQ:
	case MLX5_CMD_OP_DESTROY_RQ:
	case MLX5_CMD_OP_DESTROY_RMP:
	case MLX5_CMD_OP_DESTROY_TIS:
	case MLX5_CMD_OP_DESTROY_RQT:
	case MLX5_CMD_OP_DESTROY_FLOW_TABLE:
	case MLX5_CMD_OP_DESTROY_FLOW_GROUP:
	case MLX5_CMD_OP_DELETE_FLOW_TABLE_ENTRY:
	case MLX5_CMD_OP_2ERR_QP:
	case MLX5_CMD_OP_2RST_QP:
	case MLX5_CMD_OP_MODIFY_NIC_VPORT_CONTEXT:
	case MLX5_CMD_OP_MODIFY_FLOW_TABLE:
	case MLX5_CMD_OP_SET_FLOW_TABLE_ENTRY:
	case MLX5_CMD_OP_SET_FLOW_TABLE_ROOT:
		return MLX5_CMD_STAT_OK;

	case MLX5_CMD_OP_QUERY_HCA_CAP:
	case MLX5_CMD_OP_QUERY_ADAPTER:
	case MLX5_CMD_OP_INIT_HCA:
	case MLX5_CMD_OP_ENABLE_HCA:
	case MLX5_CMD_OP_QUERY_PAGES:
	case MLX5_CMD_OP_SET_HCA_CAP:
	case MLX5_CMD_OP_QUERY_ISSI:
	case MLX5_CMD_OP_SET_ISSI:
	case MLX5_CMD_OP_CREATE_MKEY:
	case MLX5_CMD_OP_QUERY_MKEY:
	case MLX5_CMD_OP_QUERY_SPECIAL_CONTEXTS:
	case MLX5_CMD_OP_PAGE_FAULT_RESUME:
	case MLX5_CMD_OP_CREATE_EQ:
	case MLX5_CMD_OP_QUERY_EQ:
	case MLX5_CMD_OP_GEN_EQE:
	case MLX5_CMD_OP_CREATE_CQ:
	case MLX5_CMD_OP_QUERY_CQ:
	case MLX5_CMD_OP_MODIFY_CQ:
	case MLX5_CMD_OP_CREATE_QP:
	case MLX5_CMD_OP_RST2INIT_QP:
	case MLX5_CMD_OP_INIT2RTR_QP:
	case MLX5_CMD_OP_RTR2RTS_QP:
	case MLX5_CMD_OP_RTS2RTS_QP:
	case MLX5_CMD_OP_SQERR2RTS_QP:
	case MLX5_CMD_OP_QUERY_QP:
	case MLX5_CMD_OP_SQD_RTS_QP:
	case MLX5_CMD_OP_INIT2INIT_QP:
	case MLX5_CMD_OP_CREATE_PSV:
	case MLX5_CMD_OP_CREATE_SRQ:
	case MLX5_CMD_OP_QUERY_SRQ:
	case MLX5_CMD_OP_ARM_RQ:
	case MLX5_CMD_OP_CREATE_XRC_SRQ:
	case MLX5_CMD_OP_QUERY_XRC_SRQ:
	case MLX5_CMD_OP_ARM_XRC_SRQ:
	case MLX5_CMD_OP_CREATE_DCT:
	case MLX5_CMD_OP_DRAIN_DCT:
	case MLX5_CMD_OP_QUERY_DCT:
	case MLX5_CMD_OP_ARM_DCT_FOR_KEY_VIOLATION:
	case MLX5_CMD_OP_QUERY_VPORT_STATE:
	case MLX5_CMD_OP_MODIFY_VPORT_STATE:
	case MLX5_CMD_OP_QUERY_ESW_VPORT_CONTEXT:
	case MLX5_CMD_OP_MODIFY_ESW_VPORT_CONTEXT:
	case MLX5_CMD_OP_QUERY_NIC_VPORT_CONTEXT:
	case MLX5_CMD_OP_QUERY_ROCE_ADDRESS:
	case MLX5_CMD_OP_SET_ROCE_ADDRESS:
	case MLX5_CMD_OP_QUERY_HCA_VPORT_CONTEXT:
	case MLX5_CMD_OP_MODIFY_HCA_VPORT_CONTEXT:
	case MLX5_CMD_OP_QUERY_HCA_VPORT_GID:
	case MLX5_CMD_OP_QUERY_HCA_VPORT_PKEY:
	case MLX5_CMD_OP_QUERY_VNIC_ENV:
	case MLX5_CMD_OP_QUERY_VPORT_COUNTER:
	case MLX5_CMD_OP_ALLOC_Q_COUNTER:
	case MLX5_CMD_OP_QUERY_Q_COUNTER:
	case MLX5_CMD_OP_ALLOC_PD:
	case MLX5_CMD_OP_ALLOC_UAR:
	case MLX5_CMD_OP_CONFIG_INT_MODERATION:
	case MLX5_CMD_OP_ACCESS_REG:
	case MLX5_CMD_OP_ATTACH_TO_MCG:
	case MLX5_CMD_OP_GET_DROPPED_PACKET_LOG:
	case MLX5_CMD_OP_MAD_IFC:
	case MLX5_CMD_OP_QUERY_MAD_DEMUX:
	case MLX5_CMD_OP_SET_MAD_DEMUX:
	case MLX5_CMD_OP_NOP:
	case MLX5_CMD_OP_ALLOC_XRCD:
	case MLX5_CMD_OP_ALLOC_TRANSPORT_DOMAIN:
	case MLX5_CMD_OP_QUERY_CONG_STATUS:
	case MLX5_CMD_OP_MODIFY_CONG_STATUS:
	case MLX5_CMD_OP_QUERY_CONG_PARAMS:
	case MLX5_CMD_OP_MODIFY_CONG_PARAMS:
	case MLX5_CMD_OP_QUERY_CONG_STATISTICS:
	case MLX5_CMD_OP_ADD_VXLAN_UDP_DPORT:
	case MLX5_CMD_OP_SET_L2_TABLE_ENTRY:
	case MLX5_CMD_OP_QUERY_L2_TABLE_ENTRY:
	case MLX5_CMD_OP_CREATE_TIR:
	case MLX5_CMD_OP_MODIFY_TIR:
	case MLX5_CMD_OP_QUERY_TIR:
	case MLX5_CMD_OP_CREATE_SQ:
	case MLX5_CMD_OP_MODIFY_SQ:
	case MLX5_CMD_OP_QUERY_SQ:
	case MLX5_CMD_OP_CREATE_RQ:
	case MLX5_CMD_OP_MODIFY_RQ:
	case MLX5_CMD_OP_QUERY_RQ:
	case MLX5_CMD_OP_CREATE_RMP:
	case MLX5_CMD_OP_MODIFY_RMP:
	case MLX5_CMD_OP_QUERY_RMP:
	case MLX5_CMD_OP_CREATE_TIS:
	case MLX5_CMD_OP_MODIFY_TIS:
	case MLX5_CMD_OP_QUERY_TIS:
	case MLX5_CMD_OP_CREATE_RQT:
	case MLX5_CMD_OP_MODIFY_RQT:
	case MLX5_CMD_OP_QUERY_RQT:
	case MLX5_CMD_OP_CREATE_FLOW_TABLE:
	case MLX5_CMD_OP_QUERY_FLOW_TABLE:
	case MLX5_CMD_OP_CREATE_FLOW_GROUP:
	case MLX5_CMD_OP_QUERY_FLOW_GROUP:
	case MLX5_CMD_OP_QUERY_FLOW_TABLE_ENTRY:
		*status = MLX5_DRIVER_STATUS_ABORTED;
		*synd = MLX5_DRIVER_SYND;
		return -EIO;
	default:
		mlx5_core_err(dev, "Unknown FW command (%d)\n", op);
		return -EINVAL;
	}
}