#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  int /*<<< orphan*/  TCase ;
typedef  int /*<<< orphan*/  Suite ;

/* Variables and functions */
 int /*<<< orphan*/ * alloc_setup ; 
 int /*<<< orphan*/  alloc_teardown ; 
 int /*<<< orphan*/ * basic_setup ; 
 int /*<<< orphan*/  basic_teardown ; 
 int /*<<< orphan*/ * namespace_setup ; 
 int /*<<< orphan*/  namespace_teardown ; 
 int /*<<< orphan*/ * nsalloc_setup ; 
 int /*<<< orphan*/  nsalloc_teardown ; 
 int /*<<< orphan*/  suite_add_tcase (int /*<<< orphan*/ *,int /*<<< orphan*/ *) ; 
 int /*<<< orphan*/ * suite_create (char*) ; 
 int /*<<< orphan*/  tcase_add_checked_fixture (int /*<<< orphan*/ *,int /*<<< orphan*/ *,int /*<<< orphan*/ ) ; 
 int /*<<< orphan*/  tcase_add_test (int /*<<< orphan*/ *,int /*<<< orphan*/ ) ; 
 int /*<<< orphan*/ * tcase_create (char*) ; 
 int /*<<< orphan*/  test_abort_epilog ; 
 int /*<<< orphan*/  test_abort_epilog_2 ; 
 int /*<<< orphan*/  test_alloc_attribute_enum_value ; 
 int /*<<< orphan*/  test_alloc_attribute_predefined_entity ; 
 int /*<<< orphan*/  test_alloc_attribute_whitespace ; 
 int /*<<< orphan*/  test_alloc_comment_in_epilog ; 
 int /*<<< orphan*/  test_alloc_create_external_parser ; 
 int /*<<< orphan*/  test_alloc_dtd_copy_default_atts ; 
 int /*<<< orphan*/  test_alloc_dtd_default_handling ; 
 int /*<<< orphan*/  test_alloc_explicit_encoding ; 
 int /*<<< orphan*/  test_alloc_ext_entity_realloc_buffer ; 
 int /*<<< orphan*/  test_alloc_ext_entity_set_encoding ; 
 int /*<<< orphan*/  test_alloc_external_entity ; 
 int /*<<< orphan*/  test_alloc_internal_entity ; 
 int /*<<< orphan*/  test_alloc_large_group ; 
 int /*<<< orphan*/  test_alloc_long_attr_default_with_char_ref ; 
 int /*<<< orphan*/  test_alloc_long_attr_value ; 
 int /*<<< orphan*/  test_alloc_long_base ; 
 int /*<<< orphan*/  test_alloc_long_doc_name ; 
 int /*<<< orphan*/  test_alloc_long_entity_value ; 
 int /*<<< orphan*/  test_alloc_long_notation ; 
 int /*<<< orphan*/  test_alloc_long_public_id ; 
 int /*<<< orphan*/  test_alloc_nested_entities ; 
 int /*<<< orphan*/  test_alloc_nested_groups ; 
 int /*<<< orphan*/  test_alloc_notation ; 
 int /*<<< orphan*/  test_alloc_parse_comment ; 
 int /*<<< orphan*/  test_alloc_parse_comment_2 ; 
 int /*<<< orphan*/  test_alloc_parse_pi ; 
 int /*<<< orphan*/  test_alloc_parse_pi_2 ; 
 int /*<<< orphan*/  test_alloc_parse_pi_3 ; 
 int /*<<< orphan*/  test_alloc_parse_public_doctype ; 
 int /*<<< orphan*/  test_alloc_parse_public_doctype_long_name ; 
 int /*<<< orphan*/  test_alloc_parse_xdecl ; 
 int /*<<< orphan*/  test_alloc_parse_xdecl_2 ; 
 int /*<<< orphan*/  test_alloc_pi_in_epilog ; 
 int /*<<< orphan*/  test_alloc_public_entity_value ; 
 int /*<<< orphan*/  test_alloc_public_notation ; 
 int /*<<< orphan*/  test_alloc_realloc_attribute_enum_value ; 
 int /*<<< orphan*/  test_alloc_realloc_attributes ; 
 int /*<<< orphan*/  test_alloc_realloc_buffer ; 
 int /*<<< orphan*/  test_alloc_realloc_ce_extends_pe ; 
 int /*<<< orphan*/  test_alloc_realloc_default_attribute ; 
 int /*<<< orphan*/  test_alloc_realloc_group_choice ; 
 int /*<<< orphan*/  test_alloc_realloc_implied_attribute ; 
 int /*<<< orphan*/  test_alloc_realloc_long_attribute_value ; 
 int /*<<< orphan*/  test_alloc_realloc_many_attributes ; 
 int /*<<< orphan*/  test_alloc_realloc_nested_groups ; 
 int /*<<< orphan*/  test_alloc_realloc_param_entity_newline ; 
 int /*<<< orphan*/  test_alloc_realloc_subst_public_entity_value ; 
 int /*<<< orphan*/  test_alloc_run_external_parser ; 
 int /*<<< orphan*/  test_alloc_set_base ; 
 int /*<<< orphan*/  test_alloc_set_foreign_dtd ; 
 int /*<<< orphan*/  test_alloc_system_notation ; 
 int /*<<< orphan*/  test_attr_after_solidus ; 
 int /*<<< orphan*/  test_attr_whitespace_normalization ; 
 int /*<<< orphan*/  test_attribute_enum_value ; 
 int /*<<< orphan*/  test_attributes ; 
 int /*<<< orphan*/  test_bad_attr_desc_keyword ; 
 int /*<<< orphan*/  test_bad_attr_desc_keyword_utf16 ; 
 int /*<<< orphan*/  test_bad_cdata ; 
 int /*<<< orphan*/  test_bad_cdata_utf16 ; 
 int /*<<< orphan*/  test_bad_doctype ; 
 int /*<<< orphan*/  test_bad_doctype_plus ; 
 int /*<<< orphan*/  test_bad_doctype_query ; 
 int /*<<< orphan*/  test_bad_doctype_star ; 
 int /*<<< orphan*/  test_bad_doctype_utf16 ; 
 int /*<<< orphan*/  test_bad_encoding ; 
 int /*<<< orphan*/  test_bad_entity ; 
 int /*<<< orphan*/  test_bad_entity_2 ; 
 int /*<<< orphan*/  test_bad_entity_3 ; 
 int /*<<< orphan*/  test_bad_entity_4 ; 
 int /*<<< orphan*/  test_bad_ignore_section ; 
 int /*<<< orphan*/  test_bad_notation ; 
 int /*<<< orphan*/  test_bad_public_doctype ; 
 int /*<<< orphan*/  test_bom_utf16_be ; 
 int /*<<< orphan*/  test_bom_utf16_le ; 
 int /*<<< orphan*/  test_bom_utf8 ; 
 int /*<<< orphan*/  test_byte_info_at_cdata ; 
 int /*<<< orphan*/  test_byte_info_at_end ; 
 int /*<<< orphan*/  test_byte_info_at_error ; 
 int /*<<< orphan*/  test_cdata_default ; 
 int /*<<< orphan*/  test_column_number_after_error ; 
 int /*<<< orphan*/  test_column_number_after_parse ; 
 int /*<<< orphan*/  test_comment_handled_in_default ; 
 int /*<<< orphan*/  test_danish_latin1 ; 
 int /*<<< orphan*/  test_default_current ; 
 int /*<<< orphan*/  test_default_doctype_handler ; 
 int /*<<< orphan*/  test_default_ns_from_ext_subset_and_ext_ge ; 
 int /*<<< orphan*/  test_dtd_attr_handling ; 
 int /*<<< orphan*/  test_dtd_default_handling ; 
 int /*<<< orphan*/  test_dtd_elements ; 
 int /*<<< orphan*/  test_dtd_stop_processing ; 
 int /*<<< orphan*/  test_empty_element_abort ; 
 int /*<<< orphan*/  test_empty_foreign_dtd ; 
 int /*<<< orphan*/  test_empty_ns_without_namespaces ; 
 int /*<<< orphan*/  test_empty_parse ; 
 int /*<<< orphan*/  test_end_element_events ; 
 int /*<<< orphan*/  test_entity_in_utf16_be_attr ; 
 int /*<<< orphan*/  test_entity_in_utf16_le_attr ; 
 int /*<<< orphan*/  test_entity_public_utf16_be ; 
 int /*<<< orphan*/  test_entity_public_utf16_le ; 
 int /*<<< orphan*/  test_entity_with_external_subset_unless_standalone ; 
 int /*<<< orphan*/  test_explicit_encoding ; 
 int /*<<< orphan*/  test_ext_entity_bad_encoding ; 
 int /*<<< orphan*/  test_ext_entity_bad_encoding_2 ; 
 int /*<<< orphan*/  test_ext_entity_good_cdata ; 
 int /*<<< orphan*/  test_ext_entity_invalid_parse ; 
 int /*<<< orphan*/  test_ext_entity_invalid_suspended_parse ; 
 int /*<<< orphan*/  test_ext_entity_latin1_utf16be_bom ; 
 int /*<<< orphan*/  test_ext_entity_latin1_utf16be_bom2 ; 
 int /*<<< orphan*/  test_ext_entity_latin1_utf16le_bom ; 
 int /*<<< orphan*/  test_ext_entity_latin1_utf16le_bom2 ; 
 int /*<<< orphan*/  test_ext_entity_no_handler ; 
 int /*<<< orphan*/  test_ext_entity_not_standalone ; 
 int /*<<< orphan*/  test_ext_entity_ref_parameter ; 
 int /*<<< orphan*/  test_ext_entity_set_bom ; 
 int /*<<< orphan*/  test_ext_entity_set_encoding ; 
 int /*<<< orphan*/  test_ext_entity_trailing_cr ; 
 int /*<<< orphan*/  test_ext_entity_trailing_rsqb ; 
 int /*<<< orphan*/  test_ext_entity_utf16_be ; 
 int /*<<< orphan*/  test_ext_entity_utf16_le ; 
 int /*<<< orphan*/  test_ext_entity_utf16_unknown ; 
 int /*<<< orphan*/  test_ext_entity_utf8_non_bom ; 
 int /*<<< orphan*/  test_ext_entity_value_abort ; 
 int /*<<< orphan*/  test_external_entity_values ; 
 int /*<<< orphan*/  test_failing_encoding_conversion_fn ; 
 int /*<<< orphan*/  test_foreign_dtd_not_standalone ; 
 int /*<<< orphan*/  test_foreign_dtd_with_doctype ; 
 int /*<<< orphan*/  test_foreign_dtd_without_external_subset ; 
 int /*<<< orphan*/  test_french_charref_decimal ; 
 int /*<<< orphan*/  test_french_charref_hexidecimal ; 
 int /*<<< orphan*/  test_french_latin1 ; 
 int /*<<< orphan*/  test_french_utf8 ; 
 int /*<<< orphan*/  test_get_buffer_1 ; 
 int /*<<< orphan*/  test_get_buffer_2 ; 
 int /*<<< orphan*/  test_good_cdata_ascii ; 
 int /*<<< orphan*/  test_good_cdata_utf16 ; 
 int /*<<< orphan*/  test_good_cdata_utf16_le ; 
 int /*<<< orphan*/  test_group_choice ; 
 int /*<<< orphan*/  test_hash_collision ; 
 int /*<<< orphan*/  test_ignore_section ; 
 int /*<<< orphan*/  test_ignore_section_utf16 ; 
 int /*<<< orphan*/  test_ignore_section_utf16_be ; 
 int /*<<< orphan*/  test_illegal_utf8 ; 
 int /*<<< orphan*/  test_invalid_character_entity ; 
 int /*<<< orphan*/  test_invalid_character_entity_2 ; 
 int /*<<< orphan*/  test_invalid_character_entity_3 ; 
 int /*<<< orphan*/  test_invalid_character_entity_4 ; 
 int /*<<< orphan*/  test_invalid_foreign_dtd ; 
 int /*<<< orphan*/  test_invalid_tag_in_dtd ; 
 int /*<<< orphan*/  test_invalid_unknown_encoding ; 
 int /*<<< orphan*/  test_latin1_umlauts ; 
 int /*<<< orphan*/  test_line_and_column_numbers_inside_handlers ; 
 int /*<<< orphan*/  test_line_number_after_error ; 
 int /*<<< orphan*/  test_line_number_after_parse ; 
 int /*<<< orphan*/  test_long_ascii_attribute ; 
 int /*<<< orphan*/  test_long_cdata_utf16 ; 
 int /*<<< orphan*/  test_long_doctype ; 
 int /*<<< orphan*/  test_long_latin1_attribute ; 
 int /*<<< orphan*/  test_long_utf8_character ; 
 int /*<<< orphan*/  test_memory_allocation ; 
 int /*<<< orphan*/  test_misc_alloc_create_parser ; 
 int /*<<< orphan*/  test_misc_alloc_create_parser_with_encoding ; 
 int /*<<< orphan*/  test_misc_attribute_leak ; 
 int /*<<< orphan*/  test_misc_error_string ; 
 int /*<<< orphan*/  test_misc_features ; 
 int /*<<< orphan*/  test_misc_null_parser ; 
 int /*<<< orphan*/  test_misc_utf16le ; 
 int /*<<< orphan*/  test_misc_version ; 
 int /*<<< orphan*/  test_missing_encoding_conversion_fn ; 
 int /*<<< orphan*/  test_multichar_cdata_utf16 ; 
 int /*<<< orphan*/  test_nested_groups ; 
 int /*<<< orphan*/  test_nobom_utf16_le ; 
 int /*<<< orphan*/  test_not_predefined_entities ; 
 int /*<<< orphan*/  test_not_standalone_handler_accept ; 
 int /*<<< orphan*/  test_not_standalone_handler_reject ; 
 int /*<<< orphan*/  test_not_utf16 ; 
 int /*<<< orphan*/  test_ns_bad_attr_leafname ; 
 int /*<<< orphan*/  test_ns_bad_element_leafname ; 
 int /*<<< orphan*/  test_ns_default_with_empty_uri ; 
 int /*<<< orphan*/  test_ns_double_colon ; 
 int /*<<< orphan*/  test_ns_double_colon_doctype ; 
 int /*<<< orphan*/  test_ns_double_colon_element ; 
 int /*<<< orphan*/  test_ns_duplicate_attrs_diff_prefixes ; 
 int /*<<< orphan*/  test_ns_duplicate_hashes ; 
 int /*<<< orphan*/  test_ns_extend_uri_buffer ; 
 int /*<<< orphan*/  test_ns_extremely_long_prefix ; 
 int /*<<< orphan*/  test_ns_in_attribute_default_without_namespaces ; 
 int /*<<< orphan*/  test_ns_invalid_doctype ; 
 int /*<<< orphan*/  test_ns_long_element ; 
 int /*<<< orphan*/  test_ns_mixed_prefix_atts ; 
 int /*<<< orphan*/  test_ns_parser_reset ; 
 int /*<<< orphan*/  test_ns_prefix_with_empty_uri_1 ; 
 int /*<<< orphan*/  test_ns_prefix_with_empty_uri_2 ; 
 int /*<<< orphan*/  test_ns_prefix_with_empty_uri_3 ; 
 int /*<<< orphan*/  test_ns_prefix_with_empty_uri_4 ; 
 int /*<<< orphan*/  test_ns_reserved_attributes ; 
 int /*<<< orphan*/  test_ns_reserved_attributes_2 ; 
 int /*<<< orphan*/  test_ns_tagname_overwrite ; 
 int /*<<< orphan*/  test_ns_tagname_overwrite_triplet ; 
 int /*<<< orphan*/  test_ns_unbound_prefix ; 
 int /*<<< orphan*/  test_ns_unbound_prefix_on_attribute ; 
 int /*<<< orphan*/  test_ns_unbound_prefix_on_element ; 
 int /*<<< orphan*/  test_ns_unknown_encoding_success ; 
 int /*<<< orphan*/  test_ns_utf16_doctype ; 
 int /*<<< orphan*/  test_ns_utf16_element_leafname ; 
 int /*<<< orphan*/  test_ns_utf16_leafname ; 
 int /*<<< orphan*/  test_nsalloc_less_long_namespace ; 
 int /*<<< orphan*/  test_nsalloc_long_attr ; 
 int /*<<< orphan*/  test_nsalloc_long_attr_prefix ; 
 int /*<<< orphan*/  test_nsalloc_long_context ; 
 int /*<<< orphan*/  test_nsalloc_long_default_in_ext ; 
 int /*<<< orphan*/  test_nsalloc_long_element ; 
 int /*<<< orphan*/  test_nsalloc_long_namespace ; 
 int /*<<< orphan*/  test_nsalloc_long_prefix ; 
 int /*<<< orphan*/  test_nsalloc_long_systemid_in_ext ; 
 int /*<<< orphan*/  test_nsalloc_long_uri ; 
 int /*<<< orphan*/  test_nsalloc_parse_buffer ; 
 int /*<<< orphan*/  test_nsalloc_prefixed_element ; 
 int /*<<< orphan*/  test_nsalloc_realloc_attributes ; 
 int /*<<< orphan*/  test_nsalloc_realloc_binding_uri ; 
 int /*<<< orphan*/  test_nsalloc_realloc_long_context ; 
 int /*<<< orphan*/  test_nsalloc_realloc_long_context_2 ; 
 int /*<<< orphan*/  test_nsalloc_realloc_long_context_3 ; 
 int /*<<< orphan*/  test_nsalloc_realloc_long_context_4 ; 
 int /*<<< orphan*/  test_nsalloc_realloc_long_context_5 ; 
 int /*<<< orphan*/  test_nsalloc_realloc_long_context_6 ; 
 int /*<<< orphan*/  test_nsalloc_realloc_long_context_7 ; 
 int /*<<< orphan*/  test_nsalloc_realloc_long_context_in_dtd ; 
 int /*<<< orphan*/  test_nsalloc_realloc_long_ge_name ; 
 int /*<<< orphan*/  test_nsalloc_realloc_long_prefix ; 
 int /*<<< orphan*/  test_nsalloc_realloc_longer_prefix ; 
 int /*<<< orphan*/  test_nsalloc_xmlns ; 
 int /*<<< orphan*/  test_nul_byte ; 
 int /*<<< orphan*/  test_param_entity_with_trailing_cr ; 
 int /*<<< orphan*/  test_partial_char_in_epilog ; 
 int /*<<< orphan*/  test_pi_handled_in_default ; 
 int /*<<< orphan*/  test_pi_xmm ; 
 int /*<<< orphan*/  test_pi_xnl ; 
 int /*<<< orphan*/  test_pi_yml ; 
 int /*<<< orphan*/  test_predefined_entities ; 
 int /*<<< orphan*/  test_predefined_entity_redefinition ; 
 int /*<<< orphan*/  test_public_notation_no_sysid ; 
 int /*<<< orphan*/  test_really_long_encoded_lines ; 
 int /*<<< orphan*/  test_really_long_lines ; 
 int /*<<< orphan*/  test_recursive_external_parameter_entity ; 
 int /*<<< orphan*/  test_reject_lt_in_attribute_value ; 
 int /*<<< orphan*/  test_reject_unfinished_param_in_att_value ; 
 int /*<<< orphan*/  test_repeated_stop_parser_between_char_data_calls ; 
 int /*<<< orphan*/  test_reset_in_entity ; 
 int /*<<< orphan*/  test_restart_on_error ; 
 int /*<<< orphan*/  test_resume_entity_with_syntax_error ; 
 int /*<<< orphan*/  test_resume_invalid_parse ; 
 int /*<<< orphan*/  test_resume_resuspended ; 
 int /*<<< orphan*/  test_return_ns_triplet ; 
 int /*<<< orphan*/  test_set_base ; 
 int /*<<< orphan*/  test_set_foreign_dtd ; 
 int /*<<< orphan*/  test_short_doctype ; 
 int /*<<< orphan*/  test_short_doctype_2 ; 
 int /*<<< orphan*/  test_short_doctype_3 ; 
 int /*<<< orphan*/  test_siphash_self ; 
 int /*<<< orphan*/  test_siphash_spec ; 
 int /*<<< orphan*/  test_skipped_external_entity ; 
 int /*<<< orphan*/  test_skipped_null_loaded_ext_entity ; 
 int /*<<< orphan*/  test_skipped_parameter_entity ; 
 int /*<<< orphan*/  test_skipped_unloaded_ext_entity ; 
 int /*<<< orphan*/  test_standalone_internal_entity ; 
 int /*<<< orphan*/  test_standalone_parameter_entity ; 
 int /*<<< orphan*/  test_start_ns_clears_start_element ; 
 int /*<<< orphan*/  test_stop_parser_between_cdata_calls ; 
 int /*<<< orphan*/  test_stop_parser_between_char_data_calls ; 
 int /*<<< orphan*/  test_subordinate_reset ; 
 int /*<<< orphan*/  test_subordinate_suspend ; 
 int /*<<< orphan*/  test_subordinate_xdecl_abort ; 
 int /*<<< orphan*/  test_subordinate_xdecl_suspend ; 
 int /*<<< orphan*/  test_suspend_epilog ; 
 int /*<<< orphan*/  test_suspend_in_sole_empty_tag ; 
 int /*<<< orphan*/  test_suspend_parser_between_cdata_calls ; 
 int /*<<< orphan*/  test_suspend_parser_between_char_data_calls ; 
 int /*<<< orphan*/  test_suspend_resume_internal_entity ; 
 int /*<<< orphan*/  test_suspend_resume_parameter_entity ; 
 int /*<<< orphan*/  test_suspend_xdecl ; 
 int /*<<< orphan*/  test_trailing_cr ; 
 int /*<<< orphan*/  test_trailing_cr_in_att_value ; 
 int /*<<< orphan*/  test_trailing_rsqb ; 
 int /*<<< orphan*/  test_trailing_spaces_in_elements ; 
 int /*<<< orphan*/  test_u0000_char ; 
 int /*<<< orphan*/  test_undefined_ext_entity_in_external_dtd ; 
 int /*<<< orphan*/  test_unfinished_epilog ; 
 int /*<<< orphan*/  test_unknown_ascii_encoding_fail ; 
 int /*<<< orphan*/  test_unknown_ascii_encoding_ok ; 
 int /*<<< orphan*/  test_unknown_encoding_bad_ignore ; 
 int /*<<< orphan*/  test_unknown_encoding_bad_name ; 
 int /*<<< orphan*/  test_unknown_encoding_bad_name_2 ; 
 int /*<<< orphan*/  test_unknown_encoding_internal_entity ; 
 int /*<<< orphan*/  test_unknown_encoding_invalid_attr_value ; 
 int /*<<< orphan*/  test_unknown_encoding_invalid_high ; 
 int /*<<< orphan*/  test_unknown_encoding_invalid_length ; 
 int /*<<< orphan*/  test_unknown_encoding_invalid_surrogate ; 
 int /*<<< orphan*/  test_unknown_encoding_invalid_topbit ; 
 int /*<<< orphan*/  test_unknown_encoding_long_name_1 ; 
 int /*<<< orphan*/  test_unknown_encoding_long_name_2 ; 
 int /*<<< orphan*/  test_unknown_encoding_success ; 
 int /*<<< orphan*/  test_unrecognised_encoding_internal_entity ; 
 int /*<<< orphan*/  test_user_parameters ; 
 int /*<<< orphan*/  test_utf16 ; 
 int /*<<< orphan*/  test_utf16_attribute ; 
 int /*<<< orphan*/  test_utf16_bad_surrogate_pair ; 
 int /*<<< orphan*/  test_utf16_be_comment ; 
 int /*<<< orphan*/  test_utf16_be_pi ; 
 int /*<<< orphan*/  test_utf16_le_comment ; 
 int /*<<< orphan*/  test_utf16_le_epilog_newline ; 
 int /*<<< orphan*/  test_utf16_pe ; 
 int /*<<< orphan*/  test_utf16_pi ; 
 int /*<<< orphan*/  test_utf16_second_attr ; 
 int /*<<< orphan*/  test_utf8_auto_align ; 
 int /*<<< orphan*/  test_utf8_false_rejection ; 
 int /*<<< orphan*/  test_utf8_in_cdata_section ; 
 int /*<<< orphan*/  test_utf8_in_cdata_section_2 ; 
 int /*<<< orphan*/  test_wfc_no_recursive_entity_refs ; 
 int /*<<< orphan*/  test_wfc_undeclared_entity_no_external_subset ; 
 int /*<<< orphan*/  test_wfc_undeclared_entity_standalone ; 
 int /*<<< orphan*/  test_wfc_undeclared_entity_unread_external_subset ; 
 int /*<<< orphan*/  test_wfc_undeclared_entity_with_external_subset ; 
 int /*<<< orphan*/  test_wfc_undeclared_entity_with_external_subset_standalone ; 
 int /*<<< orphan*/  test_xmldecl_invalid ; 
 int /*<<< orphan*/  test_xmldecl_misplaced ; 
 int /*<<< orphan*/  test_xmldecl_missing_attr ; 
 int /*<<< orphan*/  test_xmldecl_missing_value ; 

__attribute__((used)) static Suite *
make_suite(void)
{
    Suite *s = suite_create("basic");
    TCase *tc_basic = tcase_create("basic tests");
    TCase *tc_namespace = tcase_create("XML namespaces");
    TCase *tc_misc = tcase_create("miscellaneous tests");
    TCase *tc_alloc = tcase_create("allocation tests");
    TCase *tc_nsalloc = tcase_create("namespace allocation tests");

    suite_add_tcase(s, tc_basic);
    tcase_add_checked_fixture(tc_basic, basic_setup, basic_teardown);
    tcase_add_test(tc_basic, test_nul_byte);
    tcase_add_test(tc_basic, test_u0000_char);
    tcase_add_test(tc_basic, test_siphash_self);
    tcase_add_test(tc_basic, test_siphash_spec);
    tcase_add_test(tc_basic, test_bom_utf8);
    tcase_add_test(tc_basic, test_bom_utf16_be);
    tcase_add_test(tc_basic, test_bom_utf16_le);
    tcase_add_test(tc_basic, test_nobom_utf16_le);
    tcase_add_test(tc_basic, test_illegal_utf8);
    tcase_add_test(tc_basic, test_utf8_auto_align);
    tcase_add_test(tc_basic, test_utf16);
    tcase_add_test(tc_basic, test_utf16_le_epilog_newline);
    tcase_add_test(tc_basic, test_not_utf16);
    tcase_add_test(tc_basic, test_bad_encoding);
    tcase_add_test(tc_basic, test_latin1_umlauts);
    tcase_add_test(tc_basic, test_long_utf8_character);
    tcase_add_test(tc_basic, test_long_latin1_attribute);
    tcase_add_test(tc_basic, test_long_ascii_attribute);
    /* Regression test for SF bug #491986. */
    tcase_add_test(tc_basic, test_danish_latin1);
    /* Regression test for SF bug #514281. */
    tcase_add_test(tc_basic, test_french_charref_hexidecimal);
    tcase_add_test(tc_basic, test_french_charref_decimal);
    tcase_add_test(tc_basic, test_french_latin1);
    tcase_add_test(tc_basic, test_french_utf8);
    tcase_add_test(tc_basic, test_utf8_false_rejection);
    tcase_add_test(tc_basic, test_line_number_after_parse);
    tcase_add_test(tc_basic, test_column_number_after_parse);
    tcase_add_test(tc_basic, test_line_and_column_numbers_inside_handlers);
    tcase_add_test(tc_basic, test_line_number_after_error);
    tcase_add_test(tc_basic, test_column_number_after_error);
    tcase_add_test(tc_basic, test_really_long_lines);
    tcase_add_test(tc_basic, test_really_long_encoded_lines);
    tcase_add_test(tc_basic, test_end_element_events);
    tcase_add_test(tc_basic, test_attr_whitespace_normalization);
    tcase_add_test(tc_basic, test_xmldecl_misplaced);
    tcase_add_test(tc_basic, test_xmldecl_invalid);
    tcase_add_test(tc_basic, test_xmldecl_missing_attr);
    tcase_add_test(tc_basic, test_xmldecl_missing_value);
    tcase_add_test(tc_basic, test_unknown_encoding_internal_entity);
    tcase_add_test(tc_basic, test_unrecognised_encoding_internal_entity);
    tcase_add_test(tc_basic,
                   test_wfc_undeclared_entity_unread_external_subset);
    tcase_add_test(tc_basic, test_wfc_undeclared_entity_no_external_subset);
    tcase_add_test(tc_basic, test_wfc_undeclared_entity_standalone);
    tcase_add_test(tc_basic, test_wfc_undeclared_entity_with_external_subset);
    tcase_add_test(tc_basic, test_not_standalone_handler_reject);
    tcase_add_test(tc_basic, test_not_standalone_handler_accept);
    tcase_add_test(tc_basic,
                   test_wfc_undeclared_entity_with_external_subset_standalone);
    tcase_add_test(tc_basic,
                   test_entity_with_external_subset_unless_standalone);
    tcase_add_test(tc_basic, test_wfc_no_recursive_entity_refs);
    tcase_add_test(tc_basic, test_ext_entity_set_encoding);
    tcase_add_test(tc_basic, test_ext_entity_no_handler);
    tcase_add_test(tc_basic, test_ext_entity_set_bom);
    tcase_add_test(tc_basic, test_ext_entity_bad_encoding);
    tcase_add_test(tc_basic, test_ext_entity_bad_encoding_2);
    tcase_add_test(tc_basic, test_ext_entity_invalid_parse);
    tcase_add_test(tc_basic, test_ext_entity_invalid_suspended_parse);
    tcase_add_test(tc_basic, test_dtd_default_handling);
    tcase_add_test(tc_basic, test_dtd_attr_handling);
    tcase_add_test(tc_basic, test_empty_ns_without_namespaces);
    tcase_add_test(tc_basic, test_ns_in_attribute_default_without_namespaces);
    tcase_add_test(tc_basic, test_stop_parser_between_char_data_calls);
    tcase_add_test(tc_basic, test_suspend_parser_between_char_data_calls);
    tcase_add_test(tc_basic, test_repeated_stop_parser_between_char_data_calls);
    tcase_add_test(tc_basic, test_good_cdata_ascii);
    tcase_add_test(tc_basic, test_good_cdata_utf16);
    tcase_add_test(tc_basic, test_good_cdata_utf16_le);
    tcase_add_test(tc_basic, test_long_cdata_utf16);
    tcase_add_test(tc_basic, test_multichar_cdata_utf16);
    tcase_add_test(tc_basic, test_utf16_bad_surrogate_pair);
    tcase_add_test(tc_basic, test_bad_cdata);
    tcase_add_test(tc_basic, test_bad_cdata_utf16);
    tcase_add_test(tc_basic, test_stop_parser_between_cdata_calls);
    tcase_add_test(tc_basic, test_suspend_parser_between_cdata_calls);
    tcase_add_test(tc_basic, test_memory_allocation);
    tcase_add_test(tc_basic, test_default_current);
    tcase_add_test(tc_basic, test_dtd_elements);
    tcase_add_test(tc_basic, test_set_foreign_dtd);
    tcase_add_test(tc_basic, test_foreign_dtd_not_standalone);
    tcase_add_test(tc_basic, test_invalid_foreign_dtd);
    tcase_add_test(tc_basic, test_foreign_dtd_with_doctype);
    tcase_add_test(tc_basic, test_foreign_dtd_without_external_subset);
    tcase_add_test(tc_basic, test_empty_foreign_dtd);
    tcase_add_test(tc_basic, test_set_base);
    tcase_add_test(tc_basic, test_attributes);
    tcase_add_test(tc_basic, test_reset_in_entity);
    tcase_add_test(tc_basic, test_resume_invalid_parse);
    tcase_add_test(tc_basic, test_resume_resuspended);
    tcase_add_test(tc_basic, test_cdata_default);
    tcase_add_test(tc_basic, test_subordinate_reset);
    tcase_add_test(tc_basic, test_subordinate_suspend);
    tcase_add_test(tc_basic, test_subordinate_xdecl_suspend);
    tcase_add_test(tc_basic, test_subordinate_xdecl_abort);
    tcase_add_test(tc_basic, test_explicit_encoding);
    tcase_add_test(tc_basic, test_trailing_cr);
    tcase_add_test(tc_basic, test_ext_entity_trailing_cr);
    tcase_add_test(tc_basic, test_trailing_rsqb);
    tcase_add_test(tc_basic, test_ext_entity_trailing_rsqb);
    tcase_add_test(tc_basic, test_ext_entity_good_cdata);
    tcase_add_test(tc_basic, test_user_parameters);
    tcase_add_test(tc_basic, test_ext_entity_ref_parameter);
    tcase_add_test(tc_basic, test_empty_parse);
    tcase_add_test(tc_basic, test_get_buffer_1);
    tcase_add_test(tc_basic, test_get_buffer_2);
    tcase_add_test(tc_basic, test_byte_info_at_end);
    tcase_add_test(tc_basic, test_byte_info_at_error);
    tcase_add_test(tc_basic, test_byte_info_at_cdata);
    tcase_add_test(tc_basic, test_predefined_entities);
    tcase_add_test(tc_basic, test_invalid_tag_in_dtd);
    tcase_add_test(tc_basic, test_not_predefined_entities);
    tcase_add_test(tc_basic, test_ignore_section);
    tcase_add_test(tc_basic, test_ignore_section_utf16);
    tcase_add_test(tc_basic, test_ignore_section_utf16_be);
    tcase_add_test(tc_basic, test_bad_ignore_section);
    tcase_add_test(tc_basic, test_external_entity_values);
    tcase_add_test(tc_basic, test_ext_entity_not_standalone);
    tcase_add_test(tc_basic, test_ext_entity_value_abort);
    tcase_add_test(tc_basic, test_bad_public_doctype);
    tcase_add_test(tc_basic, test_attribute_enum_value);
    tcase_add_test(tc_basic, test_predefined_entity_redefinition);
    tcase_add_test(tc_basic, test_dtd_stop_processing);
    tcase_add_test(tc_basic, test_public_notation_no_sysid);
    tcase_add_test(tc_basic, test_nested_groups);
    tcase_add_test(tc_basic, test_group_choice);
    tcase_add_test(tc_basic, test_standalone_parameter_entity);
    tcase_add_test(tc_basic, test_skipped_parameter_entity);
    tcase_add_test(tc_basic, test_recursive_external_parameter_entity);
    tcase_add_test(tc_basic, test_undefined_ext_entity_in_external_dtd);
    tcase_add_test(tc_basic, test_suspend_xdecl);
    tcase_add_test(tc_basic, test_abort_epilog);
    tcase_add_test(tc_basic, test_abort_epilog_2);
    tcase_add_test(tc_basic, test_suspend_epilog);
    tcase_add_test(tc_basic, test_suspend_in_sole_empty_tag);
    tcase_add_test(tc_basic, test_unfinished_epilog);
    tcase_add_test(tc_basic, test_partial_char_in_epilog);
    tcase_add_test(tc_basic, test_hash_collision);
    tcase_add_test(tc_basic, test_suspend_resume_internal_entity);
    tcase_add_test(tc_basic, test_resume_entity_with_syntax_error);
    tcase_add_test(tc_basic, test_suspend_resume_parameter_entity);
    tcase_add_test(tc_basic, test_restart_on_error);
    tcase_add_test(tc_basic, test_reject_lt_in_attribute_value);
    tcase_add_test(tc_basic, test_reject_unfinished_param_in_att_value);
    tcase_add_test(tc_basic, test_trailing_cr_in_att_value);
    tcase_add_test(tc_basic, test_standalone_internal_entity);
    tcase_add_test(tc_basic, test_skipped_external_entity);
    tcase_add_test(tc_basic, test_skipped_null_loaded_ext_entity);
    tcase_add_test(tc_basic, test_skipped_unloaded_ext_entity);
    tcase_add_test(tc_basic, test_param_entity_with_trailing_cr);
    tcase_add_test(tc_basic, test_invalid_character_entity);
    tcase_add_test(tc_basic, test_invalid_character_entity_2);
    tcase_add_test(tc_basic, test_invalid_character_entity_3);
    tcase_add_test(tc_basic, test_invalid_character_entity_4);
    tcase_add_test(tc_basic, test_pi_handled_in_default);
    tcase_add_test(tc_basic, test_comment_handled_in_default);
    tcase_add_test(tc_basic, test_pi_yml);
    tcase_add_test(tc_basic, test_pi_xnl);
    tcase_add_test(tc_basic, test_pi_xmm);
    tcase_add_test(tc_basic, test_utf16_pi);
    tcase_add_test(tc_basic, test_utf16_be_pi);
    tcase_add_test(tc_basic, test_utf16_be_comment);
    tcase_add_test(tc_basic, test_utf16_le_comment);
    tcase_add_test(tc_basic, test_missing_encoding_conversion_fn);
    tcase_add_test(tc_basic, test_failing_encoding_conversion_fn);
    tcase_add_test(tc_basic, test_unknown_encoding_success);
    tcase_add_test(tc_basic, test_unknown_encoding_bad_name);
    tcase_add_test(tc_basic, test_unknown_encoding_bad_name_2);
    tcase_add_test(tc_basic, test_unknown_encoding_long_name_1);
    tcase_add_test(tc_basic, test_unknown_encoding_long_name_2);
    tcase_add_test(tc_basic, test_invalid_unknown_encoding);
    tcase_add_test(tc_basic, test_unknown_ascii_encoding_ok);
    tcase_add_test(tc_basic, test_unknown_ascii_encoding_fail);
    tcase_add_test(tc_basic, test_unknown_encoding_invalid_length);
    tcase_add_test(tc_basic, test_unknown_encoding_invalid_topbit);
    tcase_add_test(tc_basic, test_unknown_encoding_invalid_surrogate);
    tcase_add_test(tc_basic, test_unknown_encoding_invalid_high);
    tcase_add_test(tc_basic, test_unknown_encoding_invalid_attr_value);
    tcase_add_test(tc_basic, test_ext_entity_latin1_utf16le_bom);
    tcase_add_test(tc_basic, test_ext_entity_latin1_utf16be_bom);
    tcase_add_test(tc_basic, test_ext_entity_latin1_utf16le_bom2);
    tcase_add_test(tc_basic, test_ext_entity_latin1_utf16be_bom2);
    tcase_add_test(tc_basic, test_ext_entity_utf16_be);
    tcase_add_test(tc_basic, test_ext_entity_utf16_le);
    tcase_add_test(tc_basic, test_ext_entity_utf16_unknown);
    tcase_add_test(tc_basic, test_ext_entity_utf8_non_bom);
    tcase_add_test(tc_basic, test_utf8_in_cdata_section);
    tcase_add_test(tc_basic, test_utf8_in_cdata_section_2);
    tcase_add_test(tc_basic, test_trailing_spaces_in_elements);
    tcase_add_test(tc_basic, test_utf16_attribute);
    tcase_add_test(tc_basic, test_utf16_second_attr);
    tcase_add_test(tc_basic, test_attr_after_solidus);
    tcase_add_test(tc_basic, test_utf16_pe);
    tcase_add_test(tc_basic, test_bad_attr_desc_keyword);
    tcase_add_test(tc_basic, test_bad_attr_desc_keyword_utf16);
    tcase_add_test(tc_basic, test_bad_doctype);
    tcase_add_test(tc_basic, test_bad_doctype_utf16);
    tcase_add_test(tc_basic, test_bad_doctype_plus);
    tcase_add_test(tc_basic, test_bad_doctype_star);
    tcase_add_test(tc_basic, test_bad_doctype_query);
    tcase_add_test(tc_basic, test_unknown_encoding_bad_ignore);
    tcase_add_test(tc_basic, test_entity_in_utf16_be_attr);
    tcase_add_test(tc_basic, test_entity_in_utf16_le_attr);
    tcase_add_test(tc_basic, test_entity_public_utf16_be);
    tcase_add_test(tc_basic, test_entity_public_utf16_le);
    tcase_add_test(tc_basic, test_short_doctype);
    tcase_add_test(tc_basic, test_short_doctype_2);
    tcase_add_test(tc_basic, test_short_doctype_3);
    tcase_add_test(tc_basic, test_long_doctype);
    tcase_add_test(tc_basic, test_bad_entity);
    tcase_add_test(tc_basic, test_bad_entity_2);
    tcase_add_test(tc_basic, test_bad_entity_3);
    tcase_add_test(tc_basic, test_bad_entity_4);
    tcase_add_test(tc_basic, test_bad_notation);
    tcase_add_test(tc_basic, test_default_doctype_handler);
    tcase_add_test(tc_basic, test_empty_element_abort);

    suite_add_tcase(s, tc_namespace);
    tcase_add_checked_fixture(tc_namespace,
                              namespace_setup, namespace_teardown);
    tcase_add_test(tc_namespace, test_return_ns_triplet);
    tcase_add_test(tc_namespace, test_ns_tagname_overwrite);
    tcase_add_test(tc_namespace, test_ns_tagname_overwrite_triplet);
    tcase_add_test(tc_namespace, test_start_ns_clears_start_element);
    tcase_add_test(tc_namespace, test_default_ns_from_ext_subset_and_ext_ge);
    tcase_add_test(tc_namespace, test_ns_prefix_with_empty_uri_1);
    tcase_add_test(tc_namespace, test_ns_prefix_with_empty_uri_2);
    tcase_add_test(tc_namespace, test_ns_prefix_with_empty_uri_3);
    tcase_add_test(tc_namespace, test_ns_prefix_with_empty_uri_4);
    tcase_add_test(tc_namespace, test_ns_unbound_prefix);
    tcase_add_test(tc_namespace, test_ns_default_with_empty_uri);
    tcase_add_test(tc_namespace, test_ns_duplicate_attrs_diff_prefixes);
    tcase_add_test(tc_namespace, test_ns_duplicate_hashes);
    tcase_add_test(tc_namespace, test_ns_unbound_prefix_on_attribute);
    tcase_add_test(tc_namespace, test_ns_unbound_prefix_on_element);
    tcase_add_test(tc_namespace, test_ns_parser_reset);
    tcase_add_test(tc_namespace, test_ns_long_element);
    tcase_add_test(tc_namespace, test_ns_mixed_prefix_atts);
    tcase_add_test(tc_namespace, test_ns_extend_uri_buffer);
    tcase_add_test(tc_namespace, test_ns_reserved_attributes);
    tcase_add_test(tc_namespace, test_ns_reserved_attributes_2);
    tcase_add_test(tc_namespace, test_ns_extremely_long_prefix);
    tcase_add_test(tc_namespace, test_ns_unknown_encoding_success);
    tcase_add_test(tc_namespace, test_ns_double_colon);
    tcase_add_test(tc_namespace, test_ns_double_colon_element);
    tcase_add_test(tc_namespace, test_ns_bad_attr_leafname);
    tcase_add_test(tc_namespace, test_ns_bad_element_leafname);
    tcase_add_test(tc_namespace, test_ns_utf16_leafname);
    tcase_add_test(tc_namespace, test_ns_utf16_element_leafname);
    tcase_add_test(tc_namespace, test_ns_utf16_doctype);
    tcase_add_test(tc_namespace, test_ns_invalid_doctype);
    tcase_add_test(tc_namespace, test_ns_double_colon_doctype);

    suite_add_tcase(s, tc_misc);
    tcase_add_checked_fixture(tc_misc, NULL, basic_teardown);
    tcase_add_test(tc_misc, test_misc_alloc_create_parser);
    tcase_add_test(tc_misc, test_misc_alloc_create_parser_with_encoding);
    tcase_add_test(tc_misc, test_misc_null_parser);
    tcase_add_test(tc_misc, test_misc_error_string);
    tcase_add_test(tc_misc, test_misc_version);
    tcase_add_test(tc_misc, test_misc_features);
    tcase_add_test(tc_misc, test_misc_attribute_leak);
    tcase_add_test(tc_misc, test_misc_utf16le);

    suite_add_tcase(s, tc_alloc);
    tcase_add_checked_fixture(tc_alloc, alloc_setup, alloc_teardown);
    tcase_add_test(tc_alloc, test_alloc_parse_xdecl);
    tcase_add_test(tc_alloc, test_alloc_parse_xdecl_2);
    tcase_add_test(tc_alloc, test_alloc_parse_pi);
    tcase_add_test(tc_alloc, test_alloc_parse_pi_2);
    tcase_add_test(tc_alloc, test_alloc_parse_pi_3);
    tcase_add_test(tc_alloc, test_alloc_parse_comment);
    tcase_add_test(tc_alloc, test_alloc_parse_comment_2);
    tcase_add_test(tc_alloc, test_alloc_create_external_parser);
    tcase_add_test(tc_alloc, test_alloc_run_external_parser);
    tcase_add_test(tc_alloc, test_alloc_dtd_copy_default_atts);
    tcase_add_test(tc_alloc, test_alloc_external_entity);
    tcase_add_test(tc_alloc, test_alloc_ext_entity_set_encoding);
    tcase_add_test(tc_alloc, test_alloc_internal_entity);
    tcase_add_test(tc_alloc, test_alloc_dtd_default_handling);
    tcase_add_test(tc_alloc, test_alloc_explicit_encoding);
    tcase_add_test(tc_alloc, test_alloc_set_base);
    tcase_add_test(tc_alloc, test_alloc_realloc_buffer);
    tcase_add_test(tc_alloc, test_alloc_ext_entity_realloc_buffer);
    tcase_add_test(tc_alloc, test_alloc_realloc_many_attributes);
    tcase_add_test(tc_alloc, test_alloc_public_entity_value);
    tcase_add_test(tc_alloc, test_alloc_realloc_subst_public_entity_value);
    tcase_add_test(tc_alloc, test_alloc_parse_public_doctype);
    tcase_add_test(tc_alloc, test_alloc_parse_public_doctype_long_name);
    tcase_add_test(tc_alloc, test_alloc_set_foreign_dtd);
    tcase_add_test(tc_alloc, test_alloc_attribute_enum_value);
    tcase_add_test(tc_alloc, test_alloc_realloc_attribute_enum_value);
    tcase_add_test(tc_alloc, test_alloc_realloc_implied_attribute);
    tcase_add_test(tc_alloc, test_alloc_realloc_default_attribute);
    tcase_add_test(tc_alloc, test_alloc_notation);
    tcase_add_test(tc_alloc, test_alloc_public_notation);
    tcase_add_test(tc_alloc, test_alloc_system_notation);
    tcase_add_test(tc_alloc, test_alloc_nested_groups);
    tcase_add_test(tc_alloc, test_alloc_realloc_nested_groups);
    tcase_add_test(tc_alloc, test_alloc_large_group);
    tcase_add_test(tc_alloc, test_alloc_realloc_group_choice);
    tcase_add_test(tc_alloc, test_alloc_pi_in_epilog);
    tcase_add_test(tc_alloc, test_alloc_comment_in_epilog);
    tcase_add_test(tc_alloc, test_alloc_realloc_long_attribute_value);
    tcase_add_test(tc_alloc, test_alloc_attribute_whitespace);
    tcase_add_test(tc_alloc, test_alloc_attribute_predefined_entity);
    tcase_add_test(tc_alloc, test_alloc_long_attr_default_with_char_ref);
    tcase_add_test(tc_alloc, test_alloc_long_attr_value);
    tcase_add_test(tc_alloc, test_alloc_nested_entities);
    tcase_add_test(tc_alloc, test_alloc_realloc_param_entity_newline);
    tcase_add_test(tc_alloc, test_alloc_realloc_ce_extends_pe);
    tcase_add_test(tc_alloc, test_alloc_realloc_attributes);
    tcase_add_test(tc_alloc, test_alloc_long_doc_name);
    tcase_add_test(tc_alloc, test_alloc_long_base);
    tcase_add_test(tc_alloc, test_alloc_long_public_id);
    tcase_add_test(tc_alloc, test_alloc_long_entity_value);
    tcase_add_test(tc_alloc, test_alloc_long_notation);

    suite_add_tcase(s, tc_nsalloc);
    tcase_add_checked_fixture(tc_nsalloc, nsalloc_setup, nsalloc_teardown);
    tcase_add_test(tc_nsalloc, test_nsalloc_xmlns);
    tcase_add_test(tc_nsalloc, test_nsalloc_parse_buffer);
    tcase_add_test(tc_nsalloc, test_nsalloc_long_prefix);
    tcase_add_test(tc_nsalloc, test_nsalloc_long_uri);
    tcase_add_test(tc_nsalloc, test_nsalloc_long_attr);
    tcase_add_test(tc_nsalloc, test_nsalloc_long_attr_prefix);
    tcase_add_test(tc_nsalloc, test_nsalloc_realloc_attributes);
    tcase_add_test(tc_nsalloc, test_nsalloc_long_element);
    tcase_add_test(tc_nsalloc, test_nsalloc_realloc_binding_uri);
    tcase_add_test(tc_nsalloc, test_nsalloc_realloc_long_prefix);
    tcase_add_test(tc_nsalloc, test_nsalloc_realloc_longer_prefix);
    tcase_add_test(tc_nsalloc, test_nsalloc_long_namespace);
    tcase_add_test(tc_nsalloc, test_nsalloc_less_long_namespace);
    tcase_add_test(tc_nsalloc, test_nsalloc_long_context);
    tcase_add_test(tc_nsalloc, test_nsalloc_realloc_long_context);
    tcase_add_test(tc_nsalloc, test_nsalloc_realloc_long_context_2);
    tcase_add_test(tc_nsalloc, test_nsalloc_realloc_long_context_3);
    tcase_add_test(tc_nsalloc, test_nsalloc_realloc_long_context_4);
    tcase_add_test(tc_nsalloc, test_nsalloc_realloc_long_context_5);
    tcase_add_test(tc_nsalloc, test_nsalloc_realloc_long_context_6);
    tcase_add_test(tc_nsalloc, test_nsalloc_realloc_long_context_7);
    tcase_add_test(tc_nsalloc, test_nsalloc_realloc_long_ge_name);
    tcase_add_test(tc_nsalloc, test_nsalloc_realloc_long_context_in_dtd);
    tcase_add_test(tc_nsalloc, test_nsalloc_long_default_in_ext);
    tcase_add_test(tc_nsalloc, test_nsalloc_long_systemid_in_ext);
    tcase_add_test(tc_nsalloc, test_nsalloc_prefixed_element);

    return s;
}