#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
struct drm_i915_private {int dummy; } ;
typedef  enum intel_display_power_domain { ____Placeholder_intel_display_power_domain } intel_display_power_domain ;

/* Variables and functions */
 int /*<<< orphan*/  BUILD_BUG_ON (int) ; 
 int IS_GEN (struct drm_i915_private*,int) ; 
 int /*<<< orphan*/  MISSING_CASE (int) ; 
#define  POWER_DOMAIN_AUDIO 188 
#define  POWER_DOMAIN_AUX_A 187 
#define  POWER_DOMAIN_AUX_B 186 
#define  POWER_DOMAIN_AUX_C 185 
#define  POWER_DOMAIN_AUX_D 184 
#define  POWER_DOMAIN_AUX_E 183 
#define  POWER_DOMAIN_AUX_F 182 
#define  POWER_DOMAIN_AUX_IO_A 181 
#define  POWER_DOMAIN_AUX_TBT1 180 
#define  POWER_DOMAIN_AUX_TBT2 179 
#define  POWER_DOMAIN_AUX_TBT3 178 
#define  POWER_DOMAIN_AUX_TBT4 177 
#define  POWER_DOMAIN_AUX_TBT5 176 
#define  POWER_DOMAIN_AUX_TBT6 175 
 int const POWER_DOMAIN_AUX_TC1 ; 
 int const POWER_DOMAIN_AUX_TC2 ; 
 int const POWER_DOMAIN_AUX_TC3 ; 
#define  POWER_DOMAIN_AUX_TC4 174 
#define  POWER_DOMAIN_AUX_TC5 173 
#define  POWER_DOMAIN_AUX_TC6 172 
#define  POWER_DOMAIN_DISPLAY_CORE 171 
#define  POWER_DOMAIN_DPLL_DC_OFF 170 
#define  POWER_DOMAIN_GMBUS 169 
#define  POWER_DOMAIN_GT_IRQ 168 
#define  POWER_DOMAIN_INIT 167 
#define  POWER_DOMAIN_MODESET 166 
#define  POWER_DOMAIN_PIPE_A 165 
#define  POWER_DOMAIN_PIPE_A_PANEL_FITTER 164 
#define  POWER_DOMAIN_PIPE_B 163 
#define  POWER_DOMAIN_PIPE_B_PANEL_FITTER 162 
#define  POWER_DOMAIN_PIPE_C 161 
#define  POWER_DOMAIN_PIPE_C_PANEL_FITTER 160 
#define  POWER_DOMAIN_PIPE_D 159 
#define  POWER_DOMAIN_PIPE_D_PANEL_FITTER 158 
#define  POWER_DOMAIN_PORT_CRT 157 
#define  POWER_DOMAIN_PORT_DDI_A_IO 156 
#define  POWER_DOMAIN_PORT_DDI_A_LANES 155 
#define  POWER_DOMAIN_PORT_DDI_B_IO 154 
#define  POWER_DOMAIN_PORT_DDI_B_LANES 153 
#define  POWER_DOMAIN_PORT_DDI_C_IO 152 
#define  POWER_DOMAIN_PORT_DDI_C_LANES 151 
#define  POWER_DOMAIN_PORT_DDI_D_IO 150 
#define  POWER_DOMAIN_PORT_DDI_D_LANES 149 
#define  POWER_DOMAIN_PORT_DDI_E_IO 148 
#define  POWER_DOMAIN_PORT_DDI_E_LANES 147 
#define  POWER_DOMAIN_PORT_DDI_F_IO 146 
#define  POWER_DOMAIN_PORT_DDI_F_LANES 145 
 int const POWER_DOMAIN_PORT_DDI_TC1_IO ; 
 int const POWER_DOMAIN_PORT_DDI_TC1_LANES ; 
 int const POWER_DOMAIN_PORT_DDI_TC2_IO ; 
 int const POWER_DOMAIN_PORT_DDI_TC2_LANES ; 
 int const POWER_DOMAIN_PORT_DDI_TC3_IO ; 
 int const POWER_DOMAIN_PORT_DDI_TC3_LANES ; 
#define  POWER_DOMAIN_PORT_DDI_TC4_IO 144 
#define  POWER_DOMAIN_PORT_DDI_TC4_LANES 143 
#define  POWER_DOMAIN_PORT_DDI_TC5_IO 142 
#define  POWER_DOMAIN_PORT_DDI_TC5_LANES 141 
#define  POWER_DOMAIN_PORT_DDI_TC6_IO 140 
#define  POWER_DOMAIN_PORT_DDI_TC6_LANES 139 
#define  POWER_DOMAIN_PORT_DSI 138 
#define  POWER_DOMAIN_PORT_OTHER 137 
#define  POWER_DOMAIN_TRANSCODER_A 136 
#define  POWER_DOMAIN_TRANSCODER_B 135 
#define  POWER_DOMAIN_TRANSCODER_C 134 
#define  POWER_DOMAIN_TRANSCODER_D 133 
#define  POWER_DOMAIN_TRANSCODER_DSI_A 132 
#define  POWER_DOMAIN_TRANSCODER_DSI_C 131 
#define  POWER_DOMAIN_TRANSCODER_EDP 130 
#define  POWER_DOMAIN_TRANSCODER_VDSC_PW2 129 
#define  POWER_DOMAIN_VGA 128 

const char *
intel_display_power_domain_str(struct drm_i915_private *i915,
			       enum intel_display_power_domain domain)
{
	bool ddi_tc_ports = IS_GEN(i915, 12);

	switch (domain) {
	case POWER_DOMAIN_DISPLAY_CORE:
		return "DISPLAY_CORE";
	case POWER_DOMAIN_PIPE_A:
		return "PIPE_A";
	case POWER_DOMAIN_PIPE_B:
		return "PIPE_B";
	case POWER_DOMAIN_PIPE_C:
		return "PIPE_C";
	case POWER_DOMAIN_PIPE_D:
		return "PIPE_D";
	case POWER_DOMAIN_PIPE_A_PANEL_FITTER:
		return "PIPE_A_PANEL_FITTER";
	case POWER_DOMAIN_PIPE_B_PANEL_FITTER:
		return "PIPE_B_PANEL_FITTER";
	case POWER_DOMAIN_PIPE_C_PANEL_FITTER:
		return "PIPE_C_PANEL_FITTER";
	case POWER_DOMAIN_PIPE_D_PANEL_FITTER:
		return "PIPE_D_PANEL_FITTER";
	case POWER_DOMAIN_TRANSCODER_A:
		return "TRANSCODER_A";
	case POWER_DOMAIN_TRANSCODER_B:
		return "TRANSCODER_B";
	case POWER_DOMAIN_TRANSCODER_C:
		return "TRANSCODER_C";
	case POWER_DOMAIN_TRANSCODER_D:
		return "TRANSCODER_D";
	case POWER_DOMAIN_TRANSCODER_EDP:
		return "TRANSCODER_EDP";
	case POWER_DOMAIN_TRANSCODER_VDSC_PW2:
		return "TRANSCODER_VDSC_PW2";
	case POWER_DOMAIN_TRANSCODER_DSI_A:
		return "TRANSCODER_DSI_A";
	case POWER_DOMAIN_TRANSCODER_DSI_C:
		return "TRANSCODER_DSI_C";
	case POWER_DOMAIN_PORT_DDI_A_LANES:
		return "PORT_DDI_A_LANES";
	case POWER_DOMAIN_PORT_DDI_B_LANES:
		return "PORT_DDI_B_LANES";
	case POWER_DOMAIN_PORT_DDI_C_LANES:
		return "PORT_DDI_C_LANES";
	case POWER_DOMAIN_PORT_DDI_D_LANES:
		BUILD_BUG_ON(POWER_DOMAIN_PORT_DDI_D_LANES !=
			     POWER_DOMAIN_PORT_DDI_TC1_LANES);
		return ddi_tc_ports ? "PORT_DDI_TC1_LANES" : "PORT_DDI_D_LANES";
	case POWER_DOMAIN_PORT_DDI_E_LANES:
		BUILD_BUG_ON(POWER_DOMAIN_PORT_DDI_E_LANES !=
			     POWER_DOMAIN_PORT_DDI_TC2_LANES);
		return ddi_tc_ports ? "PORT_DDI_TC2_LANES" : "PORT_DDI_E_LANES";
	case POWER_DOMAIN_PORT_DDI_F_LANES:
		BUILD_BUG_ON(POWER_DOMAIN_PORT_DDI_F_LANES !=
			     POWER_DOMAIN_PORT_DDI_TC3_LANES);
		return ddi_tc_ports ? "PORT_DDI_TC3_LANES" : "PORT_DDI_F_LANES";
	case POWER_DOMAIN_PORT_DDI_TC4_LANES:
		return "PORT_DDI_TC4_LANES";
	case POWER_DOMAIN_PORT_DDI_TC5_LANES:
		return "PORT_DDI_TC5_LANES";
	case POWER_DOMAIN_PORT_DDI_TC6_LANES:
		return "PORT_DDI_TC6_LANES";
	case POWER_DOMAIN_PORT_DDI_A_IO:
		return "PORT_DDI_A_IO";
	case POWER_DOMAIN_PORT_DDI_B_IO:
		return "PORT_DDI_B_IO";
	case POWER_DOMAIN_PORT_DDI_C_IO:
		return "PORT_DDI_C_IO";
	case POWER_DOMAIN_PORT_DDI_D_IO:
		BUILD_BUG_ON(POWER_DOMAIN_PORT_DDI_D_IO !=
			     POWER_DOMAIN_PORT_DDI_TC1_IO);
		return ddi_tc_ports ? "PORT_DDI_TC1_IO" : "PORT_DDI_D_IO";
	case POWER_DOMAIN_PORT_DDI_E_IO:
		BUILD_BUG_ON(POWER_DOMAIN_PORT_DDI_E_IO !=
			     POWER_DOMAIN_PORT_DDI_TC2_IO);
		return ddi_tc_ports ? "PORT_DDI_TC2_IO" : "PORT_DDI_E_IO";
	case POWER_DOMAIN_PORT_DDI_F_IO:
		BUILD_BUG_ON(POWER_DOMAIN_PORT_DDI_F_IO !=
			     POWER_DOMAIN_PORT_DDI_TC3_IO);
		return ddi_tc_ports ? "PORT_DDI_TC3_IO" : "PORT_DDI_F_IO";
	case POWER_DOMAIN_PORT_DDI_TC4_IO:
		return "PORT_DDI_TC4_IO";
	case POWER_DOMAIN_PORT_DDI_TC5_IO:
		return "PORT_DDI_TC5_IO";
	case POWER_DOMAIN_PORT_DDI_TC6_IO:
		return "PORT_DDI_TC6_IO";
	case POWER_DOMAIN_PORT_DSI:
		return "PORT_DSI";
	case POWER_DOMAIN_PORT_CRT:
		return "PORT_CRT";
	case POWER_DOMAIN_PORT_OTHER:
		return "PORT_OTHER";
	case POWER_DOMAIN_VGA:
		return "VGA";
	case POWER_DOMAIN_AUDIO:
		return "AUDIO";
	case POWER_DOMAIN_AUX_A:
		return "AUX_A";
	case POWER_DOMAIN_AUX_B:
		return "AUX_B";
	case POWER_DOMAIN_AUX_C:
		return "AUX_C";
	case POWER_DOMAIN_AUX_D:
		BUILD_BUG_ON(POWER_DOMAIN_AUX_D != POWER_DOMAIN_AUX_TC1);
		return ddi_tc_ports ? "AUX_TC1" : "AUX_D";
	case POWER_DOMAIN_AUX_E:
		BUILD_BUG_ON(POWER_DOMAIN_AUX_E != POWER_DOMAIN_AUX_TC2);
		return ddi_tc_ports ? "AUX_TC2" : "AUX_E";
	case POWER_DOMAIN_AUX_F:
		BUILD_BUG_ON(POWER_DOMAIN_AUX_F != POWER_DOMAIN_AUX_TC3);
		return ddi_tc_ports ? "AUX_TC3" : "AUX_F";
	case POWER_DOMAIN_AUX_TC4:
		return "AUX_TC4";
	case POWER_DOMAIN_AUX_TC5:
		return "AUX_TC5";
	case POWER_DOMAIN_AUX_TC6:
		return "AUX_TC6";
	case POWER_DOMAIN_AUX_IO_A:
		return "AUX_IO_A";
	case POWER_DOMAIN_AUX_TBT1:
		return "AUX_TBT1";
	case POWER_DOMAIN_AUX_TBT2:
		return "AUX_TBT2";
	case POWER_DOMAIN_AUX_TBT3:
		return "AUX_TBT3";
	case POWER_DOMAIN_AUX_TBT4:
		return "AUX_TBT4";
	case POWER_DOMAIN_AUX_TBT5:
		return "AUX_TBT5";
	case POWER_DOMAIN_AUX_TBT6:
		return "AUX_TBT6";
	case POWER_DOMAIN_GMBUS:
		return "GMBUS";
	case POWER_DOMAIN_INIT:
		return "INIT";
	case POWER_DOMAIN_MODESET:
		return "MODESET";
	case POWER_DOMAIN_GT_IRQ:
		return "GT_IRQ";
	case POWER_DOMAIN_DPLL_DC_OFF:
		return "DPLL_DC_OFF";
	default:
		MISSING_CASE(domain);
		return "?";
	}
}