#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  int u8 ;
typedef  int u32 ;

/* Variables and functions */
 int ARRAY_SIZE (int const*) ; 
#define  RESERVED0 158 
#define  TRANS_TX_ERR_PHY_NOT_ENABLE 157 
#define  TRANS_TX_ERR_WITH_ACK_NAK_TIMEOUT 156 
#define  TRANS_TX_ERR_WITH_BREAK_RECEVIED 155 
#define  TRANS_TX_ERR_WITH_BREAK_REQUEST 154 
#define  TRANS_TX_ERR_WITH_BREAK_TIMEOUT 153 
#define  TRANS_TX_ERR_WITH_CLOSE_COMINIT 152 
#define  TRANS_TX_ERR_WITH_CLOSE_DWS_TIMEOUT 151 
#define  TRANS_TX_ERR_WITH_CLOSE_NORMAL 150 
#define  TRANS_TX_ERR_WITH_CLOSE_PHYDISALE 149 
#define  TRANS_TX_ERR_WITH_CLOSE_TIMEOUT 148 
#define  TRANS_TX_ERR_WITH_CREDIT_TIMEOUT 147 
#define  TRANS_TX_ERR_WITH_IPTT_CONFLICT 146 
#define  TRANS_TX_ERR_WITH_NAK_RECEVIED 145 
#define  TRANS_TX_ERR_WITH_OPEN_BY_DES_OR_OTHERS 144 
#define  TRANS_TX_ERR_WITH_WAIT_RECV_TIMEOUT 143 
 int const TRANS_TX_FAIL_BASE ; 
#define  TRANS_TX_OPEN_CNX_ERR_AIP_TIMEOUT 142 
#define  TRANS_TX_OPEN_CNX_ERR_BAD_DESTINATION 141 
#define  TRANS_TX_OPEN_CNX_ERR_BREAK_RCVD 140 
#define  TRANS_TX_OPEN_CNX_ERR_BY_OTHER 139 
#define  TRANS_TX_OPEN_CNX_ERR_CONNECTION_RATE_NOT_SUPPORTED 138 
#define  TRANS_TX_OPEN_CNX_ERR_LOW_PHY_POWER 137 
#define  TRANS_TX_OPEN_CNX_ERR_NO_DESTINATION 136 
#define  TRANS_TX_OPEN_CNX_ERR_OPEN_TIMEOUT 135 
#define  TRANS_TX_OPEN_CNX_ERR_PATHWAY_BLOCKED 134 
#define  TRANS_TX_OPEN_CNX_ERR_PROTOCOL_NOT_SUPPORTED 133 
#define  TRANS_TX_OPEN_CNX_ERR_STP_RESOURCES_BUSY 132 
#define  TRANS_TX_OPEN_CNX_ERR_WRONG_DESTINATION 131 
#define  TRANS_TX_OPEN_CNX_ERR_ZONE_VIOLATION 130 
#define  TRANS_TX_OPEN_FAIL_WITH_IT_NEXUS_LOSS 129 
#define  TRANS_TX_OPEN_RETRY_ERR_THRESHOLD_REACHED 128 

__attribute__((used)) static int parse_trans_tx_err_code_v2_hw(u32 err_msk)
{
	static const u8 trans_tx_err_code_prio[] = {
		TRANS_TX_OPEN_FAIL_WITH_IT_NEXUS_LOSS,
		TRANS_TX_ERR_PHY_NOT_ENABLE,
		TRANS_TX_OPEN_CNX_ERR_WRONG_DESTINATION,
		TRANS_TX_OPEN_CNX_ERR_ZONE_VIOLATION,
		TRANS_TX_OPEN_CNX_ERR_BY_OTHER,
		RESERVED0,
		TRANS_TX_OPEN_CNX_ERR_AIP_TIMEOUT,
		TRANS_TX_OPEN_CNX_ERR_STP_RESOURCES_BUSY,
		TRANS_TX_OPEN_CNX_ERR_PROTOCOL_NOT_SUPPORTED,
		TRANS_TX_OPEN_CNX_ERR_CONNECTION_RATE_NOT_SUPPORTED,
		TRANS_TX_OPEN_CNX_ERR_BAD_DESTINATION,
		TRANS_TX_OPEN_CNX_ERR_BREAK_RCVD,
		TRANS_TX_OPEN_CNX_ERR_LOW_PHY_POWER,
		TRANS_TX_OPEN_CNX_ERR_PATHWAY_BLOCKED,
		TRANS_TX_OPEN_CNX_ERR_OPEN_TIMEOUT,
		TRANS_TX_OPEN_CNX_ERR_NO_DESTINATION,
		TRANS_TX_OPEN_RETRY_ERR_THRESHOLD_REACHED,
		TRANS_TX_ERR_WITH_CLOSE_PHYDISALE,
		TRANS_TX_ERR_WITH_CLOSE_DWS_TIMEOUT,
		TRANS_TX_ERR_WITH_CLOSE_COMINIT,
		TRANS_TX_ERR_WITH_BREAK_TIMEOUT,
		TRANS_TX_ERR_WITH_BREAK_REQUEST,
		TRANS_TX_ERR_WITH_BREAK_RECEVIED,
		TRANS_TX_ERR_WITH_CLOSE_TIMEOUT,
		TRANS_TX_ERR_WITH_CLOSE_NORMAL,
		TRANS_TX_ERR_WITH_NAK_RECEVIED,
		TRANS_TX_ERR_WITH_ACK_NAK_TIMEOUT,
		TRANS_TX_ERR_WITH_CREDIT_TIMEOUT,
		TRANS_TX_ERR_WITH_IPTT_CONFLICT,
		TRANS_TX_ERR_WITH_OPEN_BY_DES_OR_OTHERS,
		TRANS_TX_ERR_WITH_WAIT_RECV_TIMEOUT,
	};
	int index, i;

	for (i = 0; i < ARRAY_SIZE(trans_tx_err_code_prio); i++) {
		index = trans_tx_err_code_prio[i] - TRANS_TX_FAIL_BASE;
		if (err_msk & (1 << index))
			return trans_tx_err_code_prio[i];
	}
	return -1;
}