#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */
typedef  struct TYPE_2__   TYPE_1__ ;

/* Type definitions */
struct TYPE_2__ {int /*<<< orphan*/ * OpenGLLib; } ;

/* Variables and functions */
 int /*<<< orphan*/  dlclose (int /*<<< orphan*/ *) ; 
 TYPE_1__ glw_state ; 
 int /*<<< orphan*/ * qfxMesaCreateBestContext ; 
 int /*<<< orphan*/ * qfxMesaCreateContext ; 
 int /*<<< orphan*/ * qfxMesaDestroyContext ; 
 int /*<<< orphan*/ * qfxMesaGetCurrentContext ; 
 int /*<<< orphan*/ * qfxMesaMakeCurrent ; 
 int /*<<< orphan*/ * qfxMesaSwapBuffers ; 
 int /*<<< orphan*/ * qglAccum ; 
 int /*<<< orphan*/ * qglAlphaFunc ; 
 int /*<<< orphan*/ * qglAreTexturesResident ; 
 int /*<<< orphan*/ * qglArrayElement ; 
 int /*<<< orphan*/ * qglBegin ; 
 int /*<<< orphan*/ * qglBindTexture ; 
 int /*<<< orphan*/ * qglBitmap ; 
 int /*<<< orphan*/ * qglBlendFunc ; 
 int /*<<< orphan*/ * qglCallList ; 
 int /*<<< orphan*/ * qglCallLists ; 
 int /*<<< orphan*/ * qglClear ; 
 int /*<<< orphan*/ * qglClearAccum ; 
 int /*<<< orphan*/ * qglClearColor ; 
 int /*<<< orphan*/ * qglClearDepth ; 
 int /*<<< orphan*/ * qglClearIndex ; 
 int /*<<< orphan*/ * qglClearStencil ; 
 int /*<<< orphan*/ * qglClipPlane ; 
 int /*<<< orphan*/ * qglColor3b ; 
 int /*<<< orphan*/ * qglColor3bv ; 
 int /*<<< orphan*/ * qglColor3d ; 
 int /*<<< orphan*/ * qglColor3dv ; 
 int /*<<< orphan*/ * qglColor3f ; 
 int /*<<< orphan*/ * qglColor3fv ; 
 int /*<<< orphan*/ * qglColor3i ; 
 int /*<<< orphan*/ * qglColor3iv ; 
 int /*<<< orphan*/ * qglColor3s ; 
 int /*<<< orphan*/ * qglColor3sv ; 
 int /*<<< orphan*/ * qglColor3ub ; 
 int /*<<< orphan*/ * qglColor3ubv ; 
 int /*<<< orphan*/ * qglColor3ui ; 
 int /*<<< orphan*/ * qglColor3uiv ; 
 int /*<<< orphan*/ * qglColor3us ; 
 int /*<<< orphan*/ * qglColor3usv ; 
 int /*<<< orphan*/ * qglColor4b ; 
 int /*<<< orphan*/ * qglColor4bv ; 
 int /*<<< orphan*/ * qglColor4d ; 
 int /*<<< orphan*/ * qglColor4dv ; 
 int /*<<< orphan*/ * qglColor4f ; 
 int /*<<< orphan*/ * qglColor4fv ; 
 int /*<<< orphan*/ * qglColor4i ; 
 int /*<<< orphan*/ * qglColor4iv ; 
 int /*<<< orphan*/ * qglColor4s ; 
 int /*<<< orphan*/ * qglColor4sv ; 
 int /*<<< orphan*/ * qglColor4ub ; 
 int /*<<< orphan*/ * qglColor4ubv ; 
 int /*<<< orphan*/ * qglColor4ui ; 
 int /*<<< orphan*/ * qglColor4uiv ; 
 int /*<<< orphan*/ * qglColor4us ; 
 int /*<<< orphan*/ * qglColor4usv ; 
 int /*<<< orphan*/ * qglColorMask ; 
 int /*<<< orphan*/ * qglColorMaterial ; 
 int /*<<< orphan*/ * qglColorPointer ; 
 int /*<<< orphan*/ * qglCopyPixels ; 
 int /*<<< orphan*/ * qglCopyTexImage1D ; 
 int /*<<< orphan*/ * qglCopyTexImage2D ; 
 int /*<<< orphan*/ * qglCopyTexSubImage1D ; 
 int /*<<< orphan*/ * qglCopyTexSubImage2D ; 
 int /*<<< orphan*/ * qglCullFace ; 
 int /*<<< orphan*/ * qglDeleteLists ; 
 int /*<<< orphan*/ * qglDeleteTextures ; 
 int /*<<< orphan*/ * qglDepthFunc ; 
 int /*<<< orphan*/ * qglDepthMask ; 
 int /*<<< orphan*/ * qglDepthRange ; 
 int /*<<< orphan*/ * qglDisable ; 
 int /*<<< orphan*/ * qglDisableClientState ; 
 int /*<<< orphan*/ * qglDrawArrays ; 
 int /*<<< orphan*/ * qglDrawBuffer ; 
 int /*<<< orphan*/ * qglDrawElements ; 
 int /*<<< orphan*/ * qglDrawPixels ; 
 int /*<<< orphan*/ * qglEdgeFlag ; 
 int /*<<< orphan*/ * qglEdgeFlagPointer ; 
 int /*<<< orphan*/ * qglEdgeFlagv ; 
 int /*<<< orphan*/ * qglEnable ; 
 int /*<<< orphan*/ * qglEnableClientState ; 
 int /*<<< orphan*/ * qglEnd ; 
 int /*<<< orphan*/ * qglEndList ; 
 int /*<<< orphan*/ * qglEvalCoord1d ; 
 int /*<<< orphan*/ * qglEvalCoord1dv ; 
 int /*<<< orphan*/ * qglEvalCoord1f ; 
 int /*<<< orphan*/ * qglEvalCoord1fv ; 
 int /*<<< orphan*/ * qglEvalCoord2d ; 
 int /*<<< orphan*/ * qglEvalCoord2dv ; 
 int /*<<< orphan*/ * qglEvalCoord2f ; 
 int /*<<< orphan*/ * qglEvalCoord2fv ; 
 int /*<<< orphan*/ * qglEvalMesh1 ; 
 int /*<<< orphan*/ * qglEvalMesh2 ; 
 int /*<<< orphan*/ * qglEvalPoint1 ; 
 int /*<<< orphan*/ * qglEvalPoint2 ; 
 int /*<<< orphan*/ * qglFeedbackBuffer ; 
 int /*<<< orphan*/ * qglFinish ; 
 int /*<<< orphan*/ * qglFlush ; 
 int /*<<< orphan*/ * qglFogf ; 
 int /*<<< orphan*/ * qglFogfv ; 
 int /*<<< orphan*/ * qglFogi ; 
 int /*<<< orphan*/ * qglFogiv ; 
 int /*<<< orphan*/ * qglFrontFace ; 
 int /*<<< orphan*/ * qglFrustum ; 
 int /*<<< orphan*/ * qglGenLists ; 
 int /*<<< orphan*/ * qglGenTextures ; 
 int /*<<< orphan*/ * qglGetBooleanv ; 
 int /*<<< orphan*/ * qglGetClipPlane ; 
 int /*<<< orphan*/ * qglGetDoublev ; 
 int /*<<< orphan*/ * qglGetError ; 
 int /*<<< orphan*/ * qglGetFloatv ; 
 int /*<<< orphan*/ * qglGetIntegerv ; 
 int /*<<< orphan*/ * qglGetLightfv ; 
 int /*<<< orphan*/ * qglGetLightiv ; 
 int /*<<< orphan*/ * qglGetMapdv ; 
 int /*<<< orphan*/ * qglGetMapfv ; 
 int /*<<< orphan*/ * qglGetMapiv ; 
 int /*<<< orphan*/ * qglGetMaterialfv ; 
 int /*<<< orphan*/ * qglGetMaterialiv ; 
 int /*<<< orphan*/ * qglGetPixelMapfv ; 
 int /*<<< orphan*/ * qglGetPixelMapuiv ; 
 int /*<<< orphan*/ * qglGetPixelMapusv ; 
 int /*<<< orphan*/ * qglGetPointerv ; 
 int /*<<< orphan*/ * qglGetPolygonStipple ; 
 int /*<<< orphan*/ * qglGetString ; 
 int /*<<< orphan*/ * qglGetTexEnvfv ; 
 int /*<<< orphan*/ * qglGetTexEnviv ; 
 int /*<<< orphan*/ * qglGetTexGendv ; 
 int /*<<< orphan*/ * qglGetTexGenfv ; 
 int /*<<< orphan*/ * qglGetTexGeniv ; 
 int /*<<< orphan*/ * qglGetTexImage ; 
 int /*<<< orphan*/ * qglGetTexLevelParameterfv ; 
 int /*<<< orphan*/ * qglGetTexLevelParameteriv ; 
 int /*<<< orphan*/ * qglGetTexParameterfv ; 
 int /*<<< orphan*/ * qglGetTexParameteriv ; 
 int /*<<< orphan*/ * qglHint ; 
 int /*<<< orphan*/ * qglIndexMask ; 
 int /*<<< orphan*/ * qglIndexPointer ; 
 int /*<<< orphan*/ * qglIndexd ; 
 int /*<<< orphan*/ * qglIndexdv ; 
 int /*<<< orphan*/ * qglIndexf ; 
 int /*<<< orphan*/ * qglIndexfv ; 
 int /*<<< orphan*/ * qglIndexi ; 
 int /*<<< orphan*/ * qglIndexiv ; 
 int /*<<< orphan*/ * qglIndexs ; 
 int /*<<< orphan*/ * qglIndexsv ; 
 int /*<<< orphan*/ * qglIndexub ; 
 int /*<<< orphan*/ * qglIndexubv ; 
 int /*<<< orphan*/ * qglInitNames ; 
 int /*<<< orphan*/ * qglInterleavedArrays ; 
 int /*<<< orphan*/ * qglIsEnabled ; 
 int /*<<< orphan*/ * qglIsList ; 
 int /*<<< orphan*/ * qglIsTexture ; 
 int /*<<< orphan*/ * qglLightModelf ; 
 int /*<<< orphan*/ * qglLightModelfv ; 
 int /*<<< orphan*/ * qglLightModeli ; 
 int /*<<< orphan*/ * qglLightModeliv ; 
 int /*<<< orphan*/ * qglLightf ; 
 int /*<<< orphan*/ * qglLightfv ; 
 int /*<<< orphan*/ * qglLighti ; 
 int /*<<< orphan*/ * qglLightiv ; 
 int /*<<< orphan*/ * qglLineStipple ; 
 int /*<<< orphan*/ * qglLineWidth ; 
 int /*<<< orphan*/ * qglListBase ; 
 int /*<<< orphan*/ * qglLoadIdentity ; 
 int /*<<< orphan*/ * qglLoadMatrixd ; 
 int /*<<< orphan*/ * qglLoadMatrixf ; 
 int /*<<< orphan*/ * qglLoadName ; 
 int /*<<< orphan*/ * qglLogicOp ; 
 int /*<<< orphan*/ * qglMap1d ; 
 int /*<<< orphan*/ * qglMap1f ; 
 int /*<<< orphan*/ * qglMap2d ; 
 int /*<<< orphan*/ * qglMap2f ; 
 int /*<<< orphan*/ * qglMapGrid1d ; 
 int /*<<< orphan*/ * qglMapGrid1f ; 
 int /*<<< orphan*/ * qglMapGrid2d ; 
 int /*<<< orphan*/ * qglMapGrid2f ; 
 int /*<<< orphan*/ * qglMaterialf ; 
 int /*<<< orphan*/ * qglMaterialfv ; 
 int /*<<< orphan*/ * qglMateriali ; 
 int /*<<< orphan*/ * qglMaterialiv ; 
 int /*<<< orphan*/ * qglMatrixMode ; 
 int /*<<< orphan*/ * qglMultMatrixd ; 
 int /*<<< orphan*/ * qglMultMatrixf ; 
 int /*<<< orphan*/ * qglNewList ; 
 int /*<<< orphan*/ * qglNormal3b ; 
 int /*<<< orphan*/ * qglNormal3bv ; 
 int /*<<< orphan*/ * qglNormal3d ; 
 int /*<<< orphan*/ * qglNormal3dv ; 
 int /*<<< orphan*/ * qglNormal3f ; 
 int /*<<< orphan*/ * qglNormal3fv ; 
 int /*<<< orphan*/ * qglNormal3i ; 
 int /*<<< orphan*/ * qglNormal3iv ; 
 int /*<<< orphan*/ * qglNormal3s ; 
 int /*<<< orphan*/ * qglNormal3sv ; 
 int /*<<< orphan*/ * qglNormalPointer ; 
 int /*<<< orphan*/ * qglOrtho ; 
 int /*<<< orphan*/ * qglPassThrough ; 
 int /*<<< orphan*/ * qglPixelMapfv ; 
 int /*<<< orphan*/ * qglPixelMapuiv ; 
 int /*<<< orphan*/ * qglPixelMapusv ; 
 int /*<<< orphan*/ * qglPixelStoref ; 
 int /*<<< orphan*/ * qglPixelStorei ; 
 int /*<<< orphan*/ * qglPixelTransferf ; 
 int /*<<< orphan*/ * qglPixelTransferi ; 
 int /*<<< orphan*/ * qglPixelZoom ; 
 int /*<<< orphan*/ * qglPointSize ; 
 int /*<<< orphan*/ * qglPolygonMode ; 
 int /*<<< orphan*/ * qglPolygonOffset ; 
 int /*<<< orphan*/ * qglPolygonStipple ; 
 int /*<<< orphan*/ * qglPopAttrib ; 
 int /*<<< orphan*/ * qglPopClientAttrib ; 
 int /*<<< orphan*/ * qglPopMatrix ; 
 int /*<<< orphan*/ * qglPopName ; 
 int /*<<< orphan*/ * qglPrioritizeTextures ; 
 int /*<<< orphan*/ * qglPushAttrib ; 
 int /*<<< orphan*/ * qglPushClientAttrib ; 
 int /*<<< orphan*/ * qglPushMatrix ; 
 int /*<<< orphan*/ * qglPushName ; 
 int /*<<< orphan*/ * qglRasterPos2d ; 
 int /*<<< orphan*/ * qglRasterPos2dv ; 
 int /*<<< orphan*/ * qglRasterPos2f ; 
 int /*<<< orphan*/ * qglRasterPos2fv ; 
 int /*<<< orphan*/ * qglRasterPos2i ; 
 int /*<<< orphan*/ * qglRasterPos2iv ; 
 int /*<<< orphan*/ * qglRasterPos2s ; 
 int /*<<< orphan*/ * qglRasterPos2sv ; 
 int /*<<< orphan*/ * qglRasterPos3d ; 
 int /*<<< orphan*/ * qglRasterPos3dv ; 
 int /*<<< orphan*/ * qglRasterPos3f ; 
 int /*<<< orphan*/ * qglRasterPos3fv ; 
 int /*<<< orphan*/ * qglRasterPos3i ; 
 int /*<<< orphan*/ * qglRasterPos3iv ; 
 int /*<<< orphan*/ * qglRasterPos3s ; 
 int /*<<< orphan*/ * qglRasterPos3sv ; 
 int /*<<< orphan*/ * qglRasterPos4d ; 
 int /*<<< orphan*/ * qglRasterPos4dv ; 
 int /*<<< orphan*/ * qglRasterPos4f ; 
 int /*<<< orphan*/ * qglRasterPos4fv ; 
 int /*<<< orphan*/ * qglRasterPos4i ; 
 int /*<<< orphan*/ * qglRasterPos4iv ; 
 int /*<<< orphan*/ * qglRasterPos4s ; 
 int /*<<< orphan*/ * qglRasterPos4sv ; 
 int /*<<< orphan*/ * qglReadBuffer ; 
 int /*<<< orphan*/ * qglReadPixels ; 
 int /*<<< orphan*/ * qglRectd ; 
 int /*<<< orphan*/ * qglRectdv ; 
 int /*<<< orphan*/ * qglRectf ; 
 int /*<<< orphan*/ * qglRectfv ; 
 int /*<<< orphan*/ * qglRecti ; 
 int /*<<< orphan*/ * qglRectiv ; 
 int /*<<< orphan*/ * qglRects ; 
 int /*<<< orphan*/ * qglRectsv ; 
 int /*<<< orphan*/ * qglRenderMode ; 
 int /*<<< orphan*/ * qglRotated ; 
 int /*<<< orphan*/ * qglRotatef ; 
 int /*<<< orphan*/ * qglScaled ; 
 int /*<<< orphan*/ * qglScalef ; 
 int /*<<< orphan*/ * qglScissor ; 
 int /*<<< orphan*/ * qglSelectBuffer ; 
 int /*<<< orphan*/ * qglShadeModel ; 
 int /*<<< orphan*/ * qglStencilFunc ; 
 int /*<<< orphan*/ * qglStencilMask ; 
 int /*<<< orphan*/ * qglStencilOp ; 
 int /*<<< orphan*/ * qglTexCoord1d ; 
 int /*<<< orphan*/ * qglTexCoord1dv ; 
 int /*<<< orphan*/ * qglTexCoord1f ; 
 int /*<<< orphan*/ * qglTexCoord1fv ; 
 int /*<<< orphan*/ * qglTexCoord1i ; 
 int /*<<< orphan*/ * qglTexCoord1iv ; 
 int /*<<< orphan*/ * qglTexCoord1s ; 
 int /*<<< orphan*/ * qglTexCoord1sv ; 
 int /*<<< orphan*/ * qglTexCoord2d ; 
 int /*<<< orphan*/ * qglTexCoord2dv ; 
 int /*<<< orphan*/ * qglTexCoord2f ; 
 int /*<<< orphan*/ * qglTexCoord2fv ; 
 int /*<<< orphan*/ * qglTexCoord2i ; 
 int /*<<< orphan*/ * qglTexCoord2iv ; 
 int /*<<< orphan*/ * qglTexCoord2s ; 
 int /*<<< orphan*/ * qglTexCoord2sv ; 
 int /*<<< orphan*/ * qglTexCoord3d ; 
 int /*<<< orphan*/ * qglTexCoord3dv ; 
 int /*<<< orphan*/ * qglTexCoord3f ; 
 int /*<<< orphan*/ * qglTexCoord3fv ; 
 int /*<<< orphan*/ * qglTexCoord3i ; 
 int /*<<< orphan*/ * qglTexCoord3iv ; 
 int /*<<< orphan*/ * qglTexCoord3s ; 
 int /*<<< orphan*/ * qglTexCoord3sv ; 
 int /*<<< orphan*/ * qglTexCoord4d ; 
 int /*<<< orphan*/ * qglTexCoord4dv ; 
 int /*<<< orphan*/ * qglTexCoord4f ; 
 int /*<<< orphan*/ * qglTexCoord4fv ; 
 int /*<<< orphan*/ * qglTexCoord4i ; 
 int /*<<< orphan*/ * qglTexCoord4iv ; 
 int /*<<< orphan*/ * qglTexCoord4s ; 
 int /*<<< orphan*/ * qglTexCoord4sv ; 
 int /*<<< orphan*/ * qglTexCoordPointer ; 
 int /*<<< orphan*/ * qglTexEnvf ; 
 int /*<<< orphan*/ * qglTexEnvfv ; 
 int /*<<< orphan*/ * qglTexEnvi ; 
 int /*<<< orphan*/ * qglTexEnviv ; 
 int /*<<< orphan*/ * qglTexGend ; 
 int /*<<< orphan*/ * qglTexGendv ; 
 int /*<<< orphan*/ * qglTexGenf ; 
 int /*<<< orphan*/ * qglTexGenfv ; 
 int /*<<< orphan*/ * qglTexGeni ; 
 int /*<<< orphan*/ * qglTexGeniv ; 
 int /*<<< orphan*/ * qglTexImage1D ; 
 int /*<<< orphan*/ * qglTexImage2D ; 
 int /*<<< orphan*/ * qglTexParameterf ; 
 int /*<<< orphan*/ * qglTexParameterfv ; 
 int /*<<< orphan*/ * qglTexParameteri ; 
 int /*<<< orphan*/ * qglTexParameteriv ; 
 int /*<<< orphan*/ * qglTexSubImage1D ; 
 int /*<<< orphan*/ * qglTexSubImage2D ; 
 int /*<<< orphan*/ * qglTranslated ; 
 int /*<<< orphan*/ * qglTranslatef ; 
 int /*<<< orphan*/ * qglVertex2d ; 
 int /*<<< orphan*/ * qglVertex2dv ; 
 int /*<<< orphan*/ * qglVertex2f ; 
 int /*<<< orphan*/ * qglVertex2fv ; 
 int /*<<< orphan*/ * qglVertex2i ; 
 int /*<<< orphan*/ * qglVertex2iv ; 
 int /*<<< orphan*/ * qglVertex2s ; 
 int /*<<< orphan*/ * qglVertex2sv ; 
 int /*<<< orphan*/ * qglVertex3d ; 
 int /*<<< orphan*/ * qglVertex3dv ; 
 int /*<<< orphan*/ * qglVertex3f ; 
 int /*<<< orphan*/ * qglVertex3fv ; 
 int /*<<< orphan*/ * qglVertex3i ; 
 int /*<<< orphan*/ * qglVertex3iv ; 
 int /*<<< orphan*/ * qglVertex3s ; 
 int /*<<< orphan*/ * qglVertex3sv ; 
 int /*<<< orphan*/ * qglVertex4d ; 
 int /*<<< orphan*/ * qglVertex4dv ; 
 int /*<<< orphan*/ * qglVertex4f ; 
 int /*<<< orphan*/ * qglVertex4fv ; 
 int /*<<< orphan*/ * qglVertex4i ; 
 int /*<<< orphan*/ * qglVertex4iv ; 
 int /*<<< orphan*/ * qglVertex4s ; 
 int /*<<< orphan*/ * qglVertex4sv ; 
 int /*<<< orphan*/ * qglVertexPointer ; 
 int /*<<< orphan*/ * qglViewport ; 
 int /*<<< orphan*/ * qglXChooseVisual ; 
 int /*<<< orphan*/ * qglXCopyContext ; 
 int /*<<< orphan*/ * qglXCreateContext ; 
 int /*<<< orphan*/ * qglXDestroyContext ; 
 int /*<<< orphan*/ * qglXMakeCurrent ; 
 int /*<<< orphan*/ * qglXSwapBuffers ; 

void QGL_Shutdown( void )
{
	if ( glw_state.OpenGLLib )
	{
		dlclose ( glw_state.OpenGLLib );
		glw_state.OpenGLLib = NULL;
	}

	glw_state.OpenGLLib = NULL;

	qglAccum                     = NULL;
	qglAlphaFunc                 = NULL;
	qglAreTexturesResident       = NULL;
	qglArrayElement              = NULL;
	qglBegin                     = NULL;
	qglBindTexture               = NULL;
	qglBitmap                    = NULL;
	qglBlendFunc                 = NULL;
	qglCallList                  = NULL;
	qglCallLists                 = NULL;
	qglClear                     = NULL;
	qglClearAccum                = NULL;
	qglClearColor                = NULL;
	qglClearDepth                = NULL;
	qglClearIndex                = NULL;
	qglClearStencil              = NULL;
	qglClipPlane                 = NULL;
	qglColor3b                   = NULL;
	qglColor3bv                  = NULL;
	qglColor3d                   = NULL;
	qglColor3dv                  = NULL;
	qglColor3f                   = NULL;
	qglColor3fv                  = NULL;
	qglColor3i                   = NULL;
	qglColor3iv                  = NULL;
	qglColor3s                   = NULL;
	qglColor3sv                  = NULL;
	qglColor3ub                  = NULL;
	qglColor3ubv                 = NULL;
	qglColor3ui                  = NULL;
	qglColor3uiv                 = NULL;
	qglColor3us                  = NULL;
	qglColor3usv                 = NULL;
	qglColor4b                   = NULL;
	qglColor4bv                  = NULL;
	qglColor4d                   = NULL;
	qglColor4dv                  = NULL;
	qglColor4f                   = NULL;
	qglColor4fv                  = NULL;
	qglColor4i                   = NULL;
	qglColor4iv                  = NULL;
	qglColor4s                   = NULL;
	qglColor4sv                  = NULL;
	qglColor4ub                  = NULL;
	qglColor4ubv                 = NULL;
	qglColor4ui                  = NULL;
	qglColor4uiv                 = NULL;
	qglColor4us                  = NULL;
	qglColor4usv                 = NULL;
	qglColorMask                 = NULL;
	qglColorMaterial             = NULL;
	qglColorPointer              = NULL;
	qglCopyPixels                = NULL;
	qglCopyTexImage1D            = NULL;
	qglCopyTexImage2D            = NULL;
	qglCopyTexSubImage1D         = NULL;
	qglCopyTexSubImage2D         = NULL;
	qglCullFace                  = NULL;
	qglDeleteLists               = NULL;
	qglDeleteTextures            = NULL;
	qglDepthFunc                 = NULL;
	qglDepthMask                 = NULL;
	qglDepthRange                = NULL;
	qglDisable                   = NULL;
	qglDisableClientState        = NULL;
	qglDrawArrays                = NULL;
	qglDrawBuffer                = NULL;
	qglDrawElements              = NULL;
	qglDrawPixels                = NULL;
	qglEdgeFlag                  = NULL;
	qglEdgeFlagPointer           = NULL;
	qglEdgeFlagv                 = NULL;
	qglEnable                    = NULL;
	qglEnableClientState         = NULL;
	qglEnd                       = NULL;
	qglEndList                   = NULL;
	qglEvalCoord1d               = NULL;
	qglEvalCoord1dv              = NULL;
	qglEvalCoord1f               = NULL;
	qglEvalCoord1fv              = NULL;
	qglEvalCoord2d               = NULL;
	qglEvalCoord2dv              = NULL;
	qglEvalCoord2f               = NULL;
	qglEvalCoord2fv              = NULL;
	qglEvalMesh1                 = NULL;
	qglEvalMesh2                 = NULL;
	qglEvalPoint1                = NULL;
	qglEvalPoint2                = NULL;
	qglFeedbackBuffer            = NULL;
	qglFinish                    = NULL;
	qglFlush                     = NULL;
	qglFogf                      = NULL;
	qglFogfv                     = NULL;
	qglFogi                      = NULL;
	qglFogiv                     = NULL;
	qglFrontFace                 = NULL;
	qglFrustum                   = NULL;
	qglGenLists                  = NULL;
	qglGenTextures               = NULL;
	qglGetBooleanv               = NULL;
	qglGetClipPlane              = NULL;
	qglGetDoublev                = NULL;
	qglGetError                  = NULL;
	qglGetFloatv                 = NULL;
	qglGetIntegerv               = NULL;
	qglGetLightfv                = NULL;
	qglGetLightiv                = NULL;
	qglGetMapdv                  = NULL;
	qglGetMapfv                  = NULL;
	qglGetMapiv                  = NULL;
	qglGetMaterialfv             = NULL;
	qglGetMaterialiv             = NULL;
	qglGetPixelMapfv             = NULL;
	qglGetPixelMapuiv            = NULL;
	qglGetPixelMapusv            = NULL;
	qglGetPointerv               = NULL;
	qglGetPolygonStipple         = NULL;
	qglGetString                 = NULL;
	qglGetTexEnvfv               = NULL;
	qglGetTexEnviv               = NULL;
	qglGetTexGendv               = NULL;
	qglGetTexGenfv               = NULL;
	qglGetTexGeniv               = NULL;
	qglGetTexImage               = NULL;
	qglGetTexLevelParameterfv    = NULL;
	qglGetTexLevelParameteriv    = NULL;
	qglGetTexParameterfv         = NULL;
	qglGetTexParameteriv         = NULL;
	qglHint                      = NULL;
	qglIndexMask                 = NULL;
	qglIndexPointer              = NULL;
	qglIndexd                    = NULL;
	qglIndexdv                   = NULL;
	qglIndexf                    = NULL;
	qglIndexfv                   = NULL;
	qglIndexi                    = NULL;
	qglIndexiv                   = NULL;
	qglIndexs                    = NULL;
	qglIndexsv                   = NULL;
	qglIndexub                   = NULL;
	qglIndexubv                  = NULL;
	qglInitNames                 = NULL;
	qglInterleavedArrays         = NULL;
	qglIsEnabled                 = NULL;
	qglIsList                    = NULL;
	qglIsTexture                 = NULL;
	qglLightModelf               = NULL;
	qglLightModelfv              = NULL;
	qglLightModeli               = NULL;
	qglLightModeliv              = NULL;
	qglLightf                    = NULL;
	qglLightfv                   = NULL;
	qglLighti                    = NULL;
	qglLightiv                   = NULL;
	qglLineStipple               = NULL;
	qglLineWidth                 = NULL;
	qglListBase                  = NULL;
	qglLoadIdentity              = NULL;
	qglLoadMatrixd               = NULL;
	qglLoadMatrixf               = NULL;
	qglLoadName                  = NULL;
	qglLogicOp                   = NULL;
	qglMap1d                     = NULL;
	qglMap1f                     = NULL;
	qglMap2d                     = NULL;
	qglMap2f                     = NULL;
	qglMapGrid1d                 = NULL;
	qglMapGrid1f                 = NULL;
	qglMapGrid2d                 = NULL;
	qglMapGrid2f                 = NULL;
	qglMaterialf                 = NULL;
	qglMaterialfv                = NULL;
	qglMateriali                 = NULL;
	qglMaterialiv                = NULL;
	qglMatrixMode                = NULL;
	qglMultMatrixd               = NULL;
	qglMultMatrixf               = NULL;
	qglNewList                   = NULL;
	qglNormal3b                  = NULL;
	qglNormal3bv                 = NULL;
	qglNormal3d                  = NULL;
	qglNormal3dv                 = NULL;
	qglNormal3f                  = NULL;
	qglNormal3fv                 = NULL;
	qglNormal3i                  = NULL;
	qglNormal3iv                 = NULL;
	qglNormal3s                  = NULL;
	qglNormal3sv                 = NULL;
	qglNormalPointer             = NULL;
	qglOrtho                     = NULL;
	qglPassThrough               = NULL;
	qglPixelMapfv                = NULL;
	qglPixelMapuiv               = NULL;
	qglPixelMapusv               = NULL;
	qglPixelStoref               = NULL;
	qglPixelStorei               = NULL;
	qglPixelTransferf            = NULL;
	qglPixelTransferi            = NULL;
	qglPixelZoom                 = NULL;
	qglPointSize                 = NULL;
	qglPolygonMode               = NULL;
	qglPolygonOffset             = NULL;
	qglPolygonStipple            = NULL;
	qglPopAttrib                 = NULL;
	qglPopClientAttrib           = NULL;
	qglPopMatrix                 = NULL;
	qglPopName                   = NULL;
	qglPrioritizeTextures        = NULL;
	qglPushAttrib                = NULL;
	qglPushClientAttrib          = NULL;
	qglPushMatrix                = NULL;
	qglPushName                  = NULL;
	qglRasterPos2d               = NULL;
	qglRasterPos2dv              = NULL;
	qglRasterPos2f               = NULL;
	qglRasterPos2fv              = NULL;
	qglRasterPos2i               = NULL;
	qglRasterPos2iv              = NULL;
	qglRasterPos2s               = NULL;
	qglRasterPos2sv              = NULL;
	qglRasterPos3d               = NULL;
	qglRasterPos3dv              = NULL;
	qglRasterPos3f               = NULL;
	qglRasterPos3fv              = NULL;
	qglRasterPos3i               = NULL;
	qglRasterPos3iv              = NULL;
	qglRasterPos3s               = NULL;
	qglRasterPos3sv              = NULL;
	qglRasterPos4d               = NULL;
	qglRasterPos4dv              = NULL;
	qglRasterPos4f               = NULL;
	qglRasterPos4fv              = NULL;
	qglRasterPos4i               = NULL;
	qglRasterPos4iv              = NULL;
	qglRasterPos4s               = NULL;
	qglRasterPos4sv              = NULL;
	qglReadBuffer                = NULL;
	qglReadPixels                = NULL;
	qglRectd                     = NULL;
	qglRectdv                    = NULL;
	qglRectf                     = NULL;
	qglRectfv                    = NULL;
	qglRecti                     = NULL;
	qglRectiv                    = NULL;
	qglRects                     = NULL;
	qglRectsv                    = NULL;
	qglRenderMode                = NULL;
	qglRotated                   = NULL;
	qglRotatef                   = NULL;
	qglScaled                    = NULL;
	qglScalef                    = NULL;
	qglScissor                   = NULL;
	qglSelectBuffer              = NULL;
	qglShadeModel                = NULL;
	qglStencilFunc               = NULL;
	qglStencilMask               = NULL;
	qglStencilOp                 = NULL;
	qglTexCoord1d                = NULL;
	qglTexCoord1dv               = NULL;
	qglTexCoord1f                = NULL;
	qglTexCoord1fv               = NULL;
	qglTexCoord1i                = NULL;
	qglTexCoord1iv               = NULL;
	qglTexCoord1s                = NULL;
	qglTexCoord1sv               = NULL;
	qglTexCoord2d                = NULL;
	qglTexCoord2dv               = NULL;
	qglTexCoord2f                = NULL;
	qglTexCoord2fv               = NULL;
	qglTexCoord2i                = NULL;
	qglTexCoord2iv               = NULL;
	qglTexCoord2s                = NULL;
	qglTexCoord2sv               = NULL;
	qglTexCoord3d                = NULL;
	qglTexCoord3dv               = NULL;
	qglTexCoord3f                = NULL;
	qglTexCoord3fv               = NULL;
	qglTexCoord3i                = NULL;
	qglTexCoord3iv               = NULL;
	qglTexCoord3s                = NULL;
	qglTexCoord3sv               = NULL;
	qglTexCoord4d                = NULL;
	qglTexCoord4dv               = NULL;
	qglTexCoord4f                = NULL;
	qglTexCoord4fv               = NULL;
	qglTexCoord4i                = NULL;
	qglTexCoord4iv               = NULL;
	qglTexCoord4s                = NULL;
	qglTexCoord4sv               = NULL;
	qglTexCoordPointer           = NULL;
	qglTexEnvf                   = NULL;
	qglTexEnvfv                  = NULL;
	qglTexEnvi                   = NULL;
	qglTexEnviv                  = NULL;
	qglTexGend                   = NULL;
	qglTexGendv                  = NULL;
	qglTexGenf                   = NULL;
	qglTexGenfv                  = NULL;
	qglTexGeni                   = NULL;
	qglTexGeniv                  = NULL;
	qglTexImage1D                = NULL;
	qglTexImage2D                = NULL;
	qglTexParameterf             = NULL;
	qglTexParameterfv            = NULL;
	qglTexParameteri             = NULL;
	qglTexParameteriv            = NULL;
	qglTexSubImage1D             = NULL;
	qglTexSubImage2D             = NULL;
	qglTranslated                = NULL;
	qglTranslatef                = NULL;
	qglVertex2d                  = NULL;
	qglVertex2dv                 = NULL;
	qglVertex2f                  = NULL;
	qglVertex2fv                 = NULL;
	qglVertex2i                  = NULL;
	qglVertex2iv                 = NULL;
	qglVertex2s                  = NULL;
	qglVertex2sv                 = NULL;
	qglVertex3d                  = NULL;
	qglVertex3dv                 = NULL;
	qglVertex3f                  = NULL;
	qglVertex3fv                 = NULL;
	qglVertex3i                  = NULL;
	qglVertex3iv                 = NULL;
	qglVertex3s                  = NULL;
	qglVertex3sv                 = NULL;
	qglVertex4d                  = NULL;
	qglVertex4dv                 = NULL;
	qglVertex4f                  = NULL;
	qglVertex4fv                 = NULL;
	qglVertex4i                  = NULL;
	qglVertex4iv                 = NULL;
	qglVertex4s                  = NULL;
	qglVertex4sv                 = NULL;
	qglVertexPointer             = NULL;
	qglViewport                  = NULL;

// bk001129 - from cvs1.17 (mkv)
#if defined(__FX__)
	qfxMesaCreateContext         = NULL;
	qfxMesaCreateBestContext     = NULL;
	qfxMesaDestroyContext        = NULL;
	qfxMesaMakeCurrent           = NULL;
	qfxMesaGetCurrentContext     = NULL;
	qfxMesaSwapBuffers           = NULL;
#endif

	qglXChooseVisual             = NULL;
	qglXCreateContext            = NULL;
	qglXDestroyContext           = NULL;
	qglXMakeCurrent              = NULL;
	qglXCopyContext              = NULL;
	qglXSwapBuffers              = NULL;
}