#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
struct device {int dummy; } ;

/* Variables and functions */
#define  ARIZONA_ADC_DIGITAL_VOLUME_1L 820 
#define  ARIZONA_ADC_DIGITAL_VOLUME_1R 819 
#define  ARIZONA_ADC_DIGITAL_VOLUME_2L 818 
#define  ARIZONA_ADC_DIGITAL_VOLUME_2R 817 
#define  ARIZONA_AIF1TX1MIX_INPUT_1_SOURCE 816 
#define  ARIZONA_AIF1TX1MIX_INPUT_1_VOLUME 815 
#define  ARIZONA_AIF1TX1MIX_INPUT_2_SOURCE 814 
#define  ARIZONA_AIF1TX1MIX_INPUT_2_VOLUME 813 
#define  ARIZONA_AIF1TX1MIX_INPUT_3_SOURCE 812 
#define  ARIZONA_AIF1TX1MIX_INPUT_3_VOLUME 811 
#define  ARIZONA_AIF1TX1MIX_INPUT_4_SOURCE 810 
#define  ARIZONA_AIF1TX1MIX_INPUT_4_VOLUME 809 
#define  ARIZONA_AIF1TX2MIX_INPUT_1_SOURCE 808 
#define  ARIZONA_AIF1TX2MIX_INPUT_1_VOLUME 807 
#define  ARIZONA_AIF1TX2MIX_INPUT_2_SOURCE 806 
#define  ARIZONA_AIF1TX2MIX_INPUT_2_VOLUME 805 
#define  ARIZONA_AIF1TX2MIX_INPUT_3_SOURCE 804 
#define  ARIZONA_AIF1TX2MIX_INPUT_3_VOLUME 803 
#define  ARIZONA_AIF1TX2MIX_INPUT_4_SOURCE 802 
#define  ARIZONA_AIF1TX2MIX_INPUT_4_VOLUME 801 
#define  ARIZONA_AIF1TX3MIX_INPUT_1_SOURCE 800 
#define  ARIZONA_AIF1TX3MIX_INPUT_1_VOLUME 799 
#define  ARIZONA_AIF1TX3MIX_INPUT_2_SOURCE 798 
#define  ARIZONA_AIF1TX3MIX_INPUT_2_VOLUME 797 
#define  ARIZONA_AIF1TX3MIX_INPUT_3_SOURCE 796 
#define  ARIZONA_AIF1TX3MIX_INPUT_3_VOLUME 795 
#define  ARIZONA_AIF1TX3MIX_INPUT_4_SOURCE 794 
#define  ARIZONA_AIF1TX3MIX_INPUT_4_VOLUME 793 
#define  ARIZONA_AIF1TX4MIX_INPUT_1_SOURCE 792 
#define  ARIZONA_AIF1TX4MIX_INPUT_1_VOLUME 791 
#define  ARIZONA_AIF1TX4MIX_INPUT_2_SOURCE 790 
#define  ARIZONA_AIF1TX4MIX_INPUT_2_VOLUME 789 
#define  ARIZONA_AIF1TX4MIX_INPUT_3_SOURCE 788 
#define  ARIZONA_AIF1TX4MIX_INPUT_3_VOLUME 787 
#define  ARIZONA_AIF1TX4MIX_INPUT_4_SOURCE 786 
#define  ARIZONA_AIF1TX4MIX_INPUT_4_VOLUME 785 
#define  ARIZONA_AIF1TX5MIX_INPUT_1_SOURCE 784 
#define  ARIZONA_AIF1TX5MIX_INPUT_1_VOLUME 783 
#define  ARIZONA_AIF1TX5MIX_INPUT_2_SOURCE 782 
#define  ARIZONA_AIF1TX5MIX_INPUT_2_VOLUME 781 
#define  ARIZONA_AIF1TX5MIX_INPUT_3_SOURCE 780 
#define  ARIZONA_AIF1TX5MIX_INPUT_3_VOLUME 779 
#define  ARIZONA_AIF1TX5MIX_INPUT_4_SOURCE 778 
#define  ARIZONA_AIF1TX5MIX_INPUT_4_VOLUME 777 
#define  ARIZONA_AIF1TX6MIX_INPUT_1_SOURCE 776 
#define  ARIZONA_AIF1TX6MIX_INPUT_1_VOLUME 775 
#define  ARIZONA_AIF1TX6MIX_INPUT_2_SOURCE 774 
#define  ARIZONA_AIF1TX6MIX_INPUT_2_VOLUME 773 
#define  ARIZONA_AIF1TX6MIX_INPUT_3_SOURCE 772 
#define  ARIZONA_AIF1TX6MIX_INPUT_3_VOLUME 771 
#define  ARIZONA_AIF1TX6MIX_INPUT_4_SOURCE 770 
#define  ARIZONA_AIF1TX6MIX_INPUT_4_VOLUME 769 
#define  ARIZONA_AIF1TX7MIX_INPUT_1_SOURCE 768 
#define  ARIZONA_AIF1TX7MIX_INPUT_1_VOLUME 767 
#define  ARIZONA_AIF1TX7MIX_INPUT_2_SOURCE 766 
#define  ARIZONA_AIF1TX7MIX_INPUT_2_VOLUME 765 
#define  ARIZONA_AIF1TX7MIX_INPUT_3_SOURCE 764 
#define  ARIZONA_AIF1TX7MIX_INPUT_3_VOLUME 763 
#define  ARIZONA_AIF1TX7MIX_INPUT_4_SOURCE 762 
#define  ARIZONA_AIF1TX7MIX_INPUT_4_VOLUME 761 
#define  ARIZONA_AIF1TX8MIX_INPUT_1_SOURCE 760 
#define  ARIZONA_AIF1TX8MIX_INPUT_1_VOLUME 759 
#define  ARIZONA_AIF1TX8MIX_INPUT_2_SOURCE 758 
#define  ARIZONA_AIF1TX8MIX_INPUT_2_VOLUME 757 
#define  ARIZONA_AIF1TX8MIX_INPUT_3_SOURCE 756 
#define  ARIZONA_AIF1TX8MIX_INPUT_3_VOLUME 755 
#define  ARIZONA_AIF1TX8MIX_INPUT_4_SOURCE 754 
#define  ARIZONA_AIF1TX8MIX_INPUT_4_VOLUME 753 
#define  ARIZONA_AIF1_BCLK_CTRL 752 
#define  ARIZONA_AIF1_FORMAT 751 
#define  ARIZONA_AIF1_FRAME_CTRL_1 750 
#define  ARIZONA_AIF1_FRAME_CTRL_10 749 
#define  ARIZONA_AIF1_FRAME_CTRL_11 748 
#define  ARIZONA_AIF1_FRAME_CTRL_12 747 
#define  ARIZONA_AIF1_FRAME_CTRL_13 746 
#define  ARIZONA_AIF1_FRAME_CTRL_14 745 
#define  ARIZONA_AIF1_FRAME_CTRL_15 744 
#define  ARIZONA_AIF1_FRAME_CTRL_16 743 
#define  ARIZONA_AIF1_FRAME_CTRL_17 742 
#define  ARIZONA_AIF1_FRAME_CTRL_18 741 
#define  ARIZONA_AIF1_FRAME_CTRL_2 740 
#define  ARIZONA_AIF1_FRAME_CTRL_3 739 
#define  ARIZONA_AIF1_FRAME_CTRL_4 738 
#define  ARIZONA_AIF1_FRAME_CTRL_5 737 
#define  ARIZONA_AIF1_FRAME_CTRL_6 736 
#define  ARIZONA_AIF1_FRAME_CTRL_7 735 
#define  ARIZONA_AIF1_FRAME_CTRL_8 734 
#define  ARIZONA_AIF1_FRAME_CTRL_9 733 
#define  ARIZONA_AIF1_RATE_CTRL 732 
#define  ARIZONA_AIF1_RX_BCLK_RATE 731 
#define  ARIZONA_AIF1_RX_ENABLES 730 
#define  ARIZONA_AIF1_RX_PIN_CTRL 729 
#define  ARIZONA_AIF1_TX_BCLK_RATE 728 
#define  ARIZONA_AIF1_TX_ENABLES 727 
#define  ARIZONA_AIF1_TX_PIN_CTRL 726 
#define  ARIZONA_AIF2TX1MIX_INPUT_1_SOURCE 725 
#define  ARIZONA_AIF2TX1MIX_INPUT_1_VOLUME 724 
#define  ARIZONA_AIF2TX1MIX_INPUT_2_SOURCE 723 
#define  ARIZONA_AIF2TX1MIX_INPUT_2_VOLUME 722 
#define  ARIZONA_AIF2TX1MIX_INPUT_3_SOURCE 721 
#define  ARIZONA_AIF2TX1MIX_INPUT_3_VOLUME 720 
#define  ARIZONA_AIF2TX1MIX_INPUT_4_SOURCE 719 
#define  ARIZONA_AIF2TX1MIX_INPUT_4_VOLUME 718 
#define  ARIZONA_AIF2TX2MIX_INPUT_1_SOURCE 717 
#define  ARIZONA_AIF2TX2MIX_INPUT_1_VOLUME 716 
#define  ARIZONA_AIF2TX2MIX_INPUT_2_SOURCE 715 
#define  ARIZONA_AIF2TX2MIX_INPUT_2_VOLUME 714 
#define  ARIZONA_AIF2TX2MIX_INPUT_3_SOURCE 713 
#define  ARIZONA_AIF2TX2MIX_INPUT_3_VOLUME 712 
#define  ARIZONA_AIF2TX2MIX_INPUT_4_SOURCE 711 
#define  ARIZONA_AIF2TX2MIX_INPUT_4_VOLUME 710 
#define  ARIZONA_AIF2TX3MIX_INPUT_1_SOURCE 709 
#define  ARIZONA_AIF2TX3MIX_INPUT_1_VOLUME 708 
#define  ARIZONA_AIF2TX3MIX_INPUT_2_SOURCE 707 
#define  ARIZONA_AIF2TX3MIX_INPUT_2_VOLUME 706 
#define  ARIZONA_AIF2TX3MIX_INPUT_3_SOURCE 705 
#define  ARIZONA_AIF2TX3MIX_INPUT_3_VOLUME 704 
#define  ARIZONA_AIF2TX3MIX_INPUT_4_SOURCE 703 
#define  ARIZONA_AIF2TX3MIX_INPUT_4_VOLUME 702 
#define  ARIZONA_AIF2TX4MIX_INPUT_1_SOURCE 701 
#define  ARIZONA_AIF2TX4MIX_INPUT_1_VOLUME 700 
#define  ARIZONA_AIF2TX4MIX_INPUT_2_SOURCE 699 
#define  ARIZONA_AIF2TX4MIX_INPUT_2_VOLUME 698 
#define  ARIZONA_AIF2TX4MIX_INPUT_3_SOURCE 697 
#define  ARIZONA_AIF2TX4MIX_INPUT_3_VOLUME 696 
#define  ARIZONA_AIF2TX4MIX_INPUT_4_SOURCE 695 
#define  ARIZONA_AIF2TX4MIX_INPUT_4_VOLUME 694 
#define  ARIZONA_AIF2TX5MIX_INPUT_1_SOURCE 693 
#define  ARIZONA_AIF2TX5MIX_INPUT_1_VOLUME 692 
#define  ARIZONA_AIF2TX5MIX_INPUT_2_SOURCE 691 
#define  ARIZONA_AIF2TX5MIX_INPUT_2_VOLUME 690 
#define  ARIZONA_AIF2TX5MIX_INPUT_3_SOURCE 689 
#define  ARIZONA_AIF2TX5MIX_INPUT_3_VOLUME 688 
#define  ARIZONA_AIF2TX5MIX_INPUT_4_SOURCE 687 
#define  ARIZONA_AIF2TX5MIX_INPUT_4_VOLUME 686 
#define  ARIZONA_AIF2TX6MIX_INPUT_1_SOURCE 685 
#define  ARIZONA_AIF2TX6MIX_INPUT_1_VOLUME 684 
#define  ARIZONA_AIF2TX6MIX_INPUT_2_SOURCE 683 
#define  ARIZONA_AIF2TX6MIX_INPUT_2_VOLUME 682 
#define  ARIZONA_AIF2TX6MIX_INPUT_3_SOURCE 681 
#define  ARIZONA_AIF2TX6MIX_INPUT_3_VOLUME 680 
#define  ARIZONA_AIF2TX6MIX_INPUT_4_SOURCE 679 
#define  ARIZONA_AIF2TX6MIX_INPUT_4_VOLUME 678 
#define  ARIZONA_AIF2_BCLK_CTRL 677 
#define  ARIZONA_AIF2_FORMAT 676 
#define  ARIZONA_AIF2_FRAME_CTRL_1 675 
#define  ARIZONA_AIF2_FRAME_CTRL_11 674 
#define  ARIZONA_AIF2_FRAME_CTRL_12 673 
#define  ARIZONA_AIF2_FRAME_CTRL_13 672 
#define  ARIZONA_AIF2_FRAME_CTRL_14 671 
#define  ARIZONA_AIF2_FRAME_CTRL_15 670 
#define  ARIZONA_AIF2_FRAME_CTRL_16 669 
#define  ARIZONA_AIF2_FRAME_CTRL_2 668 
#define  ARIZONA_AIF2_FRAME_CTRL_3 667 
#define  ARIZONA_AIF2_FRAME_CTRL_4 666 
#define  ARIZONA_AIF2_FRAME_CTRL_5 665 
#define  ARIZONA_AIF2_FRAME_CTRL_6 664 
#define  ARIZONA_AIF2_FRAME_CTRL_7 663 
#define  ARIZONA_AIF2_FRAME_CTRL_8 662 
#define  ARIZONA_AIF2_RATE_CTRL 661 
#define  ARIZONA_AIF2_RX_BCLK_RATE 660 
#define  ARIZONA_AIF2_RX_ENABLES 659 
#define  ARIZONA_AIF2_RX_PIN_CTRL 658 
#define  ARIZONA_AIF2_TX_BCLK_RATE 657 
#define  ARIZONA_AIF2_TX_ENABLES 656 
#define  ARIZONA_AIF2_TX_PIN_CTRL 655 
#define  ARIZONA_AIF3TX1MIX_INPUT_1_SOURCE 654 
#define  ARIZONA_AIF3TX1MIX_INPUT_1_VOLUME 653 
#define  ARIZONA_AIF3TX1MIX_INPUT_2_SOURCE 652 
#define  ARIZONA_AIF3TX1MIX_INPUT_2_VOLUME 651 
#define  ARIZONA_AIF3TX1MIX_INPUT_3_SOURCE 650 
#define  ARIZONA_AIF3TX1MIX_INPUT_3_VOLUME 649 
#define  ARIZONA_AIF3TX1MIX_INPUT_4_SOURCE 648 
#define  ARIZONA_AIF3TX1MIX_INPUT_4_VOLUME 647 
#define  ARIZONA_AIF3TX2MIX_INPUT_1_SOURCE 646 
#define  ARIZONA_AIF3TX2MIX_INPUT_1_VOLUME 645 
#define  ARIZONA_AIF3TX2MIX_INPUT_2_SOURCE 644 
#define  ARIZONA_AIF3TX2MIX_INPUT_2_VOLUME 643 
#define  ARIZONA_AIF3TX2MIX_INPUT_3_SOURCE 642 
#define  ARIZONA_AIF3TX2MIX_INPUT_3_VOLUME 641 
#define  ARIZONA_AIF3TX2MIX_INPUT_4_SOURCE 640 
#define  ARIZONA_AIF3TX2MIX_INPUT_4_VOLUME 639 
#define  ARIZONA_AIF3_BCLK_CTRL 638 
#define  ARIZONA_AIF3_FORMAT 637 
#define  ARIZONA_AIF3_FRAME_CTRL_1 636 
#define  ARIZONA_AIF3_FRAME_CTRL_11 635 
#define  ARIZONA_AIF3_FRAME_CTRL_12 634 
#define  ARIZONA_AIF3_FRAME_CTRL_2 633 
#define  ARIZONA_AIF3_FRAME_CTRL_3 632 
#define  ARIZONA_AIF3_FRAME_CTRL_4 631 
#define  ARIZONA_AIF3_RATE_CTRL 630 
#define  ARIZONA_AIF3_RX_BCLK_RATE 629 
#define  ARIZONA_AIF3_RX_ENABLES 628 
#define  ARIZONA_AIF3_RX_PIN_CTRL 627 
#define  ARIZONA_AIF3_TX_BCLK_RATE 626 
#define  ARIZONA_AIF3_TX_ENABLES 625 
#define  ARIZONA_AIF3_TX_PIN_CTRL 624 
#define  ARIZONA_ASRC1LMIX_INPUT_1_SOURCE 623 
#define  ARIZONA_ASRC1RMIX_INPUT_1_SOURCE 622 
#define  ARIZONA_ASRC2LMIX_INPUT_1_SOURCE 621 
#define  ARIZONA_ASRC2RMIX_INPUT_1_SOURCE 620 
#define  ARIZONA_ASRC_ENABLE 619 
#define  ARIZONA_ASRC_RATE1 618 
#define  ARIZONA_ASRC_RATE2 617 
#define  ARIZONA_ASRC_STATUS 616 
#define  ARIZONA_ASYNC_CLOCK_1 615 
#define  ARIZONA_ASYNC_SAMPLE_RATE_1 614 
#define  ARIZONA_ASYNC_SAMPLE_RATE_1_STATUS 613 
#define  ARIZONA_ASYNC_SAMPLE_RATE_2 612 
#define  ARIZONA_ASYNC_SAMPLE_RATE_2_STATUS 611 
#define  ARIZONA_CLOCK_32K_1 610 
#define  ARIZONA_COMFORT_NOISE_GENERATOR 609 
#define  ARIZONA_CTRL_IF_SPI_CFG_1 608 
#define  ARIZONA_DAC_AEC_CONTROL_1 607 
#define  ARIZONA_DAC_DIGITAL_VOLUME_1L 606 
#define  ARIZONA_DAC_DIGITAL_VOLUME_1R 605 
#define  ARIZONA_DAC_DIGITAL_VOLUME_4L 604 
#define  ARIZONA_DAC_VOLUME_LIMIT_1L 603 
#define  ARIZONA_DAC_VOLUME_LIMIT_1R 602 
#define  ARIZONA_DEVICE_REVISION 601 
#define  ARIZONA_DMIC1L_CONTROL 600 
#define  ARIZONA_DMIC1R_CONTROL 599 
#define  ARIZONA_DMIC2L_CONTROL 598 
#define  ARIZONA_DMIC2R_CONTROL 597 
#define  ARIZONA_DRC1LMIX_INPUT_1_SOURCE 596 
#define  ARIZONA_DRC1LMIX_INPUT_1_VOLUME 595 
#define  ARIZONA_DRC1LMIX_INPUT_2_SOURCE 594 
#define  ARIZONA_DRC1LMIX_INPUT_2_VOLUME 593 
#define  ARIZONA_DRC1LMIX_INPUT_3_SOURCE 592 
#define  ARIZONA_DRC1LMIX_INPUT_3_VOLUME 591 
#define  ARIZONA_DRC1LMIX_INPUT_4_SOURCE 590 
#define  ARIZONA_DRC1LMIX_INPUT_4_VOLUME 589 
#define  ARIZONA_DRC1RMIX_INPUT_1_SOURCE 588 
#define  ARIZONA_DRC1RMIX_INPUT_1_VOLUME 587 
#define  ARIZONA_DRC1RMIX_INPUT_2_SOURCE 586 
#define  ARIZONA_DRC1RMIX_INPUT_2_VOLUME 585 
#define  ARIZONA_DRC1RMIX_INPUT_3_SOURCE 584 
#define  ARIZONA_DRC1RMIX_INPUT_3_VOLUME 583 
#define  ARIZONA_DRC1RMIX_INPUT_4_SOURCE 582 
#define  ARIZONA_DRC1RMIX_INPUT_4_VOLUME 581 
#define  ARIZONA_DRC1_CTRL1 580 
#define  ARIZONA_DRC1_CTRL2 579 
#define  ARIZONA_DRC1_CTRL3 578 
#define  ARIZONA_DRC1_CTRL4 577 
#define  ARIZONA_DRC1_CTRL5 576 
#define  ARIZONA_DRC2LMIX_INPUT_1_SOURCE 575 
#define  ARIZONA_DRC2LMIX_INPUT_1_VOLUME 574 
#define  ARIZONA_DRC2LMIX_INPUT_2_SOURCE 573 
#define  ARIZONA_DRC2LMIX_INPUT_2_VOLUME 572 
#define  ARIZONA_DRC2LMIX_INPUT_3_SOURCE 571 
#define  ARIZONA_DRC2LMIX_INPUT_3_VOLUME 570 
#define  ARIZONA_DRC2LMIX_INPUT_4_SOURCE 569 
#define  ARIZONA_DRC2LMIX_INPUT_4_VOLUME 568 
#define  ARIZONA_DRC2RMIX_INPUT_1_SOURCE 567 
#define  ARIZONA_DRC2RMIX_INPUT_1_VOLUME 566 
#define  ARIZONA_DRC2RMIX_INPUT_2_SOURCE 565 
#define  ARIZONA_DRC2RMIX_INPUT_2_VOLUME 564 
#define  ARIZONA_DRC2RMIX_INPUT_3_SOURCE 563 
#define  ARIZONA_DRC2RMIX_INPUT_3_VOLUME 562 
#define  ARIZONA_DRC2RMIX_INPUT_4_SOURCE 561 
#define  ARIZONA_DRC2RMIX_INPUT_4_VOLUME 560 
#define  ARIZONA_DRC2_CTRL1 559 
#define  ARIZONA_DRC2_CTRL2 558 
#define  ARIZONA_DRC2_CTRL3 557 
#define  ARIZONA_DRC2_CTRL4 556 
#define  ARIZONA_DRC2_CTRL5 555 
#define  ARIZONA_DSP2AUX1MIX_INPUT_1_SOURCE 554 
#define  ARIZONA_DSP2AUX2MIX_INPUT_1_SOURCE 553 
#define  ARIZONA_DSP2AUX3MIX_INPUT_1_SOURCE 552 
#define  ARIZONA_DSP2AUX4MIX_INPUT_1_SOURCE 551 
#define  ARIZONA_DSP2AUX5MIX_INPUT_1_SOURCE 550 
#define  ARIZONA_DSP2AUX6MIX_INPUT_1_SOURCE 549 
#define  ARIZONA_DSP2LMIX_INPUT_1_SOURCE 548 
#define  ARIZONA_DSP2LMIX_INPUT_1_VOLUME 547 
#define  ARIZONA_DSP2LMIX_INPUT_2_SOURCE 546 
#define  ARIZONA_DSP2LMIX_INPUT_2_VOLUME 545 
#define  ARIZONA_DSP2LMIX_INPUT_3_SOURCE 544 
#define  ARIZONA_DSP2LMIX_INPUT_3_VOLUME 543 
#define  ARIZONA_DSP2LMIX_INPUT_4_SOURCE 542 
#define  ARIZONA_DSP2LMIX_INPUT_4_VOLUME 541 
#define  ARIZONA_DSP2RMIX_INPUT_1_SOURCE 540 
#define  ARIZONA_DSP2RMIX_INPUT_1_VOLUME 539 
#define  ARIZONA_DSP2RMIX_INPUT_2_SOURCE 538 
#define  ARIZONA_DSP2RMIX_INPUT_2_VOLUME 537 
#define  ARIZONA_DSP2RMIX_INPUT_3_SOURCE 536 
#define  ARIZONA_DSP2RMIX_INPUT_3_VOLUME 535 
#define  ARIZONA_DSP2RMIX_INPUT_4_SOURCE 534 
#define  ARIZONA_DSP2RMIX_INPUT_4_VOLUME 533 
#define  ARIZONA_DSP2_CLOCKING_1 532 
#define  ARIZONA_DSP2_CONTROL_1 531 
#define  ARIZONA_DSP2_EXTERNAL_START_SELECT_1 530 
#define  ARIZONA_DSP2_RDMA_BUFFER_1 529 
#define  ARIZONA_DSP2_RDMA_BUFFER_2 528 
#define  ARIZONA_DSP2_RDMA_BUFFER_3 527 
#define  ARIZONA_DSP2_RDMA_BUFFER_4 526 
#define  ARIZONA_DSP2_RDMA_BUFFER_5 525 
#define  ARIZONA_DSP2_RDMA_BUFFER_6 524 
#define  ARIZONA_DSP2_RDMA_CONFIG_1 523 
#define  ARIZONA_DSP2_RDMA_OFFSET_1 522 
#define  ARIZONA_DSP2_SCRATCH_0 521 
#define  ARIZONA_DSP2_SCRATCH_1 520 
#define  ARIZONA_DSP2_SCRATCH_2 519 
#define  ARIZONA_DSP2_SCRATCH_3 518 
#define  ARIZONA_DSP2_STATUS_1 517 
#define  ARIZONA_DSP2_STATUS_2 516 
#define  ARIZONA_DSP2_STATUS_3 515 
#define  ARIZONA_DSP2_STATUS_4 514 
#define  ARIZONA_DSP2_WDMA_BUFFER_1 513 
#define  ARIZONA_DSP2_WDMA_BUFFER_2 512 
#define  ARIZONA_DSP2_WDMA_BUFFER_3 511 
#define  ARIZONA_DSP2_WDMA_BUFFER_4 510 
#define  ARIZONA_DSP2_WDMA_BUFFER_5 509 
#define  ARIZONA_DSP2_WDMA_BUFFER_6 508 
#define  ARIZONA_DSP2_WDMA_BUFFER_7 507 
#define  ARIZONA_DSP2_WDMA_BUFFER_8 506 
#define  ARIZONA_DSP2_WDMA_CONFIG_1 505 
#define  ARIZONA_DSP2_WDMA_CONFIG_2 504 
#define  ARIZONA_DSP2_WDMA_OFFSET_1 503 
#define  ARIZONA_DSP3AUX1MIX_INPUT_1_SOURCE 502 
#define  ARIZONA_DSP3AUX2MIX_INPUT_1_SOURCE 501 
#define  ARIZONA_DSP3AUX3MIX_INPUT_1_SOURCE 500 
#define  ARIZONA_DSP3AUX4MIX_INPUT_1_SOURCE 499 
#define  ARIZONA_DSP3AUX5MIX_INPUT_1_SOURCE 498 
#define  ARIZONA_DSP3AUX6MIX_INPUT_1_SOURCE 497 
#define  ARIZONA_DSP3LMIX_INPUT_1_SOURCE 496 
#define  ARIZONA_DSP3LMIX_INPUT_1_VOLUME 495 
#define  ARIZONA_DSP3LMIX_INPUT_2_SOURCE 494 
#define  ARIZONA_DSP3LMIX_INPUT_2_VOLUME 493 
#define  ARIZONA_DSP3LMIX_INPUT_3_SOURCE 492 
#define  ARIZONA_DSP3LMIX_INPUT_3_VOLUME 491 
#define  ARIZONA_DSP3LMIX_INPUT_4_SOURCE 490 
#define  ARIZONA_DSP3LMIX_INPUT_4_VOLUME 489 
#define  ARIZONA_DSP3RMIX_INPUT_1_SOURCE 488 
#define  ARIZONA_DSP3RMIX_INPUT_1_VOLUME 487 
#define  ARIZONA_DSP3RMIX_INPUT_2_SOURCE 486 
#define  ARIZONA_DSP3RMIX_INPUT_2_VOLUME 485 
#define  ARIZONA_DSP3RMIX_INPUT_3_SOURCE 484 
#define  ARIZONA_DSP3RMIX_INPUT_3_VOLUME 483 
#define  ARIZONA_DSP3RMIX_INPUT_4_SOURCE 482 
#define  ARIZONA_DSP3RMIX_INPUT_4_VOLUME 481 
#define  ARIZONA_DSP3_CLOCKING_1 480 
#define  ARIZONA_DSP3_CONTROL_1 479 
#define  ARIZONA_DSP3_EXTERNAL_START_SELECT_1 478 
#define  ARIZONA_DSP3_RDMA_BUFFER_1 477 
#define  ARIZONA_DSP3_RDMA_BUFFER_2 476 
#define  ARIZONA_DSP3_RDMA_BUFFER_3 475 
#define  ARIZONA_DSP3_RDMA_BUFFER_4 474 
#define  ARIZONA_DSP3_RDMA_BUFFER_5 473 
#define  ARIZONA_DSP3_RDMA_BUFFER_6 472 
#define  ARIZONA_DSP3_RDMA_CONFIG_1 471 
#define  ARIZONA_DSP3_RDMA_OFFSET_1 470 
#define  ARIZONA_DSP3_SCRATCH_0 469 
#define  ARIZONA_DSP3_SCRATCH_1 468 
#define  ARIZONA_DSP3_SCRATCH_2 467 
#define  ARIZONA_DSP3_SCRATCH_3 466 
#define  ARIZONA_DSP3_STATUS_1 465 
#define  ARIZONA_DSP3_STATUS_2 464 
#define  ARIZONA_DSP3_STATUS_3 463 
#define  ARIZONA_DSP3_STATUS_4 462 
#define  ARIZONA_DSP3_WDMA_BUFFER_1 461 
#define  ARIZONA_DSP3_WDMA_BUFFER_2 460 
#define  ARIZONA_DSP3_WDMA_BUFFER_3 459 
#define  ARIZONA_DSP3_WDMA_BUFFER_4 458 
#define  ARIZONA_DSP3_WDMA_BUFFER_5 457 
#define  ARIZONA_DSP3_WDMA_BUFFER_6 456 
#define  ARIZONA_DSP3_WDMA_BUFFER_7 455 
#define  ARIZONA_DSP3_WDMA_BUFFER_8 454 
#define  ARIZONA_DSP3_WDMA_CONFIG_1 453 
#define  ARIZONA_DSP3_WDMA_CONFIG_2 452 
#define  ARIZONA_DSP3_WDMA_OFFSET_1 451 
#define  ARIZONA_EQ1MIX_INPUT_1_SOURCE 450 
#define  ARIZONA_EQ1MIX_INPUT_1_VOLUME 449 
#define  ARIZONA_EQ1MIX_INPUT_2_SOURCE 448 
#define  ARIZONA_EQ1MIX_INPUT_2_VOLUME 447 
#define  ARIZONA_EQ1MIX_INPUT_3_SOURCE 446 
#define  ARIZONA_EQ1MIX_INPUT_3_VOLUME 445 
#define  ARIZONA_EQ1MIX_INPUT_4_SOURCE 444 
#define  ARIZONA_EQ1MIX_INPUT_4_VOLUME 443 
#define  ARIZONA_EQ1_1 442 
#define  ARIZONA_EQ1_10 441 
#define  ARIZONA_EQ1_11 440 
#define  ARIZONA_EQ1_12 439 
#define  ARIZONA_EQ1_13 438 
#define  ARIZONA_EQ1_14 437 
#define  ARIZONA_EQ1_15 436 
#define  ARIZONA_EQ1_16 435 
#define  ARIZONA_EQ1_17 434 
#define  ARIZONA_EQ1_18 433 
#define  ARIZONA_EQ1_19 432 
#define  ARIZONA_EQ1_2 431 
#define  ARIZONA_EQ1_20 430 
#define  ARIZONA_EQ1_21 429 
#define  ARIZONA_EQ1_3 428 
#define  ARIZONA_EQ1_4 427 
#define  ARIZONA_EQ1_5 426 
#define  ARIZONA_EQ1_6 425 
#define  ARIZONA_EQ1_7 424 
#define  ARIZONA_EQ1_8 423 
#define  ARIZONA_EQ1_9 422 
#define  ARIZONA_EQ2MIX_INPUT_1_SOURCE 421 
#define  ARIZONA_EQ2MIX_INPUT_1_VOLUME 420 
#define  ARIZONA_EQ2MIX_INPUT_2_SOURCE 419 
#define  ARIZONA_EQ2MIX_INPUT_2_VOLUME 418 
#define  ARIZONA_EQ2MIX_INPUT_3_SOURCE 417 
#define  ARIZONA_EQ2MIX_INPUT_3_VOLUME 416 
#define  ARIZONA_EQ2MIX_INPUT_4_SOURCE 415 
#define  ARIZONA_EQ2MIX_INPUT_4_VOLUME 414 
#define  ARIZONA_EQ2_1 413 
#define  ARIZONA_EQ2_10 412 
#define  ARIZONA_EQ2_11 411 
#define  ARIZONA_EQ2_12 410 
#define  ARIZONA_EQ2_13 409 
#define  ARIZONA_EQ2_14 408 
#define  ARIZONA_EQ2_15 407 
#define  ARIZONA_EQ2_16 406 
#define  ARIZONA_EQ2_17 405 
#define  ARIZONA_EQ2_18 404 
#define  ARIZONA_EQ2_19 403 
#define  ARIZONA_EQ2_2 402 
#define  ARIZONA_EQ2_20 401 
#define  ARIZONA_EQ2_21 400 
#define  ARIZONA_EQ2_3 399 
#define  ARIZONA_EQ2_4 398 
#define  ARIZONA_EQ2_5 397 
#define  ARIZONA_EQ2_6 396 
#define  ARIZONA_EQ2_7 395 
#define  ARIZONA_EQ2_8 394 
#define  ARIZONA_EQ2_9 393 
#define  ARIZONA_FLL1_CONTROL_1 392 
#define  ARIZONA_FLL1_CONTROL_2 391 
#define  ARIZONA_FLL1_CONTROL_3 390 
#define  ARIZONA_FLL1_CONTROL_4 389 
#define  ARIZONA_FLL1_CONTROL_5 388 
#define  ARIZONA_FLL1_CONTROL_6 387 
#define  ARIZONA_FLL1_CONTROL_7 386 
#define  ARIZONA_FLL1_GPIO_CLOCK 385 
#define  ARIZONA_FLL1_SPREAD_SPECTRUM 384 
#define  ARIZONA_FLL1_SYNCHRONISER_1 383 
#define  ARIZONA_FLL1_SYNCHRONISER_2 382 
#define  ARIZONA_FLL1_SYNCHRONISER_3 381 
#define  ARIZONA_FLL1_SYNCHRONISER_4 380 
#define  ARIZONA_FLL1_SYNCHRONISER_5 379 
#define  ARIZONA_FLL1_SYNCHRONISER_6 378 
#define  ARIZONA_FLL1_SYNCHRONISER_7 377 
#define  ARIZONA_FLL2_CONTROL_1 376 
#define  ARIZONA_FLL2_CONTROL_2 375 
#define  ARIZONA_FLL2_CONTROL_3 374 
#define  ARIZONA_FLL2_CONTROL_4 373 
#define  ARIZONA_FLL2_CONTROL_5 372 
#define  ARIZONA_FLL2_CONTROL_6 371 
#define  ARIZONA_FLL2_CONTROL_7 370 
#define  ARIZONA_FLL2_GPIO_CLOCK 369 
#define  ARIZONA_FLL2_SPREAD_SPECTRUM 368 
#define  ARIZONA_FLL2_SYNCHRONISER_1 367 
#define  ARIZONA_FLL2_SYNCHRONISER_2 366 
#define  ARIZONA_FLL2_SYNCHRONISER_3 365 
#define  ARIZONA_FLL2_SYNCHRONISER_4 364 
#define  ARIZONA_FLL2_SYNCHRONISER_5 363 
#define  ARIZONA_FLL2_SYNCHRONISER_6 362 
#define  ARIZONA_FLL2_SYNCHRONISER_7 361 
#define  ARIZONA_FX_CTRL1 360 
#define  ARIZONA_FX_CTRL2 359 
#define  ARIZONA_GPIO1_CTRL 358 
#define  ARIZONA_GPIO2_CTRL 357 
#define  ARIZONA_GPIO_DEBOUNCE_CONFIG 356 
#define  ARIZONA_HAPTICS_CONTROL_1 355 
#define  ARIZONA_HAPTICS_CONTROL_2 354 
#define  ARIZONA_HAPTICS_PHASE_1_DURATION 353 
#define  ARIZONA_HAPTICS_PHASE_1_INTENSITY 352 
#define  ARIZONA_HAPTICS_PHASE_2_DURATION 351 
#define  ARIZONA_HAPTICS_PHASE_2_INTENSITY 350 
#define  ARIZONA_HAPTICS_PHASE_3_DURATION 349 
#define  ARIZONA_HAPTICS_PHASE_3_INTENSITY 348 
#define  ARIZONA_HAPTICS_STATUS 347 
#define  ARIZONA_HP1_SHORT_CIRCUIT_CTRL 346 
#define  ARIZONA_HPF_CONTROL 345 
#define  ARIZONA_HPLP1MIX_INPUT_1_SOURCE 344 
#define  ARIZONA_HPLP1MIX_INPUT_1_VOLUME 343 
#define  ARIZONA_HPLP1MIX_INPUT_2_SOURCE 342 
#define  ARIZONA_HPLP1MIX_INPUT_2_VOLUME 341 
#define  ARIZONA_HPLP1MIX_INPUT_3_SOURCE 340 
#define  ARIZONA_HPLP1MIX_INPUT_3_VOLUME 339 
#define  ARIZONA_HPLP1MIX_INPUT_4_SOURCE 338 
#define  ARIZONA_HPLP1MIX_INPUT_4_VOLUME 337 
#define  ARIZONA_HPLP2MIX_INPUT_1_SOURCE 336 
#define  ARIZONA_HPLP2MIX_INPUT_1_VOLUME 335 
#define  ARIZONA_HPLP2MIX_INPUT_2_SOURCE 334 
#define  ARIZONA_HPLP2MIX_INPUT_2_VOLUME 333 
#define  ARIZONA_HPLP2MIX_INPUT_3_SOURCE 332 
#define  ARIZONA_HPLP2MIX_INPUT_3_VOLUME 331 
#define  ARIZONA_HPLP2MIX_INPUT_4_SOURCE 330 
#define  ARIZONA_HPLP2MIX_INPUT_4_VOLUME 329 
#define  ARIZONA_HPLP3MIX_INPUT_1_SOURCE 328 
#define  ARIZONA_HPLP3MIX_INPUT_1_VOLUME 327 
#define  ARIZONA_HPLP3MIX_INPUT_2_SOURCE 326 
#define  ARIZONA_HPLP3MIX_INPUT_2_VOLUME 325 
#define  ARIZONA_HPLP3MIX_INPUT_3_SOURCE 324 
#define  ARIZONA_HPLP3MIX_INPUT_3_VOLUME 323 
#define  ARIZONA_HPLP3MIX_INPUT_4_SOURCE 322 
#define  ARIZONA_HPLP3MIX_INPUT_4_VOLUME 321 
#define  ARIZONA_HPLP4MIX_INPUT_1_SOURCE 320 
#define  ARIZONA_HPLP4MIX_INPUT_1_VOLUME 319 
#define  ARIZONA_HPLP4MIX_INPUT_2_SOURCE 318 
#define  ARIZONA_HPLP4MIX_INPUT_2_VOLUME 317 
#define  ARIZONA_HPLP4MIX_INPUT_3_SOURCE 316 
#define  ARIZONA_HPLP4MIX_INPUT_3_VOLUME 315 
#define  ARIZONA_HPLP4MIX_INPUT_4_SOURCE 314 
#define  ARIZONA_HPLP4MIX_INPUT_4_VOLUME 313 
#define  ARIZONA_HPLPF1_1 312 
#define  ARIZONA_HPLPF1_2 311 
#define  ARIZONA_HPLPF2_1 310 
#define  ARIZONA_HPLPF2_2 309 
#define  ARIZONA_HPLPF3_1 308 
#define  ARIZONA_HPLPF3_2 307 
#define  ARIZONA_HPLPF4_1 306 
#define  ARIZONA_HPLPF4_2 305 
#define  ARIZONA_HP_CTRL_1L 304 
#define  ARIZONA_HP_CTRL_1R 303 
#define  ARIZONA_IN1L_CONTROL 302 
#define  ARIZONA_IN1R_CONTROL 301 
#define  ARIZONA_IN2L_CONTROL 300 
#define  ARIZONA_IN2R_CONTROL 299 
#define  ARIZONA_INPUT_ENABLES 298 
#define  ARIZONA_INPUT_ENABLES_STATUS 297 
#define  ARIZONA_INPUT_RATE 296 
#define  ARIZONA_INPUT_VOLUME_RAMP 295 
#define  ARIZONA_INTERRUPT_CONTROL 294 
#define  ARIZONA_INTERRUPT_RAW_STATUS_2 293 
#define  ARIZONA_INTERRUPT_RAW_STATUS_3 292 
#define  ARIZONA_INTERRUPT_RAW_STATUS_4 291 
#define  ARIZONA_INTERRUPT_RAW_STATUS_5 290 
#define  ARIZONA_INTERRUPT_RAW_STATUS_6 289 
#define  ARIZONA_INTERRUPT_RAW_STATUS_7 288 
#define  ARIZONA_INTERRUPT_RAW_STATUS_8 287 
#define  ARIZONA_INTERRUPT_RAW_STATUS_9 286 
#define  ARIZONA_INTERRUPT_STATUS_1 285 
#define  ARIZONA_INTERRUPT_STATUS_1_MASK 284 
#define  ARIZONA_INTERRUPT_STATUS_2 283 
#define  ARIZONA_INTERRUPT_STATUS_2_MASK 282 
#define  ARIZONA_INTERRUPT_STATUS_3 281 
#define  ARIZONA_INTERRUPT_STATUS_3_MASK 280 
#define  ARIZONA_INTERRUPT_STATUS_4 279 
#define  ARIZONA_INTERRUPT_STATUS_4_MASK 278 
#define  ARIZONA_INTERRUPT_STATUS_5 277 
#define  ARIZONA_INTERRUPT_STATUS_5_MASK 276 
#define  ARIZONA_INTERRUPT_STATUS_6 275 
#define  ARIZONA_INTERRUPT_STATUS_6_MASK 274 
#define  ARIZONA_IRQ2_CONTROL 273 
#define  ARIZONA_IRQ2_STATUS_1 272 
#define  ARIZONA_IRQ2_STATUS_1_MASK 271 
#define  ARIZONA_IRQ2_STATUS_2 270 
#define  ARIZONA_IRQ2_STATUS_2_MASK 269 
#define  ARIZONA_IRQ2_STATUS_3 268 
#define  ARIZONA_IRQ2_STATUS_3_MASK 267 
#define  ARIZONA_IRQ2_STATUS_4 266 
#define  ARIZONA_IRQ2_STATUS_4_MASK 265 
#define  ARIZONA_IRQ2_STATUS_5 264 
#define  ARIZONA_IRQ2_STATUS_5_MASK 263 
#define  ARIZONA_IRQ2_STATUS_6 262 
#define  ARIZONA_IRQ2_STATUS_6_MASK 261 
#define  ARIZONA_IRQ_CTRL_1 260 
#define  ARIZONA_IRQ_PIN_STATUS 259 
#define  ARIZONA_ISRC1DEC1MIX_INPUT_1_SOURCE 258 
#define  ARIZONA_ISRC1DEC2MIX_INPUT_1_SOURCE 257 
#define  ARIZONA_ISRC1DEC3MIX_INPUT_1_SOURCE 256 
#define  ARIZONA_ISRC1DEC4MIX_INPUT_1_SOURCE 255 
#define  ARIZONA_ISRC1INT1MIX_INPUT_1_SOURCE 254 
#define  ARIZONA_ISRC1INT2MIX_INPUT_1_SOURCE 253 
#define  ARIZONA_ISRC1INT3MIX_INPUT_1_SOURCE 252 
#define  ARIZONA_ISRC1INT4MIX_INPUT_1_SOURCE 251 
#define  ARIZONA_ISRC2DEC1MIX_INPUT_1_SOURCE 250 
#define  ARIZONA_ISRC2DEC2MIX_INPUT_1_SOURCE 249 
#define  ARIZONA_ISRC2DEC3MIX_INPUT_1_SOURCE 248 
#define  ARIZONA_ISRC2DEC4MIX_INPUT_1_SOURCE 247 
#define  ARIZONA_ISRC2INT1MIX_INPUT_1_SOURCE 246 
#define  ARIZONA_ISRC2INT2MIX_INPUT_1_SOURCE 245 
#define  ARIZONA_ISRC2INT3MIX_INPUT_1_SOURCE 244 
#define  ARIZONA_ISRC2INT4MIX_INPUT_1_SOURCE 243 
#define  ARIZONA_ISRC3DEC1MIX_INPUT_1_SOURCE 242 
#define  ARIZONA_ISRC3DEC2MIX_INPUT_1_SOURCE 241 
#define  ARIZONA_ISRC3DEC3MIX_INPUT_1_SOURCE 240 
#define  ARIZONA_ISRC3DEC4MIX_INPUT_1_SOURCE 239 
#define  ARIZONA_ISRC3INT1MIX_INPUT_1_SOURCE 238 
#define  ARIZONA_ISRC3INT2MIX_INPUT_1_SOURCE 237 
#define  ARIZONA_ISRC3INT3MIX_INPUT_1_SOURCE 236 
#define  ARIZONA_ISRC3INT4MIX_INPUT_1_SOURCE 235 
#define  ARIZONA_ISRC_1_CTRL_1 234 
#define  ARIZONA_ISRC_1_CTRL_2 233 
#define  ARIZONA_ISRC_1_CTRL_3 232 
#define  ARIZONA_ISRC_2_CTRL_1 231 
#define  ARIZONA_ISRC_2_CTRL_2 230 
#define  ARIZONA_ISRC_2_CTRL_3 229 
#define  ARIZONA_ISRC_3_CTRL_1 228 
#define  ARIZONA_ISRC_3_CTRL_2 227 
#define  ARIZONA_ISRC_3_CTRL_3 226 
#define  ARIZONA_MIC_BIAS_CTRL_1 225 
#define  ARIZONA_MIC_BIAS_CTRL_2 224 
#define  ARIZONA_MISC_PAD_CTRL_1 223 
#define  ARIZONA_MISC_PAD_CTRL_10 222 
#define  ARIZONA_MISC_PAD_CTRL_11 221 
#define  ARIZONA_MISC_PAD_CTRL_12 220 
#define  ARIZONA_MISC_PAD_CTRL_13 219 
#define  ARIZONA_MISC_PAD_CTRL_14 218 
#define  ARIZONA_MISC_PAD_CTRL_16 217 
#define  ARIZONA_MISC_PAD_CTRL_2 216 
#define  ARIZONA_MISC_PAD_CTRL_3 215 
#define  ARIZONA_MISC_PAD_CTRL_4 214 
#define  ARIZONA_MISC_PAD_CTRL_5 213 
#define  ARIZONA_MISC_PAD_CTRL_6 212 
#define  ARIZONA_MISC_PAD_CTRL_7 211 
#define  ARIZONA_MISC_PAD_CTRL_9 210 
#define  ARIZONA_NOISE_GATE_CONTROL 209 
#define  ARIZONA_NOISE_GATE_SELECT_1L 208 
#define  ARIZONA_NOISE_GATE_SELECT_1R 207 
#define  ARIZONA_NOISE_GATE_SELECT_4L 206 
#define  ARIZONA_OUT1LMIX_INPUT_1_SOURCE 205 
#define  ARIZONA_OUT1LMIX_INPUT_1_VOLUME 204 
#define  ARIZONA_OUT1LMIX_INPUT_2_SOURCE 203 
#define  ARIZONA_OUT1LMIX_INPUT_2_VOLUME 202 
#define  ARIZONA_OUT1LMIX_INPUT_3_SOURCE 201 
#define  ARIZONA_OUT1LMIX_INPUT_3_VOLUME 200 
#define  ARIZONA_OUT1LMIX_INPUT_4_SOURCE 199 
#define  ARIZONA_OUT1LMIX_INPUT_4_VOLUME 198 
#define  ARIZONA_OUT1RMIX_INPUT_1_SOURCE 197 
#define  ARIZONA_OUT1RMIX_INPUT_1_VOLUME 196 
#define  ARIZONA_OUT1RMIX_INPUT_2_SOURCE 195 
#define  ARIZONA_OUT1RMIX_INPUT_2_VOLUME 194 
#define  ARIZONA_OUT1RMIX_INPUT_3_SOURCE 193 
#define  ARIZONA_OUT1RMIX_INPUT_3_VOLUME 192 
#define  ARIZONA_OUT1RMIX_INPUT_4_SOURCE 191 
#define  ARIZONA_OUT1RMIX_INPUT_4_VOLUME 190 
#define  ARIZONA_OUT4LMIX_INPUT_1_SOURCE 189 
#define  ARIZONA_OUT4LMIX_INPUT_1_VOLUME 188 
#define  ARIZONA_OUT4LMIX_INPUT_2_SOURCE 187 
#define  ARIZONA_OUT4LMIX_INPUT_2_VOLUME 186 
#define  ARIZONA_OUT4LMIX_INPUT_3_SOURCE 185 
#define  ARIZONA_OUT4LMIX_INPUT_3_VOLUME 184 
#define  ARIZONA_OUT4LMIX_INPUT_4_SOURCE 183 
#define  ARIZONA_OUT4LMIX_INPUT_4_VOLUME 182 
#define  ARIZONA_OUTPUT_ASYNC_CLOCK 181 
#define  ARIZONA_OUTPUT_ENABLES_1 180 
#define  ARIZONA_OUTPUT_PATH_CONFIG_1L 179 
#define  ARIZONA_OUTPUT_RATE_1 178 
#define  ARIZONA_OUTPUT_STATUS_1 177 
#define  ARIZONA_OUTPUT_SYSTEM_CLOCK 176 
#define  ARIZONA_OUTPUT_VOLUME_RAMP 175 
#define  ARIZONA_OUT_VOLUME_4L 174 
#define  ARIZONA_PWM1MIX_INPUT_1_SOURCE 173 
#define  ARIZONA_PWM1MIX_INPUT_1_VOLUME 172 
#define  ARIZONA_PWM1MIX_INPUT_2_SOURCE 171 
#define  ARIZONA_PWM1MIX_INPUT_2_VOLUME 170 
#define  ARIZONA_PWM1MIX_INPUT_3_SOURCE 169 
#define  ARIZONA_PWM1MIX_INPUT_3_VOLUME 168 
#define  ARIZONA_PWM1MIX_INPUT_4_SOURCE 167 
#define  ARIZONA_PWM1MIX_INPUT_4_VOLUME 166 
#define  ARIZONA_PWM2MIX_INPUT_1_SOURCE 165 
#define  ARIZONA_PWM2MIX_INPUT_1_VOLUME 164 
#define  ARIZONA_PWM2MIX_INPUT_2_SOURCE 163 
#define  ARIZONA_PWM2MIX_INPUT_2_VOLUME 162 
#define  ARIZONA_PWM2MIX_INPUT_3_SOURCE 161 
#define  ARIZONA_PWM2MIX_INPUT_3_VOLUME 160 
#define  ARIZONA_PWM2MIX_INPUT_4_SOURCE 159 
#define  ARIZONA_PWM2MIX_INPUT_4_VOLUME 158 
#define  ARIZONA_PWM_DRIVE_1 157 
#define  ARIZONA_PWM_DRIVE_2 156 
#define  ARIZONA_PWM_DRIVE_3 155 
#define  ARIZONA_RATE_ESTIMATOR_1 154 
#define  ARIZONA_RATE_ESTIMATOR_2 153 
#define  ARIZONA_RATE_ESTIMATOR_3 152 
#define  ARIZONA_RATE_ESTIMATOR_4 151 
#define  ARIZONA_RATE_ESTIMATOR_5 150 
#define  ARIZONA_RAW_OUTPUT_STATUS_1 149 
#define  ARIZONA_SAMPLE_RATE_1 148 
#define  ARIZONA_SAMPLE_RATE_1_STATUS 147 
#define  ARIZONA_SAMPLE_RATE_2 146 
#define  ARIZONA_SAMPLE_RATE_2_STATUS 145 
#define  ARIZONA_SAMPLE_RATE_3 144 
#define  ARIZONA_SAMPLE_RATE_3_STATUS 143 
#define  ARIZONA_SAMPLE_RATE_SEQUENCE_SELECT_1 142 
#define  ARIZONA_SAMPLE_RATE_SEQUENCE_SELECT_2 141 
#define  ARIZONA_SAMPLE_RATE_SEQUENCE_SELECT_3 140 
#define  ARIZONA_SAMPLE_RATE_SEQUENCE_SELECT_4 139 
#define  ARIZONA_SEQUENCE_CONTROL 138 
#define  ARIZONA_SOFTWARE_RESET 137 
#define  ARIZONA_SYSTEM_CLOCK_1 136 
#define  ARIZONA_TONE_GENERATOR_1 135 
#define  ARIZONA_TONE_GENERATOR_2 134 
#define  ARIZONA_TONE_GENERATOR_3 133 
#define  ARIZONA_TONE_GENERATOR_4 132 
#define  ARIZONA_TONE_GENERATOR_5 131 
#define  ARIZONA_WRITE_SEQUENCER_CTRL_0 130 
#define  ARIZONA_WRITE_SEQUENCER_CTRL_1 129 
#define  ARIZONA_WRITE_SEQUENCER_CTRL_2 128 
 int cs47l24_is_adsp_memory (unsigned int) ; 

__attribute__((used)) static bool cs47l24_readable_register(struct device *dev, unsigned int reg)
{
	switch (reg) {
	case ARIZONA_SOFTWARE_RESET:
	case ARIZONA_DEVICE_REVISION:
	case ARIZONA_CTRL_IF_SPI_CFG_1:
	case ARIZONA_WRITE_SEQUENCER_CTRL_0:
	case ARIZONA_WRITE_SEQUENCER_CTRL_1:
	case ARIZONA_WRITE_SEQUENCER_CTRL_2:
	case ARIZONA_TONE_GENERATOR_1:
	case ARIZONA_TONE_GENERATOR_2:
	case ARIZONA_TONE_GENERATOR_3:
	case ARIZONA_TONE_GENERATOR_4:
	case ARIZONA_TONE_GENERATOR_5:
	case ARIZONA_PWM_DRIVE_1:
	case ARIZONA_PWM_DRIVE_2:
	case ARIZONA_PWM_DRIVE_3:
	case ARIZONA_SEQUENCE_CONTROL:
	case ARIZONA_SAMPLE_RATE_SEQUENCE_SELECT_1:
	case ARIZONA_SAMPLE_RATE_SEQUENCE_SELECT_2:
	case ARIZONA_SAMPLE_RATE_SEQUENCE_SELECT_3:
	case ARIZONA_SAMPLE_RATE_SEQUENCE_SELECT_4:
	case ARIZONA_COMFORT_NOISE_GENERATOR:
	case ARIZONA_HAPTICS_CONTROL_1:
	case ARIZONA_HAPTICS_CONTROL_2:
	case ARIZONA_HAPTICS_PHASE_1_INTENSITY:
	case ARIZONA_HAPTICS_PHASE_1_DURATION:
	case ARIZONA_HAPTICS_PHASE_2_INTENSITY:
	case ARIZONA_HAPTICS_PHASE_2_DURATION:
	case ARIZONA_HAPTICS_PHASE_3_INTENSITY:
	case ARIZONA_HAPTICS_PHASE_3_DURATION:
	case ARIZONA_HAPTICS_STATUS:
	case ARIZONA_CLOCK_32K_1:
	case ARIZONA_SYSTEM_CLOCK_1:
	case ARIZONA_SAMPLE_RATE_1:
	case ARIZONA_SAMPLE_RATE_2:
	case ARIZONA_SAMPLE_RATE_3:
	case ARIZONA_SAMPLE_RATE_1_STATUS:
	case ARIZONA_SAMPLE_RATE_2_STATUS:
	case ARIZONA_SAMPLE_RATE_3_STATUS:
	case ARIZONA_ASYNC_CLOCK_1:
	case ARIZONA_ASYNC_SAMPLE_RATE_1:
	case ARIZONA_ASYNC_SAMPLE_RATE_1_STATUS:
	case ARIZONA_ASYNC_SAMPLE_RATE_2:
	case ARIZONA_ASYNC_SAMPLE_RATE_2_STATUS:
	case ARIZONA_OUTPUT_SYSTEM_CLOCK:
	case ARIZONA_OUTPUT_ASYNC_CLOCK:
	case ARIZONA_RATE_ESTIMATOR_1:
	case ARIZONA_RATE_ESTIMATOR_2:
	case ARIZONA_RATE_ESTIMATOR_3:
	case ARIZONA_RATE_ESTIMATOR_4:
	case ARIZONA_RATE_ESTIMATOR_5:
	case ARIZONA_FLL1_CONTROL_1:
	case ARIZONA_FLL1_CONTROL_2:
	case ARIZONA_FLL1_CONTROL_3:
	case ARIZONA_FLL1_CONTROL_4:
	case ARIZONA_FLL1_CONTROL_5:
	case ARIZONA_FLL1_CONTROL_6:
	case ARIZONA_FLL1_CONTROL_7:
	case ARIZONA_FLL1_SYNCHRONISER_1:
	case ARIZONA_FLL1_SYNCHRONISER_2:
	case ARIZONA_FLL1_SYNCHRONISER_3:
	case ARIZONA_FLL1_SYNCHRONISER_4:
	case ARIZONA_FLL1_SYNCHRONISER_5:
	case ARIZONA_FLL1_SYNCHRONISER_6:
	case ARIZONA_FLL1_SYNCHRONISER_7:
	case ARIZONA_FLL1_SPREAD_SPECTRUM:
	case ARIZONA_FLL1_GPIO_CLOCK:
	case ARIZONA_FLL2_CONTROL_1:
	case ARIZONA_FLL2_CONTROL_2:
	case ARIZONA_FLL2_CONTROL_3:
	case ARIZONA_FLL2_CONTROL_4:
	case ARIZONA_FLL2_CONTROL_5:
	case ARIZONA_FLL2_CONTROL_6:
	case ARIZONA_FLL2_CONTROL_7:
	case ARIZONA_FLL2_SYNCHRONISER_1:
	case ARIZONA_FLL2_SYNCHRONISER_2:
	case ARIZONA_FLL2_SYNCHRONISER_3:
	case ARIZONA_FLL2_SYNCHRONISER_4:
	case ARIZONA_FLL2_SYNCHRONISER_5:
	case ARIZONA_FLL2_SYNCHRONISER_6:
	case ARIZONA_FLL2_SYNCHRONISER_7:
	case ARIZONA_FLL2_SPREAD_SPECTRUM:
	case ARIZONA_FLL2_GPIO_CLOCK:
	case ARIZONA_MIC_BIAS_CTRL_1:
	case ARIZONA_MIC_BIAS_CTRL_2:
	case ARIZONA_HP_CTRL_1L:
	case ARIZONA_HP_CTRL_1R:
	case ARIZONA_INPUT_ENABLES:
	case ARIZONA_INPUT_ENABLES_STATUS:
	case ARIZONA_INPUT_RATE:
	case ARIZONA_INPUT_VOLUME_RAMP:
	case ARIZONA_HPF_CONTROL:
	case ARIZONA_IN1L_CONTROL:
	case ARIZONA_ADC_DIGITAL_VOLUME_1L:
	case ARIZONA_DMIC1L_CONTROL:
	case ARIZONA_IN1R_CONTROL:
	case ARIZONA_ADC_DIGITAL_VOLUME_1R:
	case ARIZONA_DMIC1R_CONTROL:
	case ARIZONA_IN2L_CONTROL:
	case ARIZONA_ADC_DIGITAL_VOLUME_2L:
	case ARIZONA_DMIC2L_CONTROL:
	case ARIZONA_IN2R_CONTROL:
	case ARIZONA_ADC_DIGITAL_VOLUME_2R:
	case ARIZONA_DMIC2R_CONTROL:
	case ARIZONA_OUTPUT_ENABLES_1:
	case ARIZONA_OUTPUT_STATUS_1:
	case ARIZONA_RAW_OUTPUT_STATUS_1:
	case ARIZONA_OUTPUT_RATE_1:
	case ARIZONA_OUTPUT_VOLUME_RAMP:
	case ARIZONA_OUTPUT_PATH_CONFIG_1L:
	case ARIZONA_DAC_DIGITAL_VOLUME_1L:
	case ARIZONA_DAC_VOLUME_LIMIT_1L:
	case ARIZONA_NOISE_GATE_SELECT_1L:
	case ARIZONA_DAC_DIGITAL_VOLUME_1R:
	case ARIZONA_DAC_VOLUME_LIMIT_1R:
	case ARIZONA_NOISE_GATE_SELECT_1R:
	case ARIZONA_DAC_DIGITAL_VOLUME_4L:
	case ARIZONA_OUT_VOLUME_4L:
	case ARIZONA_NOISE_GATE_SELECT_4L:
	case ARIZONA_DAC_AEC_CONTROL_1:
	case ARIZONA_NOISE_GATE_CONTROL:
	case ARIZONA_HP1_SHORT_CIRCUIT_CTRL:
	case ARIZONA_AIF1_BCLK_CTRL:
	case ARIZONA_AIF1_TX_PIN_CTRL:
	case ARIZONA_AIF1_RX_PIN_CTRL:
	case ARIZONA_AIF1_RATE_CTRL:
	case ARIZONA_AIF1_FORMAT:
	case ARIZONA_AIF1_TX_BCLK_RATE:
	case ARIZONA_AIF1_RX_BCLK_RATE:
	case ARIZONA_AIF1_FRAME_CTRL_1:
	case ARIZONA_AIF1_FRAME_CTRL_2:
	case ARIZONA_AIF1_FRAME_CTRL_3:
	case ARIZONA_AIF1_FRAME_CTRL_4:
	case ARIZONA_AIF1_FRAME_CTRL_5:
	case ARIZONA_AIF1_FRAME_CTRL_6:
	case ARIZONA_AIF1_FRAME_CTRL_7:
	case ARIZONA_AIF1_FRAME_CTRL_8:
	case ARIZONA_AIF1_FRAME_CTRL_9:
	case ARIZONA_AIF1_FRAME_CTRL_10:
	case ARIZONA_AIF1_FRAME_CTRL_11:
	case ARIZONA_AIF1_FRAME_CTRL_12:
	case ARIZONA_AIF1_FRAME_CTRL_13:
	case ARIZONA_AIF1_FRAME_CTRL_14:
	case ARIZONA_AIF1_FRAME_CTRL_15:
	case ARIZONA_AIF1_FRAME_CTRL_16:
	case ARIZONA_AIF1_FRAME_CTRL_17:
	case ARIZONA_AIF1_FRAME_CTRL_18:
	case ARIZONA_AIF1_TX_ENABLES:
	case ARIZONA_AIF1_RX_ENABLES:
	case ARIZONA_AIF2_BCLK_CTRL:
	case ARIZONA_AIF2_TX_PIN_CTRL:
	case ARIZONA_AIF2_RX_PIN_CTRL:
	case ARIZONA_AIF2_RATE_CTRL:
	case ARIZONA_AIF2_FORMAT:
	case ARIZONA_AIF2_TX_BCLK_RATE:
	case ARIZONA_AIF2_RX_BCLK_RATE:
	case ARIZONA_AIF2_FRAME_CTRL_1:
	case ARIZONA_AIF2_FRAME_CTRL_2:
	case ARIZONA_AIF2_FRAME_CTRL_3:
	case ARIZONA_AIF2_FRAME_CTRL_4:
	case ARIZONA_AIF2_FRAME_CTRL_5:
	case ARIZONA_AIF2_FRAME_CTRL_6:
	case ARIZONA_AIF2_FRAME_CTRL_7:
	case ARIZONA_AIF2_FRAME_CTRL_8:
	case ARIZONA_AIF2_FRAME_CTRL_11:
	case ARIZONA_AIF2_FRAME_CTRL_12:
	case ARIZONA_AIF2_FRAME_CTRL_13:
	case ARIZONA_AIF2_FRAME_CTRL_14:
	case ARIZONA_AIF2_FRAME_CTRL_15:
	case ARIZONA_AIF2_FRAME_CTRL_16:
	case ARIZONA_AIF2_TX_ENABLES:
	case ARIZONA_AIF2_RX_ENABLES:
	case ARIZONA_AIF3_BCLK_CTRL:
	case ARIZONA_AIF3_TX_PIN_CTRL:
	case ARIZONA_AIF3_RX_PIN_CTRL:
	case ARIZONA_AIF3_RATE_CTRL:
	case ARIZONA_AIF3_FORMAT:
	case ARIZONA_AIF3_TX_BCLK_RATE:
	case ARIZONA_AIF3_RX_BCLK_RATE:
	case ARIZONA_AIF3_FRAME_CTRL_1:
	case ARIZONA_AIF3_FRAME_CTRL_2:
	case ARIZONA_AIF3_FRAME_CTRL_3:
	case ARIZONA_AIF3_FRAME_CTRL_4:
	case ARIZONA_AIF3_FRAME_CTRL_11:
	case ARIZONA_AIF3_FRAME_CTRL_12:
	case ARIZONA_AIF3_TX_ENABLES:
	case ARIZONA_AIF3_RX_ENABLES:
	case ARIZONA_PWM1MIX_INPUT_1_SOURCE:
	case ARIZONA_PWM1MIX_INPUT_1_VOLUME:
	case ARIZONA_PWM1MIX_INPUT_2_SOURCE:
	case ARIZONA_PWM1MIX_INPUT_2_VOLUME:
	case ARIZONA_PWM1MIX_INPUT_3_SOURCE:
	case ARIZONA_PWM1MIX_INPUT_3_VOLUME:
	case ARIZONA_PWM1MIX_INPUT_4_SOURCE:
	case ARIZONA_PWM1MIX_INPUT_4_VOLUME:
	case ARIZONA_PWM2MIX_INPUT_1_SOURCE:
	case ARIZONA_PWM2MIX_INPUT_1_VOLUME:
	case ARIZONA_PWM2MIX_INPUT_2_SOURCE:
	case ARIZONA_PWM2MIX_INPUT_2_VOLUME:
	case ARIZONA_PWM2MIX_INPUT_3_SOURCE:
	case ARIZONA_PWM2MIX_INPUT_3_VOLUME:
	case ARIZONA_PWM2MIX_INPUT_4_SOURCE:
	case ARIZONA_PWM2MIX_INPUT_4_VOLUME:
	case ARIZONA_OUT1LMIX_INPUT_1_SOURCE:
	case ARIZONA_OUT1LMIX_INPUT_1_VOLUME:
	case ARIZONA_OUT1LMIX_INPUT_2_SOURCE:
	case ARIZONA_OUT1LMIX_INPUT_2_VOLUME:
	case ARIZONA_OUT1LMIX_INPUT_3_SOURCE:
	case ARIZONA_OUT1LMIX_INPUT_3_VOLUME:
	case ARIZONA_OUT1LMIX_INPUT_4_SOURCE:
	case ARIZONA_OUT1LMIX_INPUT_4_VOLUME:
	case ARIZONA_OUT1RMIX_INPUT_1_SOURCE:
	case ARIZONA_OUT1RMIX_INPUT_1_VOLUME:
	case ARIZONA_OUT1RMIX_INPUT_2_SOURCE:
	case ARIZONA_OUT1RMIX_INPUT_2_VOLUME:
	case ARIZONA_OUT1RMIX_INPUT_3_SOURCE:
	case ARIZONA_OUT1RMIX_INPUT_3_VOLUME:
	case ARIZONA_OUT1RMIX_INPUT_4_SOURCE:
	case ARIZONA_OUT1RMIX_INPUT_4_VOLUME:
	case ARIZONA_OUT4LMIX_INPUT_1_SOURCE:
	case ARIZONA_OUT4LMIX_INPUT_1_VOLUME:
	case ARIZONA_OUT4LMIX_INPUT_2_SOURCE:
	case ARIZONA_OUT4LMIX_INPUT_2_VOLUME:
	case ARIZONA_OUT4LMIX_INPUT_3_SOURCE:
	case ARIZONA_OUT4LMIX_INPUT_3_VOLUME:
	case ARIZONA_OUT4LMIX_INPUT_4_SOURCE:
	case ARIZONA_OUT4LMIX_INPUT_4_VOLUME:
	case ARIZONA_AIF1TX1MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF1TX1MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF1TX1MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF1TX1MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF1TX1MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF1TX1MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF1TX1MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF1TX1MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF1TX2MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF1TX2MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF1TX2MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF1TX2MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF1TX2MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF1TX2MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF1TX2MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF1TX2MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF1TX3MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF1TX3MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF1TX3MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF1TX3MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF1TX3MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF1TX3MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF1TX3MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF1TX3MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF1TX4MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF1TX4MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF1TX4MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF1TX4MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF1TX4MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF1TX4MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF1TX4MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF1TX4MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF1TX5MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF1TX5MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF1TX5MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF1TX5MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF1TX5MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF1TX5MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF1TX5MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF1TX5MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF1TX6MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF1TX6MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF1TX6MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF1TX6MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF1TX6MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF1TX6MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF1TX6MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF1TX6MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF1TX7MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF1TX7MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF1TX7MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF1TX7MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF1TX7MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF1TX7MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF1TX7MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF1TX7MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF1TX8MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF1TX8MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF1TX8MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF1TX8MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF1TX8MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF1TX8MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF1TX8MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF1TX8MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF2TX1MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF2TX1MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF2TX1MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF2TX1MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF2TX1MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF2TX1MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF2TX1MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF2TX1MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF2TX2MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF2TX2MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF2TX2MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF2TX2MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF2TX2MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF2TX2MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF2TX2MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF2TX2MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF2TX3MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF2TX3MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF2TX3MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF2TX3MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF2TX3MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF2TX3MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF2TX3MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF2TX3MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF2TX4MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF2TX4MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF2TX4MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF2TX4MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF2TX4MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF2TX4MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF2TX4MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF2TX4MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF2TX5MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF2TX5MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF2TX5MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF2TX5MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF2TX5MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF2TX5MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF2TX5MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF2TX5MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF2TX6MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF2TX6MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF2TX6MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF2TX6MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF2TX6MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF2TX6MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF2TX6MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF2TX6MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF3TX1MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF3TX1MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF3TX1MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF3TX1MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF3TX1MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF3TX1MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF3TX1MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF3TX1MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF3TX2MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF3TX2MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF3TX2MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF3TX2MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF3TX2MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF3TX2MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF3TX2MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF3TX2MIX_INPUT_4_VOLUME:
	case ARIZONA_EQ1MIX_INPUT_1_SOURCE:
	case ARIZONA_EQ1MIX_INPUT_1_VOLUME:
	case ARIZONA_EQ1MIX_INPUT_2_SOURCE:
	case ARIZONA_EQ1MIX_INPUT_2_VOLUME:
	case ARIZONA_EQ1MIX_INPUT_3_SOURCE:
	case ARIZONA_EQ1MIX_INPUT_3_VOLUME:
	case ARIZONA_EQ1MIX_INPUT_4_SOURCE:
	case ARIZONA_EQ1MIX_INPUT_4_VOLUME:
	case ARIZONA_EQ2MIX_INPUT_1_SOURCE:
	case ARIZONA_EQ2MIX_INPUT_1_VOLUME:
	case ARIZONA_EQ2MIX_INPUT_2_SOURCE:
	case ARIZONA_EQ2MIX_INPUT_2_VOLUME:
	case ARIZONA_EQ2MIX_INPUT_3_SOURCE:
	case ARIZONA_EQ2MIX_INPUT_3_VOLUME:
	case ARIZONA_EQ2MIX_INPUT_4_SOURCE:
	case ARIZONA_EQ2MIX_INPUT_4_VOLUME:
	case ARIZONA_DRC1LMIX_INPUT_1_SOURCE:
	case ARIZONA_DRC1LMIX_INPUT_1_VOLUME:
	case ARIZONA_DRC1LMIX_INPUT_2_SOURCE:
	case ARIZONA_DRC1LMIX_INPUT_2_VOLUME:
	case ARIZONA_DRC1LMIX_INPUT_3_SOURCE:
	case ARIZONA_DRC1LMIX_INPUT_3_VOLUME:
	case ARIZONA_DRC1LMIX_INPUT_4_SOURCE:
	case ARIZONA_DRC1LMIX_INPUT_4_VOLUME:
	case ARIZONA_DRC1RMIX_INPUT_1_SOURCE:
	case ARIZONA_DRC1RMIX_INPUT_1_VOLUME:
	case ARIZONA_DRC1RMIX_INPUT_2_SOURCE:
	case ARIZONA_DRC1RMIX_INPUT_2_VOLUME:
	case ARIZONA_DRC1RMIX_INPUT_3_SOURCE:
	case ARIZONA_DRC1RMIX_INPUT_3_VOLUME:
	case ARIZONA_DRC1RMIX_INPUT_4_SOURCE:
	case ARIZONA_DRC1RMIX_INPUT_4_VOLUME:
	case ARIZONA_DRC2LMIX_INPUT_1_SOURCE:
	case ARIZONA_DRC2LMIX_INPUT_1_VOLUME:
	case ARIZONA_DRC2LMIX_INPUT_2_SOURCE:
	case ARIZONA_DRC2LMIX_INPUT_2_VOLUME:
	case ARIZONA_DRC2LMIX_INPUT_3_SOURCE:
	case ARIZONA_DRC2LMIX_INPUT_3_VOLUME:
	case ARIZONA_DRC2LMIX_INPUT_4_SOURCE:
	case ARIZONA_DRC2LMIX_INPUT_4_VOLUME:
	case ARIZONA_DRC2RMIX_INPUT_1_SOURCE:
	case ARIZONA_DRC2RMIX_INPUT_1_VOLUME:
	case ARIZONA_DRC2RMIX_INPUT_2_SOURCE:
	case ARIZONA_DRC2RMIX_INPUT_2_VOLUME:
	case ARIZONA_DRC2RMIX_INPUT_3_SOURCE:
	case ARIZONA_DRC2RMIX_INPUT_3_VOLUME:
	case ARIZONA_DRC2RMIX_INPUT_4_SOURCE:
	case ARIZONA_DRC2RMIX_INPUT_4_VOLUME:
	case ARIZONA_HPLP1MIX_INPUT_1_SOURCE:
	case ARIZONA_HPLP1MIX_INPUT_1_VOLUME:
	case ARIZONA_HPLP1MIX_INPUT_2_SOURCE:
	case ARIZONA_HPLP1MIX_INPUT_2_VOLUME:
	case ARIZONA_HPLP1MIX_INPUT_3_SOURCE:
	case ARIZONA_HPLP1MIX_INPUT_3_VOLUME:
	case ARIZONA_HPLP1MIX_INPUT_4_SOURCE:
	case ARIZONA_HPLP1MIX_INPUT_4_VOLUME:
	case ARIZONA_HPLP2MIX_INPUT_1_SOURCE:
	case ARIZONA_HPLP2MIX_INPUT_1_VOLUME:
	case ARIZONA_HPLP2MIX_INPUT_2_SOURCE:
	case ARIZONA_HPLP2MIX_INPUT_2_VOLUME:
	case ARIZONA_HPLP2MIX_INPUT_3_SOURCE:
	case ARIZONA_HPLP2MIX_INPUT_3_VOLUME:
	case ARIZONA_HPLP2MIX_INPUT_4_SOURCE:
	case ARIZONA_HPLP2MIX_INPUT_4_VOLUME:
	case ARIZONA_HPLP3MIX_INPUT_1_SOURCE:
	case ARIZONA_HPLP3MIX_INPUT_1_VOLUME:
	case ARIZONA_HPLP3MIX_INPUT_2_SOURCE:
	case ARIZONA_HPLP3MIX_INPUT_2_VOLUME:
	case ARIZONA_HPLP3MIX_INPUT_3_SOURCE:
	case ARIZONA_HPLP3MIX_INPUT_3_VOLUME:
	case ARIZONA_HPLP3MIX_INPUT_4_SOURCE:
	case ARIZONA_HPLP3MIX_INPUT_4_VOLUME:
	case ARIZONA_HPLP4MIX_INPUT_1_SOURCE:
	case ARIZONA_HPLP4MIX_INPUT_1_VOLUME:
	case ARIZONA_HPLP4MIX_INPUT_2_SOURCE:
	case ARIZONA_HPLP4MIX_INPUT_2_VOLUME:
	case ARIZONA_HPLP4MIX_INPUT_3_SOURCE:
	case ARIZONA_HPLP4MIX_INPUT_3_VOLUME:
	case ARIZONA_HPLP4MIX_INPUT_4_SOURCE:
	case ARIZONA_HPLP4MIX_INPUT_4_VOLUME:
	case ARIZONA_DSP2LMIX_INPUT_1_SOURCE:
	case ARIZONA_DSP2LMIX_INPUT_1_VOLUME:
	case ARIZONA_DSP2LMIX_INPUT_2_SOURCE:
	case ARIZONA_DSP2LMIX_INPUT_2_VOLUME:
	case ARIZONA_DSP2LMIX_INPUT_3_SOURCE:
	case ARIZONA_DSP2LMIX_INPUT_3_VOLUME:
	case ARIZONA_DSP2LMIX_INPUT_4_SOURCE:
	case ARIZONA_DSP2LMIX_INPUT_4_VOLUME:
	case ARIZONA_DSP2RMIX_INPUT_1_SOURCE:
	case ARIZONA_DSP2RMIX_INPUT_1_VOLUME:
	case ARIZONA_DSP2RMIX_INPUT_2_SOURCE:
	case ARIZONA_DSP2RMIX_INPUT_2_VOLUME:
	case ARIZONA_DSP2RMIX_INPUT_3_SOURCE:
	case ARIZONA_DSP2RMIX_INPUT_3_VOLUME:
	case ARIZONA_DSP2RMIX_INPUT_4_SOURCE:
	case ARIZONA_DSP2RMIX_INPUT_4_VOLUME:
	case ARIZONA_DSP2AUX1MIX_INPUT_1_SOURCE:
	case ARIZONA_DSP2AUX2MIX_INPUT_1_SOURCE:
	case ARIZONA_DSP2AUX3MIX_INPUT_1_SOURCE:
	case ARIZONA_DSP2AUX4MIX_INPUT_1_SOURCE:
	case ARIZONA_DSP2AUX5MIX_INPUT_1_SOURCE:
	case ARIZONA_DSP2AUX6MIX_INPUT_1_SOURCE:
	case ARIZONA_DSP3LMIX_INPUT_1_SOURCE:
	case ARIZONA_DSP3LMIX_INPUT_1_VOLUME:
	case ARIZONA_DSP3LMIX_INPUT_2_SOURCE:
	case ARIZONA_DSP3LMIX_INPUT_2_VOLUME:
	case ARIZONA_DSP3LMIX_INPUT_3_SOURCE:
	case ARIZONA_DSP3LMIX_INPUT_3_VOLUME:
	case ARIZONA_DSP3LMIX_INPUT_4_SOURCE:
	case ARIZONA_DSP3LMIX_INPUT_4_VOLUME:
	case ARIZONA_DSP3RMIX_INPUT_1_SOURCE:
	case ARIZONA_DSP3RMIX_INPUT_1_VOLUME:
	case ARIZONA_DSP3RMIX_INPUT_2_SOURCE:
	case ARIZONA_DSP3RMIX_INPUT_2_VOLUME:
	case ARIZONA_DSP3RMIX_INPUT_3_SOURCE:
	case ARIZONA_DSP3RMIX_INPUT_3_VOLUME:
	case ARIZONA_DSP3RMIX_INPUT_4_SOURCE:
	case ARIZONA_DSP3RMIX_INPUT_4_VOLUME:
	case ARIZONA_DSP3AUX1MIX_INPUT_1_SOURCE:
	case ARIZONA_DSP3AUX2MIX_INPUT_1_SOURCE:
	case ARIZONA_DSP3AUX3MIX_INPUT_1_SOURCE:
	case ARIZONA_DSP3AUX4MIX_INPUT_1_SOURCE:
	case ARIZONA_DSP3AUX5MIX_INPUT_1_SOURCE:
	case ARIZONA_DSP3AUX6MIX_INPUT_1_SOURCE:
	case ARIZONA_ASRC1LMIX_INPUT_1_SOURCE:
	case ARIZONA_ASRC1RMIX_INPUT_1_SOURCE:
	case ARIZONA_ASRC2LMIX_INPUT_1_SOURCE:
	case ARIZONA_ASRC2RMIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC1DEC1MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC1DEC2MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC1DEC3MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC1DEC4MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC1INT1MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC1INT2MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC1INT3MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC1INT4MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC2DEC1MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC2DEC2MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC2DEC3MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC2DEC4MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC2INT1MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC2INT2MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC2INT3MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC2INT4MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC3DEC1MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC3DEC2MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC3DEC3MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC3DEC4MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC3INT1MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC3INT2MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC3INT3MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC3INT4MIX_INPUT_1_SOURCE:
	case ARIZONA_GPIO1_CTRL:
	case ARIZONA_GPIO2_CTRL:
	case ARIZONA_IRQ_CTRL_1:
	case ARIZONA_GPIO_DEBOUNCE_CONFIG:
	case ARIZONA_MISC_PAD_CTRL_1:
	case ARIZONA_MISC_PAD_CTRL_2:
	case ARIZONA_MISC_PAD_CTRL_3:
	case ARIZONA_MISC_PAD_CTRL_4:
	case ARIZONA_MISC_PAD_CTRL_5:
	case ARIZONA_MISC_PAD_CTRL_6:
	case ARIZONA_MISC_PAD_CTRL_7:
	case ARIZONA_MISC_PAD_CTRL_9:
	case ARIZONA_MISC_PAD_CTRL_10:
	case ARIZONA_MISC_PAD_CTRL_11:
	case ARIZONA_MISC_PAD_CTRL_12:
	case ARIZONA_MISC_PAD_CTRL_13:
	case ARIZONA_MISC_PAD_CTRL_14:
	case ARIZONA_MISC_PAD_CTRL_16:
	case ARIZONA_INTERRUPT_STATUS_1:
	case ARIZONA_INTERRUPT_STATUS_2:
	case ARIZONA_INTERRUPT_STATUS_3:
	case ARIZONA_INTERRUPT_STATUS_4:
	case ARIZONA_INTERRUPT_STATUS_5:
	case ARIZONA_INTERRUPT_STATUS_6:
	case ARIZONA_INTERRUPT_STATUS_1_MASK:
	case ARIZONA_INTERRUPT_STATUS_2_MASK:
	case ARIZONA_INTERRUPT_STATUS_3_MASK:
	case ARIZONA_INTERRUPT_STATUS_4_MASK:
	case ARIZONA_INTERRUPT_STATUS_5_MASK:
	case ARIZONA_INTERRUPT_STATUS_6_MASK:
	case ARIZONA_INTERRUPT_CONTROL:
	case ARIZONA_IRQ2_STATUS_1:
	case ARIZONA_IRQ2_STATUS_2:
	case ARIZONA_IRQ2_STATUS_3:
	case ARIZONA_IRQ2_STATUS_4:
	case ARIZONA_IRQ2_STATUS_5:
	case ARIZONA_IRQ2_STATUS_6:
	case ARIZONA_IRQ2_STATUS_1_MASK:
	case ARIZONA_IRQ2_STATUS_2_MASK:
	case ARIZONA_IRQ2_STATUS_3_MASK:
	case ARIZONA_IRQ2_STATUS_4_MASK:
	case ARIZONA_IRQ2_STATUS_5_MASK:
	case ARIZONA_IRQ2_STATUS_6_MASK:
	case ARIZONA_IRQ2_CONTROL:
	case ARIZONA_INTERRUPT_RAW_STATUS_2:
	case ARIZONA_INTERRUPT_RAW_STATUS_3:
	case ARIZONA_INTERRUPT_RAW_STATUS_4:
	case ARIZONA_INTERRUPT_RAW_STATUS_5:
	case ARIZONA_INTERRUPT_RAW_STATUS_6:
	case ARIZONA_INTERRUPT_RAW_STATUS_7:
	case ARIZONA_INTERRUPT_RAW_STATUS_8:
	case ARIZONA_INTERRUPT_RAW_STATUS_9:
	case ARIZONA_IRQ_PIN_STATUS:
	case ARIZONA_FX_CTRL1:
	case ARIZONA_FX_CTRL2:
	case ARIZONA_EQ1_1:
	case ARIZONA_EQ1_2:
	case ARIZONA_EQ1_3:
	case ARIZONA_EQ1_4:
	case ARIZONA_EQ1_5:
	case ARIZONA_EQ1_6:
	case ARIZONA_EQ1_7:
	case ARIZONA_EQ1_8:
	case ARIZONA_EQ1_9:
	case ARIZONA_EQ1_10:
	case ARIZONA_EQ1_11:
	case ARIZONA_EQ1_12:
	case ARIZONA_EQ1_13:
	case ARIZONA_EQ1_14:
	case ARIZONA_EQ1_15:
	case ARIZONA_EQ1_16:
	case ARIZONA_EQ1_17:
	case ARIZONA_EQ1_18:
	case ARIZONA_EQ1_19:
	case ARIZONA_EQ1_20:
	case ARIZONA_EQ1_21:
	case ARIZONA_EQ2_1:
	case ARIZONA_EQ2_2:
	case ARIZONA_EQ2_3:
	case ARIZONA_EQ2_4:
	case ARIZONA_EQ2_5:
	case ARIZONA_EQ2_6:
	case ARIZONA_EQ2_7:
	case ARIZONA_EQ2_8:
	case ARIZONA_EQ2_9:
	case ARIZONA_EQ2_10:
	case ARIZONA_EQ2_11:
	case ARIZONA_EQ2_12:
	case ARIZONA_EQ2_13:
	case ARIZONA_EQ2_14:
	case ARIZONA_EQ2_15:
	case ARIZONA_EQ2_16:
	case ARIZONA_EQ2_17:
	case ARIZONA_EQ2_18:
	case ARIZONA_EQ2_19:
	case ARIZONA_EQ2_20:
	case ARIZONA_EQ2_21:
	case ARIZONA_DRC1_CTRL1:
	case ARIZONA_DRC1_CTRL2:
	case ARIZONA_DRC1_CTRL3:
	case ARIZONA_DRC1_CTRL4:
	case ARIZONA_DRC1_CTRL5:
	case ARIZONA_DRC2_CTRL1:
	case ARIZONA_DRC2_CTRL2:
	case ARIZONA_DRC2_CTRL3:
	case ARIZONA_DRC2_CTRL4:
	case ARIZONA_DRC2_CTRL5:
	case ARIZONA_HPLPF1_1:
	case ARIZONA_HPLPF1_2:
	case ARIZONA_HPLPF2_1:
	case ARIZONA_HPLPF2_2:
	case ARIZONA_HPLPF3_1:
	case ARIZONA_HPLPF3_2:
	case ARIZONA_HPLPF4_1:
	case ARIZONA_HPLPF4_2:
	case ARIZONA_ASRC_ENABLE:
	case ARIZONA_ASRC_STATUS:
	case ARIZONA_ASRC_RATE1:
	case ARIZONA_ASRC_RATE2:
	case ARIZONA_ISRC_1_CTRL_1:
	case ARIZONA_ISRC_1_CTRL_2:
	case ARIZONA_ISRC_1_CTRL_3:
	case ARIZONA_ISRC_2_CTRL_1:
	case ARIZONA_ISRC_2_CTRL_2:
	case ARIZONA_ISRC_2_CTRL_3:
	case ARIZONA_ISRC_3_CTRL_1:
	case ARIZONA_ISRC_3_CTRL_2:
	case ARIZONA_ISRC_3_CTRL_3:
	case ARIZONA_DSP2_CONTROL_1:
	case ARIZONA_DSP2_CLOCKING_1:
	case ARIZONA_DSP2_STATUS_1:
	case ARIZONA_DSP2_STATUS_2:
	case ARIZONA_DSP2_STATUS_3:
	case ARIZONA_DSP2_STATUS_4:
	case ARIZONA_DSP2_WDMA_BUFFER_1:
	case ARIZONA_DSP2_WDMA_BUFFER_2:
	case ARIZONA_DSP2_WDMA_BUFFER_3:
	case ARIZONA_DSP2_WDMA_BUFFER_4:
	case ARIZONA_DSP2_WDMA_BUFFER_5:
	case ARIZONA_DSP2_WDMA_BUFFER_6:
	case ARIZONA_DSP2_WDMA_BUFFER_7:
	case ARIZONA_DSP2_WDMA_BUFFER_8:
	case ARIZONA_DSP2_RDMA_BUFFER_1:
	case ARIZONA_DSP2_RDMA_BUFFER_2:
	case ARIZONA_DSP2_RDMA_BUFFER_3:
	case ARIZONA_DSP2_RDMA_BUFFER_4:
	case ARIZONA_DSP2_RDMA_BUFFER_5:
	case ARIZONA_DSP2_RDMA_BUFFER_6:
	case ARIZONA_DSP2_WDMA_CONFIG_1:
	case ARIZONA_DSP2_WDMA_CONFIG_2:
	case ARIZONA_DSP2_WDMA_OFFSET_1:
	case ARIZONA_DSP2_RDMA_CONFIG_1:
	case ARIZONA_DSP2_RDMA_OFFSET_1:
	case ARIZONA_DSP2_EXTERNAL_START_SELECT_1:
	case ARIZONA_DSP2_SCRATCH_0:
	case ARIZONA_DSP2_SCRATCH_1:
	case ARIZONA_DSP2_SCRATCH_2:
	case ARIZONA_DSP2_SCRATCH_3:
	case ARIZONA_DSP3_CONTROL_1:
	case ARIZONA_DSP3_CLOCKING_1:
	case ARIZONA_DSP3_STATUS_1:
	case ARIZONA_DSP3_STATUS_2:
	case ARIZONA_DSP3_STATUS_3:
	case ARIZONA_DSP3_STATUS_4:
	case ARIZONA_DSP3_WDMA_BUFFER_1:
	case ARIZONA_DSP3_WDMA_BUFFER_2:
	case ARIZONA_DSP3_WDMA_BUFFER_3:
	case ARIZONA_DSP3_WDMA_BUFFER_4:
	case ARIZONA_DSP3_WDMA_BUFFER_5:
	case ARIZONA_DSP3_WDMA_BUFFER_6:
	case ARIZONA_DSP3_WDMA_BUFFER_7:
	case ARIZONA_DSP3_WDMA_BUFFER_8:
	case ARIZONA_DSP3_RDMA_BUFFER_1:
	case ARIZONA_DSP3_RDMA_BUFFER_2:
	case ARIZONA_DSP3_RDMA_BUFFER_3:
	case ARIZONA_DSP3_RDMA_BUFFER_4:
	case ARIZONA_DSP3_RDMA_BUFFER_5:
	case ARIZONA_DSP3_RDMA_BUFFER_6:
	case ARIZONA_DSP3_WDMA_CONFIG_1:
	case ARIZONA_DSP3_WDMA_CONFIG_2:
	case ARIZONA_DSP3_WDMA_OFFSET_1:
	case ARIZONA_DSP3_RDMA_CONFIG_1:
	case ARIZONA_DSP3_RDMA_OFFSET_1:
	case ARIZONA_DSP3_EXTERNAL_START_SELECT_1:
	case ARIZONA_DSP3_SCRATCH_0:
	case ARIZONA_DSP3_SCRATCH_1:
	case ARIZONA_DSP3_SCRATCH_2:
	case ARIZONA_DSP3_SCRATCH_3:
		return true;
	default:
		return cs47l24_is_adsp_memory(reg);
	}
}