#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
struct device {int dummy; } ;

/* Variables and functions */
#define  ARIZONA_ASRC_STATUS 224 
#define  ARIZONA_ASYNC_SAMPLE_RATE_1_STATUS 223 
#define  ARIZONA_ASYNC_SAMPLE_RATE_2_STATUS 222 
#define  ARIZONA_DEVICE_REVISION 221 
#define  ARIZONA_DSP2_CLOCKING_1 220 
#define  ARIZONA_DSP2_EXTERNAL_START_SELECT_1 219 
#define  ARIZONA_DSP2_RDMA_BUFFER_1 218 
#define  ARIZONA_DSP2_RDMA_BUFFER_2 217 
#define  ARIZONA_DSP2_RDMA_BUFFER_3 216 
#define  ARIZONA_DSP2_RDMA_BUFFER_4 215 
#define  ARIZONA_DSP2_RDMA_BUFFER_5 214 
#define  ARIZONA_DSP2_RDMA_BUFFER_6 213 
#define  ARIZONA_DSP2_RDMA_CONFIG_1 212 
#define  ARIZONA_DSP2_RDMA_OFFSET_1 211 
#define  ARIZONA_DSP2_SCRATCH_0 210 
#define  ARIZONA_DSP2_SCRATCH_1 209 
#define  ARIZONA_DSP2_SCRATCH_2 208 
#define  ARIZONA_DSP2_SCRATCH_3 207 
#define  ARIZONA_DSP2_STATUS_1 206 
#define  ARIZONA_DSP2_STATUS_2 205 
#define  ARIZONA_DSP2_STATUS_3 204 
#define  ARIZONA_DSP2_STATUS_4 203 
#define  ARIZONA_DSP2_WDMA_BUFFER_1 202 
#define  ARIZONA_DSP2_WDMA_BUFFER_2 201 
#define  ARIZONA_DSP2_WDMA_BUFFER_3 200 
#define  ARIZONA_DSP2_WDMA_BUFFER_4 199 
#define  ARIZONA_DSP2_WDMA_BUFFER_5 198 
#define  ARIZONA_DSP2_WDMA_BUFFER_6 197 
#define  ARIZONA_DSP2_WDMA_BUFFER_7 196 
#define  ARIZONA_DSP2_WDMA_BUFFER_8 195 
#define  ARIZONA_DSP2_WDMA_CONFIG_1 194 
#define  ARIZONA_DSP2_WDMA_CONFIG_2 193 
#define  ARIZONA_DSP2_WDMA_OFFSET_1 192 
#define  ARIZONA_DSP3_CLOCKING_1 191 
#define  ARIZONA_DSP3_EXTERNAL_START_SELECT_1 190 
#define  ARIZONA_DSP3_RDMA_BUFFER_1 189 
#define  ARIZONA_DSP3_RDMA_BUFFER_2 188 
#define  ARIZONA_DSP3_RDMA_BUFFER_3 187 
#define  ARIZONA_DSP3_RDMA_BUFFER_4 186 
#define  ARIZONA_DSP3_RDMA_BUFFER_5 185 
#define  ARIZONA_DSP3_RDMA_BUFFER_6 184 
#define  ARIZONA_DSP3_RDMA_CONFIG_1 183 
#define  ARIZONA_DSP3_RDMA_OFFSET_1 182 
#define  ARIZONA_DSP3_SCRATCH_0 181 
#define  ARIZONA_DSP3_SCRATCH_1 180 
#define  ARIZONA_DSP3_SCRATCH_2 179 
#define  ARIZONA_DSP3_SCRATCH_3 178 
#define  ARIZONA_DSP3_STATUS_1 177 
#define  ARIZONA_DSP3_STATUS_2 176 
#define  ARIZONA_DSP3_STATUS_3 175 
#define  ARIZONA_DSP3_STATUS_4 174 
#define  ARIZONA_DSP3_WDMA_BUFFER_1 173 
#define  ARIZONA_DSP3_WDMA_BUFFER_2 172 
#define  ARIZONA_DSP3_WDMA_BUFFER_3 171 
#define  ARIZONA_DSP3_WDMA_BUFFER_4 170 
#define  ARIZONA_DSP3_WDMA_BUFFER_5 169 
#define  ARIZONA_DSP3_WDMA_BUFFER_6 168 
#define  ARIZONA_DSP3_WDMA_BUFFER_7 167 
#define  ARIZONA_DSP3_WDMA_BUFFER_8 166 
#define  ARIZONA_DSP3_WDMA_CONFIG_1 165 
#define  ARIZONA_DSP3_WDMA_CONFIG_2 164 
#define  ARIZONA_DSP3_WDMA_OFFSET_1 163 
#define  ARIZONA_FX_CTRL2 162 
#define  ARIZONA_HAPTICS_STATUS 161 
#define  ARIZONA_HP_CTRL_1L 160 
#define  ARIZONA_HP_CTRL_1R 159 
#define  ARIZONA_INPUT_ENABLES_STATUS 158 
#define  ARIZONA_INTERRUPT_RAW_STATUS_2 157 
#define  ARIZONA_INTERRUPT_RAW_STATUS_3 156 
#define  ARIZONA_INTERRUPT_RAW_STATUS_4 155 
#define  ARIZONA_INTERRUPT_RAW_STATUS_5 154 
#define  ARIZONA_INTERRUPT_RAW_STATUS_6 153 
#define  ARIZONA_INTERRUPT_RAW_STATUS_7 152 
#define  ARIZONA_INTERRUPT_RAW_STATUS_8 151 
#define  ARIZONA_INTERRUPT_RAW_STATUS_9 150 
#define  ARIZONA_INTERRUPT_STATUS_1 149 
#define  ARIZONA_INTERRUPT_STATUS_2 148 
#define  ARIZONA_INTERRUPT_STATUS_3 147 
#define  ARIZONA_INTERRUPT_STATUS_4 146 
#define  ARIZONA_INTERRUPT_STATUS_5 145 
#define  ARIZONA_INTERRUPT_STATUS_6 144 
#define  ARIZONA_IRQ2_STATUS_1 143 
#define  ARIZONA_IRQ2_STATUS_2 142 
#define  ARIZONA_IRQ2_STATUS_3 141 
#define  ARIZONA_IRQ2_STATUS_4 140 
#define  ARIZONA_IRQ2_STATUS_5 139 
#define  ARIZONA_IRQ2_STATUS_6 138 
#define  ARIZONA_IRQ_PIN_STATUS 137 
#define  ARIZONA_OUTPUT_STATUS_1 136 
#define  ARIZONA_RAW_OUTPUT_STATUS_1 135 
#define  ARIZONA_SAMPLE_RATE_1_STATUS 134 
#define  ARIZONA_SAMPLE_RATE_2_STATUS 133 
#define  ARIZONA_SAMPLE_RATE_3_STATUS 132 
#define  ARIZONA_SOFTWARE_RESET 131 
#define  ARIZONA_WRITE_SEQUENCER_CTRL_0 130 
#define  ARIZONA_WRITE_SEQUENCER_CTRL_1 129 
#define  ARIZONA_WRITE_SEQUENCER_CTRL_2 128 
 int cs47l24_is_adsp_memory (unsigned int) ; 

__attribute__((used)) static bool cs47l24_volatile_register(struct device *dev, unsigned int reg)
{
	switch (reg) {
	case ARIZONA_SOFTWARE_RESET:
	case ARIZONA_DEVICE_REVISION:
	case ARIZONA_WRITE_SEQUENCER_CTRL_0:
	case ARIZONA_WRITE_SEQUENCER_CTRL_1:
	case ARIZONA_WRITE_SEQUENCER_CTRL_2:
	case ARIZONA_HAPTICS_STATUS:
	case ARIZONA_SAMPLE_RATE_1_STATUS:
	case ARIZONA_SAMPLE_RATE_2_STATUS:
	case ARIZONA_SAMPLE_RATE_3_STATUS:
	case ARIZONA_ASYNC_SAMPLE_RATE_1_STATUS:
	case ARIZONA_ASYNC_SAMPLE_RATE_2_STATUS:
	case ARIZONA_HP_CTRL_1L:
	case ARIZONA_HP_CTRL_1R:
	case ARIZONA_INPUT_ENABLES_STATUS:
	case ARIZONA_OUTPUT_STATUS_1:
	case ARIZONA_RAW_OUTPUT_STATUS_1:
	case ARIZONA_INTERRUPT_STATUS_1:
	case ARIZONA_INTERRUPT_STATUS_2:
	case ARIZONA_INTERRUPT_STATUS_3:
	case ARIZONA_INTERRUPT_STATUS_4:
	case ARIZONA_INTERRUPT_STATUS_5:
	case ARIZONA_INTERRUPT_STATUS_6:
	case ARIZONA_IRQ2_STATUS_1:
	case ARIZONA_IRQ2_STATUS_2:
	case ARIZONA_IRQ2_STATUS_3:
	case ARIZONA_IRQ2_STATUS_4:
	case ARIZONA_IRQ2_STATUS_5:
	case ARIZONA_IRQ2_STATUS_6:
	case ARIZONA_INTERRUPT_RAW_STATUS_2:
	case ARIZONA_INTERRUPT_RAW_STATUS_3:
	case ARIZONA_INTERRUPT_RAW_STATUS_4:
	case ARIZONA_INTERRUPT_RAW_STATUS_5:
	case ARIZONA_INTERRUPT_RAW_STATUS_6:
	case ARIZONA_INTERRUPT_RAW_STATUS_7:
	case ARIZONA_INTERRUPT_RAW_STATUS_8:
	case ARIZONA_INTERRUPT_RAW_STATUS_9:
	case ARIZONA_IRQ_PIN_STATUS:
	case ARIZONA_FX_CTRL2:
	case ARIZONA_ASRC_STATUS:
	case ARIZONA_DSP2_STATUS_1:
	case ARIZONA_DSP2_STATUS_2:
	case ARIZONA_DSP2_STATUS_3:
	case ARIZONA_DSP2_STATUS_4:
	case ARIZONA_DSP2_WDMA_BUFFER_1:
	case ARIZONA_DSP2_WDMA_BUFFER_2:
	case ARIZONA_DSP2_WDMA_BUFFER_3:
	case ARIZONA_DSP2_WDMA_BUFFER_4:
	case ARIZONA_DSP2_WDMA_BUFFER_5:
	case ARIZONA_DSP2_WDMA_BUFFER_6:
	case ARIZONA_DSP2_WDMA_BUFFER_7:
	case ARIZONA_DSP2_WDMA_BUFFER_8:
	case ARIZONA_DSP2_RDMA_BUFFER_1:
	case ARIZONA_DSP2_RDMA_BUFFER_2:
	case ARIZONA_DSP2_RDMA_BUFFER_3:
	case ARIZONA_DSP2_RDMA_BUFFER_4:
	case ARIZONA_DSP2_RDMA_BUFFER_5:
	case ARIZONA_DSP2_RDMA_BUFFER_6:
	case ARIZONA_DSP2_WDMA_CONFIG_1:
	case ARIZONA_DSP2_WDMA_CONFIG_2:
	case ARIZONA_DSP2_WDMA_OFFSET_1:
	case ARIZONA_DSP2_RDMA_CONFIG_1:
	case ARIZONA_DSP2_RDMA_OFFSET_1:
	case ARIZONA_DSP2_EXTERNAL_START_SELECT_1:
	case ARIZONA_DSP2_SCRATCH_0:
	case ARIZONA_DSP2_SCRATCH_1:
	case ARIZONA_DSP2_SCRATCH_2:
	case ARIZONA_DSP2_SCRATCH_3:
	case ARIZONA_DSP2_CLOCKING_1:
	case ARIZONA_DSP3_STATUS_1:
	case ARIZONA_DSP3_STATUS_2:
	case ARIZONA_DSP3_STATUS_3:
	case ARIZONA_DSP3_STATUS_4:
	case ARIZONA_DSP3_WDMA_BUFFER_1:
	case ARIZONA_DSP3_WDMA_BUFFER_2:
	case ARIZONA_DSP3_WDMA_BUFFER_3:
	case ARIZONA_DSP3_WDMA_BUFFER_4:
	case ARIZONA_DSP3_WDMA_BUFFER_5:
	case ARIZONA_DSP3_WDMA_BUFFER_6:
	case ARIZONA_DSP3_WDMA_BUFFER_7:
	case ARIZONA_DSP3_WDMA_BUFFER_8:
	case ARIZONA_DSP3_RDMA_BUFFER_1:
	case ARIZONA_DSP3_RDMA_BUFFER_2:
	case ARIZONA_DSP3_RDMA_BUFFER_3:
	case ARIZONA_DSP3_RDMA_BUFFER_4:
	case ARIZONA_DSP3_RDMA_BUFFER_5:
	case ARIZONA_DSP3_RDMA_BUFFER_6:
	case ARIZONA_DSP3_WDMA_CONFIG_1:
	case ARIZONA_DSP3_WDMA_CONFIG_2:
	case ARIZONA_DSP3_WDMA_OFFSET_1:
	case ARIZONA_DSP3_RDMA_CONFIG_1:
	case ARIZONA_DSP3_RDMA_OFFSET_1:
	case ARIZONA_DSP3_EXTERNAL_START_SELECT_1:
	case ARIZONA_DSP3_SCRATCH_0:
	case ARIZONA_DSP3_SCRATCH_1:
	case ARIZONA_DSP3_SCRATCH_2:
	case ARIZONA_DSP3_SCRATCH_3:
	case ARIZONA_DSP3_CLOCKING_1:
		return true;
	default:
		return cs47l24_is_adsp_memory(reg);
	}
}