#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
struct device {int dummy; } ;

/* Variables and functions */
#define  ARIZONA_ACCESSORY_DETECT_MODE_1 945 
#define  ARIZONA_ADC_DIGITAL_VOLUME_1L 944 
#define  ARIZONA_ADC_DIGITAL_VOLUME_1R 943 
#define  ARIZONA_ADC_DIGITAL_VOLUME_2L 942 
#define  ARIZONA_ADC_DIGITAL_VOLUME_2R 941 
#define  ARIZONA_ADC_DIGITAL_VOLUME_3L 940 
#define  ARIZONA_ADC_DIGITAL_VOLUME_3R 939 
#define  ARIZONA_ADSP2_IRQ0 938 
#define  ARIZONA_AIF1TX1MIX_INPUT_1_SOURCE 937 
#define  ARIZONA_AIF1TX1MIX_INPUT_1_VOLUME 936 
#define  ARIZONA_AIF1TX1MIX_INPUT_2_SOURCE 935 
#define  ARIZONA_AIF1TX1MIX_INPUT_2_VOLUME 934 
#define  ARIZONA_AIF1TX1MIX_INPUT_3_SOURCE 933 
#define  ARIZONA_AIF1TX1MIX_INPUT_3_VOLUME 932 
#define  ARIZONA_AIF1TX1MIX_INPUT_4_SOURCE 931 
#define  ARIZONA_AIF1TX1MIX_INPUT_4_VOLUME 930 
#define  ARIZONA_AIF1TX2MIX_INPUT_1_SOURCE 929 
#define  ARIZONA_AIF1TX2MIX_INPUT_1_VOLUME 928 
#define  ARIZONA_AIF1TX2MIX_INPUT_2_SOURCE 927 
#define  ARIZONA_AIF1TX2MIX_INPUT_2_VOLUME 926 
#define  ARIZONA_AIF1TX2MIX_INPUT_3_SOURCE 925 
#define  ARIZONA_AIF1TX2MIX_INPUT_3_VOLUME 924 
#define  ARIZONA_AIF1TX2MIX_INPUT_4_SOURCE 923 
#define  ARIZONA_AIF1TX2MIX_INPUT_4_VOLUME 922 
#define  ARIZONA_AIF1TX3MIX_INPUT_1_SOURCE 921 
#define  ARIZONA_AIF1TX3MIX_INPUT_1_VOLUME 920 
#define  ARIZONA_AIF1TX3MIX_INPUT_2_SOURCE 919 
#define  ARIZONA_AIF1TX3MIX_INPUT_2_VOLUME 918 
#define  ARIZONA_AIF1TX3MIX_INPUT_3_SOURCE 917 
#define  ARIZONA_AIF1TX3MIX_INPUT_3_VOLUME 916 
#define  ARIZONA_AIF1TX3MIX_INPUT_4_SOURCE 915 
#define  ARIZONA_AIF1TX3MIX_INPUT_4_VOLUME 914 
#define  ARIZONA_AIF1TX4MIX_INPUT_1_SOURCE 913 
#define  ARIZONA_AIF1TX4MIX_INPUT_1_VOLUME 912 
#define  ARIZONA_AIF1TX4MIX_INPUT_2_SOURCE 911 
#define  ARIZONA_AIF1TX4MIX_INPUT_2_VOLUME 910 
#define  ARIZONA_AIF1TX4MIX_INPUT_3_SOURCE 909 
#define  ARIZONA_AIF1TX4MIX_INPUT_3_VOLUME 908 
#define  ARIZONA_AIF1TX4MIX_INPUT_4_SOURCE 907 
#define  ARIZONA_AIF1TX4MIX_INPUT_4_VOLUME 906 
#define  ARIZONA_AIF1TX5MIX_INPUT_1_SOURCE 905 
#define  ARIZONA_AIF1TX5MIX_INPUT_1_VOLUME 904 
#define  ARIZONA_AIF1TX5MIX_INPUT_2_SOURCE 903 
#define  ARIZONA_AIF1TX5MIX_INPUT_2_VOLUME 902 
#define  ARIZONA_AIF1TX5MIX_INPUT_3_SOURCE 901 
#define  ARIZONA_AIF1TX5MIX_INPUT_3_VOLUME 900 
#define  ARIZONA_AIF1TX5MIX_INPUT_4_SOURCE 899 
#define  ARIZONA_AIF1TX5MIX_INPUT_4_VOLUME 898 
#define  ARIZONA_AIF1TX6MIX_INPUT_1_SOURCE 897 
#define  ARIZONA_AIF1TX6MIX_INPUT_1_VOLUME 896 
#define  ARIZONA_AIF1TX6MIX_INPUT_2_SOURCE 895 
#define  ARIZONA_AIF1TX6MIX_INPUT_2_VOLUME 894 
#define  ARIZONA_AIF1TX6MIX_INPUT_3_SOURCE 893 
#define  ARIZONA_AIF1TX6MIX_INPUT_3_VOLUME 892 
#define  ARIZONA_AIF1TX6MIX_INPUT_4_SOURCE 891 
#define  ARIZONA_AIF1TX6MIX_INPUT_4_VOLUME 890 
#define  ARIZONA_AIF1TX7MIX_INPUT_1_SOURCE 889 
#define  ARIZONA_AIF1TX7MIX_INPUT_1_VOLUME 888 
#define  ARIZONA_AIF1TX7MIX_INPUT_2_SOURCE 887 
#define  ARIZONA_AIF1TX7MIX_INPUT_2_VOLUME 886 
#define  ARIZONA_AIF1TX7MIX_INPUT_3_SOURCE 885 
#define  ARIZONA_AIF1TX7MIX_INPUT_3_VOLUME 884 
#define  ARIZONA_AIF1TX7MIX_INPUT_4_SOURCE 883 
#define  ARIZONA_AIF1TX7MIX_INPUT_4_VOLUME 882 
#define  ARIZONA_AIF1TX8MIX_INPUT_1_SOURCE 881 
#define  ARIZONA_AIF1TX8MIX_INPUT_1_VOLUME 880 
#define  ARIZONA_AIF1TX8MIX_INPUT_2_SOURCE 879 
#define  ARIZONA_AIF1TX8MIX_INPUT_2_VOLUME 878 
#define  ARIZONA_AIF1TX8MIX_INPUT_3_SOURCE 877 
#define  ARIZONA_AIF1TX8MIX_INPUT_3_VOLUME 876 
#define  ARIZONA_AIF1TX8MIX_INPUT_4_SOURCE 875 
#define  ARIZONA_AIF1TX8MIX_INPUT_4_VOLUME 874 
#define  ARIZONA_AIF1_BCLK_CTRL 873 
#define  ARIZONA_AIF1_FORMAT 872 
#define  ARIZONA_AIF1_FRAME_CTRL_1 871 
#define  ARIZONA_AIF1_FRAME_CTRL_10 870 
#define  ARIZONA_AIF1_FRAME_CTRL_11 869 
#define  ARIZONA_AIF1_FRAME_CTRL_12 868 
#define  ARIZONA_AIF1_FRAME_CTRL_13 867 
#define  ARIZONA_AIF1_FRAME_CTRL_14 866 
#define  ARIZONA_AIF1_FRAME_CTRL_15 865 
#define  ARIZONA_AIF1_FRAME_CTRL_16 864 
#define  ARIZONA_AIF1_FRAME_CTRL_17 863 
#define  ARIZONA_AIF1_FRAME_CTRL_18 862 
#define  ARIZONA_AIF1_FRAME_CTRL_2 861 
#define  ARIZONA_AIF1_FRAME_CTRL_3 860 
#define  ARIZONA_AIF1_FRAME_CTRL_4 859 
#define  ARIZONA_AIF1_FRAME_CTRL_5 858 
#define  ARIZONA_AIF1_FRAME_CTRL_6 857 
#define  ARIZONA_AIF1_FRAME_CTRL_7 856 
#define  ARIZONA_AIF1_FRAME_CTRL_8 855 
#define  ARIZONA_AIF1_FRAME_CTRL_9 854 
#define  ARIZONA_AIF1_RATE_CTRL 853 
#define  ARIZONA_AIF1_RX_BCLK_RATE 852 
#define  ARIZONA_AIF1_RX_ENABLES 851 
#define  ARIZONA_AIF1_RX_PIN_CTRL 850 
#define  ARIZONA_AIF1_TX_BCLK_RATE 849 
#define  ARIZONA_AIF1_TX_ENABLES 848 
#define  ARIZONA_AIF1_TX_PIN_CTRL 847 
#define  ARIZONA_AIF2TX1MIX_INPUT_1_SOURCE 846 
#define  ARIZONA_AIF2TX1MIX_INPUT_1_VOLUME 845 
#define  ARIZONA_AIF2TX1MIX_INPUT_2_SOURCE 844 
#define  ARIZONA_AIF2TX1MIX_INPUT_2_VOLUME 843 
#define  ARIZONA_AIF2TX1MIX_INPUT_3_SOURCE 842 
#define  ARIZONA_AIF2TX1MIX_INPUT_3_VOLUME 841 
#define  ARIZONA_AIF2TX1MIX_INPUT_4_SOURCE 840 
#define  ARIZONA_AIF2TX1MIX_INPUT_4_VOLUME 839 
#define  ARIZONA_AIF2TX2MIX_INPUT_1_SOURCE 838 
#define  ARIZONA_AIF2TX2MIX_INPUT_1_VOLUME 837 
#define  ARIZONA_AIF2TX2MIX_INPUT_2_SOURCE 836 
#define  ARIZONA_AIF2TX2MIX_INPUT_2_VOLUME 835 
#define  ARIZONA_AIF2TX2MIX_INPUT_3_SOURCE 834 
#define  ARIZONA_AIF2TX2MIX_INPUT_3_VOLUME 833 
#define  ARIZONA_AIF2TX2MIX_INPUT_4_SOURCE 832 
#define  ARIZONA_AIF2TX2MIX_INPUT_4_VOLUME 831 
#define  ARIZONA_AIF2_BCLK_CTRL 830 
#define  ARIZONA_AIF2_FORMAT 829 
#define  ARIZONA_AIF2_FRAME_CTRL_1 828 
#define  ARIZONA_AIF2_FRAME_CTRL_11 827 
#define  ARIZONA_AIF2_FRAME_CTRL_12 826 
#define  ARIZONA_AIF2_FRAME_CTRL_2 825 
#define  ARIZONA_AIF2_FRAME_CTRL_3 824 
#define  ARIZONA_AIF2_FRAME_CTRL_4 823 
#define  ARIZONA_AIF2_RATE_CTRL 822 
#define  ARIZONA_AIF2_RX_BCLK_RATE 821 
#define  ARIZONA_AIF2_RX_ENABLES 820 
#define  ARIZONA_AIF2_RX_PIN_CTRL 819 
#define  ARIZONA_AIF2_TX_BCLK_RATE 818 
#define  ARIZONA_AIF2_TX_ENABLES 817 
#define  ARIZONA_AIF2_TX_PIN_CTRL 816 
#define  ARIZONA_AIF3TX1MIX_INPUT_1_SOURCE 815 
#define  ARIZONA_AIF3TX1MIX_INPUT_1_VOLUME 814 
#define  ARIZONA_AIF3TX1MIX_INPUT_2_SOURCE 813 
#define  ARIZONA_AIF3TX1MIX_INPUT_2_VOLUME 812 
#define  ARIZONA_AIF3TX1MIX_INPUT_3_SOURCE 811 
#define  ARIZONA_AIF3TX1MIX_INPUT_3_VOLUME 810 
#define  ARIZONA_AIF3TX1MIX_INPUT_4_SOURCE 809 
#define  ARIZONA_AIF3TX1MIX_INPUT_4_VOLUME 808 
#define  ARIZONA_AIF3TX2MIX_INPUT_1_SOURCE 807 
#define  ARIZONA_AIF3TX2MIX_INPUT_1_VOLUME 806 
#define  ARIZONA_AIF3TX2MIX_INPUT_2_SOURCE 805 
#define  ARIZONA_AIF3TX2MIX_INPUT_2_VOLUME 804 
#define  ARIZONA_AIF3TX2MIX_INPUT_3_SOURCE 803 
#define  ARIZONA_AIF3TX2MIX_INPUT_3_VOLUME 802 
#define  ARIZONA_AIF3TX2MIX_INPUT_4_SOURCE 801 
#define  ARIZONA_AIF3TX2MIX_INPUT_4_VOLUME 800 
#define  ARIZONA_AIF3_BCLK_CTRL 799 
#define  ARIZONA_AIF3_FORMAT 798 
#define  ARIZONA_AIF3_FRAME_CTRL_1 797 
#define  ARIZONA_AIF3_FRAME_CTRL_11 796 
#define  ARIZONA_AIF3_FRAME_CTRL_12 795 
#define  ARIZONA_AIF3_FRAME_CTRL_2 794 
#define  ARIZONA_AIF3_FRAME_CTRL_3 793 
#define  ARIZONA_AIF3_FRAME_CTRL_4 792 
#define  ARIZONA_AIF3_RATE_CTRL 791 
#define  ARIZONA_AIF3_RX_BCLK_RATE 790 
#define  ARIZONA_AIF3_RX_ENABLES 789 
#define  ARIZONA_AIF3_RX_PIN_CTRL 788 
#define  ARIZONA_AIF3_TX_BCLK_RATE 787 
#define  ARIZONA_AIF3_TX_ENABLES 786 
#define  ARIZONA_AIF3_TX_PIN_CTRL 785 
#define  ARIZONA_ALWAYS_ON_TRIGGERS_SEQUENCE_SELECT_1 784 
#define  ARIZONA_ALWAYS_ON_TRIGGERS_SEQUENCE_SELECT_2 783 
#define  ARIZONA_ALWAYS_ON_TRIGGERS_SEQUENCE_SELECT_3 782 
#define  ARIZONA_ALWAYS_ON_TRIGGERS_SEQUENCE_SELECT_4 781 
#define  ARIZONA_ALWAYS_ON_TRIGGERS_SEQUENCE_SELECT_5 780 
#define  ARIZONA_ALWAYS_ON_TRIGGERS_SEQUENCE_SELECT_6 779 
#define  ARIZONA_AOD_IRQ1 778 
#define  ARIZONA_AOD_IRQ2 777 
#define  ARIZONA_AOD_IRQ_MASK_IRQ1 776 
#define  ARIZONA_AOD_IRQ_MASK_IRQ2 775 
#define  ARIZONA_AOD_IRQ_RAW_STATUS 774 
#define  ARIZONA_AOD_WKUP_AND_TRIG 773 
#define  ARIZONA_ASRC1LMIX_INPUT_1_SOURCE 772 
#define  ARIZONA_ASRC1RMIX_INPUT_1_SOURCE 771 
#define  ARIZONA_ASRC2LMIX_INPUT_1_SOURCE 770 
#define  ARIZONA_ASRC2RMIX_INPUT_1_SOURCE 769 
#define  ARIZONA_ASRC_ENABLE 768 
#define  ARIZONA_ASRC_RATE1 767 
#define  ARIZONA_ASRC_RATE2 766 
#define  ARIZONA_ASYNC_CLOCK_1 765 
#define  ARIZONA_ASYNC_SAMPLE_RATE_1 764 
#define  ARIZONA_ASYNC_SAMPLE_RATE_1_STATUS 763 
#define  ARIZONA_ASYNC_SAMPLE_RATE_2 762 
#define  ARIZONA_ASYNC_SAMPLE_RATE_2_STATUS 761 
#define  ARIZONA_CLOCK_32K_1 760 
#define  ARIZONA_COMFORT_NOISE_GENERATOR 759 
#define  ARIZONA_CTRL_IF_I2C1_CFG_1 758 
#define  ARIZONA_CTRL_IF_SPI_CFG_1 757 
#define  ARIZONA_DAC_AEC_CONTROL_1 756 
#define  ARIZONA_DAC_COMP_1 755 
#define  ARIZONA_DAC_COMP_2 754 
#define  ARIZONA_DAC_COMP_3 753 
#define  ARIZONA_DAC_COMP_4 752 
#define  ARIZONA_DAC_DIGITAL_VOLUME_1L 751 
#define  ARIZONA_DAC_DIGITAL_VOLUME_1R 750 
#define  ARIZONA_DAC_DIGITAL_VOLUME_2L 749 
#define  ARIZONA_DAC_DIGITAL_VOLUME_2R 748 
#define  ARIZONA_DAC_DIGITAL_VOLUME_3L 747 
#define  ARIZONA_DAC_DIGITAL_VOLUME_4L 746 
#define  ARIZONA_DAC_DIGITAL_VOLUME_4R 745 
#define  ARIZONA_DAC_DIGITAL_VOLUME_5L 744 
#define  ARIZONA_DAC_DIGITAL_VOLUME_5R 743 
#define  ARIZONA_DAC_VOLUME_LIMIT_1L 742 
#define  ARIZONA_DAC_VOLUME_LIMIT_1R 741 
#define  ARIZONA_DAC_VOLUME_LIMIT_2L 740 
#define  ARIZONA_DAC_VOLUME_LIMIT_2R 739 
#define  ARIZONA_DAC_VOLUME_LIMIT_3L 738 
#define  ARIZONA_DAC_VOLUME_LIMIT_5L 737 
#define  ARIZONA_DAC_VOLUME_LIMIT_5R 736 
#define  ARIZONA_DEVICE_REVISION 735 
#define  ARIZONA_DMIC1L_CONTROL 734 
#define  ARIZONA_DMIC1R_CONTROL 733 
#define  ARIZONA_DMIC2L_CONTROL 732 
#define  ARIZONA_DMIC2R_CONTROL 731 
#define  ARIZONA_DMIC3L_CONTROL 730 
#define  ARIZONA_DMIC3R_CONTROL 729 
#define  ARIZONA_DRC1LMIX_INPUT_1_SOURCE 728 
#define  ARIZONA_DRC1LMIX_INPUT_1_VOLUME 727 
#define  ARIZONA_DRC1LMIX_INPUT_2_SOURCE 726 
#define  ARIZONA_DRC1LMIX_INPUT_2_VOLUME 725 
#define  ARIZONA_DRC1LMIX_INPUT_3_SOURCE 724 
#define  ARIZONA_DRC1LMIX_INPUT_3_VOLUME 723 
#define  ARIZONA_DRC1LMIX_INPUT_4_SOURCE 722 
#define  ARIZONA_DRC1LMIX_INPUT_4_VOLUME 721 
#define  ARIZONA_DRC1RMIX_INPUT_1_SOURCE 720 
#define  ARIZONA_DRC1RMIX_INPUT_1_VOLUME 719 
#define  ARIZONA_DRC1RMIX_INPUT_2_SOURCE 718 
#define  ARIZONA_DRC1RMIX_INPUT_2_VOLUME 717 
#define  ARIZONA_DRC1RMIX_INPUT_3_SOURCE 716 
#define  ARIZONA_DRC1RMIX_INPUT_3_VOLUME 715 
#define  ARIZONA_DRC1RMIX_INPUT_4_SOURCE 714 
#define  ARIZONA_DRC1RMIX_INPUT_4_VOLUME 713 
#define  ARIZONA_DRC1_CTRL1 712 
#define  ARIZONA_DRC1_CTRL2 711 
#define  ARIZONA_DRC1_CTRL3 710 
#define  ARIZONA_DRC1_CTRL4 709 
#define  ARIZONA_DRC1_CTRL5 708 
#define  ARIZONA_DRE_CONTROL_2 707 
#define  ARIZONA_DRE_CONTROL_3 706 
#define  ARIZONA_DRE_ENABLE 705 
#define  ARIZONA_DSP1AUX1MIX_INPUT_1_SOURCE 704 
#define  ARIZONA_DSP1AUX2MIX_INPUT_1_SOURCE 703 
#define  ARIZONA_DSP1AUX3MIX_INPUT_1_SOURCE 702 
#define  ARIZONA_DSP1AUX4MIX_INPUT_1_SOURCE 701 
#define  ARIZONA_DSP1AUX5MIX_INPUT_1_SOURCE 700 
#define  ARIZONA_DSP1AUX6MIX_INPUT_1_SOURCE 699 
#define  ARIZONA_DSP1LMIX_INPUT_1_SOURCE 698 
#define  ARIZONA_DSP1LMIX_INPUT_1_VOLUME 697 
#define  ARIZONA_DSP1LMIX_INPUT_2_SOURCE 696 
#define  ARIZONA_DSP1LMIX_INPUT_2_VOLUME 695 
#define  ARIZONA_DSP1LMIX_INPUT_3_SOURCE 694 
#define  ARIZONA_DSP1LMIX_INPUT_3_VOLUME 693 
#define  ARIZONA_DSP1LMIX_INPUT_4_SOURCE 692 
#define  ARIZONA_DSP1LMIX_INPUT_4_VOLUME 691 
#define  ARIZONA_DSP1RMIX_INPUT_1_SOURCE 690 
#define  ARIZONA_DSP1RMIX_INPUT_1_VOLUME 689 
#define  ARIZONA_DSP1RMIX_INPUT_2_SOURCE 688 
#define  ARIZONA_DSP1RMIX_INPUT_2_VOLUME 687 
#define  ARIZONA_DSP1RMIX_INPUT_3_SOURCE 686 
#define  ARIZONA_DSP1RMIX_INPUT_3_VOLUME 685 
#define  ARIZONA_DSP1RMIX_INPUT_4_SOURCE 684 
#define  ARIZONA_DSP1RMIX_INPUT_4_VOLUME 683 
#define  ARIZONA_DSP1_CLOCKING_1 682 
#define  ARIZONA_DSP1_CONTROL_1 681 
#define  ARIZONA_DSP1_RDMA_BUFFER_1 680 
#define  ARIZONA_DSP1_RDMA_BUFFER_2 679 
#define  ARIZONA_DSP1_RDMA_BUFFER_3 678 
#define  ARIZONA_DSP1_RDMA_BUFFER_4 677 
#define  ARIZONA_DSP1_RDMA_BUFFER_5 676 
#define  ARIZONA_DSP1_RDMA_BUFFER_6 675 
#define  ARIZONA_DSP1_RDMA_CONFIG_1 674 
#define  ARIZONA_DSP1_SCRATCH_0 673 
#define  ARIZONA_DSP1_SCRATCH_1 672 
#define  ARIZONA_DSP1_SCRATCH_2 671 
#define  ARIZONA_DSP1_SCRATCH_3 670 
#define  ARIZONA_DSP1_STATUS_1 669 
#define  ARIZONA_DSP1_STATUS_2 668 
#define  ARIZONA_DSP1_STATUS_3 667 
#define  ARIZONA_DSP1_WDMA_BUFFER_1 666 
#define  ARIZONA_DSP1_WDMA_BUFFER_2 665 
#define  ARIZONA_DSP1_WDMA_BUFFER_3 664 
#define  ARIZONA_DSP1_WDMA_BUFFER_4 663 
#define  ARIZONA_DSP1_WDMA_BUFFER_5 662 
#define  ARIZONA_DSP1_WDMA_BUFFER_6 661 
#define  ARIZONA_DSP1_WDMA_BUFFER_7 660 
#define  ARIZONA_DSP1_WDMA_BUFFER_8 659 
#define  ARIZONA_DSP1_WDMA_CONFIG_1 658 
#define  ARIZONA_DSP1_WDMA_CONFIG_2 657 
#define  ARIZONA_DYNAMIC_FREQUENCY_SCALING_1 656 
#define  ARIZONA_EQ1MIX_INPUT_1_SOURCE 655 
#define  ARIZONA_EQ1MIX_INPUT_1_VOLUME 654 
#define  ARIZONA_EQ1MIX_INPUT_2_SOURCE 653 
#define  ARIZONA_EQ1MIX_INPUT_2_VOLUME 652 
#define  ARIZONA_EQ1MIX_INPUT_3_SOURCE 651 
#define  ARIZONA_EQ1MIX_INPUT_3_VOLUME 650 
#define  ARIZONA_EQ1MIX_INPUT_4_SOURCE 649 
#define  ARIZONA_EQ1MIX_INPUT_4_VOLUME 648 
#define  ARIZONA_EQ1_1 647 
#define  ARIZONA_EQ1_10 646 
#define  ARIZONA_EQ1_11 645 
#define  ARIZONA_EQ1_12 644 
#define  ARIZONA_EQ1_13 643 
#define  ARIZONA_EQ1_14 642 
#define  ARIZONA_EQ1_15 641 
#define  ARIZONA_EQ1_16 640 
#define  ARIZONA_EQ1_17 639 
#define  ARIZONA_EQ1_18 638 
#define  ARIZONA_EQ1_19 637 
#define  ARIZONA_EQ1_2 636 
#define  ARIZONA_EQ1_20 635 
#define  ARIZONA_EQ1_21 634 
#define  ARIZONA_EQ1_3 633 
#define  ARIZONA_EQ1_4 632 
#define  ARIZONA_EQ1_5 631 
#define  ARIZONA_EQ1_6 630 
#define  ARIZONA_EQ1_7 629 
#define  ARIZONA_EQ1_8 628 
#define  ARIZONA_EQ1_9 627 
#define  ARIZONA_EQ2MIX_INPUT_1_SOURCE 626 
#define  ARIZONA_EQ2MIX_INPUT_1_VOLUME 625 
#define  ARIZONA_EQ2MIX_INPUT_2_SOURCE 624 
#define  ARIZONA_EQ2MIX_INPUT_2_VOLUME 623 
#define  ARIZONA_EQ2MIX_INPUT_3_SOURCE 622 
#define  ARIZONA_EQ2MIX_INPUT_3_VOLUME 621 
#define  ARIZONA_EQ2MIX_INPUT_4_SOURCE 620 
#define  ARIZONA_EQ2MIX_INPUT_4_VOLUME 619 
#define  ARIZONA_EQ2_1 618 
#define  ARIZONA_EQ2_10 617 
#define  ARIZONA_EQ2_11 616 
#define  ARIZONA_EQ2_12 615 
#define  ARIZONA_EQ2_13 614 
#define  ARIZONA_EQ2_14 613 
#define  ARIZONA_EQ2_15 612 
#define  ARIZONA_EQ2_16 611 
#define  ARIZONA_EQ2_17 610 
#define  ARIZONA_EQ2_18 609 
#define  ARIZONA_EQ2_19 608 
#define  ARIZONA_EQ2_2 607 
#define  ARIZONA_EQ2_20 606 
#define  ARIZONA_EQ2_21 605 
#define  ARIZONA_EQ2_3 604 
#define  ARIZONA_EQ2_4 603 
#define  ARIZONA_EQ2_5 602 
#define  ARIZONA_EQ2_6 601 
#define  ARIZONA_EQ2_7 600 
#define  ARIZONA_EQ2_8 599 
#define  ARIZONA_EQ2_9 598 
#define  ARIZONA_EQ3MIX_INPUT_1_SOURCE 597 
#define  ARIZONA_EQ3MIX_INPUT_1_VOLUME 596 
#define  ARIZONA_EQ3MIX_INPUT_2_SOURCE 595 
#define  ARIZONA_EQ3MIX_INPUT_2_VOLUME 594 
#define  ARIZONA_EQ3MIX_INPUT_3_SOURCE 593 
#define  ARIZONA_EQ3MIX_INPUT_3_VOLUME 592 
#define  ARIZONA_EQ3MIX_INPUT_4_SOURCE 591 
#define  ARIZONA_EQ3MIX_INPUT_4_VOLUME 590 
#define  ARIZONA_EQ3_1 589 
#define  ARIZONA_EQ3_10 588 
#define  ARIZONA_EQ3_11 587 
#define  ARIZONA_EQ3_12 586 
#define  ARIZONA_EQ3_13 585 
#define  ARIZONA_EQ3_14 584 
#define  ARIZONA_EQ3_15 583 
#define  ARIZONA_EQ3_16 582 
#define  ARIZONA_EQ3_17 581 
#define  ARIZONA_EQ3_18 580 
#define  ARIZONA_EQ3_19 579 
#define  ARIZONA_EQ3_2 578 
#define  ARIZONA_EQ3_20 577 
#define  ARIZONA_EQ3_21 576 
#define  ARIZONA_EQ3_3 575 
#define  ARIZONA_EQ3_4 574 
#define  ARIZONA_EQ3_5 573 
#define  ARIZONA_EQ3_6 572 
#define  ARIZONA_EQ3_7 571 
#define  ARIZONA_EQ3_8 570 
#define  ARIZONA_EQ3_9 569 
#define  ARIZONA_EQ4MIX_INPUT_1_SOURCE 568 
#define  ARIZONA_EQ4MIX_INPUT_1_VOLUME 567 
#define  ARIZONA_EQ4MIX_INPUT_2_SOURCE 566 
#define  ARIZONA_EQ4MIX_INPUT_2_VOLUME 565 
#define  ARIZONA_EQ4MIX_INPUT_3_SOURCE 564 
#define  ARIZONA_EQ4MIX_INPUT_3_VOLUME 563 
#define  ARIZONA_EQ4MIX_INPUT_4_SOURCE 562 
#define  ARIZONA_EQ4MIX_INPUT_4_VOLUME 561 
#define  ARIZONA_EQ4_1 560 
#define  ARIZONA_EQ4_10 559 
#define  ARIZONA_EQ4_11 558 
#define  ARIZONA_EQ4_12 557 
#define  ARIZONA_EQ4_13 556 
#define  ARIZONA_EQ4_14 555 
#define  ARIZONA_EQ4_15 554 
#define  ARIZONA_EQ4_16 553 
#define  ARIZONA_EQ4_17 552 
#define  ARIZONA_EQ4_18 551 
#define  ARIZONA_EQ4_19 550 
#define  ARIZONA_EQ4_2 549 
#define  ARIZONA_EQ4_20 548 
#define  ARIZONA_EQ4_21 547 
#define  ARIZONA_EQ4_3 546 
#define  ARIZONA_EQ4_4 545 
#define  ARIZONA_EQ4_5 544 
#define  ARIZONA_EQ4_6 543 
#define  ARIZONA_EQ4_7 542 
#define  ARIZONA_EQ4_8 541 
#define  ARIZONA_EQ4_9 540 
#define  ARIZONA_FLL1_CONTROL_1 539 
#define  ARIZONA_FLL1_CONTROL_2 538 
#define  ARIZONA_FLL1_CONTROL_3 537 
#define  ARIZONA_FLL1_CONTROL_4 536 
#define  ARIZONA_FLL1_CONTROL_5 535 
#define  ARIZONA_FLL1_CONTROL_6 534 
#define  ARIZONA_FLL1_CONTROL_7 533 
#define  ARIZONA_FLL1_GPIO_CLOCK 532 
#define  ARIZONA_FLL1_SPREAD_SPECTRUM 531 
#define  ARIZONA_FLL1_SYNCHRONISER_1 530 
#define  ARIZONA_FLL1_SYNCHRONISER_2 529 
#define  ARIZONA_FLL1_SYNCHRONISER_3 528 
#define  ARIZONA_FLL1_SYNCHRONISER_4 527 
#define  ARIZONA_FLL1_SYNCHRONISER_5 526 
#define  ARIZONA_FLL1_SYNCHRONISER_6 525 
#define  ARIZONA_FLL1_SYNCHRONISER_7 524 
#define  ARIZONA_FLL2_CONTROL_1 523 
#define  ARIZONA_FLL2_CONTROL_2 522 
#define  ARIZONA_FLL2_CONTROL_3 521 
#define  ARIZONA_FLL2_CONTROL_4 520 
#define  ARIZONA_FLL2_CONTROL_5 519 
#define  ARIZONA_FLL2_CONTROL_6 518 
#define  ARIZONA_FLL2_CONTROL_7 517 
#define  ARIZONA_FLL2_GPIO_CLOCK 516 
#define  ARIZONA_FLL2_SPREAD_SPECTRUM 515 
#define  ARIZONA_FLL2_SYNCHRONISER_1 514 
#define  ARIZONA_FLL2_SYNCHRONISER_2 513 
#define  ARIZONA_FLL2_SYNCHRONISER_3 512 
#define  ARIZONA_FLL2_SYNCHRONISER_4 511 
#define  ARIZONA_FLL2_SYNCHRONISER_5 510 
#define  ARIZONA_FLL2_SYNCHRONISER_6 509 
#define  ARIZONA_FLL2_SYNCHRONISER_7 508 
#define  ARIZONA_FX_CTRL1 507 
#define  ARIZONA_FX_CTRL2 506 
#define  ARIZONA_GPIO1_CTRL 505 
#define  ARIZONA_GPIO2_CTRL 504 
#define  ARIZONA_GPIO3_CTRL 503 
#define  ARIZONA_GPIO4_CTRL 502 
#define  ARIZONA_GPIO5_CTRL 501 
#define  ARIZONA_GPIO_DEBOUNCE_CONFIG 500 
#define  ARIZONA_HAPTICS_CONTROL_1 499 
#define  ARIZONA_HAPTICS_CONTROL_2 498 
#define  ARIZONA_HAPTICS_PHASE_1_DURATION 497 
#define  ARIZONA_HAPTICS_PHASE_1_INTENSITY 496 
#define  ARIZONA_HAPTICS_PHASE_2_DURATION 495 
#define  ARIZONA_HAPTICS_PHASE_2_INTENSITY 494 
#define  ARIZONA_HAPTICS_PHASE_3_DURATION 493 
#define  ARIZONA_HAPTICS_PHASE_3_INTENSITY 492 
#define  ARIZONA_HAPTICS_STATUS 491 
#define  ARIZONA_HEADPHONE_DETECT_1 490 
#define  ARIZONA_HEADPHONE_DETECT_2 489 
#define  ARIZONA_HPLP1MIX_INPUT_1_SOURCE 488 
#define  ARIZONA_HPLP1MIX_INPUT_1_VOLUME 487 
#define  ARIZONA_HPLP1MIX_INPUT_2_SOURCE 486 
#define  ARIZONA_HPLP1MIX_INPUT_2_VOLUME 485 
#define  ARIZONA_HPLP1MIX_INPUT_3_SOURCE 484 
#define  ARIZONA_HPLP1MIX_INPUT_3_VOLUME 483 
#define  ARIZONA_HPLP1MIX_INPUT_4_SOURCE 482 
#define  ARIZONA_HPLP1MIX_INPUT_4_VOLUME 481 
#define  ARIZONA_HPLP2MIX_INPUT_1_SOURCE 480 
#define  ARIZONA_HPLP2MIX_INPUT_1_VOLUME 479 
#define  ARIZONA_HPLP2MIX_INPUT_2_SOURCE 478 
#define  ARIZONA_HPLP2MIX_INPUT_2_VOLUME 477 
#define  ARIZONA_HPLP2MIX_INPUT_3_SOURCE 476 
#define  ARIZONA_HPLP2MIX_INPUT_3_VOLUME 475 
#define  ARIZONA_HPLP2MIX_INPUT_4_SOURCE 474 
#define  ARIZONA_HPLP2MIX_INPUT_4_VOLUME 473 
#define  ARIZONA_HPLP3MIX_INPUT_1_SOURCE 472 
#define  ARIZONA_HPLP3MIX_INPUT_1_VOLUME 471 
#define  ARIZONA_HPLP3MIX_INPUT_2_SOURCE 470 
#define  ARIZONA_HPLP3MIX_INPUT_2_VOLUME 469 
#define  ARIZONA_HPLP3MIX_INPUT_3_SOURCE 468 
#define  ARIZONA_HPLP3MIX_INPUT_3_VOLUME 467 
#define  ARIZONA_HPLP3MIX_INPUT_4_SOURCE 466 
#define  ARIZONA_HPLP3MIX_INPUT_4_VOLUME 465 
#define  ARIZONA_HPLP4MIX_INPUT_1_SOURCE 464 
#define  ARIZONA_HPLP4MIX_INPUT_1_VOLUME 463 
#define  ARIZONA_HPLP4MIX_INPUT_2_SOURCE 462 
#define  ARIZONA_HPLP4MIX_INPUT_2_VOLUME 461 
#define  ARIZONA_HPLP4MIX_INPUT_3_SOURCE 460 
#define  ARIZONA_HPLP4MIX_INPUT_3_VOLUME 459 
#define  ARIZONA_HPLP4MIX_INPUT_4_SOURCE 458 
#define  ARIZONA_HPLP4MIX_INPUT_4_VOLUME 457 
#define  ARIZONA_HPLPF1_1 456 
#define  ARIZONA_HPLPF1_2 455 
#define  ARIZONA_HPLPF2_1 454 
#define  ARIZONA_HPLPF2_2 453 
#define  ARIZONA_HPLPF3_1 452 
#define  ARIZONA_HPLPF3_2 451 
#define  ARIZONA_HPLPF4_1 450 
#define  ARIZONA_HPLPF4_2 449 
#define  ARIZONA_HP_CTRL_1L 448 
#define  ARIZONA_HP_CTRL_1R 447 
#define  ARIZONA_HP_DACVAL 446 
#define  ARIZONA_IN1L_CONTROL 445 
#define  ARIZONA_IN1R_CONTROL 444 
#define  ARIZONA_IN2L_CONTROL 443 
#define  ARIZONA_IN2R_CONTROL 442 
#define  ARIZONA_IN3L_CONTROL 441 
#define  ARIZONA_IN3R_CONTROL 440 
#define  ARIZONA_INPUT_ENABLES 439 
#define  ARIZONA_INPUT_RATE 438 
#define  ARIZONA_INPUT_VOLUME_RAMP 437 
#define  ARIZONA_INTERRUPT_CONTROL 436 
#define  ARIZONA_INTERRUPT_RAW_STATUS_2 435 
#define  ARIZONA_INTERRUPT_RAW_STATUS_3 434 
#define  ARIZONA_INTERRUPT_RAW_STATUS_4 433 
#define  ARIZONA_INTERRUPT_RAW_STATUS_5 432 
#define  ARIZONA_INTERRUPT_RAW_STATUS_6 431 
#define  ARIZONA_INTERRUPT_RAW_STATUS_7 430 
#define  ARIZONA_INTERRUPT_RAW_STATUS_8 429 
#define  ARIZONA_INTERRUPT_STATUS_1 428 
#define  ARIZONA_INTERRUPT_STATUS_1_MASK 427 
#define  ARIZONA_INTERRUPT_STATUS_2 426 
#define  ARIZONA_INTERRUPT_STATUS_2_MASK 425 
#define  ARIZONA_INTERRUPT_STATUS_3 424 
#define  ARIZONA_INTERRUPT_STATUS_3_MASK 423 
#define  ARIZONA_INTERRUPT_STATUS_4 422 
#define  ARIZONA_INTERRUPT_STATUS_4_MASK 421 
#define  ARIZONA_INTERRUPT_STATUS_5 420 
#define  ARIZONA_INTERRUPT_STATUS_5_MASK 419 
#define  ARIZONA_IRQ2_CONTROL 418 
#define  ARIZONA_IRQ2_STATUS_1 417 
#define  ARIZONA_IRQ2_STATUS_1_MASK 416 
#define  ARIZONA_IRQ2_STATUS_2 415 
#define  ARIZONA_IRQ2_STATUS_2_MASK 414 
#define  ARIZONA_IRQ2_STATUS_3 413 
#define  ARIZONA_IRQ2_STATUS_3_MASK 412 
#define  ARIZONA_IRQ2_STATUS_4 411 
#define  ARIZONA_IRQ2_STATUS_4_MASK 410 
#define  ARIZONA_IRQ2_STATUS_5 409 
#define  ARIZONA_IRQ2_STATUS_5_MASK 408 
#define  ARIZONA_IRQ_CTRL_1 407 
#define  ARIZONA_IRQ_PIN_STATUS 406 
#define  ARIZONA_ISOLATION_CONTROL 405 
#define  ARIZONA_ISRC1DEC1MIX_INPUT_1_SOURCE 404 
#define  ARIZONA_ISRC1DEC2MIX_INPUT_1_SOURCE 403 
#define  ARIZONA_ISRC1INT1MIX_INPUT_1_SOURCE 402 
#define  ARIZONA_ISRC1INT2MIX_INPUT_1_SOURCE 401 
#define  ARIZONA_ISRC2DEC1MIX_INPUT_1_SOURCE 400 
#define  ARIZONA_ISRC2DEC2MIX_INPUT_1_SOURCE 399 
#define  ARIZONA_ISRC2INT1MIX_INPUT_1_SOURCE 398 
#define  ARIZONA_ISRC2INT2MIX_INPUT_1_SOURCE 397 
#define  ARIZONA_ISRC_1_CTRL_1 396 
#define  ARIZONA_ISRC_1_CTRL_2 395 
#define  ARIZONA_ISRC_1_CTRL_3 394 
#define  ARIZONA_ISRC_2_CTRL_1 393 
#define  ARIZONA_ISRC_2_CTRL_2 392 
#define  ARIZONA_ISRC_2_CTRL_3 391 
#define  ARIZONA_JACK_DETECT_ANALOGUE 390 
#define  ARIZONA_JACK_DETECT_DEBOUNCE 389 
#define  ARIZONA_LDO1_CONTROL_1 388 
#define  ARIZONA_LDO1_CONTROL_2 387 
#define  ARIZONA_LDO2_CONTROL_1 386 
#define  ARIZONA_MICD_CLAMP_CONTROL 385 
#define  ARIZONA_MICMIX_INPUT_1_SOURCE 384 
#define  ARIZONA_MICMIX_INPUT_1_VOLUME 383 
#define  ARIZONA_MICMIX_INPUT_2_SOURCE 382 
#define  ARIZONA_MICMIX_INPUT_2_VOLUME 381 
#define  ARIZONA_MICMIX_INPUT_3_SOURCE 380 
#define  ARIZONA_MICMIX_INPUT_3_VOLUME 379 
#define  ARIZONA_MICMIX_INPUT_4_SOURCE 378 
#define  ARIZONA_MICMIX_INPUT_4_VOLUME 377 
#define  ARIZONA_MIC_BIAS_CTRL_1 376 
#define  ARIZONA_MIC_BIAS_CTRL_2 375 
#define  ARIZONA_MIC_BIAS_CTRL_3 374 
#define  ARIZONA_MIC_CHARGE_PUMP_1 373 
#define  ARIZONA_MIC_DETECT_1 372 
#define  ARIZONA_MIC_DETECT_2 371 
#define  ARIZONA_MIC_DETECT_3 370 
#define  ARIZONA_MIC_DETECT_LEVEL_1 369 
#define  ARIZONA_MIC_DETECT_LEVEL_2 368 
#define  ARIZONA_MIC_DETECT_LEVEL_3 367 
#define  ARIZONA_MIC_DETECT_LEVEL_4 366 
#define  ARIZONA_MIC_NOISE_MIX_CONTROL_1 365 
#define  ARIZONA_MISC_PAD_CTRL_1 364 
#define  ARIZONA_MISC_PAD_CTRL_2 363 
#define  ARIZONA_MISC_PAD_CTRL_3 362 
#define  ARIZONA_MISC_PAD_CTRL_4 361 
#define  ARIZONA_MISC_PAD_CTRL_5 360 
#define  ARIZONA_MISC_PAD_CTRL_6 359 
#define  ARIZONA_NOISEMIX_INPUT_1_SOURCE 358 
#define  ARIZONA_NOISEMIX_INPUT_1_VOLUME 357 
#define  ARIZONA_NOISEMIX_INPUT_2_SOURCE 356 
#define  ARIZONA_NOISEMIX_INPUT_2_VOLUME 355 
#define  ARIZONA_NOISEMIX_INPUT_3_SOURCE 354 
#define  ARIZONA_NOISEMIX_INPUT_3_VOLUME 353 
#define  ARIZONA_NOISEMIX_INPUT_4_SOURCE 352 
#define  ARIZONA_NOISEMIX_INPUT_4_VOLUME 351 
#define  ARIZONA_NOISE_GATE_CONTROL 350 
#define  ARIZONA_NOISE_GATE_SELECT_1L 349 
#define  ARIZONA_NOISE_GATE_SELECT_1R 348 
#define  ARIZONA_NOISE_GATE_SELECT_2L 347 
#define  ARIZONA_NOISE_GATE_SELECT_2R 346 
#define  ARIZONA_NOISE_GATE_SELECT_3L 345 
#define  ARIZONA_NOISE_GATE_SELECT_4L 344 
#define  ARIZONA_NOISE_GATE_SELECT_4R 343 
#define  ARIZONA_NOISE_GATE_SELECT_5L 342 
#define  ARIZONA_NOISE_GATE_SELECT_5R 341 
#define  ARIZONA_OUT1LMIX_INPUT_1_SOURCE 340 
#define  ARIZONA_OUT1LMIX_INPUT_1_VOLUME 339 
#define  ARIZONA_OUT1LMIX_INPUT_2_SOURCE 338 
#define  ARIZONA_OUT1LMIX_INPUT_2_VOLUME 337 
#define  ARIZONA_OUT1LMIX_INPUT_3_SOURCE 336 
#define  ARIZONA_OUT1LMIX_INPUT_3_VOLUME 335 
#define  ARIZONA_OUT1LMIX_INPUT_4_SOURCE 334 
#define  ARIZONA_OUT1LMIX_INPUT_4_VOLUME 333 
#define  ARIZONA_OUT1RMIX_INPUT_1_SOURCE 332 
#define  ARIZONA_OUT1RMIX_INPUT_1_VOLUME 331 
#define  ARIZONA_OUT1RMIX_INPUT_2_SOURCE 330 
#define  ARIZONA_OUT1RMIX_INPUT_2_VOLUME 329 
#define  ARIZONA_OUT1RMIX_INPUT_3_SOURCE 328 
#define  ARIZONA_OUT1RMIX_INPUT_3_VOLUME 327 
#define  ARIZONA_OUT1RMIX_INPUT_4_SOURCE 326 
#define  ARIZONA_OUT1RMIX_INPUT_4_VOLUME 325 
#define  ARIZONA_OUT2LMIX_INPUT_1_SOURCE 324 
#define  ARIZONA_OUT2LMIX_INPUT_1_VOLUME 323 
#define  ARIZONA_OUT2LMIX_INPUT_2_SOURCE 322 
#define  ARIZONA_OUT2LMIX_INPUT_2_VOLUME 321 
#define  ARIZONA_OUT2LMIX_INPUT_3_SOURCE 320 
#define  ARIZONA_OUT2LMIX_INPUT_3_VOLUME 319 
#define  ARIZONA_OUT2LMIX_INPUT_4_SOURCE 318 
#define  ARIZONA_OUT2LMIX_INPUT_4_VOLUME 317 
#define  ARIZONA_OUT2RMIX_INPUT_1_SOURCE 316 
#define  ARIZONA_OUT2RMIX_INPUT_1_VOLUME 315 
#define  ARIZONA_OUT2RMIX_INPUT_2_SOURCE 314 
#define  ARIZONA_OUT2RMIX_INPUT_2_VOLUME 313 
#define  ARIZONA_OUT2RMIX_INPUT_3_SOURCE 312 
#define  ARIZONA_OUT2RMIX_INPUT_3_VOLUME 311 
#define  ARIZONA_OUT2RMIX_INPUT_4_SOURCE 310 
#define  ARIZONA_OUT2RMIX_INPUT_4_VOLUME 309 
#define  ARIZONA_OUT3LMIX_INPUT_1_SOURCE 308 
#define  ARIZONA_OUT3LMIX_INPUT_1_VOLUME 307 
#define  ARIZONA_OUT3LMIX_INPUT_2_SOURCE 306 
#define  ARIZONA_OUT3LMIX_INPUT_2_VOLUME 305 
#define  ARIZONA_OUT3LMIX_INPUT_3_SOURCE 304 
#define  ARIZONA_OUT3LMIX_INPUT_3_VOLUME 303 
#define  ARIZONA_OUT3LMIX_INPUT_4_SOURCE 302 
#define  ARIZONA_OUT3LMIX_INPUT_4_VOLUME 301 
#define  ARIZONA_OUT4LMIX_INPUT_1_SOURCE 300 
#define  ARIZONA_OUT4LMIX_INPUT_1_VOLUME 299 
#define  ARIZONA_OUT4LMIX_INPUT_2_SOURCE 298 
#define  ARIZONA_OUT4LMIX_INPUT_2_VOLUME 297 
#define  ARIZONA_OUT4LMIX_INPUT_3_SOURCE 296 
#define  ARIZONA_OUT4LMIX_INPUT_3_VOLUME 295 
#define  ARIZONA_OUT4LMIX_INPUT_4_SOURCE 294 
#define  ARIZONA_OUT4LMIX_INPUT_4_VOLUME 293 
#define  ARIZONA_OUT4RMIX_INPUT_1_SOURCE 292 
#define  ARIZONA_OUT4RMIX_INPUT_1_VOLUME 291 
#define  ARIZONA_OUT4RMIX_INPUT_2_SOURCE 290 
#define  ARIZONA_OUT4RMIX_INPUT_2_VOLUME 289 
#define  ARIZONA_OUT4RMIX_INPUT_3_SOURCE 288 
#define  ARIZONA_OUT4RMIX_INPUT_3_VOLUME 287 
#define  ARIZONA_OUT4RMIX_INPUT_4_SOURCE 286 
#define  ARIZONA_OUT4RMIX_INPUT_4_VOLUME 285 
#define  ARIZONA_OUT5LMIX_INPUT_1_SOURCE 284 
#define  ARIZONA_OUT5LMIX_INPUT_1_VOLUME 283 
#define  ARIZONA_OUT5LMIX_INPUT_2_SOURCE 282 
#define  ARIZONA_OUT5LMIX_INPUT_2_VOLUME 281 
#define  ARIZONA_OUT5LMIX_INPUT_3_SOURCE 280 
#define  ARIZONA_OUT5LMIX_INPUT_3_VOLUME 279 
#define  ARIZONA_OUT5LMIX_INPUT_4_SOURCE 278 
#define  ARIZONA_OUT5LMIX_INPUT_4_VOLUME 277 
#define  ARIZONA_OUT5RMIX_INPUT_1_SOURCE 276 
#define  ARIZONA_OUT5RMIX_INPUT_1_VOLUME 275 
#define  ARIZONA_OUT5RMIX_INPUT_2_SOURCE 274 
#define  ARIZONA_OUT5RMIX_INPUT_2_VOLUME 273 
#define  ARIZONA_OUT5RMIX_INPUT_3_SOURCE 272 
#define  ARIZONA_OUT5RMIX_INPUT_3_VOLUME 271 
#define  ARIZONA_OUT5RMIX_INPUT_4_SOURCE 270 
#define  ARIZONA_OUT5RMIX_INPUT_4_VOLUME 269 
#define  ARIZONA_OUTPUT_ASYNC_CLOCK 268 
#define  ARIZONA_OUTPUT_ENABLES_1 267 
#define  ARIZONA_OUTPUT_PATH_CONFIG_1L 266 
#define  ARIZONA_OUTPUT_PATH_CONFIG_1R 265 
#define  ARIZONA_OUTPUT_PATH_CONFIG_2L 264 
#define  ARIZONA_OUTPUT_PATH_CONFIG_2R 263 
#define  ARIZONA_OUTPUT_PATH_CONFIG_3L 262 
#define  ARIZONA_OUTPUT_PATH_CONFIG_4L 261 
#define  ARIZONA_OUTPUT_PATH_CONFIG_5L 260 
#define  ARIZONA_OUTPUT_RATE_1 259 
#define  ARIZONA_OUTPUT_STATUS_1 258 
#define  ARIZONA_OUTPUT_SYSTEM_CLOCK 257 
#define  ARIZONA_OUTPUT_VOLUME_RAMP 256 
#define  ARIZONA_OUT_VOLUME_4L 255 
#define  ARIZONA_OUT_VOLUME_4R 254 
#define  ARIZONA_PDM_SPK1_CTRL_1 253 
#define  ARIZONA_PDM_SPK1_CTRL_2 252 
#define  ARIZONA_PWM1MIX_INPUT_1_SOURCE 251 
#define  ARIZONA_PWM1MIX_INPUT_1_VOLUME 250 
#define  ARIZONA_PWM1MIX_INPUT_2_SOURCE 249 
#define  ARIZONA_PWM1MIX_INPUT_2_VOLUME 248 
#define  ARIZONA_PWM1MIX_INPUT_3_SOURCE 247 
#define  ARIZONA_PWM1MIX_INPUT_3_VOLUME 246 
#define  ARIZONA_PWM1MIX_INPUT_4_SOURCE 245 
#define  ARIZONA_PWM1MIX_INPUT_4_VOLUME 244 
#define  ARIZONA_PWM2MIX_INPUT_1_SOURCE 243 
#define  ARIZONA_PWM2MIX_INPUT_1_VOLUME 242 
#define  ARIZONA_PWM2MIX_INPUT_2_SOURCE 241 
#define  ARIZONA_PWM2MIX_INPUT_2_VOLUME 240 
#define  ARIZONA_PWM2MIX_INPUT_3_SOURCE 239 
#define  ARIZONA_PWM2MIX_INPUT_3_VOLUME 238 
#define  ARIZONA_PWM2MIX_INPUT_4_SOURCE 237 
#define  ARIZONA_PWM2MIX_INPUT_4_VOLUME 236 
#define  ARIZONA_PWM_DRIVE_1 235 
#define  ARIZONA_PWM_DRIVE_2 234 
#define  ARIZONA_PWM_DRIVE_3 233 
#define  ARIZONA_RATE_ESTIMATOR_1 232 
#define  ARIZONA_RATE_ESTIMATOR_2 231 
#define  ARIZONA_RATE_ESTIMATOR_3 230 
#define  ARIZONA_RATE_ESTIMATOR_4 229 
#define  ARIZONA_RATE_ESTIMATOR_5 228 
#define  ARIZONA_SAMPLE_RATE_1 227 
#define  ARIZONA_SAMPLE_RATE_1_STATUS 226 
#define  ARIZONA_SAMPLE_RATE_2 225 
#define  ARIZONA_SAMPLE_RATE_2_STATUS 224 
#define  ARIZONA_SAMPLE_RATE_3 223 
#define  ARIZONA_SAMPLE_RATE_3_STATUS 222 
#define  ARIZONA_SAMPLE_RATE_SEQUENCE_SELECT_1 221 
#define  ARIZONA_SAMPLE_RATE_SEQUENCE_SELECT_2 220 
#define  ARIZONA_SAMPLE_RATE_SEQUENCE_SELECT_3 219 
#define  ARIZONA_SAMPLE_RATE_SEQUENCE_SELECT_4 218 
#define  ARIZONA_SEQUENCE_CONTROL 217 
#define  ARIZONA_SLIMBUS_FRAMER_REF_GEAR 216 
#define  ARIZONA_SLIMBUS_RATES_1 215 
#define  ARIZONA_SLIMBUS_RATES_2 214 
#define  ARIZONA_SLIMBUS_RATES_3 213 
#define  ARIZONA_SLIMBUS_RATES_4 212 
#define  ARIZONA_SLIMBUS_RATES_5 211 
#define  ARIZONA_SLIMBUS_RATES_6 210 
#define  ARIZONA_SLIMBUS_RATES_7 209 
#define  ARIZONA_SLIMBUS_RATES_8 208 
#define  ARIZONA_SLIMBUS_RX_CHANNEL_ENABLE 207 
#define  ARIZONA_SLIMBUS_RX_PORT_STATUS 206 
#define  ARIZONA_SLIMBUS_TX_CHANNEL_ENABLE 205 
#define  ARIZONA_SLIMBUS_TX_PORT_STATUS 204 
#define  ARIZONA_SLIMTX1MIX_INPUT_1_SOURCE 203 
#define  ARIZONA_SLIMTX1MIX_INPUT_1_VOLUME 202 
#define  ARIZONA_SLIMTX1MIX_INPUT_2_SOURCE 201 
#define  ARIZONA_SLIMTX1MIX_INPUT_2_VOLUME 200 
#define  ARIZONA_SLIMTX1MIX_INPUT_3_SOURCE 199 
#define  ARIZONA_SLIMTX1MIX_INPUT_3_VOLUME 198 
#define  ARIZONA_SLIMTX1MIX_INPUT_4_SOURCE 197 
#define  ARIZONA_SLIMTX1MIX_INPUT_4_VOLUME 196 
#define  ARIZONA_SLIMTX2MIX_INPUT_1_SOURCE 195 
#define  ARIZONA_SLIMTX2MIX_INPUT_1_VOLUME 194 
#define  ARIZONA_SLIMTX2MIX_INPUT_2_SOURCE 193 
#define  ARIZONA_SLIMTX2MIX_INPUT_2_VOLUME 192 
#define  ARIZONA_SLIMTX2MIX_INPUT_3_SOURCE 191 
#define  ARIZONA_SLIMTX2MIX_INPUT_3_VOLUME 190 
#define  ARIZONA_SLIMTX2MIX_INPUT_4_SOURCE 189 
#define  ARIZONA_SLIMTX2MIX_INPUT_4_VOLUME 188 
#define  ARIZONA_SLIMTX3MIX_INPUT_1_SOURCE 187 
#define  ARIZONA_SLIMTX3MIX_INPUT_1_VOLUME 186 
#define  ARIZONA_SLIMTX3MIX_INPUT_2_SOURCE 185 
#define  ARIZONA_SLIMTX3MIX_INPUT_2_VOLUME 184 
#define  ARIZONA_SLIMTX3MIX_INPUT_3_SOURCE 183 
#define  ARIZONA_SLIMTX3MIX_INPUT_3_VOLUME 182 
#define  ARIZONA_SLIMTX3MIX_INPUT_4_SOURCE 181 
#define  ARIZONA_SLIMTX3MIX_INPUT_4_VOLUME 180 
#define  ARIZONA_SLIMTX4MIX_INPUT_1_SOURCE 179 
#define  ARIZONA_SLIMTX4MIX_INPUT_1_VOLUME 178 
#define  ARIZONA_SLIMTX4MIX_INPUT_2_SOURCE 177 
#define  ARIZONA_SLIMTX4MIX_INPUT_2_VOLUME 176 
#define  ARIZONA_SLIMTX4MIX_INPUT_3_SOURCE 175 
#define  ARIZONA_SLIMTX4MIX_INPUT_3_VOLUME 174 
#define  ARIZONA_SLIMTX4MIX_INPUT_4_SOURCE 173 
#define  ARIZONA_SLIMTX4MIX_INPUT_4_VOLUME 172 
#define  ARIZONA_SLIMTX5MIX_INPUT_1_SOURCE 171 
#define  ARIZONA_SLIMTX5MIX_INPUT_1_VOLUME 170 
#define  ARIZONA_SLIMTX5MIX_INPUT_2_SOURCE 169 
#define  ARIZONA_SLIMTX5MIX_INPUT_2_VOLUME 168 
#define  ARIZONA_SLIMTX5MIX_INPUT_3_SOURCE 167 
#define  ARIZONA_SLIMTX5MIX_INPUT_3_VOLUME 166 
#define  ARIZONA_SLIMTX5MIX_INPUT_4_SOURCE 165 
#define  ARIZONA_SLIMTX5MIX_INPUT_4_VOLUME 164 
#define  ARIZONA_SLIMTX6MIX_INPUT_1_SOURCE 163 
#define  ARIZONA_SLIMTX6MIX_INPUT_1_VOLUME 162 
#define  ARIZONA_SLIMTX6MIX_INPUT_2_SOURCE 161 
#define  ARIZONA_SLIMTX6MIX_INPUT_2_VOLUME 160 
#define  ARIZONA_SLIMTX6MIX_INPUT_3_SOURCE 159 
#define  ARIZONA_SLIMTX6MIX_INPUT_3_VOLUME 158 
#define  ARIZONA_SLIMTX6MIX_INPUT_4_SOURCE 157 
#define  ARIZONA_SLIMTX6MIX_INPUT_4_VOLUME 156 
#define  ARIZONA_SLIMTX7MIX_INPUT_1_SOURCE 155 
#define  ARIZONA_SLIMTX7MIX_INPUT_1_VOLUME 154 
#define  ARIZONA_SLIMTX7MIX_INPUT_2_SOURCE 153 
#define  ARIZONA_SLIMTX7MIX_INPUT_2_VOLUME 152 
#define  ARIZONA_SLIMTX7MIX_INPUT_3_SOURCE 151 
#define  ARIZONA_SLIMTX7MIX_INPUT_3_VOLUME 150 
#define  ARIZONA_SLIMTX7MIX_INPUT_4_SOURCE 149 
#define  ARIZONA_SLIMTX7MIX_INPUT_4_VOLUME 148 
#define  ARIZONA_SLIMTX8MIX_INPUT_1_SOURCE 147 
#define  ARIZONA_SLIMTX8MIX_INPUT_1_VOLUME 146 
#define  ARIZONA_SLIMTX8MIX_INPUT_2_SOURCE 145 
#define  ARIZONA_SLIMTX8MIX_INPUT_2_VOLUME 144 
#define  ARIZONA_SLIMTX8MIX_INPUT_3_SOURCE 143 
#define  ARIZONA_SLIMTX8MIX_INPUT_3_VOLUME 142 
#define  ARIZONA_SLIMTX8MIX_INPUT_4_SOURCE 141 
#define  ARIZONA_SLIMTX8MIX_INPUT_4_VOLUME 140 
#define  ARIZONA_SOFTWARE_RESET 139 
#define  ARIZONA_SYSTEM_CLOCK_1 138 
#define  ARIZONA_TONE_GENERATOR_1 137 
#define  ARIZONA_TONE_GENERATOR_2 136 
#define  ARIZONA_TONE_GENERATOR_3 135 
#define  ARIZONA_TONE_GENERATOR_4 134 
#define  ARIZONA_TONE_GENERATOR_5 133 
#define  ARIZONA_WAKE_CONTROL 132 
#define  ARIZONA_WRITE_SEQUENCER_CTRL_0 131 
#define  ARIZONA_WRITE_SEQUENCER_CTRL_1 130 
#define  ARIZONA_WRITE_SEQUENCER_CTRL_2 129 
#define  ARIZONA_WRITE_SEQUENCER_CTRL_3 128 

__attribute__((used)) static bool wm5102_readable_register(struct device *dev, unsigned int reg)
{
	switch (reg) {
	case ARIZONA_SOFTWARE_RESET:
	case ARIZONA_DEVICE_REVISION:
	case ARIZONA_CTRL_IF_SPI_CFG_1:
	case ARIZONA_CTRL_IF_I2C1_CFG_1:
	case ARIZONA_WRITE_SEQUENCER_CTRL_0:
	case ARIZONA_WRITE_SEQUENCER_CTRL_1:
	case ARIZONA_WRITE_SEQUENCER_CTRL_2:
	case ARIZONA_WRITE_SEQUENCER_CTRL_3:
	case ARIZONA_TONE_GENERATOR_1:
	case ARIZONA_TONE_GENERATOR_2:
	case ARIZONA_TONE_GENERATOR_3:
	case ARIZONA_TONE_GENERATOR_4:
	case ARIZONA_TONE_GENERATOR_5:
	case ARIZONA_PWM_DRIVE_1:
	case ARIZONA_PWM_DRIVE_2:
	case ARIZONA_PWM_DRIVE_3:
	case ARIZONA_WAKE_CONTROL:
	case ARIZONA_SEQUENCE_CONTROL:
	case ARIZONA_SAMPLE_RATE_SEQUENCE_SELECT_1:
	case ARIZONA_SAMPLE_RATE_SEQUENCE_SELECT_2:
	case ARIZONA_SAMPLE_RATE_SEQUENCE_SELECT_3:
	case ARIZONA_SAMPLE_RATE_SEQUENCE_SELECT_4:
	case ARIZONA_ALWAYS_ON_TRIGGERS_SEQUENCE_SELECT_1:
	case ARIZONA_ALWAYS_ON_TRIGGERS_SEQUENCE_SELECT_2:
	case ARIZONA_ALWAYS_ON_TRIGGERS_SEQUENCE_SELECT_3:
	case ARIZONA_ALWAYS_ON_TRIGGERS_SEQUENCE_SELECT_4:
	case ARIZONA_ALWAYS_ON_TRIGGERS_SEQUENCE_SELECT_5:
	case ARIZONA_ALWAYS_ON_TRIGGERS_SEQUENCE_SELECT_6:
	case ARIZONA_COMFORT_NOISE_GENERATOR:
	case ARIZONA_HAPTICS_CONTROL_1:
	case ARIZONA_HAPTICS_CONTROL_2:
	case ARIZONA_HAPTICS_PHASE_1_INTENSITY:
	case ARIZONA_HAPTICS_PHASE_1_DURATION:
	case ARIZONA_HAPTICS_PHASE_2_INTENSITY:
	case ARIZONA_HAPTICS_PHASE_2_DURATION:
	case ARIZONA_HAPTICS_PHASE_3_INTENSITY:
	case ARIZONA_HAPTICS_PHASE_3_DURATION:
	case ARIZONA_HAPTICS_STATUS:
	case ARIZONA_CLOCK_32K_1:
	case ARIZONA_SYSTEM_CLOCK_1:
	case ARIZONA_SAMPLE_RATE_1:
	case ARIZONA_SAMPLE_RATE_2:
	case ARIZONA_SAMPLE_RATE_3:
	case ARIZONA_SAMPLE_RATE_1_STATUS:
	case ARIZONA_SAMPLE_RATE_2_STATUS:
	case ARIZONA_SAMPLE_RATE_3_STATUS:
	case ARIZONA_ASYNC_CLOCK_1:
	case ARIZONA_ASYNC_SAMPLE_RATE_1:
	case ARIZONA_ASYNC_SAMPLE_RATE_1_STATUS:
	case ARIZONA_ASYNC_SAMPLE_RATE_2:
	case ARIZONA_ASYNC_SAMPLE_RATE_2_STATUS:
	case ARIZONA_OUTPUT_SYSTEM_CLOCK:
	case ARIZONA_OUTPUT_ASYNC_CLOCK:
	case ARIZONA_RATE_ESTIMATOR_1:
	case ARIZONA_RATE_ESTIMATOR_2:
	case ARIZONA_RATE_ESTIMATOR_3:
	case ARIZONA_RATE_ESTIMATOR_4:
	case ARIZONA_RATE_ESTIMATOR_5:
	case ARIZONA_DYNAMIC_FREQUENCY_SCALING_1:
	case ARIZONA_FLL1_CONTROL_1:
	case ARIZONA_FLL1_CONTROL_2:
	case ARIZONA_FLL1_CONTROL_3:
	case ARIZONA_FLL1_CONTROL_4:
	case ARIZONA_FLL1_CONTROL_5:
	case ARIZONA_FLL1_CONTROL_6:
	case ARIZONA_FLL1_CONTROL_7:
	case ARIZONA_FLL1_SYNCHRONISER_1:
	case ARIZONA_FLL1_SYNCHRONISER_2:
	case ARIZONA_FLL1_SYNCHRONISER_3:
	case ARIZONA_FLL1_SYNCHRONISER_4:
	case ARIZONA_FLL1_SYNCHRONISER_5:
	case ARIZONA_FLL1_SYNCHRONISER_6:
	case ARIZONA_FLL1_SYNCHRONISER_7:
	case ARIZONA_FLL1_SPREAD_SPECTRUM:
	case ARIZONA_FLL1_GPIO_CLOCK:
	case ARIZONA_FLL2_CONTROL_1:
	case ARIZONA_FLL2_CONTROL_2:
	case ARIZONA_FLL2_CONTROL_3:
	case ARIZONA_FLL2_CONTROL_4:
	case ARIZONA_FLL2_CONTROL_5:
	case ARIZONA_FLL2_CONTROL_6:
	case ARIZONA_FLL2_CONTROL_7:
	case ARIZONA_FLL2_SYNCHRONISER_1:
	case ARIZONA_FLL2_SYNCHRONISER_2:
	case ARIZONA_FLL2_SYNCHRONISER_3:
	case ARIZONA_FLL2_SYNCHRONISER_4:
	case ARIZONA_FLL2_SYNCHRONISER_5:
	case ARIZONA_FLL2_SYNCHRONISER_6:
	case ARIZONA_FLL2_SYNCHRONISER_7:
	case ARIZONA_FLL2_SPREAD_SPECTRUM:
	case ARIZONA_FLL2_GPIO_CLOCK:
	case ARIZONA_MIC_CHARGE_PUMP_1:
	case ARIZONA_LDO1_CONTROL_1:
	case ARIZONA_LDO1_CONTROL_2:
	case ARIZONA_LDO2_CONTROL_1:
	case ARIZONA_MIC_BIAS_CTRL_1:
	case ARIZONA_MIC_BIAS_CTRL_2:
	case ARIZONA_MIC_BIAS_CTRL_3:
	case ARIZONA_HP_CTRL_1L:
	case ARIZONA_HP_CTRL_1R:
	case ARIZONA_ACCESSORY_DETECT_MODE_1:
	case ARIZONA_HEADPHONE_DETECT_1:
	case ARIZONA_HEADPHONE_DETECT_2:
	case ARIZONA_HP_DACVAL:
	case ARIZONA_MICD_CLAMP_CONTROL:
	case ARIZONA_MIC_DETECT_1:
	case ARIZONA_MIC_DETECT_2:
	case ARIZONA_MIC_DETECT_3:
	case ARIZONA_MIC_DETECT_LEVEL_1:
	case ARIZONA_MIC_DETECT_LEVEL_2:
	case ARIZONA_MIC_DETECT_LEVEL_3:
	case ARIZONA_MIC_DETECT_LEVEL_4:
	case ARIZONA_MIC_NOISE_MIX_CONTROL_1:
	case ARIZONA_ISOLATION_CONTROL:
	case ARIZONA_JACK_DETECT_ANALOGUE:
	case ARIZONA_INPUT_ENABLES:
	case ARIZONA_INPUT_RATE:
	case ARIZONA_INPUT_VOLUME_RAMP:
	case ARIZONA_IN1L_CONTROL:
	case ARIZONA_ADC_DIGITAL_VOLUME_1L:
	case ARIZONA_DMIC1L_CONTROL:
	case ARIZONA_IN1R_CONTROL:
	case ARIZONA_ADC_DIGITAL_VOLUME_1R:
	case ARIZONA_DMIC1R_CONTROL:
	case ARIZONA_IN2L_CONTROL:
	case ARIZONA_ADC_DIGITAL_VOLUME_2L:
	case ARIZONA_DMIC2L_CONTROL:
	case ARIZONA_IN2R_CONTROL:
	case ARIZONA_ADC_DIGITAL_VOLUME_2R:
	case ARIZONA_DMIC2R_CONTROL:
	case ARIZONA_IN3L_CONTROL:
	case ARIZONA_ADC_DIGITAL_VOLUME_3L:
	case ARIZONA_DMIC3L_CONTROL:
	case ARIZONA_IN3R_CONTROL:
	case ARIZONA_ADC_DIGITAL_VOLUME_3R:
	case ARIZONA_DMIC3R_CONTROL:
	case ARIZONA_OUTPUT_ENABLES_1:
	case ARIZONA_OUTPUT_STATUS_1:
	case ARIZONA_OUTPUT_RATE_1:
	case ARIZONA_OUTPUT_VOLUME_RAMP:
	case ARIZONA_OUTPUT_PATH_CONFIG_1L:
	case ARIZONA_DAC_DIGITAL_VOLUME_1L:
	case ARIZONA_DAC_VOLUME_LIMIT_1L:
	case ARIZONA_NOISE_GATE_SELECT_1L:
	case ARIZONA_OUTPUT_PATH_CONFIG_1R:
	case ARIZONA_DAC_DIGITAL_VOLUME_1R:
	case ARIZONA_DAC_VOLUME_LIMIT_1R:
	case ARIZONA_NOISE_GATE_SELECT_1R:
	case ARIZONA_OUTPUT_PATH_CONFIG_2L:
	case ARIZONA_DAC_DIGITAL_VOLUME_2L:
	case ARIZONA_DAC_VOLUME_LIMIT_2L:
	case ARIZONA_NOISE_GATE_SELECT_2L:
	case ARIZONA_OUTPUT_PATH_CONFIG_2R:
	case ARIZONA_DAC_DIGITAL_VOLUME_2R:
	case ARIZONA_DAC_VOLUME_LIMIT_2R:
	case ARIZONA_NOISE_GATE_SELECT_2R:
	case ARIZONA_OUTPUT_PATH_CONFIG_3L:
	case ARIZONA_DAC_DIGITAL_VOLUME_3L:
	case ARIZONA_DAC_VOLUME_LIMIT_3L:
	case ARIZONA_NOISE_GATE_SELECT_3L:
	case ARIZONA_OUTPUT_PATH_CONFIG_4L:
	case ARIZONA_DAC_DIGITAL_VOLUME_4L:
	case ARIZONA_OUT_VOLUME_4L:
	case ARIZONA_NOISE_GATE_SELECT_4L:
	case ARIZONA_DAC_DIGITAL_VOLUME_4R:
	case ARIZONA_OUT_VOLUME_4R:
	case ARIZONA_NOISE_GATE_SELECT_4R:
	case ARIZONA_OUTPUT_PATH_CONFIG_5L:
	case ARIZONA_DAC_DIGITAL_VOLUME_5L:
	case ARIZONA_DAC_VOLUME_LIMIT_5L:
	case ARIZONA_NOISE_GATE_SELECT_5L:
	case ARIZONA_DAC_DIGITAL_VOLUME_5R:
	case ARIZONA_DAC_VOLUME_LIMIT_5R:
	case ARIZONA_NOISE_GATE_SELECT_5R:
	case ARIZONA_DRE_ENABLE:
	case ARIZONA_DRE_CONTROL_2:
	case ARIZONA_DRE_CONTROL_3:
	case ARIZONA_DAC_AEC_CONTROL_1:
	case ARIZONA_NOISE_GATE_CONTROL:
	case ARIZONA_PDM_SPK1_CTRL_1:
	case ARIZONA_PDM_SPK1_CTRL_2:
	case ARIZONA_DAC_COMP_1:
	case ARIZONA_DAC_COMP_2:
	case ARIZONA_DAC_COMP_3:
	case ARIZONA_DAC_COMP_4:
	case ARIZONA_AIF1_BCLK_CTRL:
	case ARIZONA_AIF1_TX_PIN_CTRL:
	case ARIZONA_AIF1_RX_PIN_CTRL:
	case ARIZONA_AIF1_RATE_CTRL:
	case ARIZONA_AIF1_FORMAT:
	case ARIZONA_AIF1_TX_BCLK_RATE:
	case ARIZONA_AIF1_RX_BCLK_RATE:
	case ARIZONA_AIF1_FRAME_CTRL_1:
	case ARIZONA_AIF1_FRAME_CTRL_2:
	case ARIZONA_AIF1_FRAME_CTRL_3:
	case ARIZONA_AIF1_FRAME_CTRL_4:
	case ARIZONA_AIF1_FRAME_CTRL_5:
	case ARIZONA_AIF1_FRAME_CTRL_6:
	case ARIZONA_AIF1_FRAME_CTRL_7:
	case ARIZONA_AIF1_FRAME_CTRL_8:
	case ARIZONA_AIF1_FRAME_CTRL_9:
	case ARIZONA_AIF1_FRAME_CTRL_10:
	case ARIZONA_AIF1_FRAME_CTRL_11:
	case ARIZONA_AIF1_FRAME_CTRL_12:
	case ARIZONA_AIF1_FRAME_CTRL_13:
	case ARIZONA_AIF1_FRAME_CTRL_14:
	case ARIZONA_AIF1_FRAME_CTRL_15:
	case ARIZONA_AIF1_FRAME_CTRL_16:
	case ARIZONA_AIF1_FRAME_CTRL_17:
	case ARIZONA_AIF1_FRAME_CTRL_18:
	case ARIZONA_AIF1_TX_ENABLES:
	case ARIZONA_AIF1_RX_ENABLES:
	case ARIZONA_AIF2_BCLK_CTRL:
	case ARIZONA_AIF2_TX_PIN_CTRL:
	case ARIZONA_AIF2_RX_PIN_CTRL:
	case ARIZONA_AIF2_RATE_CTRL:
	case ARIZONA_AIF2_FORMAT:
	case ARIZONA_AIF2_TX_BCLK_RATE:
	case ARIZONA_AIF2_RX_BCLK_RATE:
	case ARIZONA_AIF2_FRAME_CTRL_1:
	case ARIZONA_AIF2_FRAME_CTRL_2:
	case ARIZONA_AIF2_FRAME_CTRL_3:
	case ARIZONA_AIF2_FRAME_CTRL_4:
	case ARIZONA_AIF2_FRAME_CTRL_11:
	case ARIZONA_AIF2_FRAME_CTRL_12:
	case ARIZONA_AIF2_TX_ENABLES:
	case ARIZONA_AIF2_RX_ENABLES:
	case ARIZONA_AIF3_BCLK_CTRL:
	case ARIZONA_AIF3_TX_PIN_CTRL:
	case ARIZONA_AIF3_RX_PIN_CTRL:
	case ARIZONA_AIF3_RATE_CTRL:
	case ARIZONA_AIF3_FORMAT:
	case ARIZONA_AIF3_TX_BCLK_RATE:
	case ARIZONA_AIF3_RX_BCLK_RATE:
	case ARIZONA_AIF3_FRAME_CTRL_1:
	case ARIZONA_AIF3_FRAME_CTRL_2:
	case ARIZONA_AIF3_FRAME_CTRL_3:
	case ARIZONA_AIF3_FRAME_CTRL_4:
	case ARIZONA_AIF3_FRAME_CTRL_11:
	case ARIZONA_AIF3_FRAME_CTRL_12:
	case ARIZONA_AIF3_TX_ENABLES:
	case ARIZONA_AIF3_RX_ENABLES:
	case ARIZONA_SLIMBUS_FRAMER_REF_GEAR:
	case ARIZONA_SLIMBUS_RATES_1:
	case ARIZONA_SLIMBUS_RATES_2:
	case ARIZONA_SLIMBUS_RATES_3:
	case ARIZONA_SLIMBUS_RATES_4:
	case ARIZONA_SLIMBUS_RATES_5:
	case ARIZONA_SLIMBUS_RATES_6:
	case ARIZONA_SLIMBUS_RATES_7:
	case ARIZONA_SLIMBUS_RATES_8:
	case ARIZONA_SLIMBUS_RX_CHANNEL_ENABLE:
	case ARIZONA_SLIMBUS_TX_CHANNEL_ENABLE:
	case ARIZONA_SLIMBUS_RX_PORT_STATUS:
	case ARIZONA_SLIMBUS_TX_PORT_STATUS:
	case ARIZONA_PWM1MIX_INPUT_1_SOURCE:
	case ARIZONA_PWM1MIX_INPUT_1_VOLUME:
	case ARIZONA_PWM1MIX_INPUT_2_SOURCE:
	case ARIZONA_PWM1MIX_INPUT_2_VOLUME:
	case ARIZONA_PWM1MIX_INPUT_3_SOURCE:
	case ARIZONA_PWM1MIX_INPUT_3_VOLUME:
	case ARIZONA_PWM1MIX_INPUT_4_SOURCE:
	case ARIZONA_PWM1MIX_INPUT_4_VOLUME:
	case ARIZONA_PWM2MIX_INPUT_1_SOURCE:
	case ARIZONA_PWM2MIX_INPUT_1_VOLUME:
	case ARIZONA_PWM2MIX_INPUT_2_SOURCE:
	case ARIZONA_PWM2MIX_INPUT_2_VOLUME:
	case ARIZONA_PWM2MIX_INPUT_3_SOURCE:
	case ARIZONA_PWM2MIX_INPUT_3_VOLUME:
	case ARIZONA_PWM2MIX_INPUT_4_SOURCE:
	case ARIZONA_PWM2MIX_INPUT_4_VOLUME:
	case ARIZONA_MICMIX_INPUT_1_SOURCE:
	case ARIZONA_MICMIX_INPUT_1_VOLUME:
	case ARIZONA_MICMIX_INPUT_2_SOURCE:
	case ARIZONA_MICMIX_INPUT_2_VOLUME:
	case ARIZONA_MICMIX_INPUT_3_SOURCE:
	case ARIZONA_MICMIX_INPUT_3_VOLUME:
	case ARIZONA_MICMIX_INPUT_4_SOURCE:
	case ARIZONA_MICMIX_INPUT_4_VOLUME:
	case ARIZONA_NOISEMIX_INPUT_1_SOURCE:
	case ARIZONA_NOISEMIX_INPUT_1_VOLUME:
	case ARIZONA_NOISEMIX_INPUT_2_SOURCE:
	case ARIZONA_NOISEMIX_INPUT_2_VOLUME:
	case ARIZONA_NOISEMIX_INPUT_3_SOURCE:
	case ARIZONA_NOISEMIX_INPUT_3_VOLUME:
	case ARIZONA_NOISEMIX_INPUT_4_SOURCE:
	case ARIZONA_NOISEMIX_INPUT_4_VOLUME:
	case ARIZONA_OUT1LMIX_INPUT_1_SOURCE:
	case ARIZONA_OUT1LMIX_INPUT_1_VOLUME:
	case ARIZONA_OUT1LMIX_INPUT_2_SOURCE:
	case ARIZONA_OUT1LMIX_INPUT_2_VOLUME:
	case ARIZONA_OUT1LMIX_INPUT_3_SOURCE:
	case ARIZONA_OUT1LMIX_INPUT_3_VOLUME:
	case ARIZONA_OUT1LMIX_INPUT_4_SOURCE:
	case ARIZONA_OUT1LMIX_INPUT_4_VOLUME:
	case ARIZONA_OUT1RMIX_INPUT_1_SOURCE:
	case ARIZONA_OUT1RMIX_INPUT_1_VOLUME:
	case ARIZONA_OUT1RMIX_INPUT_2_SOURCE:
	case ARIZONA_OUT1RMIX_INPUT_2_VOLUME:
	case ARIZONA_OUT1RMIX_INPUT_3_SOURCE:
	case ARIZONA_OUT1RMIX_INPUT_3_VOLUME:
	case ARIZONA_OUT1RMIX_INPUT_4_SOURCE:
	case ARIZONA_OUT1RMIX_INPUT_4_VOLUME:
	case ARIZONA_OUT2LMIX_INPUT_1_SOURCE:
	case ARIZONA_OUT2LMIX_INPUT_1_VOLUME:
	case ARIZONA_OUT2LMIX_INPUT_2_SOURCE:
	case ARIZONA_OUT2LMIX_INPUT_2_VOLUME:
	case ARIZONA_OUT2LMIX_INPUT_3_SOURCE:
	case ARIZONA_OUT2LMIX_INPUT_3_VOLUME:
	case ARIZONA_OUT2LMIX_INPUT_4_SOURCE:
	case ARIZONA_OUT2LMIX_INPUT_4_VOLUME:
	case ARIZONA_OUT2RMIX_INPUT_1_SOURCE:
	case ARIZONA_OUT2RMIX_INPUT_1_VOLUME:
	case ARIZONA_OUT2RMIX_INPUT_2_SOURCE:
	case ARIZONA_OUT2RMIX_INPUT_2_VOLUME:
	case ARIZONA_OUT2RMIX_INPUT_3_SOURCE:
	case ARIZONA_OUT2RMIX_INPUT_3_VOLUME:
	case ARIZONA_OUT2RMIX_INPUT_4_SOURCE:
	case ARIZONA_OUT2RMIX_INPUT_4_VOLUME:
	case ARIZONA_OUT3LMIX_INPUT_1_SOURCE:
	case ARIZONA_OUT3LMIX_INPUT_1_VOLUME:
	case ARIZONA_OUT3LMIX_INPUT_2_SOURCE:
	case ARIZONA_OUT3LMIX_INPUT_2_VOLUME:
	case ARIZONA_OUT3LMIX_INPUT_3_SOURCE:
	case ARIZONA_OUT3LMIX_INPUT_3_VOLUME:
	case ARIZONA_OUT3LMIX_INPUT_4_SOURCE:
	case ARIZONA_OUT3LMIX_INPUT_4_VOLUME:
	case ARIZONA_OUT4LMIX_INPUT_1_SOURCE:
	case ARIZONA_OUT4LMIX_INPUT_1_VOLUME:
	case ARIZONA_OUT4LMIX_INPUT_2_SOURCE:
	case ARIZONA_OUT4LMIX_INPUT_2_VOLUME:
	case ARIZONA_OUT4LMIX_INPUT_3_SOURCE:
	case ARIZONA_OUT4LMIX_INPUT_3_VOLUME:
	case ARIZONA_OUT4LMIX_INPUT_4_SOURCE:
	case ARIZONA_OUT4LMIX_INPUT_4_VOLUME:
	case ARIZONA_OUT4RMIX_INPUT_1_SOURCE:
	case ARIZONA_OUT4RMIX_INPUT_1_VOLUME:
	case ARIZONA_OUT4RMIX_INPUT_2_SOURCE:
	case ARIZONA_OUT4RMIX_INPUT_2_VOLUME:
	case ARIZONA_OUT4RMIX_INPUT_3_SOURCE:
	case ARIZONA_OUT4RMIX_INPUT_3_VOLUME:
	case ARIZONA_OUT4RMIX_INPUT_4_SOURCE:
	case ARIZONA_OUT4RMIX_INPUT_4_VOLUME:
	case ARIZONA_OUT5LMIX_INPUT_1_SOURCE:
	case ARIZONA_OUT5LMIX_INPUT_1_VOLUME:
	case ARIZONA_OUT5LMIX_INPUT_2_SOURCE:
	case ARIZONA_OUT5LMIX_INPUT_2_VOLUME:
	case ARIZONA_OUT5LMIX_INPUT_3_SOURCE:
	case ARIZONA_OUT5LMIX_INPUT_3_VOLUME:
	case ARIZONA_OUT5LMIX_INPUT_4_SOURCE:
	case ARIZONA_OUT5LMIX_INPUT_4_VOLUME:
	case ARIZONA_OUT5RMIX_INPUT_1_SOURCE:
	case ARIZONA_OUT5RMIX_INPUT_1_VOLUME:
	case ARIZONA_OUT5RMIX_INPUT_2_SOURCE:
	case ARIZONA_OUT5RMIX_INPUT_2_VOLUME:
	case ARIZONA_OUT5RMIX_INPUT_3_SOURCE:
	case ARIZONA_OUT5RMIX_INPUT_3_VOLUME:
	case ARIZONA_OUT5RMIX_INPUT_4_SOURCE:
	case ARIZONA_OUT5RMIX_INPUT_4_VOLUME:
	case ARIZONA_AIF1TX1MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF1TX1MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF1TX1MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF1TX1MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF1TX1MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF1TX1MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF1TX1MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF1TX1MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF1TX2MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF1TX2MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF1TX2MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF1TX2MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF1TX2MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF1TX2MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF1TX2MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF1TX2MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF1TX3MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF1TX3MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF1TX3MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF1TX3MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF1TX3MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF1TX3MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF1TX3MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF1TX3MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF1TX4MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF1TX4MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF1TX4MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF1TX4MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF1TX4MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF1TX4MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF1TX4MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF1TX4MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF1TX5MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF1TX5MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF1TX5MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF1TX5MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF1TX5MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF1TX5MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF1TX5MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF1TX5MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF1TX6MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF1TX6MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF1TX6MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF1TX6MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF1TX6MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF1TX6MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF1TX6MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF1TX6MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF1TX7MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF1TX7MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF1TX7MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF1TX7MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF1TX7MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF1TX7MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF1TX7MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF1TX7MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF1TX8MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF1TX8MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF1TX8MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF1TX8MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF1TX8MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF1TX8MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF1TX8MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF1TX8MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF2TX1MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF2TX1MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF2TX1MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF2TX1MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF2TX1MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF2TX1MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF2TX1MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF2TX1MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF2TX2MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF2TX2MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF2TX2MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF2TX2MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF2TX2MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF2TX2MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF2TX2MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF2TX2MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF3TX1MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF3TX1MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF3TX1MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF3TX1MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF3TX1MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF3TX1MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF3TX1MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF3TX1MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF3TX2MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF3TX2MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF3TX2MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF3TX2MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF3TX2MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF3TX2MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF3TX2MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF3TX2MIX_INPUT_4_VOLUME:
	case ARIZONA_SLIMTX1MIX_INPUT_1_SOURCE:
	case ARIZONA_SLIMTX1MIX_INPUT_1_VOLUME:
	case ARIZONA_SLIMTX1MIX_INPUT_2_SOURCE:
	case ARIZONA_SLIMTX1MIX_INPUT_2_VOLUME:
	case ARIZONA_SLIMTX1MIX_INPUT_3_SOURCE:
	case ARIZONA_SLIMTX1MIX_INPUT_3_VOLUME:
	case ARIZONA_SLIMTX1MIX_INPUT_4_SOURCE:
	case ARIZONA_SLIMTX1MIX_INPUT_4_VOLUME:
	case ARIZONA_SLIMTX2MIX_INPUT_1_SOURCE:
	case ARIZONA_SLIMTX2MIX_INPUT_1_VOLUME:
	case ARIZONA_SLIMTX2MIX_INPUT_2_SOURCE:
	case ARIZONA_SLIMTX2MIX_INPUT_2_VOLUME:
	case ARIZONA_SLIMTX2MIX_INPUT_3_SOURCE:
	case ARIZONA_SLIMTX2MIX_INPUT_3_VOLUME:
	case ARIZONA_SLIMTX2MIX_INPUT_4_SOURCE:
	case ARIZONA_SLIMTX2MIX_INPUT_4_VOLUME:
	case ARIZONA_SLIMTX3MIX_INPUT_1_SOURCE:
	case ARIZONA_SLIMTX3MIX_INPUT_1_VOLUME:
	case ARIZONA_SLIMTX3MIX_INPUT_2_SOURCE:
	case ARIZONA_SLIMTX3MIX_INPUT_2_VOLUME:
	case ARIZONA_SLIMTX3MIX_INPUT_3_SOURCE:
	case ARIZONA_SLIMTX3MIX_INPUT_3_VOLUME:
	case ARIZONA_SLIMTX3MIX_INPUT_4_SOURCE:
	case ARIZONA_SLIMTX3MIX_INPUT_4_VOLUME:
	case ARIZONA_SLIMTX4MIX_INPUT_1_SOURCE:
	case ARIZONA_SLIMTX4MIX_INPUT_1_VOLUME:
	case ARIZONA_SLIMTX4MIX_INPUT_2_SOURCE:
	case ARIZONA_SLIMTX4MIX_INPUT_2_VOLUME:
	case ARIZONA_SLIMTX4MIX_INPUT_3_SOURCE:
	case ARIZONA_SLIMTX4MIX_INPUT_3_VOLUME:
	case ARIZONA_SLIMTX4MIX_INPUT_4_SOURCE:
	case ARIZONA_SLIMTX4MIX_INPUT_4_VOLUME:
	case ARIZONA_SLIMTX5MIX_INPUT_1_SOURCE:
	case ARIZONA_SLIMTX5MIX_INPUT_1_VOLUME:
	case ARIZONA_SLIMTX5MIX_INPUT_2_SOURCE:
	case ARIZONA_SLIMTX5MIX_INPUT_2_VOLUME:
	case ARIZONA_SLIMTX5MIX_INPUT_3_SOURCE:
	case ARIZONA_SLIMTX5MIX_INPUT_3_VOLUME:
	case ARIZONA_SLIMTX5MIX_INPUT_4_SOURCE:
	case ARIZONA_SLIMTX5MIX_INPUT_4_VOLUME:
	case ARIZONA_SLIMTX6MIX_INPUT_1_SOURCE:
	case ARIZONA_SLIMTX6MIX_INPUT_1_VOLUME:
	case ARIZONA_SLIMTX6MIX_INPUT_2_SOURCE:
	case ARIZONA_SLIMTX6MIX_INPUT_2_VOLUME:
	case ARIZONA_SLIMTX6MIX_INPUT_3_SOURCE:
	case ARIZONA_SLIMTX6MIX_INPUT_3_VOLUME:
	case ARIZONA_SLIMTX6MIX_INPUT_4_SOURCE:
	case ARIZONA_SLIMTX6MIX_INPUT_4_VOLUME:
	case ARIZONA_SLIMTX7MIX_INPUT_1_SOURCE:
	case ARIZONA_SLIMTX7MIX_INPUT_1_VOLUME:
	case ARIZONA_SLIMTX7MIX_INPUT_2_SOURCE:
	case ARIZONA_SLIMTX7MIX_INPUT_2_VOLUME:
	case ARIZONA_SLIMTX7MIX_INPUT_3_SOURCE:
	case ARIZONA_SLIMTX7MIX_INPUT_3_VOLUME:
	case ARIZONA_SLIMTX7MIX_INPUT_4_SOURCE:
	case ARIZONA_SLIMTX7MIX_INPUT_4_VOLUME:
	case ARIZONA_SLIMTX8MIX_INPUT_1_SOURCE:
	case ARIZONA_SLIMTX8MIX_INPUT_1_VOLUME:
	case ARIZONA_SLIMTX8MIX_INPUT_2_SOURCE:
	case ARIZONA_SLIMTX8MIX_INPUT_2_VOLUME:
	case ARIZONA_SLIMTX8MIX_INPUT_3_SOURCE:
	case ARIZONA_SLIMTX8MIX_INPUT_3_VOLUME:
	case ARIZONA_SLIMTX8MIX_INPUT_4_SOURCE:
	case ARIZONA_SLIMTX8MIX_INPUT_4_VOLUME:
	case ARIZONA_EQ1MIX_INPUT_1_SOURCE:
	case ARIZONA_EQ1MIX_INPUT_1_VOLUME:
	case ARIZONA_EQ1MIX_INPUT_2_SOURCE:
	case ARIZONA_EQ1MIX_INPUT_2_VOLUME:
	case ARIZONA_EQ1MIX_INPUT_3_SOURCE:
	case ARIZONA_EQ1MIX_INPUT_3_VOLUME:
	case ARIZONA_EQ1MIX_INPUT_4_SOURCE:
	case ARIZONA_EQ1MIX_INPUT_4_VOLUME:
	case ARIZONA_EQ2MIX_INPUT_1_SOURCE:
	case ARIZONA_EQ2MIX_INPUT_1_VOLUME:
	case ARIZONA_EQ2MIX_INPUT_2_SOURCE:
	case ARIZONA_EQ2MIX_INPUT_2_VOLUME:
	case ARIZONA_EQ2MIX_INPUT_3_SOURCE:
	case ARIZONA_EQ2MIX_INPUT_3_VOLUME:
	case ARIZONA_EQ2MIX_INPUT_4_SOURCE:
	case ARIZONA_EQ2MIX_INPUT_4_VOLUME:
	case ARIZONA_EQ3MIX_INPUT_1_SOURCE:
	case ARIZONA_EQ3MIX_INPUT_1_VOLUME:
	case ARIZONA_EQ3MIX_INPUT_2_SOURCE:
	case ARIZONA_EQ3MIX_INPUT_2_VOLUME:
	case ARIZONA_EQ3MIX_INPUT_3_SOURCE:
	case ARIZONA_EQ3MIX_INPUT_3_VOLUME:
	case ARIZONA_EQ3MIX_INPUT_4_SOURCE:
	case ARIZONA_EQ3MIX_INPUT_4_VOLUME:
	case ARIZONA_EQ4MIX_INPUT_1_SOURCE:
	case ARIZONA_EQ4MIX_INPUT_1_VOLUME:
	case ARIZONA_EQ4MIX_INPUT_2_SOURCE:
	case ARIZONA_EQ4MIX_INPUT_2_VOLUME:
	case ARIZONA_EQ4MIX_INPUT_3_SOURCE:
	case ARIZONA_EQ4MIX_INPUT_3_VOLUME:
	case ARIZONA_EQ4MIX_INPUT_4_SOURCE:
	case ARIZONA_EQ4MIX_INPUT_4_VOLUME:
	case ARIZONA_DRC1LMIX_INPUT_1_SOURCE:
	case ARIZONA_DRC1LMIX_INPUT_1_VOLUME:
	case ARIZONA_DRC1LMIX_INPUT_2_SOURCE:
	case ARIZONA_DRC1LMIX_INPUT_2_VOLUME:
	case ARIZONA_DRC1LMIX_INPUT_3_SOURCE:
	case ARIZONA_DRC1LMIX_INPUT_3_VOLUME:
	case ARIZONA_DRC1LMIX_INPUT_4_SOURCE:
	case ARIZONA_DRC1LMIX_INPUT_4_VOLUME:
	case ARIZONA_DRC1RMIX_INPUT_1_SOURCE:
	case ARIZONA_DRC1RMIX_INPUT_1_VOLUME:
	case ARIZONA_DRC1RMIX_INPUT_2_SOURCE:
	case ARIZONA_DRC1RMIX_INPUT_2_VOLUME:
	case ARIZONA_DRC1RMIX_INPUT_3_SOURCE:
	case ARIZONA_DRC1RMIX_INPUT_3_VOLUME:
	case ARIZONA_DRC1RMIX_INPUT_4_SOURCE:
	case ARIZONA_DRC1RMIX_INPUT_4_VOLUME:
	case ARIZONA_HPLP1MIX_INPUT_1_SOURCE:
	case ARIZONA_HPLP1MIX_INPUT_1_VOLUME:
	case ARIZONA_HPLP1MIX_INPUT_2_SOURCE:
	case ARIZONA_HPLP1MIX_INPUT_2_VOLUME:
	case ARIZONA_HPLP1MIX_INPUT_3_SOURCE:
	case ARIZONA_HPLP1MIX_INPUT_3_VOLUME:
	case ARIZONA_HPLP1MIX_INPUT_4_SOURCE:
	case ARIZONA_HPLP1MIX_INPUT_4_VOLUME:
	case ARIZONA_HPLP2MIX_INPUT_1_SOURCE:
	case ARIZONA_HPLP2MIX_INPUT_1_VOLUME:
	case ARIZONA_HPLP2MIX_INPUT_2_SOURCE:
	case ARIZONA_HPLP2MIX_INPUT_2_VOLUME:
	case ARIZONA_HPLP2MIX_INPUT_3_SOURCE:
	case ARIZONA_HPLP2MIX_INPUT_3_VOLUME:
	case ARIZONA_HPLP2MIX_INPUT_4_SOURCE:
	case ARIZONA_HPLP2MIX_INPUT_4_VOLUME:
	case ARIZONA_HPLP3MIX_INPUT_1_SOURCE:
	case ARIZONA_HPLP3MIX_INPUT_1_VOLUME:
	case ARIZONA_HPLP3MIX_INPUT_2_SOURCE:
	case ARIZONA_HPLP3MIX_INPUT_2_VOLUME:
	case ARIZONA_HPLP3MIX_INPUT_3_SOURCE:
	case ARIZONA_HPLP3MIX_INPUT_3_VOLUME:
	case ARIZONA_HPLP3MIX_INPUT_4_SOURCE:
	case ARIZONA_HPLP3MIX_INPUT_4_VOLUME:
	case ARIZONA_HPLP4MIX_INPUT_1_SOURCE:
	case ARIZONA_HPLP4MIX_INPUT_1_VOLUME:
	case ARIZONA_HPLP4MIX_INPUT_2_SOURCE:
	case ARIZONA_HPLP4MIX_INPUT_2_VOLUME:
	case ARIZONA_HPLP4MIX_INPUT_3_SOURCE:
	case ARIZONA_HPLP4MIX_INPUT_3_VOLUME:
	case ARIZONA_HPLP4MIX_INPUT_4_SOURCE:
	case ARIZONA_HPLP4MIX_INPUT_4_VOLUME:
	case ARIZONA_DSP1LMIX_INPUT_1_SOURCE:
	case ARIZONA_DSP1LMIX_INPUT_1_VOLUME:
	case ARIZONA_DSP1LMIX_INPUT_2_SOURCE:
	case ARIZONA_DSP1LMIX_INPUT_2_VOLUME:
	case ARIZONA_DSP1LMIX_INPUT_3_SOURCE:
	case ARIZONA_DSP1LMIX_INPUT_3_VOLUME:
	case ARIZONA_DSP1LMIX_INPUT_4_SOURCE:
	case ARIZONA_DSP1LMIX_INPUT_4_VOLUME:
	case ARIZONA_DSP1RMIX_INPUT_1_SOURCE:
	case ARIZONA_DSP1RMIX_INPUT_1_VOLUME:
	case ARIZONA_DSP1RMIX_INPUT_2_SOURCE:
	case ARIZONA_DSP1RMIX_INPUT_2_VOLUME:
	case ARIZONA_DSP1RMIX_INPUT_3_SOURCE:
	case ARIZONA_DSP1RMIX_INPUT_3_VOLUME:
	case ARIZONA_DSP1RMIX_INPUT_4_SOURCE:
	case ARIZONA_DSP1RMIX_INPUT_4_VOLUME:
	case ARIZONA_DSP1AUX1MIX_INPUT_1_SOURCE:
	case ARIZONA_DSP1AUX2MIX_INPUT_1_SOURCE:
	case ARIZONA_DSP1AUX3MIX_INPUT_1_SOURCE:
	case ARIZONA_DSP1AUX4MIX_INPUT_1_SOURCE:
	case ARIZONA_DSP1AUX5MIX_INPUT_1_SOURCE:
	case ARIZONA_DSP1AUX6MIX_INPUT_1_SOURCE:
	case ARIZONA_ASRC1LMIX_INPUT_1_SOURCE:
	case ARIZONA_ASRC1RMIX_INPUT_1_SOURCE:
	case ARIZONA_ASRC2LMIX_INPUT_1_SOURCE:
	case ARIZONA_ASRC2RMIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC1DEC1MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC1DEC2MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC1INT1MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC1INT2MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC2DEC1MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC2DEC2MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC2INT1MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC2INT2MIX_INPUT_1_SOURCE:
	case ARIZONA_GPIO1_CTRL:
	case ARIZONA_GPIO2_CTRL:
	case ARIZONA_GPIO3_CTRL:
	case ARIZONA_GPIO4_CTRL:
	case ARIZONA_GPIO5_CTRL:
	case ARIZONA_IRQ_CTRL_1:
	case ARIZONA_GPIO_DEBOUNCE_CONFIG:
	case ARIZONA_MISC_PAD_CTRL_1:
	case ARIZONA_MISC_PAD_CTRL_2:
	case ARIZONA_MISC_PAD_CTRL_3:
	case ARIZONA_MISC_PAD_CTRL_4:
	case ARIZONA_MISC_PAD_CTRL_5:
	case ARIZONA_MISC_PAD_CTRL_6:
	case ARIZONA_INTERRUPT_STATUS_1:
	case ARIZONA_INTERRUPT_STATUS_2:
	case ARIZONA_INTERRUPT_STATUS_3:
	case ARIZONA_INTERRUPT_STATUS_4:
	case ARIZONA_INTERRUPT_STATUS_5:
	case ARIZONA_INTERRUPT_STATUS_1_MASK:
	case ARIZONA_INTERRUPT_STATUS_2_MASK:
	case ARIZONA_INTERRUPT_STATUS_3_MASK:
	case ARIZONA_INTERRUPT_STATUS_4_MASK:
	case ARIZONA_INTERRUPT_STATUS_5_MASK:
	case ARIZONA_INTERRUPT_CONTROL:
	case ARIZONA_IRQ2_STATUS_1:
	case ARIZONA_IRQ2_STATUS_2:
	case ARIZONA_IRQ2_STATUS_3:
	case ARIZONA_IRQ2_STATUS_4:
	case ARIZONA_IRQ2_STATUS_5:
	case ARIZONA_IRQ2_STATUS_1_MASK:
	case ARIZONA_IRQ2_STATUS_2_MASK:
	case ARIZONA_IRQ2_STATUS_3_MASK:
	case ARIZONA_IRQ2_STATUS_4_MASK:
	case ARIZONA_IRQ2_STATUS_5_MASK:
	case ARIZONA_IRQ2_CONTROL:
	case ARIZONA_INTERRUPT_RAW_STATUS_2:
	case ARIZONA_INTERRUPT_RAW_STATUS_3:
	case ARIZONA_INTERRUPT_RAW_STATUS_4:
	case ARIZONA_INTERRUPT_RAW_STATUS_5:
	case ARIZONA_INTERRUPT_RAW_STATUS_6:
	case ARIZONA_INTERRUPT_RAW_STATUS_7:
	case ARIZONA_INTERRUPT_RAW_STATUS_8:
	case ARIZONA_IRQ_PIN_STATUS:
	case ARIZONA_ADSP2_IRQ0:
	case ARIZONA_AOD_WKUP_AND_TRIG:
	case ARIZONA_AOD_IRQ1:
	case ARIZONA_AOD_IRQ2:
	case ARIZONA_AOD_IRQ_MASK_IRQ1:
	case ARIZONA_AOD_IRQ_MASK_IRQ2:
	case ARIZONA_AOD_IRQ_RAW_STATUS:
	case ARIZONA_JACK_DETECT_DEBOUNCE:
	case ARIZONA_FX_CTRL1:
	case ARIZONA_FX_CTRL2:
	case ARIZONA_EQ1_1:
	case ARIZONA_EQ1_2:
	case ARIZONA_EQ1_3:
	case ARIZONA_EQ1_4:
	case ARIZONA_EQ1_5:
	case ARIZONA_EQ1_6:
	case ARIZONA_EQ1_7:
	case ARIZONA_EQ1_8:
	case ARIZONA_EQ1_9:
	case ARIZONA_EQ1_10:
	case ARIZONA_EQ1_11:
	case ARIZONA_EQ1_12:
	case ARIZONA_EQ1_13:
	case ARIZONA_EQ1_14:
	case ARIZONA_EQ1_15:
	case ARIZONA_EQ1_16:
	case ARIZONA_EQ1_17:
	case ARIZONA_EQ1_18:
	case ARIZONA_EQ1_19:
	case ARIZONA_EQ1_20:
	case ARIZONA_EQ1_21:
	case ARIZONA_EQ2_1:
	case ARIZONA_EQ2_2:
	case ARIZONA_EQ2_3:
	case ARIZONA_EQ2_4:
	case ARIZONA_EQ2_5:
	case ARIZONA_EQ2_6:
	case ARIZONA_EQ2_7:
	case ARIZONA_EQ2_8:
	case ARIZONA_EQ2_9:
	case ARIZONA_EQ2_10:
	case ARIZONA_EQ2_11:
	case ARIZONA_EQ2_12:
	case ARIZONA_EQ2_13:
	case ARIZONA_EQ2_14:
	case ARIZONA_EQ2_15:
	case ARIZONA_EQ2_16:
	case ARIZONA_EQ2_17:
	case ARIZONA_EQ2_18:
	case ARIZONA_EQ2_19:
	case ARIZONA_EQ2_20:
	case ARIZONA_EQ2_21:
	case ARIZONA_EQ3_1:
	case ARIZONA_EQ3_2:
	case ARIZONA_EQ3_3:
	case ARIZONA_EQ3_4:
	case ARIZONA_EQ3_5:
	case ARIZONA_EQ3_6:
	case ARIZONA_EQ3_7:
	case ARIZONA_EQ3_8:
	case ARIZONA_EQ3_9:
	case ARIZONA_EQ3_10:
	case ARIZONA_EQ3_11:
	case ARIZONA_EQ3_12:
	case ARIZONA_EQ3_13:
	case ARIZONA_EQ3_14:
	case ARIZONA_EQ3_15:
	case ARIZONA_EQ3_16:
	case ARIZONA_EQ3_17:
	case ARIZONA_EQ3_18:
	case ARIZONA_EQ3_19:
	case ARIZONA_EQ3_20:
	case ARIZONA_EQ3_21:
	case ARIZONA_EQ4_1:
	case ARIZONA_EQ4_2:
	case ARIZONA_EQ4_3:
	case ARIZONA_EQ4_4:
	case ARIZONA_EQ4_5:
	case ARIZONA_EQ4_6:
	case ARIZONA_EQ4_7:
	case ARIZONA_EQ4_8:
	case ARIZONA_EQ4_9:
	case ARIZONA_EQ4_10:
	case ARIZONA_EQ4_11:
	case ARIZONA_EQ4_12:
	case ARIZONA_EQ4_13:
	case ARIZONA_EQ4_14:
	case ARIZONA_EQ4_15:
	case ARIZONA_EQ4_16:
	case ARIZONA_EQ4_17:
	case ARIZONA_EQ4_18:
	case ARIZONA_EQ4_19:
	case ARIZONA_EQ4_20:
	case ARIZONA_EQ4_21:
	case ARIZONA_DRC1_CTRL1:
	case ARIZONA_DRC1_CTRL2:
	case ARIZONA_DRC1_CTRL3:
	case ARIZONA_DRC1_CTRL4:
	case ARIZONA_DRC1_CTRL5:
	case ARIZONA_HPLPF1_1:
	case ARIZONA_HPLPF1_2:
	case ARIZONA_HPLPF2_1:
	case ARIZONA_HPLPF2_2:
	case ARIZONA_HPLPF3_1:
	case ARIZONA_HPLPF3_2:
	case ARIZONA_HPLPF4_1:
	case ARIZONA_HPLPF4_2:
	case ARIZONA_ASRC_ENABLE:
	case ARIZONA_ASRC_RATE1:
	case ARIZONA_ASRC_RATE2:
	case ARIZONA_ISRC_1_CTRL_1:
	case ARIZONA_ISRC_1_CTRL_2:
	case ARIZONA_ISRC_1_CTRL_3:
	case ARIZONA_ISRC_2_CTRL_1:
	case ARIZONA_ISRC_2_CTRL_2:
	case ARIZONA_ISRC_2_CTRL_3:
	case ARIZONA_DSP1_CONTROL_1:
	case ARIZONA_DSP1_CLOCKING_1:
	case ARIZONA_DSP1_STATUS_1:
	case ARIZONA_DSP1_STATUS_2:
	case ARIZONA_DSP1_STATUS_3:
	case ARIZONA_DSP1_WDMA_BUFFER_1:
	case ARIZONA_DSP1_WDMA_BUFFER_2:
	case ARIZONA_DSP1_WDMA_BUFFER_3:
	case ARIZONA_DSP1_WDMA_BUFFER_4:
	case ARIZONA_DSP1_WDMA_BUFFER_5:
	case ARIZONA_DSP1_WDMA_BUFFER_6:
	case ARIZONA_DSP1_WDMA_BUFFER_7:
	case ARIZONA_DSP1_WDMA_BUFFER_8:
	case ARIZONA_DSP1_RDMA_BUFFER_1:
	case ARIZONA_DSP1_RDMA_BUFFER_2:
	case ARIZONA_DSP1_RDMA_BUFFER_3:
	case ARIZONA_DSP1_RDMA_BUFFER_4:
	case ARIZONA_DSP1_RDMA_BUFFER_5:
	case ARIZONA_DSP1_RDMA_BUFFER_6:
	case ARIZONA_DSP1_WDMA_CONFIG_1:
	case ARIZONA_DSP1_WDMA_CONFIG_2:
	case ARIZONA_DSP1_RDMA_CONFIG_1:
	case ARIZONA_DSP1_SCRATCH_0:
	case ARIZONA_DSP1_SCRATCH_1:
	case ARIZONA_DSP1_SCRATCH_2:
	case ARIZONA_DSP1_SCRATCH_3:
		return true;
	default:
		if ((reg >= 0x100000 && reg < 0x106000) ||
		    (reg >= 0x180000 && reg < 0x180800) ||
		    (reg >= 0x190000 && reg < 0x194800) ||
		    (reg >= 0x1a8000 && reg < 0x1a9800))
			return true;
		else
			return false;
	}
}