#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  scalar_t__ PFNGLVERTEXSTREAM4SVATIPROC ;
typedef  scalar_t__ PFNGLVERTEXSTREAM4SATIPROC ;
typedef  scalar_t__ PFNGLVERTEXSTREAM4IVATIPROC ;
typedef  scalar_t__ PFNGLVERTEXSTREAM4IATIPROC ;
typedef  scalar_t__ PFNGLVERTEXSTREAM4FVATIPROC ;
typedef  scalar_t__ PFNGLVERTEXSTREAM4FATIPROC ;
typedef  scalar_t__ PFNGLVERTEXSTREAM4DVATIPROC ;
typedef  scalar_t__ PFNGLVERTEXSTREAM4DATIPROC ;
typedef  scalar_t__ PFNGLVERTEXSTREAM3SVATIPROC ;
typedef  scalar_t__ PFNGLVERTEXSTREAM3SATIPROC ;
typedef  scalar_t__ PFNGLVERTEXSTREAM3IVATIPROC ;
typedef  scalar_t__ PFNGLVERTEXSTREAM3IATIPROC ;
typedef  scalar_t__ PFNGLVERTEXSTREAM3FVATIPROC ;
typedef  scalar_t__ PFNGLVERTEXSTREAM3FATIPROC ;
typedef  scalar_t__ PFNGLVERTEXSTREAM3DVATIPROC ;
typedef  scalar_t__ PFNGLVERTEXSTREAM3DATIPROC ;
typedef  scalar_t__ PFNGLVERTEXSTREAM2SVATIPROC ;
typedef  scalar_t__ PFNGLVERTEXSTREAM2SATIPROC ;
typedef  scalar_t__ PFNGLVERTEXSTREAM2IVATIPROC ;
typedef  scalar_t__ PFNGLVERTEXSTREAM2IATIPROC ;
typedef  scalar_t__ PFNGLVERTEXSTREAM2FVATIPROC ;
typedef  scalar_t__ PFNGLVERTEXSTREAM2FATIPROC ;
typedef  scalar_t__ PFNGLVERTEXSTREAM2DVATIPROC ;
typedef  scalar_t__ PFNGLVERTEXSTREAM2DATIPROC ;
typedef  scalar_t__ PFNGLVERTEXSTREAM1SVATIPROC ;
typedef  scalar_t__ PFNGLVERTEXSTREAM1SATIPROC ;
typedef  scalar_t__ PFNGLVERTEXSTREAM1IVATIPROC ;
typedef  scalar_t__ PFNGLVERTEXSTREAM1IATIPROC ;
typedef  scalar_t__ PFNGLVERTEXSTREAM1FVATIPROC ;
typedef  scalar_t__ PFNGLVERTEXSTREAM1FATIPROC ;
typedef  scalar_t__ PFNGLVERTEXSTREAM1DVATIPROC ;
typedef  scalar_t__ PFNGLVERTEXSTREAM1DATIPROC ;
typedef  scalar_t__ PFNGLVERTEXBLENDENVIATIPROC ;
typedef  scalar_t__ PFNGLVERTEXBLENDENVFATIPROC ;
typedef  scalar_t__ PFNGLNORMALSTREAM3SVATIPROC ;
typedef  scalar_t__ PFNGLNORMALSTREAM3SATIPROC ;
typedef  scalar_t__ PFNGLNORMALSTREAM3IVATIPROC ;
typedef  scalar_t__ PFNGLNORMALSTREAM3IATIPROC ;
typedef  scalar_t__ PFNGLNORMALSTREAM3FVATIPROC ;
typedef  scalar_t__ PFNGLNORMALSTREAM3FATIPROC ;
typedef  scalar_t__ PFNGLNORMALSTREAM3DVATIPROC ;
typedef  scalar_t__ PFNGLNORMALSTREAM3DATIPROC ;
typedef  scalar_t__ PFNGLNORMALSTREAM3BVATIPROC ;
typedef  scalar_t__ PFNGLNORMALSTREAM3BATIPROC ;
typedef  scalar_t__ PFNGLCLIENTACTIVEVERTEXSTREAMATIPROC ;

/* Variables and functions */
 scalar_t__ IntGetProcAddress (char*) ; 
 scalar_t__ _funcptr_glClientActiveVertexStreamATI ; 
 scalar_t__ _funcptr_glNormalStream3bATI ; 
 scalar_t__ _funcptr_glNormalStream3bvATI ; 
 scalar_t__ _funcptr_glNormalStream3dATI ; 
 scalar_t__ _funcptr_glNormalStream3dvATI ; 
 scalar_t__ _funcptr_glNormalStream3fATI ; 
 scalar_t__ _funcptr_glNormalStream3fvATI ; 
 scalar_t__ _funcptr_glNormalStream3iATI ; 
 scalar_t__ _funcptr_glNormalStream3ivATI ; 
 scalar_t__ _funcptr_glNormalStream3sATI ; 
 scalar_t__ _funcptr_glNormalStream3svATI ; 
 scalar_t__ _funcptr_glVertexBlendEnvfATI ; 
 scalar_t__ _funcptr_glVertexBlendEnviATI ; 
 scalar_t__ _funcptr_glVertexStream1dATI ; 
 scalar_t__ _funcptr_glVertexStream1dvATI ; 
 scalar_t__ _funcptr_glVertexStream1fATI ; 
 scalar_t__ _funcptr_glVertexStream1fvATI ; 
 scalar_t__ _funcptr_glVertexStream1iATI ; 
 scalar_t__ _funcptr_glVertexStream1ivATI ; 
 scalar_t__ _funcptr_glVertexStream1sATI ; 
 scalar_t__ _funcptr_glVertexStream1svATI ; 
 scalar_t__ _funcptr_glVertexStream2dATI ; 
 scalar_t__ _funcptr_glVertexStream2dvATI ; 
 scalar_t__ _funcptr_glVertexStream2fATI ; 
 scalar_t__ _funcptr_glVertexStream2fvATI ; 
 scalar_t__ _funcptr_glVertexStream2iATI ; 
 scalar_t__ _funcptr_glVertexStream2ivATI ; 
 scalar_t__ _funcptr_glVertexStream2sATI ; 
 scalar_t__ _funcptr_glVertexStream2svATI ; 
 scalar_t__ _funcptr_glVertexStream3dATI ; 
 scalar_t__ _funcptr_glVertexStream3dvATI ; 
 scalar_t__ _funcptr_glVertexStream3fATI ; 
 scalar_t__ _funcptr_glVertexStream3fvATI ; 
 scalar_t__ _funcptr_glVertexStream3iATI ; 
 scalar_t__ _funcptr_glVertexStream3ivATI ; 
 scalar_t__ _funcptr_glVertexStream3sATI ; 
 scalar_t__ _funcptr_glVertexStream3svATI ; 
 scalar_t__ _funcptr_glVertexStream4dATI ; 
 scalar_t__ _funcptr_glVertexStream4dvATI ; 
 scalar_t__ _funcptr_glVertexStream4fATI ; 
 scalar_t__ _funcptr_glVertexStream4fvATI ; 
 scalar_t__ _funcptr_glVertexStream4iATI ; 
 scalar_t__ _funcptr_glVertexStream4ivATI ; 
 scalar_t__ _funcptr_glVertexStream4sATI ; 
 scalar_t__ _funcptr_glVertexStream4svATI ; 

__attribute__((used)) static int LoadExt_ATI_vertex_streams()
{
	int numFailed = 0;
	_funcptr_glClientActiveVertexStreamATI = (PFNGLCLIENTACTIVEVERTEXSTREAMATIPROC)IntGetProcAddress("glClientActiveVertexStreamATI");
	if(!_funcptr_glClientActiveVertexStreamATI) ++numFailed;
	_funcptr_glNormalStream3bATI = (PFNGLNORMALSTREAM3BATIPROC)IntGetProcAddress("glNormalStream3bATI");
	if(!_funcptr_glNormalStream3bATI) ++numFailed;
	_funcptr_glNormalStream3bvATI = (PFNGLNORMALSTREAM3BVATIPROC)IntGetProcAddress("glNormalStream3bvATI");
	if(!_funcptr_glNormalStream3bvATI) ++numFailed;
	_funcptr_glNormalStream3dATI = (PFNGLNORMALSTREAM3DATIPROC)IntGetProcAddress("glNormalStream3dATI");
	if(!_funcptr_glNormalStream3dATI) ++numFailed;
	_funcptr_glNormalStream3dvATI = (PFNGLNORMALSTREAM3DVATIPROC)IntGetProcAddress("glNormalStream3dvATI");
	if(!_funcptr_glNormalStream3dvATI) ++numFailed;
	_funcptr_glNormalStream3fATI = (PFNGLNORMALSTREAM3FATIPROC)IntGetProcAddress("glNormalStream3fATI");
	if(!_funcptr_glNormalStream3fATI) ++numFailed;
	_funcptr_glNormalStream3fvATI = (PFNGLNORMALSTREAM3FVATIPROC)IntGetProcAddress("glNormalStream3fvATI");
	if(!_funcptr_glNormalStream3fvATI) ++numFailed;
	_funcptr_glNormalStream3iATI = (PFNGLNORMALSTREAM3IATIPROC)IntGetProcAddress("glNormalStream3iATI");
	if(!_funcptr_glNormalStream3iATI) ++numFailed;
	_funcptr_glNormalStream3ivATI = (PFNGLNORMALSTREAM3IVATIPROC)IntGetProcAddress("glNormalStream3ivATI");
	if(!_funcptr_glNormalStream3ivATI) ++numFailed;
	_funcptr_glNormalStream3sATI = (PFNGLNORMALSTREAM3SATIPROC)IntGetProcAddress("glNormalStream3sATI");
	if(!_funcptr_glNormalStream3sATI) ++numFailed;
	_funcptr_glNormalStream3svATI = (PFNGLNORMALSTREAM3SVATIPROC)IntGetProcAddress("glNormalStream3svATI");
	if(!_funcptr_glNormalStream3svATI) ++numFailed;
	_funcptr_glVertexBlendEnvfATI = (PFNGLVERTEXBLENDENVFATIPROC)IntGetProcAddress("glVertexBlendEnvfATI");
	if(!_funcptr_glVertexBlendEnvfATI) ++numFailed;
	_funcptr_glVertexBlendEnviATI = (PFNGLVERTEXBLENDENVIATIPROC)IntGetProcAddress("glVertexBlendEnviATI");
	if(!_funcptr_glVertexBlendEnviATI) ++numFailed;
	_funcptr_glVertexStream1dATI = (PFNGLVERTEXSTREAM1DATIPROC)IntGetProcAddress("glVertexStream1dATI");
	if(!_funcptr_glVertexStream1dATI) ++numFailed;
	_funcptr_glVertexStream1dvATI = (PFNGLVERTEXSTREAM1DVATIPROC)IntGetProcAddress("glVertexStream1dvATI");
	if(!_funcptr_glVertexStream1dvATI) ++numFailed;
	_funcptr_glVertexStream1fATI = (PFNGLVERTEXSTREAM1FATIPROC)IntGetProcAddress("glVertexStream1fATI");
	if(!_funcptr_glVertexStream1fATI) ++numFailed;
	_funcptr_glVertexStream1fvATI = (PFNGLVERTEXSTREAM1FVATIPROC)IntGetProcAddress("glVertexStream1fvATI");
	if(!_funcptr_glVertexStream1fvATI) ++numFailed;
	_funcptr_glVertexStream1iATI = (PFNGLVERTEXSTREAM1IATIPROC)IntGetProcAddress("glVertexStream1iATI");
	if(!_funcptr_glVertexStream1iATI) ++numFailed;
	_funcptr_glVertexStream1ivATI = (PFNGLVERTEXSTREAM1IVATIPROC)IntGetProcAddress("glVertexStream1ivATI");
	if(!_funcptr_glVertexStream1ivATI) ++numFailed;
	_funcptr_glVertexStream1sATI = (PFNGLVERTEXSTREAM1SATIPROC)IntGetProcAddress("glVertexStream1sATI");
	if(!_funcptr_glVertexStream1sATI) ++numFailed;
	_funcptr_glVertexStream1svATI = (PFNGLVERTEXSTREAM1SVATIPROC)IntGetProcAddress("glVertexStream1svATI");
	if(!_funcptr_glVertexStream1svATI) ++numFailed;
	_funcptr_glVertexStream2dATI = (PFNGLVERTEXSTREAM2DATIPROC)IntGetProcAddress("glVertexStream2dATI");
	if(!_funcptr_glVertexStream2dATI) ++numFailed;
	_funcptr_glVertexStream2dvATI = (PFNGLVERTEXSTREAM2DVATIPROC)IntGetProcAddress("glVertexStream2dvATI");
	if(!_funcptr_glVertexStream2dvATI) ++numFailed;
	_funcptr_glVertexStream2fATI = (PFNGLVERTEXSTREAM2FATIPROC)IntGetProcAddress("glVertexStream2fATI");
	if(!_funcptr_glVertexStream2fATI) ++numFailed;
	_funcptr_glVertexStream2fvATI = (PFNGLVERTEXSTREAM2FVATIPROC)IntGetProcAddress("glVertexStream2fvATI");
	if(!_funcptr_glVertexStream2fvATI) ++numFailed;
	_funcptr_glVertexStream2iATI = (PFNGLVERTEXSTREAM2IATIPROC)IntGetProcAddress("glVertexStream2iATI");
	if(!_funcptr_glVertexStream2iATI) ++numFailed;
	_funcptr_glVertexStream2ivATI = (PFNGLVERTEXSTREAM2IVATIPROC)IntGetProcAddress("glVertexStream2ivATI");
	if(!_funcptr_glVertexStream2ivATI) ++numFailed;
	_funcptr_glVertexStream2sATI = (PFNGLVERTEXSTREAM2SATIPROC)IntGetProcAddress("glVertexStream2sATI");
	if(!_funcptr_glVertexStream2sATI) ++numFailed;
	_funcptr_glVertexStream2svATI = (PFNGLVERTEXSTREAM2SVATIPROC)IntGetProcAddress("glVertexStream2svATI");
	if(!_funcptr_glVertexStream2svATI) ++numFailed;
	_funcptr_glVertexStream3dATI = (PFNGLVERTEXSTREAM3DATIPROC)IntGetProcAddress("glVertexStream3dATI");
	if(!_funcptr_glVertexStream3dATI) ++numFailed;
	_funcptr_glVertexStream3dvATI = (PFNGLVERTEXSTREAM3DVATIPROC)IntGetProcAddress("glVertexStream3dvATI");
	if(!_funcptr_glVertexStream3dvATI) ++numFailed;
	_funcptr_glVertexStream3fATI = (PFNGLVERTEXSTREAM3FATIPROC)IntGetProcAddress("glVertexStream3fATI");
	if(!_funcptr_glVertexStream3fATI) ++numFailed;
	_funcptr_glVertexStream3fvATI = (PFNGLVERTEXSTREAM3FVATIPROC)IntGetProcAddress("glVertexStream3fvATI");
	if(!_funcptr_glVertexStream3fvATI) ++numFailed;
	_funcptr_glVertexStream3iATI = (PFNGLVERTEXSTREAM3IATIPROC)IntGetProcAddress("glVertexStream3iATI");
	if(!_funcptr_glVertexStream3iATI) ++numFailed;
	_funcptr_glVertexStream3ivATI = (PFNGLVERTEXSTREAM3IVATIPROC)IntGetProcAddress("glVertexStream3ivATI");
	if(!_funcptr_glVertexStream3ivATI) ++numFailed;
	_funcptr_glVertexStream3sATI = (PFNGLVERTEXSTREAM3SATIPROC)IntGetProcAddress("glVertexStream3sATI");
	if(!_funcptr_glVertexStream3sATI) ++numFailed;
	_funcptr_glVertexStream3svATI = (PFNGLVERTEXSTREAM3SVATIPROC)IntGetProcAddress("glVertexStream3svATI");
	if(!_funcptr_glVertexStream3svATI) ++numFailed;
	_funcptr_glVertexStream4dATI = (PFNGLVERTEXSTREAM4DATIPROC)IntGetProcAddress("glVertexStream4dATI");
	if(!_funcptr_glVertexStream4dATI) ++numFailed;
	_funcptr_glVertexStream4dvATI = (PFNGLVERTEXSTREAM4DVATIPROC)IntGetProcAddress("glVertexStream4dvATI");
	if(!_funcptr_glVertexStream4dvATI) ++numFailed;
	_funcptr_glVertexStream4fATI = (PFNGLVERTEXSTREAM4FATIPROC)IntGetProcAddress("glVertexStream4fATI");
	if(!_funcptr_glVertexStream4fATI) ++numFailed;
	_funcptr_glVertexStream4fvATI = (PFNGLVERTEXSTREAM4FVATIPROC)IntGetProcAddress("glVertexStream4fvATI");
	if(!_funcptr_glVertexStream4fvATI) ++numFailed;
	_funcptr_glVertexStream4iATI = (PFNGLVERTEXSTREAM4IATIPROC)IntGetProcAddress("glVertexStream4iATI");
	if(!_funcptr_glVertexStream4iATI) ++numFailed;
	_funcptr_glVertexStream4ivATI = (PFNGLVERTEXSTREAM4IVATIPROC)IntGetProcAddress("glVertexStream4ivATI");
	if(!_funcptr_glVertexStream4ivATI) ++numFailed;
	_funcptr_glVertexStream4sATI = (PFNGLVERTEXSTREAM4SATIPROC)IntGetProcAddress("glVertexStream4sATI");
	if(!_funcptr_glVertexStream4sATI) ++numFailed;
	_funcptr_glVertexStream4svATI = (PFNGLVERTEXSTREAM4SVATIPROC)IntGetProcAddress("glVertexStream4svATI");
	if(!_funcptr_glVertexStream4svATI) ++numFailed;
	return numFailed;
}