#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  scalar_t__ PFNGLVERTEXATTRIBPOINTERARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4USVARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4UIVARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4UBVARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4SVARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4SARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4NUSVARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4NUIVARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4NUBVARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4NUBARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4NSVARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4NIVARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4NBVARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4IVARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4FVARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4FARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4DVARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4DARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4BVARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB3SVARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB3SARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB3FVARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB3FARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB3DVARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB3DARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB2SVARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB2SARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB2FVARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB2FARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB2DVARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB2DARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB1SVARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB1SARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB1FVARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB1FARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB1DVARBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB1DARBPROC ;
typedef  scalar_t__ PFNGLPROGRAMSTRINGARBPROC ;
typedef  scalar_t__ PFNGLPROGRAMLOCALPARAMETER4FVARBPROC ;
typedef  scalar_t__ PFNGLPROGRAMLOCALPARAMETER4FARBPROC ;
typedef  scalar_t__ PFNGLPROGRAMLOCALPARAMETER4DVARBPROC ;
typedef  scalar_t__ PFNGLPROGRAMLOCALPARAMETER4DARBPROC ;
typedef  scalar_t__ PFNGLPROGRAMENVPARAMETER4FVARBPROC ;
typedef  scalar_t__ PFNGLPROGRAMENVPARAMETER4FARBPROC ;
typedef  scalar_t__ PFNGLPROGRAMENVPARAMETER4DVARBPROC ;
typedef  scalar_t__ PFNGLPROGRAMENVPARAMETER4DARBPROC ;
typedef  scalar_t__ PFNGLISPROGRAMARBPROC ;
typedef  scalar_t__ PFNGLGETVERTEXATTRIBPOINTERVARBPROC ;
typedef  scalar_t__ PFNGLGETVERTEXATTRIBIVARBPROC ;
typedef  scalar_t__ PFNGLGETVERTEXATTRIBFVARBPROC ;
typedef  scalar_t__ PFNGLGETVERTEXATTRIBDVARBPROC ;
typedef  scalar_t__ PFNGLGETPROGRAMSTRINGARBPROC ;
typedef  scalar_t__ PFNGLGETPROGRAMLOCALPARAMETERFVARBPROC ;
typedef  scalar_t__ PFNGLGETPROGRAMLOCALPARAMETERDVARBPROC ;
typedef  scalar_t__ PFNGLGETPROGRAMIVARBPROC ;
typedef  scalar_t__ PFNGLGETPROGRAMENVPARAMETERFVARBPROC ;
typedef  scalar_t__ PFNGLGETPROGRAMENVPARAMETERDVARBPROC ;
typedef  scalar_t__ PFNGLGENPROGRAMSARBPROC ;
typedef  scalar_t__ PFNGLENABLEVERTEXATTRIBARRAYARBPROC ;
typedef  scalar_t__ PFNGLDISABLEVERTEXATTRIBARRAYARBPROC ;
typedef  scalar_t__ PFNGLDELETEPROGRAMSARBPROC ;
typedef  scalar_t__ PFNGLBINDPROGRAMARBPROC ;

/* Variables and functions */
 scalar_t__ IntGetProcAddress (char*) ; 
 scalar_t__ _funcptr_glBindProgramARB ; 
 scalar_t__ _funcptr_glDeleteProgramsARB ; 
 scalar_t__ _funcptr_glDisableVertexAttribArrayARB ; 
 scalar_t__ _funcptr_glEnableVertexAttribArrayARB ; 
 scalar_t__ _funcptr_glGenProgramsARB ; 
 scalar_t__ _funcptr_glGetProgramEnvParameterdvARB ; 
 scalar_t__ _funcptr_glGetProgramEnvParameterfvARB ; 
 scalar_t__ _funcptr_glGetProgramLocalParameterdvARB ; 
 scalar_t__ _funcptr_glGetProgramLocalParameterfvARB ; 
 scalar_t__ _funcptr_glGetProgramStringARB ; 
 scalar_t__ _funcptr_glGetProgramivARB ; 
 scalar_t__ _funcptr_glGetVertexAttribPointervARB ; 
 scalar_t__ _funcptr_glGetVertexAttribdvARB ; 
 scalar_t__ _funcptr_glGetVertexAttribfvARB ; 
 scalar_t__ _funcptr_glGetVertexAttribivARB ; 
 scalar_t__ _funcptr_glIsProgramARB ; 
 scalar_t__ _funcptr_glProgramEnvParameter4dARB ; 
 scalar_t__ _funcptr_glProgramEnvParameter4dvARB ; 
 scalar_t__ _funcptr_glProgramEnvParameter4fARB ; 
 scalar_t__ _funcptr_glProgramEnvParameter4fvARB ; 
 scalar_t__ _funcptr_glProgramLocalParameter4dARB ; 
 scalar_t__ _funcptr_glProgramLocalParameter4dvARB ; 
 scalar_t__ _funcptr_glProgramLocalParameter4fARB ; 
 scalar_t__ _funcptr_glProgramLocalParameter4fvARB ; 
 scalar_t__ _funcptr_glProgramStringARB ; 
 scalar_t__ _funcptr_glVertexAttrib1dARB ; 
 scalar_t__ _funcptr_glVertexAttrib1dvARB ; 
 scalar_t__ _funcptr_glVertexAttrib1fARB ; 
 scalar_t__ _funcptr_glVertexAttrib1fvARB ; 
 scalar_t__ _funcptr_glVertexAttrib1sARB ; 
 scalar_t__ _funcptr_glVertexAttrib1svARB ; 
 scalar_t__ _funcptr_glVertexAttrib2dARB ; 
 scalar_t__ _funcptr_glVertexAttrib2dvARB ; 
 scalar_t__ _funcptr_glVertexAttrib2fARB ; 
 scalar_t__ _funcptr_glVertexAttrib2fvARB ; 
 scalar_t__ _funcptr_glVertexAttrib2sARB ; 
 scalar_t__ _funcptr_glVertexAttrib2svARB ; 
 scalar_t__ _funcptr_glVertexAttrib3dARB ; 
 scalar_t__ _funcptr_glVertexAttrib3dvARB ; 
 scalar_t__ _funcptr_glVertexAttrib3fARB ; 
 scalar_t__ _funcptr_glVertexAttrib3fvARB ; 
 scalar_t__ _funcptr_glVertexAttrib3sARB ; 
 scalar_t__ _funcptr_glVertexAttrib3svARB ; 
 scalar_t__ _funcptr_glVertexAttrib4NbvARB ; 
 scalar_t__ _funcptr_glVertexAttrib4NivARB ; 
 scalar_t__ _funcptr_glVertexAttrib4NsvARB ; 
 scalar_t__ _funcptr_glVertexAttrib4NubARB ; 
 scalar_t__ _funcptr_glVertexAttrib4NubvARB ; 
 scalar_t__ _funcptr_glVertexAttrib4NuivARB ; 
 scalar_t__ _funcptr_glVertexAttrib4NusvARB ; 
 scalar_t__ _funcptr_glVertexAttrib4bvARB ; 
 scalar_t__ _funcptr_glVertexAttrib4dARB ; 
 scalar_t__ _funcptr_glVertexAttrib4dvARB ; 
 scalar_t__ _funcptr_glVertexAttrib4fARB ; 
 scalar_t__ _funcptr_glVertexAttrib4fvARB ; 
 scalar_t__ _funcptr_glVertexAttrib4ivARB ; 
 scalar_t__ _funcptr_glVertexAttrib4sARB ; 
 scalar_t__ _funcptr_glVertexAttrib4svARB ; 
 scalar_t__ _funcptr_glVertexAttrib4ubvARB ; 
 scalar_t__ _funcptr_glVertexAttrib4uivARB ; 
 scalar_t__ _funcptr_glVertexAttrib4usvARB ; 
 scalar_t__ _funcptr_glVertexAttribPointerARB ; 

__attribute__((used)) static int LoadExt_ARB_vertex_program()
{
	int numFailed = 0;
	_funcptr_glBindProgramARB = (PFNGLBINDPROGRAMARBPROC)IntGetProcAddress("glBindProgramARB");
	if(!_funcptr_glBindProgramARB) ++numFailed;
	_funcptr_glDeleteProgramsARB = (PFNGLDELETEPROGRAMSARBPROC)IntGetProcAddress("glDeleteProgramsARB");
	if(!_funcptr_glDeleteProgramsARB) ++numFailed;
	_funcptr_glDisableVertexAttribArrayARB = (PFNGLDISABLEVERTEXATTRIBARRAYARBPROC)IntGetProcAddress("glDisableVertexAttribArrayARB");
	if(!_funcptr_glDisableVertexAttribArrayARB) ++numFailed;
	_funcptr_glEnableVertexAttribArrayARB = (PFNGLENABLEVERTEXATTRIBARRAYARBPROC)IntGetProcAddress("glEnableVertexAttribArrayARB");
	if(!_funcptr_glEnableVertexAttribArrayARB) ++numFailed;
	_funcptr_glGenProgramsARB = (PFNGLGENPROGRAMSARBPROC)IntGetProcAddress("glGenProgramsARB");
	if(!_funcptr_glGenProgramsARB) ++numFailed;
	_funcptr_glGetProgramEnvParameterdvARB = (PFNGLGETPROGRAMENVPARAMETERDVARBPROC)IntGetProcAddress("glGetProgramEnvParameterdvARB");
	if(!_funcptr_glGetProgramEnvParameterdvARB) ++numFailed;
	_funcptr_glGetProgramEnvParameterfvARB = (PFNGLGETPROGRAMENVPARAMETERFVARBPROC)IntGetProcAddress("glGetProgramEnvParameterfvARB");
	if(!_funcptr_glGetProgramEnvParameterfvARB) ++numFailed;
	_funcptr_glGetProgramLocalParameterdvARB = (PFNGLGETPROGRAMLOCALPARAMETERDVARBPROC)IntGetProcAddress("glGetProgramLocalParameterdvARB");
	if(!_funcptr_glGetProgramLocalParameterdvARB) ++numFailed;
	_funcptr_glGetProgramLocalParameterfvARB = (PFNGLGETPROGRAMLOCALPARAMETERFVARBPROC)IntGetProcAddress("glGetProgramLocalParameterfvARB");
	if(!_funcptr_glGetProgramLocalParameterfvARB) ++numFailed;
	_funcptr_glGetProgramStringARB = (PFNGLGETPROGRAMSTRINGARBPROC)IntGetProcAddress("glGetProgramStringARB");
	if(!_funcptr_glGetProgramStringARB) ++numFailed;
	_funcptr_glGetProgramivARB = (PFNGLGETPROGRAMIVARBPROC)IntGetProcAddress("glGetProgramivARB");
	if(!_funcptr_glGetProgramivARB) ++numFailed;
	_funcptr_glGetVertexAttribPointervARB = (PFNGLGETVERTEXATTRIBPOINTERVARBPROC)IntGetProcAddress("glGetVertexAttribPointervARB");
	if(!_funcptr_glGetVertexAttribPointervARB) ++numFailed;
	_funcptr_glGetVertexAttribdvARB = (PFNGLGETVERTEXATTRIBDVARBPROC)IntGetProcAddress("glGetVertexAttribdvARB");
	if(!_funcptr_glGetVertexAttribdvARB) ++numFailed;
	_funcptr_glGetVertexAttribfvARB = (PFNGLGETVERTEXATTRIBFVARBPROC)IntGetProcAddress("glGetVertexAttribfvARB");
	if(!_funcptr_glGetVertexAttribfvARB) ++numFailed;
	_funcptr_glGetVertexAttribivARB = (PFNGLGETVERTEXATTRIBIVARBPROC)IntGetProcAddress("glGetVertexAttribivARB");
	if(!_funcptr_glGetVertexAttribivARB) ++numFailed;
	_funcptr_glIsProgramARB = (PFNGLISPROGRAMARBPROC)IntGetProcAddress("glIsProgramARB");
	if(!_funcptr_glIsProgramARB) ++numFailed;
	_funcptr_glProgramEnvParameter4dARB = (PFNGLPROGRAMENVPARAMETER4DARBPROC)IntGetProcAddress("glProgramEnvParameter4dARB");
	if(!_funcptr_glProgramEnvParameter4dARB) ++numFailed;
	_funcptr_glProgramEnvParameter4dvARB = (PFNGLPROGRAMENVPARAMETER4DVARBPROC)IntGetProcAddress("glProgramEnvParameter4dvARB");
	if(!_funcptr_glProgramEnvParameter4dvARB) ++numFailed;
	_funcptr_glProgramEnvParameter4fARB = (PFNGLPROGRAMENVPARAMETER4FARBPROC)IntGetProcAddress("glProgramEnvParameter4fARB");
	if(!_funcptr_glProgramEnvParameter4fARB) ++numFailed;
	_funcptr_glProgramEnvParameter4fvARB = (PFNGLPROGRAMENVPARAMETER4FVARBPROC)IntGetProcAddress("glProgramEnvParameter4fvARB");
	if(!_funcptr_glProgramEnvParameter4fvARB) ++numFailed;
	_funcptr_glProgramLocalParameter4dARB = (PFNGLPROGRAMLOCALPARAMETER4DARBPROC)IntGetProcAddress("glProgramLocalParameter4dARB");
	if(!_funcptr_glProgramLocalParameter4dARB) ++numFailed;
	_funcptr_glProgramLocalParameter4dvARB = (PFNGLPROGRAMLOCALPARAMETER4DVARBPROC)IntGetProcAddress("glProgramLocalParameter4dvARB");
	if(!_funcptr_glProgramLocalParameter4dvARB) ++numFailed;
	_funcptr_glProgramLocalParameter4fARB = (PFNGLPROGRAMLOCALPARAMETER4FARBPROC)IntGetProcAddress("glProgramLocalParameter4fARB");
	if(!_funcptr_glProgramLocalParameter4fARB) ++numFailed;
	_funcptr_glProgramLocalParameter4fvARB = (PFNGLPROGRAMLOCALPARAMETER4FVARBPROC)IntGetProcAddress("glProgramLocalParameter4fvARB");
	if(!_funcptr_glProgramLocalParameter4fvARB) ++numFailed;
	_funcptr_glProgramStringARB = (PFNGLPROGRAMSTRINGARBPROC)IntGetProcAddress("glProgramStringARB");
	if(!_funcptr_glProgramStringARB) ++numFailed;
	_funcptr_glVertexAttrib1dARB = (PFNGLVERTEXATTRIB1DARBPROC)IntGetProcAddress("glVertexAttrib1dARB");
	if(!_funcptr_glVertexAttrib1dARB) ++numFailed;
	_funcptr_glVertexAttrib1dvARB = (PFNGLVERTEXATTRIB1DVARBPROC)IntGetProcAddress("glVertexAttrib1dvARB");
	if(!_funcptr_glVertexAttrib1dvARB) ++numFailed;
	_funcptr_glVertexAttrib1fARB = (PFNGLVERTEXATTRIB1FARBPROC)IntGetProcAddress("glVertexAttrib1fARB");
	if(!_funcptr_glVertexAttrib1fARB) ++numFailed;
	_funcptr_glVertexAttrib1fvARB = (PFNGLVERTEXATTRIB1FVARBPROC)IntGetProcAddress("glVertexAttrib1fvARB");
	if(!_funcptr_glVertexAttrib1fvARB) ++numFailed;
	_funcptr_glVertexAttrib1sARB = (PFNGLVERTEXATTRIB1SARBPROC)IntGetProcAddress("glVertexAttrib1sARB");
	if(!_funcptr_glVertexAttrib1sARB) ++numFailed;
	_funcptr_glVertexAttrib1svARB = (PFNGLVERTEXATTRIB1SVARBPROC)IntGetProcAddress("glVertexAttrib1svARB");
	if(!_funcptr_glVertexAttrib1svARB) ++numFailed;
	_funcptr_glVertexAttrib2dARB = (PFNGLVERTEXATTRIB2DARBPROC)IntGetProcAddress("glVertexAttrib2dARB");
	if(!_funcptr_glVertexAttrib2dARB) ++numFailed;
	_funcptr_glVertexAttrib2dvARB = (PFNGLVERTEXATTRIB2DVARBPROC)IntGetProcAddress("glVertexAttrib2dvARB");
	if(!_funcptr_glVertexAttrib2dvARB) ++numFailed;
	_funcptr_glVertexAttrib2fARB = (PFNGLVERTEXATTRIB2FARBPROC)IntGetProcAddress("glVertexAttrib2fARB");
	if(!_funcptr_glVertexAttrib2fARB) ++numFailed;
	_funcptr_glVertexAttrib2fvARB = (PFNGLVERTEXATTRIB2FVARBPROC)IntGetProcAddress("glVertexAttrib2fvARB");
	if(!_funcptr_glVertexAttrib2fvARB) ++numFailed;
	_funcptr_glVertexAttrib2sARB = (PFNGLVERTEXATTRIB2SARBPROC)IntGetProcAddress("glVertexAttrib2sARB");
	if(!_funcptr_glVertexAttrib2sARB) ++numFailed;
	_funcptr_glVertexAttrib2svARB = (PFNGLVERTEXATTRIB2SVARBPROC)IntGetProcAddress("glVertexAttrib2svARB");
	if(!_funcptr_glVertexAttrib2svARB) ++numFailed;
	_funcptr_glVertexAttrib3dARB = (PFNGLVERTEXATTRIB3DARBPROC)IntGetProcAddress("glVertexAttrib3dARB");
	if(!_funcptr_glVertexAttrib3dARB) ++numFailed;
	_funcptr_glVertexAttrib3dvARB = (PFNGLVERTEXATTRIB3DVARBPROC)IntGetProcAddress("glVertexAttrib3dvARB");
	if(!_funcptr_glVertexAttrib3dvARB) ++numFailed;
	_funcptr_glVertexAttrib3fARB = (PFNGLVERTEXATTRIB3FARBPROC)IntGetProcAddress("glVertexAttrib3fARB");
	if(!_funcptr_glVertexAttrib3fARB) ++numFailed;
	_funcptr_glVertexAttrib3fvARB = (PFNGLVERTEXATTRIB3FVARBPROC)IntGetProcAddress("glVertexAttrib3fvARB");
	if(!_funcptr_glVertexAttrib3fvARB) ++numFailed;
	_funcptr_glVertexAttrib3sARB = (PFNGLVERTEXATTRIB3SARBPROC)IntGetProcAddress("glVertexAttrib3sARB");
	if(!_funcptr_glVertexAttrib3sARB) ++numFailed;
	_funcptr_glVertexAttrib3svARB = (PFNGLVERTEXATTRIB3SVARBPROC)IntGetProcAddress("glVertexAttrib3svARB");
	if(!_funcptr_glVertexAttrib3svARB) ++numFailed;
	_funcptr_glVertexAttrib4NbvARB = (PFNGLVERTEXATTRIB4NBVARBPROC)IntGetProcAddress("glVertexAttrib4NbvARB");
	if(!_funcptr_glVertexAttrib4NbvARB) ++numFailed;
	_funcptr_glVertexAttrib4NivARB = (PFNGLVERTEXATTRIB4NIVARBPROC)IntGetProcAddress("glVertexAttrib4NivARB");
	if(!_funcptr_glVertexAttrib4NivARB) ++numFailed;
	_funcptr_glVertexAttrib4NsvARB = (PFNGLVERTEXATTRIB4NSVARBPROC)IntGetProcAddress("glVertexAttrib4NsvARB");
	if(!_funcptr_glVertexAttrib4NsvARB) ++numFailed;
	_funcptr_glVertexAttrib4NubARB = (PFNGLVERTEXATTRIB4NUBARBPROC)IntGetProcAddress("glVertexAttrib4NubARB");
	if(!_funcptr_glVertexAttrib4NubARB) ++numFailed;
	_funcptr_glVertexAttrib4NubvARB = (PFNGLVERTEXATTRIB4NUBVARBPROC)IntGetProcAddress("glVertexAttrib4NubvARB");
	if(!_funcptr_glVertexAttrib4NubvARB) ++numFailed;
	_funcptr_glVertexAttrib4NuivARB = (PFNGLVERTEXATTRIB4NUIVARBPROC)IntGetProcAddress("glVertexAttrib4NuivARB");
	if(!_funcptr_glVertexAttrib4NuivARB) ++numFailed;
	_funcptr_glVertexAttrib4NusvARB = (PFNGLVERTEXATTRIB4NUSVARBPROC)IntGetProcAddress("glVertexAttrib4NusvARB");
	if(!_funcptr_glVertexAttrib4NusvARB) ++numFailed;
	_funcptr_glVertexAttrib4bvARB = (PFNGLVERTEXATTRIB4BVARBPROC)IntGetProcAddress("glVertexAttrib4bvARB");
	if(!_funcptr_glVertexAttrib4bvARB) ++numFailed;
	_funcptr_glVertexAttrib4dARB = (PFNGLVERTEXATTRIB4DARBPROC)IntGetProcAddress("glVertexAttrib4dARB");
	if(!_funcptr_glVertexAttrib4dARB) ++numFailed;
	_funcptr_glVertexAttrib4dvARB = (PFNGLVERTEXATTRIB4DVARBPROC)IntGetProcAddress("glVertexAttrib4dvARB");
	if(!_funcptr_glVertexAttrib4dvARB) ++numFailed;
	_funcptr_glVertexAttrib4fARB = (PFNGLVERTEXATTRIB4FARBPROC)IntGetProcAddress("glVertexAttrib4fARB");
	if(!_funcptr_glVertexAttrib4fARB) ++numFailed;
	_funcptr_glVertexAttrib4fvARB = (PFNGLVERTEXATTRIB4FVARBPROC)IntGetProcAddress("glVertexAttrib4fvARB");
	if(!_funcptr_glVertexAttrib4fvARB) ++numFailed;
	_funcptr_glVertexAttrib4ivARB = (PFNGLVERTEXATTRIB4IVARBPROC)IntGetProcAddress("glVertexAttrib4ivARB");
	if(!_funcptr_glVertexAttrib4ivARB) ++numFailed;
	_funcptr_glVertexAttrib4sARB = (PFNGLVERTEXATTRIB4SARBPROC)IntGetProcAddress("glVertexAttrib4sARB");
	if(!_funcptr_glVertexAttrib4sARB) ++numFailed;
	_funcptr_glVertexAttrib4svARB = (PFNGLVERTEXATTRIB4SVARBPROC)IntGetProcAddress("glVertexAttrib4svARB");
	if(!_funcptr_glVertexAttrib4svARB) ++numFailed;
	_funcptr_glVertexAttrib4ubvARB = (PFNGLVERTEXATTRIB4UBVARBPROC)IntGetProcAddress("glVertexAttrib4ubvARB");
	if(!_funcptr_glVertexAttrib4ubvARB) ++numFailed;
	_funcptr_glVertexAttrib4uivARB = (PFNGLVERTEXATTRIB4UIVARBPROC)IntGetProcAddress("glVertexAttrib4uivARB");
	if(!_funcptr_glVertexAttrib4uivARB) ++numFailed;
	_funcptr_glVertexAttrib4usvARB = (PFNGLVERTEXATTRIB4USVARBPROC)IntGetProcAddress("glVertexAttrib4usvARB");
	if(!_funcptr_glVertexAttrib4usvARB) ++numFailed;
	_funcptr_glVertexAttribPointerARB = (PFNGLVERTEXATTRIBPOINTERARBPROC)IntGetProcAddress("glVertexAttribPointerARB");
	if(!_funcptr_glVertexAttribPointerARB) ++numFailed;
	return numFailed;
}