#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  scalar_t__ PFNGLUNIFORMSUBROUTINESUIVPROC ;
typedef  scalar_t__ PFNGLUNIFORMMATRIX4X3DVPROC ;
typedef  scalar_t__ PFNGLUNIFORMMATRIX4X2DVPROC ;
typedef  scalar_t__ PFNGLUNIFORMMATRIX4DVPROC ;
typedef  scalar_t__ PFNGLUNIFORMMATRIX3X4DVPROC ;
typedef  scalar_t__ PFNGLUNIFORMMATRIX3X2DVPROC ;
typedef  scalar_t__ PFNGLUNIFORMMATRIX3DVPROC ;
typedef  scalar_t__ PFNGLUNIFORMMATRIX2X4DVPROC ;
typedef  scalar_t__ PFNGLUNIFORMMATRIX2X3DVPROC ;
typedef  scalar_t__ PFNGLUNIFORMMATRIX2DVPROC ;
typedef  scalar_t__ PFNGLUNIFORM4DVPROC ;
typedef  scalar_t__ PFNGLUNIFORM4DPROC ;
typedef  scalar_t__ PFNGLUNIFORM3DVPROC ;
typedef  scalar_t__ PFNGLUNIFORM3DPROC ;
typedef  scalar_t__ PFNGLUNIFORM2DVPROC ;
typedef  scalar_t__ PFNGLUNIFORM2DPROC ;
typedef  scalar_t__ PFNGLUNIFORM1DVPROC ;
typedef  scalar_t__ PFNGLUNIFORM1DPROC ;
typedef  scalar_t__ PFNGLRESUMETRANSFORMFEEDBACKPROC ;
typedef  scalar_t__ PFNGLPAUSETRANSFORMFEEDBACKPROC ;
typedef  scalar_t__ PFNGLPATCHPARAMETERIPROC ;
typedef  scalar_t__ PFNGLPATCHPARAMETERFVPROC ;
typedef  scalar_t__ PFNGLMINSAMPLESHADINGPROC ;
typedef  scalar_t__ PFNGLISTRANSFORMFEEDBACKPROC ;
typedef  scalar_t__ PFNGLGETUNIFORMSUBROUTINEUIVPROC ;
typedef  scalar_t__ PFNGLGETUNIFORMDVPROC ;
typedef  scalar_t__ PFNGLGETSUBROUTINEUNIFORMLOCATIONPROC ;
typedef  scalar_t__ PFNGLGETSUBROUTINEINDEXPROC ;
typedef  scalar_t__ PFNGLGETQUERYINDEXEDIVPROC ;
typedef  scalar_t__ PFNGLGETPROGRAMSTAGEIVPROC ;
typedef  scalar_t__ PFNGLGETACTIVESUBROUTINEUNIFORMNAMEPROC ;
typedef  scalar_t__ PFNGLGETACTIVESUBROUTINEUNIFORMIVPROC ;
typedef  scalar_t__ PFNGLGETACTIVESUBROUTINENAMEPROC ;
typedef  scalar_t__ PFNGLGENTRANSFORMFEEDBACKSPROC ;
typedef  scalar_t__ PFNGLENDQUERYINDEXEDPROC ;
typedef  scalar_t__ PFNGLDRAWTRANSFORMFEEDBACKSTREAMPROC ;
typedef  scalar_t__ PFNGLDRAWTRANSFORMFEEDBACKPROC ;
typedef  scalar_t__ PFNGLDRAWELEMENTSINDIRECTPROC ;
typedef  scalar_t__ PFNGLDRAWARRAYSINDIRECTPROC ;
typedef  scalar_t__ PFNGLDELETETRANSFORMFEEDBACKSPROC ;
typedef  scalar_t__ PFNGLBLENDFUNCSEPARATEIPROC ;
typedef  scalar_t__ PFNGLBLENDFUNCIPROC ;
typedef  scalar_t__ PFNGLBLENDEQUATIONSEPARATEIPROC ;
typedef  scalar_t__ PFNGLBLENDEQUATIONIPROC ;
typedef  scalar_t__ PFNGLBINDTRANSFORMFEEDBACKPROC ;
typedef  scalar_t__ PFNGLBEGINQUERYINDEXEDPROC ;

/* Variables and functions */
 scalar_t__ IntGetProcAddress (char*) ; 
 scalar_t__ _funcptr_glBeginQueryIndexed ; 
 scalar_t__ _funcptr_glBindTransformFeedback ; 
 scalar_t__ _funcptr_glBlendEquationSeparatei ; 
 scalar_t__ _funcptr_glBlendEquationi ; 
 scalar_t__ _funcptr_glBlendFuncSeparatei ; 
 scalar_t__ _funcptr_glBlendFunci ; 
 scalar_t__ _funcptr_glDeleteTransformFeedbacks ; 
 scalar_t__ _funcptr_glDrawArraysIndirect ; 
 scalar_t__ _funcptr_glDrawElementsIndirect ; 
 scalar_t__ _funcptr_glDrawTransformFeedback ; 
 scalar_t__ _funcptr_glDrawTransformFeedbackStream ; 
 scalar_t__ _funcptr_glEndQueryIndexed ; 
 scalar_t__ _funcptr_glGenTransformFeedbacks ; 
 scalar_t__ _funcptr_glGetActiveSubroutineName ; 
 scalar_t__ _funcptr_glGetActiveSubroutineUniformName ; 
 scalar_t__ _funcptr_glGetActiveSubroutineUniformiv ; 
 scalar_t__ _funcptr_glGetProgramStageiv ; 
 scalar_t__ _funcptr_glGetQueryIndexediv ; 
 scalar_t__ _funcptr_glGetSubroutineIndex ; 
 scalar_t__ _funcptr_glGetSubroutineUniformLocation ; 
 scalar_t__ _funcptr_glGetUniformSubroutineuiv ; 
 scalar_t__ _funcptr_glGetUniformdv ; 
 scalar_t__ _funcptr_glIsTransformFeedback ; 
 scalar_t__ _funcptr_glMinSampleShading ; 
 scalar_t__ _funcptr_glPatchParameterfv ; 
 scalar_t__ _funcptr_glPatchParameteri ; 
 scalar_t__ _funcptr_glPauseTransformFeedback ; 
 scalar_t__ _funcptr_glResumeTransformFeedback ; 
 scalar_t__ _funcptr_glUniform1d ; 
 scalar_t__ _funcptr_glUniform1dv ; 
 scalar_t__ _funcptr_glUniform2d ; 
 scalar_t__ _funcptr_glUniform2dv ; 
 scalar_t__ _funcptr_glUniform3d ; 
 scalar_t__ _funcptr_glUniform3dv ; 
 scalar_t__ _funcptr_glUniform4d ; 
 scalar_t__ _funcptr_glUniform4dv ; 
 scalar_t__ _funcptr_glUniformMatrix2dv ; 
 scalar_t__ _funcptr_glUniformMatrix2x3dv ; 
 scalar_t__ _funcptr_glUniformMatrix2x4dv ; 
 scalar_t__ _funcptr_glUniformMatrix3dv ; 
 scalar_t__ _funcptr_glUniformMatrix3x2dv ; 
 scalar_t__ _funcptr_glUniformMatrix3x4dv ; 
 scalar_t__ _funcptr_glUniformMatrix4dv ; 
 scalar_t__ _funcptr_glUniformMatrix4x2dv ; 
 scalar_t__ _funcptr_glUniformMatrix4x3dv ; 
 scalar_t__ _funcptr_glUniformSubroutinesuiv ; 

__attribute__((used)) static int LoadCore_Version_4_0()
{
	int numFailed = 0;
	_funcptr_glBeginQueryIndexed = (PFNGLBEGINQUERYINDEXEDPROC)IntGetProcAddress("glBeginQueryIndexed");
	if(!_funcptr_glBeginQueryIndexed) ++numFailed;
	_funcptr_glBindTransformFeedback = (PFNGLBINDTRANSFORMFEEDBACKPROC)IntGetProcAddress("glBindTransformFeedback");
	if(!_funcptr_glBindTransformFeedback) ++numFailed;
	_funcptr_glBlendEquationSeparatei = (PFNGLBLENDEQUATIONSEPARATEIPROC)IntGetProcAddress("glBlendEquationSeparatei");
	if(!_funcptr_glBlendEquationSeparatei) ++numFailed;
	_funcptr_glBlendEquationi = (PFNGLBLENDEQUATIONIPROC)IntGetProcAddress("glBlendEquationi");
	if(!_funcptr_glBlendEquationi) ++numFailed;
	_funcptr_glBlendFuncSeparatei = (PFNGLBLENDFUNCSEPARATEIPROC)IntGetProcAddress("glBlendFuncSeparatei");
	if(!_funcptr_glBlendFuncSeparatei) ++numFailed;
	_funcptr_glBlendFunci = (PFNGLBLENDFUNCIPROC)IntGetProcAddress("glBlendFunci");
	if(!_funcptr_glBlendFunci) ++numFailed;
	_funcptr_glDeleteTransformFeedbacks = (PFNGLDELETETRANSFORMFEEDBACKSPROC)IntGetProcAddress("glDeleteTransformFeedbacks");
	if(!_funcptr_glDeleteTransformFeedbacks) ++numFailed;
	_funcptr_glDrawArraysIndirect = (PFNGLDRAWARRAYSINDIRECTPROC)IntGetProcAddress("glDrawArraysIndirect");
	if(!_funcptr_glDrawArraysIndirect) ++numFailed;
	_funcptr_glDrawElementsIndirect = (PFNGLDRAWELEMENTSINDIRECTPROC)IntGetProcAddress("glDrawElementsIndirect");
	if(!_funcptr_glDrawElementsIndirect) ++numFailed;
	_funcptr_glDrawTransformFeedback = (PFNGLDRAWTRANSFORMFEEDBACKPROC)IntGetProcAddress("glDrawTransformFeedback");
	if(!_funcptr_glDrawTransformFeedback) ++numFailed;
	_funcptr_glDrawTransformFeedbackStream = (PFNGLDRAWTRANSFORMFEEDBACKSTREAMPROC)IntGetProcAddress("glDrawTransformFeedbackStream");
	if(!_funcptr_glDrawTransformFeedbackStream) ++numFailed;
	_funcptr_glEndQueryIndexed = (PFNGLENDQUERYINDEXEDPROC)IntGetProcAddress("glEndQueryIndexed");
	if(!_funcptr_glEndQueryIndexed) ++numFailed;
	_funcptr_glGenTransformFeedbacks = (PFNGLGENTRANSFORMFEEDBACKSPROC)IntGetProcAddress("glGenTransformFeedbacks");
	if(!_funcptr_glGenTransformFeedbacks) ++numFailed;
	_funcptr_glGetActiveSubroutineName = (PFNGLGETACTIVESUBROUTINENAMEPROC)IntGetProcAddress("glGetActiveSubroutineName");
	if(!_funcptr_glGetActiveSubroutineName) ++numFailed;
	_funcptr_glGetActiveSubroutineUniformName = (PFNGLGETACTIVESUBROUTINEUNIFORMNAMEPROC)IntGetProcAddress("glGetActiveSubroutineUniformName");
	if(!_funcptr_glGetActiveSubroutineUniformName) ++numFailed;
	_funcptr_glGetActiveSubroutineUniformiv = (PFNGLGETACTIVESUBROUTINEUNIFORMIVPROC)IntGetProcAddress("glGetActiveSubroutineUniformiv");
	if(!_funcptr_glGetActiveSubroutineUniformiv) ++numFailed;
	_funcptr_glGetProgramStageiv = (PFNGLGETPROGRAMSTAGEIVPROC)IntGetProcAddress("glGetProgramStageiv");
	if(!_funcptr_glGetProgramStageiv) ++numFailed;
	_funcptr_glGetQueryIndexediv = (PFNGLGETQUERYINDEXEDIVPROC)IntGetProcAddress("glGetQueryIndexediv");
	if(!_funcptr_glGetQueryIndexediv) ++numFailed;
	_funcptr_glGetSubroutineIndex = (PFNGLGETSUBROUTINEINDEXPROC)IntGetProcAddress("glGetSubroutineIndex");
	if(!_funcptr_glGetSubroutineIndex) ++numFailed;
	_funcptr_glGetSubroutineUniformLocation = (PFNGLGETSUBROUTINEUNIFORMLOCATIONPROC)IntGetProcAddress("glGetSubroutineUniformLocation");
	if(!_funcptr_glGetSubroutineUniformLocation) ++numFailed;
	_funcptr_glGetUniformSubroutineuiv = (PFNGLGETUNIFORMSUBROUTINEUIVPROC)IntGetProcAddress("glGetUniformSubroutineuiv");
	if(!_funcptr_glGetUniformSubroutineuiv) ++numFailed;
	_funcptr_glGetUniformdv = (PFNGLGETUNIFORMDVPROC)IntGetProcAddress("glGetUniformdv");
	if(!_funcptr_glGetUniformdv) ++numFailed;
	_funcptr_glIsTransformFeedback = (PFNGLISTRANSFORMFEEDBACKPROC)IntGetProcAddress("glIsTransformFeedback");
	if(!_funcptr_glIsTransformFeedback) ++numFailed;
	_funcptr_glMinSampleShading = (PFNGLMINSAMPLESHADINGPROC)IntGetProcAddress("glMinSampleShading");
	if(!_funcptr_glMinSampleShading) ++numFailed;
	_funcptr_glPatchParameterfv = (PFNGLPATCHPARAMETERFVPROC)IntGetProcAddress("glPatchParameterfv");
	if(!_funcptr_glPatchParameterfv) ++numFailed;
	_funcptr_glPatchParameteri = (PFNGLPATCHPARAMETERIPROC)IntGetProcAddress("glPatchParameteri");
	if(!_funcptr_glPatchParameteri) ++numFailed;
	_funcptr_glPauseTransformFeedback = (PFNGLPAUSETRANSFORMFEEDBACKPROC)IntGetProcAddress("glPauseTransformFeedback");
	if(!_funcptr_glPauseTransformFeedback) ++numFailed;
	_funcptr_glResumeTransformFeedback = (PFNGLRESUMETRANSFORMFEEDBACKPROC)IntGetProcAddress("glResumeTransformFeedback");
	if(!_funcptr_glResumeTransformFeedback) ++numFailed;
	_funcptr_glUniform1d = (PFNGLUNIFORM1DPROC)IntGetProcAddress("glUniform1d");
	if(!_funcptr_glUniform1d) ++numFailed;
	_funcptr_glUniform1dv = (PFNGLUNIFORM1DVPROC)IntGetProcAddress("glUniform1dv");
	if(!_funcptr_glUniform1dv) ++numFailed;
	_funcptr_glUniform2d = (PFNGLUNIFORM2DPROC)IntGetProcAddress("glUniform2d");
	if(!_funcptr_glUniform2d) ++numFailed;
	_funcptr_glUniform2dv = (PFNGLUNIFORM2DVPROC)IntGetProcAddress("glUniform2dv");
	if(!_funcptr_glUniform2dv) ++numFailed;
	_funcptr_glUniform3d = (PFNGLUNIFORM3DPROC)IntGetProcAddress("glUniform3d");
	if(!_funcptr_glUniform3d) ++numFailed;
	_funcptr_glUniform3dv = (PFNGLUNIFORM3DVPROC)IntGetProcAddress("glUniform3dv");
	if(!_funcptr_glUniform3dv) ++numFailed;
	_funcptr_glUniform4d = (PFNGLUNIFORM4DPROC)IntGetProcAddress("glUniform4d");
	if(!_funcptr_glUniform4d) ++numFailed;
	_funcptr_glUniform4dv = (PFNGLUNIFORM4DVPROC)IntGetProcAddress("glUniform4dv");
	if(!_funcptr_glUniform4dv) ++numFailed;
	_funcptr_glUniformMatrix2dv = (PFNGLUNIFORMMATRIX2DVPROC)IntGetProcAddress("glUniformMatrix2dv");
	if(!_funcptr_glUniformMatrix2dv) ++numFailed;
	_funcptr_glUniformMatrix2x3dv = (PFNGLUNIFORMMATRIX2X3DVPROC)IntGetProcAddress("glUniformMatrix2x3dv");
	if(!_funcptr_glUniformMatrix2x3dv) ++numFailed;
	_funcptr_glUniformMatrix2x4dv = (PFNGLUNIFORMMATRIX2X4DVPROC)IntGetProcAddress("glUniformMatrix2x4dv");
	if(!_funcptr_glUniformMatrix2x4dv) ++numFailed;
	_funcptr_glUniformMatrix3dv = (PFNGLUNIFORMMATRIX3DVPROC)IntGetProcAddress("glUniformMatrix3dv");
	if(!_funcptr_glUniformMatrix3dv) ++numFailed;
	_funcptr_glUniformMatrix3x2dv = (PFNGLUNIFORMMATRIX3X2DVPROC)IntGetProcAddress("glUniformMatrix3x2dv");
	if(!_funcptr_glUniformMatrix3x2dv) ++numFailed;
	_funcptr_glUniformMatrix3x4dv = (PFNGLUNIFORMMATRIX3X4DVPROC)IntGetProcAddress("glUniformMatrix3x4dv");
	if(!_funcptr_glUniformMatrix3x4dv) ++numFailed;
	_funcptr_glUniformMatrix4dv = (PFNGLUNIFORMMATRIX4DVPROC)IntGetProcAddress("glUniformMatrix4dv");
	if(!_funcptr_glUniformMatrix4dv) ++numFailed;
	_funcptr_glUniformMatrix4x2dv = (PFNGLUNIFORMMATRIX4X2DVPROC)IntGetProcAddress("glUniformMatrix4x2dv");
	if(!_funcptr_glUniformMatrix4x2dv) ++numFailed;
	_funcptr_glUniformMatrix4x3dv = (PFNGLUNIFORMMATRIX4X3DVPROC)IntGetProcAddress("glUniformMatrix4x3dv");
	if(!_funcptr_glUniformMatrix4x3dv) ++numFailed;
	_funcptr_glUniformSubroutinesuiv = (PFNGLUNIFORMSUBROUTINESUIVPROC)IntGetProcAddress("glUniformSubroutinesuiv");
	if(!_funcptr_glUniformSubroutinesuiv) ++numFailed;
	return numFailed;
}