#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  scalar_t__ PFNGLVERTEXATTRIBS4UBVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBS4SVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBS4FVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBS4DVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBS3SVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBS3FVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBS3DVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBS2SVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBS2FVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBS2DVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBS1SVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBS1FVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBS1DVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBPOINTERNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4UBVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4UBNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4SVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4SNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4FVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4FNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4DVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4DNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB3SVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB3SNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB3FVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB3FNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB3DVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB3DNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB2SVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB2SNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB2FVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB2FNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB2DVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB2DNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB1SVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB1SNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB1FVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB1FNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB1DVNVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB1DNVPROC ;
typedef  scalar_t__ PFNGLTRACKMATRIXNVPROC ;
typedef  scalar_t__ PFNGLREQUESTRESIDENTPROGRAMSNVPROC ;
typedef  scalar_t__ PFNGLPROGRAMPARAMETERS4FVNVPROC ;
typedef  scalar_t__ PFNGLPROGRAMPARAMETERS4DVNVPROC ;
typedef  scalar_t__ PFNGLPROGRAMPARAMETER4FVNVPROC ;
typedef  scalar_t__ PFNGLPROGRAMPARAMETER4FNVPROC ;
typedef  scalar_t__ PFNGLPROGRAMPARAMETER4DVNVPROC ;
typedef  scalar_t__ PFNGLPROGRAMPARAMETER4DNVPROC ;
typedef  scalar_t__ PFNGLLOADPROGRAMNVPROC ;
typedef  scalar_t__ PFNGLISPROGRAMNVPROC ;
typedef  scalar_t__ PFNGLGETVERTEXATTRIBPOINTERVNVPROC ;
typedef  scalar_t__ PFNGLGETVERTEXATTRIBIVNVPROC ;
typedef  scalar_t__ PFNGLGETVERTEXATTRIBFVNVPROC ;
typedef  scalar_t__ PFNGLGETVERTEXATTRIBDVNVPROC ;
typedef  scalar_t__ PFNGLGETTRACKMATRIXIVNVPROC ;
typedef  scalar_t__ PFNGLGETPROGRAMSTRINGNVPROC ;
typedef  scalar_t__ PFNGLGETPROGRAMPARAMETERFVNVPROC ;
typedef  scalar_t__ PFNGLGETPROGRAMPARAMETERDVNVPROC ;
typedef  scalar_t__ PFNGLGETPROGRAMIVNVPROC ;
typedef  scalar_t__ PFNGLGENPROGRAMSNVPROC ;
typedef  scalar_t__ PFNGLEXECUTEPROGRAMNVPROC ;
typedef  scalar_t__ PFNGLDELETEPROGRAMSNVPROC ;
typedef  scalar_t__ PFNGLBINDPROGRAMNVPROC ;
typedef  scalar_t__ PFNGLAREPROGRAMSRESIDENTNVPROC ;

/* Variables and functions */
 scalar_t__ IntGetProcAddress (char*) ; 
 scalar_t__ _funcptr_glAreProgramsResidentNV ; 
 scalar_t__ _funcptr_glBindProgramNV ; 
 scalar_t__ _funcptr_glDeleteProgramsNV ; 
 scalar_t__ _funcptr_glExecuteProgramNV ; 
 scalar_t__ _funcptr_glGenProgramsNV ; 
 scalar_t__ _funcptr_glGetProgramParameterdvNV ; 
 scalar_t__ _funcptr_glGetProgramParameterfvNV ; 
 scalar_t__ _funcptr_glGetProgramStringNV ; 
 scalar_t__ _funcptr_glGetProgramivNV ; 
 scalar_t__ _funcptr_glGetTrackMatrixivNV ; 
 scalar_t__ _funcptr_glGetVertexAttribPointervNV ; 
 scalar_t__ _funcptr_glGetVertexAttribdvNV ; 
 scalar_t__ _funcptr_glGetVertexAttribfvNV ; 
 scalar_t__ _funcptr_glGetVertexAttribivNV ; 
 scalar_t__ _funcptr_glIsProgramNV ; 
 scalar_t__ _funcptr_glLoadProgramNV ; 
 scalar_t__ _funcptr_glProgramParameter4dNV ; 
 scalar_t__ _funcptr_glProgramParameter4dvNV ; 
 scalar_t__ _funcptr_glProgramParameter4fNV ; 
 scalar_t__ _funcptr_glProgramParameter4fvNV ; 
 scalar_t__ _funcptr_glProgramParameters4dvNV ; 
 scalar_t__ _funcptr_glProgramParameters4fvNV ; 
 scalar_t__ _funcptr_glRequestResidentProgramsNV ; 
 scalar_t__ _funcptr_glTrackMatrixNV ; 
 scalar_t__ _funcptr_glVertexAttrib1dNV ; 
 scalar_t__ _funcptr_glVertexAttrib1dvNV ; 
 scalar_t__ _funcptr_glVertexAttrib1fNV ; 
 scalar_t__ _funcptr_glVertexAttrib1fvNV ; 
 scalar_t__ _funcptr_glVertexAttrib1sNV ; 
 scalar_t__ _funcptr_glVertexAttrib1svNV ; 
 scalar_t__ _funcptr_glVertexAttrib2dNV ; 
 scalar_t__ _funcptr_glVertexAttrib2dvNV ; 
 scalar_t__ _funcptr_glVertexAttrib2fNV ; 
 scalar_t__ _funcptr_glVertexAttrib2fvNV ; 
 scalar_t__ _funcptr_glVertexAttrib2sNV ; 
 scalar_t__ _funcptr_glVertexAttrib2svNV ; 
 scalar_t__ _funcptr_glVertexAttrib3dNV ; 
 scalar_t__ _funcptr_glVertexAttrib3dvNV ; 
 scalar_t__ _funcptr_glVertexAttrib3fNV ; 
 scalar_t__ _funcptr_glVertexAttrib3fvNV ; 
 scalar_t__ _funcptr_glVertexAttrib3sNV ; 
 scalar_t__ _funcptr_glVertexAttrib3svNV ; 
 scalar_t__ _funcptr_glVertexAttrib4dNV ; 
 scalar_t__ _funcptr_glVertexAttrib4dvNV ; 
 scalar_t__ _funcptr_glVertexAttrib4fNV ; 
 scalar_t__ _funcptr_glVertexAttrib4fvNV ; 
 scalar_t__ _funcptr_glVertexAttrib4sNV ; 
 scalar_t__ _funcptr_glVertexAttrib4svNV ; 
 scalar_t__ _funcptr_glVertexAttrib4ubNV ; 
 scalar_t__ _funcptr_glVertexAttrib4ubvNV ; 
 scalar_t__ _funcptr_glVertexAttribPointerNV ; 
 scalar_t__ _funcptr_glVertexAttribs1dvNV ; 
 scalar_t__ _funcptr_glVertexAttribs1fvNV ; 
 scalar_t__ _funcptr_glVertexAttribs1svNV ; 
 scalar_t__ _funcptr_glVertexAttribs2dvNV ; 
 scalar_t__ _funcptr_glVertexAttribs2fvNV ; 
 scalar_t__ _funcptr_glVertexAttribs2svNV ; 
 scalar_t__ _funcptr_glVertexAttribs3dvNV ; 
 scalar_t__ _funcptr_glVertexAttribs3fvNV ; 
 scalar_t__ _funcptr_glVertexAttribs3svNV ; 
 scalar_t__ _funcptr_glVertexAttribs4dvNV ; 
 scalar_t__ _funcptr_glVertexAttribs4fvNV ; 
 scalar_t__ _funcptr_glVertexAttribs4svNV ; 
 scalar_t__ _funcptr_glVertexAttribs4ubvNV ; 

__attribute__((used)) static int LoadExt_NV_vertex_program()
{
	int numFailed = 0;
	_funcptr_glAreProgramsResidentNV = (PFNGLAREPROGRAMSRESIDENTNVPROC)IntGetProcAddress("glAreProgramsResidentNV");
	if(!_funcptr_glAreProgramsResidentNV) ++numFailed;
	_funcptr_glBindProgramNV = (PFNGLBINDPROGRAMNVPROC)IntGetProcAddress("glBindProgramNV");
	if(!_funcptr_glBindProgramNV) ++numFailed;
	_funcptr_glDeleteProgramsNV = (PFNGLDELETEPROGRAMSNVPROC)IntGetProcAddress("glDeleteProgramsNV");
	if(!_funcptr_glDeleteProgramsNV) ++numFailed;
	_funcptr_glExecuteProgramNV = (PFNGLEXECUTEPROGRAMNVPROC)IntGetProcAddress("glExecuteProgramNV");
	if(!_funcptr_glExecuteProgramNV) ++numFailed;
	_funcptr_glGenProgramsNV = (PFNGLGENPROGRAMSNVPROC)IntGetProcAddress("glGenProgramsNV");
	if(!_funcptr_glGenProgramsNV) ++numFailed;
	_funcptr_glGetProgramParameterdvNV = (PFNGLGETPROGRAMPARAMETERDVNVPROC)IntGetProcAddress("glGetProgramParameterdvNV");
	if(!_funcptr_glGetProgramParameterdvNV) ++numFailed;
	_funcptr_glGetProgramParameterfvNV = (PFNGLGETPROGRAMPARAMETERFVNVPROC)IntGetProcAddress("glGetProgramParameterfvNV");
	if(!_funcptr_glGetProgramParameterfvNV) ++numFailed;
	_funcptr_glGetProgramStringNV = (PFNGLGETPROGRAMSTRINGNVPROC)IntGetProcAddress("glGetProgramStringNV");
	if(!_funcptr_glGetProgramStringNV) ++numFailed;
	_funcptr_glGetProgramivNV = (PFNGLGETPROGRAMIVNVPROC)IntGetProcAddress("glGetProgramivNV");
	if(!_funcptr_glGetProgramivNV) ++numFailed;
	_funcptr_glGetTrackMatrixivNV = (PFNGLGETTRACKMATRIXIVNVPROC)IntGetProcAddress("glGetTrackMatrixivNV");
	if(!_funcptr_glGetTrackMatrixivNV) ++numFailed;
	_funcptr_glGetVertexAttribPointervNV = (PFNGLGETVERTEXATTRIBPOINTERVNVPROC)IntGetProcAddress("glGetVertexAttribPointervNV");
	if(!_funcptr_glGetVertexAttribPointervNV) ++numFailed;
	_funcptr_glGetVertexAttribdvNV = (PFNGLGETVERTEXATTRIBDVNVPROC)IntGetProcAddress("glGetVertexAttribdvNV");
	if(!_funcptr_glGetVertexAttribdvNV) ++numFailed;
	_funcptr_glGetVertexAttribfvNV = (PFNGLGETVERTEXATTRIBFVNVPROC)IntGetProcAddress("glGetVertexAttribfvNV");
	if(!_funcptr_glGetVertexAttribfvNV) ++numFailed;
	_funcptr_glGetVertexAttribivNV = (PFNGLGETVERTEXATTRIBIVNVPROC)IntGetProcAddress("glGetVertexAttribivNV");
	if(!_funcptr_glGetVertexAttribivNV) ++numFailed;
	_funcptr_glIsProgramNV = (PFNGLISPROGRAMNVPROC)IntGetProcAddress("glIsProgramNV");
	if(!_funcptr_glIsProgramNV) ++numFailed;
	_funcptr_glLoadProgramNV = (PFNGLLOADPROGRAMNVPROC)IntGetProcAddress("glLoadProgramNV");
	if(!_funcptr_glLoadProgramNV) ++numFailed;
	_funcptr_glProgramParameter4dNV = (PFNGLPROGRAMPARAMETER4DNVPROC)IntGetProcAddress("glProgramParameter4dNV");
	if(!_funcptr_glProgramParameter4dNV) ++numFailed;
	_funcptr_glProgramParameter4dvNV = (PFNGLPROGRAMPARAMETER4DVNVPROC)IntGetProcAddress("glProgramParameter4dvNV");
	if(!_funcptr_glProgramParameter4dvNV) ++numFailed;
	_funcptr_glProgramParameter4fNV = (PFNGLPROGRAMPARAMETER4FNVPROC)IntGetProcAddress("glProgramParameter4fNV");
	if(!_funcptr_glProgramParameter4fNV) ++numFailed;
	_funcptr_glProgramParameter4fvNV = (PFNGLPROGRAMPARAMETER4FVNVPROC)IntGetProcAddress("glProgramParameter4fvNV");
	if(!_funcptr_glProgramParameter4fvNV) ++numFailed;
	_funcptr_glProgramParameters4dvNV = (PFNGLPROGRAMPARAMETERS4DVNVPROC)IntGetProcAddress("glProgramParameters4dvNV");
	if(!_funcptr_glProgramParameters4dvNV) ++numFailed;
	_funcptr_glProgramParameters4fvNV = (PFNGLPROGRAMPARAMETERS4FVNVPROC)IntGetProcAddress("glProgramParameters4fvNV");
	if(!_funcptr_glProgramParameters4fvNV) ++numFailed;
	_funcptr_glRequestResidentProgramsNV = (PFNGLREQUESTRESIDENTPROGRAMSNVPROC)IntGetProcAddress("glRequestResidentProgramsNV");
	if(!_funcptr_glRequestResidentProgramsNV) ++numFailed;
	_funcptr_glTrackMatrixNV = (PFNGLTRACKMATRIXNVPROC)IntGetProcAddress("glTrackMatrixNV");
	if(!_funcptr_glTrackMatrixNV) ++numFailed;
	_funcptr_glVertexAttrib1dNV = (PFNGLVERTEXATTRIB1DNVPROC)IntGetProcAddress("glVertexAttrib1dNV");
	if(!_funcptr_glVertexAttrib1dNV) ++numFailed;
	_funcptr_glVertexAttrib1dvNV = (PFNGLVERTEXATTRIB1DVNVPROC)IntGetProcAddress("glVertexAttrib1dvNV");
	if(!_funcptr_glVertexAttrib1dvNV) ++numFailed;
	_funcptr_glVertexAttrib1fNV = (PFNGLVERTEXATTRIB1FNVPROC)IntGetProcAddress("glVertexAttrib1fNV");
	if(!_funcptr_glVertexAttrib1fNV) ++numFailed;
	_funcptr_glVertexAttrib1fvNV = (PFNGLVERTEXATTRIB1FVNVPROC)IntGetProcAddress("glVertexAttrib1fvNV");
	if(!_funcptr_glVertexAttrib1fvNV) ++numFailed;
	_funcptr_glVertexAttrib1sNV = (PFNGLVERTEXATTRIB1SNVPROC)IntGetProcAddress("glVertexAttrib1sNV");
	if(!_funcptr_glVertexAttrib1sNV) ++numFailed;
	_funcptr_glVertexAttrib1svNV = (PFNGLVERTEXATTRIB1SVNVPROC)IntGetProcAddress("glVertexAttrib1svNV");
	if(!_funcptr_glVertexAttrib1svNV) ++numFailed;
	_funcptr_glVertexAttrib2dNV = (PFNGLVERTEXATTRIB2DNVPROC)IntGetProcAddress("glVertexAttrib2dNV");
	if(!_funcptr_glVertexAttrib2dNV) ++numFailed;
	_funcptr_glVertexAttrib2dvNV = (PFNGLVERTEXATTRIB2DVNVPROC)IntGetProcAddress("glVertexAttrib2dvNV");
	if(!_funcptr_glVertexAttrib2dvNV) ++numFailed;
	_funcptr_glVertexAttrib2fNV = (PFNGLVERTEXATTRIB2FNVPROC)IntGetProcAddress("glVertexAttrib2fNV");
	if(!_funcptr_glVertexAttrib2fNV) ++numFailed;
	_funcptr_glVertexAttrib2fvNV = (PFNGLVERTEXATTRIB2FVNVPROC)IntGetProcAddress("glVertexAttrib2fvNV");
	if(!_funcptr_glVertexAttrib2fvNV) ++numFailed;
	_funcptr_glVertexAttrib2sNV = (PFNGLVERTEXATTRIB2SNVPROC)IntGetProcAddress("glVertexAttrib2sNV");
	if(!_funcptr_glVertexAttrib2sNV) ++numFailed;
	_funcptr_glVertexAttrib2svNV = (PFNGLVERTEXATTRIB2SVNVPROC)IntGetProcAddress("glVertexAttrib2svNV");
	if(!_funcptr_glVertexAttrib2svNV) ++numFailed;
	_funcptr_glVertexAttrib3dNV = (PFNGLVERTEXATTRIB3DNVPROC)IntGetProcAddress("glVertexAttrib3dNV");
	if(!_funcptr_glVertexAttrib3dNV) ++numFailed;
	_funcptr_glVertexAttrib3dvNV = (PFNGLVERTEXATTRIB3DVNVPROC)IntGetProcAddress("glVertexAttrib3dvNV");
	if(!_funcptr_glVertexAttrib3dvNV) ++numFailed;
	_funcptr_glVertexAttrib3fNV = (PFNGLVERTEXATTRIB3FNVPROC)IntGetProcAddress("glVertexAttrib3fNV");
	if(!_funcptr_glVertexAttrib3fNV) ++numFailed;
	_funcptr_glVertexAttrib3fvNV = (PFNGLVERTEXATTRIB3FVNVPROC)IntGetProcAddress("glVertexAttrib3fvNV");
	if(!_funcptr_glVertexAttrib3fvNV) ++numFailed;
	_funcptr_glVertexAttrib3sNV = (PFNGLVERTEXATTRIB3SNVPROC)IntGetProcAddress("glVertexAttrib3sNV");
	if(!_funcptr_glVertexAttrib3sNV) ++numFailed;
	_funcptr_glVertexAttrib3svNV = (PFNGLVERTEXATTRIB3SVNVPROC)IntGetProcAddress("glVertexAttrib3svNV");
	if(!_funcptr_glVertexAttrib3svNV) ++numFailed;
	_funcptr_glVertexAttrib4dNV = (PFNGLVERTEXATTRIB4DNVPROC)IntGetProcAddress("glVertexAttrib4dNV");
	if(!_funcptr_glVertexAttrib4dNV) ++numFailed;
	_funcptr_glVertexAttrib4dvNV = (PFNGLVERTEXATTRIB4DVNVPROC)IntGetProcAddress("glVertexAttrib4dvNV");
	if(!_funcptr_glVertexAttrib4dvNV) ++numFailed;
	_funcptr_glVertexAttrib4fNV = (PFNGLVERTEXATTRIB4FNVPROC)IntGetProcAddress("glVertexAttrib4fNV");
	if(!_funcptr_glVertexAttrib4fNV) ++numFailed;
	_funcptr_glVertexAttrib4fvNV = (PFNGLVERTEXATTRIB4FVNVPROC)IntGetProcAddress("glVertexAttrib4fvNV");
	if(!_funcptr_glVertexAttrib4fvNV) ++numFailed;
	_funcptr_glVertexAttrib4sNV = (PFNGLVERTEXATTRIB4SNVPROC)IntGetProcAddress("glVertexAttrib4sNV");
	if(!_funcptr_glVertexAttrib4sNV) ++numFailed;
	_funcptr_glVertexAttrib4svNV = (PFNGLVERTEXATTRIB4SVNVPROC)IntGetProcAddress("glVertexAttrib4svNV");
	if(!_funcptr_glVertexAttrib4svNV) ++numFailed;
	_funcptr_glVertexAttrib4ubNV = (PFNGLVERTEXATTRIB4UBNVPROC)IntGetProcAddress("glVertexAttrib4ubNV");
	if(!_funcptr_glVertexAttrib4ubNV) ++numFailed;
	_funcptr_glVertexAttrib4ubvNV = (PFNGLVERTEXATTRIB4UBVNVPROC)IntGetProcAddress("glVertexAttrib4ubvNV");
	if(!_funcptr_glVertexAttrib4ubvNV) ++numFailed;
	_funcptr_glVertexAttribPointerNV = (PFNGLVERTEXATTRIBPOINTERNVPROC)IntGetProcAddress("glVertexAttribPointerNV");
	if(!_funcptr_glVertexAttribPointerNV) ++numFailed;
	_funcptr_glVertexAttribs1dvNV = (PFNGLVERTEXATTRIBS1DVNVPROC)IntGetProcAddress("glVertexAttribs1dvNV");
	if(!_funcptr_glVertexAttribs1dvNV) ++numFailed;
	_funcptr_glVertexAttribs1fvNV = (PFNGLVERTEXATTRIBS1FVNVPROC)IntGetProcAddress("glVertexAttribs1fvNV");
	if(!_funcptr_glVertexAttribs1fvNV) ++numFailed;
	_funcptr_glVertexAttribs1svNV = (PFNGLVERTEXATTRIBS1SVNVPROC)IntGetProcAddress("glVertexAttribs1svNV");
	if(!_funcptr_glVertexAttribs1svNV) ++numFailed;
	_funcptr_glVertexAttribs2dvNV = (PFNGLVERTEXATTRIBS2DVNVPROC)IntGetProcAddress("glVertexAttribs2dvNV");
	if(!_funcptr_glVertexAttribs2dvNV) ++numFailed;
	_funcptr_glVertexAttribs2fvNV = (PFNGLVERTEXATTRIBS2FVNVPROC)IntGetProcAddress("glVertexAttribs2fvNV");
	if(!_funcptr_glVertexAttribs2fvNV) ++numFailed;
	_funcptr_glVertexAttribs2svNV = (PFNGLVERTEXATTRIBS2SVNVPROC)IntGetProcAddress("glVertexAttribs2svNV");
	if(!_funcptr_glVertexAttribs2svNV) ++numFailed;
	_funcptr_glVertexAttribs3dvNV = (PFNGLVERTEXATTRIBS3DVNVPROC)IntGetProcAddress("glVertexAttribs3dvNV");
	if(!_funcptr_glVertexAttribs3dvNV) ++numFailed;
	_funcptr_glVertexAttribs3fvNV = (PFNGLVERTEXATTRIBS3FVNVPROC)IntGetProcAddress("glVertexAttribs3fvNV");
	if(!_funcptr_glVertexAttribs3fvNV) ++numFailed;
	_funcptr_glVertexAttribs3svNV = (PFNGLVERTEXATTRIBS3SVNVPROC)IntGetProcAddress("glVertexAttribs3svNV");
	if(!_funcptr_glVertexAttribs3svNV) ++numFailed;
	_funcptr_glVertexAttribs4dvNV = (PFNGLVERTEXATTRIBS4DVNVPROC)IntGetProcAddress("glVertexAttribs4dvNV");
	if(!_funcptr_glVertexAttribs4dvNV) ++numFailed;
	_funcptr_glVertexAttribs4fvNV = (PFNGLVERTEXATTRIBS4FVNVPROC)IntGetProcAddress("glVertexAttribs4fvNV");
	if(!_funcptr_glVertexAttribs4fvNV) ++numFailed;
	_funcptr_glVertexAttribs4svNV = (PFNGLVERTEXATTRIBS4SVNVPROC)IntGetProcAddress("glVertexAttribs4svNV");
	if(!_funcptr_glVertexAttribs4svNV) ++numFailed;
	_funcptr_glVertexAttribs4ubvNV = (PFNGLVERTEXATTRIBS4UBVNVPROC)IntGetProcAddress("glVertexAttribs4ubvNV");
	if(!_funcptr_glVertexAttribs4ubvNV) ++numFailed;
	return numFailed;
}