#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  scalar_t__ PFNGLVERTEXATTRIBPOINTERPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4USVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4UIVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4UBVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4SVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4SPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4NUSVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4NUIVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4NUBVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4NUBPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4NSVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4NIVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4NBVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4IVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4FVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4FPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4DVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4DPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB4BVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB3SVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB3SPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB3FVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB3FPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB3DVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB3DPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB2SVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB2SPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB2FVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB2FPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB2DVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB2DPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB1SVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB1SPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB1FVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB1FPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB1DVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIB1DPROC ;
typedef  scalar_t__ PFNGLVALIDATEPROGRAMPROC ;
typedef  scalar_t__ PFNGLUSEPROGRAMPROC ;
typedef  scalar_t__ PFNGLUNIFORMMATRIX4FVPROC ;
typedef  scalar_t__ PFNGLUNIFORMMATRIX3FVPROC ;
typedef  scalar_t__ PFNGLUNIFORMMATRIX2FVPROC ;
typedef  scalar_t__ PFNGLUNIFORM4IVPROC ;
typedef  scalar_t__ PFNGLUNIFORM4IPROC ;
typedef  scalar_t__ PFNGLUNIFORM4FVPROC ;
typedef  scalar_t__ PFNGLUNIFORM4FPROC ;
typedef  scalar_t__ PFNGLUNIFORM3IVPROC ;
typedef  scalar_t__ PFNGLUNIFORM3IPROC ;
typedef  scalar_t__ PFNGLUNIFORM3FVPROC ;
typedef  scalar_t__ PFNGLUNIFORM3FPROC ;
typedef  scalar_t__ PFNGLUNIFORM2IVPROC ;
typedef  scalar_t__ PFNGLUNIFORM2IPROC ;
typedef  scalar_t__ PFNGLUNIFORM2FVPROC ;
typedef  scalar_t__ PFNGLUNIFORM2FPROC ;
typedef  scalar_t__ PFNGLUNIFORM1IVPROC ;
typedef  scalar_t__ PFNGLUNIFORM1IPROC ;
typedef  scalar_t__ PFNGLUNIFORM1FVPROC ;
typedef  scalar_t__ PFNGLUNIFORM1FPROC ;
typedef  scalar_t__ PFNGLSTENCILOPSEPARATEPROC ;
typedef  scalar_t__ PFNGLSTENCILMASKSEPARATEPROC ;
typedef  scalar_t__ PFNGLSTENCILFUNCSEPARATEPROC ;
typedef  scalar_t__ PFNGLSHADERSOURCEPROC ;
typedef  scalar_t__ PFNGLLINKPROGRAMPROC ;
typedef  scalar_t__ PFNGLISSHADERPROC ;
typedef  scalar_t__ PFNGLISPROGRAMPROC ;
typedef  scalar_t__ PFNGLGETVERTEXATTRIBPOINTERVPROC ;
typedef  scalar_t__ PFNGLGETVERTEXATTRIBIVPROC ;
typedef  scalar_t__ PFNGLGETVERTEXATTRIBFVPROC ;
typedef  scalar_t__ PFNGLGETVERTEXATTRIBDVPROC ;
typedef  scalar_t__ PFNGLGETUNIFORMLOCATIONPROC ;
typedef  scalar_t__ PFNGLGETUNIFORMIVPROC ;
typedef  scalar_t__ PFNGLGETUNIFORMFVPROC ;
typedef  scalar_t__ PFNGLGETSHADERSOURCEPROC ;
typedef  scalar_t__ PFNGLGETSHADERIVPROC ;
typedef  scalar_t__ PFNGLGETSHADERINFOLOGPROC ;
typedef  scalar_t__ PFNGLGETPROGRAMIVPROC ;
typedef  scalar_t__ PFNGLGETPROGRAMINFOLOGPROC ;
typedef  scalar_t__ PFNGLGETATTRIBLOCATIONPROC ;
typedef  scalar_t__ PFNGLGETATTACHEDSHADERSPROC ;
typedef  scalar_t__ PFNGLGETACTIVEUNIFORMPROC ;
typedef  scalar_t__ PFNGLGETACTIVEATTRIBPROC ;
typedef  scalar_t__ PFNGLENABLEVERTEXATTRIBARRAYPROC ;
typedef  scalar_t__ PFNGLDRAWBUFFERSPROC ;
typedef  scalar_t__ PFNGLDISABLEVERTEXATTRIBARRAYPROC ;
typedef  scalar_t__ PFNGLDETACHSHADERPROC ;
typedef  scalar_t__ PFNGLDELETESHADERPROC ;
typedef  scalar_t__ PFNGLDELETEPROGRAMPROC ;
typedef  scalar_t__ PFNGLCREATESHADERPROC ;
typedef  scalar_t__ PFNGLCREATEPROGRAMPROC ;
typedef  scalar_t__ PFNGLCOMPILESHADERPROC ;
typedef  scalar_t__ PFNGLBLENDEQUATIONSEPARATEPROC ;
typedef  scalar_t__ PFNGLBINDATTRIBLOCATIONPROC ;
typedef  scalar_t__ PFNGLATTACHSHADERPROC ;

/* Variables and functions */
 scalar_t__ IntGetProcAddress (char*) ; 
 scalar_t__ _funcptr_glAttachShader ; 
 scalar_t__ _funcptr_glBindAttribLocation ; 
 scalar_t__ _funcptr_glBlendEquationSeparate ; 
 scalar_t__ _funcptr_glCompileShader ; 
 scalar_t__ _funcptr_glCreateProgram ; 
 scalar_t__ _funcptr_glCreateShader ; 
 scalar_t__ _funcptr_glDeleteProgram ; 
 scalar_t__ _funcptr_glDeleteShader ; 
 scalar_t__ _funcptr_glDetachShader ; 
 scalar_t__ _funcptr_glDisableVertexAttribArray ; 
 scalar_t__ _funcptr_glDrawBuffers ; 
 scalar_t__ _funcptr_glEnableVertexAttribArray ; 
 scalar_t__ _funcptr_glGetActiveAttrib ; 
 scalar_t__ _funcptr_glGetActiveUniform ; 
 scalar_t__ _funcptr_glGetAttachedShaders ; 
 scalar_t__ _funcptr_glGetAttribLocation ; 
 scalar_t__ _funcptr_glGetProgramInfoLog ; 
 scalar_t__ _funcptr_glGetProgramiv ; 
 scalar_t__ _funcptr_glGetShaderInfoLog ; 
 scalar_t__ _funcptr_glGetShaderSource ; 
 scalar_t__ _funcptr_glGetShaderiv ; 
 scalar_t__ _funcptr_glGetUniformLocation ; 
 scalar_t__ _funcptr_glGetUniformfv ; 
 scalar_t__ _funcptr_glGetUniformiv ; 
 scalar_t__ _funcptr_glGetVertexAttribPointerv ; 
 scalar_t__ _funcptr_glGetVertexAttribdv ; 
 scalar_t__ _funcptr_glGetVertexAttribfv ; 
 scalar_t__ _funcptr_glGetVertexAttribiv ; 
 scalar_t__ _funcptr_glIsProgram ; 
 scalar_t__ _funcptr_glIsShader ; 
 scalar_t__ _funcptr_glLinkProgram ; 
 scalar_t__ _funcptr_glShaderSource ; 
 scalar_t__ _funcptr_glStencilFuncSeparate ; 
 scalar_t__ _funcptr_glStencilMaskSeparate ; 
 scalar_t__ _funcptr_glStencilOpSeparate ; 
 scalar_t__ _funcptr_glUniform1f ; 
 scalar_t__ _funcptr_glUniform1fv ; 
 scalar_t__ _funcptr_glUniform1i ; 
 scalar_t__ _funcptr_glUniform1iv ; 
 scalar_t__ _funcptr_glUniform2f ; 
 scalar_t__ _funcptr_glUniform2fv ; 
 scalar_t__ _funcptr_glUniform2i ; 
 scalar_t__ _funcptr_glUniform2iv ; 
 scalar_t__ _funcptr_glUniform3f ; 
 scalar_t__ _funcptr_glUniform3fv ; 
 scalar_t__ _funcptr_glUniform3i ; 
 scalar_t__ _funcptr_glUniform3iv ; 
 scalar_t__ _funcptr_glUniform4f ; 
 scalar_t__ _funcptr_glUniform4fv ; 
 scalar_t__ _funcptr_glUniform4i ; 
 scalar_t__ _funcptr_glUniform4iv ; 
 scalar_t__ _funcptr_glUniformMatrix2fv ; 
 scalar_t__ _funcptr_glUniformMatrix3fv ; 
 scalar_t__ _funcptr_glUniformMatrix4fv ; 
 scalar_t__ _funcptr_glUseProgram ; 
 scalar_t__ _funcptr_glValidateProgram ; 
 scalar_t__ _funcptr_glVertexAttrib1d ; 
 scalar_t__ _funcptr_glVertexAttrib1dv ; 
 scalar_t__ _funcptr_glVertexAttrib1f ; 
 scalar_t__ _funcptr_glVertexAttrib1fv ; 
 scalar_t__ _funcptr_glVertexAttrib1s ; 
 scalar_t__ _funcptr_glVertexAttrib1sv ; 
 scalar_t__ _funcptr_glVertexAttrib2d ; 
 scalar_t__ _funcptr_glVertexAttrib2dv ; 
 scalar_t__ _funcptr_glVertexAttrib2f ; 
 scalar_t__ _funcptr_glVertexAttrib2fv ; 
 scalar_t__ _funcptr_glVertexAttrib2s ; 
 scalar_t__ _funcptr_glVertexAttrib2sv ; 
 scalar_t__ _funcptr_glVertexAttrib3d ; 
 scalar_t__ _funcptr_glVertexAttrib3dv ; 
 scalar_t__ _funcptr_glVertexAttrib3f ; 
 scalar_t__ _funcptr_glVertexAttrib3fv ; 
 scalar_t__ _funcptr_glVertexAttrib3s ; 
 scalar_t__ _funcptr_glVertexAttrib3sv ; 
 scalar_t__ _funcptr_glVertexAttrib4Nbv ; 
 scalar_t__ _funcptr_glVertexAttrib4Niv ; 
 scalar_t__ _funcptr_glVertexAttrib4Nsv ; 
 scalar_t__ _funcptr_glVertexAttrib4Nub ; 
 scalar_t__ _funcptr_glVertexAttrib4Nubv ; 
 scalar_t__ _funcptr_glVertexAttrib4Nuiv ; 
 scalar_t__ _funcptr_glVertexAttrib4Nusv ; 
 scalar_t__ _funcptr_glVertexAttrib4bv ; 
 scalar_t__ _funcptr_glVertexAttrib4d ; 
 scalar_t__ _funcptr_glVertexAttrib4dv ; 
 scalar_t__ _funcptr_glVertexAttrib4f ; 
 scalar_t__ _funcptr_glVertexAttrib4fv ; 
 scalar_t__ _funcptr_glVertexAttrib4iv ; 
 scalar_t__ _funcptr_glVertexAttrib4s ; 
 scalar_t__ _funcptr_glVertexAttrib4sv ; 
 scalar_t__ _funcptr_glVertexAttrib4ubv ; 
 scalar_t__ _funcptr_glVertexAttrib4uiv ; 
 scalar_t__ _funcptr_glVertexAttrib4usv ; 
 scalar_t__ _funcptr_glVertexAttribPointer ; 

__attribute__((used)) static int LoadCore_Version_2_0()
{
	int numFailed = 0;
	_funcptr_glAttachShader = (PFNGLATTACHSHADERPROC)IntGetProcAddress("glAttachShader");
	if(!_funcptr_glAttachShader) ++numFailed;
	_funcptr_glBindAttribLocation = (PFNGLBINDATTRIBLOCATIONPROC)IntGetProcAddress("glBindAttribLocation");
	if(!_funcptr_glBindAttribLocation) ++numFailed;
	_funcptr_glBlendEquationSeparate = (PFNGLBLENDEQUATIONSEPARATEPROC)IntGetProcAddress("glBlendEquationSeparate");
	if(!_funcptr_glBlendEquationSeparate) ++numFailed;
	_funcptr_glCompileShader = (PFNGLCOMPILESHADERPROC)IntGetProcAddress("glCompileShader");
	if(!_funcptr_glCompileShader) ++numFailed;
	_funcptr_glCreateProgram = (PFNGLCREATEPROGRAMPROC)IntGetProcAddress("glCreateProgram");
	if(!_funcptr_glCreateProgram) ++numFailed;
	_funcptr_glCreateShader = (PFNGLCREATESHADERPROC)IntGetProcAddress("glCreateShader");
	if(!_funcptr_glCreateShader) ++numFailed;
	_funcptr_glDeleteProgram = (PFNGLDELETEPROGRAMPROC)IntGetProcAddress("glDeleteProgram");
	if(!_funcptr_glDeleteProgram) ++numFailed;
	_funcptr_glDeleteShader = (PFNGLDELETESHADERPROC)IntGetProcAddress("glDeleteShader");
	if(!_funcptr_glDeleteShader) ++numFailed;
	_funcptr_glDetachShader = (PFNGLDETACHSHADERPROC)IntGetProcAddress("glDetachShader");
	if(!_funcptr_glDetachShader) ++numFailed;
	_funcptr_glDisableVertexAttribArray = (PFNGLDISABLEVERTEXATTRIBARRAYPROC)IntGetProcAddress("glDisableVertexAttribArray");
	if(!_funcptr_glDisableVertexAttribArray) ++numFailed;
	_funcptr_glDrawBuffers = (PFNGLDRAWBUFFERSPROC)IntGetProcAddress("glDrawBuffers");
	if(!_funcptr_glDrawBuffers) ++numFailed;
	_funcptr_glEnableVertexAttribArray = (PFNGLENABLEVERTEXATTRIBARRAYPROC)IntGetProcAddress("glEnableVertexAttribArray");
	if(!_funcptr_glEnableVertexAttribArray) ++numFailed;
	_funcptr_glGetActiveAttrib = (PFNGLGETACTIVEATTRIBPROC)IntGetProcAddress("glGetActiveAttrib");
	if(!_funcptr_glGetActiveAttrib) ++numFailed;
	_funcptr_glGetActiveUniform = (PFNGLGETACTIVEUNIFORMPROC)IntGetProcAddress("glGetActiveUniform");
	if(!_funcptr_glGetActiveUniform) ++numFailed;
	_funcptr_glGetAttachedShaders = (PFNGLGETATTACHEDSHADERSPROC)IntGetProcAddress("glGetAttachedShaders");
	if(!_funcptr_glGetAttachedShaders) ++numFailed;
	_funcptr_glGetAttribLocation = (PFNGLGETATTRIBLOCATIONPROC)IntGetProcAddress("glGetAttribLocation");
	if(!_funcptr_glGetAttribLocation) ++numFailed;
	_funcptr_glGetProgramInfoLog = (PFNGLGETPROGRAMINFOLOGPROC)IntGetProcAddress("glGetProgramInfoLog");
	if(!_funcptr_glGetProgramInfoLog) ++numFailed;
	_funcptr_glGetProgramiv = (PFNGLGETPROGRAMIVPROC)IntGetProcAddress("glGetProgramiv");
	if(!_funcptr_glGetProgramiv) ++numFailed;
	_funcptr_glGetShaderInfoLog = (PFNGLGETSHADERINFOLOGPROC)IntGetProcAddress("glGetShaderInfoLog");
	if(!_funcptr_glGetShaderInfoLog) ++numFailed;
	_funcptr_glGetShaderSource = (PFNGLGETSHADERSOURCEPROC)IntGetProcAddress("glGetShaderSource");
	if(!_funcptr_glGetShaderSource) ++numFailed;
	_funcptr_glGetShaderiv = (PFNGLGETSHADERIVPROC)IntGetProcAddress("glGetShaderiv");
	if(!_funcptr_glGetShaderiv) ++numFailed;
	_funcptr_glGetUniformLocation = (PFNGLGETUNIFORMLOCATIONPROC)IntGetProcAddress("glGetUniformLocation");
	if(!_funcptr_glGetUniformLocation) ++numFailed;
	_funcptr_glGetUniformfv = (PFNGLGETUNIFORMFVPROC)IntGetProcAddress("glGetUniformfv");
	if(!_funcptr_glGetUniformfv) ++numFailed;
	_funcptr_glGetUniformiv = (PFNGLGETUNIFORMIVPROC)IntGetProcAddress("glGetUniformiv");
	if(!_funcptr_glGetUniformiv) ++numFailed;
	_funcptr_glGetVertexAttribPointerv = (PFNGLGETVERTEXATTRIBPOINTERVPROC)IntGetProcAddress("glGetVertexAttribPointerv");
	if(!_funcptr_glGetVertexAttribPointerv) ++numFailed;
	_funcptr_glGetVertexAttribdv = (PFNGLGETVERTEXATTRIBDVPROC)IntGetProcAddress("glGetVertexAttribdv");
	if(!_funcptr_glGetVertexAttribdv) ++numFailed;
	_funcptr_glGetVertexAttribfv = (PFNGLGETVERTEXATTRIBFVPROC)IntGetProcAddress("glGetVertexAttribfv");
	if(!_funcptr_glGetVertexAttribfv) ++numFailed;
	_funcptr_glGetVertexAttribiv = (PFNGLGETVERTEXATTRIBIVPROC)IntGetProcAddress("glGetVertexAttribiv");
	if(!_funcptr_glGetVertexAttribiv) ++numFailed;
	_funcptr_glIsProgram = (PFNGLISPROGRAMPROC)IntGetProcAddress("glIsProgram");
	if(!_funcptr_glIsProgram) ++numFailed;
	_funcptr_glIsShader = (PFNGLISSHADERPROC)IntGetProcAddress("glIsShader");
	if(!_funcptr_glIsShader) ++numFailed;
	_funcptr_glLinkProgram = (PFNGLLINKPROGRAMPROC)IntGetProcAddress("glLinkProgram");
	if(!_funcptr_glLinkProgram) ++numFailed;
	_funcptr_glShaderSource = (PFNGLSHADERSOURCEPROC)IntGetProcAddress("glShaderSource");
	if(!_funcptr_glShaderSource) ++numFailed;
	_funcptr_glStencilFuncSeparate = (PFNGLSTENCILFUNCSEPARATEPROC)IntGetProcAddress("glStencilFuncSeparate");
	if(!_funcptr_glStencilFuncSeparate) ++numFailed;
	_funcptr_glStencilMaskSeparate = (PFNGLSTENCILMASKSEPARATEPROC)IntGetProcAddress("glStencilMaskSeparate");
	if(!_funcptr_glStencilMaskSeparate) ++numFailed;
	_funcptr_glStencilOpSeparate = (PFNGLSTENCILOPSEPARATEPROC)IntGetProcAddress("glStencilOpSeparate");
	if(!_funcptr_glStencilOpSeparate) ++numFailed;
	_funcptr_glUniform1f = (PFNGLUNIFORM1FPROC)IntGetProcAddress("glUniform1f");
	if(!_funcptr_glUniform1f) ++numFailed;
	_funcptr_glUniform1fv = (PFNGLUNIFORM1FVPROC)IntGetProcAddress("glUniform1fv");
	if(!_funcptr_glUniform1fv) ++numFailed;
	_funcptr_glUniform1i = (PFNGLUNIFORM1IPROC)IntGetProcAddress("glUniform1i");
	if(!_funcptr_glUniform1i) ++numFailed;
	_funcptr_glUniform1iv = (PFNGLUNIFORM1IVPROC)IntGetProcAddress("glUniform1iv");
	if(!_funcptr_glUniform1iv) ++numFailed;
	_funcptr_glUniform2f = (PFNGLUNIFORM2FPROC)IntGetProcAddress("glUniform2f");
	if(!_funcptr_glUniform2f) ++numFailed;
	_funcptr_glUniform2fv = (PFNGLUNIFORM2FVPROC)IntGetProcAddress("glUniform2fv");
	if(!_funcptr_glUniform2fv) ++numFailed;
	_funcptr_glUniform2i = (PFNGLUNIFORM2IPROC)IntGetProcAddress("glUniform2i");
	if(!_funcptr_glUniform2i) ++numFailed;
	_funcptr_glUniform2iv = (PFNGLUNIFORM2IVPROC)IntGetProcAddress("glUniform2iv");
	if(!_funcptr_glUniform2iv) ++numFailed;
	_funcptr_glUniform3f = (PFNGLUNIFORM3FPROC)IntGetProcAddress("glUniform3f");
	if(!_funcptr_glUniform3f) ++numFailed;
	_funcptr_glUniform3fv = (PFNGLUNIFORM3FVPROC)IntGetProcAddress("glUniform3fv");
	if(!_funcptr_glUniform3fv) ++numFailed;
	_funcptr_glUniform3i = (PFNGLUNIFORM3IPROC)IntGetProcAddress("glUniform3i");
	if(!_funcptr_glUniform3i) ++numFailed;
	_funcptr_glUniform3iv = (PFNGLUNIFORM3IVPROC)IntGetProcAddress("glUniform3iv");
	if(!_funcptr_glUniform3iv) ++numFailed;
	_funcptr_glUniform4f = (PFNGLUNIFORM4FPROC)IntGetProcAddress("glUniform4f");
	if(!_funcptr_glUniform4f) ++numFailed;
	_funcptr_glUniform4fv = (PFNGLUNIFORM4FVPROC)IntGetProcAddress("glUniform4fv");
	if(!_funcptr_glUniform4fv) ++numFailed;
	_funcptr_glUniform4i = (PFNGLUNIFORM4IPROC)IntGetProcAddress("glUniform4i");
	if(!_funcptr_glUniform4i) ++numFailed;
	_funcptr_glUniform4iv = (PFNGLUNIFORM4IVPROC)IntGetProcAddress("glUniform4iv");
	if(!_funcptr_glUniform4iv) ++numFailed;
	_funcptr_glUniformMatrix2fv = (PFNGLUNIFORMMATRIX2FVPROC)IntGetProcAddress("glUniformMatrix2fv");
	if(!_funcptr_glUniformMatrix2fv) ++numFailed;
	_funcptr_glUniformMatrix3fv = (PFNGLUNIFORMMATRIX3FVPROC)IntGetProcAddress("glUniformMatrix3fv");
	if(!_funcptr_glUniformMatrix3fv) ++numFailed;
	_funcptr_glUniformMatrix4fv = (PFNGLUNIFORMMATRIX4FVPROC)IntGetProcAddress("glUniformMatrix4fv");
	if(!_funcptr_glUniformMatrix4fv) ++numFailed;
	_funcptr_glUseProgram = (PFNGLUSEPROGRAMPROC)IntGetProcAddress("glUseProgram");
	if(!_funcptr_glUseProgram) ++numFailed;
	_funcptr_glValidateProgram = (PFNGLVALIDATEPROGRAMPROC)IntGetProcAddress("glValidateProgram");
	if(!_funcptr_glValidateProgram) ++numFailed;
	_funcptr_glVertexAttrib1d = (PFNGLVERTEXATTRIB1DPROC)IntGetProcAddress("glVertexAttrib1d");
	if(!_funcptr_glVertexAttrib1d) ++numFailed;
	_funcptr_glVertexAttrib1dv = (PFNGLVERTEXATTRIB1DVPROC)IntGetProcAddress("glVertexAttrib1dv");
	if(!_funcptr_glVertexAttrib1dv) ++numFailed;
	_funcptr_glVertexAttrib1f = (PFNGLVERTEXATTRIB1FPROC)IntGetProcAddress("glVertexAttrib1f");
	if(!_funcptr_glVertexAttrib1f) ++numFailed;
	_funcptr_glVertexAttrib1fv = (PFNGLVERTEXATTRIB1FVPROC)IntGetProcAddress("glVertexAttrib1fv");
	if(!_funcptr_glVertexAttrib1fv) ++numFailed;
	_funcptr_glVertexAttrib1s = (PFNGLVERTEXATTRIB1SPROC)IntGetProcAddress("glVertexAttrib1s");
	if(!_funcptr_glVertexAttrib1s) ++numFailed;
	_funcptr_glVertexAttrib1sv = (PFNGLVERTEXATTRIB1SVPROC)IntGetProcAddress("glVertexAttrib1sv");
	if(!_funcptr_glVertexAttrib1sv) ++numFailed;
	_funcptr_glVertexAttrib2d = (PFNGLVERTEXATTRIB2DPROC)IntGetProcAddress("glVertexAttrib2d");
	if(!_funcptr_glVertexAttrib2d) ++numFailed;
	_funcptr_glVertexAttrib2dv = (PFNGLVERTEXATTRIB2DVPROC)IntGetProcAddress("glVertexAttrib2dv");
	if(!_funcptr_glVertexAttrib2dv) ++numFailed;
	_funcptr_glVertexAttrib2f = (PFNGLVERTEXATTRIB2FPROC)IntGetProcAddress("glVertexAttrib2f");
	if(!_funcptr_glVertexAttrib2f) ++numFailed;
	_funcptr_glVertexAttrib2fv = (PFNGLVERTEXATTRIB2FVPROC)IntGetProcAddress("glVertexAttrib2fv");
	if(!_funcptr_glVertexAttrib2fv) ++numFailed;
	_funcptr_glVertexAttrib2s = (PFNGLVERTEXATTRIB2SPROC)IntGetProcAddress("glVertexAttrib2s");
	if(!_funcptr_glVertexAttrib2s) ++numFailed;
	_funcptr_glVertexAttrib2sv = (PFNGLVERTEXATTRIB2SVPROC)IntGetProcAddress("glVertexAttrib2sv");
	if(!_funcptr_glVertexAttrib2sv) ++numFailed;
	_funcptr_glVertexAttrib3d = (PFNGLVERTEXATTRIB3DPROC)IntGetProcAddress("glVertexAttrib3d");
	if(!_funcptr_glVertexAttrib3d) ++numFailed;
	_funcptr_glVertexAttrib3dv = (PFNGLVERTEXATTRIB3DVPROC)IntGetProcAddress("glVertexAttrib3dv");
	if(!_funcptr_glVertexAttrib3dv) ++numFailed;
	_funcptr_glVertexAttrib3f = (PFNGLVERTEXATTRIB3FPROC)IntGetProcAddress("glVertexAttrib3f");
	if(!_funcptr_glVertexAttrib3f) ++numFailed;
	_funcptr_glVertexAttrib3fv = (PFNGLVERTEXATTRIB3FVPROC)IntGetProcAddress("glVertexAttrib3fv");
	if(!_funcptr_glVertexAttrib3fv) ++numFailed;
	_funcptr_glVertexAttrib3s = (PFNGLVERTEXATTRIB3SPROC)IntGetProcAddress("glVertexAttrib3s");
	if(!_funcptr_glVertexAttrib3s) ++numFailed;
	_funcptr_glVertexAttrib3sv = (PFNGLVERTEXATTRIB3SVPROC)IntGetProcAddress("glVertexAttrib3sv");
	if(!_funcptr_glVertexAttrib3sv) ++numFailed;
	_funcptr_glVertexAttrib4Nbv = (PFNGLVERTEXATTRIB4NBVPROC)IntGetProcAddress("glVertexAttrib4Nbv");
	if(!_funcptr_glVertexAttrib4Nbv) ++numFailed;
	_funcptr_glVertexAttrib4Niv = (PFNGLVERTEXATTRIB4NIVPROC)IntGetProcAddress("glVertexAttrib4Niv");
	if(!_funcptr_glVertexAttrib4Niv) ++numFailed;
	_funcptr_glVertexAttrib4Nsv = (PFNGLVERTEXATTRIB4NSVPROC)IntGetProcAddress("glVertexAttrib4Nsv");
	if(!_funcptr_glVertexAttrib4Nsv) ++numFailed;
	_funcptr_glVertexAttrib4Nub = (PFNGLVERTEXATTRIB4NUBPROC)IntGetProcAddress("glVertexAttrib4Nub");
	if(!_funcptr_glVertexAttrib4Nub) ++numFailed;
	_funcptr_glVertexAttrib4Nubv = (PFNGLVERTEXATTRIB4NUBVPROC)IntGetProcAddress("glVertexAttrib4Nubv");
	if(!_funcptr_glVertexAttrib4Nubv) ++numFailed;
	_funcptr_glVertexAttrib4Nuiv = (PFNGLVERTEXATTRIB4NUIVPROC)IntGetProcAddress("glVertexAttrib4Nuiv");
	if(!_funcptr_glVertexAttrib4Nuiv) ++numFailed;
	_funcptr_glVertexAttrib4Nusv = (PFNGLVERTEXATTRIB4NUSVPROC)IntGetProcAddress("glVertexAttrib4Nusv");
	if(!_funcptr_glVertexAttrib4Nusv) ++numFailed;
	_funcptr_glVertexAttrib4bv = (PFNGLVERTEXATTRIB4BVPROC)IntGetProcAddress("glVertexAttrib4bv");
	if(!_funcptr_glVertexAttrib4bv) ++numFailed;
	_funcptr_glVertexAttrib4d = (PFNGLVERTEXATTRIB4DPROC)IntGetProcAddress("glVertexAttrib4d");
	if(!_funcptr_glVertexAttrib4d) ++numFailed;
	_funcptr_glVertexAttrib4dv = (PFNGLVERTEXATTRIB4DVPROC)IntGetProcAddress("glVertexAttrib4dv");
	if(!_funcptr_glVertexAttrib4dv) ++numFailed;
	_funcptr_glVertexAttrib4f = (PFNGLVERTEXATTRIB4FPROC)IntGetProcAddress("glVertexAttrib4f");
	if(!_funcptr_glVertexAttrib4f) ++numFailed;
	_funcptr_glVertexAttrib4fv = (PFNGLVERTEXATTRIB4FVPROC)IntGetProcAddress("glVertexAttrib4fv");
	if(!_funcptr_glVertexAttrib4fv) ++numFailed;
	_funcptr_glVertexAttrib4iv = (PFNGLVERTEXATTRIB4IVPROC)IntGetProcAddress("glVertexAttrib4iv");
	if(!_funcptr_glVertexAttrib4iv) ++numFailed;
	_funcptr_glVertexAttrib4s = (PFNGLVERTEXATTRIB4SPROC)IntGetProcAddress("glVertexAttrib4s");
	if(!_funcptr_glVertexAttrib4s) ++numFailed;
	_funcptr_glVertexAttrib4sv = (PFNGLVERTEXATTRIB4SVPROC)IntGetProcAddress("glVertexAttrib4sv");
	if(!_funcptr_glVertexAttrib4sv) ++numFailed;
	_funcptr_glVertexAttrib4ubv = (PFNGLVERTEXATTRIB4UBVPROC)IntGetProcAddress("glVertexAttrib4ubv");
	if(!_funcptr_glVertexAttrib4ubv) ++numFailed;
	_funcptr_glVertexAttrib4uiv = (PFNGLVERTEXATTRIB4UIVPROC)IntGetProcAddress("glVertexAttrib4uiv");
	if(!_funcptr_glVertexAttrib4uiv) ++numFailed;
	_funcptr_glVertexAttrib4usv = (PFNGLVERTEXATTRIB4USVPROC)IntGetProcAddress("glVertexAttrib4usv");
	if(!_funcptr_glVertexAttrib4usv) ++numFailed;
	_funcptr_glVertexAttribPointer = (PFNGLVERTEXATTRIBPOINTERPROC)IntGetProcAddress("glVertexAttribPointer");
	if(!_funcptr_glVertexAttribPointer) ++numFailed;
	return numFailed;
}