#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  scalar_t__ PFNGLWRITEMASKEXTPROC ;
typedef  scalar_t__ PFNGLVARIANTUSVEXTPROC ;
typedef  scalar_t__ PFNGLVARIANTUIVEXTPROC ;
typedef  scalar_t__ PFNGLVARIANTUBVEXTPROC ;
typedef  scalar_t__ PFNGLVARIANTSVEXTPROC ;
typedef  scalar_t__ PFNGLVARIANTPOINTEREXTPROC ;
typedef  scalar_t__ PFNGLVARIANTIVEXTPROC ;
typedef  scalar_t__ PFNGLVARIANTFVEXTPROC ;
typedef  scalar_t__ PFNGLVARIANTDVEXTPROC ;
typedef  scalar_t__ PFNGLVARIANTBVEXTPROC ;
typedef  scalar_t__ PFNGLSWIZZLEEXTPROC ;
typedef  scalar_t__ PFNGLSHADEROP3EXTPROC ;
typedef  scalar_t__ PFNGLSHADEROP2EXTPROC ;
typedef  scalar_t__ PFNGLSHADEROP1EXTPROC ;
typedef  scalar_t__ PFNGLSETLOCALCONSTANTEXTPROC ;
typedef  scalar_t__ PFNGLSETINVARIANTEXTPROC ;
typedef  scalar_t__ PFNGLISVARIANTENABLEDEXTPROC ;
typedef  scalar_t__ PFNGLINSERTCOMPONENTEXTPROC ;
typedef  scalar_t__ PFNGLGETVARIANTPOINTERVEXTPROC ;
typedef  scalar_t__ PFNGLGETVARIANTINTEGERVEXTPROC ;
typedef  scalar_t__ PFNGLGETVARIANTFLOATVEXTPROC ;
typedef  scalar_t__ PFNGLGETVARIANTBOOLEANVEXTPROC ;
typedef  scalar_t__ PFNGLGETLOCALCONSTANTINTEGERVEXTPROC ;
typedef  scalar_t__ PFNGLGETLOCALCONSTANTFLOATVEXTPROC ;
typedef  scalar_t__ PFNGLGETLOCALCONSTANTBOOLEANVEXTPROC ;
typedef  scalar_t__ PFNGLGETINVARIANTINTEGERVEXTPROC ;
typedef  scalar_t__ PFNGLGETINVARIANTFLOATVEXTPROC ;
typedef  scalar_t__ PFNGLGETINVARIANTBOOLEANVEXTPROC ;
typedef  scalar_t__ PFNGLGENVERTEXSHADERSEXTPROC ;
typedef  scalar_t__ PFNGLGENSYMBOLSEXTPROC ;
typedef  scalar_t__ PFNGLEXTRACTCOMPONENTEXTPROC ;
typedef  scalar_t__ PFNGLENDVERTEXSHADEREXTPROC ;
typedef  scalar_t__ PFNGLENABLEVARIANTCLIENTSTATEEXTPROC ;
typedef  scalar_t__ PFNGLDISABLEVARIANTCLIENTSTATEEXTPROC ;
typedef  scalar_t__ PFNGLDELETEVERTEXSHADEREXTPROC ;
typedef  scalar_t__ PFNGLBINDVERTEXSHADEREXTPROC ;
typedef  scalar_t__ PFNGLBINDTEXTUREUNITPARAMETEREXTPROC ;
typedef  scalar_t__ PFNGLBINDTEXGENPARAMETEREXTPROC ;
typedef  scalar_t__ PFNGLBINDPARAMETEREXTPROC ;
typedef  scalar_t__ PFNGLBINDMATERIALPARAMETEREXTPROC ;
typedef  scalar_t__ PFNGLBINDLIGHTPARAMETEREXTPROC ;
typedef  scalar_t__ PFNGLBEGINVERTEXSHADEREXTPROC ;

/* Variables and functions */
 scalar_t__ IntGetProcAddress (char*) ; 
 scalar_t__ _funcptr_glBeginVertexShaderEXT ; 
 scalar_t__ _funcptr_glBindLightParameterEXT ; 
 scalar_t__ _funcptr_glBindMaterialParameterEXT ; 
 scalar_t__ _funcptr_glBindParameterEXT ; 
 scalar_t__ _funcptr_glBindTexGenParameterEXT ; 
 scalar_t__ _funcptr_glBindTextureUnitParameterEXT ; 
 scalar_t__ _funcptr_glBindVertexShaderEXT ; 
 scalar_t__ _funcptr_glDeleteVertexShaderEXT ; 
 scalar_t__ _funcptr_glDisableVariantClientStateEXT ; 
 scalar_t__ _funcptr_glEnableVariantClientStateEXT ; 
 scalar_t__ _funcptr_glEndVertexShaderEXT ; 
 scalar_t__ _funcptr_glExtractComponentEXT ; 
 scalar_t__ _funcptr_glGenSymbolsEXT ; 
 scalar_t__ _funcptr_glGenVertexShadersEXT ; 
 scalar_t__ _funcptr_glGetInvariantBooleanvEXT ; 
 scalar_t__ _funcptr_glGetInvariantFloatvEXT ; 
 scalar_t__ _funcptr_glGetInvariantIntegervEXT ; 
 scalar_t__ _funcptr_glGetLocalConstantBooleanvEXT ; 
 scalar_t__ _funcptr_glGetLocalConstantFloatvEXT ; 
 scalar_t__ _funcptr_glGetLocalConstantIntegervEXT ; 
 scalar_t__ _funcptr_glGetVariantBooleanvEXT ; 
 scalar_t__ _funcptr_glGetVariantFloatvEXT ; 
 scalar_t__ _funcptr_glGetVariantIntegervEXT ; 
 scalar_t__ _funcptr_glGetVariantPointervEXT ; 
 scalar_t__ _funcptr_glInsertComponentEXT ; 
 scalar_t__ _funcptr_glIsVariantEnabledEXT ; 
 scalar_t__ _funcptr_glSetInvariantEXT ; 
 scalar_t__ _funcptr_glSetLocalConstantEXT ; 
 scalar_t__ _funcptr_glShaderOp1EXT ; 
 scalar_t__ _funcptr_glShaderOp2EXT ; 
 scalar_t__ _funcptr_glShaderOp3EXT ; 
 scalar_t__ _funcptr_glSwizzleEXT ; 
 scalar_t__ _funcptr_glVariantPointerEXT ; 
 scalar_t__ _funcptr_glVariantbvEXT ; 
 scalar_t__ _funcptr_glVariantdvEXT ; 
 scalar_t__ _funcptr_glVariantfvEXT ; 
 scalar_t__ _funcptr_glVariantivEXT ; 
 scalar_t__ _funcptr_glVariantsvEXT ; 
 scalar_t__ _funcptr_glVariantubvEXT ; 
 scalar_t__ _funcptr_glVariantuivEXT ; 
 scalar_t__ _funcptr_glVariantusvEXT ; 
 scalar_t__ _funcptr_glWriteMaskEXT ; 

__attribute__((used)) static int LoadExt_EXT_vertex_shader()
{
	int numFailed = 0;
	_funcptr_glBeginVertexShaderEXT = (PFNGLBEGINVERTEXSHADEREXTPROC)IntGetProcAddress("glBeginVertexShaderEXT");
	if(!_funcptr_glBeginVertexShaderEXT) ++numFailed;
	_funcptr_glBindLightParameterEXT = (PFNGLBINDLIGHTPARAMETEREXTPROC)IntGetProcAddress("glBindLightParameterEXT");
	if(!_funcptr_glBindLightParameterEXT) ++numFailed;
	_funcptr_glBindMaterialParameterEXT = (PFNGLBINDMATERIALPARAMETEREXTPROC)IntGetProcAddress("glBindMaterialParameterEXT");
	if(!_funcptr_glBindMaterialParameterEXT) ++numFailed;
	_funcptr_glBindParameterEXT = (PFNGLBINDPARAMETEREXTPROC)IntGetProcAddress("glBindParameterEXT");
	if(!_funcptr_glBindParameterEXT) ++numFailed;
	_funcptr_glBindTexGenParameterEXT = (PFNGLBINDTEXGENPARAMETEREXTPROC)IntGetProcAddress("glBindTexGenParameterEXT");
	if(!_funcptr_glBindTexGenParameterEXT) ++numFailed;
	_funcptr_glBindTextureUnitParameterEXT = (PFNGLBINDTEXTUREUNITPARAMETEREXTPROC)IntGetProcAddress("glBindTextureUnitParameterEXT");
	if(!_funcptr_glBindTextureUnitParameterEXT) ++numFailed;
	_funcptr_glBindVertexShaderEXT = (PFNGLBINDVERTEXSHADEREXTPROC)IntGetProcAddress("glBindVertexShaderEXT");
	if(!_funcptr_glBindVertexShaderEXT) ++numFailed;
	_funcptr_glDeleteVertexShaderEXT = (PFNGLDELETEVERTEXSHADEREXTPROC)IntGetProcAddress("glDeleteVertexShaderEXT");
	if(!_funcptr_glDeleteVertexShaderEXT) ++numFailed;
	_funcptr_glDisableVariantClientStateEXT = (PFNGLDISABLEVARIANTCLIENTSTATEEXTPROC)IntGetProcAddress("glDisableVariantClientStateEXT");
	if(!_funcptr_glDisableVariantClientStateEXT) ++numFailed;
	_funcptr_glEnableVariantClientStateEXT = (PFNGLENABLEVARIANTCLIENTSTATEEXTPROC)IntGetProcAddress("glEnableVariantClientStateEXT");
	if(!_funcptr_glEnableVariantClientStateEXT) ++numFailed;
	_funcptr_glEndVertexShaderEXT = (PFNGLENDVERTEXSHADEREXTPROC)IntGetProcAddress("glEndVertexShaderEXT");
	if(!_funcptr_glEndVertexShaderEXT) ++numFailed;
	_funcptr_glExtractComponentEXT = (PFNGLEXTRACTCOMPONENTEXTPROC)IntGetProcAddress("glExtractComponentEXT");
	if(!_funcptr_glExtractComponentEXT) ++numFailed;
	_funcptr_glGenSymbolsEXT = (PFNGLGENSYMBOLSEXTPROC)IntGetProcAddress("glGenSymbolsEXT");
	if(!_funcptr_glGenSymbolsEXT) ++numFailed;
	_funcptr_glGenVertexShadersEXT = (PFNGLGENVERTEXSHADERSEXTPROC)IntGetProcAddress("glGenVertexShadersEXT");
	if(!_funcptr_glGenVertexShadersEXT) ++numFailed;
	_funcptr_glGetInvariantBooleanvEXT = (PFNGLGETINVARIANTBOOLEANVEXTPROC)IntGetProcAddress("glGetInvariantBooleanvEXT");
	if(!_funcptr_glGetInvariantBooleanvEXT) ++numFailed;
	_funcptr_glGetInvariantFloatvEXT = (PFNGLGETINVARIANTFLOATVEXTPROC)IntGetProcAddress("glGetInvariantFloatvEXT");
	if(!_funcptr_glGetInvariantFloatvEXT) ++numFailed;
	_funcptr_glGetInvariantIntegervEXT = (PFNGLGETINVARIANTINTEGERVEXTPROC)IntGetProcAddress("glGetInvariantIntegervEXT");
	if(!_funcptr_glGetInvariantIntegervEXT) ++numFailed;
	_funcptr_glGetLocalConstantBooleanvEXT = (PFNGLGETLOCALCONSTANTBOOLEANVEXTPROC)IntGetProcAddress("glGetLocalConstantBooleanvEXT");
	if(!_funcptr_glGetLocalConstantBooleanvEXT) ++numFailed;
	_funcptr_glGetLocalConstantFloatvEXT = (PFNGLGETLOCALCONSTANTFLOATVEXTPROC)IntGetProcAddress("glGetLocalConstantFloatvEXT");
	if(!_funcptr_glGetLocalConstantFloatvEXT) ++numFailed;
	_funcptr_glGetLocalConstantIntegervEXT = (PFNGLGETLOCALCONSTANTINTEGERVEXTPROC)IntGetProcAddress("glGetLocalConstantIntegervEXT");
	if(!_funcptr_glGetLocalConstantIntegervEXT) ++numFailed;
	_funcptr_glGetVariantBooleanvEXT = (PFNGLGETVARIANTBOOLEANVEXTPROC)IntGetProcAddress("glGetVariantBooleanvEXT");
	if(!_funcptr_glGetVariantBooleanvEXT) ++numFailed;
	_funcptr_glGetVariantFloatvEXT = (PFNGLGETVARIANTFLOATVEXTPROC)IntGetProcAddress("glGetVariantFloatvEXT");
	if(!_funcptr_glGetVariantFloatvEXT) ++numFailed;
	_funcptr_glGetVariantIntegervEXT = (PFNGLGETVARIANTINTEGERVEXTPROC)IntGetProcAddress("glGetVariantIntegervEXT");
	if(!_funcptr_glGetVariantIntegervEXT) ++numFailed;
	_funcptr_glGetVariantPointervEXT = (PFNGLGETVARIANTPOINTERVEXTPROC)IntGetProcAddress("glGetVariantPointervEXT");
	if(!_funcptr_glGetVariantPointervEXT) ++numFailed;
	_funcptr_glInsertComponentEXT = (PFNGLINSERTCOMPONENTEXTPROC)IntGetProcAddress("glInsertComponentEXT");
	if(!_funcptr_glInsertComponentEXT) ++numFailed;
	_funcptr_glIsVariantEnabledEXT = (PFNGLISVARIANTENABLEDEXTPROC)IntGetProcAddress("glIsVariantEnabledEXT");
	if(!_funcptr_glIsVariantEnabledEXT) ++numFailed;
	_funcptr_glSetInvariantEXT = (PFNGLSETINVARIANTEXTPROC)IntGetProcAddress("glSetInvariantEXT");
	if(!_funcptr_glSetInvariantEXT) ++numFailed;
	_funcptr_glSetLocalConstantEXT = (PFNGLSETLOCALCONSTANTEXTPROC)IntGetProcAddress("glSetLocalConstantEXT");
	if(!_funcptr_glSetLocalConstantEXT) ++numFailed;
	_funcptr_glShaderOp1EXT = (PFNGLSHADEROP1EXTPROC)IntGetProcAddress("glShaderOp1EXT");
	if(!_funcptr_glShaderOp1EXT) ++numFailed;
	_funcptr_glShaderOp2EXT = (PFNGLSHADEROP2EXTPROC)IntGetProcAddress("glShaderOp2EXT");
	if(!_funcptr_glShaderOp2EXT) ++numFailed;
	_funcptr_glShaderOp3EXT = (PFNGLSHADEROP3EXTPROC)IntGetProcAddress("glShaderOp3EXT");
	if(!_funcptr_glShaderOp3EXT) ++numFailed;
	_funcptr_glSwizzleEXT = (PFNGLSWIZZLEEXTPROC)IntGetProcAddress("glSwizzleEXT");
	if(!_funcptr_glSwizzleEXT) ++numFailed;
	_funcptr_glVariantPointerEXT = (PFNGLVARIANTPOINTEREXTPROC)IntGetProcAddress("glVariantPointerEXT");
	if(!_funcptr_glVariantPointerEXT) ++numFailed;
	_funcptr_glVariantbvEXT = (PFNGLVARIANTBVEXTPROC)IntGetProcAddress("glVariantbvEXT");
	if(!_funcptr_glVariantbvEXT) ++numFailed;
	_funcptr_glVariantdvEXT = (PFNGLVARIANTDVEXTPROC)IntGetProcAddress("glVariantdvEXT");
	if(!_funcptr_glVariantdvEXT) ++numFailed;
	_funcptr_glVariantfvEXT = (PFNGLVARIANTFVEXTPROC)IntGetProcAddress("glVariantfvEXT");
	if(!_funcptr_glVariantfvEXT) ++numFailed;
	_funcptr_glVariantivEXT = (PFNGLVARIANTIVEXTPROC)IntGetProcAddress("glVariantivEXT");
	if(!_funcptr_glVariantivEXT) ++numFailed;
	_funcptr_glVariantsvEXT = (PFNGLVARIANTSVEXTPROC)IntGetProcAddress("glVariantsvEXT");
	if(!_funcptr_glVariantsvEXT) ++numFailed;
	_funcptr_glVariantubvEXT = (PFNGLVARIANTUBVEXTPROC)IntGetProcAddress("glVariantubvEXT");
	if(!_funcptr_glVariantubvEXT) ++numFailed;
	_funcptr_glVariantuivEXT = (PFNGLVARIANTUIVEXTPROC)IntGetProcAddress("glVariantuivEXT");
	if(!_funcptr_glVariantuivEXT) ++numFailed;
	_funcptr_glVariantusvEXT = (PFNGLVARIANTUSVEXTPROC)IntGetProcAddress("glVariantusvEXT");
	if(!_funcptr_glVariantusvEXT) ++numFailed;
	_funcptr_glWriteMaskEXT = (PFNGLWRITEMASKEXTPROC)IntGetProcAddress("glWriteMaskEXT");
	if(!_funcptr_glWriteMaskEXT) ++numFailed;
	return numFailed;
}