#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  scalar_t__ PFNGLVALIDATEPROGRAMPIPELINEPROC ;
typedef  scalar_t__ PFNGLUSEPROGRAMSTAGESPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX4X3DVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX4X2DVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX4FVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX4DVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX3X4DVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX3FVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX3DVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX2X4DVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX2FVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORMMATRIX2DVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM4UIVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM4UIPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM4IVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM4IPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM4FVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM4FPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM4DVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM4DPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM3UIVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM3UIPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM3IVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM3IPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM3FVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM3FPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM3DVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM3DPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM2UIVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM2UIPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM2IVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM2IPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM2FVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM2FPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM2DVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM2DPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM1UIVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM1UIPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM1IVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM1IPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM1FVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM1FPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM1DVPROC ;
typedef  scalar_t__ PFNGLPROGRAMUNIFORM1DPROC ;
typedef  scalar_t__ PFNGLISPROGRAMPIPELINEPROC ;
typedef  scalar_t__ PFNGLGETPROGRAMPIPELINEIVPROC ;
typedef  scalar_t__ PFNGLGETPROGRAMPIPELINEINFOLOGPROC ;
typedef  scalar_t__ PFNGLGENPROGRAMPIPELINESPROC ;
typedef  scalar_t__ PFNGLDELETEPROGRAMPIPELINESPROC ;
typedef  scalar_t__ PFNGLCREATESHADERPROGRAMVPROC ;
typedef  scalar_t__ PFNGLBINDPROGRAMPIPELINEPROC ;
typedef  scalar_t__ PFNGLACTIVESHADERPROGRAMPROC ;

/* Variables and functions */
 scalar_t__ IntGetProcAddress (char*) ; 
 scalar_t__ _funcptr_glActiveShaderProgram ; 
 scalar_t__ _funcptr_glBindProgramPipeline ; 
 scalar_t__ _funcptr_glCreateShaderProgramv ; 
 scalar_t__ _funcptr_glDeleteProgramPipelines ; 
 scalar_t__ _funcptr_glGenProgramPipelines ; 
 scalar_t__ _funcptr_glGetProgramPipelineInfoLog ; 
 scalar_t__ _funcptr_glGetProgramPipelineiv ; 
 scalar_t__ _funcptr_glIsProgramPipeline ; 
 scalar_t__ _funcptr_glProgramUniform1d ; 
 scalar_t__ _funcptr_glProgramUniform1dv ; 
 scalar_t__ _funcptr_glProgramUniform1f ; 
 scalar_t__ _funcptr_glProgramUniform1fv ; 
 scalar_t__ _funcptr_glProgramUniform1i ; 
 scalar_t__ _funcptr_glProgramUniform1iv ; 
 scalar_t__ _funcptr_glProgramUniform1ui ; 
 scalar_t__ _funcptr_glProgramUniform1uiv ; 
 scalar_t__ _funcptr_glProgramUniform2d ; 
 scalar_t__ _funcptr_glProgramUniform2dv ; 
 scalar_t__ _funcptr_glProgramUniform2f ; 
 scalar_t__ _funcptr_glProgramUniform2fv ; 
 scalar_t__ _funcptr_glProgramUniform2i ; 
 scalar_t__ _funcptr_glProgramUniform2iv ; 
 scalar_t__ _funcptr_glProgramUniform2ui ; 
 scalar_t__ _funcptr_glProgramUniform2uiv ; 
 scalar_t__ _funcptr_glProgramUniform3d ; 
 scalar_t__ _funcptr_glProgramUniform3dv ; 
 scalar_t__ _funcptr_glProgramUniform3f ; 
 scalar_t__ _funcptr_glProgramUniform3fv ; 
 scalar_t__ _funcptr_glProgramUniform3i ; 
 scalar_t__ _funcptr_glProgramUniform3iv ; 
 scalar_t__ _funcptr_glProgramUniform3ui ; 
 scalar_t__ _funcptr_glProgramUniform3uiv ; 
 scalar_t__ _funcptr_glProgramUniform4d ; 
 scalar_t__ _funcptr_glProgramUniform4dv ; 
 scalar_t__ _funcptr_glProgramUniform4f ; 
 scalar_t__ _funcptr_glProgramUniform4fv ; 
 scalar_t__ _funcptr_glProgramUniform4i ; 
 scalar_t__ _funcptr_glProgramUniform4iv ; 
 scalar_t__ _funcptr_glProgramUniform4ui ; 
 scalar_t__ _funcptr_glProgramUniform4uiv ; 
 scalar_t__ _funcptr_glProgramUniformMatrix2dv ; 
 scalar_t__ _funcptr_glProgramUniformMatrix2fv ; 
 scalar_t__ _funcptr_glProgramUniformMatrix2x3dv ; 
 scalar_t__ _funcptr_glProgramUniformMatrix2x3fv ; 
 scalar_t__ _funcptr_glProgramUniformMatrix2x4dv ; 
 scalar_t__ _funcptr_glProgramUniformMatrix2x4fv ; 
 scalar_t__ _funcptr_glProgramUniformMatrix3dv ; 
 scalar_t__ _funcptr_glProgramUniformMatrix3fv ; 
 scalar_t__ _funcptr_glProgramUniformMatrix3x2dv ; 
 scalar_t__ _funcptr_glProgramUniformMatrix3x2fv ; 
 scalar_t__ _funcptr_glProgramUniformMatrix3x4dv ; 
 scalar_t__ _funcptr_glProgramUniformMatrix3x4fv ; 
 scalar_t__ _funcptr_glProgramUniformMatrix4dv ; 
 scalar_t__ _funcptr_glProgramUniformMatrix4fv ; 
 scalar_t__ _funcptr_glProgramUniformMatrix4x2dv ; 
 scalar_t__ _funcptr_glProgramUniformMatrix4x2fv ; 
 scalar_t__ _funcptr_glProgramUniformMatrix4x3dv ; 
 scalar_t__ _funcptr_glProgramUniformMatrix4x3fv ; 
 scalar_t__ _funcptr_glUseProgramStages ; 
 scalar_t__ _funcptr_glValidateProgramPipeline ; 

__attribute__((used)) static int LoadExt_ARB_separate_shader_objects()
{
	int numFailed = 0;
	_funcptr_glActiveShaderProgram = (PFNGLACTIVESHADERPROGRAMPROC)IntGetProcAddress("glActiveShaderProgram");
	if(!_funcptr_glActiveShaderProgram) ++numFailed;
	_funcptr_glBindProgramPipeline = (PFNGLBINDPROGRAMPIPELINEPROC)IntGetProcAddress("glBindProgramPipeline");
	if(!_funcptr_glBindProgramPipeline) ++numFailed;
	_funcptr_glCreateShaderProgramv = (PFNGLCREATESHADERPROGRAMVPROC)IntGetProcAddress("glCreateShaderProgramv");
	if(!_funcptr_glCreateShaderProgramv) ++numFailed;
	_funcptr_glDeleteProgramPipelines = (PFNGLDELETEPROGRAMPIPELINESPROC)IntGetProcAddress("glDeleteProgramPipelines");
	if(!_funcptr_glDeleteProgramPipelines) ++numFailed;
	_funcptr_glGenProgramPipelines = (PFNGLGENPROGRAMPIPELINESPROC)IntGetProcAddress("glGenProgramPipelines");
	if(!_funcptr_glGenProgramPipelines) ++numFailed;
	_funcptr_glGetProgramPipelineInfoLog = (PFNGLGETPROGRAMPIPELINEINFOLOGPROC)IntGetProcAddress("glGetProgramPipelineInfoLog");
	if(!_funcptr_glGetProgramPipelineInfoLog) ++numFailed;
	_funcptr_glGetProgramPipelineiv = (PFNGLGETPROGRAMPIPELINEIVPROC)IntGetProcAddress("glGetProgramPipelineiv");
	if(!_funcptr_glGetProgramPipelineiv) ++numFailed;
	_funcptr_glIsProgramPipeline = (PFNGLISPROGRAMPIPELINEPROC)IntGetProcAddress("glIsProgramPipeline");
	if(!_funcptr_glIsProgramPipeline) ++numFailed;
	_funcptr_glProgramUniform1d = (PFNGLPROGRAMUNIFORM1DPROC)IntGetProcAddress("glProgramUniform1d");
	if(!_funcptr_glProgramUniform1d) ++numFailed;
	_funcptr_glProgramUniform1dv = (PFNGLPROGRAMUNIFORM1DVPROC)IntGetProcAddress("glProgramUniform1dv");
	if(!_funcptr_glProgramUniform1dv) ++numFailed;
	_funcptr_glProgramUniform1f = (PFNGLPROGRAMUNIFORM1FPROC)IntGetProcAddress("glProgramUniform1f");
	if(!_funcptr_glProgramUniform1f) ++numFailed;
	_funcptr_glProgramUniform1fv = (PFNGLPROGRAMUNIFORM1FVPROC)IntGetProcAddress("glProgramUniform1fv");
	if(!_funcptr_glProgramUniform1fv) ++numFailed;
	_funcptr_glProgramUniform1i = (PFNGLPROGRAMUNIFORM1IPROC)IntGetProcAddress("glProgramUniform1i");
	if(!_funcptr_glProgramUniform1i) ++numFailed;
	_funcptr_glProgramUniform1iv = (PFNGLPROGRAMUNIFORM1IVPROC)IntGetProcAddress("glProgramUniform1iv");
	if(!_funcptr_glProgramUniform1iv) ++numFailed;
	_funcptr_glProgramUniform1ui = (PFNGLPROGRAMUNIFORM1UIPROC)IntGetProcAddress("glProgramUniform1ui");
	if(!_funcptr_glProgramUniform1ui) ++numFailed;
	_funcptr_glProgramUniform1uiv = (PFNGLPROGRAMUNIFORM1UIVPROC)IntGetProcAddress("glProgramUniform1uiv");
	if(!_funcptr_glProgramUniform1uiv) ++numFailed;
	_funcptr_glProgramUniform2d = (PFNGLPROGRAMUNIFORM2DPROC)IntGetProcAddress("glProgramUniform2d");
	if(!_funcptr_glProgramUniform2d) ++numFailed;
	_funcptr_glProgramUniform2dv = (PFNGLPROGRAMUNIFORM2DVPROC)IntGetProcAddress("glProgramUniform2dv");
	if(!_funcptr_glProgramUniform2dv) ++numFailed;
	_funcptr_glProgramUniform2f = (PFNGLPROGRAMUNIFORM2FPROC)IntGetProcAddress("glProgramUniform2f");
	if(!_funcptr_glProgramUniform2f) ++numFailed;
	_funcptr_glProgramUniform2fv = (PFNGLPROGRAMUNIFORM2FVPROC)IntGetProcAddress("glProgramUniform2fv");
	if(!_funcptr_glProgramUniform2fv) ++numFailed;
	_funcptr_glProgramUniform2i = (PFNGLPROGRAMUNIFORM2IPROC)IntGetProcAddress("glProgramUniform2i");
	if(!_funcptr_glProgramUniform2i) ++numFailed;
	_funcptr_glProgramUniform2iv = (PFNGLPROGRAMUNIFORM2IVPROC)IntGetProcAddress("glProgramUniform2iv");
	if(!_funcptr_glProgramUniform2iv) ++numFailed;
	_funcptr_glProgramUniform2ui = (PFNGLPROGRAMUNIFORM2UIPROC)IntGetProcAddress("glProgramUniform2ui");
	if(!_funcptr_glProgramUniform2ui) ++numFailed;
	_funcptr_glProgramUniform2uiv = (PFNGLPROGRAMUNIFORM2UIVPROC)IntGetProcAddress("glProgramUniform2uiv");
	if(!_funcptr_glProgramUniform2uiv) ++numFailed;
	_funcptr_glProgramUniform3d = (PFNGLPROGRAMUNIFORM3DPROC)IntGetProcAddress("glProgramUniform3d");
	if(!_funcptr_glProgramUniform3d) ++numFailed;
	_funcptr_glProgramUniform3dv = (PFNGLPROGRAMUNIFORM3DVPROC)IntGetProcAddress("glProgramUniform3dv");
	if(!_funcptr_glProgramUniform3dv) ++numFailed;
	_funcptr_glProgramUniform3f = (PFNGLPROGRAMUNIFORM3FPROC)IntGetProcAddress("glProgramUniform3f");
	if(!_funcptr_glProgramUniform3f) ++numFailed;
	_funcptr_glProgramUniform3fv = (PFNGLPROGRAMUNIFORM3FVPROC)IntGetProcAddress("glProgramUniform3fv");
	if(!_funcptr_glProgramUniform3fv) ++numFailed;
	_funcptr_glProgramUniform3i = (PFNGLPROGRAMUNIFORM3IPROC)IntGetProcAddress("glProgramUniform3i");
	if(!_funcptr_glProgramUniform3i) ++numFailed;
	_funcptr_glProgramUniform3iv = (PFNGLPROGRAMUNIFORM3IVPROC)IntGetProcAddress("glProgramUniform3iv");
	if(!_funcptr_glProgramUniform3iv) ++numFailed;
	_funcptr_glProgramUniform3ui = (PFNGLPROGRAMUNIFORM3UIPROC)IntGetProcAddress("glProgramUniform3ui");
	if(!_funcptr_glProgramUniform3ui) ++numFailed;
	_funcptr_glProgramUniform3uiv = (PFNGLPROGRAMUNIFORM3UIVPROC)IntGetProcAddress("glProgramUniform3uiv");
	if(!_funcptr_glProgramUniform3uiv) ++numFailed;
	_funcptr_glProgramUniform4d = (PFNGLPROGRAMUNIFORM4DPROC)IntGetProcAddress("glProgramUniform4d");
	if(!_funcptr_glProgramUniform4d) ++numFailed;
	_funcptr_glProgramUniform4dv = (PFNGLPROGRAMUNIFORM4DVPROC)IntGetProcAddress("glProgramUniform4dv");
	if(!_funcptr_glProgramUniform4dv) ++numFailed;
	_funcptr_glProgramUniform4f = (PFNGLPROGRAMUNIFORM4FPROC)IntGetProcAddress("glProgramUniform4f");
	if(!_funcptr_glProgramUniform4f) ++numFailed;
	_funcptr_glProgramUniform4fv = (PFNGLPROGRAMUNIFORM4FVPROC)IntGetProcAddress("glProgramUniform4fv");
	if(!_funcptr_glProgramUniform4fv) ++numFailed;
	_funcptr_glProgramUniform4i = (PFNGLPROGRAMUNIFORM4IPROC)IntGetProcAddress("glProgramUniform4i");
	if(!_funcptr_glProgramUniform4i) ++numFailed;
	_funcptr_glProgramUniform4iv = (PFNGLPROGRAMUNIFORM4IVPROC)IntGetProcAddress("glProgramUniform4iv");
	if(!_funcptr_glProgramUniform4iv) ++numFailed;
	_funcptr_glProgramUniform4ui = (PFNGLPROGRAMUNIFORM4UIPROC)IntGetProcAddress("glProgramUniform4ui");
	if(!_funcptr_glProgramUniform4ui) ++numFailed;
	_funcptr_glProgramUniform4uiv = (PFNGLPROGRAMUNIFORM4UIVPROC)IntGetProcAddress("glProgramUniform4uiv");
	if(!_funcptr_glProgramUniform4uiv) ++numFailed;
	_funcptr_glProgramUniformMatrix2dv = (PFNGLPROGRAMUNIFORMMATRIX2DVPROC)IntGetProcAddress("glProgramUniformMatrix2dv");
	if(!_funcptr_glProgramUniformMatrix2dv) ++numFailed;
	_funcptr_glProgramUniformMatrix2fv = (PFNGLPROGRAMUNIFORMMATRIX2FVPROC)IntGetProcAddress("glProgramUniformMatrix2fv");
	if(!_funcptr_glProgramUniformMatrix2fv) ++numFailed;
	_funcptr_glProgramUniformMatrix2x3dv = (PFNGLPROGRAMUNIFORMMATRIX2X3DVPROC)IntGetProcAddress("glProgramUniformMatrix2x3dv");
	if(!_funcptr_glProgramUniformMatrix2x3dv) ++numFailed;
	_funcptr_glProgramUniformMatrix2x3fv = (PFNGLPROGRAMUNIFORMMATRIX2X3FVPROC)IntGetProcAddress("glProgramUniformMatrix2x3fv");
	if(!_funcptr_glProgramUniformMatrix2x3fv) ++numFailed;
	_funcptr_glProgramUniformMatrix2x4dv = (PFNGLPROGRAMUNIFORMMATRIX2X4DVPROC)IntGetProcAddress("glProgramUniformMatrix2x4dv");
	if(!_funcptr_glProgramUniformMatrix2x4dv) ++numFailed;
	_funcptr_glProgramUniformMatrix2x4fv = (PFNGLPROGRAMUNIFORMMATRIX2X4FVPROC)IntGetProcAddress("glProgramUniformMatrix2x4fv");
	if(!_funcptr_glProgramUniformMatrix2x4fv) ++numFailed;
	_funcptr_glProgramUniformMatrix3dv = (PFNGLPROGRAMUNIFORMMATRIX3DVPROC)IntGetProcAddress("glProgramUniformMatrix3dv");
	if(!_funcptr_glProgramUniformMatrix3dv) ++numFailed;
	_funcptr_glProgramUniformMatrix3fv = (PFNGLPROGRAMUNIFORMMATRIX3FVPROC)IntGetProcAddress("glProgramUniformMatrix3fv");
	if(!_funcptr_glProgramUniformMatrix3fv) ++numFailed;
	_funcptr_glProgramUniformMatrix3x2dv = (PFNGLPROGRAMUNIFORMMATRIX3X2DVPROC)IntGetProcAddress("glProgramUniformMatrix3x2dv");
	if(!_funcptr_glProgramUniformMatrix3x2dv) ++numFailed;
	_funcptr_glProgramUniformMatrix3x2fv = (PFNGLPROGRAMUNIFORMMATRIX3X2FVPROC)IntGetProcAddress("glProgramUniformMatrix3x2fv");
	if(!_funcptr_glProgramUniformMatrix3x2fv) ++numFailed;
	_funcptr_glProgramUniformMatrix3x4dv = (PFNGLPROGRAMUNIFORMMATRIX3X4DVPROC)IntGetProcAddress("glProgramUniformMatrix3x4dv");
	if(!_funcptr_glProgramUniformMatrix3x4dv) ++numFailed;
	_funcptr_glProgramUniformMatrix3x4fv = (PFNGLPROGRAMUNIFORMMATRIX3X4FVPROC)IntGetProcAddress("glProgramUniformMatrix3x4fv");
	if(!_funcptr_glProgramUniformMatrix3x4fv) ++numFailed;
	_funcptr_glProgramUniformMatrix4dv = (PFNGLPROGRAMUNIFORMMATRIX4DVPROC)IntGetProcAddress("glProgramUniformMatrix4dv");
	if(!_funcptr_glProgramUniformMatrix4dv) ++numFailed;
	_funcptr_glProgramUniformMatrix4fv = (PFNGLPROGRAMUNIFORMMATRIX4FVPROC)IntGetProcAddress("glProgramUniformMatrix4fv");
	if(!_funcptr_glProgramUniformMatrix4fv) ++numFailed;
	_funcptr_glProgramUniformMatrix4x2dv = (PFNGLPROGRAMUNIFORMMATRIX4X2DVPROC)IntGetProcAddress("glProgramUniformMatrix4x2dv");
	if(!_funcptr_glProgramUniformMatrix4x2dv) ++numFailed;
	_funcptr_glProgramUniformMatrix4x2fv = (PFNGLPROGRAMUNIFORMMATRIX4X2FVPROC)IntGetProcAddress("glProgramUniformMatrix4x2fv");
	if(!_funcptr_glProgramUniformMatrix4x2fv) ++numFailed;
	_funcptr_glProgramUniformMatrix4x3dv = (PFNGLPROGRAMUNIFORMMATRIX4X3DVPROC)IntGetProcAddress("glProgramUniformMatrix4x3dv");
	if(!_funcptr_glProgramUniformMatrix4x3dv) ++numFailed;
	_funcptr_glProgramUniformMatrix4x3fv = (PFNGLPROGRAMUNIFORMMATRIX4X3FVPROC)IntGetProcAddress("glProgramUniformMatrix4x3fv");
	if(!_funcptr_glProgramUniformMatrix4x3fv) ++numFailed;
	_funcptr_glUseProgramStages = (PFNGLUSEPROGRAMSTAGESPROC)IntGetProcAddress("glUseProgramStages");
	if(!_funcptr_glUseProgramStages) ++numFailed;
	_funcptr_glValidateProgramPipeline = (PFNGLVALIDATEPROGRAMPIPELINEPROC)IntGetProcAddress("glValidateProgramPipeline");
	if(!_funcptr_glValidateProgramPipeline) ++numFailed;
	return numFailed;
}