#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  scalar_t__ PFNGLTEXCOORD4FVERTEX4FVSUNPROC ;
typedef  scalar_t__ PFNGLTEXCOORD4FVERTEX4FSUNPROC ;
typedef  scalar_t__ PFNGLTEXCOORD4FCOLOR4FNORMAL3FVERTEX4FVSUNPROC ;
typedef  scalar_t__ PFNGLTEXCOORD4FCOLOR4FNORMAL3FVERTEX4FSUNPROC ;
typedef  scalar_t__ PFNGLTEXCOORD2FVERTEX3FVSUNPROC ;
typedef  scalar_t__ PFNGLTEXCOORD2FVERTEX3FSUNPROC ;
typedef  scalar_t__ PFNGLTEXCOORD2FNORMAL3FVERTEX3FVSUNPROC ;
typedef  scalar_t__ PFNGLTEXCOORD2FNORMAL3FVERTEX3FSUNPROC ;
typedef  scalar_t__ PFNGLTEXCOORD2FCOLOR4UBVERTEX3FVSUNPROC ;
typedef  scalar_t__ PFNGLTEXCOORD2FCOLOR4UBVERTEX3FSUNPROC ;
typedef  scalar_t__ PFNGLTEXCOORD2FCOLOR4FNORMAL3FVERTEX3FVSUNPROC ;
typedef  scalar_t__ PFNGLTEXCOORD2FCOLOR4FNORMAL3FVERTEX3FSUNPROC ;
typedef  scalar_t__ PFNGLTEXCOORD2FCOLOR3FVERTEX3FVSUNPROC ;
typedef  scalar_t__ PFNGLTEXCOORD2FCOLOR3FVERTEX3FSUNPROC ;
typedef  scalar_t__ PFNGLREPLACEMENTCODEUIVERTEX3FVSUNPROC ;
typedef  scalar_t__ PFNGLREPLACEMENTCODEUIVERTEX3FSUNPROC ;
typedef  scalar_t__ PFNGLREPLACEMENTCODEUITEXCOORD2FVERTEX3FVSUNPROC ;
typedef  scalar_t__ PFNGLREPLACEMENTCODEUITEXCOORD2FVERTEX3FSUNPROC ;
typedef  scalar_t__ PFNGLREPLACEMENTCODEUITEXCOORD2FNORMAL3FVERTEX3FVSUNPROC ;
typedef  scalar_t__ PFNGLREPLACEMENTCODEUITEXCOORD2FNORMAL3FVERTEX3FSUNPROC ;
typedef  scalar_t__ PFNGLREPLACEMENTCODEUITEXCOORD2FCOLOR4FNORMAL3FVERTEX3FVSUNPROC ;
typedef  scalar_t__ PFNGLREPLACEMENTCODEUITEXCOORD2FCOLOR4FNORMAL3FVERTEX3FSUNPROC ;
typedef  scalar_t__ PFNGLREPLACEMENTCODEUINORMAL3FVERTEX3FVSUNPROC ;
typedef  scalar_t__ PFNGLREPLACEMENTCODEUINORMAL3FVERTEX3FSUNPROC ;
typedef  scalar_t__ PFNGLREPLACEMENTCODEUICOLOR4UBVERTEX3FVSUNPROC ;
typedef  scalar_t__ PFNGLREPLACEMENTCODEUICOLOR4UBVERTEX3FSUNPROC ;
typedef  scalar_t__ PFNGLREPLACEMENTCODEUICOLOR4FNORMAL3FVERTEX3FVSUNPROC ;
typedef  scalar_t__ PFNGLREPLACEMENTCODEUICOLOR4FNORMAL3FVERTEX3FSUNPROC ;
typedef  scalar_t__ PFNGLREPLACEMENTCODEUICOLOR3FVERTEX3FVSUNPROC ;
typedef  scalar_t__ PFNGLREPLACEMENTCODEUICOLOR3FVERTEX3FSUNPROC ;
typedef  scalar_t__ PFNGLNORMAL3FVERTEX3FVSUNPROC ;
typedef  scalar_t__ PFNGLNORMAL3FVERTEX3FSUNPROC ;
typedef  scalar_t__ PFNGLCOLOR4UBVERTEX3FVSUNPROC ;
typedef  scalar_t__ PFNGLCOLOR4UBVERTEX3FSUNPROC ;
typedef  scalar_t__ PFNGLCOLOR4UBVERTEX2FVSUNPROC ;
typedef  scalar_t__ PFNGLCOLOR4UBVERTEX2FSUNPROC ;
typedef  scalar_t__ PFNGLCOLOR4FNORMAL3FVERTEX3FVSUNPROC ;
typedef  scalar_t__ PFNGLCOLOR4FNORMAL3FVERTEX3FSUNPROC ;
typedef  scalar_t__ PFNGLCOLOR3FVERTEX3FVSUNPROC ;
typedef  scalar_t__ PFNGLCOLOR3FVERTEX3FSUNPROC ;

/* Variables and functions */
 scalar_t__ IntGetProcAddress (char*) ; 
 scalar_t__ _funcptr_glColor3fVertex3fSUN ; 
 scalar_t__ _funcptr_glColor3fVertex3fvSUN ; 
 scalar_t__ _funcptr_glColor4fNormal3fVertex3fSUN ; 
 scalar_t__ _funcptr_glColor4fNormal3fVertex3fvSUN ; 
 scalar_t__ _funcptr_glColor4ubVertex2fSUN ; 
 scalar_t__ _funcptr_glColor4ubVertex2fvSUN ; 
 scalar_t__ _funcptr_glColor4ubVertex3fSUN ; 
 scalar_t__ _funcptr_glColor4ubVertex3fvSUN ; 
 scalar_t__ _funcptr_glNormal3fVertex3fSUN ; 
 scalar_t__ _funcptr_glNormal3fVertex3fvSUN ; 
 scalar_t__ _funcptr_glReplacementCodeuiColor3fVertex3fSUN ; 
 scalar_t__ _funcptr_glReplacementCodeuiColor3fVertex3fvSUN ; 
 scalar_t__ _funcptr_glReplacementCodeuiColor4fNormal3fVertex3fSUN ; 
 scalar_t__ _funcptr_glReplacementCodeuiColor4fNormal3fVertex3fvSUN ; 
 scalar_t__ _funcptr_glReplacementCodeuiColor4ubVertex3fSUN ; 
 scalar_t__ _funcptr_glReplacementCodeuiColor4ubVertex3fvSUN ; 
 scalar_t__ _funcptr_glReplacementCodeuiNormal3fVertex3fSUN ; 
 scalar_t__ _funcptr_glReplacementCodeuiNormal3fVertex3fvSUN ; 
 scalar_t__ _funcptr_glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fSUN ; 
 scalar_t__ _funcptr_glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fvSUN ; 
 scalar_t__ _funcptr_glReplacementCodeuiTexCoord2fNormal3fVertex3fSUN ; 
 scalar_t__ _funcptr_glReplacementCodeuiTexCoord2fNormal3fVertex3fvSUN ; 
 scalar_t__ _funcptr_glReplacementCodeuiTexCoord2fVertex3fSUN ; 
 scalar_t__ _funcptr_glReplacementCodeuiTexCoord2fVertex3fvSUN ; 
 scalar_t__ _funcptr_glReplacementCodeuiVertex3fSUN ; 
 scalar_t__ _funcptr_glReplacementCodeuiVertex3fvSUN ; 
 scalar_t__ _funcptr_glTexCoord2fColor3fVertex3fSUN ; 
 scalar_t__ _funcptr_glTexCoord2fColor3fVertex3fvSUN ; 
 scalar_t__ _funcptr_glTexCoord2fColor4fNormal3fVertex3fSUN ; 
 scalar_t__ _funcptr_glTexCoord2fColor4fNormal3fVertex3fvSUN ; 
 scalar_t__ _funcptr_glTexCoord2fColor4ubVertex3fSUN ; 
 scalar_t__ _funcptr_glTexCoord2fColor4ubVertex3fvSUN ; 
 scalar_t__ _funcptr_glTexCoord2fNormal3fVertex3fSUN ; 
 scalar_t__ _funcptr_glTexCoord2fNormal3fVertex3fvSUN ; 
 scalar_t__ _funcptr_glTexCoord2fVertex3fSUN ; 
 scalar_t__ _funcptr_glTexCoord2fVertex3fvSUN ; 
 scalar_t__ _funcptr_glTexCoord4fColor4fNormal3fVertex4fSUN ; 
 scalar_t__ _funcptr_glTexCoord4fColor4fNormal3fVertex4fvSUN ; 
 scalar_t__ _funcptr_glTexCoord4fVertex4fSUN ; 
 scalar_t__ _funcptr_glTexCoord4fVertex4fvSUN ; 

__attribute__((used)) static int LoadExt_SUN_vertex()
{
	int numFailed = 0;
	_funcptr_glColor3fVertex3fSUN = (PFNGLCOLOR3FVERTEX3FSUNPROC)IntGetProcAddress("glColor3fVertex3fSUN");
	if(!_funcptr_glColor3fVertex3fSUN) ++numFailed;
	_funcptr_glColor3fVertex3fvSUN = (PFNGLCOLOR3FVERTEX3FVSUNPROC)IntGetProcAddress("glColor3fVertex3fvSUN");
	if(!_funcptr_glColor3fVertex3fvSUN) ++numFailed;
	_funcptr_glColor4fNormal3fVertex3fSUN = (PFNGLCOLOR4FNORMAL3FVERTEX3FSUNPROC)IntGetProcAddress("glColor4fNormal3fVertex3fSUN");
	if(!_funcptr_glColor4fNormal3fVertex3fSUN) ++numFailed;
	_funcptr_glColor4fNormal3fVertex3fvSUN = (PFNGLCOLOR4FNORMAL3FVERTEX3FVSUNPROC)IntGetProcAddress("glColor4fNormal3fVertex3fvSUN");
	if(!_funcptr_glColor4fNormal3fVertex3fvSUN) ++numFailed;
	_funcptr_glColor4ubVertex2fSUN = (PFNGLCOLOR4UBVERTEX2FSUNPROC)IntGetProcAddress("glColor4ubVertex2fSUN");
	if(!_funcptr_glColor4ubVertex2fSUN) ++numFailed;
	_funcptr_glColor4ubVertex2fvSUN = (PFNGLCOLOR4UBVERTEX2FVSUNPROC)IntGetProcAddress("glColor4ubVertex2fvSUN");
	if(!_funcptr_glColor4ubVertex2fvSUN) ++numFailed;
	_funcptr_glColor4ubVertex3fSUN = (PFNGLCOLOR4UBVERTEX3FSUNPROC)IntGetProcAddress("glColor4ubVertex3fSUN");
	if(!_funcptr_glColor4ubVertex3fSUN) ++numFailed;
	_funcptr_glColor4ubVertex3fvSUN = (PFNGLCOLOR4UBVERTEX3FVSUNPROC)IntGetProcAddress("glColor4ubVertex3fvSUN");
	if(!_funcptr_glColor4ubVertex3fvSUN) ++numFailed;
	_funcptr_glNormal3fVertex3fSUN = (PFNGLNORMAL3FVERTEX3FSUNPROC)IntGetProcAddress("glNormal3fVertex3fSUN");
	if(!_funcptr_glNormal3fVertex3fSUN) ++numFailed;
	_funcptr_glNormal3fVertex3fvSUN = (PFNGLNORMAL3FVERTEX3FVSUNPROC)IntGetProcAddress("glNormal3fVertex3fvSUN");
	if(!_funcptr_glNormal3fVertex3fvSUN) ++numFailed;
	_funcptr_glReplacementCodeuiColor3fVertex3fSUN = (PFNGLREPLACEMENTCODEUICOLOR3FVERTEX3FSUNPROC)IntGetProcAddress("glReplacementCodeuiColor3fVertex3fSUN");
	if(!_funcptr_glReplacementCodeuiColor3fVertex3fSUN) ++numFailed;
	_funcptr_glReplacementCodeuiColor3fVertex3fvSUN = (PFNGLREPLACEMENTCODEUICOLOR3FVERTEX3FVSUNPROC)IntGetProcAddress("glReplacementCodeuiColor3fVertex3fvSUN");
	if(!_funcptr_glReplacementCodeuiColor3fVertex3fvSUN) ++numFailed;
	_funcptr_glReplacementCodeuiColor4fNormal3fVertex3fSUN = (PFNGLREPLACEMENTCODEUICOLOR4FNORMAL3FVERTEX3FSUNPROC)IntGetProcAddress("glReplacementCodeuiColor4fNormal3fVertex3fSUN");
	if(!_funcptr_glReplacementCodeuiColor4fNormal3fVertex3fSUN) ++numFailed;
	_funcptr_glReplacementCodeuiColor4fNormal3fVertex3fvSUN = (PFNGLREPLACEMENTCODEUICOLOR4FNORMAL3FVERTEX3FVSUNPROC)IntGetProcAddress("glReplacementCodeuiColor4fNormal3fVertex3fvSUN");
	if(!_funcptr_glReplacementCodeuiColor4fNormal3fVertex3fvSUN) ++numFailed;
	_funcptr_glReplacementCodeuiColor4ubVertex3fSUN = (PFNGLREPLACEMENTCODEUICOLOR4UBVERTEX3FSUNPROC)IntGetProcAddress("glReplacementCodeuiColor4ubVertex3fSUN");
	if(!_funcptr_glReplacementCodeuiColor4ubVertex3fSUN) ++numFailed;
	_funcptr_glReplacementCodeuiColor4ubVertex3fvSUN = (PFNGLREPLACEMENTCODEUICOLOR4UBVERTEX3FVSUNPROC)IntGetProcAddress("glReplacementCodeuiColor4ubVertex3fvSUN");
	if(!_funcptr_glReplacementCodeuiColor4ubVertex3fvSUN) ++numFailed;
	_funcptr_glReplacementCodeuiNormal3fVertex3fSUN = (PFNGLREPLACEMENTCODEUINORMAL3FVERTEX3FSUNPROC)IntGetProcAddress("glReplacementCodeuiNormal3fVertex3fSUN");
	if(!_funcptr_glReplacementCodeuiNormal3fVertex3fSUN) ++numFailed;
	_funcptr_glReplacementCodeuiNormal3fVertex3fvSUN = (PFNGLREPLACEMENTCODEUINORMAL3FVERTEX3FVSUNPROC)IntGetProcAddress("glReplacementCodeuiNormal3fVertex3fvSUN");
	if(!_funcptr_glReplacementCodeuiNormal3fVertex3fvSUN) ++numFailed;
	_funcptr_glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fSUN = (PFNGLREPLACEMENTCODEUITEXCOORD2FCOLOR4FNORMAL3FVERTEX3FSUNPROC)IntGetProcAddress("glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fSUN");
	if(!_funcptr_glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fSUN) ++numFailed;
	_funcptr_glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fvSUN = (PFNGLREPLACEMENTCODEUITEXCOORD2FCOLOR4FNORMAL3FVERTEX3FVSUNPROC)IntGetProcAddress("glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fvSUN");
	if(!_funcptr_glReplacementCodeuiTexCoord2fColor4fNormal3fVertex3fvSUN) ++numFailed;
	_funcptr_glReplacementCodeuiTexCoord2fNormal3fVertex3fSUN = (PFNGLREPLACEMENTCODEUITEXCOORD2FNORMAL3FVERTEX3FSUNPROC)IntGetProcAddress("glReplacementCodeuiTexCoord2fNormal3fVertex3fSUN");
	if(!_funcptr_glReplacementCodeuiTexCoord2fNormal3fVertex3fSUN) ++numFailed;
	_funcptr_glReplacementCodeuiTexCoord2fNormal3fVertex3fvSUN = (PFNGLREPLACEMENTCODEUITEXCOORD2FNORMAL3FVERTEX3FVSUNPROC)IntGetProcAddress("glReplacementCodeuiTexCoord2fNormal3fVertex3fvSUN");
	if(!_funcptr_glReplacementCodeuiTexCoord2fNormal3fVertex3fvSUN) ++numFailed;
	_funcptr_glReplacementCodeuiTexCoord2fVertex3fSUN = (PFNGLREPLACEMENTCODEUITEXCOORD2FVERTEX3FSUNPROC)IntGetProcAddress("glReplacementCodeuiTexCoord2fVertex3fSUN");
	if(!_funcptr_glReplacementCodeuiTexCoord2fVertex3fSUN) ++numFailed;
	_funcptr_glReplacementCodeuiTexCoord2fVertex3fvSUN = (PFNGLREPLACEMENTCODEUITEXCOORD2FVERTEX3FVSUNPROC)IntGetProcAddress("glReplacementCodeuiTexCoord2fVertex3fvSUN");
	if(!_funcptr_glReplacementCodeuiTexCoord2fVertex3fvSUN) ++numFailed;
	_funcptr_glReplacementCodeuiVertex3fSUN = (PFNGLREPLACEMENTCODEUIVERTEX3FSUNPROC)IntGetProcAddress("glReplacementCodeuiVertex3fSUN");
	if(!_funcptr_glReplacementCodeuiVertex3fSUN) ++numFailed;
	_funcptr_glReplacementCodeuiVertex3fvSUN = (PFNGLREPLACEMENTCODEUIVERTEX3FVSUNPROC)IntGetProcAddress("glReplacementCodeuiVertex3fvSUN");
	if(!_funcptr_glReplacementCodeuiVertex3fvSUN) ++numFailed;
	_funcptr_glTexCoord2fColor3fVertex3fSUN = (PFNGLTEXCOORD2FCOLOR3FVERTEX3FSUNPROC)IntGetProcAddress("glTexCoord2fColor3fVertex3fSUN");
	if(!_funcptr_glTexCoord2fColor3fVertex3fSUN) ++numFailed;
	_funcptr_glTexCoord2fColor3fVertex3fvSUN = (PFNGLTEXCOORD2FCOLOR3FVERTEX3FVSUNPROC)IntGetProcAddress("glTexCoord2fColor3fVertex3fvSUN");
	if(!_funcptr_glTexCoord2fColor3fVertex3fvSUN) ++numFailed;
	_funcptr_glTexCoord2fColor4fNormal3fVertex3fSUN = (PFNGLTEXCOORD2FCOLOR4FNORMAL3FVERTEX3FSUNPROC)IntGetProcAddress("glTexCoord2fColor4fNormal3fVertex3fSUN");
	if(!_funcptr_glTexCoord2fColor4fNormal3fVertex3fSUN) ++numFailed;
	_funcptr_glTexCoord2fColor4fNormal3fVertex3fvSUN = (PFNGLTEXCOORD2FCOLOR4FNORMAL3FVERTEX3FVSUNPROC)IntGetProcAddress("glTexCoord2fColor4fNormal3fVertex3fvSUN");
	if(!_funcptr_glTexCoord2fColor4fNormal3fVertex3fvSUN) ++numFailed;
	_funcptr_glTexCoord2fColor4ubVertex3fSUN = (PFNGLTEXCOORD2FCOLOR4UBVERTEX3FSUNPROC)IntGetProcAddress("glTexCoord2fColor4ubVertex3fSUN");
	if(!_funcptr_glTexCoord2fColor4ubVertex3fSUN) ++numFailed;
	_funcptr_glTexCoord2fColor4ubVertex3fvSUN = (PFNGLTEXCOORD2FCOLOR4UBVERTEX3FVSUNPROC)IntGetProcAddress("glTexCoord2fColor4ubVertex3fvSUN");
	if(!_funcptr_glTexCoord2fColor4ubVertex3fvSUN) ++numFailed;
	_funcptr_glTexCoord2fNormal3fVertex3fSUN = (PFNGLTEXCOORD2FNORMAL3FVERTEX3FSUNPROC)IntGetProcAddress("glTexCoord2fNormal3fVertex3fSUN");
	if(!_funcptr_glTexCoord2fNormal3fVertex3fSUN) ++numFailed;
	_funcptr_glTexCoord2fNormal3fVertex3fvSUN = (PFNGLTEXCOORD2FNORMAL3FVERTEX3FVSUNPROC)IntGetProcAddress("glTexCoord2fNormal3fVertex3fvSUN");
	if(!_funcptr_glTexCoord2fNormal3fVertex3fvSUN) ++numFailed;
	_funcptr_glTexCoord2fVertex3fSUN = (PFNGLTEXCOORD2FVERTEX3FSUNPROC)IntGetProcAddress("glTexCoord2fVertex3fSUN");
	if(!_funcptr_glTexCoord2fVertex3fSUN) ++numFailed;
	_funcptr_glTexCoord2fVertex3fvSUN = (PFNGLTEXCOORD2FVERTEX3FVSUNPROC)IntGetProcAddress("glTexCoord2fVertex3fvSUN");
	if(!_funcptr_glTexCoord2fVertex3fvSUN) ++numFailed;
	_funcptr_glTexCoord4fColor4fNormal3fVertex4fSUN = (PFNGLTEXCOORD4FCOLOR4FNORMAL3FVERTEX4FSUNPROC)IntGetProcAddress("glTexCoord4fColor4fNormal3fVertex4fSUN");
	if(!_funcptr_glTexCoord4fColor4fNormal3fVertex4fSUN) ++numFailed;
	_funcptr_glTexCoord4fColor4fNormal3fVertex4fvSUN = (PFNGLTEXCOORD4FCOLOR4FNORMAL3FVERTEX4FVSUNPROC)IntGetProcAddress("glTexCoord4fColor4fNormal3fVertex4fvSUN");
	if(!_funcptr_glTexCoord4fColor4fNormal3fVertex4fvSUN) ++numFailed;
	_funcptr_glTexCoord4fVertex4fSUN = (PFNGLTEXCOORD4FVERTEX4FSUNPROC)IntGetProcAddress("glTexCoord4fVertex4fSUN");
	if(!_funcptr_glTexCoord4fVertex4fSUN) ++numFailed;
	_funcptr_glTexCoord4fVertex4fvSUN = (PFNGLTEXCOORD4FVERTEX4FVSUNPROC)IntGetProcAddress("glTexCoord4fVertex4fvSUN");
	if(!_funcptr_glTexCoord4fVertex4fvSUN) ++numFailed;
	return numFailed;
}