#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  scalar_t__ PFNGLVERTEXATTRIBIPOINTERPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBI4USVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBI4UIVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBI4UIPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBI4UBVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBI4SVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBI4IVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBI4IPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBI4BVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBI3UIVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBI3UIPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBI3IVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBI3IPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBI2UIVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBI2UIPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBI2IVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBI2IPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBI1UIVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBI1UIPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBI1IVPROC ;
typedef  scalar_t__ PFNGLVERTEXATTRIBI1IPROC ;
typedef  scalar_t__ PFNGLUNIFORM4UIVPROC ;
typedef  scalar_t__ PFNGLUNIFORM4UIPROC ;
typedef  scalar_t__ PFNGLUNIFORM3UIVPROC ;
typedef  scalar_t__ PFNGLUNIFORM3UIPROC ;
typedef  scalar_t__ PFNGLUNIFORM2UIVPROC ;
typedef  scalar_t__ PFNGLUNIFORM2UIPROC ;
typedef  scalar_t__ PFNGLUNIFORM1UIVPROC ;
typedef  scalar_t__ PFNGLUNIFORM1UIPROC ;
typedef  scalar_t__ PFNGLTRANSFORMFEEDBACKVARYINGSPROC ;
typedef  scalar_t__ PFNGLTEXPARAMETERIUIVPROC ;
typedef  scalar_t__ PFNGLTEXPARAMETERIIVPROC ;
typedef  scalar_t__ PFNGLRENDERBUFFERSTORAGEPROC ;
typedef  scalar_t__ PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC ;
typedef  scalar_t__ PFNGLMAPBUFFERRANGEPROC ;
typedef  scalar_t__ PFNGLISVERTEXARRAYPROC ;
typedef  scalar_t__ PFNGLISRENDERBUFFERPROC ;
typedef  scalar_t__ PFNGLISFRAMEBUFFERPROC ;
typedef  scalar_t__ PFNGLISENABLEDIPROC ;
typedef  scalar_t__ PFNGLGETVERTEXATTRIBIUIVPROC ;
typedef  scalar_t__ PFNGLGETVERTEXATTRIBIIVPROC ;
typedef  scalar_t__ PFNGLGETUNIFORMUIVPROC ;
typedef  scalar_t__ PFNGLGETTRANSFORMFEEDBACKVARYINGPROC ;
typedef  scalar_t__ PFNGLGETTEXPARAMETERIUIVPROC ;
typedef  scalar_t__ PFNGLGETTEXPARAMETERIIVPROC ;
typedef  scalar_t__ PFNGLGETSTRINGIPROC ;
typedef  scalar_t__ PFNGLGETRENDERBUFFERPARAMETERIVPROC ;
typedef  scalar_t__ PFNGLGETINTEGERI_VPROC ;
typedef  scalar_t__ PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC ;
typedef  scalar_t__ PFNGLGETFRAGDATALOCATIONPROC ;
typedef  scalar_t__ PFNGLGETBOOLEANI_VPROC ;
typedef  scalar_t__ PFNGLGENVERTEXARRAYSPROC ;
typedef  scalar_t__ PFNGLGENRENDERBUFFERSPROC ;
typedef  scalar_t__ PFNGLGENFRAMEBUFFERSPROC ;
typedef  scalar_t__ PFNGLGENERATEMIPMAPPROC ;
typedef  scalar_t__ PFNGLFRAMEBUFFERTEXTURELAYERPROC ;
typedef  scalar_t__ PFNGLFRAMEBUFFERTEXTURE3DPROC ;
typedef  scalar_t__ PFNGLFRAMEBUFFERTEXTURE2DPROC ;
typedef  scalar_t__ PFNGLFRAMEBUFFERTEXTURE1DPROC ;
typedef  scalar_t__ PFNGLFRAMEBUFFERRENDERBUFFERPROC ;
typedef  scalar_t__ PFNGLFLUSHMAPPEDBUFFERRANGEPROC ;
typedef  scalar_t__ PFNGLENDTRANSFORMFEEDBACKPROC ;
typedef  scalar_t__ PFNGLENDCONDITIONALRENDERPROC ;
typedef  scalar_t__ PFNGLENABLEIPROC ;
typedef  scalar_t__ PFNGLDISABLEIPROC ;
typedef  scalar_t__ PFNGLDELETEVERTEXARRAYSPROC ;
typedef  scalar_t__ PFNGLDELETERENDERBUFFERSPROC ;
typedef  scalar_t__ PFNGLDELETEFRAMEBUFFERSPROC ;
typedef  scalar_t__ PFNGLCOLORMASKIPROC ;
typedef  scalar_t__ PFNGLCLEARBUFFERUIVPROC ;
typedef  scalar_t__ PFNGLCLEARBUFFERIVPROC ;
typedef  scalar_t__ PFNGLCLEARBUFFERFVPROC ;
typedef  scalar_t__ PFNGLCLEARBUFFERFIPROC ;
typedef  scalar_t__ PFNGLCLAMPCOLORPROC ;
typedef  scalar_t__ PFNGLCHECKFRAMEBUFFERSTATUSPROC ;
typedef  scalar_t__ PFNGLBLITFRAMEBUFFERPROC ;
typedef  scalar_t__ PFNGLBINDVERTEXARRAYPROC ;
typedef  scalar_t__ PFNGLBINDRENDERBUFFERPROC ;
typedef  scalar_t__ PFNGLBINDFRAMEBUFFERPROC ;
typedef  scalar_t__ PFNGLBINDFRAGDATALOCATIONPROC ;
typedef  scalar_t__ PFNGLBINDBUFFERRANGEPROC ;
typedef  scalar_t__ PFNGLBINDBUFFERBASEPROC ;
typedef  scalar_t__ PFNGLBEGINTRANSFORMFEEDBACKPROC ;
typedef  scalar_t__ PFNGLBEGINCONDITIONALRENDERPROC ;

/* Variables and functions */
 scalar_t__ IntGetProcAddress (char*) ; 
 scalar_t__ _funcptr_glBeginConditionalRender ; 
 scalar_t__ _funcptr_glBeginTransformFeedback ; 
 scalar_t__ _funcptr_glBindBufferBase ; 
 scalar_t__ _funcptr_glBindBufferRange ; 
 scalar_t__ _funcptr_glBindFragDataLocation ; 
 scalar_t__ _funcptr_glBindFramebuffer ; 
 scalar_t__ _funcptr_glBindRenderbuffer ; 
 scalar_t__ _funcptr_glBindVertexArray ; 
 scalar_t__ _funcptr_glBlitFramebuffer ; 
 scalar_t__ _funcptr_glCheckFramebufferStatus ; 
 scalar_t__ _funcptr_glClampColor ; 
 scalar_t__ _funcptr_glClearBufferfi ; 
 scalar_t__ _funcptr_glClearBufferfv ; 
 scalar_t__ _funcptr_glClearBufferiv ; 
 scalar_t__ _funcptr_glClearBufferuiv ; 
 scalar_t__ _funcptr_glColorMaski ; 
 scalar_t__ _funcptr_glDeleteFramebuffers ; 
 scalar_t__ _funcptr_glDeleteRenderbuffers ; 
 scalar_t__ _funcptr_glDeleteVertexArrays ; 
 scalar_t__ _funcptr_glDisablei ; 
 scalar_t__ _funcptr_glEnablei ; 
 scalar_t__ _funcptr_glEndConditionalRender ; 
 scalar_t__ _funcptr_glEndTransformFeedback ; 
 scalar_t__ _funcptr_glFlushMappedBufferRange ; 
 scalar_t__ _funcptr_glFramebufferRenderbuffer ; 
 scalar_t__ _funcptr_glFramebufferTexture1D ; 
 scalar_t__ _funcptr_glFramebufferTexture2D ; 
 scalar_t__ _funcptr_glFramebufferTexture3D ; 
 scalar_t__ _funcptr_glFramebufferTextureLayer ; 
 scalar_t__ _funcptr_glGenFramebuffers ; 
 scalar_t__ _funcptr_glGenRenderbuffers ; 
 scalar_t__ _funcptr_glGenVertexArrays ; 
 scalar_t__ _funcptr_glGenerateMipmap ; 
 scalar_t__ _funcptr_glGetBooleani_v ; 
 scalar_t__ _funcptr_glGetFragDataLocation ; 
 scalar_t__ _funcptr_glGetFramebufferAttachmentParameteriv ; 
 scalar_t__ _funcptr_glGetIntegeri_v ; 
 scalar_t__ _funcptr_glGetRenderbufferParameteriv ; 
 scalar_t__ _funcptr_glGetStringi ; 
 scalar_t__ _funcptr_glGetTexParameterIiv ; 
 scalar_t__ _funcptr_glGetTexParameterIuiv ; 
 scalar_t__ _funcptr_glGetTransformFeedbackVarying ; 
 scalar_t__ _funcptr_glGetUniformuiv ; 
 scalar_t__ _funcptr_glGetVertexAttribIiv ; 
 scalar_t__ _funcptr_glGetVertexAttribIuiv ; 
 scalar_t__ _funcptr_glIsEnabledi ; 
 scalar_t__ _funcptr_glIsFramebuffer ; 
 scalar_t__ _funcptr_glIsRenderbuffer ; 
 scalar_t__ _funcptr_glIsVertexArray ; 
 scalar_t__ _funcptr_glMapBufferRange ; 
 scalar_t__ _funcptr_glRenderbufferStorage ; 
 scalar_t__ _funcptr_glRenderbufferStorageMultisample ; 
 scalar_t__ _funcptr_glTexParameterIiv ; 
 scalar_t__ _funcptr_glTexParameterIuiv ; 
 scalar_t__ _funcptr_glTransformFeedbackVaryings ; 
 scalar_t__ _funcptr_glUniform1ui ; 
 scalar_t__ _funcptr_glUniform1uiv ; 
 scalar_t__ _funcptr_glUniform2ui ; 
 scalar_t__ _funcptr_glUniform2uiv ; 
 scalar_t__ _funcptr_glUniform3ui ; 
 scalar_t__ _funcptr_glUniform3uiv ; 
 scalar_t__ _funcptr_glUniform4ui ; 
 scalar_t__ _funcptr_glUniform4uiv ; 
 scalar_t__ _funcptr_glVertexAttribI1i ; 
 scalar_t__ _funcptr_glVertexAttribI1iv ; 
 scalar_t__ _funcptr_glVertexAttribI1ui ; 
 scalar_t__ _funcptr_glVertexAttribI1uiv ; 
 scalar_t__ _funcptr_glVertexAttribI2i ; 
 scalar_t__ _funcptr_glVertexAttribI2iv ; 
 scalar_t__ _funcptr_glVertexAttribI2ui ; 
 scalar_t__ _funcptr_glVertexAttribI2uiv ; 
 scalar_t__ _funcptr_glVertexAttribI3i ; 
 scalar_t__ _funcptr_glVertexAttribI3iv ; 
 scalar_t__ _funcptr_glVertexAttribI3ui ; 
 scalar_t__ _funcptr_glVertexAttribI3uiv ; 
 scalar_t__ _funcptr_glVertexAttribI4bv ; 
 scalar_t__ _funcptr_glVertexAttribI4i ; 
 scalar_t__ _funcptr_glVertexAttribI4iv ; 
 scalar_t__ _funcptr_glVertexAttribI4sv ; 
 scalar_t__ _funcptr_glVertexAttribI4ubv ; 
 scalar_t__ _funcptr_glVertexAttribI4ui ; 
 scalar_t__ _funcptr_glVertexAttribI4uiv ; 
 scalar_t__ _funcptr_glVertexAttribI4usv ; 
 scalar_t__ _funcptr_glVertexAttribIPointer ; 

__attribute__((used)) static int LoadCore_Version_3_0()
{
	int numFailed = 0;
	_funcptr_glBeginConditionalRender = (PFNGLBEGINCONDITIONALRENDERPROC)IntGetProcAddress("glBeginConditionalRender");
	if(!_funcptr_glBeginConditionalRender) ++numFailed;
	_funcptr_glBeginTransformFeedback = (PFNGLBEGINTRANSFORMFEEDBACKPROC)IntGetProcAddress("glBeginTransformFeedback");
	if(!_funcptr_glBeginTransformFeedback) ++numFailed;
	_funcptr_glBindBufferBase = (PFNGLBINDBUFFERBASEPROC)IntGetProcAddress("glBindBufferBase");
	if(!_funcptr_glBindBufferBase) ++numFailed;
	_funcptr_glBindBufferRange = (PFNGLBINDBUFFERRANGEPROC)IntGetProcAddress("glBindBufferRange");
	if(!_funcptr_glBindBufferRange) ++numFailed;
	_funcptr_glBindFragDataLocation = (PFNGLBINDFRAGDATALOCATIONPROC)IntGetProcAddress("glBindFragDataLocation");
	if(!_funcptr_glBindFragDataLocation) ++numFailed;
	_funcptr_glBindFramebuffer = (PFNGLBINDFRAMEBUFFERPROC)IntGetProcAddress("glBindFramebuffer");
	if(!_funcptr_glBindFramebuffer) ++numFailed;
	_funcptr_glBindRenderbuffer = (PFNGLBINDRENDERBUFFERPROC)IntGetProcAddress("glBindRenderbuffer");
	if(!_funcptr_glBindRenderbuffer) ++numFailed;
	_funcptr_glBindVertexArray = (PFNGLBINDVERTEXARRAYPROC)IntGetProcAddress("glBindVertexArray");
	if(!_funcptr_glBindVertexArray) ++numFailed;
	_funcptr_glBlitFramebuffer = (PFNGLBLITFRAMEBUFFERPROC)IntGetProcAddress("glBlitFramebuffer");
	if(!_funcptr_glBlitFramebuffer) ++numFailed;
	_funcptr_glCheckFramebufferStatus = (PFNGLCHECKFRAMEBUFFERSTATUSPROC)IntGetProcAddress("glCheckFramebufferStatus");
	if(!_funcptr_glCheckFramebufferStatus) ++numFailed;
	_funcptr_glClampColor = (PFNGLCLAMPCOLORPROC)IntGetProcAddress("glClampColor");
	if(!_funcptr_glClampColor) ++numFailed;
	_funcptr_glClearBufferfi = (PFNGLCLEARBUFFERFIPROC)IntGetProcAddress("glClearBufferfi");
	if(!_funcptr_glClearBufferfi) ++numFailed;
	_funcptr_glClearBufferfv = (PFNGLCLEARBUFFERFVPROC)IntGetProcAddress("glClearBufferfv");
	if(!_funcptr_glClearBufferfv) ++numFailed;
	_funcptr_glClearBufferiv = (PFNGLCLEARBUFFERIVPROC)IntGetProcAddress("glClearBufferiv");
	if(!_funcptr_glClearBufferiv) ++numFailed;
	_funcptr_glClearBufferuiv = (PFNGLCLEARBUFFERUIVPROC)IntGetProcAddress("glClearBufferuiv");
	if(!_funcptr_glClearBufferuiv) ++numFailed;
	_funcptr_glColorMaski = (PFNGLCOLORMASKIPROC)IntGetProcAddress("glColorMaski");
	if(!_funcptr_glColorMaski) ++numFailed;
	_funcptr_glDeleteFramebuffers = (PFNGLDELETEFRAMEBUFFERSPROC)IntGetProcAddress("glDeleteFramebuffers");
	if(!_funcptr_glDeleteFramebuffers) ++numFailed;
	_funcptr_glDeleteRenderbuffers = (PFNGLDELETERENDERBUFFERSPROC)IntGetProcAddress("glDeleteRenderbuffers");
	if(!_funcptr_glDeleteRenderbuffers) ++numFailed;
	_funcptr_glDeleteVertexArrays = (PFNGLDELETEVERTEXARRAYSPROC)IntGetProcAddress("glDeleteVertexArrays");
	if(!_funcptr_glDeleteVertexArrays) ++numFailed;
	_funcptr_glDisablei = (PFNGLDISABLEIPROC)IntGetProcAddress("glDisablei");
	if(!_funcptr_glDisablei) ++numFailed;
	_funcptr_glEnablei = (PFNGLENABLEIPROC)IntGetProcAddress("glEnablei");
	if(!_funcptr_glEnablei) ++numFailed;
	_funcptr_glEndConditionalRender = (PFNGLENDCONDITIONALRENDERPROC)IntGetProcAddress("glEndConditionalRender");
	if(!_funcptr_glEndConditionalRender) ++numFailed;
	_funcptr_glEndTransformFeedback = (PFNGLENDTRANSFORMFEEDBACKPROC)IntGetProcAddress("glEndTransformFeedback");
	if(!_funcptr_glEndTransformFeedback) ++numFailed;
	_funcptr_glFlushMappedBufferRange = (PFNGLFLUSHMAPPEDBUFFERRANGEPROC)IntGetProcAddress("glFlushMappedBufferRange");
	if(!_funcptr_glFlushMappedBufferRange) ++numFailed;
	_funcptr_glFramebufferRenderbuffer = (PFNGLFRAMEBUFFERRENDERBUFFERPROC)IntGetProcAddress("glFramebufferRenderbuffer");
	if(!_funcptr_glFramebufferRenderbuffer) ++numFailed;
	_funcptr_glFramebufferTexture1D = (PFNGLFRAMEBUFFERTEXTURE1DPROC)IntGetProcAddress("glFramebufferTexture1D");
	if(!_funcptr_glFramebufferTexture1D) ++numFailed;
	_funcptr_glFramebufferTexture2D = (PFNGLFRAMEBUFFERTEXTURE2DPROC)IntGetProcAddress("glFramebufferTexture2D");
	if(!_funcptr_glFramebufferTexture2D) ++numFailed;
	_funcptr_glFramebufferTexture3D = (PFNGLFRAMEBUFFERTEXTURE3DPROC)IntGetProcAddress("glFramebufferTexture3D");
	if(!_funcptr_glFramebufferTexture3D) ++numFailed;
	_funcptr_glFramebufferTextureLayer = (PFNGLFRAMEBUFFERTEXTURELAYERPROC)IntGetProcAddress("glFramebufferTextureLayer");
	if(!_funcptr_glFramebufferTextureLayer) ++numFailed;
	_funcptr_glGenFramebuffers = (PFNGLGENFRAMEBUFFERSPROC)IntGetProcAddress("glGenFramebuffers");
	if(!_funcptr_glGenFramebuffers) ++numFailed;
	_funcptr_glGenRenderbuffers = (PFNGLGENRENDERBUFFERSPROC)IntGetProcAddress("glGenRenderbuffers");
	if(!_funcptr_glGenRenderbuffers) ++numFailed;
	_funcptr_glGenVertexArrays = (PFNGLGENVERTEXARRAYSPROC)IntGetProcAddress("glGenVertexArrays");
	if(!_funcptr_glGenVertexArrays) ++numFailed;
	_funcptr_glGenerateMipmap = (PFNGLGENERATEMIPMAPPROC)IntGetProcAddress("glGenerateMipmap");
	if(!_funcptr_glGenerateMipmap) ++numFailed;
	_funcptr_glGetBooleani_v = (PFNGLGETBOOLEANI_VPROC)IntGetProcAddress("glGetBooleani_v");
	if(!_funcptr_glGetBooleani_v) ++numFailed;
	_funcptr_glGetFragDataLocation = (PFNGLGETFRAGDATALOCATIONPROC)IntGetProcAddress("glGetFragDataLocation");
	if(!_funcptr_glGetFragDataLocation) ++numFailed;
	_funcptr_glGetFramebufferAttachmentParameteriv = (PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC)IntGetProcAddress("glGetFramebufferAttachmentParameteriv");
	if(!_funcptr_glGetFramebufferAttachmentParameteriv) ++numFailed;
	_funcptr_glGetIntegeri_v = (PFNGLGETINTEGERI_VPROC)IntGetProcAddress("glGetIntegeri_v");
	if(!_funcptr_glGetIntegeri_v) ++numFailed;
	_funcptr_glGetRenderbufferParameteriv = (PFNGLGETRENDERBUFFERPARAMETERIVPROC)IntGetProcAddress("glGetRenderbufferParameteriv");
	if(!_funcptr_glGetRenderbufferParameteriv) ++numFailed;
	_funcptr_glGetStringi = (PFNGLGETSTRINGIPROC)IntGetProcAddress("glGetStringi");
	if(!_funcptr_glGetStringi) ++numFailed;
	_funcptr_glGetTexParameterIiv = (PFNGLGETTEXPARAMETERIIVPROC)IntGetProcAddress("glGetTexParameterIiv");
	if(!_funcptr_glGetTexParameterIiv) ++numFailed;
	_funcptr_glGetTexParameterIuiv = (PFNGLGETTEXPARAMETERIUIVPROC)IntGetProcAddress("glGetTexParameterIuiv");
	if(!_funcptr_glGetTexParameterIuiv) ++numFailed;
	_funcptr_glGetTransformFeedbackVarying = (PFNGLGETTRANSFORMFEEDBACKVARYINGPROC)IntGetProcAddress("glGetTransformFeedbackVarying");
	if(!_funcptr_glGetTransformFeedbackVarying) ++numFailed;
	_funcptr_glGetUniformuiv = (PFNGLGETUNIFORMUIVPROC)IntGetProcAddress("glGetUniformuiv");
	if(!_funcptr_glGetUniformuiv) ++numFailed;
	_funcptr_glGetVertexAttribIiv = (PFNGLGETVERTEXATTRIBIIVPROC)IntGetProcAddress("glGetVertexAttribIiv");
	if(!_funcptr_glGetVertexAttribIiv) ++numFailed;
	_funcptr_glGetVertexAttribIuiv = (PFNGLGETVERTEXATTRIBIUIVPROC)IntGetProcAddress("glGetVertexAttribIuiv");
	if(!_funcptr_glGetVertexAttribIuiv) ++numFailed;
	_funcptr_glIsEnabledi = (PFNGLISENABLEDIPROC)IntGetProcAddress("glIsEnabledi");
	if(!_funcptr_glIsEnabledi) ++numFailed;
	_funcptr_glIsFramebuffer = (PFNGLISFRAMEBUFFERPROC)IntGetProcAddress("glIsFramebuffer");
	if(!_funcptr_glIsFramebuffer) ++numFailed;
	_funcptr_glIsRenderbuffer = (PFNGLISRENDERBUFFERPROC)IntGetProcAddress("glIsRenderbuffer");
	if(!_funcptr_glIsRenderbuffer) ++numFailed;
	_funcptr_glIsVertexArray = (PFNGLISVERTEXARRAYPROC)IntGetProcAddress("glIsVertexArray");
	if(!_funcptr_glIsVertexArray) ++numFailed;
	_funcptr_glMapBufferRange = (PFNGLMAPBUFFERRANGEPROC)IntGetProcAddress("glMapBufferRange");
	if(!_funcptr_glMapBufferRange) ++numFailed;
	_funcptr_glRenderbufferStorage = (PFNGLRENDERBUFFERSTORAGEPROC)IntGetProcAddress("glRenderbufferStorage");
	if(!_funcptr_glRenderbufferStorage) ++numFailed;
	_funcptr_glRenderbufferStorageMultisample = (PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC)IntGetProcAddress("glRenderbufferStorageMultisample");
	if(!_funcptr_glRenderbufferStorageMultisample) ++numFailed;
	_funcptr_glTexParameterIiv = (PFNGLTEXPARAMETERIIVPROC)IntGetProcAddress("glTexParameterIiv");
	if(!_funcptr_glTexParameterIiv) ++numFailed;
	_funcptr_glTexParameterIuiv = (PFNGLTEXPARAMETERIUIVPROC)IntGetProcAddress("glTexParameterIuiv");
	if(!_funcptr_glTexParameterIuiv) ++numFailed;
	_funcptr_glTransformFeedbackVaryings = (PFNGLTRANSFORMFEEDBACKVARYINGSPROC)IntGetProcAddress("glTransformFeedbackVaryings");
	if(!_funcptr_glTransformFeedbackVaryings) ++numFailed;
	_funcptr_glUniform1ui = (PFNGLUNIFORM1UIPROC)IntGetProcAddress("glUniform1ui");
	if(!_funcptr_glUniform1ui) ++numFailed;
	_funcptr_glUniform1uiv = (PFNGLUNIFORM1UIVPROC)IntGetProcAddress("glUniform1uiv");
	if(!_funcptr_glUniform1uiv) ++numFailed;
	_funcptr_glUniform2ui = (PFNGLUNIFORM2UIPROC)IntGetProcAddress("glUniform2ui");
	if(!_funcptr_glUniform2ui) ++numFailed;
	_funcptr_glUniform2uiv = (PFNGLUNIFORM2UIVPROC)IntGetProcAddress("glUniform2uiv");
	if(!_funcptr_glUniform2uiv) ++numFailed;
	_funcptr_glUniform3ui = (PFNGLUNIFORM3UIPROC)IntGetProcAddress("glUniform3ui");
	if(!_funcptr_glUniform3ui) ++numFailed;
	_funcptr_glUniform3uiv = (PFNGLUNIFORM3UIVPROC)IntGetProcAddress("glUniform3uiv");
	if(!_funcptr_glUniform3uiv) ++numFailed;
	_funcptr_glUniform4ui = (PFNGLUNIFORM4UIPROC)IntGetProcAddress("glUniform4ui");
	if(!_funcptr_glUniform4ui) ++numFailed;
	_funcptr_glUniform4uiv = (PFNGLUNIFORM4UIVPROC)IntGetProcAddress("glUniform4uiv");
	if(!_funcptr_glUniform4uiv) ++numFailed;
	_funcptr_glVertexAttribI1i = (PFNGLVERTEXATTRIBI1IPROC)IntGetProcAddress("glVertexAttribI1i");
	if(!_funcptr_glVertexAttribI1i) ++numFailed;
	_funcptr_glVertexAttribI1iv = (PFNGLVERTEXATTRIBI1IVPROC)IntGetProcAddress("glVertexAttribI1iv");
	if(!_funcptr_glVertexAttribI1iv) ++numFailed;
	_funcptr_glVertexAttribI1ui = (PFNGLVERTEXATTRIBI1UIPROC)IntGetProcAddress("glVertexAttribI1ui");
	if(!_funcptr_glVertexAttribI1ui) ++numFailed;
	_funcptr_glVertexAttribI1uiv = (PFNGLVERTEXATTRIBI1UIVPROC)IntGetProcAddress("glVertexAttribI1uiv");
	if(!_funcptr_glVertexAttribI1uiv) ++numFailed;
	_funcptr_glVertexAttribI2i = (PFNGLVERTEXATTRIBI2IPROC)IntGetProcAddress("glVertexAttribI2i");
	if(!_funcptr_glVertexAttribI2i) ++numFailed;
	_funcptr_glVertexAttribI2iv = (PFNGLVERTEXATTRIBI2IVPROC)IntGetProcAddress("glVertexAttribI2iv");
	if(!_funcptr_glVertexAttribI2iv) ++numFailed;
	_funcptr_glVertexAttribI2ui = (PFNGLVERTEXATTRIBI2UIPROC)IntGetProcAddress("glVertexAttribI2ui");
	if(!_funcptr_glVertexAttribI2ui) ++numFailed;
	_funcptr_glVertexAttribI2uiv = (PFNGLVERTEXATTRIBI2UIVPROC)IntGetProcAddress("glVertexAttribI2uiv");
	if(!_funcptr_glVertexAttribI2uiv) ++numFailed;
	_funcptr_glVertexAttribI3i = (PFNGLVERTEXATTRIBI3IPROC)IntGetProcAddress("glVertexAttribI3i");
	if(!_funcptr_glVertexAttribI3i) ++numFailed;
	_funcptr_glVertexAttribI3iv = (PFNGLVERTEXATTRIBI3IVPROC)IntGetProcAddress("glVertexAttribI3iv");
	if(!_funcptr_glVertexAttribI3iv) ++numFailed;
	_funcptr_glVertexAttribI3ui = (PFNGLVERTEXATTRIBI3UIPROC)IntGetProcAddress("glVertexAttribI3ui");
	if(!_funcptr_glVertexAttribI3ui) ++numFailed;
	_funcptr_glVertexAttribI3uiv = (PFNGLVERTEXATTRIBI3UIVPROC)IntGetProcAddress("glVertexAttribI3uiv");
	if(!_funcptr_glVertexAttribI3uiv) ++numFailed;
	_funcptr_glVertexAttribI4bv = (PFNGLVERTEXATTRIBI4BVPROC)IntGetProcAddress("glVertexAttribI4bv");
	if(!_funcptr_glVertexAttribI4bv) ++numFailed;
	_funcptr_glVertexAttribI4i = (PFNGLVERTEXATTRIBI4IPROC)IntGetProcAddress("glVertexAttribI4i");
	if(!_funcptr_glVertexAttribI4i) ++numFailed;
	_funcptr_glVertexAttribI4iv = (PFNGLVERTEXATTRIBI4IVPROC)IntGetProcAddress("glVertexAttribI4iv");
	if(!_funcptr_glVertexAttribI4iv) ++numFailed;
	_funcptr_glVertexAttribI4sv = (PFNGLVERTEXATTRIBI4SVPROC)IntGetProcAddress("glVertexAttribI4sv");
	if(!_funcptr_glVertexAttribI4sv) ++numFailed;
	_funcptr_glVertexAttribI4ubv = (PFNGLVERTEXATTRIBI4UBVPROC)IntGetProcAddress("glVertexAttribI4ubv");
	if(!_funcptr_glVertexAttribI4ubv) ++numFailed;
	_funcptr_glVertexAttribI4ui = (PFNGLVERTEXATTRIBI4UIPROC)IntGetProcAddress("glVertexAttribI4ui");
	if(!_funcptr_glVertexAttribI4ui) ++numFailed;
	_funcptr_glVertexAttribI4uiv = (PFNGLVERTEXATTRIBI4UIVPROC)IntGetProcAddress("glVertexAttribI4uiv");
	if(!_funcptr_glVertexAttribI4uiv) ++numFailed;
	_funcptr_glVertexAttribI4usv = (PFNGLVERTEXATTRIBI4USVPROC)IntGetProcAddress("glVertexAttribI4usv");
	if(!_funcptr_glVertexAttribI4usv) ++numFailed;
	_funcptr_glVertexAttribIPointer = (PFNGLVERTEXATTRIBIPOINTERPROC)IntGetProcAddress("glVertexAttribIPointer");
	if(!_funcptr_glVertexAttribIPointer) ++numFailed;
	return numFailed;
}