#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */
typedef  struct TYPE_4__   TYPE_2__ ;
typedef  struct TYPE_3__   TYPE_1__ ;

/* Type definitions */
struct TYPE_3__ {int /*<<< orphan*/ * publicKeys; } ;
struct TYPE_4__ {TYPE_1__ win32; } ;

/* Variables and functions */
 int /*<<< orphan*/  GLFW_KEY_0 ; 
 int /*<<< orphan*/  GLFW_KEY_1 ; 
 int /*<<< orphan*/  GLFW_KEY_2 ; 
 int /*<<< orphan*/  GLFW_KEY_3 ; 
 int /*<<< orphan*/  GLFW_KEY_4 ; 
 int /*<<< orphan*/  GLFW_KEY_5 ; 
 int /*<<< orphan*/  GLFW_KEY_6 ; 
 int /*<<< orphan*/  GLFW_KEY_7 ; 
 int /*<<< orphan*/  GLFW_KEY_8 ; 
 int /*<<< orphan*/  GLFW_KEY_9 ; 
 int /*<<< orphan*/  GLFW_KEY_A ; 
 int /*<<< orphan*/  GLFW_KEY_APOSTROPHE ; 
 int /*<<< orphan*/  GLFW_KEY_B ; 
 int /*<<< orphan*/  GLFW_KEY_BACKSLASH ; 
 int /*<<< orphan*/  GLFW_KEY_BACKSPACE ; 
 int /*<<< orphan*/  GLFW_KEY_C ; 
 int /*<<< orphan*/  GLFW_KEY_CAPS_LOCK ; 
 int /*<<< orphan*/  GLFW_KEY_COMMA ; 
 int /*<<< orphan*/  GLFW_KEY_D ; 
 int /*<<< orphan*/  GLFW_KEY_DELETE ; 
 int /*<<< orphan*/  GLFW_KEY_DOWN ; 
 int /*<<< orphan*/  GLFW_KEY_E ; 
 int /*<<< orphan*/  GLFW_KEY_END ; 
 int /*<<< orphan*/  GLFW_KEY_ENTER ; 
 int /*<<< orphan*/  GLFW_KEY_EQUAL ; 
 int /*<<< orphan*/  GLFW_KEY_ESCAPE ; 
 int /*<<< orphan*/  GLFW_KEY_F ; 
 int /*<<< orphan*/  GLFW_KEY_F1 ; 
 int /*<<< orphan*/  GLFW_KEY_F10 ; 
 int /*<<< orphan*/  GLFW_KEY_F11 ; 
 int /*<<< orphan*/  GLFW_KEY_F12 ; 
 int /*<<< orphan*/  GLFW_KEY_F13 ; 
 int /*<<< orphan*/  GLFW_KEY_F14 ; 
 int /*<<< orphan*/  GLFW_KEY_F15 ; 
 int /*<<< orphan*/  GLFW_KEY_F16 ; 
 int /*<<< orphan*/  GLFW_KEY_F17 ; 
 int /*<<< orphan*/  GLFW_KEY_F18 ; 
 int /*<<< orphan*/  GLFW_KEY_F19 ; 
 int /*<<< orphan*/  GLFW_KEY_F2 ; 
 int /*<<< orphan*/  GLFW_KEY_F20 ; 
 int /*<<< orphan*/  GLFW_KEY_F21 ; 
 int /*<<< orphan*/  GLFW_KEY_F22 ; 
 int /*<<< orphan*/  GLFW_KEY_F23 ; 
 int /*<<< orphan*/  GLFW_KEY_F24 ; 
 int /*<<< orphan*/  GLFW_KEY_F3 ; 
 int /*<<< orphan*/  GLFW_KEY_F4 ; 
 int /*<<< orphan*/  GLFW_KEY_F5 ; 
 int /*<<< orphan*/  GLFW_KEY_F6 ; 
 int /*<<< orphan*/  GLFW_KEY_F7 ; 
 int /*<<< orphan*/  GLFW_KEY_F8 ; 
 int /*<<< orphan*/  GLFW_KEY_F9 ; 
 int /*<<< orphan*/  GLFW_KEY_G ; 
 int /*<<< orphan*/  GLFW_KEY_GRAVE_ACCENT ; 
 int /*<<< orphan*/  GLFW_KEY_H ; 
 int /*<<< orphan*/  GLFW_KEY_HOME ; 
 int /*<<< orphan*/  GLFW_KEY_I ; 
 int /*<<< orphan*/  GLFW_KEY_INSERT ; 
 int /*<<< orphan*/  GLFW_KEY_J ; 
 int /*<<< orphan*/  GLFW_KEY_K ; 
 int /*<<< orphan*/  GLFW_KEY_KP_0 ; 
 int /*<<< orphan*/  GLFW_KEY_KP_1 ; 
 int /*<<< orphan*/  GLFW_KEY_KP_2 ; 
 int /*<<< orphan*/  GLFW_KEY_KP_3 ; 
 int /*<<< orphan*/  GLFW_KEY_KP_4 ; 
 int /*<<< orphan*/  GLFW_KEY_KP_5 ; 
 int /*<<< orphan*/  GLFW_KEY_KP_6 ; 
 int /*<<< orphan*/  GLFW_KEY_KP_7 ; 
 int /*<<< orphan*/  GLFW_KEY_KP_8 ; 
 int /*<<< orphan*/  GLFW_KEY_KP_9 ; 
 int /*<<< orphan*/  GLFW_KEY_KP_ADD ; 
 int /*<<< orphan*/  GLFW_KEY_KP_DECIMAL ; 
 int /*<<< orphan*/  GLFW_KEY_KP_DIVIDE ; 
 int /*<<< orphan*/  GLFW_KEY_KP_ENTER ; 
 int /*<<< orphan*/  GLFW_KEY_KP_MULTIPLY ; 
 int /*<<< orphan*/  GLFW_KEY_KP_SUBTRACT ; 
 int /*<<< orphan*/  GLFW_KEY_L ; 
 int /*<<< orphan*/  GLFW_KEY_LEFT ; 
 int /*<<< orphan*/  GLFW_KEY_LEFT_ALT ; 
 int /*<<< orphan*/  GLFW_KEY_LEFT_BRACKET ; 
 int /*<<< orphan*/  GLFW_KEY_LEFT_CONTROL ; 
 int /*<<< orphan*/  GLFW_KEY_LEFT_SHIFT ; 
 int /*<<< orphan*/  GLFW_KEY_LEFT_SUPER ; 
 int /*<<< orphan*/  GLFW_KEY_M ; 
 int /*<<< orphan*/  GLFW_KEY_MENU ; 
 int /*<<< orphan*/  GLFW_KEY_MINUS ; 
 int /*<<< orphan*/  GLFW_KEY_N ; 
 int /*<<< orphan*/  GLFW_KEY_NUM_LOCK ; 
 int /*<<< orphan*/  GLFW_KEY_O ; 
 int /*<<< orphan*/  GLFW_KEY_P ; 
 int /*<<< orphan*/  GLFW_KEY_PAGE_DOWN ; 
 int /*<<< orphan*/  GLFW_KEY_PAGE_UP ; 
 int /*<<< orphan*/  GLFW_KEY_PAUSE ; 
 int /*<<< orphan*/  GLFW_KEY_PERIOD ; 
 int /*<<< orphan*/  GLFW_KEY_PRINT_SCREEN ; 
 int /*<<< orphan*/  GLFW_KEY_Q ; 
 int /*<<< orphan*/  GLFW_KEY_R ; 
 int /*<<< orphan*/  GLFW_KEY_RIGHT ; 
 int /*<<< orphan*/  GLFW_KEY_RIGHT_ALT ; 
 int /*<<< orphan*/  GLFW_KEY_RIGHT_BRACKET ; 
 int /*<<< orphan*/  GLFW_KEY_RIGHT_CONTROL ; 
 int /*<<< orphan*/  GLFW_KEY_RIGHT_SHIFT ; 
 int /*<<< orphan*/  GLFW_KEY_RIGHT_SUPER ; 
 int /*<<< orphan*/  GLFW_KEY_S ; 
 int /*<<< orphan*/  GLFW_KEY_SCROLL_LOCK ; 
 int /*<<< orphan*/  GLFW_KEY_SEMICOLON ; 
 int /*<<< orphan*/  GLFW_KEY_SLASH ; 
 int /*<<< orphan*/  GLFW_KEY_SPACE ; 
 int /*<<< orphan*/  GLFW_KEY_T ; 
 int /*<<< orphan*/  GLFW_KEY_TAB ; 
 int /*<<< orphan*/  GLFW_KEY_U ; 
 int /*<<< orphan*/  GLFW_KEY_UP ; 
 int /*<<< orphan*/  GLFW_KEY_V ; 
 int /*<<< orphan*/  GLFW_KEY_W ; 
 int /*<<< orphan*/  GLFW_KEY_WORLD_2 ; 
 int /*<<< orphan*/  GLFW_KEY_X ; 
 int /*<<< orphan*/  GLFW_KEY_Y ; 
 int /*<<< orphan*/  GLFW_KEY_Z ; 
 TYPE_2__ _glfw ; 
 int /*<<< orphan*/  memset (int /*<<< orphan*/ *,int,int) ; 

__attribute__((used)) static void createKeyTables(void)
{
    memset(_glfw.win32.publicKeys, -1, sizeof(_glfw.win32.publicKeys));

    _glfw.win32.publicKeys[0x00B] = GLFW_KEY_0;
    _glfw.win32.publicKeys[0x002] = GLFW_KEY_1;
    _glfw.win32.publicKeys[0x003] = GLFW_KEY_2;
    _glfw.win32.publicKeys[0x004] = GLFW_KEY_3;
    _glfw.win32.publicKeys[0x005] = GLFW_KEY_4;
    _glfw.win32.publicKeys[0x006] = GLFW_KEY_5;
    _glfw.win32.publicKeys[0x007] = GLFW_KEY_6;
    _glfw.win32.publicKeys[0x008] = GLFW_KEY_7;
    _glfw.win32.publicKeys[0x009] = GLFW_KEY_8;
    _glfw.win32.publicKeys[0x00A] = GLFW_KEY_9;
    _glfw.win32.publicKeys[0x01E] = GLFW_KEY_A;
    _glfw.win32.publicKeys[0x030] = GLFW_KEY_B;
    _glfw.win32.publicKeys[0x02E] = GLFW_KEY_C;
    _glfw.win32.publicKeys[0x020] = GLFW_KEY_D;
    _glfw.win32.publicKeys[0x012] = GLFW_KEY_E;
    _glfw.win32.publicKeys[0x021] = GLFW_KEY_F;
    _glfw.win32.publicKeys[0x022] = GLFW_KEY_G;
    _glfw.win32.publicKeys[0x023] = GLFW_KEY_H;
    _glfw.win32.publicKeys[0x017] = GLFW_KEY_I;
    _glfw.win32.publicKeys[0x024] = GLFW_KEY_J;
    _glfw.win32.publicKeys[0x025] = GLFW_KEY_K;
    _glfw.win32.publicKeys[0x026] = GLFW_KEY_L;
    _glfw.win32.publicKeys[0x032] = GLFW_KEY_M;
    _glfw.win32.publicKeys[0x031] = GLFW_KEY_N;
    _glfw.win32.publicKeys[0x018] = GLFW_KEY_O;
    _glfw.win32.publicKeys[0x019] = GLFW_KEY_P;
    _glfw.win32.publicKeys[0x010] = GLFW_KEY_Q;
    _glfw.win32.publicKeys[0x013] = GLFW_KEY_R;
    _glfw.win32.publicKeys[0x01F] = GLFW_KEY_S;
    _glfw.win32.publicKeys[0x014] = GLFW_KEY_T;
    _glfw.win32.publicKeys[0x016] = GLFW_KEY_U;
    _glfw.win32.publicKeys[0x02F] = GLFW_KEY_V;
    _glfw.win32.publicKeys[0x011] = GLFW_KEY_W;
    _glfw.win32.publicKeys[0x02D] = GLFW_KEY_X;
    _glfw.win32.publicKeys[0x015] = GLFW_KEY_Y;
    _glfw.win32.publicKeys[0x02C] = GLFW_KEY_Z;

    _glfw.win32.publicKeys[0x028] = GLFW_KEY_APOSTROPHE;
    _glfw.win32.publicKeys[0x02B] = GLFW_KEY_BACKSLASH;
    _glfw.win32.publicKeys[0x033] = GLFW_KEY_COMMA;
    _glfw.win32.publicKeys[0x00D] = GLFW_KEY_EQUAL;
    _glfw.win32.publicKeys[0x029] = GLFW_KEY_GRAVE_ACCENT;
    _glfw.win32.publicKeys[0x01A] = GLFW_KEY_LEFT_BRACKET;
    _glfw.win32.publicKeys[0x00C] = GLFW_KEY_MINUS;
    _glfw.win32.publicKeys[0x034] = GLFW_KEY_PERIOD;
    _glfw.win32.publicKeys[0x01B] = GLFW_KEY_RIGHT_BRACKET;
    _glfw.win32.publicKeys[0x027] = GLFW_KEY_SEMICOLON;
    _glfw.win32.publicKeys[0x035] = GLFW_KEY_SLASH;
    _glfw.win32.publicKeys[0x056] = GLFW_KEY_WORLD_2;

    _glfw.win32.publicKeys[0x00E] = GLFW_KEY_BACKSPACE;
    _glfw.win32.publicKeys[0x153] = GLFW_KEY_DELETE;
    _glfw.win32.publicKeys[0x14F] = GLFW_KEY_END;
    _glfw.win32.publicKeys[0x01C] = GLFW_KEY_ENTER;
    _glfw.win32.publicKeys[0x001] = GLFW_KEY_ESCAPE;
    _glfw.win32.publicKeys[0x147] = GLFW_KEY_HOME;
    _glfw.win32.publicKeys[0x152] = GLFW_KEY_INSERT;
    _glfw.win32.publicKeys[0x15D] = GLFW_KEY_MENU;
    _glfw.win32.publicKeys[0x151] = GLFW_KEY_PAGE_DOWN;
    _glfw.win32.publicKeys[0x149] = GLFW_KEY_PAGE_UP;
    _glfw.win32.publicKeys[0x045] = GLFW_KEY_PAUSE;
    _glfw.win32.publicKeys[0x039] = GLFW_KEY_SPACE;
    _glfw.win32.publicKeys[0x00F] = GLFW_KEY_TAB;
    _glfw.win32.publicKeys[0x03A] = GLFW_KEY_CAPS_LOCK;
    _glfw.win32.publicKeys[0x145] = GLFW_KEY_NUM_LOCK;
    _glfw.win32.publicKeys[0x046] = GLFW_KEY_SCROLL_LOCK;
    _glfw.win32.publicKeys[0x03B] = GLFW_KEY_F1;
    _glfw.win32.publicKeys[0x03C] = GLFW_KEY_F2;
    _glfw.win32.publicKeys[0x03D] = GLFW_KEY_F3;
    _glfw.win32.publicKeys[0x03E] = GLFW_KEY_F4;
    _glfw.win32.publicKeys[0x03F] = GLFW_KEY_F5;
    _glfw.win32.publicKeys[0x040] = GLFW_KEY_F6;
    _glfw.win32.publicKeys[0x041] = GLFW_KEY_F7;
    _glfw.win32.publicKeys[0x042] = GLFW_KEY_F8;
    _glfw.win32.publicKeys[0x043] = GLFW_KEY_F9;
    _glfw.win32.publicKeys[0x044] = GLFW_KEY_F10;
    _glfw.win32.publicKeys[0x057] = GLFW_KEY_F11;
    _glfw.win32.publicKeys[0x058] = GLFW_KEY_F12;
    _glfw.win32.publicKeys[0x064] = GLFW_KEY_F13;
    _glfw.win32.publicKeys[0x065] = GLFW_KEY_F14;
    _glfw.win32.publicKeys[0x066] = GLFW_KEY_F15;
    _glfw.win32.publicKeys[0x067] = GLFW_KEY_F16;
    _glfw.win32.publicKeys[0x068] = GLFW_KEY_F17;
    _glfw.win32.publicKeys[0x069] = GLFW_KEY_F18;
    _glfw.win32.publicKeys[0x06A] = GLFW_KEY_F19;
    _glfw.win32.publicKeys[0x06B] = GLFW_KEY_F20;
    _glfw.win32.publicKeys[0x06C] = GLFW_KEY_F21;
    _glfw.win32.publicKeys[0x06D] = GLFW_KEY_F22;
    _glfw.win32.publicKeys[0x06E] = GLFW_KEY_F23;
    _glfw.win32.publicKeys[0x076] = GLFW_KEY_F24;
    _glfw.win32.publicKeys[0x038] = GLFW_KEY_LEFT_ALT;
    _glfw.win32.publicKeys[0x01D] = GLFW_KEY_LEFT_CONTROL;
    _glfw.win32.publicKeys[0x02A] = GLFW_KEY_LEFT_SHIFT;
    _glfw.win32.publicKeys[0x15B] = GLFW_KEY_LEFT_SUPER;
    _glfw.win32.publicKeys[0x137] = GLFW_KEY_PRINT_SCREEN;
    _glfw.win32.publicKeys[0x138] = GLFW_KEY_RIGHT_ALT;
    _glfw.win32.publicKeys[0x11D] = GLFW_KEY_RIGHT_CONTROL;
    _glfw.win32.publicKeys[0x036] = GLFW_KEY_RIGHT_SHIFT;
    _glfw.win32.publicKeys[0x15C] = GLFW_KEY_RIGHT_SUPER;
    _glfw.win32.publicKeys[0x150] = GLFW_KEY_DOWN;
    _glfw.win32.publicKeys[0x14B] = GLFW_KEY_LEFT;
    _glfw.win32.publicKeys[0x14D] = GLFW_KEY_RIGHT;
    _glfw.win32.publicKeys[0x148] = GLFW_KEY_UP;

    _glfw.win32.publicKeys[0x052] = GLFW_KEY_KP_0;
    _glfw.win32.publicKeys[0x04F] = GLFW_KEY_KP_1;
    _glfw.win32.publicKeys[0x050] = GLFW_KEY_KP_2;
    _glfw.win32.publicKeys[0x051] = GLFW_KEY_KP_3;
    _glfw.win32.publicKeys[0x04B] = GLFW_KEY_KP_4;
    _glfw.win32.publicKeys[0x04C] = GLFW_KEY_KP_5;
    _glfw.win32.publicKeys[0x04D] = GLFW_KEY_KP_6;
    _glfw.win32.publicKeys[0x047] = GLFW_KEY_KP_7;
    _glfw.win32.publicKeys[0x048] = GLFW_KEY_KP_8;
    _glfw.win32.publicKeys[0x049] = GLFW_KEY_KP_9;
    _glfw.win32.publicKeys[0x04E] = GLFW_KEY_KP_ADD;
    _glfw.win32.publicKeys[0x053] = GLFW_KEY_KP_DECIMAL;
    _glfw.win32.publicKeys[0x135] = GLFW_KEY_KP_DIVIDE;
    _glfw.win32.publicKeys[0x11C] = GLFW_KEY_KP_ENTER;
    _glfw.win32.publicKeys[0x037] = GLFW_KEY_KP_MULTIPLY;
    _glfw.win32.publicKeys[0x04A] = GLFW_KEY_KP_SUBTRACT;
}