#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  scalar_t__ u8 ;

/* Variables and functions */
#define  ATA_CMD_CFA_ERASE 218 
#define  ATA_CMD_CFA_REQ_EXT_ERR 217 
#define  ATA_CMD_CFA_TRANS_SECT 216 
#define  ATA_CMD_CFA_WRITE_MULT_NE 215 
#define  ATA_CMD_CFA_WRITE_NE 214 
#define  ATA_CMD_CHK_MED_CRD_TYP 213 
#define  ATA_CMD_CHK_POWER 212 
#define  ATA_CMD_CONFIG_STREAM 211 
#define  ATA_CMD_CONF_OVERLAY 210 
#define  ATA_CMD_DEV_RESET 209 
#define  ATA_CMD_DOWNLOAD_MICRO 208 
#define  ATA_CMD_DOWNLOAD_MICRO_DMA 207 
#define  ATA_CMD_DSM 206 
#define  ATA_CMD_EDD 205 
#define  ATA_CMD_FLUSH 204 
#define  ATA_CMD_FLUSH_EXT 203 
#define  ATA_CMD_FPDMA_READ 202 
#define  ATA_CMD_FPDMA_RECV 201 
#define  ATA_CMD_FPDMA_SEND 200 
#define  ATA_CMD_FPDMA_WRITE 199 
#define  ATA_CMD_IDLE 198 
#define  ATA_CMD_IDLEIMMEDIATE 197 
#define  ATA_CMD_ID_ATA 196 
#define  ATA_CMD_ID_ATAPI 195 
#define  ATA_CMD_INIT_DEV_PARAMS 194 
#define  ATA_CMD_MEDIA_LOCK 193 
#define  ATA_CMD_MEDIA_UNLOCK 192 
#define  ATA_CMD_NOP 191 
#define  ATA_CMD_PIO_READ 190 
#define  ATA_CMD_PIO_READ_EXT 189 
#define  ATA_CMD_PIO_WRITE 188 
#define  ATA_CMD_PIO_WRITE_EXT 187 
#define  ATA_CMD_PMP_READ 186 
#define  ATA_CMD_PMP_READ_DMA 185 
#define  ATA_CMD_PMP_WRITE 184 
#define  ATA_CMD_PMP_WRITE_DMA 183 
#define  ATA_CMD_READ 182 
#define  ATA_CMD_READ_EXT 181 
#define  ATA_CMD_READ_LOG_DMA_EXT 180 
#define  ATA_CMD_READ_LOG_EXT 179 
#define  ATA_CMD_READ_LONG 178 
#define  ATA_CMD_READ_LONG_ONCE 177 
#define  ATA_CMD_READ_MULTI 176 
#define  ATA_CMD_READ_MULTI_EXT 175 
#define  ATA_CMD_READ_NATIVE_MAX 174 
#define  ATA_CMD_READ_NATIVE_MAX_EXT 173 
#define  ATA_CMD_READ_QUEUED 172 
#define  ATA_CMD_READ_STREAM_DMA_EXT 171 
#define  ATA_CMD_READ_STREAM_EXT 170 
#define  ATA_CMD_REQ_SENSE_DATA 169 
#define  ATA_CMD_RESTORE 168 
#define  ATA_CMD_SANITIZE_DEVICE 167 
#define  ATA_CMD_SEC_DISABLE_PASS 166 
#define  ATA_CMD_SEC_ERASE_PREP 165 
#define  ATA_CMD_SEC_ERASE_UNIT 164 
#define  ATA_CMD_SEC_FREEZE_LOCK 163 
#define  ATA_CMD_SEC_SET_PASS 162 
#define  ATA_CMD_SEC_UNLOCK 161 
#define  ATA_CMD_SERVICE 160 
#define  ATA_CMD_SET_FEATURES 159 
#define  ATA_CMD_SET_MAX 158 
#define  ATA_CMD_SET_MAX_EXT 157 
#define  ATA_CMD_SET_MULTI 156 
#define  ATA_CMD_SLEEP 155 
#define  ATA_CMD_SMART 154 
#define  ATA_CMD_STANDBY 153 
#define  ATA_CMD_STANDBYNOW1 152 
#define  ATA_CMD_TRUSTED_NONDATA 151 
#define  ATA_CMD_TRUSTED_RCV 150 
#define  ATA_CMD_TRUSTED_RCV_DMA 149 
#define  ATA_CMD_TRUSTED_SND 148 
#define  ATA_CMD_TRUSTED_SND_DMA 147 
#define  ATA_CMD_VERIFY 146 
#define  ATA_CMD_VERIFY_EXT 145 
#define  ATA_CMD_WRITE 144 
#define  ATA_CMD_WRITE_EXT 143 
#define  ATA_CMD_WRITE_FUA_EXT 142 
#define  ATA_CMD_WRITE_LOG_DMA_EXT 141 
#define  ATA_CMD_WRITE_LOG_EXT 140 
#define  ATA_CMD_WRITE_LONG 139 
#define  ATA_CMD_WRITE_LONG_ONCE 138 
#define  ATA_CMD_WRITE_MULTI 137 
#define  ATA_CMD_WRITE_MULTI_EXT 136 
#define  ATA_CMD_WRITE_MULTI_FUA_EXT 135 
#define  ATA_CMD_WRITE_QUEUED 134 
#define  ATA_CMD_WRITE_QUEUED_FUA_EXT 133 
#define  ATA_CMD_WRITE_STREAM_DMA_EXT 132 
#define  ATA_CMD_WRITE_STREAM_EXT 131 
#define  ATA_CMD_WRITE_UNCORR_EXT 130 
#define  ATA_CMD_ZAC_MGMT_IN 129 
#define  ATA_CMD_ZAC_MGMT_OUT 128 

const char *ata_get_cmd_descript(u8 command)
{
#ifdef CONFIG_ATA_VERBOSE_ERROR
	static const struct
	{
		u8 command;
		const char *text;
	} cmd_descr[] = {
		{ ATA_CMD_DEV_RESET,		"DEVICE RESET" },
		{ ATA_CMD_CHK_POWER,		"CHECK POWER MODE" },
		{ ATA_CMD_STANDBY,		"STANDBY" },
		{ ATA_CMD_IDLE,			"IDLE" },
		{ ATA_CMD_EDD,			"EXECUTE DEVICE DIAGNOSTIC" },
		{ ATA_CMD_DOWNLOAD_MICRO,	"DOWNLOAD MICROCODE" },
		{ ATA_CMD_DOWNLOAD_MICRO_DMA,	"DOWNLOAD MICROCODE DMA" },
		{ ATA_CMD_NOP,			"NOP" },
		{ ATA_CMD_FLUSH,		"FLUSH CACHE" },
		{ ATA_CMD_FLUSH_EXT,		"FLUSH CACHE EXT" },
		{ ATA_CMD_ID_ATA,		"IDENTIFY DEVICE" },
		{ ATA_CMD_ID_ATAPI,		"IDENTIFY PACKET DEVICE" },
		{ ATA_CMD_SERVICE,		"SERVICE" },
		{ ATA_CMD_READ,			"READ DMA" },
		{ ATA_CMD_READ_EXT,		"READ DMA EXT" },
		{ ATA_CMD_READ_QUEUED,		"READ DMA QUEUED" },
		{ ATA_CMD_READ_STREAM_EXT,	"READ STREAM EXT" },
		{ ATA_CMD_READ_STREAM_DMA_EXT,  "READ STREAM DMA EXT" },
		{ ATA_CMD_WRITE,		"WRITE DMA" },
		{ ATA_CMD_WRITE_EXT,		"WRITE DMA EXT" },
		{ ATA_CMD_WRITE_QUEUED,		"WRITE DMA QUEUED EXT" },
		{ ATA_CMD_WRITE_STREAM_EXT,	"WRITE STREAM EXT" },
		{ ATA_CMD_WRITE_STREAM_DMA_EXT, "WRITE STREAM DMA EXT" },
		{ ATA_CMD_WRITE_FUA_EXT,	"WRITE DMA FUA EXT" },
		{ ATA_CMD_WRITE_QUEUED_FUA_EXT, "WRITE DMA QUEUED FUA EXT" },
		{ ATA_CMD_FPDMA_READ,		"READ FPDMA QUEUED" },
		{ ATA_CMD_FPDMA_WRITE,		"WRITE FPDMA QUEUED" },
		{ ATA_CMD_FPDMA_SEND,		"SEND FPDMA QUEUED" },
		{ ATA_CMD_FPDMA_RECV,		"RECEIVE FPDMA QUEUED" },
		{ ATA_CMD_PIO_READ,		"READ SECTOR(S)" },
		{ ATA_CMD_PIO_READ_EXT,		"READ SECTOR(S) EXT" },
		{ ATA_CMD_PIO_WRITE,		"WRITE SECTOR(S)" },
		{ ATA_CMD_PIO_WRITE_EXT,	"WRITE SECTOR(S) EXT" },
		{ ATA_CMD_READ_MULTI,		"READ MULTIPLE" },
		{ ATA_CMD_READ_MULTI_EXT,	"READ MULTIPLE EXT" },
		{ ATA_CMD_WRITE_MULTI,		"WRITE MULTIPLE" },
		{ ATA_CMD_WRITE_MULTI_EXT,	"WRITE MULTIPLE EXT" },
		{ ATA_CMD_WRITE_MULTI_FUA_EXT,	"WRITE MULTIPLE FUA EXT" },
		{ ATA_CMD_SET_FEATURES,		"SET FEATURES" },
		{ ATA_CMD_SET_MULTI,		"SET MULTIPLE MODE" },
		{ ATA_CMD_VERIFY,		"READ VERIFY SECTOR(S)" },
		{ ATA_CMD_VERIFY_EXT,		"READ VERIFY SECTOR(S) EXT" },
		{ ATA_CMD_WRITE_UNCORR_EXT,	"WRITE UNCORRECTABLE EXT" },
		{ ATA_CMD_STANDBYNOW1,		"STANDBY IMMEDIATE" },
		{ ATA_CMD_IDLEIMMEDIATE,	"IDLE IMMEDIATE" },
		{ ATA_CMD_SLEEP,		"SLEEP" },
		{ ATA_CMD_INIT_DEV_PARAMS,	"INITIALIZE DEVICE PARAMETERS" },
		{ ATA_CMD_READ_NATIVE_MAX,	"READ NATIVE MAX ADDRESS" },
		{ ATA_CMD_READ_NATIVE_MAX_EXT,	"READ NATIVE MAX ADDRESS EXT" },
		{ ATA_CMD_SET_MAX,		"SET MAX ADDRESS" },
		{ ATA_CMD_SET_MAX_EXT,		"SET MAX ADDRESS EXT" },
		{ ATA_CMD_READ_LOG_EXT,		"READ LOG EXT" },
		{ ATA_CMD_WRITE_LOG_EXT,	"WRITE LOG EXT" },
		{ ATA_CMD_READ_LOG_DMA_EXT,	"READ LOG DMA EXT" },
		{ ATA_CMD_WRITE_LOG_DMA_EXT,	"WRITE LOG DMA EXT" },
		{ ATA_CMD_TRUSTED_NONDATA,	"TRUSTED NON-DATA" },
		{ ATA_CMD_TRUSTED_RCV,		"TRUSTED RECEIVE" },
		{ ATA_CMD_TRUSTED_RCV_DMA,	"TRUSTED RECEIVE DMA" },
		{ ATA_CMD_TRUSTED_SND,		"TRUSTED SEND" },
		{ ATA_CMD_TRUSTED_SND_DMA,	"TRUSTED SEND DMA" },
		{ ATA_CMD_PMP_READ,		"READ BUFFER" },
		{ ATA_CMD_PMP_READ_DMA,		"READ BUFFER DMA" },
		{ ATA_CMD_PMP_WRITE,		"WRITE BUFFER" },
		{ ATA_CMD_PMP_WRITE_DMA,	"WRITE BUFFER DMA" },
		{ ATA_CMD_CONF_OVERLAY,		"DEVICE CONFIGURATION OVERLAY" },
		{ ATA_CMD_SEC_SET_PASS,		"SECURITY SET PASSWORD" },
		{ ATA_CMD_SEC_UNLOCK,		"SECURITY UNLOCK" },
		{ ATA_CMD_SEC_ERASE_PREP,	"SECURITY ERASE PREPARE" },
		{ ATA_CMD_SEC_ERASE_UNIT,	"SECURITY ERASE UNIT" },
		{ ATA_CMD_SEC_FREEZE_LOCK,	"SECURITY FREEZE LOCK" },
		{ ATA_CMD_SEC_DISABLE_PASS,	"SECURITY DISABLE PASSWORD" },
		{ ATA_CMD_CONFIG_STREAM,	"CONFIGURE STREAM" },
		{ ATA_CMD_SMART,		"SMART" },
		{ ATA_CMD_MEDIA_LOCK,		"DOOR LOCK" },
		{ ATA_CMD_MEDIA_UNLOCK,		"DOOR UNLOCK" },
		{ ATA_CMD_DSM,			"DATA SET MANAGEMENT" },
		{ ATA_CMD_CHK_MED_CRD_TYP,	"CHECK MEDIA CARD TYPE" },
		{ ATA_CMD_CFA_REQ_EXT_ERR,	"CFA REQUEST EXTENDED ERROR" },
		{ ATA_CMD_CFA_WRITE_NE,		"CFA WRITE SECTORS WITHOUT ERASE" },
		{ ATA_CMD_CFA_TRANS_SECT,	"CFA TRANSLATE SECTOR" },
		{ ATA_CMD_CFA_ERASE,		"CFA ERASE SECTORS" },
		{ ATA_CMD_CFA_WRITE_MULT_NE,	"CFA WRITE MULTIPLE WITHOUT ERASE" },
		{ ATA_CMD_REQ_SENSE_DATA,	"REQUEST SENSE DATA EXT" },
		{ ATA_CMD_SANITIZE_DEVICE,	"SANITIZE DEVICE" },
		{ ATA_CMD_ZAC_MGMT_IN,		"ZAC MANAGEMENT IN" },
		{ ATA_CMD_ZAC_MGMT_OUT,		"ZAC MANAGEMENT OUT" },
		{ ATA_CMD_READ_LONG,		"READ LONG (with retries)" },
		{ ATA_CMD_READ_LONG_ONCE,	"READ LONG (without retries)" },
		{ ATA_CMD_WRITE_LONG,		"WRITE LONG (with retries)" },
		{ ATA_CMD_WRITE_LONG_ONCE,	"WRITE LONG (without retries)" },
		{ ATA_CMD_RESTORE,		"RECALIBRATE" },
		{ 0,				NULL } /* terminate list */
	};

	unsigned int i;
	for (i = 0; cmd_descr[i].text; i++)
		if (cmd_descr[i].command == command)
			return cmd_descr[i].text;
#endif

	return NULL;
}