#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  int u32 ;
typedef  int s32 ;
typedef  enum v4l2_ctrl_type { ____Placeholder_v4l2_ctrl_type } v4l2_ctrl_type ;

/* Variables and functions */
#define  V4L2_CID_AUDIO_BALANCE 206 
#define  V4L2_CID_AUDIO_BASS 205 
#define  V4L2_CID_AUDIO_COMPRESSION_ATTACK_TIME 204 
#define  V4L2_CID_AUDIO_COMPRESSION_ENABLED 203 
#define  V4L2_CID_AUDIO_COMPRESSION_GAIN 202 
#define  V4L2_CID_AUDIO_COMPRESSION_RELEASE_TIME 201 
#define  V4L2_CID_AUDIO_COMPRESSION_THRESHOLD 200 
#define  V4L2_CID_AUDIO_LIMITER_DEVIATION 199 
#define  V4L2_CID_AUDIO_LIMITER_ENABLED 198 
#define  V4L2_CID_AUDIO_LIMITER_RELEASE_TIME 197 
#define  V4L2_CID_AUDIO_LOUDNESS 196 
#define  V4L2_CID_AUDIO_MUTE 195 
#define  V4L2_CID_AUDIO_TREBLE 194 
#define  V4L2_CID_AUDIO_VOLUME 193 
#define  V4L2_CID_AUTOGAIN 192 
#define  V4L2_CID_AUTO_WHITE_BALANCE 191 
#define  V4L2_CID_BG_COLOR 190 
#define  V4L2_CID_BLUE_BALANCE 189 
#define  V4L2_CID_BRIGHTNESS 188 
#define  V4L2_CID_CAMERA_CLASS 187 
#define  V4L2_CID_CHROMA_AGC 186 
#define  V4L2_CID_CHROMA_GAIN 185 
#define  V4L2_CID_COLORFX 184 
#define  V4L2_CID_COLOR_KILLER 183 
#define  V4L2_CID_CONTRAST 182 
#define  V4L2_CID_EXPOSURE_AUTO 181 
#define  V4L2_CID_EXPOSURE_AUTO_PRIORITY 180 
#define  V4L2_CID_FM_TX_CLASS 179 
#define  V4L2_CID_FOCUS_AUTO 178 
#define  V4L2_CID_FOCUS_RELATIVE 177 
#define  V4L2_CID_GAMMA 176 
#define  V4L2_CID_HFLIP 175 
#define  V4L2_CID_HUE 174 
#define  V4L2_CID_HUE_AUTO 173 
#define  V4L2_CID_ILLUMINATORS_1 172 
#define  V4L2_CID_ILLUMINATORS_2 171 
#define  V4L2_CID_IRIS_RELATIVE 170 
#define  V4L2_CID_MPEG_AUDIO_AC3_BITRATE 169 
#define  V4L2_CID_MPEG_AUDIO_CRC 168 
#define  V4L2_CID_MPEG_AUDIO_EMPHASIS 167 
#define  V4L2_CID_MPEG_AUDIO_ENCODING 166 
#define  V4L2_CID_MPEG_AUDIO_L1_BITRATE 165 
#define  V4L2_CID_MPEG_AUDIO_L2_BITRATE 164 
#define  V4L2_CID_MPEG_AUDIO_L3_BITRATE 163 
#define  V4L2_CID_MPEG_AUDIO_MODE 162 
#define  V4L2_CID_MPEG_AUDIO_MODE_EXTENSION 161 
#define  V4L2_CID_MPEG_AUDIO_MUTE 160 
#define  V4L2_CID_MPEG_AUDIO_SAMPLING_FREQ 159 
#define  V4L2_CID_MPEG_CLASS 158 
#define  V4L2_CID_MPEG_STREAM_TYPE 157 
#define  V4L2_CID_MPEG_STREAM_VBI_FMT 156 
#define  V4L2_CID_MPEG_VIDEO_ASPECT 155 
#define  V4L2_CID_MPEG_VIDEO_BITRATE_MODE 154 
#define  V4L2_CID_MPEG_VIDEO_B_FRAMES 153 
#define  V4L2_CID_MPEG_VIDEO_ENCODING 152 
#define  V4L2_CID_MPEG_VIDEO_GOP_CLOSURE 151 
#define  V4L2_CID_MPEG_VIDEO_MUTE 150 
#define  V4L2_CID_MPEG_VIDEO_PULLDOWN 149 
#define  V4L2_CID_PAN_RELATIVE 148 
#define  V4L2_CID_PAN_RESET 147 
#define  V4L2_CID_PILOT_TONE_DEVIATION 146 
#define  V4L2_CID_PILOT_TONE_ENABLED 145 
#define  V4L2_CID_PILOT_TONE_FREQUENCY 144 
#define  V4L2_CID_POWER_LINE_FREQUENCY 143 
#define  V4L2_CID_PRIVACY 142 
#define  V4L2_CID_RDS_TX_DEVIATION 141 
#define  V4L2_CID_RDS_TX_PS_NAME 140 
#define  V4L2_CID_RDS_TX_RADIO_TEXT 139 
#define  V4L2_CID_RED_BALANCE 138 
#define  V4L2_CID_SATURATION 137 
#define  V4L2_CID_SHARPNESS 136 
#define  V4L2_CID_TILT_RELATIVE 135 
#define  V4L2_CID_TILT_RESET 134 
#define  V4L2_CID_TUNE_ANTENNA_CAPACITOR 133 
#define  V4L2_CID_TUNE_POWER_LEVEL 132 
#define  V4L2_CID_TUNE_PREEMPHASIS 131 
#define  V4L2_CID_USER_CLASS 130 
#define  V4L2_CID_VFLIP 129 
#define  V4L2_CID_ZOOM_RELATIVE 128 
 int V4L2_CTRL_FLAG_READ_ONLY ; 
 int V4L2_CTRL_FLAG_SLIDER ; 
 int V4L2_CTRL_FLAG_UPDATE ; 
 int V4L2_CTRL_FLAG_WRITE_ONLY ; 
 int V4L2_CTRL_TYPE_BOOLEAN ; 
 int V4L2_CTRL_TYPE_BUTTON ; 
 int V4L2_CTRL_TYPE_CTRL_CLASS ; 
 int V4L2_CTRL_TYPE_INTEGER ; 
 int V4L2_CTRL_TYPE_MENU ; 
 int V4L2_CTRL_TYPE_STRING ; 
 char* v4l2_ctrl_get_name (int) ; 

void v4l2_ctrl_fill(u32 id, const char **name, enum v4l2_ctrl_type *type,
		    s32 *min, s32 *max, s32 *step, s32 *def, u32 *flags)
{
	*name = v4l2_ctrl_get_name(id);
	*flags = 0;

	switch (id) {
	case V4L2_CID_AUDIO_MUTE:
	case V4L2_CID_AUDIO_LOUDNESS:
	case V4L2_CID_AUTO_WHITE_BALANCE:
	case V4L2_CID_AUTOGAIN:
	case V4L2_CID_HFLIP:
	case V4L2_CID_VFLIP:
	case V4L2_CID_HUE_AUTO:
	case V4L2_CID_CHROMA_AGC:
	case V4L2_CID_COLOR_KILLER:
	case V4L2_CID_MPEG_AUDIO_MUTE:
	case V4L2_CID_MPEG_VIDEO_MUTE:
	case V4L2_CID_MPEG_VIDEO_GOP_CLOSURE:
	case V4L2_CID_MPEG_VIDEO_PULLDOWN:
	case V4L2_CID_EXPOSURE_AUTO_PRIORITY:
	case V4L2_CID_FOCUS_AUTO:
	case V4L2_CID_PRIVACY:
	case V4L2_CID_AUDIO_LIMITER_ENABLED:
	case V4L2_CID_AUDIO_COMPRESSION_ENABLED:
	case V4L2_CID_PILOT_TONE_ENABLED:
	case V4L2_CID_ILLUMINATORS_1:
	case V4L2_CID_ILLUMINATORS_2:
		*type = V4L2_CTRL_TYPE_BOOLEAN;
		*min = 0;
		*max = *step = 1;
		break;
	case V4L2_CID_PAN_RESET:
	case V4L2_CID_TILT_RESET:
		*type = V4L2_CTRL_TYPE_BUTTON;
		*flags |= V4L2_CTRL_FLAG_WRITE_ONLY;
		*min = *max = *step = *def = 0;
		break;
	case V4L2_CID_POWER_LINE_FREQUENCY:
	case V4L2_CID_MPEG_AUDIO_SAMPLING_FREQ:
	case V4L2_CID_MPEG_AUDIO_ENCODING:
	case V4L2_CID_MPEG_AUDIO_L1_BITRATE:
	case V4L2_CID_MPEG_AUDIO_L2_BITRATE:
	case V4L2_CID_MPEG_AUDIO_L3_BITRATE:
	case V4L2_CID_MPEG_AUDIO_AC3_BITRATE:
	case V4L2_CID_MPEG_AUDIO_MODE:
	case V4L2_CID_MPEG_AUDIO_MODE_EXTENSION:
	case V4L2_CID_MPEG_AUDIO_EMPHASIS:
	case V4L2_CID_MPEG_AUDIO_CRC:
	case V4L2_CID_MPEG_VIDEO_ENCODING:
	case V4L2_CID_MPEG_VIDEO_ASPECT:
	case V4L2_CID_MPEG_VIDEO_BITRATE_MODE:
	case V4L2_CID_MPEG_STREAM_TYPE:
	case V4L2_CID_MPEG_STREAM_VBI_FMT:
	case V4L2_CID_EXPOSURE_AUTO:
	case V4L2_CID_COLORFX:
	case V4L2_CID_TUNE_PREEMPHASIS:
		*type = V4L2_CTRL_TYPE_MENU;
		break;
	case V4L2_CID_RDS_TX_PS_NAME:
	case V4L2_CID_RDS_TX_RADIO_TEXT:
		*type = V4L2_CTRL_TYPE_STRING;
		break;
	case V4L2_CID_USER_CLASS:
	case V4L2_CID_CAMERA_CLASS:
	case V4L2_CID_MPEG_CLASS:
	case V4L2_CID_FM_TX_CLASS:
		*type = V4L2_CTRL_TYPE_CTRL_CLASS;
		/* You can neither read not write these */
		*flags |= V4L2_CTRL_FLAG_READ_ONLY | V4L2_CTRL_FLAG_WRITE_ONLY;
		*min = *max = *step = *def = 0;
		break;
	case V4L2_CID_BG_COLOR:
		*type = V4L2_CTRL_TYPE_INTEGER;
		*step = 1;
		*min = 0;
		/* Max is calculated as RGB888 that is 2^24 */
		*max = 0xFFFFFF;
		break;
	default:
		*type = V4L2_CTRL_TYPE_INTEGER;
		break;
	}
	switch (id) {
	case V4L2_CID_MPEG_AUDIO_ENCODING:
	case V4L2_CID_MPEG_AUDIO_MODE:
	case V4L2_CID_MPEG_VIDEO_BITRATE_MODE:
	case V4L2_CID_MPEG_VIDEO_B_FRAMES:
	case V4L2_CID_MPEG_STREAM_TYPE:
		*flags |= V4L2_CTRL_FLAG_UPDATE;
		break;
	case V4L2_CID_AUDIO_VOLUME:
	case V4L2_CID_AUDIO_BALANCE:
	case V4L2_CID_AUDIO_BASS:
	case V4L2_CID_AUDIO_TREBLE:
	case V4L2_CID_BRIGHTNESS:
	case V4L2_CID_CONTRAST:
	case V4L2_CID_SATURATION:
	case V4L2_CID_HUE:
	case V4L2_CID_RED_BALANCE:
	case V4L2_CID_BLUE_BALANCE:
	case V4L2_CID_GAMMA:
	case V4L2_CID_SHARPNESS:
	case V4L2_CID_CHROMA_GAIN:
	case V4L2_CID_RDS_TX_DEVIATION:
	case V4L2_CID_AUDIO_LIMITER_RELEASE_TIME:
	case V4L2_CID_AUDIO_LIMITER_DEVIATION:
	case V4L2_CID_AUDIO_COMPRESSION_GAIN:
	case V4L2_CID_AUDIO_COMPRESSION_THRESHOLD:
	case V4L2_CID_AUDIO_COMPRESSION_ATTACK_TIME:
	case V4L2_CID_AUDIO_COMPRESSION_RELEASE_TIME:
	case V4L2_CID_PILOT_TONE_DEVIATION:
	case V4L2_CID_PILOT_TONE_FREQUENCY:
	case V4L2_CID_TUNE_POWER_LEVEL:
	case V4L2_CID_TUNE_ANTENNA_CAPACITOR:
		*flags |= V4L2_CTRL_FLAG_SLIDER;
		break;
	case V4L2_CID_PAN_RELATIVE:
	case V4L2_CID_TILT_RELATIVE:
	case V4L2_CID_FOCUS_RELATIVE:
	case V4L2_CID_IRIS_RELATIVE:
	case V4L2_CID_ZOOM_RELATIVE:
		*flags |= V4L2_CTRL_FLAG_WRITE_ONLY;
		break;
	}
}