#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */
typedef  struct TYPE_16__   TYPE_8__ ;
typedef  struct TYPE_15__   TYPE_7__ ;
typedef  struct TYPE_14__   TYPE_6__ ;
typedef  struct TYPE_13__   TYPE_5__ ;
typedef  struct TYPE_12__   TYPE_4__ ;
typedef  struct TYPE_11__   TYPE_3__ ;
typedef  struct TYPE_10__   TYPE_2__ ;
typedef  struct TYPE_9__   TYPE_1__ ;

/* Type definitions */
struct TYPE_16__ {void* item_string; } ;
struct TYPE_15__ {void* item_string; } ;
struct TYPE_14__ {void* item_string; } ;
struct TYPE_13__ {void* item_string; } ;
struct TYPE_12__ {void* item_string; } ;
struct TYPE_11__ {void* item_string; } ;
struct TYPE_10__ {void* item_string; } ;
struct TYPE_9__ {void* item_string; } ;

/* Variables and functions */
 char* AUTHOR ; 
 int /*<<< orphan*/ * AUTOFORMAT ; 
 void* CASE ; 
 char* CHARACTER ; 
 int /*<<< orphan*/ * EIGHTBIT ; 
 int /*<<< orphan*/ * EMACS_string ; 
 void* EXPAND ; 
 int /*<<< orphan*/ * Echo ; 
 char* Exit_string ; 
 char* FILE_str ; 
 char* HELP ; 
 int /*<<< orphan*/ * HIGHLIGHT ; 
 int /*<<< orphan*/ * INFO ; 
 int /*<<< orphan*/  LC_ALL ; 
 char* LINE ; 
 int /*<<< orphan*/ * MARGINS ; 
 int /*<<< orphan*/  NL_CAT_LOCALE ; 
 int /*<<< orphan*/ * NOAUTOFORMAT ; 
 void* NOCASE ; 
 int /*<<< orphan*/ * NOEIGHTBIT ; 
 int /*<<< orphan*/ * NOEMACS_string ; 
 void* NOEXPAND ; 
 int /*<<< orphan*/ * NOHIGHLIGHT ; 
 int /*<<< orphan*/ * NOINFO ; 
 int /*<<< orphan*/ * NOMARGINS ; 
 int NUM_MODES_ITEMS ; 
 void* OFF ; 
 void* ON ; 
 int /*<<< orphan*/ * PRINTCOMMAND ; 
 char* QUIT_string ; 
 char* READ ; 
 char* REDRAW ; 
 char* RESEQUENCE ; 
 int /*<<< orphan*/ * RIGHTMARGIN ; 
 char* VERSION ; 
 char* WRITE ; 
 void* ascii_code_str ; 
 void* cant_open_msg ; 
 int /*<<< orphan*/  catalog ; 
 int /*<<< orphan*/  catclose (int /*<<< orphan*/ ) ; 
 void* catgetlocal (int,char*) ; 
 int /*<<< orphan*/  catopen (char*,int /*<<< orphan*/ ) ; 
 void* changes_made_prompt ; 
 void* char_str ; 
 void* chinese_cmd ; 
 void* com_win_message ; 
 void* command_str ; 
 void** command_strings ; 
 char** commands ; 
 void* conf_dump_err_msg ; 
 void* conf_dump_success_msg ; 
 void* conf_not_saved_msg ; 
 TYPE_8__* config_dump_menu ; 
 void* continue_msg ; 
 void** control_keys ; 
 void* create_file_fail_msg ; 
 void* current_file_str ; 
 void** emacs_control_keys ; 
 void** emacs_help_text ; 
 void* exec_err_msg ; 
 void* file_exists_prompt ; 
 void* file_is_dir_msg ; 
 TYPE_7__* file_menu ; 
 void* file_not_saved_msg ; 
 void* file_read_fin_msg ; 
 void* file_read_lines_msg ; 
 void* file_read_prompt_str ; 
 void* file_write_prompt_str ; 
 void* file_written_msg ; 
 void* formatting_msg ; 
 void** help_text ; 
 int /*<<< orphan*/ ** init_strings ; 
 TYPE_6__* leave_menu ; 
 void* line_len_str ; 
 void* line_num_str ; 
 TYPE_5__* main_menu ; 
 void* malloc (int) ; 
 void* margin_prompt ; 
 void* menu_cancel_msg ; 
 void* menu_size_err_msg ; 
 void* menu_too_lrg_msg ; 
 TYPE_4__* misc_menu ; 
 void** mode_strings ; 
 TYPE_3__* modes_menu ; 
 void* more_above_str ; 
 void* more_below_str ; 
 void* new_file_msg ; 
 void* no_file_string ; 
 void* nochinese_cmd ; 
 void* non_unique_cmd_msg ; 
 void* open_file_msg ; 
 void* press_any_key_msg ; 
 void* printer_msg_str ; 
 void* read_only_msg ; 
 void* reading_file_msg ; 
 void* ree_no_file_msg ; 
 void* restricted_msg ; 
 void* save_file_name_prompt ; 
 TYPE_2__* search_menu ; 
 void* search_prompt_str ; 
 void* searching_msg ; 
 int /*<<< orphan*/  setlocale (int /*<<< orphan*/ ,char*) ; 
 void* shell_echo_msg ; 
 void* shell_prompt ; 
 void* spell_in_prog_msg ; 
 TYPE_1__* spell_menu ; 
 void* str_not_found_msg ; 
 void* unkn_cmd_str ; 
 void* usage0 ; 
 void* usage1 ; 
 void* usage2 ; 
 void* usage3 ; 
 void* usage4 ; 
 void* writing_file_msg ; 
 void* yes_char ; 

void 
strings_init()
{
	int counter;

	setlocale(LC_ALL, "");
#ifndef NO_CATGETS
	catalog = catopen("ee", NL_CAT_LOCALE);
#endif /* NO_CATGETS */

	modes_menu[0].item_string = catgetlocal( 1, "modes menu");
	mode_strings[1]  = catgetlocal( 2, "tabs to spaces       "); 
	mode_strings[2]  = catgetlocal( 3, "case sensitive search"); 
	mode_strings[3]  = catgetlocal( 4, "margins observed     "); 
	mode_strings[4]  = catgetlocal( 5, "auto-paragraph format"); 
	mode_strings[5]  = catgetlocal( 6, "eightbit characters  "); 
	mode_strings[6]  = catgetlocal( 7, "info window          "); 
	mode_strings[8]  = catgetlocal( 8, "right margin         ");
	leave_menu[0].item_string  = catgetlocal( 9, "leave menu");
	leave_menu[1].item_string  = catgetlocal( 10, "save changes");
	leave_menu[2].item_string  = catgetlocal( 11, "no save");
	file_menu[0].item_string  = catgetlocal( 12, "file menu");
	file_menu[1].item_string  = catgetlocal( 13, "read a file");
	file_menu[2].item_string  = catgetlocal( 14, "write a file");
	file_menu[3].item_string  = catgetlocal( 15, "save file");
	file_menu[4].item_string  = catgetlocal( 16, "print editor contents");
	search_menu[0].item_string = catgetlocal( 17, "search menu");
	search_menu[1].item_string = catgetlocal( 18, "search for ...");
	search_menu[2].item_string = catgetlocal( 19, "search");
	spell_menu[0].item_string = catgetlocal( 20, "spell menu");
	spell_menu[1].item_string = catgetlocal( 21, "use 'spell'");
	spell_menu[2].item_string = catgetlocal( 22, "use 'ispell'");
	misc_menu[0].item_string = catgetlocal( 23, "miscellaneous menu");
	misc_menu[1].item_string = catgetlocal( 24, "format paragraph");
	misc_menu[2].item_string = catgetlocal( 25, "shell command");
	misc_menu[3].item_string = catgetlocal( 26, "check spelling");
	main_menu[0].item_string  = catgetlocal( 27, "main menu");
	main_menu[1].item_string  = catgetlocal( 28, "leave editor");
	main_menu[2].item_string  = catgetlocal( 29, "help");
	main_menu[3].item_string  = catgetlocal( 30, "file operations");
	main_menu[4].item_string  = catgetlocal( 31, "redraw screen");
	main_menu[5].item_string  = catgetlocal( 32, "settings");
	main_menu[6].item_string  = catgetlocal( 33, "search");
	main_menu[7].item_string  = catgetlocal( 34, "miscellaneous");
	help_text[0] = catgetlocal( 35, "Control keys:                                                              "); 
	help_text[1] = catgetlocal( 36, "^a ascii code           ^i tab                  ^r right                   ");
	help_text[2] = catgetlocal( 37, "^b bottom of text       ^j newline              ^t top of text             ");
	help_text[3] = catgetlocal( 38, "^c command              ^k delete char          ^u up                      ");
	help_text[4] = catgetlocal( 39, "^d down                 ^l left                 ^v undelete word           ");
	help_text[5] = catgetlocal( 40, "^e search prompt        ^m newline              ^w delete word             ");
	help_text[6] = catgetlocal( 41, "^f undelete char        ^n next page            ^x search                  ");
	help_text[7] = catgetlocal( 42, "^g begin of line        ^o end of line          ^y delete line             ");
	help_text[8] = catgetlocal( 43, "^h backspace            ^p prev page            ^z undelete line           ");
	help_text[9] = catgetlocal( 44, "^[ (escape) menu        ESC-Enter: exit ee                                 ");
	help_text[10] = catgetlocal( 45, "                                                                           ");
	help_text[11] = catgetlocal( 46, "Commands:                                                                  ");
	help_text[12] = catgetlocal( 47, "help    : get this info                 file    : print file name          ");
	help_text[13] = catgetlocal( 48, "read    : read a file                   char    : ascii code of char       ");
	help_text[14] = catgetlocal( 49, "write   : write a file                  case    : case sensitive search    ");
	help_text[15] = catgetlocal( 50, "exit    : leave and save                nocase  : case insensitive search  ");
	help_text[16] = catgetlocal( 51, "quit    : leave, no save                !cmd    : execute \"cmd\" in shell   ");
	help_text[17] = catgetlocal( 52, "line    : display line #                0-9     : go to line \"#\"           ");
	help_text[18] = catgetlocal( 53, "expand  : expand tabs                   noexpand: do not expand tabs         ");
	help_text[19] = catgetlocal( 54, "                                                                             ");
	help_text[20] = catgetlocal( 55, "  ee [+#] [-i] [-e] [-h] [file(s)]                                            ");
	help_text[21] = catgetlocal( 56, "+# :go to line #  -i :no info window  -e : don't expand tabs  -h :no highlight");
	control_keys[0] = catgetlocal( 57, "^[ (escape) menu  ^e search prompt  ^y delete line    ^u up     ^p prev page  ");
	control_keys[1] = catgetlocal( 58, "^a ascii code     ^x search         ^z undelete line  ^d down   ^n next page  ");
	control_keys[2] = catgetlocal( 59, "^b bottom of text ^g begin of line  ^w delete word    ^l left                 ");
	control_keys[3] = catgetlocal( 60, "^t top of text    ^o end of line    ^v undelete word  ^r right                ");
	control_keys[4] = catgetlocal( 61, "^c command        ^k delete char    ^f undelete char      ESC-Enter: exit ee  ");
	command_strings[0] = catgetlocal( 62, "help : get help info  |file  : print file name         |line : print line # ");
	command_strings[1] = catgetlocal( 63, "read : read a file    |char  : ascii code of char      |0-9 : go to line \"#\"");
	command_strings[2] = catgetlocal( 64, "write: write a file   |case  : case sensitive search   |exit : leave and save ");
	command_strings[3] = catgetlocal( 65, "!cmd : shell \"cmd\"    |nocase: ignore case in search   |quit : leave, no save");
	command_strings[4] = catgetlocal( 66, "expand: expand tabs   |noexpand: do not expand tabs                           ");
	com_win_message = catgetlocal( 67, "    press Escape (^[) for menu");
	no_file_string = catgetlocal( 68, "no file");
	ascii_code_str = catgetlocal( 69, "ascii code: ");
	printer_msg_str = catgetlocal( 70, "sending contents of buffer to \"%s\" ");
	command_str = catgetlocal( 71, "command: ");
	file_write_prompt_str = catgetlocal( 72, "name of file to write: ");
	file_read_prompt_str = catgetlocal( 73, "name of file to read: ");
	char_str = catgetlocal( 74, "character = %d");
	unkn_cmd_str = catgetlocal( 75, "unknown command \"%s\"");
	non_unique_cmd_msg = catgetlocal( 76, "entered command is not unique");
	line_num_str = catgetlocal( 77, "line %d  ");
	line_len_str = catgetlocal( 78, "length = %d");
	current_file_str = catgetlocal( 79, "current file is \"%s\" ");
	usage0 = catgetlocal( 80, "usage: %s [-i] [-e] [-h] [+line_number] [file(s)]\n");
	usage1 = catgetlocal( 81, "       -i   turn off info window\n");
	usage2 = catgetlocal( 82, "       -e   do not convert tabs to spaces\n");
	usage3 = catgetlocal( 83, "       -h   do not use highlighting\n");
	file_is_dir_msg = catgetlocal( 84, "file \"%s\" is a directory");
	new_file_msg = catgetlocal( 85, "new file \"%s\"");
	cant_open_msg = catgetlocal( 86, "can't open \"%s\"");
	open_file_msg = catgetlocal( 87, "file \"%s\", %d lines");
	file_read_fin_msg = catgetlocal( 88, "finished reading file \"%s\"");
	reading_file_msg = catgetlocal( 89, "reading file \"%s\"");
	read_only_msg = catgetlocal( 90, ", read only");
	file_read_lines_msg = catgetlocal( 91, "file \"%s\", %d lines");
	save_file_name_prompt = catgetlocal( 92, "enter name of file: ");
	file_not_saved_msg = catgetlocal( 93, "no filename entered: file not saved");
	changes_made_prompt = catgetlocal( 94, "changes have been made, are you sure? (y/n [n]) ");
	yes_char = catgetlocal( 95, "y");
	file_exists_prompt = catgetlocal( 96, "file already exists, overwrite? (y/n) [n] ");
	create_file_fail_msg = catgetlocal( 97, "unable to create file \"%s\"");
	writing_file_msg = catgetlocal( 98, "writing file \"%s\"");
	file_written_msg = catgetlocal( 99, "\"%s\" %d lines, %d characters");
	searching_msg = catgetlocal( 100, "           ...searching");
	str_not_found_msg = catgetlocal( 101, "string \"%s\" not found");
	search_prompt_str = catgetlocal( 102, "search for: ");
	exec_err_msg = catgetlocal( 103, "could not exec %s\n");
	continue_msg = catgetlocal( 104, "press return to continue ");
	menu_cancel_msg = catgetlocal( 105, "press Esc to cancel");
	menu_size_err_msg = catgetlocal( 106, "menu too large for window");
	press_any_key_msg = catgetlocal( 107, "press any key to continue ");
	shell_prompt = catgetlocal( 108, "shell command: ");
	formatting_msg = catgetlocal( 109, "...formatting paragraph...");
	shell_echo_msg = catgetlocal( 110, "<!echo 'list of unrecognized words'; echo -=-=-=-=-=-");
	spell_in_prog_msg = catgetlocal( 111, "sending contents of edit buffer to 'spell'");
	margin_prompt = catgetlocal( 112, "right margin is: ");
	restricted_msg = catgetlocal( 113, "restricted mode: unable to perform requested operation");
	ON = catgetlocal( 114, "ON");
	OFF = catgetlocal( 115, "OFF");
	HELP = catgetlocal( 116, "HELP");
	WRITE = catgetlocal( 117, "WRITE");
	READ = catgetlocal( 118, "READ");
	LINE = catgetlocal( 119, "LINE");
	FILE_str = catgetlocal( 120, "FILE");
	CHARACTER = catgetlocal( 121, "CHARACTER");
	REDRAW = catgetlocal( 122, "REDRAW");
	RESEQUENCE = catgetlocal( 123, "RESEQUENCE");
	AUTHOR = catgetlocal( 124, "AUTHOR");
	VERSION = catgetlocal( 125, "VERSION");
	CASE = catgetlocal( 126, "CASE");
	NOCASE = catgetlocal( 127, "NOCASE");
	EXPAND = catgetlocal( 128, "EXPAND");
	NOEXPAND = catgetlocal( 129, "NOEXPAND");
	Exit_string = catgetlocal( 130, "EXIT");
	QUIT_string = catgetlocal( 131, "QUIT");
	INFO = catgetlocal( 132, "INFO");
	NOINFO = catgetlocal( 133, "NOINFO");
	MARGINS = catgetlocal( 134, "MARGINS");
	NOMARGINS = catgetlocal( 135, "NOMARGINS");
	AUTOFORMAT = catgetlocal( 136, "AUTOFORMAT");
	NOAUTOFORMAT = catgetlocal( 137, "NOAUTOFORMAT");
	Echo = catgetlocal( 138, "ECHO");
	PRINTCOMMAND = catgetlocal( 139, "PRINTCOMMAND");
	RIGHTMARGIN = catgetlocal( 140, "RIGHTMARGIN");
	HIGHLIGHT = catgetlocal( 141, "HIGHLIGHT");
	NOHIGHLIGHT = catgetlocal( 142, "NOHIGHLIGHT");
	EIGHTBIT = catgetlocal( 143, "EIGHTBIT");
	NOEIGHTBIT = catgetlocal( 144, "NOEIGHTBIT");
	/*
	 |	additions
	 */
	mode_strings[7] = catgetlocal( 145, "emacs key bindings   ");
	emacs_help_text[0] = help_text[0];
	emacs_help_text[1] = catgetlocal( 146, "^a beginning of line    ^i tab                  ^r restore word            ");
	emacs_help_text[2] = catgetlocal( 147, "^b back 1 char          ^j undel char           ^t top of text             ");
	emacs_help_text[3] = catgetlocal( 148, "^c command              ^k delete line          ^u bottom of text          ");
	emacs_help_text[4] = catgetlocal( 149, "^d delete char          ^l undelete line        ^v next page               ");
	emacs_help_text[5] = catgetlocal( 150, "^e end of line          ^m newline              ^w delete word             ");
	emacs_help_text[6] = catgetlocal( 151, "^f forward 1 char       ^n next line            ^x search                  ");
	emacs_help_text[7] = catgetlocal( 152, "^g go back 1 page       ^o ascii char insert    ^y search prompt           ");
	emacs_help_text[8] = catgetlocal( 153, "^h backspace            ^p prev line            ^z next word               ");
	emacs_help_text[9] = help_text[9];
	emacs_help_text[10] = help_text[10];
	emacs_help_text[11] = help_text[11];
	emacs_help_text[12] = help_text[12];
	emacs_help_text[13] = help_text[13];
	emacs_help_text[14] = help_text[14];
	emacs_help_text[15] = help_text[15];
	emacs_help_text[16] = help_text[16];
	emacs_help_text[17] = help_text[17];
	emacs_help_text[18] = help_text[18];
	emacs_help_text[19] = help_text[19];
	emacs_help_text[20] = help_text[20];
	emacs_help_text[21] = help_text[21];
	emacs_control_keys[0] = catgetlocal( 154, "^[ (escape) menu ^y search prompt ^k delete line   ^p prev li     ^g prev page");
	emacs_control_keys[1] = catgetlocal( 155, "^o ascii code    ^x search        ^l undelete line ^n next li     ^v next page");
	emacs_control_keys[2] = catgetlocal( 156, "^u end of file   ^a begin of line ^w delete word   ^b back 1 char ^z next word");
	emacs_control_keys[3] = catgetlocal( 157, "^t top of text   ^e end of line   ^r restore word  ^f forward char            ");
	emacs_control_keys[4] = catgetlocal( 158, "^c command       ^d delete char   ^j undelete char              ESC-Enter: exit");
	EMACS_string = catgetlocal( 159, "EMACS");
	NOEMACS_string = catgetlocal( 160, "NOEMACS");
	usage4 = catgetlocal( 161, "       +#   put cursor at line #\n");
	conf_dump_err_msg = catgetlocal( 162, "unable to open .init.ee for writing, no configuration saved!");
	conf_dump_success_msg = catgetlocal( 163, "ee configuration saved in file %s");
	modes_menu[10].item_string = catgetlocal( 164, "save editor configuration");
	config_dump_menu[0].item_string = catgetlocal( 165, "save ee configuration");
	config_dump_menu[1].item_string = catgetlocal( 166, "save in current directory");
	config_dump_menu[2].item_string = catgetlocal( 167, "save in home directory");
	conf_not_saved_msg = catgetlocal( 168, "ee configuration not saved");
	ree_no_file_msg = catgetlocal( 169, "must specify a file when invoking ree");
	menu_too_lrg_msg = catgetlocal( 180, "menu too large for window");
	more_above_str = catgetlocal( 181, "^^more^^");
	more_below_str = catgetlocal( 182, "VVmoreVV");
	mode_strings[9] = catgetlocal( 183, "16 bit characters    ");
	chinese_cmd = catgetlocal( 184, "16BIT");
	nochinese_cmd = catgetlocal( 185, "NO16BIT");

	commands[0] = HELP;
	commands[1] = WRITE;
	commands[2] = READ;
	commands[3] = LINE;
	commands[4] = FILE_str;
	commands[5] = REDRAW;
	commands[6] = RESEQUENCE;
	commands[7] = AUTHOR;
	commands[8] = VERSION;
	commands[9] = CASE;
	commands[10] = NOCASE;
	commands[11] = EXPAND;
	commands[12] = NOEXPAND;
	commands[13] = Exit_string;
	commands[14] = QUIT_string;
	commands[15] = "<";
	commands[16] = ">";
	commands[17] = "!";
	commands[18] = "0";
	commands[19] = "1";
	commands[20] = "2";
	commands[21] = "3";
	commands[22] = "4";
	commands[23] = "5";
	commands[24] = "6";
	commands[25] = "7";
	commands[26] = "8";
	commands[27] = "9";
	commands[28] = CHARACTER;
	commands[29] = chinese_cmd;
	commands[30] = nochinese_cmd;
	commands[31] = NULL;
	init_strings[0] = CASE;
	init_strings[1] = NOCASE;
	init_strings[2] = EXPAND;
	init_strings[3] = NOEXPAND;
	init_strings[4] = INFO;
	init_strings[5] = NOINFO;
	init_strings[6] = MARGINS;
	init_strings[7] = NOMARGINS;
	init_strings[8] = AUTOFORMAT;
	init_strings[9] = NOAUTOFORMAT;
	init_strings[10] = Echo;
	init_strings[11] = PRINTCOMMAND;
	init_strings[12] = RIGHTMARGIN;
	init_strings[13] = HIGHLIGHT;
	init_strings[14] = NOHIGHLIGHT;
	init_strings[15] = EIGHTBIT;
	init_strings[16] = NOEIGHTBIT;
	init_strings[17] = EMACS_string;
	init_strings[18] = NOEMACS_string;
	init_strings[19] = chinese_cmd;
	init_strings[20] = nochinese_cmd;
	init_strings[21] = NULL;

	/*
	 |	allocate space for strings here for settings menu
	 */

	for (counter = 1; counter < NUM_MODES_ITEMS; counter++)
	{
		modes_menu[counter].item_string = malloc(80);
	}

#ifndef NO_CATGETS
	catclose(catalog);
#endif /* NO_CATGETS */
}