#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */
typedef  struct TYPE_6__   TYPE_3__ ;
typedef  struct TYPE_5__   TYPE_2__ ;
typedef  struct TYPE_4__   TYPE_1__ ;

/* Type definitions */
struct pt_regs {int dummy; } ;
struct kexec_sha_region {int dummy; } ;
struct TYPE_6__ {int /*<<< orphan*/ ****** regs; int /*<<< orphan*/ ****** fpc; } ;
struct TYPE_5__ {int /*<<< orphan*/ ****** paid; int /*<<< orphan*/ ****** address; int /*<<< orphan*/ ****** cause; } ;
struct TYPE_4__ {int /*<<< orphan*/ ****** flags; } ;

/* Variables and functions */
 int /*<<< orphan*/  BLANK () ; 
 int CLOCK_MONOTONIC ; 
 int CLOCK_MONOTONIC_COARSE ; 
 int CLOCK_REALTIME ; 
 int CLOCK_REALTIME_COARSE ; 
 int CLOCK_THREAD_CPUTIME_ID ; 
 int /*<<< orphan*/  DEFINE (int /*<<< orphan*/ ,int) ; 
 int LOW_RES_NSEC ; 
 int MONOTONIC_RES_NSEC ; 
 int /*<<< orphan*/  OFFSET (int /*<<< orphan*/ ,int /*<<< orphan*/ ****,int /*<<< orphan*/ ****) ; 
 int /*<<< orphan*/  __CLOCK_COARSE_RES ; 
 int /*<<< orphan*/  __CLOCK_IDLE_ENTER ; 
 int /*<<< orphan*/  __CLOCK_IDLE_EXIT ; 
 int /*<<< orphan*/  __CLOCK_MONOTONIC ; 
 int /*<<< orphan*/  __CLOCK_MONOTONIC_COARSE ; 
 int /*<<< orphan*/  __CLOCK_REALTIME ; 
 int /*<<< orphan*/  __CLOCK_REALTIME_COARSE ; 
 int /*<<< orphan*/  __CLOCK_REALTIME_RES ; 
 int /*<<< orphan*/  __CLOCK_THREAD_CPUTIME_ID ; 
 int /*<<< orphan*/  __GMAP_ASCE ; 
 int /*<<< orphan*/  __KEXEC_SHA_REGION_LEN ; 
 int /*<<< orphan*/  __KEXEC_SHA_REGION_SIZE ; 
 int /*<<< orphan*/  __KEXEC_SHA_REGION_START ; 
 int /*<<< orphan*/  __LC_AREGS_SAVE_AREA ; 
 int /*<<< orphan*/  __LC_AR_MODE_ID ; 
 int /*<<< orphan*/  __LC_ASYNC_ENTER_TIMER ; 
 int /*<<< orphan*/  __LC_ASYNC_STACK ; 
 int /*<<< orphan*/  __LC_BOOT_CLOCK ; 
 int /*<<< orphan*/  __LC_BR_R1 ; 
 int /*<<< orphan*/  __LC_CLOCK_COMPARATOR ; 
 int /*<<< orphan*/  __LC_CLOCK_COMP_SAVE_AREA ; 
 int /*<<< orphan*/  __LC_CPU_FLAGS ; 
 int /*<<< orphan*/  __LC_CPU_TIMER_SAVE_AREA ; 
 int /*<<< orphan*/  __LC_CREGS_SAVE_AREA ; 
 int /*<<< orphan*/  __LC_CURRENT ; 
 int /*<<< orphan*/  __LC_CURRENT_PID ; 
 int /*<<< orphan*/  __LC_DATA_EXC_CODE ; 
 int /*<<< orphan*/  __LC_DUMP_REIPL ; 
 int /*<<< orphan*/  __LC_EXC_ACCESS_ID ; 
 int /*<<< orphan*/  __LC_EXIT_TIMER ; 
 int /*<<< orphan*/  __LC_EXT_CPU_ADDR ; 
 int /*<<< orphan*/  __LC_EXT_DAMAGE_CODE ; 
 int /*<<< orphan*/  __LC_EXT_INT_CODE ; 
 int /*<<< orphan*/  __LC_EXT_NEW_PSW ; 
 int /*<<< orphan*/  __LC_EXT_OLD_PSW ; 
 int /*<<< orphan*/  __LC_EXT_PARAMS ; 
 int /*<<< orphan*/  __LC_EXT_PARAMS2 ; 
 int /*<<< orphan*/  __LC_FPREGS_SAVE_AREA ; 
 int /*<<< orphan*/  __LC_FP_CREG_SAVE_AREA ; 
 int /*<<< orphan*/  __LC_GMAP ; 
 int /*<<< orphan*/  __LC_GPREGS_SAVE_AREA ; 
 int /*<<< orphan*/  __LC_INT_CLOCK ; 
 int /*<<< orphan*/  __LC_IO_INT_PARM ; 
 int /*<<< orphan*/  __LC_IO_INT_WORD ; 
 int /*<<< orphan*/  __LC_IO_NEW_PSW ; 
 int /*<<< orphan*/  __LC_IO_OLD_PSW ; 
 int /*<<< orphan*/  __LC_KERNEL_STACK ; 
 int /*<<< orphan*/  __LC_LAST_BREAK ; 
 int /*<<< orphan*/  __LC_LAST_UPDATE_CLOCK ; 
 int /*<<< orphan*/  __LC_LAST_UPDATE_TIMER ; 
 int /*<<< orphan*/  __LC_LPP ; 
 int /*<<< orphan*/  __LC_MACHINE_FLAGS ; 
 int /*<<< orphan*/  __LC_MCCK_CLOCK ; 
 int /*<<< orphan*/  __LC_MCCK_CODE ; 
 int /*<<< orphan*/  __LC_MCCK_ENTER_TIMER ; 
 int /*<<< orphan*/  __LC_MCCK_FAIL_STOR_ADDR ; 
 int /*<<< orphan*/  __LC_MCESAD ; 
 int /*<<< orphan*/  __LC_MCK_NEW_PSW ; 
 int /*<<< orphan*/  __LC_MCK_OLD_PSW ; 
 int /*<<< orphan*/  __LC_MON_CLASS_NR ; 
 int /*<<< orphan*/  __LC_MON_CODE ; 
 int /*<<< orphan*/  __LC_NODAT_STACK ; 
 int /*<<< orphan*/  __LC_OP_ACCESS_ID ; 
 int /*<<< orphan*/  __LC_PERCPU_OFFSET ; 
 int /*<<< orphan*/  __LC_PER_ACCESS_ID ; 
 int /*<<< orphan*/  __LC_PER_ADDRESS ; 
 int /*<<< orphan*/  __LC_PER_ATMID ; 
 int /*<<< orphan*/  __LC_PER_CODE ; 
 int /*<<< orphan*/  __LC_PGM_ILC ; 
 int /*<<< orphan*/  __LC_PGM_INT_CODE ; 
 int /*<<< orphan*/  __LC_PGM_NEW_PSW ; 
 int /*<<< orphan*/  __LC_PGM_OLD_PSW ; 
 int /*<<< orphan*/  __LC_PGM_TDB ; 
 int /*<<< orphan*/  __LC_PREEMPT_COUNT ; 
 int /*<<< orphan*/  __LC_PREFIX_SAVE_AREA ; 
 int /*<<< orphan*/  __LC_PSW_SAVE_AREA ; 
 int /*<<< orphan*/  __LC_RESTART_DATA ; 
 int /*<<< orphan*/  __LC_RESTART_FN ; 
 int /*<<< orphan*/  __LC_RESTART_SOURCE ; 
 int /*<<< orphan*/  __LC_RESTART_STACK ; 
 int /*<<< orphan*/  __LC_RETURN_MCCK_PSW ; 
 int /*<<< orphan*/  __LC_RETURN_PSW ; 
 int /*<<< orphan*/  __LC_RST_NEW_PSW ; 
 int /*<<< orphan*/  __LC_RST_OLD_PSW ; 
 int /*<<< orphan*/  __LC_SAVE_AREA_ASYNC ; 
 int /*<<< orphan*/  __LC_SAVE_AREA_RESTART ; 
 int /*<<< orphan*/  __LC_SAVE_AREA_SYNC ; 
 int /*<<< orphan*/  __LC_STEAL_TIMER ; 
 int /*<<< orphan*/  __LC_STFLE_FAC_LIST ; 
 int /*<<< orphan*/  __LC_STFL_FAC_LIST ; 
 int /*<<< orphan*/  __LC_SUBCHANNEL_ID ; 
 int /*<<< orphan*/  __LC_SUBCHANNEL_NR ; 
 int /*<<< orphan*/  __LC_SVC_ILC ; 
 int /*<<< orphan*/  __LC_SVC_INT_CODE ; 
 int /*<<< orphan*/  __LC_SVC_NEW_PSW ; 
 int /*<<< orphan*/  __LC_SVC_OLD_PSW ; 
 int /*<<< orphan*/  __LC_SYNC_ENTER_TIMER ; 
 int /*<<< orphan*/  __LC_SYSTEM_TIMER ; 
 int /*<<< orphan*/  __LC_TOD_PROGREG_SAVE_AREA ; 
 int /*<<< orphan*/  __LC_TRANS_EXC_CODE ; 
 int /*<<< orphan*/  __LC_USER_ASCE ; 
 int /*<<< orphan*/  __LC_USER_TIMER ; 
 int /*<<< orphan*/  __LC_VDSO_ASCE ; 
 int /*<<< orphan*/  __LC_VDSO_PER_CPU ; 
 int /*<<< orphan*/  __MCESA_GS_SAVE_AREA ; 
 int /*<<< orphan*/  __PT_ARGS ; 
 int /*<<< orphan*/  __PT_FLAGS ; 
 int /*<<< orphan*/  __PT_GPRS ; 
 int /*<<< orphan*/  __PT_INT_CODE ; 
 int /*<<< orphan*/  __PT_INT_PARM ; 
 int /*<<< orphan*/  __PT_INT_PARM_LONG ; 
 int /*<<< orphan*/  __PT_ORIG_GPR2 ; 
 int /*<<< orphan*/  __PT_PSW ; 
 int /*<<< orphan*/  __PT_SIZE ; 
 int /*<<< orphan*/  __SF_BACKCHAIN ; 
 int /*<<< orphan*/  __SF_EMPTY ; 
 int /*<<< orphan*/  __SF_GPRS ; 
 int /*<<< orphan*/  __SF_SIE_CONTROL ; 
 int /*<<< orphan*/  __SF_SIE_FLAGS ; 
 int /*<<< orphan*/  __SF_SIE_REASON ; 
 int /*<<< orphan*/  __SF_SIE_SAVEAREA ; 
 int /*<<< orphan*/  __SIE_PROG0C ; 
 int /*<<< orphan*/  __SIE_PROG20 ; 
 int /*<<< orphan*/  __TASK_pid ; 
 int /*<<< orphan*/  __TASK_stack ; 
 int /*<<< orphan*/  __TASK_thread ; 
 int /*<<< orphan*/  __THREAD_FPU_fpc ; 
 int /*<<< orphan*/  __THREAD_FPU_regs ; 
 int /*<<< orphan*/  __THREAD_ksp ; 
 int /*<<< orphan*/  __THREAD_last_break ; 
 int /*<<< orphan*/  __THREAD_per_address ; 
 int /*<<< orphan*/  __THREAD_per_cause ; 
 int /*<<< orphan*/  __THREAD_per_paid ; 
 int /*<<< orphan*/  __THREAD_sysc_table ; 
 int /*<<< orphan*/  __THREAD_trap_tdb ; 
 int /*<<< orphan*/  __TIMER_IDLE_ENTER ; 
 int /*<<< orphan*/  __TIMER_IDLE_EXIT ; 
 int /*<<< orphan*/  __TI_flags ; 
 int /*<<< orphan*/  __VDSO_CPU_NR ; 
 int /*<<< orphan*/  __VDSO_ECTG_BASE ; 
 int /*<<< orphan*/  __VDSO_ECTG_OK ; 
 int /*<<< orphan*/  __VDSO_ECTG_USER ; 
 int /*<<< orphan*/  __VDSO_NODE_ID ; 
 int /*<<< orphan*/  __VDSO_TIMEZONE ; 
 int /*<<< orphan*/  __VDSO_TK_MULT ; 
 int /*<<< orphan*/  __VDSO_TK_SHIFT ; 
 int /*<<< orphan*/  __VDSO_TS_DIR ; 
 int /*<<< orphan*/  __VDSO_TS_END ; 
 int /*<<< orphan*/  __VDSO_UPD_COUNT ; 
 int /*<<< orphan*/  __VDSO_WTOM_CRS_NSEC ; 
 int /*<<< orphan*/  __VDSO_WTOM_CRS_SEC ; 
 int /*<<< orphan*/  __VDSO_WTOM_NSEC ; 
 int /*<<< orphan*/  __VDSO_WTOM_SEC ; 
 int /*<<< orphan*/  __VDSO_XTIME_CRS_NSEC ; 
 int /*<<< orphan*/  __VDSO_XTIME_CRS_SEC ; 
 int /*<<< orphan*/  __VDSO_XTIME_NSEC ; 
 int /*<<< orphan*/  __VDSO_XTIME_SEC ; 
 int /*<<< orphan*/  __VDSO_XTIME_STAMP ; 
 int /*<<< orphan*/ **** access_regs_save_area ; 
 int /*<<< orphan*/ **** ar_mode_id ; 
 int /*<<< orphan*/ **** args ; 
 int /*<<< orphan*/ **** asce ; 
 int /*<<< orphan*/ **** async_enter_timer ; 
 int /*<<< orphan*/ **** async_stack ; 
 int /*<<< orphan*/ **** back_chain ; 
 int /*<<< orphan*/ **** boot_clock ; 
 int /*<<< orphan*/ **** br_r1_trampoline ; 
 int /*<<< orphan*/ **** breaking_event_addr ; 
 int /*<<< orphan*/ **** clock_comp_save_area ; 
 int /*<<< orphan*/ **** clock_comparator ; 
 int /*<<< orphan*/ **** clock_idle_enter ; 
 int /*<<< orphan*/ **** clock_idle_exit ; 
 int /*<<< orphan*/ **** cpu_flags ; 
 int /*<<< orphan*/ **** cpu_nr ; 
 int /*<<< orphan*/ **** cpu_timer_save_area ; 
 int /*<<< orphan*/ **** cregs_save_area ; 
 int /*<<< orphan*/ **** current_pid ; 
 int /*<<< orphan*/ **** current_task ; 
 int /*<<< orphan*/ **** data_exc_code ; 
 int /*<<< orphan*/ **** ectg_available ; 
 int /*<<< orphan*/ **** ectg_timer_base ; 
 int /*<<< orphan*/ **** ectg_user_time ; 
 int /*<<< orphan*/ ***** empty1 ; 
 int /*<<< orphan*/ **** exc_access_id ; 
 int /*<<< orphan*/ **** exit_timer ; 
 int /*<<< orphan*/ **** ext_cpu_addr ; 
 int /*<<< orphan*/ **** ext_int_code ; 
 int /*<<< orphan*/ **** ext_params ; 
 int /*<<< orphan*/ **** ext_params2 ; 
 int /*<<< orphan*/ **** external_damage_code ; 
 int /*<<< orphan*/ **** external_new_psw ; 
 int /*<<< orphan*/ **** external_old_psw ; 
 int /*<<< orphan*/ **** failing_storage_address ; 
 int /*<<< orphan*/ **** flags ; 
 int /*<<< orphan*/ **** floating_pt_save_area ; 
 int /*<<< orphan*/ **** fpt_creg_save_area ; 
 TYPE_3__ fpu ; 
 int /*<<< orphan*/ **** gmap ; 
 int /*<<< orphan*/ **** gpregs_save_area ; 
 int /*<<< orphan*/ **** gprs ; 
 int /*<<< orphan*/ **** guarded_storage_save_area ; 
 int /*<<< orphan*/ **** int_clock ; 
 int /*<<< orphan*/ **** int_code ; 
 int /*<<< orphan*/ **** int_parm ; 
 int /*<<< orphan*/ **** int_parm_long ; 
 int /*<<< orphan*/ **** io_int_parm ; 
 int /*<<< orphan*/ **** io_int_word ; 
 int /*<<< orphan*/ **** io_new_psw ; 
 int /*<<< orphan*/ **** io_old_psw ; 
 int /*<<< orphan*/ **** ipib ; 
 int /*<<< orphan*/ **** kernel_stack ; 
 int /*<<< orphan*/ **** kexec_sha_region ; 
 int /*<<< orphan*/ **** ksp ; 
 int /*<<< orphan*/ **** kvm_s390_sie_block ; 
 int /*<<< orphan*/ **** last_break ; 
 int /*<<< orphan*/ **** last_update_clock ; 
 int /*<<< orphan*/ **** last_update_timer ; 
 int /*<<< orphan*/ **** len ; 
 int /*<<< orphan*/ **** lowcore ; 
 int /*<<< orphan*/ **** lpp ; 
 int /*<<< orphan*/ **** machine_flags ; 
 int /*<<< orphan*/ **** mcck_clock ; 
 int /*<<< orphan*/ **** mcck_enter_timer ; 
 int /*<<< orphan*/ **** mcck_interruption_code ; 
 int /*<<< orphan*/ **** mcck_new_psw ; 
 int /*<<< orphan*/ **** mcck_old_psw ; 
 int /*<<< orphan*/ **** mcesa ; 
 int /*<<< orphan*/ **** mcesad ; 
 int /*<<< orphan*/ **** mon_class_num ; 
 int /*<<< orphan*/ **** monitor_code ; 
 int /*<<< orphan*/ **** nodat_stack ; 
 int /*<<< orphan*/ **** node_id ; 
 int /*<<< orphan*/ **** op_access_id ; 
 int /*<<< orphan*/ **** orig_gpr2 ; 
 int /*<<< orphan*/ **** per_access_id ; 
 int /*<<< orphan*/ **** per_address ; 
 int /*<<< orphan*/ **** per_atmid ; 
 int /*<<< orphan*/ **** per_code ; 
 TYPE_2__ per_event ; 
 int /*<<< orphan*/ **** percpu_offset ; 
 int /*<<< orphan*/ **** pgm_code ; 
 int /*<<< orphan*/ **** pgm_ilc ; 
 int /*<<< orphan*/ **** pgm_tdb ; 
 int /*<<< orphan*/ **** pid ; 
 int /*<<< orphan*/ **** preempt_count ; 
 int /*<<< orphan*/ **** prefixreg_save_area ; 
 int /*<<< orphan*/ **** prog0c ; 
 int /*<<< orphan*/ **** prog20 ; 
 int /*<<< orphan*/ **** program_new_psw ; 
 int /*<<< orphan*/ **** program_old_psw ; 
 int /*<<< orphan*/ **** psw ; 
 int /*<<< orphan*/ **** psw_save_area ; 
 int /*<<< orphan*/ **** pt_regs ; 
 int /*<<< orphan*/ **** restart_data ; 
 int /*<<< orphan*/ **** restart_fn ; 
 int /*<<< orphan*/ **** restart_old_psw ; 
 int /*<<< orphan*/ **** restart_psw ; 
 int /*<<< orphan*/ **** restart_source ; 
 int /*<<< orphan*/ **** restart_stack ; 
 int /*<<< orphan*/ **** return_mcck_psw ; 
 int /*<<< orphan*/ **** return_psw ; 
 int /*<<< orphan*/ **** s390_idle_data ; 
 int /*<<< orphan*/ **** save_area_async ; 
 int /*<<< orphan*/ **** save_area_restart ; 
 int /*<<< orphan*/ **** save_area_sync ; 
 int /*<<< orphan*/ **** stack ; 
 int /*<<< orphan*/ **** stack_frame ; 
 int /*<<< orphan*/ **** start ; 
 int /*<<< orphan*/ **** steal_timer ; 
 int /*<<< orphan*/ **** stfl_fac_list ; 
 int /*<<< orphan*/ **** stfle_fac_list ; 
 int /*<<< orphan*/ **** subchannel_id ; 
 int /*<<< orphan*/ **** subchannel_nr ; 
 int /*<<< orphan*/ **** svc_code ; 
 int /*<<< orphan*/ **** svc_ilc ; 
 int /*<<< orphan*/ **** svc_new_psw ; 
 int /*<<< orphan*/ **** svc_old_psw ; 
 int /*<<< orphan*/ **** sync_enter_timer ; 
 int /*<<< orphan*/ **** sys_call_table ; 
 int /*<<< orphan*/ **** system_timer ; 
 int /*<<< orphan*/ **** task_struct ; 
 int /*<<< orphan*/ **** tb_update_count ; 
 int /*<<< orphan*/ **** thread ; 
 TYPE_1__ thread_info ; 
 int /*<<< orphan*/ **** thread_struct ; 
 int /*<<< orphan*/ **** timer_idle_enter ; 
 int /*<<< orphan*/ **** timer_idle_exit ; 
 int /*<<< orphan*/ **** tk_mult ; 
 int /*<<< orphan*/ **** tk_shift ; 
 int /*<<< orphan*/ **** tod_progreg_save_area ; 
 int /*<<< orphan*/ **** trans_exc_code ; 
 int /*<<< orphan*/ **** trap_tdb ; 
 int /*<<< orphan*/ **** ts_dir ; 
 int /*<<< orphan*/ **** ts_end ; 
 int /*<<< orphan*/ **** tz_minuteswest ; 
 int /*<<< orphan*/ **** user_asce ; 
 int /*<<< orphan*/ **** user_timer ; 
 int /*<<< orphan*/ **** vdso_asce ; 
 int /*<<< orphan*/ **** vdso_data ; 
 int /*<<< orphan*/ **** vdso_per_cpu_data ; 
 int /*<<< orphan*/ **** wtom_clock_nsec ; 
 int /*<<< orphan*/ **** wtom_clock_sec ; 
 int /*<<< orphan*/ **** wtom_coarse_nsec ; 
 int /*<<< orphan*/ **** wtom_coarse_sec ; 
 int /*<<< orphan*/ **** xtime_clock_nsec ; 
 int /*<<< orphan*/ **** xtime_clock_sec ; 
 int /*<<< orphan*/ **** xtime_coarse_nsec ; 
 int /*<<< orphan*/ **** xtime_coarse_sec ; 
 int /*<<< orphan*/ **** xtime_tod_stamp ; 

int main(void)
{
	/* task struct offsets */
	OFFSET(__TASK_stack, task_struct, stack);
	OFFSET(__TASK_thread, task_struct, thread);
	OFFSET(__TASK_pid, task_struct, pid);
	BLANK();
	/* thread struct offsets */
	OFFSET(__THREAD_ksp, thread_struct, ksp);
	OFFSET(__THREAD_sysc_table,  thread_struct, sys_call_table);
	OFFSET(__THREAD_last_break, thread_struct, last_break);
	OFFSET(__THREAD_FPU_fpc, thread_struct, fpu.fpc);
	OFFSET(__THREAD_FPU_regs, thread_struct, fpu.regs);
	OFFSET(__THREAD_per_cause, thread_struct, per_event.cause);
	OFFSET(__THREAD_per_address, thread_struct, per_event.address);
	OFFSET(__THREAD_per_paid, thread_struct, per_event.paid);
	OFFSET(__THREAD_trap_tdb, thread_struct, trap_tdb);
	BLANK();
	/* thread info offsets */
	OFFSET(__TI_flags, task_struct, thread_info.flags);
	BLANK();
	/* pt_regs offsets */
	OFFSET(__PT_ARGS, pt_regs, args);
	OFFSET(__PT_PSW, pt_regs, psw);
	OFFSET(__PT_GPRS, pt_regs, gprs);
	OFFSET(__PT_ORIG_GPR2, pt_regs, orig_gpr2);
	OFFSET(__PT_INT_CODE, pt_regs, int_code);
	OFFSET(__PT_INT_PARM, pt_regs, int_parm);
	OFFSET(__PT_INT_PARM_LONG, pt_regs, int_parm_long);
	OFFSET(__PT_FLAGS, pt_regs, flags);
	DEFINE(__PT_SIZE, sizeof(struct pt_regs));
	BLANK();
	/* stack_frame offsets */
	OFFSET(__SF_BACKCHAIN, stack_frame, back_chain);
	OFFSET(__SF_GPRS, stack_frame, gprs);
	OFFSET(__SF_EMPTY, stack_frame, empty1);
	OFFSET(__SF_SIE_CONTROL, stack_frame, empty1[0]);
	OFFSET(__SF_SIE_SAVEAREA, stack_frame, empty1[1]);
	OFFSET(__SF_SIE_REASON, stack_frame, empty1[2]);
	OFFSET(__SF_SIE_FLAGS, stack_frame, empty1[3]);
	BLANK();
	/* timeval/timezone offsets for use by vdso */
	OFFSET(__VDSO_UPD_COUNT, vdso_data, tb_update_count);
	OFFSET(__VDSO_XTIME_STAMP, vdso_data, xtime_tod_stamp);
	OFFSET(__VDSO_XTIME_SEC, vdso_data, xtime_clock_sec);
	OFFSET(__VDSO_XTIME_NSEC, vdso_data, xtime_clock_nsec);
	OFFSET(__VDSO_XTIME_CRS_SEC, vdso_data, xtime_coarse_sec);
	OFFSET(__VDSO_XTIME_CRS_NSEC, vdso_data, xtime_coarse_nsec);
	OFFSET(__VDSO_WTOM_SEC, vdso_data, wtom_clock_sec);
	OFFSET(__VDSO_WTOM_NSEC, vdso_data, wtom_clock_nsec);
	OFFSET(__VDSO_WTOM_CRS_SEC, vdso_data, wtom_coarse_sec);
	OFFSET(__VDSO_WTOM_CRS_NSEC, vdso_data, wtom_coarse_nsec);
	OFFSET(__VDSO_TIMEZONE, vdso_data, tz_minuteswest);
	OFFSET(__VDSO_ECTG_OK, vdso_data, ectg_available);
	OFFSET(__VDSO_TK_MULT, vdso_data, tk_mult);
	OFFSET(__VDSO_TK_SHIFT, vdso_data, tk_shift);
	OFFSET(__VDSO_TS_DIR, vdso_data, ts_dir);
	OFFSET(__VDSO_TS_END, vdso_data, ts_end);
	OFFSET(__VDSO_ECTG_BASE, vdso_per_cpu_data, ectg_timer_base);
	OFFSET(__VDSO_ECTG_USER, vdso_per_cpu_data, ectg_user_time);
	OFFSET(__VDSO_CPU_NR, vdso_per_cpu_data, cpu_nr);
	OFFSET(__VDSO_NODE_ID, vdso_per_cpu_data, node_id);
	BLANK();
	/* constants used by the vdso */
	DEFINE(__CLOCK_REALTIME, CLOCK_REALTIME);
	DEFINE(__CLOCK_MONOTONIC, CLOCK_MONOTONIC);
	DEFINE(__CLOCK_REALTIME_COARSE, CLOCK_REALTIME_COARSE);
	DEFINE(__CLOCK_MONOTONIC_COARSE, CLOCK_MONOTONIC_COARSE);
	DEFINE(__CLOCK_THREAD_CPUTIME_ID, CLOCK_THREAD_CPUTIME_ID);
	DEFINE(__CLOCK_REALTIME_RES, MONOTONIC_RES_NSEC);
	DEFINE(__CLOCK_COARSE_RES, LOW_RES_NSEC);
	BLANK();
	/* idle data offsets */
	OFFSET(__CLOCK_IDLE_ENTER, s390_idle_data, clock_idle_enter);
	OFFSET(__CLOCK_IDLE_EXIT, s390_idle_data, clock_idle_exit);
	OFFSET(__TIMER_IDLE_ENTER, s390_idle_data, timer_idle_enter);
	OFFSET(__TIMER_IDLE_EXIT, s390_idle_data, timer_idle_exit);
	BLANK();
	/* hardware defined lowcore locations 0x000 - 0x1ff */
	OFFSET(__LC_EXT_PARAMS, lowcore, ext_params);
	OFFSET(__LC_EXT_CPU_ADDR, lowcore, ext_cpu_addr);
	OFFSET(__LC_EXT_INT_CODE, lowcore, ext_int_code);
	OFFSET(__LC_SVC_ILC, lowcore, svc_ilc);
	OFFSET(__LC_SVC_INT_CODE, lowcore, svc_code);
	OFFSET(__LC_PGM_ILC, lowcore, pgm_ilc);
	OFFSET(__LC_PGM_INT_CODE, lowcore, pgm_code);
	OFFSET(__LC_DATA_EXC_CODE, lowcore, data_exc_code);
	OFFSET(__LC_MON_CLASS_NR, lowcore, mon_class_num);
	OFFSET(__LC_PER_CODE, lowcore, per_code);
	OFFSET(__LC_PER_ATMID, lowcore, per_atmid);
	OFFSET(__LC_PER_ADDRESS, lowcore, per_address);
	OFFSET(__LC_EXC_ACCESS_ID, lowcore, exc_access_id);
	OFFSET(__LC_PER_ACCESS_ID, lowcore, per_access_id);
	OFFSET(__LC_OP_ACCESS_ID, lowcore, op_access_id);
	OFFSET(__LC_AR_MODE_ID, lowcore, ar_mode_id);
	OFFSET(__LC_TRANS_EXC_CODE, lowcore, trans_exc_code);
	OFFSET(__LC_MON_CODE, lowcore, monitor_code);
	OFFSET(__LC_SUBCHANNEL_ID, lowcore, subchannel_id);
	OFFSET(__LC_SUBCHANNEL_NR, lowcore, subchannel_nr);
	OFFSET(__LC_IO_INT_PARM, lowcore, io_int_parm);
	OFFSET(__LC_IO_INT_WORD, lowcore, io_int_word);
	OFFSET(__LC_STFL_FAC_LIST, lowcore, stfl_fac_list);
	OFFSET(__LC_STFLE_FAC_LIST, lowcore, stfle_fac_list);
	OFFSET(__LC_MCCK_CODE, lowcore, mcck_interruption_code);
	OFFSET(__LC_EXT_DAMAGE_CODE, lowcore, external_damage_code);
	OFFSET(__LC_MCCK_FAIL_STOR_ADDR, lowcore, failing_storage_address);
	OFFSET(__LC_LAST_BREAK, lowcore, breaking_event_addr);
	OFFSET(__LC_RST_OLD_PSW, lowcore, restart_old_psw);
	OFFSET(__LC_EXT_OLD_PSW, lowcore, external_old_psw);
	OFFSET(__LC_SVC_OLD_PSW, lowcore, svc_old_psw);
	OFFSET(__LC_PGM_OLD_PSW, lowcore, program_old_psw);
	OFFSET(__LC_MCK_OLD_PSW, lowcore, mcck_old_psw);
	OFFSET(__LC_IO_OLD_PSW, lowcore, io_old_psw);
	OFFSET(__LC_RST_NEW_PSW, lowcore, restart_psw);
	OFFSET(__LC_EXT_NEW_PSW, lowcore, external_new_psw);
	OFFSET(__LC_SVC_NEW_PSW, lowcore, svc_new_psw);
	OFFSET(__LC_PGM_NEW_PSW, lowcore, program_new_psw);
	OFFSET(__LC_MCK_NEW_PSW, lowcore, mcck_new_psw);
	OFFSET(__LC_IO_NEW_PSW, lowcore, io_new_psw);
	/* software defined lowcore locations 0x200 - 0xdff*/
	OFFSET(__LC_SAVE_AREA_SYNC, lowcore, save_area_sync);
	OFFSET(__LC_SAVE_AREA_ASYNC, lowcore, save_area_async);
	OFFSET(__LC_SAVE_AREA_RESTART, lowcore, save_area_restart);
	OFFSET(__LC_CPU_FLAGS, lowcore, cpu_flags);
	OFFSET(__LC_RETURN_PSW, lowcore, return_psw);
	OFFSET(__LC_RETURN_MCCK_PSW, lowcore, return_mcck_psw);
	OFFSET(__LC_SYNC_ENTER_TIMER, lowcore, sync_enter_timer);
	OFFSET(__LC_ASYNC_ENTER_TIMER, lowcore, async_enter_timer);
	OFFSET(__LC_MCCK_ENTER_TIMER, lowcore, mcck_enter_timer);
	OFFSET(__LC_EXIT_TIMER, lowcore, exit_timer);
	OFFSET(__LC_USER_TIMER, lowcore, user_timer);
	OFFSET(__LC_SYSTEM_TIMER, lowcore, system_timer);
	OFFSET(__LC_STEAL_TIMER, lowcore, steal_timer);
	OFFSET(__LC_LAST_UPDATE_TIMER, lowcore, last_update_timer);
	OFFSET(__LC_LAST_UPDATE_CLOCK, lowcore, last_update_clock);
	OFFSET(__LC_INT_CLOCK, lowcore, int_clock);
	OFFSET(__LC_MCCK_CLOCK, lowcore, mcck_clock);
	OFFSET(__LC_CLOCK_COMPARATOR, lowcore, clock_comparator);
	OFFSET(__LC_BOOT_CLOCK, lowcore, boot_clock);
	OFFSET(__LC_CURRENT, lowcore, current_task);
	OFFSET(__LC_KERNEL_STACK, lowcore, kernel_stack);
	OFFSET(__LC_ASYNC_STACK, lowcore, async_stack);
	OFFSET(__LC_NODAT_STACK, lowcore, nodat_stack);
	OFFSET(__LC_RESTART_STACK, lowcore, restart_stack);
	OFFSET(__LC_RESTART_FN, lowcore, restart_fn);
	OFFSET(__LC_RESTART_DATA, lowcore, restart_data);
	OFFSET(__LC_RESTART_SOURCE, lowcore, restart_source);
	OFFSET(__LC_USER_ASCE, lowcore, user_asce);
	OFFSET(__LC_VDSO_ASCE, lowcore, vdso_asce);
	OFFSET(__LC_LPP, lowcore, lpp);
	OFFSET(__LC_CURRENT_PID, lowcore, current_pid);
	OFFSET(__LC_PERCPU_OFFSET, lowcore, percpu_offset);
	OFFSET(__LC_VDSO_PER_CPU, lowcore, vdso_per_cpu_data);
	OFFSET(__LC_MACHINE_FLAGS, lowcore, machine_flags);
	OFFSET(__LC_PREEMPT_COUNT, lowcore, preempt_count);
	OFFSET(__LC_GMAP, lowcore, gmap);
	OFFSET(__LC_BR_R1, lowcore, br_r1_trampoline);
	/* software defined ABI-relevant lowcore locations 0xe00 - 0xe20 */
	OFFSET(__LC_DUMP_REIPL, lowcore, ipib);
	/* hardware defined lowcore locations 0x1000 - 0x18ff */
	OFFSET(__LC_MCESAD, lowcore, mcesad);
	OFFSET(__LC_EXT_PARAMS2, lowcore, ext_params2);
	OFFSET(__LC_FPREGS_SAVE_AREA, lowcore, floating_pt_save_area);
	OFFSET(__LC_GPREGS_SAVE_AREA, lowcore, gpregs_save_area);
	OFFSET(__LC_PSW_SAVE_AREA, lowcore, psw_save_area);
	OFFSET(__LC_PREFIX_SAVE_AREA, lowcore, prefixreg_save_area);
	OFFSET(__LC_FP_CREG_SAVE_AREA, lowcore, fpt_creg_save_area);
	OFFSET(__LC_TOD_PROGREG_SAVE_AREA, lowcore, tod_progreg_save_area);
	OFFSET(__LC_CPU_TIMER_SAVE_AREA, lowcore, cpu_timer_save_area);
	OFFSET(__LC_CLOCK_COMP_SAVE_AREA, lowcore, clock_comp_save_area);
	OFFSET(__LC_AREGS_SAVE_AREA, lowcore, access_regs_save_area);
	OFFSET(__LC_CREGS_SAVE_AREA, lowcore, cregs_save_area);
	OFFSET(__LC_PGM_TDB, lowcore, pgm_tdb);
	BLANK();
	/* extended machine check save area */
	OFFSET(__MCESA_GS_SAVE_AREA, mcesa, guarded_storage_save_area);
	BLANK();
	/* gmap/sie offsets */
	OFFSET(__GMAP_ASCE, gmap, asce);
	OFFSET(__SIE_PROG0C, kvm_s390_sie_block, prog0c);
	OFFSET(__SIE_PROG20, kvm_s390_sie_block, prog20);
	/* kexec_sha_region */
	OFFSET(__KEXEC_SHA_REGION_START, kexec_sha_region, start);
	OFFSET(__KEXEC_SHA_REGION_LEN, kexec_sha_region, len);
	DEFINE(__KEXEC_SHA_REGION_SIZE, sizeof(struct kexec_sha_region));
	return 0;
}