#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */

/* Variables and functions */
 int /*<<< orphan*/  test_pack_APPBARDATA () ; 
 int /*<<< orphan*/  test_pack_AUTO_SCROLL_DATA () ; 
 int /*<<< orphan*/  test_pack_BFFCALLBACK () ; 
 int /*<<< orphan*/  test_pack_BLOB () ; 
 int /*<<< orphan*/  test_pack_BROWSEINFOA () ; 
 int /*<<< orphan*/  test_pack_BROWSEINFOW () ; 
 int /*<<< orphan*/  test_pack_BSTR () ; 
 int /*<<< orphan*/  test_pack_BSTRBLOB () ; 
 int /*<<< orphan*/  test_pack_BYTE_BLOB () ; 
 int /*<<< orphan*/  test_pack_BYTE_SIZEDARR () ; 
 int /*<<< orphan*/  test_pack_CABINETSTATE () ; 
 int /*<<< orphan*/  test_pack_CIDA () ; 
 int /*<<< orphan*/  test_pack_CLIPDATA () ; 
 int /*<<< orphan*/  test_pack_CLIPFORMAT () ; 
 int /*<<< orphan*/  test_pack_CLSID () ; 
 int /*<<< orphan*/  test_pack_COAUTHIDENTITY () ; 
 int /*<<< orphan*/  test_pack_COAUTHINFO () ; 
 int /*<<< orphan*/  test_pack_CSFV () ; 
 int /*<<< orphan*/  test_pack_DATE () ; 
 int /*<<< orphan*/  test_pack_DOUBLE () ; 
 int /*<<< orphan*/  test_pack_DRAGINFOA () ; 
 int /*<<< orphan*/  test_pack_DRAGINFOW () ; 
 int /*<<< orphan*/  test_pack_DROPFILES () ; 
 int /*<<< orphan*/  test_pack_DWORD_SIZEDARR () ; 
 int /*<<< orphan*/  test_pack_FILEDESCRIPTORA () ; 
 int /*<<< orphan*/  test_pack_FILEDESCRIPTORW () ; 
 int /*<<< orphan*/  test_pack_FILEGROUPDESCRIPTORA () ; 
 int /*<<< orphan*/  test_pack_FILEGROUPDESCRIPTORW () ; 
 int /*<<< orphan*/  test_pack_FILEOP_FLAGS () ; 
 int /*<<< orphan*/  test_pack_FLAGGED_BYTE_BLOB () ; 
 int /*<<< orphan*/  test_pack_FLAGGED_WORD_BLOB () ; 
 int /*<<< orphan*/  test_pack_FMTID () ; 
 int /*<<< orphan*/  test_pack_HMETAFILEPICT () ; 
 int /*<<< orphan*/  test_pack_HYPER_SIZEDARR () ; 
 int /*<<< orphan*/  test_pack_IID () ; 
 int /*<<< orphan*/  test_pack_ITEMIDLIST () ; 
 int /*<<< orphan*/  test_pack_ITEMSPACING () ; 
 int /*<<< orphan*/  test_pack_LPBLOB () ; 
 int /*<<< orphan*/  test_pack_LPBROWSEINFOA () ; 
 int /*<<< orphan*/  test_pack_LPBROWSEINFOW () ; 
 int /*<<< orphan*/  test_pack_LPBSTR () ; 
 int /*<<< orphan*/  test_pack_LPBSTRBLOB () ; 
 int /*<<< orphan*/  test_pack_LPCABINETSTATE () ; 
 int /*<<< orphan*/  test_pack_LPCITEMIDLIST () ; 
 int /*<<< orphan*/  test_pack_LPCOLESTR () ; 
 int /*<<< orphan*/  test_pack_LPCSFV () ; 
 int /*<<< orphan*/  test_pack_LPCSHITEMID () ; 
 int /*<<< orphan*/  test_pack_LPCY () ; 
 int /*<<< orphan*/  test_pack_LPDECIMAL () ; 
 int /*<<< orphan*/  test_pack_LPDRAGINFOA () ; 
 int /*<<< orphan*/  test_pack_LPDRAGINFOW () ; 
 int /*<<< orphan*/  test_pack_LPDROPFILES () ; 
 int /*<<< orphan*/  test_pack_LPFILEDESCRIPTORA () ; 
 int /*<<< orphan*/  test_pack_LPFILEDESCRIPTORW () ; 
 int /*<<< orphan*/  test_pack_LPFILEGROUPDESCRIPTORA () ; 
 int /*<<< orphan*/  test_pack_LPFILEGROUPDESCRIPTORW () ; 
 int /*<<< orphan*/  test_pack_LPFNVIEWCALLBACK () ; 
 int /*<<< orphan*/  test_pack_LPIDA () ; 
 int /*<<< orphan*/  test_pack_LPITEMIDLIST () ; 
 int /*<<< orphan*/  test_pack_LPOLESTR () ; 
 int /*<<< orphan*/  test_pack_LPQCMINFO () ; 
 int /*<<< orphan*/  test_pack_LPSHChangeDWORDAsIDList () ; 
 int /*<<< orphan*/  test_pack_LPSHChangeProductKeyAsIDList () ; 
 int /*<<< orphan*/  test_pack_LPSHDESCRIPTIONID () ; 
 int /*<<< orphan*/  test_pack_LPSHELLDETAILS () ; 
 int /*<<< orphan*/  test_pack_LPSHELLEXECUTEINFOA () ; 
 int /*<<< orphan*/  test_pack_LPSHELLEXECUTEINFOW () ; 
 int /*<<< orphan*/  test_pack_LPSHELLFLAGSTATE () ; 
 int /*<<< orphan*/  test_pack_LPSHELLSTATE () ; 
 int /*<<< orphan*/  test_pack_LPSHFILEOPSTRUCTA () ; 
 int /*<<< orphan*/  test_pack_LPSHFILEOPSTRUCTW () ; 
 int /*<<< orphan*/  test_pack_LPSHITEMID () ; 
 int /*<<< orphan*/  test_pack_LPSHNAMEMAPPINGA () ; 
 int /*<<< orphan*/  test_pack_LPSHNAMEMAPPINGW () ; 
 int /*<<< orphan*/  test_pack_LPSTRRET () ; 
 int /*<<< orphan*/  test_pack_LPTBINFO () ; 
 int /*<<< orphan*/  test_pack_NOTIFYICONDATAA () ; 
 int /*<<< orphan*/  test_pack_NOTIFYICONDATAW () ; 
 int /*<<< orphan*/  test_pack_OLECHAR () ; 
 int /*<<< orphan*/  test_pack_PAPPBARDATA () ; 
 int /*<<< orphan*/  test_pack_PBROWSEINFOA () ; 
 int /*<<< orphan*/  test_pack_PBROWSEINFOW () ; 
 int /*<<< orphan*/  test_pack_PNOTIFYICONDATAA () ; 
 int /*<<< orphan*/  test_pack_PNOTIFYICONDATAW () ; 
 int /*<<< orphan*/  test_pack_PRINTEROP_FLAGS () ; 
 int /*<<< orphan*/  test_pack_PROPID () ; 
 int /*<<< orphan*/  test_pack_QCMINFO () ; 
 int /*<<< orphan*/  test_pack_QCMINFO_IDMAP () ; 
 int /*<<< orphan*/  test_pack_QCMINFO_IDMAP_PLACEMENT () ; 
 int /*<<< orphan*/  test_pack_RemHBITMAP () ; 
 int /*<<< orphan*/  test_pack_RemHENHMETAFILE () ; 
 int /*<<< orphan*/  test_pack_RemHGLOBAL () ; 
 int /*<<< orphan*/  test_pack_RemHMETAFILEPICT () ; 
 int /*<<< orphan*/  test_pack_RemHPALETTE () ; 
 int /*<<< orphan*/  test_pack_SCODE () ; 
 int /*<<< orphan*/  test_pack_SFV_CREATE () ; 
 int /*<<< orphan*/  test_pack_SHChangeDWORDAsIDList () ; 
 int /*<<< orphan*/  test_pack_SHChangeNotifyEntry () ; 
 int /*<<< orphan*/  test_pack_SHChangeProductKeyAsIDList () ; 
 int /*<<< orphan*/  test_pack_SHDESCRIPTIONID () ; 
 int /*<<< orphan*/  test_pack_SHELLDETAILS () ; 
 int /*<<< orphan*/  test_pack_SHELLEXECUTEINFOA () ; 
 int /*<<< orphan*/  test_pack_SHELLEXECUTEINFOW () ; 
 int /*<<< orphan*/  test_pack_SHELLFLAGSTATE () ; 
 int /*<<< orphan*/  test_pack_SHELLSTATE () ; 
 int /*<<< orphan*/  test_pack_SHFILEINFOA () ; 
 int /*<<< orphan*/  test_pack_SHFILEINFOW () ; 
 int /*<<< orphan*/  test_pack_SHFILEOPSTRUCTA () ; 
 int /*<<< orphan*/  test_pack_SHFILEOPSTRUCTW () ; 
 int /*<<< orphan*/  test_pack_SHITEMID () ; 
 int /*<<< orphan*/  test_pack_SHNAMEMAPPINGA () ; 
 int /*<<< orphan*/  test_pack_SHNAMEMAPPINGW () ; 
 int /*<<< orphan*/  test_pack_STRRET () ; 
 int /*<<< orphan*/  test_pack_TBINFO () ; 
 int /*<<< orphan*/  test_pack_UP_BYTE_BLOB () ; 
 int /*<<< orphan*/  test_pack_UP_FLAGGED_BYTE_BLOB () ; 
 int /*<<< orphan*/  test_pack_UP_FLAGGED_WORD_BLOB () ; 
 int /*<<< orphan*/  test_pack_VARIANT_BOOL () ; 
 int /*<<< orphan*/  test_pack_VARTYPE () ; 
 int /*<<< orphan*/  test_pack_WORD_SIZEDARR () ; 
 int /*<<< orphan*/  test_pack_remoteMETAFILEPICT () ; 
 int /*<<< orphan*/  test_pack_userBITMAP () ; 
 int /*<<< orphan*/  test_pack_userCLIPFORMAT () ; 
 int /*<<< orphan*/  test_pack_userHBITMAP () ; 
 int /*<<< orphan*/  test_pack_userHENHMETAFILE () ; 
 int /*<<< orphan*/  test_pack_userHGLOBAL () ; 
 int /*<<< orphan*/  test_pack_userHMETAFILE () ; 
 int /*<<< orphan*/  test_pack_userHMETAFILEPICT () ; 
 int /*<<< orphan*/  test_pack_userHPALETTE () ; 
 int /*<<< orphan*/  test_pack_wireBSTR () ; 
 int /*<<< orphan*/  test_pack_wireCLIPFORMAT () ; 
 int /*<<< orphan*/  test_pack_wireHBITMAP () ; 
 int /*<<< orphan*/  test_pack_wireHENHMETAFILE () ; 
 int /*<<< orphan*/  test_pack_wireHGLOBAL () ; 
 int /*<<< orphan*/  test_pack_wireHMETAFILE () ; 
 int /*<<< orphan*/  test_pack_wireHMETAFILEPICT () ; 
 int /*<<< orphan*/  test_pack_wireHPALETTE () ; 

__attribute__((used)) static void test_pack(void)
{
    test_pack_APPBARDATA();
    test_pack_AUTO_SCROLL_DATA();
    test_pack_BFFCALLBACK();
    test_pack_BLOB();
    test_pack_BROWSEINFOA();
    test_pack_BROWSEINFOW();
    test_pack_BSTR();
    test_pack_BSTRBLOB();
    test_pack_BYTE_BLOB();
    test_pack_BYTE_SIZEDARR();
    test_pack_CABINETSTATE();
    test_pack_CIDA();
    test_pack_CLIPDATA();
    test_pack_CLIPFORMAT();
    test_pack_CLSID();
    test_pack_COAUTHIDENTITY();
    test_pack_COAUTHINFO();
    test_pack_CSFV();
    test_pack_DATE();
    test_pack_DOUBLE();
    test_pack_DRAGINFOA();
    test_pack_DRAGINFOW();
    test_pack_DROPFILES();
    test_pack_DWORD_SIZEDARR();
    test_pack_FILEDESCRIPTORA();
    test_pack_FILEDESCRIPTORW();
    test_pack_FILEGROUPDESCRIPTORA();
    test_pack_FILEGROUPDESCRIPTORW();
    test_pack_FILEOP_FLAGS();
    test_pack_FLAGGED_BYTE_BLOB();
    test_pack_FLAGGED_WORD_BLOB();
    test_pack_FMTID();
    test_pack_HMETAFILEPICT();
    test_pack_HYPER_SIZEDARR();
    test_pack_IID();
    test_pack_ITEMIDLIST();
    test_pack_ITEMSPACING();
    test_pack_LPBLOB();
    test_pack_LPBROWSEINFOA();
    test_pack_LPBROWSEINFOW();
    test_pack_LPBSTR();
    test_pack_LPBSTRBLOB();
    test_pack_LPCABINETSTATE();
    test_pack_LPCITEMIDLIST();
    test_pack_LPCOLESTR();
    test_pack_LPCSFV();
    test_pack_LPCSHITEMID();
    test_pack_LPCY();
    test_pack_LPDECIMAL();
    test_pack_LPDRAGINFOA();
    test_pack_LPDRAGINFOW();
    test_pack_LPDROPFILES();
    test_pack_LPFILEDESCRIPTORA();
    test_pack_LPFILEDESCRIPTORW();
    test_pack_LPFILEGROUPDESCRIPTORA();
    test_pack_LPFILEGROUPDESCRIPTORW();
    test_pack_LPFNVIEWCALLBACK();
    test_pack_LPIDA();
    test_pack_LPITEMIDLIST();
    test_pack_LPOLESTR();
    test_pack_LPQCMINFO();
    test_pack_LPSHChangeDWORDAsIDList();
    test_pack_LPSHChangeProductKeyAsIDList();
    test_pack_LPSHDESCRIPTIONID();
    test_pack_LPSHELLDETAILS();
    test_pack_LPSHELLEXECUTEINFOA();
    test_pack_LPSHELLEXECUTEINFOW();
    test_pack_LPSHELLFLAGSTATE();
    test_pack_LPSHELLSTATE();
    test_pack_LPSHFILEOPSTRUCTA();
    test_pack_LPSHFILEOPSTRUCTW();
    test_pack_LPSHITEMID();
    test_pack_LPSHNAMEMAPPINGA();
    test_pack_LPSHNAMEMAPPINGW();
    test_pack_LPSTRRET();
    test_pack_LPTBINFO();
    test_pack_NOTIFYICONDATAA();
    test_pack_NOTIFYICONDATAW();
    test_pack_OLECHAR();
    test_pack_PAPPBARDATA();
    test_pack_PBROWSEINFOA();
    test_pack_PBROWSEINFOW();
    test_pack_PNOTIFYICONDATAA();
    test_pack_PNOTIFYICONDATAW();
    test_pack_PRINTEROP_FLAGS();
    test_pack_PROPID();
    test_pack_QCMINFO();
    test_pack_QCMINFO_IDMAP();
    test_pack_QCMINFO_IDMAP_PLACEMENT();
    test_pack_RemHBITMAP();
    test_pack_RemHENHMETAFILE();
    test_pack_RemHGLOBAL();
    test_pack_RemHMETAFILEPICT();
    test_pack_RemHPALETTE();
    test_pack_SCODE();
    test_pack_SFV_CREATE();
    test_pack_SHChangeDWORDAsIDList();
    test_pack_SHChangeNotifyEntry();
    test_pack_SHChangeProductKeyAsIDList();
    test_pack_SHDESCRIPTIONID();
    test_pack_SHELLDETAILS();
    test_pack_SHELLEXECUTEINFOA();
    test_pack_SHELLEXECUTEINFOW();
    test_pack_SHELLFLAGSTATE();
    test_pack_SHELLSTATE();
    test_pack_SHFILEINFOA();
    test_pack_SHFILEINFOW();
    test_pack_SHFILEOPSTRUCTA();
    test_pack_SHFILEOPSTRUCTW();
    test_pack_SHITEMID();
    test_pack_SHNAMEMAPPINGA();
    test_pack_SHNAMEMAPPINGW();
    test_pack_STRRET();
    test_pack_TBINFO();
    test_pack_UP_BYTE_BLOB();
    test_pack_UP_FLAGGED_BYTE_BLOB();
    test_pack_UP_FLAGGED_WORD_BLOB();
    test_pack_VARIANT_BOOL();
    test_pack_VARTYPE();
    test_pack_WORD_SIZEDARR();
    test_pack_remoteMETAFILEPICT();
    test_pack_userBITMAP();
    test_pack_userCLIPFORMAT();
    test_pack_userHBITMAP();
    test_pack_userHENHMETAFILE();
    test_pack_userHGLOBAL();
    test_pack_userHMETAFILE();
    test_pack_userHMETAFILEPICT();
    test_pack_userHPALETTE();
    test_pack_wireBSTR();
    test_pack_wireCLIPFORMAT();
    test_pack_wireHBITMAP();
    test_pack_wireHENHMETAFILE();
    test_pack_wireHGLOBAL();
    test_pack_wireHMETAFILE();
    test_pack_wireHMETAFILEPICT();
    test_pack_wireHPALETTE();
}