#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
struct iavf_hw {char const* err_str; } ;
typedef  enum iavf_status { ____Placeholder_iavf_status } iavf_status ;

/* Variables and functions */
#define  IAVF_ERR_ADAPTER_STOPPED 193 
#define  IAVF_ERR_ADMIN_QUEUE_CRITICAL_ERROR 192 
#define  IAVF_ERR_ADMIN_QUEUE_ERROR 191 
#define  IAVF_ERR_ADMIN_QUEUE_FULL 190 
#define  IAVF_ERR_ADMIN_QUEUE_NO_WORK 189 
#define  IAVF_ERR_ADMIN_QUEUE_TIMEOUT 188 
#define  IAVF_ERR_AUTONEG_NOT_COMPLETE 187 
#define  IAVF_ERR_BACKING_PAGE_ERROR 186 
#define  IAVF_ERR_BAD_IWARP_CQE 185 
#define  IAVF_ERR_BAD_PTR 184 
#define  IAVF_ERR_BUF_TOO_SHORT 183 
#define  IAVF_ERR_CONFIG 182 
#define  IAVF_ERR_CQP_COMPL_ERROR 181 
#define  IAVF_ERR_DEVICE_NOT_SUPPORTED 180 
#define  IAVF_ERR_DIAG_TEST_FAILED 179 
#define  IAVF_ERR_FIRMWARE_API_VERSION 178 
#define  IAVF_ERR_FLUSHED_QUEUE 177 
#define  IAVF_ERR_INVALID_AEQ_ID 176 
#define  IAVF_ERR_INVALID_ALIGNMENT 175 
#define  IAVF_ERR_INVALID_ARP_INDEX 174 
#define  IAVF_ERR_INVALID_CEQ_ID 173 
#define  IAVF_ERR_INVALID_CQ_ID 172 
#define  IAVF_ERR_INVALID_FPM_FUNC_ID 171 
#define  IAVF_ERR_INVALID_FRAG_COUNT 170 
#define  IAVF_ERR_INVALID_HMCFN_ID 169 
#define  IAVF_ERR_INVALID_HMC_OBJ_COUNT 168 
#define  IAVF_ERR_INVALID_HMC_OBJ_INDEX 167 
#define  IAVF_ERR_INVALID_IMM_DATA_SIZE 166 
#define  IAVF_ERR_INVALID_LINK_SETTINGS 165 
#define  IAVF_ERR_INVALID_MAC_ADDR 164 
#define  IAVF_ERR_INVALID_PAGE_DESC_INDEX 163 
#define  IAVF_ERR_INVALID_PBLE_INDEX 162 
#define  IAVF_ERR_INVALID_PD_ID 161 
#define  IAVF_ERR_INVALID_PUSH_PAGE_INDEX 160 
#define  IAVF_ERR_INVALID_QP_ID 159 
#define  IAVF_ERR_INVALID_SD_INDEX 158 
#define  IAVF_ERR_INVALID_SD_TYPE 157 
#define  IAVF_ERR_INVALID_SIZE 156 
#define  IAVF_ERR_INVALID_SRQ_ARM_LIMIT 155 
#define  IAVF_ERR_INVALID_VF_ID 154 
#define  IAVF_ERR_LINK_SETUP 153 
#define  IAVF_ERR_MAC_TYPE 152 
#define  IAVF_ERR_MASTER_REQUESTS_PENDING 151 
#define  IAVF_ERR_MEMCPY_FAILED 150 
#define  IAVF_ERR_NOT_IMPLEMENTED 149 
#define  IAVF_ERR_NOT_READY 148 
#define  IAVF_ERR_NO_AVAILABLE_VSI 147 
#define  IAVF_ERR_NO_MEMORY 146 
#define  IAVF_ERR_NO_PBLCHUNKS_AVAILABLE 145 
#define  IAVF_ERR_NVM 144 
#define  IAVF_ERR_NVM_BLANK_MODE 143 
#define  IAVF_ERR_NVM_CHECKSUM 142 
#define  IAVF_ERR_OPCODE_MISMATCH 141 
#define  IAVF_ERR_PARAM 140 
#define  IAVF_ERR_PE_DOORBELL_NOT_ENABLED 139 
#define  IAVF_ERR_PHY 138 
#define  IAVF_ERR_QP_INVALID_MSG_SIZE 137 
#define  IAVF_ERR_QP_TOOMANY_WRS_POSTED 136 
#define  IAVF_ERR_QUEUE_EMPTY 135 
#define  IAVF_ERR_RESET_FAILED 134 
#define  IAVF_ERR_RING_FULL 133 
#define  IAVF_ERR_SRQ_ENABLED 132 
#define  IAVF_ERR_SWFW_SYNC 131 
#define  IAVF_ERR_TIMEOUT 130 
#define  IAVF_ERR_UNKNOWN_PHY 129 
#define  IAVF_NOT_SUPPORTED 128 
 int /*<<< orphan*/  snprintf (char const*,int,char*,int) ; 

const char *iavf_stat_str(struct iavf_hw *hw, enum iavf_status stat_err)
{
	switch (stat_err) {
	case 0:
		return "OK";
	case IAVF_ERR_NVM:
		return "IAVF_ERR_NVM";
	case IAVF_ERR_NVM_CHECKSUM:
		return "IAVF_ERR_NVM_CHECKSUM";
	case IAVF_ERR_PHY:
		return "IAVF_ERR_PHY";
	case IAVF_ERR_CONFIG:
		return "IAVF_ERR_CONFIG";
	case IAVF_ERR_PARAM:
		return "IAVF_ERR_PARAM";
	case IAVF_ERR_MAC_TYPE:
		return "IAVF_ERR_MAC_TYPE";
	case IAVF_ERR_UNKNOWN_PHY:
		return "IAVF_ERR_UNKNOWN_PHY";
	case IAVF_ERR_LINK_SETUP:
		return "IAVF_ERR_LINK_SETUP";
	case IAVF_ERR_ADAPTER_STOPPED:
		return "IAVF_ERR_ADAPTER_STOPPED";
	case IAVF_ERR_INVALID_MAC_ADDR:
		return "IAVF_ERR_INVALID_MAC_ADDR";
	case IAVF_ERR_DEVICE_NOT_SUPPORTED:
		return "IAVF_ERR_DEVICE_NOT_SUPPORTED";
	case IAVF_ERR_MASTER_REQUESTS_PENDING:
		return "IAVF_ERR_MASTER_REQUESTS_PENDING";
	case IAVF_ERR_INVALID_LINK_SETTINGS:
		return "IAVF_ERR_INVALID_LINK_SETTINGS";
	case IAVF_ERR_AUTONEG_NOT_COMPLETE:
		return "IAVF_ERR_AUTONEG_NOT_COMPLETE";
	case IAVF_ERR_RESET_FAILED:
		return "IAVF_ERR_RESET_FAILED";
	case IAVF_ERR_SWFW_SYNC:
		return "IAVF_ERR_SWFW_SYNC";
	case IAVF_ERR_NO_AVAILABLE_VSI:
		return "IAVF_ERR_NO_AVAILABLE_VSI";
	case IAVF_ERR_NO_MEMORY:
		return "IAVF_ERR_NO_MEMORY";
	case IAVF_ERR_BAD_PTR:
		return "IAVF_ERR_BAD_PTR";
	case IAVF_ERR_RING_FULL:
		return "IAVF_ERR_RING_FULL";
	case IAVF_ERR_INVALID_PD_ID:
		return "IAVF_ERR_INVALID_PD_ID";
	case IAVF_ERR_INVALID_QP_ID:
		return "IAVF_ERR_INVALID_QP_ID";
	case IAVF_ERR_INVALID_CQ_ID:
		return "IAVF_ERR_INVALID_CQ_ID";
	case IAVF_ERR_INVALID_CEQ_ID:
		return "IAVF_ERR_INVALID_CEQ_ID";
	case IAVF_ERR_INVALID_AEQ_ID:
		return "IAVF_ERR_INVALID_AEQ_ID";
	case IAVF_ERR_INVALID_SIZE:
		return "IAVF_ERR_INVALID_SIZE";
	case IAVF_ERR_INVALID_ARP_INDEX:
		return "IAVF_ERR_INVALID_ARP_INDEX";
	case IAVF_ERR_INVALID_FPM_FUNC_ID:
		return "IAVF_ERR_INVALID_FPM_FUNC_ID";
	case IAVF_ERR_QP_INVALID_MSG_SIZE:
		return "IAVF_ERR_QP_INVALID_MSG_SIZE";
	case IAVF_ERR_QP_TOOMANY_WRS_POSTED:
		return "IAVF_ERR_QP_TOOMANY_WRS_POSTED";
	case IAVF_ERR_INVALID_FRAG_COUNT:
		return "IAVF_ERR_INVALID_FRAG_COUNT";
	case IAVF_ERR_QUEUE_EMPTY:
		return "IAVF_ERR_QUEUE_EMPTY";
	case IAVF_ERR_INVALID_ALIGNMENT:
		return "IAVF_ERR_INVALID_ALIGNMENT";
	case IAVF_ERR_FLUSHED_QUEUE:
		return "IAVF_ERR_FLUSHED_QUEUE";
	case IAVF_ERR_INVALID_PUSH_PAGE_INDEX:
		return "IAVF_ERR_INVALID_PUSH_PAGE_INDEX";
	case IAVF_ERR_INVALID_IMM_DATA_SIZE:
		return "IAVF_ERR_INVALID_IMM_DATA_SIZE";
	case IAVF_ERR_TIMEOUT:
		return "IAVF_ERR_TIMEOUT";
	case IAVF_ERR_OPCODE_MISMATCH:
		return "IAVF_ERR_OPCODE_MISMATCH";
	case IAVF_ERR_CQP_COMPL_ERROR:
		return "IAVF_ERR_CQP_COMPL_ERROR";
	case IAVF_ERR_INVALID_VF_ID:
		return "IAVF_ERR_INVALID_VF_ID";
	case IAVF_ERR_INVALID_HMCFN_ID:
		return "IAVF_ERR_INVALID_HMCFN_ID";
	case IAVF_ERR_BACKING_PAGE_ERROR:
		return "IAVF_ERR_BACKING_PAGE_ERROR";
	case IAVF_ERR_NO_PBLCHUNKS_AVAILABLE:
		return "IAVF_ERR_NO_PBLCHUNKS_AVAILABLE";
	case IAVF_ERR_INVALID_PBLE_INDEX:
		return "IAVF_ERR_INVALID_PBLE_INDEX";
	case IAVF_ERR_INVALID_SD_INDEX:
		return "IAVF_ERR_INVALID_SD_INDEX";
	case IAVF_ERR_INVALID_PAGE_DESC_INDEX:
		return "IAVF_ERR_INVALID_PAGE_DESC_INDEX";
	case IAVF_ERR_INVALID_SD_TYPE:
		return "IAVF_ERR_INVALID_SD_TYPE";
	case IAVF_ERR_MEMCPY_FAILED:
		return "IAVF_ERR_MEMCPY_FAILED";
	case IAVF_ERR_INVALID_HMC_OBJ_INDEX:
		return "IAVF_ERR_INVALID_HMC_OBJ_INDEX";
	case IAVF_ERR_INVALID_HMC_OBJ_COUNT:
		return "IAVF_ERR_INVALID_HMC_OBJ_COUNT";
	case IAVF_ERR_INVALID_SRQ_ARM_LIMIT:
		return "IAVF_ERR_INVALID_SRQ_ARM_LIMIT";
	case IAVF_ERR_SRQ_ENABLED:
		return "IAVF_ERR_SRQ_ENABLED";
	case IAVF_ERR_ADMIN_QUEUE_ERROR:
		return "IAVF_ERR_ADMIN_QUEUE_ERROR";
	case IAVF_ERR_ADMIN_QUEUE_TIMEOUT:
		return "IAVF_ERR_ADMIN_QUEUE_TIMEOUT";
	case IAVF_ERR_BUF_TOO_SHORT:
		return "IAVF_ERR_BUF_TOO_SHORT";
	case IAVF_ERR_ADMIN_QUEUE_FULL:
		return "IAVF_ERR_ADMIN_QUEUE_FULL";
	case IAVF_ERR_ADMIN_QUEUE_NO_WORK:
		return "IAVF_ERR_ADMIN_QUEUE_NO_WORK";
	case IAVF_ERR_BAD_IWARP_CQE:
		return "IAVF_ERR_BAD_IWARP_CQE";
	case IAVF_ERR_NVM_BLANK_MODE:
		return "IAVF_ERR_NVM_BLANK_MODE";
	case IAVF_ERR_NOT_IMPLEMENTED:
		return "IAVF_ERR_NOT_IMPLEMENTED";
	case IAVF_ERR_PE_DOORBELL_NOT_ENABLED:
		return "IAVF_ERR_PE_DOORBELL_NOT_ENABLED";
	case IAVF_ERR_DIAG_TEST_FAILED:
		return "IAVF_ERR_DIAG_TEST_FAILED";
	case IAVF_ERR_NOT_READY:
		return "IAVF_ERR_NOT_READY";
	case IAVF_NOT_SUPPORTED:
		return "IAVF_NOT_SUPPORTED";
	case IAVF_ERR_FIRMWARE_API_VERSION:
		return "IAVF_ERR_FIRMWARE_API_VERSION";
	case IAVF_ERR_ADMIN_QUEUE_CRITICAL_ERROR:
		return "IAVF_ERR_ADMIN_QUEUE_CRITICAL_ERROR";
	}

	snprintf(hw->err_str, sizeof(hw->err_str), "%d", stat_err);
	return hw->err_str;
}