#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  int /*<<< orphan*/  RAnalEsil ;

/* Variables and functions */
 int /*<<< orphan*/  esil_add ; 
 int /*<<< orphan*/  esil_addeq ; 
 int /*<<< orphan*/  esil_address ; 
 int /*<<< orphan*/  esil_and ; 
 int /*<<< orphan*/  esil_andeq ; 
 int /*<<< orphan*/  esil_asr ; 
 int /*<<< orphan*/  esil_asreq ; 
 int /*<<< orphan*/  esil_bf ; 
 int /*<<< orphan*/  esil_bigger ; 
 int /*<<< orphan*/  esil_bigger_equal ; 
 int /*<<< orphan*/  esil_bits ; 
 int /*<<< orphan*/  esil_break ; 
 int /*<<< orphan*/  esil_cf ; 
 int /*<<< orphan*/  esil_clear ; 
 int /*<<< orphan*/  esil_cmp ; 
 int /*<<< orphan*/  esil_dec ; 
 int /*<<< orphan*/  esil_deceq ; 
 int /*<<< orphan*/  esil_div ; 
 int /*<<< orphan*/  esil_diveq ; 
 int /*<<< orphan*/  esil_ds ; 
 int /*<<< orphan*/  esil_dup ; 
 int /*<<< orphan*/  esil_eq ; 
 int /*<<< orphan*/  esil_goto ; 
 int /*<<< orphan*/  esil_if ; 
 int /*<<< orphan*/  esil_inc ; 
 int /*<<< orphan*/  esil_inceq ; 
 int /*<<< orphan*/  esil_interrupt ; 
 int /*<<< orphan*/  esil_js ; 
 int /*<<< orphan*/  esil_jt ; 
 int /*<<< orphan*/  esil_lsl ; 
 int /*<<< orphan*/  esil_lsleq ; 
 int /*<<< orphan*/  esil_lsr ; 
 int /*<<< orphan*/  esil_lsreq ; 
 int /*<<< orphan*/  esil_mem_addeq ; 
 int /*<<< orphan*/  esil_mem_addeq1 ; 
 int /*<<< orphan*/  esil_mem_addeq2 ; 
 int /*<<< orphan*/  esil_mem_addeq4 ; 
 int /*<<< orphan*/  esil_mem_addeq8 ; 
 int /*<<< orphan*/  esil_mem_andeq ; 
 int /*<<< orphan*/  esil_mem_andeq1 ; 
 int /*<<< orphan*/  esil_mem_andeq2 ; 
 int /*<<< orphan*/  esil_mem_andeq4 ; 
 int /*<<< orphan*/  esil_mem_andeq8 ; 
 int /*<<< orphan*/  esil_mem_deceq ; 
 int /*<<< orphan*/  esil_mem_deceq1 ; 
 int /*<<< orphan*/  esil_mem_deceq2 ; 
 int /*<<< orphan*/  esil_mem_deceq4 ; 
 int /*<<< orphan*/  esil_mem_deceq8 ; 
 int /*<<< orphan*/  esil_mem_diveq ; 
 int /*<<< orphan*/  esil_mem_diveq1 ; 
 int /*<<< orphan*/  esil_mem_diveq2 ; 
 int /*<<< orphan*/  esil_mem_diveq4 ; 
 int /*<<< orphan*/  esil_mem_diveq8 ; 
 int /*<<< orphan*/  esil_mem_inceq ; 
 int /*<<< orphan*/  esil_mem_inceq1 ; 
 int /*<<< orphan*/  esil_mem_inceq2 ; 
 int /*<<< orphan*/  esil_mem_inceq4 ; 
 int /*<<< orphan*/  esil_mem_inceq8 ; 
 int /*<<< orphan*/  esil_mem_lsleq ; 
 int /*<<< orphan*/  esil_mem_lsleq1 ; 
 int /*<<< orphan*/  esil_mem_lsleq2 ; 
 int /*<<< orphan*/  esil_mem_lsleq4 ; 
 int /*<<< orphan*/  esil_mem_lsleq8 ; 
 int /*<<< orphan*/  esil_mem_lsreq ; 
 int /*<<< orphan*/  esil_mem_lsreq1 ; 
 int /*<<< orphan*/  esil_mem_lsreq2 ; 
 int /*<<< orphan*/  esil_mem_lsreq4 ; 
 int /*<<< orphan*/  esil_mem_lsreq8 ; 
 int /*<<< orphan*/  esil_mem_modeq ; 
 int /*<<< orphan*/  esil_mem_modeq1 ; 
 int /*<<< orphan*/  esil_mem_modeq2 ; 
 int /*<<< orphan*/  esil_mem_modeq4 ; 
 int /*<<< orphan*/  esil_mem_modeq8 ; 
 int /*<<< orphan*/  esil_mem_muleq ; 
 int /*<<< orphan*/  esil_mem_muleq1 ; 
 int /*<<< orphan*/  esil_mem_muleq2 ; 
 int /*<<< orphan*/  esil_mem_muleq4 ; 
 int /*<<< orphan*/  esil_mem_muleq8 ; 
 int /*<<< orphan*/  esil_mem_oreq ; 
 int /*<<< orphan*/  esil_mem_oreq1 ; 
 int /*<<< orphan*/  esil_mem_oreq2 ; 
 int /*<<< orphan*/  esil_mem_oreq4 ; 
 int /*<<< orphan*/  esil_mem_oreq8 ; 
 int /*<<< orphan*/  esil_mem_subeq ; 
 int /*<<< orphan*/  esil_mem_subeq1 ; 
 int /*<<< orphan*/  esil_mem_subeq2 ; 
 int /*<<< orphan*/  esil_mem_subeq4 ; 
 int /*<<< orphan*/  esil_mem_subeq8 ; 
 int /*<<< orphan*/  esil_mem_xoreq ; 
 int /*<<< orphan*/  esil_mem_xoreq1 ; 
 int /*<<< orphan*/  esil_mem_xoreq2 ; 
 int /*<<< orphan*/  esil_mem_xoreq4 ; 
 int /*<<< orphan*/  esil_mem_xoreq8 ; 
 int /*<<< orphan*/  esil_mod ; 
 int /*<<< orphan*/  esil_modeq ; 
 int /*<<< orphan*/  esil_mul ; 
 int /*<<< orphan*/  esil_muleq ; 
 int /*<<< orphan*/  esil_neg ; 
 int /*<<< orphan*/  esil_negeq ; 
 int /*<<< orphan*/  esil_nop ; 
 int /*<<< orphan*/  esil_num ; 
 int /*<<< orphan*/  esil_of ; 
 int /*<<< orphan*/  esil_or ; 
 int /*<<< orphan*/  esil_oreq ; 
 int /*<<< orphan*/  esil_peek ; 
 int /*<<< orphan*/  esil_peek1 ; 
 int /*<<< orphan*/  esil_peek16 ; 
 int /*<<< orphan*/  esil_peek2 ; 
 int /*<<< orphan*/  esil_peek3 ; 
 int /*<<< orphan*/  esil_peek4 ; 
 int /*<<< orphan*/  esil_peek8 ; 
 int /*<<< orphan*/  esil_peek_some ; 
 int /*<<< orphan*/  esil_pf ; 
 int /*<<< orphan*/  esil_poke ; 
 int /*<<< orphan*/  esil_poke1 ; 
 int /*<<< orphan*/  esil_poke16 ; 
 int /*<<< orphan*/  esil_poke2 ; 
 int /*<<< orphan*/  esil_poke3 ; 
 int /*<<< orphan*/  esil_poke4 ; 
 int /*<<< orphan*/  esil_poke8 ; 
 int /*<<< orphan*/  esil_poke_some ; 
 int /*<<< orphan*/  esil_pop ; 
 int /*<<< orphan*/  esil_repeat ; 
 int /*<<< orphan*/  esil_rol ; 
 int /*<<< orphan*/  esil_ror ; 
 int /*<<< orphan*/  esil_rs ; 
 int /*<<< orphan*/  esil_set_delay_slot ; 
 int /*<<< orphan*/  esil_set_jump_target ; 
 int /*<<< orphan*/  esil_set_jump_target_set ; 
 int /*<<< orphan*/  esil_sf ; 
 int /*<<< orphan*/  esil_smaller ; 
 int /*<<< orphan*/  esil_smaller_equal ; 
 int /*<<< orphan*/  esil_sub ; 
 int /*<<< orphan*/  esil_subeq ; 
 int /*<<< orphan*/  esil_swap ; 
 int /*<<< orphan*/  esil_todo ; 
 int /*<<< orphan*/  esil_trap ; 
 int /*<<< orphan*/  esil_weak_eq ; 
 int /*<<< orphan*/  esil_xor ; 
 int /*<<< orphan*/  esil_xoreq ; 
 int /*<<< orphan*/  esil_zf ; 
 int /*<<< orphan*/  r_anal_esil_dumpstack ; 
 int /*<<< orphan*/  r_anal_esil_set_op (int /*<<< orphan*/ *,char*,int /*<<< orphan*/ ) ; 

__attribute__((used)) static void r_anal_esil_setup_ops(RAnalEsil *esil) {
#define OP(x, y) r_anal_esil_set_op (esil, x, y)
	OP ("$", esil_interrupt);
	OP ("$z", esil_zf);
	OP ("$c", esil_cf);
	OP ("$b", esil_bf);
	OP ("$p", esil_pf);
	OP ("$s", esil_sf);
	OP ("$o", esil_of);
	OP ("$ds", esil_ds);
	OP ("$jt", esil_jt);
	OP ("$js", esil_js);
	OP ("$r", esil_rs);
	OP ("$$", esil_address);
	OP ("==", esil_cmp);
	OP ("<", esil_smaller);
	OP (">", esil_bigger);
	OP ("<=", esil_smaller_equal);
	OP (">=", esil_bigger_equal);
	OP ("?{", esil_if);
	OP ("<<", esil_lsl);
	OP ("<<=", esil_lsleq);
	OP (">>", esil_lsr);
	OP (">>=", esil_lsreq);
	OP (">>>>", esil_asr);
	OP (">>>>=", esil_asreq);
	OP (">>>", esil_ror);
	OP ("<<<", esil_rol);
	OP ("&", esil_and);
	OP ("&=", esil_andeq);
	OP ("}", esil_nop); // just to avoid push
	OP ("|", esil_or);
	OP ("|=", esil_oreq);
	OP ("!", esil_neg);
	OP ("!=", esil_negeq);
	OP ("=", esil_eq);
	OP (":=", esil_weak_eq);
	OP ("*", esil_mul);
	OP ("*=", esil_muleq);
	OP ("^", esil_xor);
	OP ("^=", esil_xoreq);
	OP ("+", esil_add);
	OP ("+=", esil_addeq);
	OP ("++", esil_inc);
	OP ("++=", esil_inceq);
	OP ("-", esil_sub);
	OP ("-=", esil_subeq);
	OP ("--", esil_dec);
	OP ("--=", esil_deceq);
	OP ("/", esil_div);
	OP ("/=", esil_diveq);
	OP ("%", esil_mod);
	OP ("%=", esil_modeq);
	OP ("=[]", esil_poke);
	OP ("=[1]", esil_poke1);
	OP ("=[2]", esil_poke2);
	OP ("=[3]", esil_poke3);
	OP ("=[4]", esil_poke4);
	OP ("=[8]", esil_poke8);
	OP ("=[16]", esil_poke16);
	OP ("|=[]", esil_mem_oreq);
	OP ("|=[1]", esil_mem_oreq1);
	OP ("|=[2]", esil_mem_oreq2);
	OP ("|=[4]", esil_mem_oreq4);
	OP ("|=[8]", esil_mem_oreq8);
	OP ("^=[]", esil_mem_xoreq);
	OP ("^=[1]", esil_mem_xoreq1);
	OP ("^=[2]", esil_mem_xoreq2);
	OP ("^=[4]", esil_mem_xoreq4);
	OP ("^=[8]", esil_mem_xoreq8);
	OP ("&=[]", esil_mem_andeq);
	OP ("&=[1]", esil_mem_andeq1);
	OP ("&=[2]", esil_mem_andeq2);
	OP ("&=[4]", esil_mem_andeq4);
	OP ("&=[8]", esil_mem_andeq8);
	OP ("+=[]", esil_mem_addeq);
	OP ("+=[1]", esil_mem_addeq1);
	OP ("+=[2]", esil_mem_addeq2);
	OP ("+=[4]", esil_mem_addeq4);
	OP ("+=[8]", esil_mem_addeq8);
	OP ("-=[]", esil_mem_subeq);
	OP ("-=[1]", esil_mem_subeq1);
	OP ("-=[2]", esil_mem_subeq2);
	OP ("-=[4]", esil_mem_subeq4);
	OP ("-=[8]", esil_mem_subeq8);
	OP ("%=[]", esil_mem_modeq);
	OP ("%=[1]", esil_mem_modeq1);
	OP ("%=[2]", esil_mem_modeq2);
	OP ("%=[4]", esil_mem_modeq4);
	OP ("%=[8]", esil_mem_modeq8);
	OP ("/=[]", esil_mem_diveq);
	OP ("/=[1]", esil_mem_diveq1);
	OP ("/=[2]", esil_mem_diveq2);
	OP ("/=[4]", esil_mem_diveq4);
	OP ("/=[8]", esil_mem_diveq8);
	OP ("*=[]", esil_mem_muleq);
	OP ("*=[1]", esil_mem_muleq1);
	OP ("*=[2]", esil_mem_muleq2);
	OP ("*=[4]", esil_mem_muleq4);
	OP ("*=[8]", esil_mem_muleq8);
	OP ("++=[]", esil_mem_inceq);
	OP ("++=[1]", esil_mem_inceq1);
	OP ("++=[2]", esil_mem_inceq2);
	OP ("++=[4]", esil_mem_inceq4);
	OP ("++=[8]", esil_mem_inceq8);
	OP ("--=[]", esil_mem_deceq);
	OP ("--=[1]", esil_mem_deceq1);
	OP ("--=[2]", esil_mem_deceq2);
	OP ("--=[4]", esil_mem_deceq4);
	OP ("--=[8]", esil_mem_deceq8);
        OP ("<<=[]", esil_mem_lsleq);
	OP ("<<=[1]", esil_mem_lsleq1);
	OP ("<<=[2]", esil_mem_lsleq2);
	OP ("<<=[4]", esil_mem_lsleq4);
	OP ("<<=[8]", esil_mem_lsleq8);
	OP (">>=[]", esil_mem_lsreq);
	OP (">>=[1]", esil_mem_lsreq1);
	OP (">>=[2]", esil_mem_lsreq2);
	OP (">>=[4]", esil_mem_lsreq4);
	OP (">>=[8]", esil_mem_lsreq8);
	OP ("[]", esil_peek);
	OP ("[*]", esil_peek_some);
	OP ("=[*]", esil_poke_some);
	OP ("[1]", esil_peek1);
	OP ("[2]", esil_peek2);
	OP ("[3]", esil_peek3);
	OP ("[4]", esil_peek4);
	OP ("[8]", esil_peek8);
	OP ("[16]", esil_peek16);
	OP ("STACK", r_anal_esil_dumpstack);
	OP ("REPEAT", esil_repeat);
	OP ("POP", esil_pop);
	OP ("TODO", esil_todo);
	OP ("GOTO", esil_goto);
	OP ("BREAK", esil_break);
	OP ("CLEAR", esil_clear);
	OP ("DUP", esil_dup);
	OP ("NUM", esil_num);
	OP ("SWAP", esil_swap);
	OP ("TRAP", esil_trap);
	OP ("BITS", esil_bits);
	OP ("SETJT", esil_set_jump_target);
	OP ("SETJTS", esil_set_jump_target_set);
	OP ("SETD", esil_set_delay_slot);
}