#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  int /*<<< orphan*/  mode_t ;

/* Variables and functions */
#define  ISCSI_FLASHNODE_ALIAS 264 
#define  ISCSI_FLASHNODE_AUTO_SND_TGT_DISABLE 263 
#define  ISCSI_FLASHNODE_BIDI_CHAP_EN 262 
#define  ISCSI_FLASHNODE_CHAP_AUTH_EN 261 
#define  ISCSI_FLASHNODE_CHAP_OUT_IDX 260 
#define  ISCSI_FLASHNODE_DATASEQ_INORDER 259 
#define  ISCSI_FLASHNODE_DATA_DGST_EN 258 
#define  ISCSI_FLASHNODE_DEF_TASKMGMT_TMO 257 
#define  ISCSI_FLASHNODE_DEF_TIME2RETAIN 256 
#define  ISCSI_FLASHNODE_DEF_TIME2WAIT 255 
#define  ISCSI_FLASHNODE_DISCOVERY_AUTH_OPTIONAL 254 
#define  ISCSI_FLASHNODE_DISCOVERY_LOGOUT_EN 253 
#define  ISCSI_FLASHNODE_DISCOVERY_PARENT_IDX 252 
#define  ISCSI_FLASHNODE_DISCOVERY_PARENT_TYPE 251 
#define  ISCSI_FLASHNODE_DISCOVERY_SESS 250 
#define  ISCSI_FLASHNODE_ENTRY_EN 249 
#define  ISCSI_FLASHNODE_ERL 248 
#define  ISCSI_FLASHNODE_EXP_STATSN 247 
#define  ISCSI_FLASHNODE_FIRST_BURST 246 
#define  ISCSI_FLASHNODE_HDR_DGST_EN 245 
#define  ISCSI_FLASHNODE_IMM_DATA_EN 244 
#define  ISCSI_FLASHNODE_INITIAL_R2T_EN 243 
#define  ISCSI_FLASHNODE_IPADDR 242 
#define  ISCSI_FLASHNODE_IPV4_TOS 241 
#define  ISCSI_FLASHNODE_IPV6_FLOW_LABEL 240 
#define  ISCSI_FLASHNODE_IPV6_TC 239 
#define  ISCSI_FLASHNODE_IP_FRAG_DISABLE 238 
#define  ISCSI_FLASHNODE_ISID 237 
#define  ISCSI_FLASHNODE_IS_BOOT_TGT 236 
#define  ISCSI_FLASHNODE_IS_FW_ASSIGNED_IPV6 235 
#define  ISCSI_FLASHNODE_KEEPALIVE_TMO 234 
#define  ISCSI_FLASHNODE_LINK_LOCAL_IPV6 233 
#define  ISCSI_FLASHNODE_LOCAL_PORT 232 
#define  ISCSI_FLASHNODE_MAX_BURST 231 
#define  ISCSI_FLASHNODE_MAX_R2T 230 
#define  ISCSI_FLASHNODE_MAX_RECV_DLENGTH 229 
#define  ISCSI_FLASHNODE_MAX_SEGMENT_SIZE 228 
#define  ISCSI_FLASHNODE_MAX_XMIT_DLENGTH 227 
#define  ISCSI_FLASHNODE_NAME 226 
#define  ISCSI_FLASHNODE_PARAM 225 
#define  ISCSI_FLASHNODE_PASSWORD 224 
#define  ISCSI_FLASHNODE_PDU_INORDER 223 
#define  ISCSI_FLASHNODE_PORT 222 
#define  ISCSI_FLASHNODE_PORTAL_TYPE 221 
#define  ISCSI_FLASHNODE_REDIRECT_IPADDR 220 
#define  ISCSI_FLASHNODE_SNACK_REQ_EN 219 
#define  ISCSI_FLASHNODE_STATSN 218 
#define  ISCSI_FLASHNODE_TCP_NAGLE_DISABLE 217 
#define  ISCSI_FLASHNODE_TCP_RECV_WSF 216 
#define  ISCSI_FLASHNODE_TCP_TIMER_SCALE 215 
#define  ISCSI_FLASHNODE_TCP_TIMESTAMP_EN 214 
#define  ISCSI_FLASHNODE_TCP_TIMESTAMP_STAT 213 
#define  ISCSI_FLASHNODE_TCP_WSF_DISABLE 212 
#define  ISCSI_FLASHNODE_TCP_XMIT_WSF 211 
#define  ISCSI_FLASHNODE_TPGT 210 
#define  ISCSI_FLASHNODE_TSID 209 
#define  ISCSI_FLASHNODE_USERNAME 208 
#define  ISCSI_HOST_PARAM 207 
#define  ISCSI_HOST_PARAM_HWADDRESS 206 
#define  ISCSI_HOST_PARAM_INITIATOR_NAME 205 
#define  ISCSI_HOST_PARAM_IPADDRESS 204 
#define  ISCSI_HOST_PARAM_PORT_SPEED 203 
#define  ISCSI_HOST_PARAM_PORT_STATE 202 
#define  ISCSI_NET_PARAM 201 
#define  ISCSI_NET_PARAM_IFACE_ENABLE 200 
#define  ISCSI_NET_PARAM_IPV4_ADDR 199 
#define  ISCSI_NET_PARAM_IPV4_BOOTPROTO 198 
#define  ISCSI_NET_PARAM_IPV4_GW 197 
#define  ISCSI_NET_PARAM_IPV4_SUBNET 196 
#define  ISCSI_NET_PARAM_IPV6_ADDR 195 
#define  ISCSI_NET_PARAM_IPV6_ADDR_AUTOCFG 194 
#define  ISCSI_NET_PARAM_IPV6_LINKLOCAL 193 
#define  ISCSI_NET_PARAM_IPV6_LINKLOCAL_AUTOCFG 192 
#define  ISCSI_NET_PARAM_IPV6_ROUTER 191 
#define  ISCSI_NET_PARAM_MTU 190 
#define  ISCSI_NET_PARAM_PORT 189 
#define  ISCSI_NET_PARAM_VLAN_ENABLED 188 
#define  ISCSI_NET_PARAM_VLAN_ID 187 
#define  ISCSI_NET_PARAM_VLAN_PRIORITY 186 
#define  ISCSI_PARAM 185 
#define  ISCSI_PARAM_AUTO_SND_TGT_DISABLE 184 
#define  ISCSI_PARAM_BIDI_CHAP_EN 183 
#define  ISCSI_PARAM_CHAP_AUTH_EN 182 
#define  ISCSI_PARAM_CHAP_IN_IDX 181 
#define  ISCSI_PARAM_CHAP_OUT_IDX 180 
#define  ISCSI_PARAM_CONN_ADDRESS 179 
#define  ISCSI_PARAM_CONN_PORT 178 
#define  ISCSI_PARAM_DATADGST_EN 177 
#define  ISCSI_PARAM_DATASEQ_INORDER_EN 176 
#define  ISCSI_PARAM_DEF_TASKMGMT_TMO 175 
#define  ISCSI_PARAM_DEF_TIME2RETAIN 174 
#define  ISCSI_PARAM_DEF_TIME2WAIT 173 
#define  ISCSI_PARAM_DISCOVERY_AUTH_OPTIONAL 172 
#define  ISCSI_PARAM_DISCOVERY_LOGOUT_EN 171 
#define  ISCSI_PARAM_DISCOVERY_PARENT_IDX 170 
#define  ISCSI_PARAM_DISCOVERY_PARENT_TYPE 169 
#define  ISCSI_PARAM_DISCOVERY_SESS 168 
#define  ISCSI_PARAM_ERL 167 
#define  ISCSI_PARAM_EXP_STATSN 166 
#define  ISCSI_PARAM_FIRST_BURST 165 
#define  ISCSI_PARAM_HDRDGST_EN 164 
#define  ISCSI_PARAM_IFACE_NAME 163 
#define  ISCSI_PARAM_IMM_DATA_EN 162 
#define  ISCSI_PARAM_INITIAL_R2T_EN 161 
#define  ISCSI_PARAM_IPV4_TOS 160 
#define  ISCSI_PARAM_IPV6_FLOW_LABEL 159 
#define  ISCSI_PARAM_IPV6_TC 158 
#define  ISCSI_PARAM_IP_FRAGMENT_DISABLE 157 
#define  ISCSI_PARAM_ISID 156 
#define  ISCSI_PARAM_IS_FW_ASSIGNED_IPV6 155 
#define  ISCSI_PARAM_KEEPALIVE_TMO 154 
#define  ISCSI_PARAM_LOCAL_PORT 153 
#define  ISCSI_PARAM_MAX_BURST 152 
#define  ISCSI_PARAM_MAX_R2T 151 
#define  ISCSI_PARAM_MAX_RECV_DLENGTH 150 
#define  ISCSI_PARAM_MAX_SEGMENT_SIZE 149 
#define  ISCSI_PARAM_MAX_XMIT_DLENGTH 148 
#define  ISCSI_PARAM_PASSWORD 147 
#define  ISCSI_PARAM_PASSWORD_IN 146 
#define  ISCSI_PARAM_PDU_INORDER_EN 145 
#define  ISCSI_PARAM_PERSISTENT_ADDRESS 144 
#define  ISCSI_PARAM_PERSISTENT_PORT 143 
#define  ISCSI_PARAM_PORTAL_TYPE 142 
#define  ISCSI_PARAM_STATSN 141 
#define  ISCSI_PARAM_TARGET_ALIAS 140 
#define  ISCSI_PARAM_TARGET_NAME 139 
#define  ISCSI_PARAM_TCP_NAGLE_DISABLE 138 
#define  ISCSI_PARAM_TCP_RECV_WSF 137 
#define  ISCSI_PARAM_TCP_TIMER_SCALE 136 
#define  ISCSI_PARAM_TCP_TIMESTAMP_EN 135 
#define  ISCSI_PARAM_TCP_TIMESTAMP_STAT 134 
#define  ISCSI_PARAM_TCP_WSF_DISABLE 133 
#define  ISCSI_PARAM_TCP_XMIT_WSF 132 
#define  ISCSI_PARAM_TPGT 131 
#define  ISCSI_PARAM_TSID 130 
#define  ISCSI_PARAM_USERNAME 129 
#define  ISCSI_PARAM_USERNAME_IN 128 
 int /*<<< orphan*/  S_IRUGO ; 

__attribute__((used)) static mode_t qla4_attr_is_visible(int param_type, int param)
{
	switch (param_type) {
	case ISCSI_HOST_PARAM:
		switch (param) {
		case ISCSI_HOST_PARAM_HWADDRESS:
		case ISCSI_HOST_PARAM_IPADDRESS:
		case ISCSI_HOST_PARAM_INITIATOR_NAME:
		case ISCSI_HOST_PARAM_PORT_STATE:
		case ISCSI_HOST_PARAM_PORT_SPEED:
			return S_IRUGO;
		default:
			return 0;
		}
	case ISCSI_PARAM:
		switch (param) {
		case ISCSI_PARAM_PERSISTENT_ADDRESS:
		case ISCSI_PARAM_PERSISTENT_PORT:
		case ISCSI_PARAM_CONN_ADDRESS:
		case ISCSI_PARAM_CONN_PORT:
		case ISCSI_PARAM_TARGET_NAME:
		case ISCSI_PARAM_TPGT:
		case ISCSI_PARAM_TARGET_ALIAS:
		case ISCSI_PARAM_MAX_BURST:
		case ISCSI_PARAM_MAX_R2T:
		case ISCSI_PARAM_FIRST_BURST:
		case ISCSI_PARAM_MAX_RECV_DLENGTH:
		case ISCSI_PARAM_MAX_XMIT_DLENGTH:
		case ISCSI_PARAM_IFACE_NAME:
		case ISCSI_PARAM_CHAP_OUT_IDX:
		case ISCSI_PARAM_CHAP_IN_IDX:
		case ISCSI_PARAM_USERNAME:
		case ISCSI_PARAM_PASSWORD:
		case ISCSI_PARAM_USERNAME_IN:
		case ISCSI_PARAM_PASSWORD_IN:
		case ISCSI_PARAM_AUTO_SND_TGT_DISABLE:
		case ISCSI_PARAM_DISCOVERY_SESS:
		case ISCSI_PARAM_PORTAL_TYPE:
		case ISCSI_PARAM_CHAP_AUTH_EN:
		case ISCSI_PARAM_DISCOVERY_LOGOUT_EN:
		case ISCSI_PARAM_BIDI_CHAP_EN:
		case ISCSI_PARAM_DISCOVERY_AUTH_OPTIONAL:
		case ISCSI_PARAM_DEF_TIME2WAIT:
		case ISCSI_PARAM_DEF_TIME2RETAIN:
		case ISCSI_PARAM_HDRDGST_EN:
		case ISCSI_PARAM_DATADGST_EN:
		case ISCSI_PARAM_INITIAL_R2T_EN:
		case ISCSI_PARAM_IMM_DATA_EN:
		case ISCSI_PARAM_PDU_INORDER_EN:
		case ISCSI_PARAM_DATASEQ_INORDER_EN:
		case ISCSI_PARAM_MAX_SEGMENT_SIZE:
		case ISCSI_PARAM_TCP_TIMESTAMP_STAT:
		case ISCSI_PARAM_TCP_WSF_DISABLE:
		case ISCSI_PARAM_TCP_NAGLE_DISABLE:
		case ISCSI_PARAM_TCP_TIMER_SCALE:
		case ISCSI_PARAM_TCP_TIMESTAMP_EN:
		case ISCSI_PARAM_TCP_XMIT_WSF:
		case ISCSI_PARAM_TCP_RECV_WSF:
		case ISCSI_PARAM_IP_FRAGMENT_DISABLE:
		case ISCSI_PARAM_IPV4_TOS:
		case ISCSI_PARAM_IPV6_TC:
		case ISCSI_PARAM_IPV6_FLOW_LABEL:
		case ISCSI_PARAM_IS_FW_ASSIGNED_IPV6:
		case ISCSI_PARAM_KEEPALIVE_TMO:
		case ISCSI_PARAM_LOCAL_PORT:
		case ISCSI_PARAM_ISID:
		case ISCSI_PARAM_TSID:
		case ISCSI_PARAM_DEF_TASKMGMT_TMO:
		case ISCSI_PARAM_ERL:
		case ISCSI_PARAM_STATSN:
		case ISCSI_PARAM_EXP_STATSN:
		case ISCSI_PARAM_DISCOVERY_PARENT_IDX:
		case ISCSI_PARAM_DISCOVERY_PARENT_TYPE:
			return S_IRUGO;
		default:
			return 0;
		}
	case ISCSI_NET_PARAM:
		switch (param) {
		case ISCSI_NET_PARAM_IPV4_ADDR:
		case ISCSI_NET_PARAM_IPV4_SUBNET:
		case ISCSI_NET_PARAM_IPV4_GW:
		case ISCSI_NET_PARAM_IPV4_BOOTPROTO:
		case ISCSI_NET_PARAM_IFACE_ENABLE:
		case ISCSI_NET_PARAM_IPV6_LINKLOCAL:
		case ISCSI_NET_PARAM_IPV6_ADDR:
		case ISCSI_NET_PARAM_IPV6_ROUTER:
		case ISCSI_NET_PARAM_IPV6_ADDR_AUTOCFG:
		case ISCSI_NET_PARAM_IPV6_LINKLOCAL_AUTOCFG:
		case ISCSI_NET_PARAM_VLAN_ID:
		case ISCSI_NET_PARAM_VLAN_PRIORITY:
		case ISCSI_NET_PARAM_VLAN_ENABLED:
		case ISCSI_NET_PARAM_MTU:
		case ISCSI_NET_PARAM_PORT:
			return S_IRUGO;
		default:
			return 0;
		}
	case ISCSI_FLASHNODE_PARAM:
		switch (param) {
		case ISCSI_FLASHNODE_IS_FW_ASSIGNED_IPV6:
		case ISCSI_FLASHNODE_PORTAL_TYPE:
		case ISCSI_FLASHNODE_AUTO_SND_TGT_DISABLE:
		case ISCSI_FLASHNODE_DISCOVERY_SESS:
		case ISCSI_FLASHNODE_ENTRY_EN:
		case ISCSI_FLASHNODE_HDR_DGST_EN:
		case ISCSI_FLASHNODE_DATA_DGST_EN:
		case ISCSI_FLASHNODE_IMM_DATA_EN:
		case ISCSI_FLASHNODE_INITIAL_R2T_EN:
		case ISCSI_FLASHNODE_DATASEQ_INORDER:
		case ISCSI_FLASHNODE_PDU_INORDER:
		case ISCSI_FLASHNODE_CHAP_AUTH_EN:
		case ISCSI_FLASHNODE_SNACK_REQ_EN:
		case ISCSI_FLASHNODE_DISCOVERY_LOGOUT_EN:
		case ISCSI_FLASHNODE_BIDI_CHAP_EN:
		case ISCSI_FLASHNODE_DISCOVERY_AUTH_OPTIONAL:
		case ISCSI_FLASHNODE_ERL:
		case ISCSI_FLASHNODE_TCP_TIMESTAMP_STAT:
		case ISCSI_FLASHNODE_TCP_NAGLE_DISABLE:
		case ISCSI_FLASHNODE_TCP_WSF_DISABLE:
		case ISCSI_FLASHNODE_TCP_TIMER_SCALE:
		case ISCSI_FLASHNODE_TCP_TIMESTAMP_EN:
		case ISCSI_FLASHNODE_IP_FRAG_DISABLE:
		case ISCSI_FLASHNODE_MAX_RECV_DLENGTH:
		case ISCSI_FLASHNODE_MAX_XMIT_DLENGTH:
		case ISCSI_FLASHNODE_FIRST_BURST:
		case ISCSI_FLASHNODE_DEF_TIME2WAIT:
		case ISCSI_FLASHNODE_DEF_TIME2RETAIN:
		case ISCSI_FLASHNODE_MAX_R2T:
		case ISCSI_FLASHNODE_KEEPALIVE_TMO:
		case ISCSI_FLASHNODE_ISID:
		case ISCSI_FLASHNODE_TSID:
		case ISCSI_FLASHNODE_PORT:
		case ISCSI_FLASHNODE_MAX_BURST:
		case ISCSI_FLASHNODE_DEF_TASKMGMT_TMO:
		case ISCSI_FLASHNODE_IPADDR:
		case ISCSI_FLASHNODE_ALIAS:
		case ISCSI_FLASHNODE_REDIRECT_IPADDR:
		case ISCSI_FLASHNODE_MAX_SEGMENT_SIZE:
		case ISCSI_FLASHNODE_LOCAL_PORT:
		case ISCSI_FLASHNODE_IPV4_TOS:
		case ISCSI_FLASHNODE_IPV6_TC:
		case ISCSI_FLASHNODE_IPV6_FLOW_LABEL:
		case ISCSI_FLASHNODE_NAME:
		case ISCSI_FLASHNODE_TPGT:
		case ISCSI_FLASHNODE_LINK_LOCAL_IPV6:
		case ISCSI_FLASHNODE_DISCOVERY_PARENT_IDX:
		case ISCSI_FLASHNODE_DISCOVERY_PARENT_TYPE:
		case ISCSI_FLASHNODE_TCP_XMIT_WSF:
		case ISCSI_FLASHNODE_TCP_RECV_WSF:
		case ISCSI_FLASHNODE_CHAP_OUT_IDX:
		case ISCSI_FLASHNODE_USERNAME:
		case ISCSI_FLASHNODE_PASSWORD:
		case ISCSI_FLASHNODE_STATSN:
		case ISCSI_FLASHNODE_EXP_STATSN:
		case ISCSI_FLASHNODE_IS_BOOT_TGT:
			return S_IRUGO;
		default:
			return 0;
		}
	}

	return 0;
}