#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  int /*<<< orphan*/  u_long ;

/* Variables and functions */
#define  OSIOCGIFADDR 321 
#define  OSIOCGIFBRDADDR 320 
#define  OSIOCGIFCONF32 319 
#define  OSIOCGIFCONF64 318 
#define  OSIOCGIFDSTADDR 317 
#define  OSIOCGIFINFO_IN6 316 
#define  OSIOCGIFNETMASK 315 
#define  SIOCADDMULTI 314 
#define  SIOCAIFADDR 313 
#define  SIOCAIFADDR_IN6_32 312 
#define  SIOCAIFADDR_IN6_64 311 
#define  SIOCAIFAGENTID 310 
#define  SIOCAIFPREFIX_IN6 309 
#define  SIOCARPIPLL 308 
#define  SIOCAUTOADDR 307 
#define  SIOCAUTOCONF_START 306 
#define  SIOCAUTOCONF_STOP 305 
#define  SIOCAUTONETMASK 304 
#define  SIOCCIFPREFIX_IN6 303 
#define  SIOCDELMULTI 302 
#define  SIOCDIFADDR 301 
#define  SIOCDIFADDR_IN6 300 
#define  SIOCDIFAGENTID 299 
#define  SIOCDIFPHYADDR 298 
#define  SIOCDIFPREFIX_IN6 297 
#define  SIOCGASSOCIDS32 296 
#define  SIOCGASSOCIDS64 295 
#define  SIOCGCONNIDS32 294 
#define  SIOCGCONNIDS64 293 
#define  SIOCGCONNINFO32 292 
#define  SIOCGCONNINFO64 291 
#define  SIOCGCONNORDER 290 
#define  SIOCGDEFIFACE_IN6_32 289 
#define  SIOCGDEFIFACE_IN6_64 288 
#define  SIOCGDRLST_IN6_32 287 
#define  SIOCGDRLST_IN6_64 286 
#define  SIOCGDRVSPEC32 285 
#define  SIOCGDRVSPEC64 284 
#define  SIOCGECNMODE 283 
#define  SIOCGIF2KCL 282 
#define  SIOCGIFADDR 281 
#define  SIOCGIFADDR_IN6 280 
#define  SIOCGIFAFLAG_IN6 279 
#define  SIOCGIFAGENTDATA32 278 
#define  SIOCGIFAGENTDATA64 277 
#define  SIOCGIFAGENTIDS32 276 
#define  SIOCGIFAGENTIDS64 275 
#define  SIOCGIFAGENTLIST32 274 
#define  SIOCGIFAGENTLIST64 273 
#define  SIOCGIFALIFETIME_IN6 272 
#define  SIOCGIFALTMTU 271 
#define  SIOCGIFASYNCMAP 270 
#define  SIOCGIFBOND 269 
#define  SIOCGIFBRDADDR 268 
#define  SIOCGIFCAP 267 
#define  SIOCGIFCGAPREP_IN6 266 
#define  SIOCGIFCLAT46ADDR 265 
#define  SIOCGIFCONF32 264 
#define  SIOCGIFCONF64 263 
#define  SIOCGIFDELEGATE 262 
#define  SIOCGIFDESC 261 
#define  SIOCGIFDEVMTU 260 
#define  SIOCGIFDSTADDR 259 
#define  SIOCGIFDSTADDR_IN6 258 
#define  SIOCGIFEFLAGS 257 
#define  SIOCGIFEXPENSIVE 256 
#define  SIOCGIFFLAGS 255 
#define  SIOCGIFFUNCTIONALTYPE 254 
#define  SIOCGIFGENERIC 253 
#define  SIOCGIFGETRTREFCNT 252 
#define  SIOCGIFINFO_IN6 251 
#define  SIOCGIFINTERFACESTATE 250 
#define  SIOCGIFKPI 249 
#define  SIOCGIFLINKPARAMS 248 
#define  SIOCGIFLINKQUALITYMETRIC 247 
#define  SIOCGIFLLADDR 246 
#define  SIOCGIFLOG 245 
#define  SIOCGIFLOWINTERNET 244 
#define  SIOCGIFLOWPOWER 243 
#define  SIOCGIFMAC 242 
#define  SIOCGIFMEDIA32 241 
#define  SIOCGIFMEDIA64 240 
#define  SIOCGIFMETRIC 239 
#define  SIOCGIFMTU 238 
#define  SIOCGIFNAT64PREFIX 237 
#define  SIOCGIFNETMASK 236 
#define  SIOCGIFNETMASK_IN6 235 
#define  SIOCGIFNETSIGNATURE 234 
#define  SIOCGIFOPPORTUNISTIC 233 
#define  SIOCGIFPDSTADDR 232 
#define  SIOCGIFPDSTADDR_IN6 231 
#define  SIOCGIFPHYS 230 
#define  SIOCGIFPREFIX_IN6 229 
#define  SIOCGIFPROBECONNECTIVITY 228 
#define  SIOCGIFPROTOLIST32 227 
#define  SIOCGIFPROTOLIST64 226 
#define  SIOCGIFPSRCADDR 225 
#define  SIOCGIFPSRCADDR_IN6 224 
#define  SIOCGIFQUEUESTATS 223 
#define  SIOCGIFSTATUS 222 
#define  SIOCGIFSTAT_ICMP6 221 
#define  SIOCGIFSTAT_IN6 220 
#define  SIOCGIFTHROTTLE 219 
#define  SIOCGIFTIMESTAMPENABLED 218 
#define  SIOCGIFTYPE 217 
#define  SIOCGIFVLAN 216 
#define  SIOCGIFWAKEFLAGS 215 
#define  SIOCGNBRINFO_IN6_32 214 
#define  SIOCGNBRINFO_IN6_64 213 
#define  SIOCGPPPCSTATS 212 
#define  SIOCGPPPSTATS 211 
#define  SIOCGPRLST_IN6_32 210 
#define  SIOCGPRLST_IN6_64 209 
#define  SIOCGQOSMARKINGENABLED 208 
#define  SIOCGQOSMARKINGMODE 207 
#define  SIOCGSCOPE6 206 
#define  SIOCGSCOPE6DEF 205 
#define  SIOCGSTARTDELAY 204 
#define  SIOCIFCREATE 203 
#define  SIOCIFCREATE2 202 
#define  SIOCIFDESTROY 201 
#define  SIOCIFGCLONERS32 200 
#define  SIOCIFGCLONERS64 199 
#define  SIOCLL_CGASTART_32 198 
#define  SIOCLL_CGASTART_64 197 
#define  SIOCLL_START_32 196 
#define  SIOCLL_START_64 195 
#define  SIOCLL_STOP 194 
#define  SIOCPROTOATTACH 193 
#define  SIOCPROTOATTACH_IN6_32 192 
#define  SIOCPROTOATTACH_IN6_64 191 
#define  SIOCPROTODETACH 190 
#define  SIOCPROTODETACH_IN6 189 
#define  SIOCRSLVMULTI 188 
#define  SIOCSCONNORDER 187 
#define  SIOCSDEFIFACE_IN6_32 186 
#define  SIOCSDEFIFACE_IN6_64 185 
#define  SIOCSDRVSPEC32 184 
#define  SIOCSDRVSPEC64 183 
#define  SIOCSECNMODE 182 
#define  SIOCSETROUTERMODE 181 
#define  SIOCSETROUTERMODE_IN6 180 
#define  SIOCSGIFPREFIX_IN6 179 
#define  SIOCSIF2KCL 178 
#define  SIOCSIFADDR 177 
#define  SIOCSIFADDR_IN6 176 
#define  SIOCSIFALIFETIME_IN6 175 
#define  SIOCSIFALTMTU 174 
#define  SIOCSIFASYNCMAP 173 
#define  SIOCSIFBOND 172 
#define  SIOCSIFBRDADDR 171 
#define  SIOCSIFCAP 170 
#define  SIOCSIFCGAPREP_IN6 169 
#define  SIOCSIFDESC 168 
#define  SIOCSIFDISABLEOUTPUT 167 
#define  SIOCSIFDSTADDR 166 
#define  SIOCSIFDSTADDR_IN6 165 
#define  SIOCSIFEXPENSIVE 164 
#define  SIOCSIFFLAGS 163 
#define  SIOCSIFGENERIC 162 
#define  SIOCSIFINFO_FLAGS 161 
#define  SIOCSIFINTERFACESTATE 160 
#define  SIOCSIFKPI 159 
#define  SIOCSIFLINKPARAMS 158 
#define  SIOCSIFLLADDR 157 
#define  SIOCSIFLOG 156 
#define  SIOCSIFLOWINTERNET 155 
#define  SIOCSIFLOWPOWER 154 
#define  SIOCSIFMAC 153 
#define  SIOCSIFMEDIA 152 
#define  SIOCSIFMETRIC 151 
#define  SIOCSIFMTU 150 
#define  SIOCSIFNAT64PREFIX 149 
#define  SIOCSIFNETMASK 148 
#define  SIOCSIFNETMASK_IN6 147 
#define  SIOCSIFNETSIGNATURE 146 
#define  SIOCSIFOPPORTUNISTIC 145 
#define  SIOCSIFORDER 144 
#define  SIOCSIFPHYADDR 143 
#define  SIOCSIFPHYADDR_IN6_32 142 
#define  SIOCSIFPHYADDR_IN6_64 141 
#define  SIOCSIFPHYS 140 
#define  SIOCSIFPREFIX_IN6 139 
#define  SIOCSIFPROBECONNECTIVITY 138 
#define  SIOCSIFTHROTTLE 137 
#define  SIOCSIFTIMESTAMPDISABLE 136 
#define  SIOCSIFTIMESTAMPENABLE 135 
#define  SIOCSIFVLAN 134 
#define  SIOCSNDFLUSH_IN6 133 
#define  SIOCSPFXFLUSH_IN6 132 
#define  SIOCSQOSMARKINGENABLED 131 
#define  SIOCSQOSMARKINGMODE 130 
#define  SIOCSRTRFLUSH_IN6 129 
#define  SIOCSSCOPE6 128 

__attribute__((used)) static __attribute__((unused)) void
ifioctl_cassert(void)
{
	/*
	 * This is equivalent to _CASSERT() and the compiler wouldn't
	 * generate any instructions, thus for compile time only.
	 */
	switch ((u_long)0) {
	case 0:

	/* bsd/net/if_ppp.h */
	case SIOCGPPPSTATS:
	case SIOCGPPPCSTATS:

#if INET6
	/* bsd/netinet6/in6_var.h */
	case SIOCSIFADDR_IN6:
	case SIOCGIFADDR_IN6:
	case SIOCSIFDSTADDR_IN6:
	case SIOCSIFNETMASK_IN6:
	case SIOCGIFDSTADDR_IN6:
	case SIOCGIFNETMASK_IN6:
	case SIOCDIFADDR_IN6:
	case SIOCAIFADDR_IN6_32:
	case SIOCAIFADDR_IN6_64:
	case SIOCSIFPHYADDR_IN6_32:
	case SIOCSIFPHYADDR_IN6_64:
	case SIOCGIFPSRCADDR_IN6:
	case SIOCGIFPDSTADDR_IN6:
	case SIOCGIFAFLAG_IN6:
	case SIOCGDRLST_IN6_32:
	case SIOCGDRLST_IN6_64:
	case SIOCGPRLST_IN6_32:
	case SIOCGPRLST_IN6_64:
	case OSIOCGIFINFO_IN6:
	case SIOCGIFINFO_IN6:
	case SIOCSNDFLUSH_IN6:
	case SIOCGNBRINFO_IN6_32:
	case SIOCGNBRINFO_IN6_64:
	case SIOCSPFXFLUSH_IN6:
	case SIOCSRTRFLUSH_IN6:
	case SIOCGIFALIFETIME_IN6:
	case SIOCSIFALIFETIME_IN6:
	case SIOCGIFSTAT_IN6:
	case SIOCGIFSTAT_ICMP6:
	case SIOCSDEFIFACE_IN6_32:
	case SIOCSDEFIFACE_IN6_64:
	case SIOCGDEFIFACE_IN6_32:
	case SIOCGDEFIFACE_IN6_64:
	case SIOCSIFINFO_FLAGS:
	case SIOCSSCOPE6:
	case SIOCGSCOPE6:
	case SIOCGSCOPE6DEF:
	case SIOCSIFPREFIX_IN6:
	case SIOCGIFPREFIX_IN6:
	case SIOCDIFPREFIX_IN6:
	case SIOCAIFPREFIX_IN6:
	case SIOCCIFPREFIX_IN6:
	case SIOCSGIFPREFIX_IN6:
	case SIOCPROTOATTACH_IN6_32:
	case SIOCPROTOATTACH_IN6_64:
	case SIOCPROTODETACH_IN6:
	case SIOCLL_START_32:
	case SIOCLL_START_64:
	case SIOCLL_STOP:
	case SIOCAUTOCONF_START:
	case SIOCAUTOCONF_STOP:
	case SIOCSETROUTERMODE_IN6:
	case SIOCLL_CGASTART_32:
	case SIOCLL_CGASTART_64:
	case SIOCGIFCGAPREP_IN6:
	case SIOCSIFCGAPREP_IN6:
#endif /* INET6 */

	/* bsd/sys/sockio.h */
	case SIOCSIFADDR:
	case OSIOCGIFADDR:
	case SIOCSIFDSTADDR:
	case OSIOCGIFDSTADDR:
	case SIOCSIFFLAGS:
	case SIOCGIFFLAGS:
	case OSIOCGIFBRDADDR:
	case SIOCSIFBRDADDR:
	case OSIOCGIFCONF32:
	case OSIOCGIFCONF64:
	case OSIOCGIFNETMASK:
	case SIOCSIFNETMASK:
	case SIOCGIFMETRIC:
	case SIOCSIFMETRIC:
	case SIOCDIFADDR:
	case SIOCAIFADDR:

	case SIOCGIFADDR:
	case SIOCGIFDSTADDR:
	case SIOCGIFBRDADDR:
	case SIOCGIFCONF32:
	case SIOCGIFCONF64:
	case SIOCGIFNETMASK:
	case SIOCAUTOADDR:
	case SIOCAUTONETMASK:
	case SIOCARPIPLL:

	case SIOCADDMULTI:
	case SIOCDELMULTI:
	case SIOCGIFMTU:
	case SIOCSIFMTU:
	case SIOCGIFPHYS:
	case SIOCSIFPHYS:
	case SIOCSIFMEDIA:
	case SIOCGIFMEDIA32:
	case SIOCGIFMEDIA64:
	case SIOCSIFGENERIC:
	case SIOCGIFGENERIC:
	case SIOCRSLVMULTI:

	case SIOCSIFLLADDR:
	case SIOCGIFSTATUS:
	case SIOCSIFPHYADDR:
	case SIOCGIFPSRCADDR:
	case SIOCGIFPDSTADDR:
	case SIOCDIFPHYADDR:

	case SIOCGIFDEVMTU:
	case SIOCSIFALTMTU:
	case SIOCGIFALTMTU:
	case SIOCSIFBOND:
	case SIOCGIFBOND:

	case SIOCPROTOATTACH:
	case SIOCPROTODETACH:

	case SIOCSIFCAP:
	case SIOCGIFCAP:

	case SIOCIFCREATE:
	case SIOCIFDESTROY:
	case SIOCIFCREATE2:

	case SIOCSDRVSPEC32:
	case SIOCGDRVSPEC32:
	case SIOCSDRVSPEC64:
	case SIOCGDRVSPEC64:

	case SIOCSIFVLAN:
	case SIOCGIFVLAN:

	case SIOCIFGCLONERS32:
	case SIOCIFGCLONERS64:

	case SIOCGIFASYNCMAP:
	case SIOCSIFASYNCMAP:
#if CONFIG_MACF_NET
	case SIOCGIFMAC:
	case SIOCSIFMAC:
#endif /* CONFIG_MACF_NET */
	case SIOCSIFKPI:
	case SIOCGIFKPI:

	case SIOCGIFWAKEFLAGS:

	case SIOCGIFGETRTREFCNT:
	case SIOCGIFLINKQUALITYMETRIC:
	case SIOCSIFOPPORTUNISTIC:
	case SIOCGIFOPPORTUNISTIC:
	case SIOCSETROUTERMODE:
	case SIOCGIFEFLAGS:
	case SIOCSIFDESC:
	case SIOCGIFDESC:
	case SIOCSIFLINKPARAMS:
	case SIOCGIFLINKPARAMS:
	case SIOCGIFQUEUESTATS:
	case SIOCSIFTHROTTLE:
	case SIOCGIFTHROTTLE:

	case SIOCGASSOCIDS32:
	case SIOCGASSOCIDS64:
	case SIOCGCONNIDS32:
	case SIOCGCONNIDS64:
	case SIOCGCONNINFO32:
	case SIOCGCONNINFO64:
	case SIOCSCONNORDER:
	case SIOCGCONNORDER:

	case SIOCSIFLOG:
	case SIOCGIFLOG:
	case SIOCGIFDELEGATE:
	case SIOCGIFLLADDR:
	case SIOCGIFTYPE:
	case SIOCGIFEXPENSIVE:
	case SIOCSIFEXPENSIVE:
	case SIOCGIF2KCL:
	case SIOCSIF2KCL:
	case SIOCGSTARTDELAY:

	case SIOCAIFAGENTID:
	case SIOCDIFAGENTID:
	case SIOCGIFAGENTIDS32:
	case SIOCGIFAGENTIDS64:
	case SIOCGIFAGENTDATA32:
	case SIOCGIFAGENTDATA64:

	case SIOCSIFINTERFACESTATE:
	case SIOCGIFINTERFACESTATE:
	case SIOCSIFPROBECONNECTIVITY:
	case SIOCGIFPROBECONNECTIVITY:

	case SIOCGIFFUNCTIONALTYPE:
	case SIOCSIFNETSIGNATURE:
	case SIOCGIFNETSIGNATURE:

	case SIOCGECNMODE:
	case SIOCSECNMODE:

	case SIOCSIFORDER:

	case SIOCSQOSMARKINGMODE:
	case SIOCSQOSMARKINGENABLED:
	case SIOCGQOSMARKINGMODE:
	case SIOCGQOSMARKINGENABLED:

	case SIOCSIFTIMESTAMPENABLE:
	case SIOCSIFTIMESTAMPDISABLE:
	case SIOCGIFTIMESTAMPENABLED:

	case SIOCSIFDISABLEOUTPUT:

	case SIOCGIFAGENTLIST32:
	case SIOCGIFAGENTLIST64:

	case SIOCSIFLOWINTERNET:
	case SIOCGIFLOWINTERNET:

#if INET6
	case SIOCGIFNAT64PREFIX:
	case SIOCSIFNAT64PREFIX:

	case SIOCGIFCLAT46ADDR:
#endif /* INET6 */

	case SIOCGIFPROTOLIST32:
	case SIOCGIFPROTOLIST64:

	case SIOCGIFLOWPOWER:
	case SIOCSIFLOWPOWER:
		;
	}
}