#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  int u32 ;

/* Variables and functions */
#define  CAYMAN_SQ_EX_ALLOC_TABLE_SLOTS 234 
#define  CAYMAN_VGT_OFFCHIP_LDS_BASE 233 
#define  CP_COHER_CNTL 232 
#define  CP_COHER_SIZE 231 
#define  CP_STRMOUT_CNTL 230 
#define  DB_DEBUG 229 
#define  DB_DEBUG2 228 
#define  DB_DEBUG3 227 
#define  DB_DEBUG4 226 
#define  DB_WATERMARKS 225 
 int /*<<< orphan*/  DRM_ERROR (char*,int) ; 
#define  GRBM_GFX_INDEX 224 
#define  PA_CL_ENHANCE 223 
#define  PA_SC_ENHANCE 222 
#define  PA_SC_LINE_STIPPLE_STATE 221 
#define  PA_SU_LINE_STIPPLE_VALUE 220 
#define  SPI_CONFIG_CNTL 219 
#define  SPI_CONFIG_CNTL_1 218 
#define  SQ_CONFIG 217 
#define  SQ_CONST_MEM_BASE 216 
#define  SQ_DYN_GPR_CNTL_PS_FLUSH_REQ 215 
#define  SQ_DYN_GPR_SIMD_LOCK_EN 214 
#define  SQ_ESGS_RING_BASE 213 
#define  SQ_ESGS_RING_ITEMSIZE 212 
#define  SQ_ESGS_RING_SIZE 211 
#define  SQ_ESTMP_RING_BASE 210 
#define  SQ_ESTMP_RING_ITEMSIZE 209 
#define  SQ_ESTMP_RING_SIZE 208 
#define  SQ_GLOBAL_GPR_RESOURCE_MGMT_1 207 
#define  SQ_GLOBAL_GPR_RESOURCE_MGMT_2 206 
#define  SQ_GPR_RESOURCE_MGMT_1 205 
#define  SQ_GSTMP_RING_BASE 204 
#define  SQ_GSTMP_RING_ITEMSIZE 203 
#define  SQ_GSTMP_RING_SIZE 202 
#define  SQ_GSVS_RING_BASE 201 
#define  SQ_GSVS_RING_ITEMSIZE 200 
#define  SQ_GSVS_RING_OFFSET_1 199 
#define  SQ_GSVS_RING_OFFSET_2 198 
#define  SQ_GSVS_RING_OFFSET_3 197 
#define  SQ_GSVS_RING_SIZE 196 
#define  SQ_GS_VERT_ITEMSIZE 195 
#define  SQ_GS_VERT_ITEMSIZE_1 194 
#define  SQ_GS_VERT_ITEMSIZE_2 193 
#define  SQ_GS_VERT_ITEMSIZE_3 192 
#define  SQ_HSTMP_RING_BASE 191 
#define  SQ_HSTMP_RING_ITEMSIZE 190 
#define  SQ_HSTMP_RING_SIZE 189 
#define  SQ_LSTMP_RING_BASE 188 
#define  SQ_LSTMP_RING_ITEMSIZE 187 
#define  SQ_LSTMP_RING_SIZE 186 
#define  SQ_PSTMP_RING_BASE 185 
#define  SQ_PSTMP_RING_ITEMSIZE 184 
#define  SQ_PSTMP_RING_SIZE 183 
#define  SQ_STATIC_THREAD_MGMT_1 182 
#define  SQ_STATIC_THREAD_MGMT_2 181 
#define  SQ_STATIC_THREAD_MGMT_3 180 
#define  SQ_VSTMP_RING_BASE 179 
#define  SQ_VSTMP_RING_ITEMSIZE 178 
#define  SQ_VSTMP_RING_SIZE 177 
#define  TA_CNTL_AUX 176 
#define  TD_CS_BORDER_COLOR_ALPHA 175 
#define  TD_CS_BORDER_COLOR_BLUE 174 
#define  TD_CS_BORDER_COLOR_GREEN 173 
#define  TD_CS_BORDER_COLOR_INDEX 172 
#define  TD_CS_BORDER_COLOR_RED 171 
#define  TD_GS_BORDER_COLOR_ALPHA 170 
#define  TD_GS_BORDER_COLOR_BLUE 169 
#define  TD_GS_BORDER_COLOR_GREEN 168 
#define  TD_GS_BORDER_COLOR_INDEX 167 
#define  TD_GS_BORDER_COLOR_RED 166 
#define  TD_HS_BORDER_COLOR_ALPHA 165 
#define  TD_HS_BORDER_COLOR_BLUE 164 
#define  TD_HS_BORDER_COLOR_GREEN 163 
#define  TD_HS_BORDER_COLOR_INDEX 162 
#define  TD_HS_BORDER_COLOR_RED 161 
#define  TD_LS_BORDER_COLOR_ALPHA 160 
#define  TD_LS_BORDER_COLOR_BLUE 159 
#define  TD_LS_BORDER_COLOR_GREEN 158 
#define  TD_LS_BORDER_COLOR_INDEX 157 
#define  TD_LS_BORDER_COLOR_RED 156 
#define  TD_PS_BORDER_COLOR_ALPHA 155 
#define  TD_PS_BORDER_COLOR_BLUE 154 
#define  TD_PS_BORDER_COLOR_GREEN 153 
#define  TD_PS_BORDER_COLOR_INDEX 152 
#define  TD_PS_BORDER_COLOR_RED 151 
#define  TD_VS_BORDER_COLOR_ALPHA 150 
#define  TD_VS_BORDER_COLOR_BLUE 149 
#define  TD_VS_BORDER_COLOR_GREEN 148 
#define  TD_VS_BORDER_COLOR_INDEX 147 
#define  TD_VS_BORDER_COLOR_RED 146 
#define  VGT_CACHE_INVALIDATION 145 
#define  VGT_COMPUTE_DIM_X 144 
#define  VGT_COMPUTE_DIM_Y 143 
#define  VGT_COMPUTE_DIM_Z 142 
#define  VGT_COMPUTE_INDEX 141 
#define  VGT_COMPUTE_START_X 140 
#define  VGT_COMPUTE_START_Y 139 
#define  VGT_COMPUTE_START_Z 138 
#define  VGT_COMPUTE_THREAD_GROUP_SIZE 137 
#define  VGT_GS_VERTEX_REUSE 136 
#define  VGT_HS_OFFCHIP_PARAM 135 
#define  VGT_INDEX_TYPE 134 
#define  VGT_NUM_INDICES 133 
#define  VGT_NUM_INSTANCES 132 
#define  VGT_PRIMITIVE_TYPE 131 
#define  VGT_TF_RING_SIZE 130 
#define  VGT_VTX_VECT_EJECT_REG 129 
#define  WAIT_UNTIL 128 

__attribute__((used)) static bool evergreen_vm_reg_valid(u32 reg)
{
	/* context regs are fine */
	if (reg >= 0x28000)
		return true;

	/* check config regs */
	switch (reg) {
	case WAIT_UNTIL:
	case GRBM_GFX_INDEX:
	case CP_STRMOUT_CNTL:
	case CP_COHER_CNTL:
	case CP_COHER_SIZE:
	case VGT_VTX_VECT_EJECT_REG:
	case VGT_CACHE_INVALIDATION:
	case VGT_GS_VERTEX_REUSE:
	case VGT_PRIMITIVE_TYPE:
	case VGT_INDEX_TYPE:
	case VGT_NUM_INDICES:
	case VGT_NUM_INSTANCES:
	case VGT_COMPUTE_DIM_X:
	case VGT_COMPUTE_DIM_Y:
	case VGT_COMPUTE_DIM_Z:
	case VGT_COMPUTE_START_X:
	case VGT_COMPUTE_START_Y:
	case VGT_COMPUTE_START_Z:
	case VGT_COMPUTE_INDEX:
	case VGT_COMPUTE_THREAD_GROUP_SIZE:
	case VGT_HS_OFFCHIP_PARAM:
	case PA_CL_ENHANCE:
	case PA_SU_LINE_STIPPLE_VALUE:
	case PA_SC_LINE_STIPPLE_STATE:
	case PA_SC_ENHANCE:
	case SQ_DYN_GPR_CNTL_PS_FLUSH_REQ:
	case SQ_DYN_GPR_SIMD_LOCK_EN:
	case SQ_CONFIG:
	case SQ_GPR_RESOURCE_MGMT_1:
	case SQ_GLOBAL_GPR_RESOURCE_MGMT_1:
	case SQ_GLOBAL_GPR_RESOURCE_MGMT_2:
	case SQ_CONST_MEM_BASE:
	case SQ_STATIC_THREAD_MGMT_1:
	case SQ_STATIC_THREAD_MGMT_2:
	case SQ_STATIC_THREAD_MGMT_3:
	case SPI_CONFIG_CNTL:
	case SPI_CONFIG_CNTL_1:
	case TA_CNTL_AUX:
	case DB_DEBUG:
	case DB_DEBUG2:
	case DB_DEBUG3:
	case DB_DEBUG4:
	case DB_WATERMARKS:
	case TD_PS_BORDER_COLOR_INDEX:
	case TD_PS_BORDER_COLOR_RED:
	case TD_PS_BORDER_COLOR_GREEN:
	case TD_PS_BORDER_COLOR_BLUE:
	case TD_PS_BORDER_COLOR_ALPHA:
	case TD_VS_BORDER_COLOR_INDEX:
	case TD_VS_BORDER_COLOR_RED:
	case TD_VS_BORDER_COLOR_GREEN:
	case TD_VS_BORDER_COLOR_BLUE:
	case TD_VS_BORDER_COLOR_ALPHA:
	case TD_GS_BORDER_COLOR_INDEX:
	case TD_GS_BORDER_COLOR_RED:
	case TD_GS_BORDER_COLOR_GREEN:
	case TD_GS_BORDER_COLOR_BLUE:
	case TD_GS_BORDER_COLOR_ALPHA:
	case TD_HS_BORDER_COLOR_INDEX:
	case TD_HS_BORDER_COLOR_RED:
	case TD_HS_BORDER_COLOR_GREEN:
	case TD_HS_BORDER_COLOR_BLUE:
	case TD_HS_BORDER_COLOR_ALPHA:
	case TD_LS_BORDER_COLOR_INDEX:
	case TD_LS_BORDER_COLOR_RED:
	case TD_LS_BORDER_COLOR_GREEN:
	case TD_LS_BORDER_COLOR_BLUE:
	case TD_LS_BORDER_COLOR_ALPHA:
	case TD_CS_BORDER_COLOR_INDEX:
	case TD_CS_BORDER_COLOR_RED:
	case TD_CS_BORDER_COLOR_GREEN:
	case TD_CS_BORDER_COLOR_BLUE:
	case TD_CS_BORDER_COLOR_ALPHA:
	case SQ_ESGS_RING_SIZE:
	case SQ_GSVS_RING_SIZE:
	case SQ_ESTMP_RING_SIZE:
	case SQ_GSTMP_RING_SIZE:
	case SQ_HSTMP_RING_SIZE:
	case SQ_LSTMP_RING_SIZE:
	case SQ_PSTMP_RING_SIZE:
	case SQ_VSTMP_RING_SIZE:
	case SQ_ESGS_RING_ITEMSIZE:
	case SQ_ESTMP_RING_ITEMSIZE:
	case SQ_GSTMP_RING_ITEMSIZE:
	case SQ_GSVS_RING_ITEMSIZE:
	case SQ_GS_VERT_ITEMSIZE:
	case SQ_GS_VERT_ITEMSIZE_1:
	case SQ_GS_VERT_ITEMSIZE_2:
	case SQ_GS_VERT_ITEMSIZE_3:
	case SQ_GSVS_RING_OFFSET_1:
	case SQ_GSVS_RING_OFFSET_2:
	case SQ_GSVS_RING_OFFSET_3:
	case SQ_HSTMP_RING_ITEMSIZE:
	case SQ_LSTMP_RING_ITEMSIZE:
	case SQ_PSTMP_RING_ITEMSIZE:
	case SQ_VSTMP_RING_ITEMSIZE:
	case VGT_TF_RING_SIZE:
	case SQ_ESGS_RING_BASE:
	case SQ_GSVS_RING_BASE:
	case SQ_ESTMP_RING_BASE:
	case SQ_GSTMP_RING_BASE:
	case SQ_HSTMP_RING_BASE:
	case SQ_LSTMP_RING_BASE:
	case SQ_PSTMP_RING_BASE:
	case SQ_VSTMP_RING_BASE:
	case CAYMAN_VGT_OFFCHIP_LDS_BASE:
	case CAYMAN_SQ_EX_ALLOC_TABLE_SLOTS:
		return true;
	default:
		DRM_ERROR("Invalid register 0x%x in CS\n", reg);
		return false;
	}
}