#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  enum msg_hash_enums { ____Placeholder_msg_hash_enums } msg_hash_enums ;

/* Variables and functions */
#define  ACTION_OK_DL_ACCOUNTS_CHEEVOS_LIST 195 
#define  ACTION_OK_DL_ACCOUNTS_LIST 194 
#define  ACTION_OK_DL_ACCOUNTS_TWITCH_LIST 193 
#define  ACTION_OK_DL_ACCOUNTS_YOUTUBE_LIST 192 
#define  ACTION_OK_DL_AI_SERVICE_SETTINGS_LIST 191 
#define  ACTION_OK_DL_AUDIO_MIXER_SETTINGS_LIST 190 
#define  ACTION_OK_DL_AUDIO_SETTINGS_LIST 189 
#define  ACTION_OK_DL_BROWSE_URL_LIST 188 
#define  ACTION_OK_DL_CDROM_INFO_DETAIL_LIST 187 
#define  ACTION_OK_DL_CHEAT_DETAILS_SETTINGS_LIST 186 
#define  ACTION_OK_DL_CHEAT_SEARCH_SETTINGS_LIST 185 
#define  ACTION_OK_DL_CONFIGURATION_SETTINGS_LIST 184 
#define  ACTION_OK_DL_CORE_SETTINGS_LIST 183 
#define  ACTION_OK_DL_CRT_SWITCHRES_SETTINGS_LIST 182 
#define  ACTION_OK_DL_DIRECTORY_SETTINGS_LIST 181 
#define  ACTION_OK_DL_DRIVER_SETTINGS_LIST 180 
#define  ACTION_OK_DL_DROPDOWN_BOX_LIST 179 
#define  ACTION_OK_DL_DROPDOWN_BOX_LIST_PLAYLIST_DEFAULT_CORE 178 
#define  ACTION_OK_DL_DROPDOWN_BOX_LIST_PLAYLIST_LABEL_DISPLAY_MODE 177 
#define  ACTION_OK_DL_DROPDOWN_BOX_LIST_PLAYLIST_LEFT_THUMBNAIL_MODE 176 
#define  ACTION_OK_DL_DROPDOWN_BOX_LIST_PLAYLIST_RIGHT_THUMBNAIL_MODE 175 
#define  ACTION_OK_DL_DROPDOWN_BOX_LIST_RESOLUTION 174 
#define  ACTION_OK_DL_DROPDOWN_BOX_LIST_SPECIAL 173 
#define  ACTION_OK_DL_DUMP_DISC_LIST 172 
#define  ACTION_OK_DL_FAVORITES_LIST 171 
#define  ACTION_OK_DL_FRAME_THROTTLE_SETTINGS_LIST 170 
#define  ACTION_OK_DL_FRAME_TIME_COUNTER_SETTINGS_LIST 169 
#define  ACTION_OK_DL_IMAGES_LIST 168 
#define  ACTION_OK_DL_INPUT_HOTKEY_BINDS_LIST 167 
#define  ACTION_OK_DL_INPUT_SETTINGS_LIST 166 
#define  ACTION_OK_DL_LAKKA_SERVICES_LIST 165 
#define  ACTION_OK_DL_LATENCY_SETTINGS_LIST 164 
#define  ACTION_OK_DL_LOAD_DISC_LIST 163 
#define  ACTION_OK_DL_LOGGING_SETTINGS_LIST 162 
#define  ACTION_OK_DL_MENU_FILE_BROWSER_SETTINGS_LIST 161 
#define  ACTION_OK_DL_MENU_SETTINGS_LIST 160 
#define  ACTION_OK_DL_MENU_SOUNDS_LIST 159 
#define  ACTION_OK_DL_MENU_VIEWS_SETTINGS_LIST 158 
#define  ACTION_OK_DL_MIDI_SETTINGS_LIST 157 
#define  ACTION_OK_DL_MIXER_STREAM_SETTINGS_LIST 156 
#define  ACTION_OK_DL_MUSIC_LIST 155 
#define  ACTION_OK_DL_NETPLAY 154 
#define  ACTION_OK_DL_NETPLAY_LAN_SCAN_SETTINGS_LIST 153 
#define  ACTION_OK_DL_NETWORK_SETTINGS_LIST 152 
#define  ACTION_OK_DL_ONSCREEN_DISPLAY_SETTINGS_LIST 151 
#define  ACTION_OK_DL_ONSCREEN_NOTIFICATIONS_SETTINGS_LIST 150 
#define  ACTION_OK_DL_ONSCREEN_OVERLAY_SETTINGS_LIST 149 
#define  ACTION_OK_DL_ONSCREEN_VIDEO_LAYOUT_SETTINGS_LIST 148 
#define  ACTION_OK_DL_PLAYLIST_COLLECTION 147 
#define  ACTION_OK_DL_PLAYLIST_MANAGER_LIST 146 
#define  ACTION_OK_DL_PLAYLIST_MANAGER_SETTINGS 145 
#define  ACTION_OK_DL_PLAYLIST_SETTINGS_LIST 144 
#define  ACTION_OK_DL_POWER_MANAGEMENT_SETTINGS_LIST 143 
#define  ACTION_OK_DL_PRIVACY_SETTINGS_LIST 142 
#define  ACTION_OK_DL_QUICK_MENU_OVERRIDE_OPTIONS_LIST 141 
#define  ACTION_OK_DL_QUICK_MENU_VIEWS_SETTINGS_LIST 140 
#define  ACTION_OK_DL_RECORDING_SETTINGS_LIST 139 
#define  ACTION_OK_DL_RETRO_ACHIEVEMENTS_SETTINGS_LIST 138 
#define  ACTION_OK_DL_REWIND_SETTINGS_LIST 137 
#define  ACTION_OK_DL_SAVING_SETTINGS_LIST 136 
#define  ACTION_OK_DL_SETTINGS_VIEWS_SETTINGS_LIST 135 
#define  ACTION_OK_DL_SHADER_PRESET_REMOVE 134 
#define  ACTION_OK_DL_SHADER_PRESET_SAVE 133 
#define  ACTION_OK_DL_UPDATER_SETTINGS_LIST 132 
#define  ACTION_OK_DL_USER_INTERFACE_SETTINGS_LIST 131 
#define  ACTION_OK_DL_USER_SETTINGS_LIST 130 
#define  ACTION_OK_DL_VIDEO_SETTINGS_LIST 129 
#define  ACTION_OK_DL_WIFI_SETTINGS_LIST 128 
 int MENU_ENUM_LABEL_DEFERRED_ACCOUNTS_CHEEVOS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_ACCOUNTS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_ACCOUNTS_TWITCH_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_ACCOUNTS_YOUTUBE_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_AI_SERVICE_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_AUDIO_MIXER_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_AUDIO_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_BROWSE_URL_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_CDROM_INFO_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_CHEAT_DETAILS_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_CHEAT_SEARCH_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_CONFIGURATION_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_CORE_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_CRT_SWITCHRES_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_DIRECTORY_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_DRIVER_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_PLAYLIST_DEFAULT_CORE ; 
 int MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_PLAYLIST_LABEL_DISPLAY_MODE ; 
 int MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_PLAYLIST_LEFT_THUMBNAIL_MODE ; 
 int MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_PLAYLIST_RIGHT_THUMBNAIL_MODE ; 
 int MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_RESOLUTION ; 
 int MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_SPECIAL ; 
 int MENU_ENUM_LABEL_DEFERRED_DUMP_DISC_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_FAVORITES_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_FRAME_THROTTLE_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_FRAME_TIME_COUNTER_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_IMAGES_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_INPUT_HOTKEY_BINDS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_INPUT_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_LAKKA_SERVICES_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_LATENCY_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_LOAD_DISC_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_LOGGING_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_MENU_FILE_BROWSER_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_MENU_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_MENU_SOUNDS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_MENU_VIEWS_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_MIDI_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_MIXER_STREAM_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_MUSIC_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_NETPLAY ; 
 int MENU_ENUM_LABEL_DEFERRED_NETPLAY_LAN_SCAN_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_NETWORK_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_ONSCREEN_DISPLAY_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_ONSCREEN_NOTIFICATIONS_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_ONSCREEN_OVERLAY_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_ONSCREEN_VIDEO_LAYOUT_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_PLAYLIST_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_PLAYLIST_MANAGER_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_PLAYLIST_MANAGER_SETTINGS ; 
 int MENU_ENUM_LABEL_DEFERRED_PLAYLIST_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_POWER_MANAGEMENT_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_PRIVACY_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_QUICK_MENU_OVERRIDE_OPTIONS ; 
 int MENU_ENUM_LABEL_DEFERRED_QUICK_MENU_VIEWS_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_RECORDING_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_RETRO_ACHIEVEMENTS_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_REWIND_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_SAVING_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_SETTINGS_VIEWS_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_UPDATER_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_USER_INTERFACE_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_USER_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_VIDEO_SETTINGS_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_VIDEO_SHADER_PRESET_REMOVE_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_VIDEO_SHADER_PRESET_SAVE_LIST ; 
 int MENU_ENUM_LABEL_DEFERRED_WIFI_SETTINGS_LIST ; 
 int MSG_UNKNOWN ; 

__attribute__((used)) static enum msg_hash_enums action_ok_dl_to_enum(unsigned lbl)
{
   switch (lbl)
   {
      case ACTION_OK_DL_DROPDOWN_BOX_LIST:
         return MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST;
      case ACTION_OK_DL_DROPDOWN_BOX_LIST_SPECIAL:
         return MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_SPECIAL;
      case ACTION_OK_DL_DROPDOWN_BOX_LIST_RESOLUTION:
         return MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_RESOLUTION;
      case ACTION_OK_DL_DROPDOWN_BOX_LIST_PLAYLIST_DEFAULT_CORE:
         return MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_PLAYLIST_DEFAULT_CORE;
      case ACTION_OK_DL_DROPDOWN_BOX_LIST_PLAYLIST_LABEL_DISPLAY_MODE:
         return MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_PLAYLIST_LABEL_DISPLAY_MODE;
      case ACTION_OK_DL_DROPDOWN_BOX_LIST_PLAYLIST_RIGHT_THUMBNAIL_MODE:
         return MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_PLAYLIST_RIGHT_THUMBNAIL_MODE;
      case ACTION_OK_DL_DROPDOWN_BOX_LIST_PLAYLIST_LEFT_THUMBNAIL_MODE:
         return MENU_ENUM_LABEL_DEFERRED_DROPDOWN_BOX_LIST_PLAYLIST_LEFT_THUMBNAIL_MODE;
      case ACTION_OK_DL_MIXER_STREAM_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_MIXER_STREAM_SETTINGS_LIST;
      case ACTION_OK_DL_ACCOUNTS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_ACCOUNTS_LIST;
      case ACTION_OK_DL_INPUT_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_INPUT_SETTINGS_LIST;
      case ACTION_OK_DL_LATENCY_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_LATENCY_SETTINGS_LIST;
      case ACTION_OK_DL_DRIVER_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_DRIVER_SETTINGS_LIST;
      case ACTION_OK_DL_CORE_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_CORE_SETTINGS_LIST;
      case ACTION_OK_DL_VIDEO_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_VIDEO_SETTINGS_LIST;
      case ACTION_OK_DL_CRT_SWITCHRES_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_CRT_SWITCHRES_SETTINGS_LIST;
      case ACTION_OK_DL_CONFIGURATION_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_CONFIGURATION_SETTINGS_LIST;
      case ACTION_OK_DL_SAVING_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_SAVING_SETTINGS_LIST;
      case ACTION_OK_DL_LOGGING_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_LOGGING_SETTINGS_LIST;
      case ACTION_OK_DL_FRAME_THROTTLE_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_FRAME_THROTTLE_SETTINGS_LIST;
      case ACTION_OK_DL_FRAME_TIME_COUNTER_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_FRAME_TIME_COUNTER_SETTINGS_LIST;
      case ACTION_OK_DL_REWIND_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_REWIND_SETTINGS_LIST;
      case ACTION_OK_DL_CHEAT_DETAILS_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_CHEAT_DETAILS_SETTINGS_LIST;
      case ACTION_OK_DL_CHEAT_SEARCH_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_CHEAT_SEARCH_SETTINGS_LIST;
      case ACTION_OK_DL_ONSCREEN_DISPLAY_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_ONSCREEN_DISPLAY_SETTINGS_LIST;
      case ACTION_OK_DL_ONSCREEN_NOTIFICATIONS_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_ONSCREEN_NOTIFICATIONS_SETTINGS_LIST;
      case ACTION_OK_DL_ONSCREEN_OVERLAY_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_ONSCREEN_OVERLAY_SETTINGS_LIST;
#ifdef HAVE_VIDEO_LAYOUT
      case ACTION_OK_DL_ONSCREEN_VIDEO_LAYOUT_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_ONSCREEN_VIDEO_LAYOUT_SETTINGS_LIST;
#endif
      case ACTION_OK_DL_MENU_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_MENU_SETTINGS_LIST;
      case ACTION_OK_DL_MENU_VIEWS_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_MENU_VIEWS_SETTINGS_LIST;
      case ACTION_OK_DL_SETTINGS_VIEWS_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_SETTINGS_VIEWS_SETTINGS_LIST;
      case ACTION_OK_DL_QUICK_MENU_VIEWS_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_QUICK_MENU_VIEWS_SETTINGS_LIST;
      case ACTION_OK_DL_QUICK_MENU_OVERRIDE_OPTIONS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_QUICK_MENU_OVERRIDE_OPTIONS;
      case ACTION_OK_DL_USER_INTERFACE_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_USER_INTERFACE_SETTINGS_LIST;
      case ACTION_OK_DL_AI_SERVICE_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_AI_SERVICE_SETTINGS_LIST;
      case ACTION_OK_DL_POWER_MANAGEMENT_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_POWER_MANAGEMENT_SETTINGS_LIST;
      case ACTION_OK_DL_MENU_SOUNDS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_MENU_SOUNDS_LIST;
      case ACTION_OK_DL_MENU_FILE_BROWSER_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_MENU_FILE_BROWSER_SETTINGS_LIST;
      case ACTION_OK_DL_RETRO_ACHIEVEMENTS_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_RETRO_ACHIEVEMENTS_SETTINGS_LIST;
      case ACTION_OK_DL_UPDATER_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_UPDATER_SETTINGS_LIST;
      case ACTION_OK_DL_NETWORK_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_NETWORK_SETTINGS_LIST;
      case ACTION_OK_DL_WIFI_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_WIFI_SETTINGS_LIST;
      case ACTION_OK_DL_NETPLAY:
         return MENU_ENUM_LABEL_DEFERRED_NETPLAY;
      case ACTION_OK_DL_NETPLAY_LAN_SCAN_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_NETPLAY_LAN_SCAN_SETTINGS_LIST;
      case ACTION_OK_DL_LAKKA_SERVICES_LIST:
         return MENU_ENUM_LABEL_DEFERRED_LAKKA_SERVICES_LIST;
      case ACTION_OK_DL_USER_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_USER_SETTINGS_LIST;
      case ACTION_OK_DL_DIRECTORY_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_DIRECTORY_SETTINGS_LIST;
      case ACTION_OK_DL_PRIVACY_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_PRIVACY_SETTINGS_LIST;
      case ACTION_OK_DL_MIDI_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_MIDI_SETTINGS_LIST;
      case ACTION_OK_DL_AUDIO_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_AUDIO_SETTINGS_LIST;
      case ACTION_OK_DL_AUDIO_MIXER_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_AUDIO_MIXER_SETTINGS_LIST;
      case ACTION_OK_DL_INPUT_HOTKEY_BINDS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_INPUT_HOTKEY_BINDS_LIST;
      case ACTION_OK_DL_RECORDING_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_RECORDING_SETTINGS_LIST;
      case ACTION_OK_DL_PLAYLIST_SETTINGS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_PLAYLIST_SETTINGS_LIST;
      case ACTION_OK_DL_PLAYLIST_MANAGER_LIST:
         return MENU_ENUM_LABEL_DEFERRED_PLAYLIST_MANAGER_LIST;
      case ACTION_OK_DL_PLAYLIST_MANAGER_SETTINGS:
         return MENU_ENUM_LABEL_DEFERRED_PLAYLIST_MANAGER_SETTINGS;
      case ACTION_OK_DL_ACCOUNTS_CHEEVOS_LIST:
         return MENU_ENUM_LABEL_DEFERRED_ACCOUNTS_CHEEVOS_LIST;
      case ACTION_OK_DL_ACCOUNTS_TWITCH_LIST:
         return MENU_ENUM_LABEL_DEFERRED_ACCOUNTS_TWITCH_LIST;
      case ACTION_OK_DL_DUMP_DISC_LIST:
         return MENU_ENUM_LABEL_DEFERRED_DUMP_DISC_LIST;
      case ACTION_OK_DL_LOAD_DISC_LIST:
         return MENU_ENUM_LABEL_DEFERRED_LOAD_DISC_LIST;
      case ACTION_OK_DL_ACCOUNTS_YOUTUBE_LIST:
         return MENU_ENUM_LABEL_DEFERRED_ACCOUNTS_YOUTUBE_LIST;
      case ACTION_OK_DL_PLAYLIST_COLLECTION:
         return MENU_ENUM_LABEL_DEFERRED_PLAYLIST_LIST;
      case ACTION_OK_DL_FAVORITES_LIST:
         return MENU_ENUM_LABEL_DEFERRED_FAVORITES_LIST;
      case ACTION_OK_DL_BROWSE_URL_LIST:
         return MENU_ENUM_LABEL_DEFERRED_BROWSE_URL_LIST;
      case ACTION_OK_DL_MUSIC_LIST:
         return MENU_ENUM_LABEL_DEFERRED_MUSIC_LIST;
      case ACTION_OK_DL_IMAGES_LIST:
         return MENU_ENUM_LABEL_DEFERRED_IMAGES_LIST;
      case ACTION_OK_DL_CDROM_INFO_DETAIL_LIST:
         return MENU_ENUM_LABEL_DEFERRED_CDROM_INFO_LIST;
      case ACTION_OK_DL_SHADER_PRESET_SAVE:
         return MENU_ENUM_LABEL_DEFERRED_VIDEO_SHADER_PRESET_SAVE_LIST;
      case ACTION_OK_DL_SHADER_PRESET_REMOVE:
         return MENU_ENUM_LABEL_DEFERRED_VIDEO_SHADER_PRESET_REMOVE_LIST;
      default:
         break;
   }

   return MSG_UNKNOWN;
}