#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  enum tls_fail_reason { ____Placeholder_tls_fail_reason } tls_fail_reason ;

/* Variables and functions */
 int TLS_FAIL_BAD_CERTIFICATE ; 
 int TLS_FAIL_EXPIRED ; 
 int TLS_FAIL_NOT_YET_VALID ; 
 int TLS_FAIL_REVOKED ; 
 int TLS_FAIL_UNSPECIFIED ; 
 int TLS_FAIL_UNTRUSTED ; 
#define  X509_V_ERR_CERT_CHAIN_TOO_LONG 151 
#define  X509_V_ERR_CERT_HAS_EXPIRED 150 
#define  X509_V_ERR_CERT_NOT_YET_VALID 149 
#define  X509_V_ERR_CERT_REJECTED 148 
#define  X509_V_ERR_CERT_REVOKED 147 
#define  X509_V_ERR_CERT_UNTRUSTED 146 
#define  X509_V_ERR_CRL_HAS_EXPIRED 145 
#define  X509_V_ERR_CRL_NOT_YET_VALID 144 
#define  X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT 143 
#define  X509_V_ERR_ERROR_IN_CERT_NOT_AFTER_FIELD 142 
#define  X509_V_ERR_ERROR_IN_CERT_NOT_BEFORE_FIELD 141 
#define  X509_V_ERR_ERROR_IN_CRL_LAST_UPDATE_FIELD 140 
#define  X509_V_ERR_ERROR_IN_CRL_NEXT_UPDATE_FIELD 139 
#define  X509_V_ERR_INVALID_CA 138 
#define  X509_V_ERR_PATH_LENGTH_EXCEEDED 137 
#define  X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN 136 
#define  X509_V_ERR_UNABLE_TO_DECODE_ISSUER_PUBLIC_KEY 135 
#define  X509_V_ERR_UNABLE_TO_DECRYPT_CERT_SIGNATURE 134 
#define  X509_V_ERR_UNABLE_TO_DECRYPT_CRL_SIGNATURE 133 
#define  X509_V_ERR_UNABLE_TO_GET_CRL 132 
#define  X509_V_ERR_UNABLE_TO_GET_CRL_ISSUER 131 
#define  X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT 130 
#define  X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY 129 
#define  X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE 128 

__attribute__((used)) static enum tls_fail_reason openssl_tls_fail_reason(int err)
{
	switch (err) {
	case X509_V_ERR_CERT_REVOKED:
		return TLS_FAIL_REVOKED;
	case X509_V_ERR_CERT_NOT_YET_VALID:
	case X509_V_ERR_CRL_NOT_YET_VALID:
		return TLS_FAIL_NOT_YET_VALID;
	case X509_V_ERR_CERT_HAS_EXPIRED:
	case X509_V_ERR_CRL_HAS_EXPIRED:
		return TLS_FAIL_EXPIRED;
	case X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT:
	case X509_V_ERR_UNABLE_TO_GET_CRL:
	case X509_V_ERR_UNABLE_TO_GET_CRL_ISSUER:
	case X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN:
	case X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY:
	case X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT:
	case X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE:
	case X509_V_ERR_CERT_CHAIN_TOO_LONG:
	case X509_V_ERR_PATH_LENGTH_EXCEEDED:
	case X509_V_ERR_INVALID_CA:
		return TLS_FAIL_UNTRUSTED;
	case X509_V_ERR_UNABLE_TO_DECRYPT_CERT_SIGNATURE:
	case X509_V_ERR_UNABLE_TO_DECRYPT_CRL_SIGNATURE:
	case X509_V_ERR_UNABLE_TO_DECODE_ISSUER_PUBLIC_KEY:
	case X509_V_ERR_ERROR_IN_CERT_NOT_BEFORE_FIELD:
	case X509_V_ERR_ERROR_IN_CERT_NOT_AFTER_FIELD:
	case X509_V_ERR_ERROR_IN_CRL_LAST_UPDATE_FIELD:
	case X509_V_ERR_ERROR_IN_CRL_NEXT_UPDATE_FIELD:
	case X509_V_ERR_CERT_UNTRUSTED:
	case X509_V_ERR_CERT_REJECTED:
		return TLS_FAIL_BAD_CERTIFICATE;
	default:
		return TLS_FAIL_UNSPECIFIED;
	}
}