#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */

/* Variables and functions */
 int /*<<< orphan*/  _initialize_annotate () ; 
 int /*<<< orphan*/  _initialize_auxv () ; 
 int /*<<< orphan*/  _initialize_ax_gdb () ; 
 int /*<<< orphan*/  _initialize_breakpoint () ; 
 int /*<<< orphan*/  _initialize_c_language () ; 
 int /*<<< orphan*/  _initialize_charset () ; 
 int /*<<< orphan*/  _initialize_cli_dump () ; 
 int /*<<< orphan*/  _initialize_cli_interp () ; 
 int /*<<< orphan*/  _initialize_cli_logging () ; 
 int /*<<< orphan*/  _initialize_cli_out () ; 
 int /*<<< orphan*/  _initialize_coffread () ; 
 int /*<<< orphan*/  _initialize_complaints () ; 
 int /*<<< orphan*/  _initialize_copying () ; 
 int /*<<< orphan*/  _initialize_core () ; 
 int /*<<< orphan*/  _initialize_corelow () ; 
 int /*<<< orphan*/  _initialize_cp_abi () ; 
 int /*<<< orphan*/  _initialize_cp_namespace () ; 
 int /*<<< orphan*/  _initialize_cp_support () ; 
 int /*<<< orphan*/  _initialize_cp_valprint () ; 
 int /*<<< orphan*/  _initialize_dbxread () ; 
 int /*<<< orphan*/  _initialize_dcache () ; 
 int /*<<< orphan*/  _initialize_demangler () ; 
 int /*<<< orphan*/  _initialize_dummy_frame () ; 
 int /*<<< orphan*/  _initialize_dwarf2_frame () ; 
 int /*<<< orphan*/  _initialize_elfread () ; 
 int /*<<< orphan*/  _initialize_exec () ; 
 int /*<<< orphan*/  _initialize_f_language () ; 
 int /*<<< orphan*/  _initialize_f_valprint () ; 
 int /*<<< orphan*/  _initialize_fbsd_proc () ; 
 int /*<<< orphan*/  _initialize_frame () ; 
 int /*<<< orphan*/  _initialize_frame_base () ; 
 int /*<<< orphan*/  _initialize_frame_reg () ; 
 int /*<<< orphan*/  _initialize_frame_unwind () ; 
 int /*<<< orphan*/  _initialize_gcore () ; 
 int /*<<< orphan*/  _initialize_gdb_events () ; 
 int /*<<< orphan*/  _initialize_gdb_osabi () ; 
 int /*<<< orphan*/  _initialize_gdbarch () ; 
 int /*<<< orphan*/  _initialize_gdbarch_utils () ; 
 int /*<<< orphan*/  _initialize_gdbtypes () ; 
 int /*<<< orphan*/  _initialize_gnu_v2_abi () ; 
 int /*<<< orphan*/  _initialize_gnu_v3_abi () ; 
 int /*<<< orphan*/  _initialize_hpacc_abi () ; 
 int /*<<< orphan*/  _initialize_i386_nat () ; 
 int /*<<< orphan*/  _initialize_i386_tdep () ; 
 int /*<<< orphan*/  _initialize_i386bsd_nat () ; 
 int /*<<< orphan*/  _initialize_i386bsd_tdep () ; 
 int /*<<< orphan*/  _initialize_i386fbsd_nat () ; 
 int /*<<< orphan*/  _initialize_i386fbsd_tdep () ; 
 int /*<<< orphan*/  _initialize_infcall () ; 
 int /*<<< orphan*/  _initialize_infcmd () ; 
 int /*<<< orphan*/  _initialize_inflow () ; 
 int /*<<< orphan*/  _initialize_infptrace () ; 
 int /*<<< orphan*/  _initialize_infrun () ; 
 int /*<<< orphan*/  _initialize_inftarg () ; 
 int /*<<< orphan*/  _initialize_interpreter () ; 
 int /*<<< orphan*/  _initialize_java_language () ; 
 int /*<<< orphan*/  _initialize_kernel_u_addr () ; 
 int /*<<< orphan*/  _initialize_kod () ; 
 int /*<<< orphan*/  _initialize_language () ; 
 int /*<<< orphan*/  _initialize_m2_language () ; 
 int /*<<< orphan*/  _initialize_macrocmd () ; 
 int /*<<< orphan*/  _initialize_maint_cmds () ; 
 int /*<<< orphan*/  _initialize_mdebugread () ; 
 int /*<<< orphan*/  _initialize_mem () ; 
 int /*<<< orphan*/  _initialize_mi_cmd_env () ; 
 int /*<<< orphan*/  _initialize_mi_cmds () ; 
 int /*<<< orphan*/  _initialize_mi_interp () ; 
 int /*<<< orphan*/  _initialize_mi_main () ; 
 int /*<<< orphan*/  _initialize_mi_out () ; 
 int /*<<< orphan*/  _initialize_mipsread () ; 
 int /*<<< orphan*/  _initialize_nlmread () ; 
 int /*<<< orphan*/  _initialize_objc_language () ; 
 int /*<<< orphan*/  _initialize_parse () ; 
 int /*<<< orphan*/  _initialize_pascal_language () ; 
 int /*<<< orphan*/  _initialize_pascal_valprint () ; 
 int /*<<< orphan*/  _initialize_printcmd () ; 
 int /*<<< orphan*/  _initialize_regcache () ; 
 int /*<<< orphan*/  _initialize_reggroup () ; 
 int /*<<< orphan*/  _initialize_remote () ; 
 int /*<<< orphan*/  _initialize_scheme_language () ; 
 int /*<<< orphan*/  _initialize_ser_hardwire () ; 
 int /*<<< orphan*/  _initialize_ser_pipe () ; 
 int /*<<< orphan*/  _initialize_ser_tcp () ; 
 int /*<<< orphan*/  _initialize_serial () ; 
 int /*<<< orphan*/  _initialize_signals () ; 
 int /*<<< orphan*/  _initialize_solib () ; 
 int /*<<< orphan*/  _initialize_source () ; 
 int /*<<< orphan*/  _initialize_sr_support () ; 
 int /*<<< orphan*/  _initialize_stabsread () ; 
 int /*<<< orphan*/  _initialize_stack () ; 
 int /*<<< orphan*/  _initialize_svr4_solib () ; 
 int /*<<< orphan*/  _initialize_symfile () ; 
 int /*<<< orphan*/  _initialize_symmisc () ; 
 int /*<<< orphan*/  _initialize_symtab () ; 
 int /*<<< orphan*/  _initialize_thread () ; 
 int /*<<< orphan*/  _initialize_thread_db () ; 
 int /*<<< orphan*/  _initialize_tracepoint () ; 
 int /*<<< orphan*/  _initialize_tui_hooks () ; 
 int /*<<< orphan*/  _initialize_tui_interp () ; 
 int /*<<< orphan*/  _initialize_tui_layout () ; 
 int /*<<< orphan*/  _initialize_tui_out () ; 
 int /*<<< orphan*/  _initialize_tui_regs () ; 
 int /*<<< orphan*/  _initialize_tui_stack () ; 
 int /*<<< orphan*/  _initialize_tui_win () ; 
 int /*<<< orphan*/  _initialize_typeprint () ; 
 int /*<<< orphan*/  _initialize_ui_out () ; 
 int /*<<< orphan*/  _initialize_user_regs () ; 
 int /*<<< orphan*/  _initialize_valarith () ; 
 int /*<<< orphan*/  _initialize_valops () ; 
 int /*<<< orphan*/  _initialize_valprint () ; 
 int /*<<< orphan*/  _initialize_values () ; 
 int /*<<< orphan*/  _initialize_varobj () ; 

void
initialize_all_files (void)
{
  _initialize_gdbtypes ();
  _initialize_i386_tdep ();
  _initialize_i386bsd_tdep ();
  _initialize_i386fbsd_tdep ();
  _initialize_corelow ();
  _initialize_solib ();
  _initialize_svr4_solib ();
  _initialize_ser_hardwire ();
  _initialize_ser_pipe ();
  _initialize_ser_tcp ();
#ifndef CROSS_DEBUGGER
  _initialize_kernel_u_addr ();
  _initialize_infptrace ();
  _initialize_inftarg ();
  _initialize_i386_nat ();
  _initialize_i386bsd_nat ();
  _initialize_i386fbsd_nat ();
  _initialize_gcore ();
  _initialize_fbsd_proc ();
  _initialize_thread_db ();
#endif
  _initialize_remote ();
  _initialize_dcache ();
  _initialize_sr_support ();
  _initialize_tracepoint ();
  _initialize_ax_gdb ();
  _initialize_annotate ();
  _initialize_auxv ();
  _initialize_breakpoint ();
  _initialize_regcache ();
  _initialize_charset ();
  _initialize_dummy_frame ();
  _initialize_source ();
  _initialize_values ();
  _initialize_valops ();
  _initialize_valarith ();
  _initialize_valprint ();
  _initialize_printcmd ();
  _initialize_symtab ();
  _initialize_symfile ();
  _initialize_symmisc ();
  _initialize_infcall ();
  _initialize_infcmd ();
  _initialize_infrun ();
  _initialize_stack ();
  _initialize_thread ();
  _initialize_interpreter ();
  _initialize_macrocmd ();
  _initialize_gdbarch ();
  _initialize_gdbarch_utils ();
  _initialize_gdb_osabi ();
  _initialize_copying ();
  _initialize_mem ();
  _initialize_parse ();
  _initialize_language ();
  _initialize_frame_reg ();
  _initialize_signals ();
  _initialize_kod ();
  _initialize_gdb_events ();
  _initialize_exec ();
  _initialize_maint_cmds ();
  _initialize_demangler ();
  _initialize_dbxread ();
  _initialize_coffread ();
  _initialize_elfread ();
  _initialize_mipsread ();
  _initialize_stabsread ();
  _initialize_core ();
  _initialize_dwarf2_frame ();
  _initialize_c_language ();
  _initialize_f_language ();
  _initialize_objc_language ();
  _initialize_ui_out ();
  _initialize_cli_out ();
  _initialize_varobj ();
  _initialize_java_language ();
  _initialize_m2_language ();
  _initialize_pascal_language ();
  _initialize_pascal_valprint ();
  _initialize_scheme_language ();
  _initialize_complaints ();
  _initialize_typeprint ();
  _initialize_cp_valprint ();
  _initialize_f_valprint ();
  _initialize_nlmread ();
  _initialize_serial ();
  _initialize_mdebugread ();
  _initialize_user_regs ();
  _initialize_frame ();
  _initialize_frame_unwind ();
  _initialize_frame_base ();
  _initialize_gnu_v2_abi ();
  _initialize_gnu_v3_abi ();
  _initialize_hpacc_abi ();
  _initialize_cp_abi ();
  _initialize_cp_support ();
  _initialize_cp_namespace ();
  _initialize_reggroup ();
  _initialize_inflow ();
  _initialize_cli_dump ();
  _initialize_cli_logging ();
  _initialize_cli_interp ();
  _initialize_mi_out ();
  _initialize_mi_cmds ();
  _initialize_mi_cmd_env ();
  _initialize_mi_interp ();
  _initialize_mi_main ();
  _initialize_tui_hooks ();
  _initialize_tui_interp ();
  _initialize_tui_layout ();
  _initialize_tui_out ();
  _initialize_tui_regs ();
  _initialize_tui_stack ();
  _initialize_tui_win ();
}