#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */

/* Variables and functions */
 int /*<<< orphan*/  ARCHITECTURE ; 
 int /*<<< orphan*/  AUTOMOUNT_RESULT ; 
 int /*<<< orphan*/  AUTOMOUNT_STATE ; 
 int /*<<< orphan*/  CGROUP_CONTROLLER ; 
 int /*<<< orphan*/  CGROUP_DEVICE_POLICY ; 
 int /*<<< orphan*/  CGROUP_IO_LIMIT_TYPE ; 
 int /*<<< orphan*/  COLLECT_MODE ; 
 int /*<<< orphan*/  CONDITION_RESULT ; 
 int /*<<< orphan*/  CONDITION_TYPE ; 
 int /*<<< orphan*/  DEVICE_ACTION ; 
 int /*<<< orphan*/  DEVICE_STATE ; 
 int /*<<< orphan*/  DNSSEC_MODE ; 
 int /*<<< orphan*/  DNS_OVER_TLS_MODE ; 
 int /*<<< orphan*/  EMERGENCY_ACTION ; 
 int /*<<< orphan*/  EXEC_DIRECTORY_TYPE ; 
 int /*<<< orphan*/  EXEC_INPUT ; 
 int /*<<< orphan*/  EXEC_KEYRING_MODE ; 
 int /*<<< orphan*/  EXEC_OUTPUT ; 
 int /*<<< orphan*/  EXEC_PRESERVE_MODE ; 
 int /*<<< orphan*/  EXEC_UTMP_MODE ; 
 int EXIT_SUCCESS ; 
 int /*<<< orphan*/  IMAGE_TYPE ; 
 int /*<<< orphan*/  IMPORT_VERIFY ; 
 int /*<<< orphan*/  JOB_MODE ; 
 int /*<<< orphan*/  JOB_RESULT ; 
 int /*<<< orphan*/  JOB_STATE ; 
 int /*<<< orphan*/  JOB_TYPE ; 
 int /*<<< orphan*/  KILL_MODE ; 
 int /*<<< orphan*/  KILL_WHO ; 
 int /*<<< orphan*/  LOG_TARGET ; 
 int /*<<< orphan*/  MAC_ADDRESS_POLICY ; 
 int /*<<< orphan*/  MANAGER_STATE ; 
 int /*<<< orphan*/  MANAGER_TIMESTAMP ; 
 int /*<<< orphan*/  MOUNT_EXEC_COMMAND ; 
 int /*<<< orphan*/  MOUNT_RESULT ; 
 int /*<<< orphan*/  MOUNT_STATE ; 
 int /*<<< orphan*/  NAMEPOLICY ; 
 int /*<<< orphan*/  NAMESPACE_TYPE ; 
 int /*<<< orphan*/  NOTIFY_ACCESS ; 
 int /*<<< orphan*/  NOTIFY_STATE ; 
 int /*<<< orphan*/  OBJECT_COMPRESSED ; 
 int /*<<< orphan*/  OUTPUT_MODE ; 
 int /*<<< orphan*/  PARTITION_DESIGNATOR ; 
 int /*<<< orphan*/  PATH_RESULT ; 
 int /*<<< orphan*/  PATH_STATE ; 
 int /*<<< orphan*/  PATH_TYPE ; 
 int /*<<< orphan*/  PROTECT_HOME ; 
 int /*<<< orphan*/  PROTECT_SYSTEM ; 
 int /*<<< orphan*/  RESOLVE_SUPPORT ; 
 int /*<<< orphan*/  RLIMIT ; 
 int /*<<< orphan*/  SCOPE_RESULT ; 
 int /*<<< orphan*/  SCOPE_STATE ; 
 int /*<<< orphan*/  SERVICE_EXEC_COMMAND ; 
 int /*<<< orphan*/  SERVICE_RESTART ; 
 int /*<<< orphan*/  SERVICE_RESULT ; 
 int /*<<< orphan*/  SERVICE_STATE ; 
 int /*<<< orphan*/  SERVICE_TYPE ; 
 int /*<<< orphan*/  SHOW_STATUS ; 
 int /*<<< orphan*/  SLICE_STATE ; 
 int /*<<< orphan*/  SOCKET_ADDRESS_BIND_IPV6_ONLY ; 
 int /*<<< orphan*/  SOCKET_EXEC_COMMAND ; 
 int /*<<< orphan*/  SOCKET_RESULT ; 
 int /*<<< orphan*/  SOCKET_STATE ; 
 int /*<<< orphan*/  SPLIT ; 
 int /*<<< orphan*/  STORAGE ; 
 int /*<<< orphan*/  SWAP_EXEC_COMMAND ; 
 int /*<<< orphan*/  SWAP_RESULT ; 
 int /*<<< orphan*/  SWAP_STATE ; 
 int /*<<< orphan*/  TARGET_STATE ; 
 int /*<<< orphan*/  TIMER_BASE ; 
 int /*<<< orphan*/  TIMER_RESULT ; 
 int /*<<< orphan*/  TIMER_STATE ; 
 int /*<<< orphan*/  UNIT_ACTIVE_STATE ; 
 int /*<<< orphan*/  UNIT_DEPENDENCY ; 
 int /*<<< orphan*/  UNIT_FILE_CHANGE_TYPE ; 
 int /*<<< orphan*/  UNIT_FILE_PRESET ; 
 int /*<<< orphan*/  UNIT_FILE_STATE ; 
 int /*<<< orphan*/  UNIT_LOAD_STATE ; 
 int /*<<< orphan*/  UNIT_TYPE ; 
 int /*<<< orphan*/  VARIABLE_LC ; 
 int /*<<< orphan*/  VIRTUALIZATION ; 
 int /*<<< orphan*/  architecture ; 
 int /*<<< orphan*/  assert_type ; 
 int /*<<< orphan*/  automount_result ; 
 int /*<<< orphan*/  automount_state ; 
 int /*<<< orphan*/  cgroup_controller ; 
 int /*<<< orphan*/  cgroup_device_policy ; 
 int /*<<< orphan*/  cgroup_io_limit_type ; 
 int /*<<< orphan*/  collect_mode ; 
 int /*<<< orphan*/  condition_result ; 
 int /*<<< orphan*/  condition_type ; 
 int /*<<< orphan*/  device_action ; 
 int /*<<< orphan*/  device_state ; 
 int /*<<< orphan*/  dns_over_tls_mode ; 
 int /*<<< orphan*/  dnssec_mode ; 
 int /*<<< orphan*/  emergency_action ; 
 int /*<<< orphan*/  exec_directory_type ; 
 int /*<<< orphan*/  exec_input ; 
 int /*<<< orphan*/  exec_keyring_mode ; 
 int /*<<< orphan*/  exec_output ; 
 int /*<<< orphan*/  exec_preserve_mode ; 
 int /*<<< orphan*/  exec_utmp_mode ; 
 int /*<<< orphan*/  image_type ; 
 int /*<<< orphan*/  import_verify ; 
 int /*<<< orphan*/  job_mode ; 
 int /*<<< orphan*/  job_result ; 
 int /*<<< orphan*/  job_state ; 
 int /*<<< orphan*/  job_type ; 
 int /*<<< orphan*/  kill_mode ; 
 int /*<<< orphan*/  kill_who ; 
 int /*<<< orphan*/  locale_variable ; 
 int /*<<< orphan*/  log_target ; 
 int /*<<< orphan*/  mac_address_policy ; 
 int /*<<< orphan*/  manager_state ; 
 int /*<<< orphan*/  manager_timestamp ; 
 int /*<<< orphan*/  mount_exec_command ; 
 int /*<<< orphan*/  mount_result ; 
 int /*<<< orphan*/  mount_state ; 
 int /*<<< orphan*/  name_policy ; 
 int /*<<< orphan*/  namespace_type ; 
 int /*<<< orphan*/  notify_access ; 
 int /*<<< orphan*/  notify_state ; 
 int /*<<< orphan*/  object_compressed ; 
 int /*<<< orphan*/  output_mode ; 
 int /*<<< orphan*/  partition_designator ; 
 int /*<<< orphan*/  path_result ; 
 int /*<<< orphan*/  path_state ; 
 int /*<<< orphan*/  path_type ; 
 int /*<<< orphan*/  protect_home ; 
 int /*<<< orphan*/  protect_system ; 
 int /*<<< orphan*/  resolve_support ; 
 int /*<<< orphan*/  rlimit ; 
 int /*<<< orphan*/  scope_result ; 
 int /*<<< orphan*/  scope_state ; 
 int /*<<< orphan*/  service_exec_command ; 
 int /*<<< orphan*/  service_restart ; 
 int /*<<< orphan*/  service_result ; 
 int /*<<< orphan*/  service_state ; 
 int /*<<< orphan*/  service_type ; 
 int /*<<< orphan*/  show_status ; 
 int /*<<< orphan*/  slice_state ; 
 int /*<<< orphan*/  socket_address_bind_ipv6_only ; 
 int /*<<< orphan*/  socket_exec_command ; 
 int /*<<< orphan*/  socket_result ; 
 int /*<<< orphan*/  socket_state ; 
 int /*<<< orphan*/  split_mode ; 
 int /*<<< orphan*/  storage ; 
 int /*<<< orphan*/  swap_exec_command ; 
 int /*<<< orphan*/  swap_result ; 
 int /*<<< orphan*/  swap_state ; 
 int /*<<< orphan*/  target_state ; 
 int /*<<< orphan*/  test_table (int /*<<< orphan*/ ,int /*<<< orphan*/ ) ; 
 int /*<<< orphan*/  test_table_sparse (int /*<<< orphan*/ ,int /*<<< orphan*/ ) ; 
 int /*<<< orphan*/  timer_base ; 
 int /*<<< orphan*/  timer_result ; 
 int /*<<< orphan*/  timer_state ; 
 int /*<<< orphan*/  unit_active_state ; 
 int /*<<< orphan*/  unit_dependency ; 
 int /*<<< orphan*/  unit_file_change_type ; 
 int /*<<< orphan*/  unit_file_preset_mode ; 
 int /*<<< orphan*/  unit_file_state ; 
 int /*<<< orphan*/  unit_load_state ; 
 int /*<<< orphan*/  unit_type ; 
 int /*<<< orphan*/  virtualization ; 

int main(int argc, char **argv) {
        test_table(architecture, ARCHITECTURE);
        test_table(assert_type, CONDITION_TYPE);
        test_table(automount_result, AUTOMOUNT_RESULT);
        test_table(automount_state, AUTOMOUNT_STATE);
        test_table(cgroup_controller, CGROUP_CONTROLLER);
        test_table(cgroup_device_policy, CGROUP_DEVICE_POLICY);
        test_table(cgroup_io_limit_type, CGROUP_IO_LIMIT_TYPE);
        test_table(collect_mode, COLLECT_MODE);
        test_table(condition_result, CONDITION_RESULT);
        test_table(condition_type, CONDITION_TYPE);
        test_table(device_action, DEVICE_ACTION);
        test_table(device_state, DEVICE_STATE);
        test_table(dns_over_tls_mode, DNS_OVER_TLS_MODE);
        test_table(dnssec_mode, DNSSEC_MODE);
        test_table(emergency_action, EMERGENCY_ACTION);
        test_table(exec_directory_type, EXEC_DIRECTORY_TYPE);
        test_table(exec_input, EXEC_INPUT);
        test_table(exec_keyring_mode, EXEC_KEYRING_MODE);
        test_table(exec_output, EXEC_OUTPUT);
        test_table(exec_preserve_mode, EXEC_PRESERVE_MODE);
        test_table(exec_utmp_mode, EXEC_UTMP_MODE);
        test_table(image_type, IMAGE_TYPE);
        test_table(import_verify, IMPORT_VERIFY);
        test_table(job_mode, JOB_MODE);
        test_table(job_result, JOB_RESULT);
        test_table(job_state, JOB_STATE);
        test_table(job_type, JOB_TYPE);
        test_table(kill_mode, KILL_MODE);
        test_table(kill_who, KILL_WHO);
        test_table(locale_variable, VARIABLE_LC);
        test_table(log_target, LOG_TARGET);
        test_table(mac_address_policy, MAC_ADDRESS_POLICY);
        test_table(manager_state, MANAGER_STATE);
        test_table(manager_timestamp, MANAGER_TIMESTAMP);
        test_table(mount_exec_command, MOUNT_EXEC_COMMAND);
        test_table(mount_result, MOUNT_RESULT);
        test_table(mount_state, MOUNT_STATE);
        test_table(name_policy, NAMEPOLICY);
        test_table(namespace_type, NAMESPACE_TYPE);
        test_table(notify_access, NOTIFY_ACCESS);
        test_table(notify_state, NOTIFY_STATE);
        test_table(output_mode, OUTPUT_MODE);
        test_table(partition_designator, PARTITION_DESIGNATOR);
        test_table(path_result, PATH_RESULT);
        test_table(path_state, PATH_STATE);
        test_table(path_type, PATH_TYPE);
        test_table(protect_home, PROTECT_HOME);
        test_table(protect_system, PROTECT_SYSTEM);
        test_table(resolve_support, RESOLVE_SUPPORT);
        test_table(rlimit, RLIMIT);
        test_table(scope_result, SCOPE_RESULT);
        test_table(scope_state, SCOPE_STATE);
        test_table(service_exec_command, SERVICE_EXEC_COMMAND);
        test_table(service_restart, SERVICE_RESTART);
        test_table(service_result, SERVICE_RESULT);
        test_table(service_state, SERVICE_STATE);
        test_table(service_type, SERVICE_TYPE);
        test_table(show_status, SHOW_STATUS);
        test_table(slice_state, SLICE_STATE);
        test_table(socket_address_bind_ipv6_only, SOCKET_ADDRESS_BIND_IPV6_ONLY);
        test_table(socket_exec_command, SOCKET_EXEC_COMMAND);
        test_table(socket_result, SOCKET_RESULT);
        test_table(socket_state, SOCKET_STATE);
        test_table(split_mode, SPLIT);
        test_table(storage, STORAGE);
        test_table(swap_exec_command, SWAP_EXEC_COMMAND);
        test_table(swap_result, SWAP_RESULT);
        test_table(swap_state, SWAP_STATE);
        test_table(target_state, TARGET_STATE);
        test_table(timer_base, TIMER_BASE);
        test_table(timer_result, TIMER_RESULT);
        test_table(timer_state, TIMER_STATE);
        test_table(unit_active_state, UNIT_ACTIVE_STATE);
        test_table(unit_dependency, UNIT_DEPENDENCY);
        test_table(unit_file_change_type, UNIT_FILE_CHANGE_TYPE);
        test_table(unit_file_preset_mode, UNIT_FILE_PRESET);
        test_table(unit_file_state, UNIT_FILE_STATE);
        test_table(unit_load_state, UNIT_LOAD_STATE);
        test_table(unit_type, UNIT_TYPE);
        test_table(virtualization, VIRTUALIZATION);

        test_table_sparse(object_compressed, OBJECT_COMPRESSED);

        return EXIT_SUCCESS;
}