#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  int uint32_t ;
struct amdgpu_device {int cg_flags; } ;

/* Variables and functions */
 int AMD_CG_SUPPORT_VCN_MGCG ; 
 int RREG32_SOC15 (int /*<<< orphan*/ ,int /*<<< orphan*/ ,int /*<<< orphan*/ ) ; 
 int UVD_CGC_CTRL__CLK_GATE_DLY_TIMER__SHIFT ; 
 int UVD_CGC_CTRL__CLK_OFF_DELAY__SHIFT ; 
 int UVD_CGC_CTRL__DYN_CLOCK_MODE_MASK ; 
 int UVD_CGC_CTRL__DYN_CLOCK_MODE__SHIFT ; 
 int UVD_CGC_CTRL__IDCT_MODE_MASK ; 
 int UVD_CGC_CTRL__LBSI_MODE_MASK ; 
 int UVD_CGC_CTRL__LMI_MC_MODE_MASK ; 
 int UVD_CGC_CTRL__LMI_UMC_MODE_MASK ; 
 int UVD_CGC_CTRL__LRBBM_MODE_MASK ; 
 int UVD_CGC_CTRL__MPC_MODE_MASK ; 
 int UVD_CGC_CTRL__MPEG2_MODE_MASK ; 
 int UVD_CGC_CTRL__MPRD_MODE_MASK ; 
 int UVD_CGC_CTRL__RBC_MODE_MASK ; 
 int UVD_CGC_CTRL__REGS_MODE_MASK ; 
 int UVD_CGC_CTRL__SCPU_MODE_MASK ; 
 int UVD_CGC_CTRL__SYS_MODE_MASK ; 
 int UVD_CGC_CTRL__UDEC_CM_MODE_MASK ; 
 int UVD_CGC_CTRL__UDEC_DB_MODE_MASK ; 
 int UVD_CGC_CTRL__UDEC_IT_MODE_MASK ; 
 int UVD_CGC_CTRL__UDEC_MODE_MASK ; 
 int UVD_CGC_CTRL__UDEC_MP_MODE_MASK ; 
 int UVD_CGC_CTRL__UDEC_RE_MODE_MASK ; 
 int UVD_CGC_CTRL__VCPU_MODE_MASK ; 
 int UVD_CGC_CTRL__WCB_MODE_MASK ; 
 int UVD_CGC_GATE__IDCT_MASK ; 
 int UVD_CGC_GATE__LBSI_MASK ; 
 int UVD_CGC_GATE__LMI_MC_MASK ; 
 int UVD_CGC_GATE__LMI_UMC_MASK ; 
 int UVD_CGC_GATE__LRBBM_MASK ; 
 int UVD_CGC_GATE__MPC_MASK ; 
 int UVD_CGC_GATE__MPEG2_MASK ; 
 int UVD_CGC_GATE__MPRD_MASK ; 
 int UVD_CGC_GATE__RBC_MASK ; 
 int UVD_CGC_GATE__REGS_MASK ; 
 int UVD_CGC_GATE__SCPU_MASK ; 
 int UVD_CGC_GATE__SYS_MASK ; 
 int UVD_CGC_GATE__UDEC_CM_MASK ; 
 int UVD_CGC_GATE__UDEC_DB_MASK ; 
 int UVD_CGC_GATE__UDEC_IT_MASK ; 
 int UVD_CGC_GATE__UDEC_MASK ; 
 int UVD_CGC_GATE__UDEC_MP_MASK ; 
 int UVD_CGC_GATE__UDEC_RE_MASK ; 
 int UVD_CGC_GATE__VCPU_MASK ; 
 int UVD_CGC_GATE__WCB_MASK ; 
 int UVD_SUVD_CGC_CTRL__ENT_MODE_MASK ; 
 int UVD_SUVD_CGC_CTRL__IME_MODE_MASK ; 
 int UVD_SUVD_CGC_CTRL__SCLR_MODE_MASK ; 
 int UVD_SUVD_CGC_CTRL__SCM_MODE_MASK ; 
 int UVD_SUVD_CGC_CTRL__SDB_MODE_MASK ; 
 int UVD_SUVD_CGC_CTRL__SITE_MODE_MASK ; 
 int UVD_SUVD_CGC_CTRL__SIT_MODE_MASK ; 
 int UVD_SUVD_CGC_CTRL__SMP_MODE_MASK ; 
 int UVD_SUVD_CGC_CTRL__SRE_MODE_MASK ; 
 int UVD_SUVD_CGC_CTRL__UVD_SC_MODE_MASK ; 
 int UVD_SUVD_CGC_GATE__ENT_MASK ; 
 int UVD_SUVD_CGC_GATE__IME_HEVC_MASK ; 
 int UVD_SUVD_CGC_GATE__SCLR_MASK ; 
 int UVD_SUVD_CGC_GATE__SCM_H264_MASK ; 
 int UVD_SUVD_CGC_GATE__SCM_HEVC_MASK ; 
 int UVD_SUVD_CGC_GATE__SCM_MASK ; 
 int UVD_SUVD_CGC_GATE__SCM_VP9_MASK ; 
 int UVD_SUVD_CGC_GATE__SDB_H264_MASK ; 
 int UVD_SUVD_CGC_GATE__SDB_HEVC_MASK ; 
 int UVD_SUVD_CGC_GATE__SDB_MASK ; 
 int UVD_SUVD_CGC_GATE__SDB_VP9_MASK ; 
 int UVD_SUVD_CGC_GATE__SITE_MASK ; 
 int UVD_SUVD_CGC_GATE__SIT_H264_MASK ; 
 int UVD_SUVD_CGC_GATE__SIT_HEVC_DEC_MASK ; 
 int UVD_SUVD_CGC_GATE__SIT_HEVC_ENC_MASK ; 
 int UVD_SUVD_CGC_GATE__SIT_HEVC_MASK ; 
 int UVD_SUVD_CGC_GATE__SIT_MASK ; 
 int UVD_SUVD_CGC_GATE__SIT_VP9_DEC_MASK ; 
 int UVD_SUVD_CGC_GATE__SMP_MASK ; 
 int UVD_SUVD_CGC_GATE__SRE_H264_MASK ; 
 int UVD_SUVD_CGC_GATE__SRE_HEVC_MASK ; 
 int UVD_SUVD_CGC_GATE__SRE_MASK ; 
 int UVD_SUVD_CGC_GATE__SRE_VP9_MASK ; 
 int UVD_SUVD_CGC_GATE__UVD_SC_MASK ; 
 int /*<<< orphan*/  VCN ; 
 int /*<<< orphan*/  WREG32_SOC15 (int /*<<< orphan*/ ,int /*<<< orphan*/ ,int /*<<< orphan*/ ,int) ; 
 int /*<<< orphan*/  mmUVD_CGC_CTRL ; 
 int /*<<< orphan*/  mmUVD_CGC_GATE ; 
 int /*<<< orphan*/  mmUVD_SUVD_CGC_CTRL ; 
 int /*<<< orphan*/  mmUVD_SUVD_CGC_GATE ; 

__attribute__((used)) static void vcn_v2_0_disable_clock_gating(struct amdgpu_device *adev)
{
	uint32_t data;

	/* UVD disable CGC */
	data = RREG32_SOC15(VCN, 0, mmUVD_CGC_CTRL);
	if (adev->cg_flags & AMD_CG_SUPPORT_VCN_MGCG)
		data |= 1 << UVD_CGC_CTRL__DYN_CLOCK_MODE__SHIFT;
	else
		data &= ~UVD_CGC_CTRL__DYN_CLOCK_MODE_MASK;
	data |= 1 << UVD_CGC_CTRL__CLK_GATE_DLY_TIMER__SHIFT;
	data |= 4 << UVD_CGC_CTRL__CLK_OFF_DELAY__SHIFT;
	WREG32_SOC15(VCN, 0, mmUVD_CGC_CTRL, data);

	data = RREG32_SOC15(VCN, 0, mmUVD_CGC_GATE);
	data &= ~(UVD_CGC_GATE__SYS_MASK
		| UVD_CGC_GATE__UDEC_MASK
		| UVD_CGC_GATE__MPEG2_MASK
		| UVD_CGC_GATE__REGS_MASK
		| UVD_CGC_GATE__RBC_MASK
		| UVD_CGC_GATE__LMI_MC_MASK
		| UVD_CGC_GATE__LMI_UMC_MASK
		| UVD_CGC_GATE__IDCT_MASK
		| UVD_CGC_GATE__MPRD_MASK
		| UVD_CGC_GATE__MPC_MASK
		| UVD_CGC_GATE__LBSI_MASK
		| UVD_CGC_GATE__LRBBM_MASK
		| UVD_CGC_GATE__UDEC_RE_MASK
		| UVD_CGC_GATE__UDEC_CM_MASK
		| UVD_CGC_GATE__UDEC_IT_MASK
		| UVD_CGC_GATE__UDEC_DB_MASK
		| UVD_CGC_GATE__UDEC_MP_MASK
		| UVD_CGC_GATE__WCB_MASK
		| UVD_CGC_GATE__VCPU_MASK
		| UVD_CGC_GATE__SCPU_MASK);
	WREG32_SOC15(VCN, 0, mmUVD_CGC_GATE, data);

	data = RREG32_SOC15(VCN, 0, mmUVD_CGC_CTRL);
	data &= ~(UVD_CGC_CTRL__UDEC_RE_MODE_MASK
		| UVD_CGC_CTRL__UDEC_CM_MODE_MASK
		| UVD_CGC_CTRL__UDEC_IT_MODE_MASK
		| UVD_CGC_CTRL__UDEC_DB_MODE_MASK
		| UVD_CGC_CTRL__UDEC_MP_MODE_MASK
		| UVD_CGC_CTRL__SYS_MODE_MASK
		| UVD_CGC_CTRL__UDEC_MODE_MASK
		| UVD_CGC_CTRL__MPEG2_MODE_MASK
		| UVD_CGC_CTRL__REGS_MODE_MASK
		| UVD_CGC_CTRL__RBC_MODE_MASK
		| UVD_CGC_CTRL__LMI_MC_MODE_MASK
		| UVD_CGC_CTRL__LMI_UMC_MODE_MASK
		| UVD_CGC_CTRL__IDCT_MODE_MASK
		| UVD_CGC_CTRL__MPRD_MODE_MASK
		| UVD_CGC_CTRL__MPC_MODE_MASK
		| UVD_CGC_CTRL__LBSI_MODE_MASK
		| UVD_CGC_CTRL__LRBBM_MODE_MASK
		| UVD_CGC_CTRL__WCB_MODE_MASK
		| UVD_CGC_CTRL__VCPU_MODE_MASK
		| UVD_CGC_CTRL__SCPU_MODE_MASK);
	WREG32_SOC15(VCN, 0, mmUVD_CGC_CTRL, data);

	/* turn on */
	data = RREG32_SOC15(VCN, 0, mmUVD_SUVD_CGC_GATE);
	data |= (UVD_SUVD_CGC_GATE__SRE_MASK
		| UVD_SUVD_CGC_GATE__SIT_MASK
		| UVD_SUVD_CGC_GATE__SMP_MASK
		| UVD_SUVD_CGC_GATE__SCM_MASK
		| UVD_SUVD_CGC_GATE__SDB_MASK
		| UVD_SUVD_CGC_GATE__SRE_H264_MASK
		| UVD_SUVD_CGC_GATE__SRE_HEVC_MASK
		| UVD_SUVD_CGC_GATE__SIT_H264_MASK
		| UVD_SUVD_CGC_GATE__SIT_HEVC_MASK
		| UVD_SUVD_CGC_GATE__SCM_H264_MASK
		| UVD_SUVD_CGC_GATE__SCM_HEVC_MASK
		| UVD_SUVD_CGC_GATE__SDB_H264_MASK
		| UVD_SUVD_CGC_GATE__SDB_HEVC_MASK
		| UVD_SUVD_CGC_GATE__SCLR_MASK
		| UVD_SUVD_CGC_GATE__UVD_SC_MASK
		| UVD_SUVD_CGC_GATE__ENT_MASK
		| UVD_SUVD_CGC_GATE__SIT_HEVC_DEC_MASK
		| UVD_SUVD_CGC_GATE__SIT_HEVC_ENC_MASK
		| UVD_SUVD_CGC_GATE__SITE_MASK
		| UVD_SUVD_CGC_GATE__SRE_VP9_MASK
		| UVD_SUVD_CGC_GATE__SCM_VP9_MASK
		| UVD_SUVD_CGC_GATE__SIT_VP9_DEC_MASK
		| UVD_SUVD_CGC_GATE__SDB_VP9_MASK
		| UVD_SUVD_CGC_GATE__IME_HEVC_MASK);
	WREG32_SOC15(VCN, 0, mmUVD_SUVD_CGC_GATE, data);

	data = RREG32_SOC15(VCN, 0, mmUVD_SUVD_CGC_CTRL);
	data &= ~(UVD_SUVD_CGC_CTRL__SRE_MODE_MASK
		| UVD_SUVD_CGC_CTRL__SIT_MODE_MASK
		| UVD_SUVD_CGC_CTRL__SMP_MODE_MASK
		| UVD_SUVD_CGC_CTRL__SCM_MODE_MASK
		| UVD_SUVD_CGC_CTRL__SDB_MODE_MASK
		| UVD_SUVD_CGC_CTRL__SCLR_MODE_MASK
		| UVD_SUVD_CGC_CTRL__UVD_SC_MODE_MASK
		| UVD_SUVD_CGC_CTRL__ENT_MODE_MASK
		| UVD_SUVD_CGC_CTRL__IME_MODE_MASK
		| UVD_SUVD_CGC_CTRL__SITE_MODE_MASK);
	WREG32_SOC15(VCN, 0, mmUVD_SUVD_CGC_CTRL, data);
}