#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
struct device {int dummy; } ;

/* Variables and functions */
#define  MLXPLAT_CPLD_LPC_REG_AGGRCO_MASK_OFFSET 190 
#define  MLXPLAT_CPLD_LPC_REG_AGGRCO_OFFSET 189 
#define  MLXPLAT_CPLD_LPC_REG_AGGRLO_MASK_OFFSET 188 
#define  MLXPLAT_CPLD_LPC_REG_AGGRLO_OFFSET 187 
#define  MLXPLAT_CPLD_LPC_REG_AGGR_MASK_OFFSET 186 
#define  MLXPLAT_CPLD_LPC_REG_AGGR_OFFSET 185 
#define  MLXPLAT_CPLD_LPC_REG_ASIC_EVENT_OFFSET 184 
#define  MLXPLAT_CPLD_LPC_REG_ASIC_HEALTH_OFFSET 183 
#define  MLXPLAT_CPLD_LPC_REG_ASIC_MASK_OFFSET 182 
#define  MLXPLAT_CPLD_LPC_REG_CPLD1_VER_OFFSET 181 
#define  MLXPLAT_CPLD_LPC_REG_CPLD2_VER_OFFSET 180 
#define  MLXPLAT_CPLD_LPC_REG_CPLD3_VER_OFFSET 179 
#define  MLXPLAT_CPLD_LPC_REG_CPLD4_VER_OFFSET 178 
#define  MLXPLAT_CPLD_LPC_REG_FAN_CAP1_OFFSET 177 
#define  MLXPLAT_CPLD_LPC_REG_FAN_CAP2_OFFSET 176 
#define  MLXPLAT_CPLD_LPC_REG_FAN_DIRECTION 175 
#define  MLXPLAT_CPLD_LPC_REG_FAN_DRW_CAP_OFFSET 174 
#define  MLXPLAT_CPLD_LPC_REG_FAN_EVENT_OFFSET 173 
#define  MLXPLAT_CPLD_LPC_REG_FAN_MASK_OFFSET 172 
#define  MLXPLAT_CPLD_LPC_REG_FAN_OFFSET 171 
#define  MLXPLAT_CPLD_LPC_REG_GP1_OFFSET 170 
#define  MLXPLAT_CPLD_LPC_REG_GP2_OFFSET 169 
#define  MLXPLAT_CPLD_LPC_REG_LED1_OFFSET 168 
#define  MLXPLAT_CPLD_LPC_REG_LED2_OFFSET 167 
#define  MLXPLAT_CPLD_LPC_REG_LED3_OFFSET 166 
#define  MLXPLAT_CPLD_LPC_REG_LED4_OFFSET 165 
#define  MLXPLAT_CPLD_LPC_REG_LED5_OFFSET 164 
#define  MLXPLAT_CPLD_LPC_REG_PSU_EVENT_OFFSET 163 
#define  MLXPLAT_CPLD_LPC_REG_PSU_MASK_OFFSET 162 
#define  MLXPLAT_CPLD_LPC_REG_PSU_OFFSET 161 
#define  MLXPLAT_CPLD_LPC_REG_PWM1_OFFSET 160 
#define  MLXPLAT_CPLD_LPC_REG_PWM_CONTROL_OFFSET 159 
#define  MLXPLAT_CPLD_LPC_REG_PWR_EVENT_OFFSET 158 
#define  MLXPLAT_CPLD_LPC_REG_PWR_MASK_OFFSET 157 
#define  MLXPLAT_CPLD_LPC_REG_PWR_OFFSET 156 
#define  MLXPLAT_CPLD_LPC_REG_RESET_CAUSE_OFFSET 155 
#define  MLXPLAT_CPLD_LPC_REG_RST_CAUSE1_OFFSET 154 
#define  MLXPLAT_CPLD_LPC_REG_RST_CAUSE2_OFFSET 153 
#define  MLXPLAT_CPLD_LPC_REG_TACHO10_OFFSET 152 
#define  MLXPLAT_CPLD_LPC_REG_TACHO11_OFFSET 151 
#define  MLXPLAT_CPLD_LPC_REG_TACHO12_OFFSET 150 
#define  MLXPLAT_CPLD_LPC_REG_TACHO1_OFFSET 149 
#define  MLXPLAT_CPLD_LPC_REG_TACHO2_OFFSET 148 
#define  MLXPLAT_CPLD_LPC_REG_TACHO3_OFFSET 147 
#define  MLXPLAT_CPLD_LPC_REG_TACHO4_OFFSET 146 
#define  MLXPLAT_CPLD_LPC_REG_TACHO5_OFFSET 145 
#define  MLXPLAT_CPLD_LPC_REG_TACHO6_OFFSET 144 
#define  MLXPLAT_CPLD_LPC_REG_TACHO7_OFFSET 143 
#define  MLXPLAT_CPLD_LPC_REG_TACHO8_OFFSET 142 
#define  MLXPLAT_CPLD_LPC_REG_TACHO9_OFFSET 141 
#define  MLXPLAT_CPLD_LPC_REG_TACHO_SPEED_OFFSET 140 
#define  MLXPLAT_CPLD_LPC_REG_WD1_ACT_OFFSET 139 
#define  MLXPLAT_CPLD_LPC_REG_WD1_TMR_OFFSET 138 
#define  MLXPLAT_CPLD_LPC_REG_WD2_ACT_OFFSET 137 
#define  MLXPLAT_CPLD_LPC_REG_WD2_TLEFT_OFFSET 136 
#define  MLXPLAT_CPLD_LPC_REG_WD2_TMR_OFFSET 135 
#define  MLXPLAT_CPLD_LPC_REG_WD3_ACT_OFFSET 134 
#define  MLXPLAT_CPLD_LPC_REG_WD3_TLEFT_OFFSET 133 
#define  MLXPLAT_CPLD_LPC_REG_WD3_TMR_OFFSET 132 
#define  MLXPLAT_CPLD_LPC_REG_WD_CLEAR_OFFSET 131 
#define  MLXPLAT_CPLD_LPC_REG_WD_CLEAR_WP_OFFSET 130 
#define  MLXPLAT_CPLD_LPC_REG_WP1_OFFSET 129 
#define  MLXPLAT_CPLD_LPC_REG_WP2_OFFSET 128 

__attribute__((used)) static bool mlxplat_mlxcpld_readable_reg(struct device *dev, unsigned int reg)
{
	switch (reg) {
	case MLXPLAT_CPLD_LPC_REG_CPLD1_VER_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_CPLD2_VER_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_CPLD3_VER_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_CPLD4_VER_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_RESET_CAUSE_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_RST_CAUSE1_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_RST_CAUSE2_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_LED1_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_LED2_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_LED3_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_LED4_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_LED5_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_FAN_DIRECTION:
	case MLXPLAT_CPLD_LPC_REG_GP1_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_WP1_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_GP2_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_WP2_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_AGGR_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_AGGR_MASK_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_AGGRLO_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_AGGRLO_MASK_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_AGGRCO_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_AGGRCO_MASK_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_ASIC_HEALTH_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_ASIC_EVENT_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_ASIC_MASK_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_PSU_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_PSU_EVENT_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_PSU_MASK_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_PWR_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_PWR_EVENT_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_PWR_MASK_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_FAN_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_FAN_EVENT_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_FAN_MASK_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_WD_CLEAR_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_WD_CLEAR_WP_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_WD1_TMR_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_WD1_ACT_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_WD2_TMR_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_WD2_TLEFT_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_WD2_ACT_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_WD3_TMR_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_WD3_TLEFT_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_WD3_ACT_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_PWM1_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_TACHO1_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_TACHO2_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_TACHO3_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_TACHO4_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_TACHO5_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_TACHO6_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_TACHO7_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_TACHO8_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_TACHO9_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_TACHO10_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_TACHO11_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_TACHO12_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_PWM_CONTROL_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_FAN_CAP1_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_FAN_CAP2_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_FAN_DRW_CAP_OFFSET:
	case MLXPLAT_CPLD_LPC_REG_TACHO_SPEED_OFFSET:
		return true;
	}
	return false;
}