#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  enum wined3d_render_state { ____Placeholder_wined3d_render_state } wined3d_render_state ;

/* Variables and functions */
 int /*<<< orphan*/  FIXME (char*,int) ; 
#define  WINED3D_RS_ADAPTIVETESS_W 258 
#define  WINED3D_RS_ADAPTIVETESS_X 257 
#define  WINED3D_RS_ADAPTIVETESS_Y 256 
#define  WINED3D_RS_ADAPTIVETESS_Z 255 
#define  WINED3D_RS_ALPHABLENDENABLE 254 
#define  WINED3D_RS_ALPHAFUNC 253 
#define  WINED3D_RS_ALPHAREF 252 
#define  WINED3D_RS_ALPHATESTENABLE 251 
#define  WINED3D_RS_AMBIENT 250 
#define  WINED3D_RS_AMBIENTMATERIALSOURCE 249 
#define  WINED3D_RS_ANISOTROPY 248 
#define  WINED3D_RS_ANTIALIAS 247 
#define  WINED3D_RS_ANTIALIASEDLINEENABLE 246 
#define  WINED3D_RS_BACK_STENCILFAIL 245 
#define  WINED3D_RS_BACK_STENCILFUNC 244 
#define  WINED3D_RS_BACK_STENCILPASS 243 
#define  WINED3D_RS_BACK_STENCILZFAIL 242 
#define  WINED3D_RS_BLENDFACTOR 241 
#define  WINED3D_RS_BLENDOP 240 
#define  WINED3D_RS_BLENDOPALPHA 239 
#define  WINED3D_RS_CLIPPING 238 
#define  WINED3D_RS_CLIPPLANEENABLE 237 
#define  WINED3D_RS_COLORKEYBLENDENABLE 236 
#define  WINED3D_RS_COLORKEYENABLE 235 
#define  WINED3D_RS_COLORVERTEX 234 
#define  WINED3D_RS_COLORWRITEENABLE 233 
#define  WINED3D_RS_COLORWRITEENABLE1 232 
#define  WINED3D_RS_COLORWRITEENABLE2 231 
#define  WINED3D_RS_COLORWRITEENABLE3 230 
#define  WINED3D_RS_COLORWRITEENABLE4 229 
#define  WINED3D_RS_COLORWRITEENABLE5 228 
#define  WINED3D_RS_COLORWRITEENABLE6 227 
#define  WINED3D_RS_COLORWRITEENABLE7 226 
#define  WINED3D_RS_CULLMODE 225 
#define  WINED3D_RS_DEBUGMONITORTOKEN 224 
#define  WINED3D_RS_DEPTHBIAS 223 
#define  WINED3D_RS_DEPTHBIASCLAMP 222 
#define  WINED3D_RS_DESTBLEND 221 
#define  WINED3D_RS_DESTBLENDALPHA 220 
#define  WINED3D_RS_DIFFUSEMATERIALSOURCE 219 
#define  WINED3D_RS_DITHERENABLE 218 
#define  WINED3D_RS_EDGEANTIALIAS 217 
#define  WINED3D_RS_EMISSIVEMATERIALSOURCE 216 
#define  WINED3D_RS_ENABLEADAPTIVETESSELLATION 215 
#define  WINED3D_RS_EXTENTS 214 
#define  WINED3D_RS_FILLMODE 213 
#define  WINED3D_RS_FLUSHBATCH 212 
#define  WINED3D_RS_FOGCOLOR 211 
#define  WINED3D_RS_FOGDENSITY 210 
#define  WINED3D_RS_FOGENABLE 209 
#define  WINED3D_RS_FOGEND 208 
#define  WINED3D_RS_FOGSTART 207 
#define  WINED3D_RS_FOGTABLEMODE 206 
#define  WINED3D_RS_FOGVERTEXMODE 205 
#define  WINED3D_RS_INDEXEDVERTEXBLENDENABLE 204 
#define  WINED3D_RS_LASTPIXEL 203 
#define  WINED3D_RS_LIGHTING 202 
#define  WINED3D_RS_LINEPATTERN 201 
#define  WINED3D_RS_LOCALVIEWER 200 
#define  WINED3D_RS_MAXTESSELLATIONLEVEL 199 
#define  WINED3D_RS_MINTESSELLATIONLEVEL 198 
#define  WINED3D_RS_MIPMAPLODBIAS 197 
#define  WINED3D_RS_MONOENABLE 196 
#define  WINED3D_RS_MULTISAMPLEANTIALIAS 195 
#define  WINED3D_RS_MULTISAMPLEMASK 194 
#define  WINED3D_RS_NORMALDEGREE 193 
#define  WINED3D_RS_NORMALIZENORMALS 192 
#define  WINED3D_RS_PATCHEDGESTYLE 191 
#define  WINED3D_RS_PATCHSEGMENTS 190 
#define  WINED3D_RS_PLANEMASK 189 
#define  WINED3D_RS_POINTSCALEENABLE 188 
#define  WINED3D_RS_POINTSCALE_A 187 
#define  WINED3D_RS_POINTSCALE_B 186 
#define  WINED3D_RS_POINTSCALE_C 185 
#define  WINED3D_RS_POINTSIZE 184 
#define  WINED3D_RS_POINTSIZE_MAX 183 
#define  WINED3D_RS_POINTSIZE_MIN 182 
#define  WINED3D_RS_POINTSPRITEENABLE 181 
#define  WINED3D_RS_POSITIONDEGREE 180 
#define  WINED3D_RS_RANGEFOGENABLE 179 
#define  WINED3D_RS_ROP2 178 
#define  WINED3D_RS_SCISSORTESTENABLE 177 
#define  WINED3D_RS_SEPARATEALPHABLENDENABLE 176 
#define  WINED3D_RS_SHADEMODE 175 
#define  WINED3D_RS_SLOPESCALEDEPTHBIAS 174 
#define  WINED3D_RS_SOFTWAREVERTEXPROCESSING 173 
#define  WINED3D_RS_SPECULARENABLE 172 
#define  WINED3D_RS_SPECULARMATERIALSOURCE 171 
#define  WINED3D_RS_SRCBLEND 170 
#define  WINED3D_RS_SRCBLENDALPHA 169 
#define  WINED3D_RS_SRGBWRITEENABLE 168 
#define  WINED3D_RS_STENCILENABLE 167 
#define  WINED3D_RS_STENCILFAIL 166 
#define  WINED3D_RS_STENCILFUNC 165 
#define  WINED3D_RS_STENCILMASK 164 
#define  WINED3D_RS_STENCILPASS 163 
#define  WINED3D_RS_STENCILREF 162 
#define  WINED3D_RS_STENCILWRITEMASK 161 
#define  WINED3D_RS_STENCILZFAIL 160 
#define  WINED3D_RS_STIPPLEDALPHA 159 
#define  WINED3D_RS_STIPPLEENABLE 158 
#define  WINED3D_RS_SUBPIXEL 157 
#define  WINED3D_RS_SUBPIXELX 156 
#define  WINED3D_RS_TEXTUREFACTOR 155 
#define  WINED3D_RS_TEXTUREPERSPECTIVE 154 
#define  WINED3D_RS_TRANSLUCENTSORTINDEPENDENT 153 
#define  WINED3D_RS_TWEENFACTOR 152 
#define  WINED3D_RS_TWOSIDEDSTENCILMODE 151 
#define  WINED3D_RS_VERTEXBLEND 150 
#define  WINED3D_RS_WRAP0 149 
#define  WINED3D_RS_WRAP1 148 
#define  WINED3D_RS_WRAP10 147 
#define  WINED3D_RS_WRAP11 146 
#define  WINED3D_RS_WRAP12 145 
#define  WINED3D_RS_WRAP13 144 
#define  WINED3D_RS_WRAP14 143 
#define  WINED3D_RS_WRAP15 142 
#define  WINED3D_RS_WRAP2 141 
#define  WINED3D_RS_WRAP3 140 
#define  WINED3D_RS_WRAP4 139 
#define  WINED3D_RS_WRAP5 138 
#define  WINED3D_RS_WRAP6 137 
#define  WINED3D_RS_WRAP7 136 
#define  WINED3D_RS_WRAP8 135 
#define  WINED3D_RS_WRAP9 134 
#define  WINED3D_RS_WRAPU 133 
#define  WINED3D_RS_WRAPV 132 
#define  WINED3D_RS_ZENABLE 131 
#define  WINED3D_RS_ZFUNC 130 
#define  WINED3D_RS_ZVISIBLE 129 
#define  WINED3D_RS_ZWRITEENABLE 128 

const char *debug_d3drenderstate(enum wined3d_render_state state)
{
    switch (state)
    {
#define D3DSTATE_TO_STR(u) case u: return #u
        D3DSTATE_TO_STR(WINED3D_RS_ANTIALIAS);
        D3DSTATE_TO_STR(WINED3D_RS_TEXTUREPERSPECTIVE);
        D3DSTATE_TO_STR(WINED3D_RS_WRAPU);
        D3DSTATE_TO_STR(WINED3D_RS_WRAPV);
        D3DSTATE_TO_STR(WINED3D_RS_ZENABLE);
        D3DSTATE_TO_STR(WINED3D_RS_FILLMODE);
        D3DSTATE_TO_STR(WINED3D_RS_SHADEMODE);
        D3DSTATE_TO_STR(WINED3D_RS_LINEPATTERN);
        D3DSTATE_TO_STR(WINED3D_RS_MONOENABLE);
        D3DSTATE_TO_STR(WINED3D_RS_ROP2);
        D3DSTATE_TO_STR(WINED3D_RS_PLANEMASK);
        D3DSTATE_TO_STR(WINED3D_RS_ZWRITEENABLE);
        D3DSTATE_TO_STR(WINED3D_RS_ALPHATESTENABLE);
        D3DSTATE_TO_STR(WINED3D_RS_LASTPIXEL);
        D3DSTATE_TO_STR(WINED3D_RS_SRCBLEND);
        D3DSTATE_TO_STR(WINED3D_RS_DESTBLEND);
        D3DSTATE_TO_STR(WINED3D_RS_CULLMODE);
        D3DSTATE_TO_STR(WINED3D_RS_ZFUNC);
        D3DSTATE_TO_STR(WINED3D_RS_ALPHAREF);
        D3DSTATE_TO_STR(WINED3D_RS_ALPHAFUNC);
        D3DSTATE_TO_STR(WINED3D_RS_DITHERENABLE);
        D3DSTATE_TO_STR(WINED3D_RS_ALPHABLENDENABLE);
        D3DSTATE_TO_STR(WINED3D_RS_FOGENABLE);
        D3DSTATE_TO_STR(WINED3D_RS_SPECULARENABLE);
        D3DSTATE_TO_STR(WINED3D_RS_ZVISIBLE);
        D3DSTATE_TO_STR(WINED3D_RS_SUBPIXEL);
        D3DSTATE_TO_STR(WINED3D_RS_SUBPIXELX);
        D3DSTATE_TO_STR(WINED3D_RS_STIPPLEDALPHA);
        D3DSTATE_TO_STR(WINED3D_RS_FOGCOLOR);
        D3DSTATE_TO_STR(WINED3D_RS_FOGTABLEMODE);
        D3DSTATE_TO_STR(WINED3D_RS_FOGSTART);
        D3DSTATE_TO_STR(WINED3D_RS_FOGEND);
        D3DSTATE_TO_STR(WINED3D_RS_FOGDENSITY);
        D3DSTATE_TO_STR(WINED3D_RS_STIPPLEENABLE);
        D3DSTATE_TO_STR(WINED3D_RS_EDGEANTIALIAS);
        D3DSTATE_TO_STR(WINED3D_RS_COLORKEYENABLE);
        D3DSTATE_TO_STR(WINED3D_RS_MIPMAPLODBIAS);
        D3DSTATE_TO_STR(WINED3D_RS_RANGEFOGENABLE);
        D3DSTATE_TO_STR(WINED3D_RS_ANISOTROPY);
        D3DSTATE_TO_STR(WINED3D_RS_FLUSHBATCH);
        D3DSTATE_TO_STR(WINED3D_RS_TRANSLUCENTSORTINDEPENDENT);
        D3DSTATE_TO_STR(WINED3D_RS_STENCILENABLE);
        D3DSTATE_TO_STR(WINED3D_RS_STENCILFAIL);
        D3DSTATE_TO_STR(WINED3D_RS_STENCILZFAIL);
        D3DSTATE_TO_STR(WINED3D_RS_STENCILPASS);
        D3DSTATE_TO_STR(WINED3D_RS_STENCILFUNC);
        D3DSTATE_TO_STR(WINED3D_RS_STENCILREF);
        D3DSTATE_TO_STR(WINED3D_RS_STENCILMASK);
        D3DSTATE_TO_STR(WINED3D_RS_STENCILWRITEMASK);
        D3DSTATE_TO_STR(WINED3D_RS_TEXTUREFACTOR);
        D3DSTATE_TO_STR(WINED3D_RS_WRAP0);
        D3DSTATE_TO_STR(WINED3D_RS_WRAP1);
        D3DSTATE_TO_STR(WINED3D_RS_WRAP2);
        D3DSTATE_TO_STR(WINED3D_RS_WRAP3);
        D3DSTATE_TO_STR(WINED3D_RS_WRAP4);
        D3DSTATE_TO_STR(WINED3D_RS_WRAP5);
        D3DSTATE_TO_STR(WINED3D_RS_WRAP6);
        D3DSTATE_TO_STR(WINED3D_RS_WRAP7);
        D3DSTATE_TO_STR(WINED3D_RS_CLIPPING);
        D3DSTATE_TO_STR(WINED3D_RS_LIGHTING);
        D3DSTATE_TO_STR(WINED3D_RS_EXTENTS);
        D3DSTATE_TO_STR(WINED3D_RS_AMBIENT);
        D3DSTATE_TO_STR(WINED3D_RS_FOGVERTEXMODE);
        D3DSTATE_TO_STR(WINED3D_RS_COLORVERTEX);
        D3DSTATE_TO_STR(WINED3D_RS_LOCALVIEWER);
        D3DSTATE_TO_STR(WINED3D_RS_NORMALIZENORMALS);
        D3DSTATE_TO_STR(WINED3D_RS_COLORKEYBLENDENABLE);
        D3DSTATE_TO_STR(WINED3D_RS_DIFFUSEMATERIALSOURCE);
        D3DSTATE_TO_STR(WINED3D_RS_SPECULARMATERIALSOURCE);
        D3DSTATE_TO_STR(WINED3D_RS_AMBIENTMATERIALSOURCE);
        D3DSTATE_TO_STR(WINED3D_RS_EMISSIVEMATERIALSOURCE);
        D3DSTATE_TO_STR(WINED3D_RS_VERTEXBLEND);
        D3DSTATE_TO_STR(WINED3D_RS_CLIPPLANEENABLE);
        D3DSTATE_TO_STR(WINED3D_RS_SOFTWAREVERTEXPROCESSING);
        D3DSTATE_TO_STR(WINED3D_RS_POINTSIZE);
        D3DSTATE_TO_STR(WINED3D_RS_POINTSIZE_MIN);
        D3DSTATE_TO_STR(WINED3D_RS_POINTSPRITEENABLE);
        D3DSTATE_TO_STR(WINED3D_RS_POINTSCALEENABLE);
        D3DSTATE_TO_STR(WINED3D_RS_POINTSCALE_A);
        D3DSTATE_TO_STR(WINED3D_RS_POINTSCALE_B);
        D3DSTATE_TO_STR(WINED3D_RS_POINTSCALE_C);
        D3DSTATE_TO_STR(WINED3D_RS_MULTISAMPLEANTIALIAS);
        D3DSTATE_TO_STR(WINED3D_RS_MULTISAMPLEMASK);
        D3DSTATE_TO_STR(WINED3D_RS_PATCHEDGESTYLE);
        D3DSTATE_TO_STR(WINED3D_RS_PATCHSEGMENTS);
        D3DSTATE_TO_STR(WINED3D_RS_DEBUGMONITORTOKEN);
        D3DSTATE_TO_STR(WINED3D_RS_POINTSIZE_MAX);
        D3DSTATE_TO_STR(WINED3D_RS_INDEXEDVERTEXBLENDENABLE);
        D3DSTATE_TO_STR(WINED3D_RS_TWEENFACTOR);
        D3DSTATE_TO_STR(WINED3D_RS_BLENDOP);
        D3DSTATE_TO_STR(WINED3D_RS_POSITIONDEGREE);
        D3DSTATE_TO_STR(WINED3D_RS_NORMALDEGREE);
        D3DSTATE_TO_STR(WINED3D_RS_SCISSORTESTENABLE);
        D3DSTATE_TO_STR(WINED3D_RS_SLOPESCALEDEPTHBIAS);
        D3DSTATE_TO_STR(WINED3D_RS_ANTIALIASEDLINEENABLE);
        D3DSTATE_TO_STR(WINED3D_RS_MINTESSELLATIONLEVEL);
        D3DSTATE_TO_STR(WINED3D_RS_MAXTESSELLATIONLEVEL);
        D3DSTATE_TO_STR(WINED3D_RS_ADAPTIVETESS_X);
        D3DSTATE_TO_STR(WINED3D_RS_ADAPTIVETESS_Y);
        D3DSTATE_TO_STR(WINED3D_RS_ADAPTIVETESS_Z);
        D3DSTATE_TO_STR(WINED3D_RS_ADAPTIVETESS_W);
        D3DSTATE_TO_STR(WINED3D_RS_ENABLEADAPTIVETESSELLATION);
        D3DSTATE_TO_STR(WINED3D_RS_TWOSIDEDSTENCILMODE);
        D3DSTATE_TO_STR(WINED3D_RS_BACK_STENCILFAIL);
        D3DSTATE_TO_STR(WINED3D_RS_BACK_STENCILZFAIL);
        D3DSTATE_TO_STR(WINED3D_RS_BACK_STENCILPASS);
        D3DSTATE_TO_STR(WINED3D_RS_BACK_STENCILFUNC);
        D3DSTATE_TO_STR(WINED3D_RS_COLORWRITEENABLE);
        D3DSTATE_TO_STR(WINED3D_RS_COLORWRITEENABLE1);
        D3DSTATE_TO_STR(WINED3D_RS_COLORWRITEENABLE2);
        D3DSTATE_TO_STR(WINED3D_RS_COLORWRITEENABLE3);
        D3DSTATE_TO_STR(WINED3D_RS_COLORWRITEENABLE4);
        D3DSTATE_TO_STR(WINED3D_RS_COLORWRITEENABLE5);
        D3DSTATE_TO_STR(WINED3D_RS_COLORWRITEENABLE6);
        D3DSTATE_TO_STR(WINED3D_RS_COLORWRITEENABLE7);
        D3DSTATE_TO_STR(WINED3D_RS_BLENDFACTOR);
        D3DSTATE_TO_STR(WINED3D_RS_SRGBWRITEENABLE);
        D3DSTATE_TO_STR(WINED3D_RS_DEPTHBIAS);
        D3DSTATE_TO_STR(WINED3D_RS_DEPTHBIASCLAMP);
        D3DSTATE_TO_STR(WINED3D_RS_WRAP8);
        D3DSTATE_TO_STR(WINED3D_RS_WRAP9);
        D3DSTATE_TO_STR(WINED3D_RS_WRAP10);
        D3DSTATE_TO_STR(WINED3D_RS_WRAP11);
        D3DSTATE_TO_STR(WINED3D_RS_WRAP12);
        D3DSTATE_TO_STR(WINED3D_RS_WRAP13);
        D3DSTATE_TO_STR(WINED3D_RS_WRAP14);
        D3DSTATE_TO_STR(WINED3D_RS_WRAP15);
        D3DSTATE_TO_STR(WINED3D_RS_SEPARATEALPHABLENDENABLE);
        D3DSTATE_TO_STR(WINED3D_RS_SRCBLENDALPHA);
        D3DSTATE_TO_STR(WINED3D_RS_DESTBLENDALPHA);
        D3DSTATE_TO_STR(WINED3D_RS_BLENDOPALPHA);
#undef D3DSTATE_TO_STR
        default:
            FIXME("Unrecognized %u render state!\n", state);
            return "unrecognized";
    }
}