#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  int MCIERROR ;

/* Variables and functions */
#define  MCIERR_BAD_CONSTANT 202 
#define  MCIERR_BAD_INTEGER 201 
#define  MCIERR_BAD_TIME_FORMAT 200 
#define  MCIERR_CANNOT_LOAD_DRIVER 199 
#define  MCIERR_CANNOT_USE_ALL 198 
#define  MCIERR_CREATEWINDOW 197 
#define  MCIERR_DEVICE_LENGTH 196 
#define  MCIERR_DEVICE_LOCKED 195 
#define  MCIERR_DEVICE_NOT_INSTALLED 194 
#define  MCIERR_DEVICE_NOT_READY 193 
#define  MCIERR_DEVICE_OPEN 192 
#define  MCIERR_DEVICE_ORD_LENGTH 191 
#define  MCIERR_DEVICE_TYPE_REQUIRED 190 
#define  MCIERR_DRIVER 189 
#define  MCIERR_DRIVER_INTERNAL 188 
#define  MCIERR_DUPLICATE_ALIAS 187 
#define  MCIERR_DUPLICATE_FLAGS 186 
#define  MCIERR_EXTENSION_NOT_FOUND 185 
#define  MCIERR_EXTRA_CHARACTERS 184 
#define  MCIERR_FILENAME_REQUIRED 183 
#define  MCIERR_FILE_NOT_FOUND 182 
#define  MCIERR_FILE_NOT_SAVED 181 
#define  MCIERR_FILE_READ 180 
#define  MCIERR_FILE_WRITE 179 
#define  MCIERR_FLAGS_NOT_COMPATIBLE 178 
#define  MCIERR_GET_CD 177 
#define  MCIERR_HARDWARE 176 
#define  MCIERR_ILLEGAL_FOR_AUTO_OPEN 175 
#define  MCIERR_INTERNAL 174 
#define  MCIERR_INVALID_DEVICE_ID 173 
#define  MCIERR_INVALID_DEVICE_NAME 172 
#define  MCIERR_INVALID_FILE 171 
#define  MCIERR_MISSING_COMMAND_STRING 170 
#define  MCIERR_MISSING_DEVICE_NAME 169 
#define  MCIERR_MISSING_PARAMETER 168 
#define  MCIERR_MISSING_STRING_ARGUMENT 167 
#define  MCIERR_MULTIPLE 166 
#define  MCIERR_MUST_USE_SHAREABLE 165 
#define  MCIERR_NEW_REQUIRES_ALIAS 164 
#define  MCIERR_NONAPPLICABLE_FUNCTION 163 
#define  MCIERR_NOTIFY_ON_AUTO_OPEN 162 
#define  MCIERR_NO_CLOSING_QUOTE 161 
#define  MCIERR_NO_ELEMENT_ALLOWED 160 
#define  MCIERR_NO_IDENTITY 159 
#define  MCIERR_NO_INTEGER 158 
#define  MCIERR_NO_WINDOW 157 
#define  MCIERR_NULL_PARAMETER_BLOCK 156 
#define  MCIERR_OUTOFRANGE 155 
#define  MCIERR_OUT_OF_MEMORY 154 
#define  MCIERR_PARAM_OVERFLOW 153 
#define  MCIERR_PARSER_INTERNAL 152 
#define  MCIERR_SEQ_DIV_INCOMPATIBLE 151 
#define  MCIERR_SEQ_NOMIDIPRESENT 150 
#define  MCIERR_SEQ_PORTUNSPECIFIED 149 
#define  MCIERR_SEQ_PORT_INUSE 148 
#define  MCIERR_SEQ_PORT_MAPNODEVICE 147 
#define  MCIERR_SEQ_PORT_MISCERROR 146 
#define  MCIERR_SEQ_PORT_NONEXISTENT 145 
#define  MCIERR_SEQ_TIMER 144 
#define  MCIERR_SET_CD 143 
#define  MCIERR_SET_DRIVE 142 
#define  MCIERR_UNNAMED_RESOURCE 141 
#define  MCIERR_UNRECOGNIZED_COMMAND 140 
#define  MCIERR_UNRECOGNIZED_KEYWORD 139 
#define  MCIERR_UNSUPPORTED_FUNCTION 138 
#define  MCIERR_WAVE_INPUTSINUSE 137 
#define  MCIERR_WAVE_INPUTSUNSUITABLE 136 
#define  MCIERR_WAVE_INPUTUNSPECIFIED 135 
#define  MCIERR_WAVE_OUTPUTSINUSE 134 
#define  MCIERR_WAVE_OUTPUTSUNSUITABLE 133 
#define  MCIERR_WAVE_OUTPUTUNSPECIFIED 132 
#define  MCIERR_WAVE_SETINPUTINUSE 131 
#define  MCIERR_WAVE_SETINPUTUNSUITABLE 130 
#define  MCIERR_WAVE_SETOUTPUTINUSE 129 
#define  MCIERR_WAVE_SETOUTPUTUNSUITABLE 128 
 int /*<<< orphan*/  sprintf (char*,char*,int) ; 

const char* dbg_mcierr(MCIERROR err)
{
     switch (err) {
     case 0: return "0=NOERROR";
#define X(label) case label: return #label ;
     X(MCIERR_INVALID_DEVICE_ID)
     X(MCIERR_UNRECOGNIZED_KEYWORD)
     X(MCIERR_UNRECOGNIZED_COMMAND)
     X(MCIERR_HARDWARE)
     X(MCIERR_INVALID_DEVICE_NAME)
     X(MCIERR_OUT_OF_MEMORY)
     X(MCIERR_DEVICE_OPEN)
     X(MCIERR_CANNOT_LOAD_DRIVER)
     X(MCIERR_MISSING_COMMAND_STRING)
     X(MCIERR_PARAM_OVERFLOW)
     X(MCIERR_MISSING_STRING_ARGUMENT)
     X(MCIERR_BAD_INTEGER)
     X(MCIERR_PARSER_INTERNAL)
     X(MCIERR_DRIVER_INTERNAL)
     X(MCIERR_MISSING_PARAMETER)
     X(MCIERR_UNSUPPORTED_FUNCTION)
     X(MCIERR_FILE_NOT_FOUND)
     X(MCIERR_DEVICE_NOT_READY)
     X(MCIERR_INTERNAL)
     X(MCIERR_DRIVER)
     X(MCIERR_CANNOT_USE_ALL)
     X(MCIERR_MULTIPLE)
     X(MCIERR_EXTENSION_NOT_FOUND)
     X(MCIERR_OUTOFRANGE)
     X(MCIERR_FLAGS_NOT_COMPATIBLE)
     X(MCIERR_FILE_NOT_SAVED)
     X(MCIERR_DEVICE_TYPE_REQUIRED)
     X(MCIERR_DEVICE_LOCKED)
     X(MCIERR_DUPLICATE_ALIAS)
     X(MCIERR_BAD_CONSTANT)
     X(MCIERR_MUST_USE_SHAREABLE)
     X(MCIERR_MISSING_DEVICE_NAME)
     X(MCIERR_BAD_TIME_FORMAT)
     X(MCIERR_NO_CLOSING_QUOTE)
     X(MCIERR_DUPLICATE_FLAGS)
     X(MCIERR_INVALID_FILE)
     X(MCIERR_NULL_PARAMETER_BLOCK)
     X(MCIERR_UNNAMED_RESOURCE)
     X(MCIERR_NEW_REQUIRES_ALIAS)
     X(MCIERR_NOTIFY_ON_AUTO_OPEN)
     X(MCIERR_NO_ELEMENT_ALLOWED)
     X(MCIERR_NONAPPLICABLE_FUNCTION)
     X(MCIERR_ILLEGAL_FOR_AUTO_OPEN)
     X(MCIERR_FILENAME_REQUIRED)
     X(MCIERR_EXTRA_CHARACTERS)
     X(MCIERR_DEVICE_NOT_INSTALLED)
     X(MCIERR_GET_CD)
     X(MCIERR_SET_CD)
     X(MCIERR_SET_DRIVE)
     X(MCIERR_DEVICE_LENGTH)
     X(MCIERR_DEVICE_ORD_LENGTH)
     X(MCIERR_NO_INTEGER)
     X(MCIERR_WAVE_OUTPUTSINUSE)
     X(MCIERR_WAVE_SETOUTPUTINUSE)
     X(MCIERR_WAVE_INPUTSINUSE)
     X(MCIERR_WAVE_SETINPUTINUSE)
     X(MCIERR_WAVE_OUTPUTUNSPECIFIED)
     X(MCIERR_WAVE_INPUTUNSPECIFIED)
     X(MCIERR_WAVE_OUTPUTSUNSUITABLE)
     X(MCIERR_WAVE_SETOUTPUTUNSUITABLE)
     X(MCIERR_WAVE_INPUTSUNSUITABLE)
     X(MCIERR_WAVE_SETINPUTUNSUITABLE)
     X(MCIERR_SEQ_DIV_INCOMPATIBLE)
     X(MCIERR_SEQ_PORT_INUSE)
     X(MCIERR_SEQ_PORT_NONEXISTENT)
     X(MCIERR_SEQ_PORT_MAPNODEVICE)
     X(MCIERR_SEQ_PORT_MISCERROR)
     X(MCIERR_SEQ_TIMER)
     X(MCIERR_SEQ_PORTUNSPECIFIED)
     X(MCIERR_SEQ_NOMIDIPRESENT)
     X(MCIERR_NO_WINDOW)
     X(MCIERR_CREATEWINDOW)
     X(MCIERR_FILE_READ)
     X(MCIERR_FILE_WRITE)
     X(MCIERR_NO_IDENTITY)
#undef X
     default: {
         static char name[20]; /* Not to be called twice in a parameter list! */
         sprintf(name, "MMSYSERR %u", err);
         return name;
         }
     }
}