#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  int MMRESULT ;

/* Variables and functions */
#define  MIDIERR_INVALIDSETUP 156 
#define  MIDIERR_NODEVICE 155 
#define  MIDIERR_STILLPLAYING 154 
#define  MIDIERR_UNPREPARED 153 
#define  MMSYSERR_ALLOCATED 152 
#define  MMSYSERR_BADDB 151 
#define  MMSYSERR_BADDEVICEID 150 
#define  MMSYSERR_BADERRNUM 149 
#define  MMSYSERR_DELETEERROR 148 
#define  MMSYSERR_ERROR 147 
#define  MMSYSERR_HANDLEBUSY 146 
#define  MMSYSERR_INVALFLAG 145 
#define  MMSYSERR_INVALHANDLE 144 
#define  MMSYSERR_INVALIDALIAS 143 
#define  MMSYSERR_INVALPARAM 142 
#define  MMSYSERR_KEYNOTFOUND 141 
#define  MMSYSERR_NODRIVER 140 
#define  MMSYSERR_NODRIVERCB 139 
#define  MMSYSERR_NOERROR 138 
#define  MMSYSERR_NOMEM 137 
#define  MMSYSERR_NOTENABLED 136 
#define  MMSYSERR_NOTSUPPORTED 135 
#define  MMSYSERR_READERROR 134 
#define  MMSYSERR_VALNOTFOUND 133 
#define  MMSYSERR_WRITEERROR 132 
#define  WAVERR_BADFORMAT 131 
#define  WAVERR_STILLPLAYING 130 
#define  WAVERR_SYNC 129 
#define  WAVERR_UNPREPARED 128 
 int /*<<< orphan*/  sprintf (char*,char*,int) ; 

const char* WINMM_ErrorToString(MMRESULT error)
{
#define ERR_TO_STR(dev) case dev: return #dev
    static char unknown[32];
    switch (error) {
    ERR_TO_STR(MMSYSERR_NOERROR);
    ERR_TO_STR(MMSYSERR_ERROR);
    ERR_TO_STR(MMSYSERR_BADDEVICEID);
    ERR_TO_STR(MMSYSERR_NOTENABLED);
    ERR_TO_STR(MMSYSERR_ALLOCATED);
    ERR_TO_STR(MMSYSERR_INVALHANDLE);
    ERR_TO_STR(MMSYSERR_NODRIVER);
    ERR_TO_STR(MMSYSERR_NOMEM);
    ERR_TO_STR(MMSYSERR_NOTSUPPORTED);
    ERR_TO_STR(MMSYSERR_BADERRNUM);
    ERR_TO_STR(MMSYSERR_INVALFLAG);
    ERR_TO_STR(MMSYSERR_INVALPARAM);
    ERR_TO_STR(MMSYSERR_HANDLEBUSY);
    ERR_TO_STR(MMSYSERR_INVALIDALIAS);
    ERR_TO_STR(MMSYSERR_BADDB);
    ERR_TO_STR(MMSYSERR_KEYNOTFOUND);
    ERR_TO_STR(MMSYSERR_READERROR);
    ERR_TO_STR(MMSYSERR_WRITEERROR);
    ERR_TO_STR(MMSYSERR_DELETEERROR);
    ERR_TO_STR(MMSYSERR_VALNOTFOUND);
    ERR_TO_STR(MMSYSERR_NODRIVERCB);
    ERR_TO_STR(WAVERR_BADFORMAT);
    ERR_TO_STR(WAVERR_STILLPLAYING);
    ERR_TO_STR(WAVERR_UNPREPARED);
    ERR_TO_STR(WAVERR_SYNC);
    ERR_TO_STR(MIDIERR_INVALIDSETUP);
    ERR_TO_STR(MIDIERR_NODEVICE);
    ERR_TO_STR(MIDIERR_STILLPLAYING);
    ERR_TO_STR(MIDIERR_UNPREPARED);
    }
    sprintf(unknown, "Unknown(0x%08x)", error);
    return unknown;
#undef ERR_TO_STR
}