#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  int WORD ;

/* Variables and functions */
#define  WAVE_FORMAT_ADPCM 169 
#define  WAVE_FORMAT_ALAW 168 
#define  WAVE_FORMAT_ANTEX_ADPCME 167 
#define  WAVE_FORMAT_APTX 166 
#define  WAVE_FORMAT_AUDIOFILE_AF10 165 
#define  WAVE_FORMAT_AUDIOFILE_AF36 164 
#define  WAVE_FORMAT_CONTROL_RES_CR10 163 
#define  WAVE_FORMAT_CONTROL_RES_VQLPC 162 
#define  WAVE_FORMAT_CREATIVE_ADPCM 161 
#define  WAVE_FORMAT_CREATIVE_FASTSPEECH10 160 
#define  WAVE_FORMAT_CREATIVE_FASTSPEECH8 159 
#define  WAVE_FORMAT_DEVELOPMENT 158 
#define  WAVE_FORMAT_DIALOGIC_OKI_ADPCM 157 
#define  WAVE_FORMAT_DIGIADPCM 156 
#define  WAVE_FORMAT_DIGIFIX 155 
#define  WAVE_FORMAT_DIGIREAL 154 
#define  WAVE_FORMAT_DIGISTD 153 
#define  WAVE_FORMAT_DOLBY_AC2 152 
#define  WAVE_FORMAT_DSPGROUP_TRUESPEECH 151 
#define  WAVE_FORMAT_ECHOSC1 150 
#define  WAVE_FORMAT_EXTENSIBLE 149 
#define  WAVE_FORMAT_FM_TOWNS_SND 148 
#define  WAVE_FORMAT_G721_ADPCM 147 
#define  WAVE_FORMAT_G723_ADPCM 146 
#define  WAVE_FORMAT_GSM610 145 
#define  WAVE_FORMAT_IBM_CVSD 144 
#define  WAVE_FORMAT_IMA_ADPCM 143 
#define  WAVE_FORMAT_MEDIASPACE_ADPCM 142 
#define  WAVE_FORMAT_MPEG 141 
#define  WAVE_FORMAT_MPEGLAYER3 140 
#define  WAVE_FORMAT_MULAW 139 
#define  WAVE_FORMAT_NMS_VBXADPCM 138 
#define  WAVE_FORMAT_OKI_ADPCM 137 
#define  WAVE_FORMAT_OLIADPCM 136 
#define  WAVE_FORMAT_OLICELP 135 
#define  WAVE_FORMAT_OLIGSM 134 
#define  WAVE_FORMAT_OLIOPR 133 
#define  WAVE_FORMAT_OLISBC 132 
#define  WAVE_FORMAT_PCM 131 
#define  WAVE_FORMAT_SIERRA_ADPCM 130 
#define  WAVE_FORMAT_SONARC 129 
#define  WAVE_FORMAT_YAMAHA_ADPCM 128 
 int /*<<< orphan*/  sprintf (char*,char*,int) ; 

__attribute__((used)) static const char * get_format_str(WORD format)
{
    static char msg[32];
#define WAVE_FORMAT(f) case f: return #f
    switch (format) {
    WAVE_FORMAT(WAVE_FORMAT_PCM);
    WAVE_FORMAT(WAVE_FORMAT_ADPCM);
    WAVE_FORMAT(WAVE_FORMAT_IBM_CVSD);
    WAVE_FORMAT(WAVE_FORMAT_ALAW);
    WAVE_FORMAT(WAVE_FORMAT_MULAW);
    WAVE_FORMAT(WAVE_FORMAT_OKI_ADPCM);
    WAVE_FORMAT(WAVE_FORMAT_IMA_ADPCM);
    WAVE_FORMAT(WAVE_FORMAT_MEDIASPACE_ADPCM);
    WAVE_FORMAT(WAVE_FORMAT_SIERRA_ADPCM);
    WAVE_FORMAT(WAVE_FORMAT_G723_ADPCM);
    WAVE_FORMAT(WAVE_FORMAT_DIGISTD);
    WAVE_FORMAT(WAVE_FORMAT_DIGIFIX);
    WAVE_FORMAT(WAVE_FORMAT_DIALOGIC_OKI_ADPCM);
    WAVE_FORMAT(WAVE_FORMAT_YAMAHA_ADPCM);
    WAVE_FORMAT(WAVE_FORMAT_SONARC);
    WAVE_FORMAT(WAVE_FORMAT_DSPGROUP_TRUESPEECH);
    WAVE_FORMAT(WAVE_FORMAT_ECHOSC1);
    WAVE_FORMAT(WAVE_FORMAT_AUDIOFILE_AF36);
    WAVE_FORMAT(WAVE_FORMAT_APTX);
    WAVE_FORMAT(WAVE_FORMAT_AUDIOFILE_AF10);
    WAVE_FORMAT(WAVE_FORMAT_DOLBY_AC2);
    WAVE_FORMAT(WAVE_FORMAT_GSM610);
    WAVE_FORMAT(WAVE_FORMAT_ANTEX_ADPCME);
    WAVE_FORMAT(WAVE_FORMAT_CONTROL_RES_VQLPC);
    WAVE_FORMAT(WAVE_FORMAT_DIGIREAL);
    WAVE_FORMAT(WAVE_FORMAT_DIGIADPCM);
    WAVE_FORMAT(WAVE_FORMAT_CONTROL_RES_CR10);
    WAVE_FORMAT(WAVE_FORMAT_NMS_VBXADPCM);
    WAVE_FORMAT(WAVE_FORMAT_G721_ADPCM);
    WAVE_FORMAT(WAVE_FORMAT_MPEG);
    WAVE_FORMAT(WAVE_FORMAT_MPEGLAYER3);
    WAVE_FORMAT(WAVE_FORMAT_CREATIVE_ADPCM);
    WAVE_FORMAT(WAVE_FORMAT_CREATIVE_FASTSPEECH8);
    WAVE_FORMAT(WAVE_FORMAT_CREATIVE_FASTSPEECH10);
    WAVE_FORMAT(WAVE_FORMAT_FM_TOWNS_SND);
    WAVE_FORMAT(WAVE_FORMAT_OLIGSM);
    WAVE_FORMAT(WAVE_FORMAT_OLIADPCM);
    WAVE_FORMAT(WAVE_FORMAT_OLICELP);
    WAVE_FORMAT(WAVE_FORMAT_OLISBC);
    WAVE_FORMAT(WAVE_FORMAT_OLIOPR);
    WAVE_FORMAT(WAVE_FORMAT_DEVELOPMENT);
    WAVE_FORMAT(WAVE_FORMAT_EXTENSIBLE);
    }
#undef WAVE_FORMAT
    sprintf(msg, "Unknown(0x%04x)", format);
    return msg;
}