#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  int DWORD ;

/* Variables and functions */
#define  MIXERCONTROL_CONTROLTYPE_BASS 158 
#define  MIXERCONTROL_CONTROLTYPE_BASS_BOOST 157 
#define  MIXERCONTROL_CONTROLTYPE_BOOLEAN 156 
#define  MIXERCONTROL_CONTROLTYPE_BOOLEANMETER 155 
#define  MIXERCONTROL_CONTROLTYPE_BUTTON 154 
#define  MIXERCONTROL_CONTROLTYPE_CUSTOM 153 
#define  MIXERCONTROL_CONTROLTYPE_DECIBELS 152 
#define  MIXERCONTROL_CONTROLTYPE_EQUALIZER 151 
#define  MIXERCONTROL_CONTROLTYPE_FADER 150 
#define  MIXERCONTROL_CONTROLTYPE_LOUDNESS 149 
#define  MIXERCONTROL_CONTROLTYPE_MICROTIME 148 
#define  MIXERCONTROL_CONTROLTYPE_MILLITIME 147 
#define  MIXERCONTROL_CONTROLTYPE_MIXER 146 
#define  MIXERCONTROL_CONTROLTYPE_MONO 145 
#define  MIXERCONTROL_CONTROLTYPE_MULTIPLESELECT 144 
#define  MIXERCONTROL_CONTROLTYPE_MUTE 143 
#define  MIXERCONTROL_CONTROLTYPE_MUX 142 
#define  MIXERCONTROL_CONTROLTYPE_ONOFF 141 
#define  MIXERCONTROL_CONTROLTYPE_PAN 140 
#define  MIXERCONTROL_CONTROLTYPE_PEAKMETER 139 
#define  MIXERCONTROL_CONTROLTYPE_PERCENT 138 
#define  MIXERCONTROL_CONTROLTYPE_QSOUNDPAN 137 
#define  MIXERCONTROL_CONTROLTYPE_SIGNED 136 
#define  MIXERCONTROL_CONTROLTYPE_SIGNEDMETER 135 
#define  MIXERCONTROL_CONTROLTYPE_SINGLESELECT 134 
#define  MIXERCONTROL_CONTROLTYPE_SLIDER 133 
#define  MIXERCONTROL_CONTROLTYPE_STEREOENH 132 
#define  MIXERCONTROL_CONTROLTYPE_TREBLE 131 
#define  MIXERCONTROL_CONTROLTYPE_UNSIGNED 130 
#define  MIXERCONTROL_CONTROLTYPE_UNSIGNEDMETER 129 
#define  MIXERCONTROL_CONTROLTYPE_VOLUME 128 

__attribute__((used)) static const char * control_type(DWORD dwControlType)
{
#define TYPE_TO_STR(x) case x: return #x
    switch (dwControlType) {
    TYPE_TO_STR(MIXERCONTROL_CONTROLTYPE_CUSTOM);
    TYPE_TO_STR(MIXERCONTROL_CONTROLTYPE_BOOLEANMETER);
    TYPE_TO_STR(MIXERCONTROL_CONTROLTYPE_SIGNEDMETER);
    TYPE_TO_STR(MIXERCONTROL_CONTROLTYPE_PEAKMETER);
    TYPE_TO_STR(MIXERCONTROL_CONTROLTYPE_UNSIGNEDMETER);
    TYPE_TO_STR(MIXERCONTROL_CONTROLTYPE_BOOLEAN);
    TYPE_TO_STR(MIXERCONTROL_CONTROLTYPE_ONOFF);
    TYPE_TO_STR(MIXERCONTROL_CONTROLTYPE_MUTE);
    TYPE_TO_STR(MIXERCONTROL_CONTROLTYPE_MONO);
    TYPE_TO_STR(MIXERCONTROL_CONTROLTYPE_LOUDNESS);
    TYPE_TO_STR(MIXERCONTROL_CONTROLTYPE_STEREOENH);
    TYPE_TO_STR(MIXERCONTROL_CONTROLTYPE_BASS_BOOST);
    TYPE_TO_STR(MIXERCONTROL_CONTROLTYPE_BUTTON);
    TYPE_TO_STR(MIXERCONTROL_CONTROLTYPE_DECIBELS);
    TYPE_TO_STR(MIXERCONTROL_CONTROLTYPE_SIGNED);
    TYPE_TO_STR(MIXERCONTROL_CONTROLTYPE_UNSIGNED);
    TYPE_TO_STR(MIXERCONTROL_CONTROLTYPE_PERCENT);
    TYPE_TO_STR(MIXERCONTROL_CONTROLTYPE_SLIDER);
    TYPE_TO_STR(MIXERCONTROL_CONTROLTYPE_PAN);
    TYPE_TO_STR(MIXERCONTROL_CONTROLTYPE_QSOUNDPAN);
    TYPE_TO_STR(MIXERCONTROL_CONTROLTYPE_FADER);
    TYPE_TO_STR(MIXERCONTROL_CONTROLTYPE_VOLUME);
    TYPE_TO_STR(MIXERCONTROL_CONTROLTYPE_BASS);
    TYPE_TO_STR(MIXERCONTROL_CONTROLTYPE_TREBLE);
    TYPE_TO_STR(MIXERCONTROL_CONTROLTYPE_EQUALIZER);
    TYPE_TO_STR(MIXERCONTROL_CONTROLTYPE_SINGLESELECT);
    TYPE_TO_STR(MIXERCONTROL_CONTROLTYPE_MUX);
    TYPE_TO_STR(MIXERCONTROL_CONTROLTYPE_MULTIPLESELECT);
    TYPE_TO_STR(MIXERCONTROL_CONTROLTYPE_MIXER);
    TYPE_TO_STR(MIXERCONTROL_CONTROLTYPE_MICROTIME);
    TYPE_TO_STR(MIXERCONTROL_CONTROLTYPE_MILLITIME);
    }
#undef TYPE_TO_STR
    return "UNKNOWN";
}