#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  int NTSTATUS ;

/* Variables and functions */
 int EACCES ; 
 int EADDRINUSE ; 
 int EADDRNOTAVAIL ; 
 int EAGAIN ; 
 int ECONNABORTED ; 
 int ECONNREFUSED ; 
 int ECONNRESET ; 
 int EFAULT ; 
 int EHOSTUNREACH ; 
 int EINTR ; 
 int EINVAL ; 
 int EIO ; 
 int EMSGSIZE ; 
 int ENETDOWN ; 
 int ENETUNREACH ; 
 int ENOBUFS ; 
 int ENOMEM ; 
 int ENOTCONN ; 
 int EOPNOTSUPP ; 
 int ESHUTDOWN ; 
 int ETIMEDOUT ; 
 int ETOOSMALL ; 
 scalar_t__ NT_SUCCESS (int) ; 
#define  STATUS_ACCESS_DENIED 179 
#define  STATUS_ACCESS_VIOLATION 178 
#define  STATUS_ADDRESS_ALREADY_EXISTS 177 
#define  STATUS_BAD_NETWORK_PATH 176 
#define  STATUS_BUFFER_OVERFLOW 175 
#define  STATUS_BUFFER_TOO_SMALL 174 
#define  STATUS_CANCELLED 173 
#define  STATUS_CANT_WAIT 172 
#define  STATUS_COMMITMENT_LIMIT 171 
#define  STATUS_CONFLICTING_ADDRESSES 170 
#define  STATUS_CONNECTION_ABORTED 169 
#define  STATUS_CONNECTION_DISCONNECTED 168 
#define  STATUS_CONNECTION_REFUSED 167 
#define  STATUS_CONNECTION_RESET 166 
#define  STATUS_DEVICE_NOT_READY 165 
#define  STATUS_HOST_UNREACHABLE 164 
#define  STATUS_INSUFFICIENT_RESOURCES 163 
#define  STATUS_INVALID_ADDRESS 162 
#define  STATUS_INVALID_ADDRESS_COMPONENT 161 
#define  STATUS_INVALID_BUFFER_SIZE 160 
#define  STATUS_INVALID_CONNECTION 159 
#define  STATUS_INVALID_NETWORK_RESPONSE 158 
#define  STATUS_INVALID_PARAMETER 157 
#define  STATUS_IO_TIMEOUT 156 
#define  STATUS_LINK_FAILED 155 
#define  STATUS_LINK_TIMEOUT 154 
#define  STATUS_LOCAL_DISCONNECT 153 
#define  STATUS_NETWORK_BUSY 152 
#define  STATUS_NETWORK_UNREACHABLE 151 
#define  STATUS_NOT_IMPLEMENTED 150 
#define  STATUS_NOT_SUPPORTED 149 
#define  STATUS_NO_MEMORY 148 
#define  STATUS_NO_SUCH_DEVICE 147 
#define  STATUS_NO_SUCH_FILE 146 
#define  STATUS_OBJECT_NAME_NOT_FOUND 145 
#define  STATUS_OBJECT_PATH_NOT_FOUND 144 
#define  STATUS_PAGEFILE_QUOTA 143 
#define  STATUS_PENDING 142 
#define  STATUS_PIPE_DISCONNECTED 141 
#define  STATUS_PORT_UNREACHABLE 140 
#define  STATUS_PROTOCOL_UNREACHABLE 139 
#define  STATUS_QUOTA_EXCEEDED 138 
#define  STATUS_REMOTE_DISCONNECT 137 
#define  STATUS_REMOTE_NOT_LISTENING 136 
#define  STATUS_REMOTE_RESOURCES 135 
#define  STATUS_REQUEST_ABORTED 134 
#define  STATUS_TIMEOUT 133 
#define  STATUS_TOO_MANY_ADDRESSES 132 
#define  STATUS_TOO_MANY_PAGING_FILES 131 
#define  STATUS_TRANSACTION_ABORTED 130 
#define  STATUS_UNEXPECTED_NETWORK_ERROR 129 
#define  STATUS_WORKING_SET_QUOTA 128 

int Ext2LinuxError (NTSTATUS Status)
{
    switch (Status) {
    case STATUS_ACCESS_DENIED:
        return (-EACCES);

    case STATUS_ACCESS_VIOLATION:
        return (-EFAULT);

    case STATUS_BUFFER_TOO_SMALL:
        return (-ETOOSMALL);

    case STATUS_INVALID_PARAMETER:
        return (-EINVAL);

    case STATUS_NOT_IMPLEMENTED:
    case STATUS_NOT_SUPPORTED:
        return (-EOPNOTSUPP);

    case STATUS_INVALID_ADDRESS:
    case STATUS_INVALID_ADDRESS_COMPONENT:
        return (-EADDRNOTAVAIL);

    case STATUS_NO_SUCH_DEVICE:
    case STATUS_NO_SUCH_FILE:
    case STATUS_OBJECT_NAME_NOT_FOUND:
    case STATUS_OBJECT_PATH_NOT_FOUND:
    case STATUS_NETWORK_BUSY:
    case STATUS_INVALID_NETWORK_RESPONSE:
    case STATUS_UNEXPECTED_NETWORK_ERROR:
        return (-ENETDOWN);

    case STATUS_BAD_NETWORK_PATH:
    case STATUS_NETWORK_UNREACHABLE:
    case STATUS_PROTOCOL_UNREACHABLE:
        return (-ENETUNREACH);

    case STATUS_LOCAL_DISCONNECT:
    case STATUS_TRANSACTION_ABORTED:
    case STATUS_CONNECTION_ABORTED:
        return (-ECONNABORTED);

    case STATUS_REMOTE_DISCONNECT:
    case STATUS_LINK_FAILED:
    case STATUS_CONNECTION_DISCONNECTED:
    case STATUS_CONNECTION_RESET:
    case STATUS_PORT_UNREACHABLE:
        return (-ECONNRESET);

    case STATUS_INSUFFICIENT_RESOURCES:
        return (-ENOMEM);

    case STATUS_PAGEFILE_QUOTA:
    case STATUS_NO_MEMORY:
    case STATUS_CONFLICTING_ADDRESSES:
    case STATUS_QUOTA_EXCEEDED:
    case STATUS_TOO_MANY_PAGING_FILES:
    case STATUS_WORKING_SET_QUOTA:
    case STATUS_COMMITMENT_LIMIT:
    case STATUS_TOO_MANY_ADDRESSES:
    case STATUS_REMOTE_RESOURCES:
        return (-ENOBUFS);

    case STATUS_INVALID_CONNECTION:
        return (-ENOTCONN);

    case STATUS_PIPE_DISCONNECTED:
        return (-ESHUTDOWN);

    case STATUS_TIMEOUT:
    case STATUS_IO_TIMEOUT:
    case STATUS_LINK_TIMEOUT:
        return (-ETIMEDOUT);

    case STATUS_REMOTE_NOT_LISTENING:
    case STATUS_CONNECTION_REFUSED:
        return (-ECONNREFUSED);

    case STATUS_HOST_UNREACHABLE:
        return (-EHOSTUNREACH);

    case STATUS_CANT_WAIT:
    case STATUS_PENDING:
        return (-EAGAIN);

    case STATUS_DEVICE_NOT_READY:
        return (-EIO);

    case STATUS_CANCELLED:
    case STATUS_REQUEST_ABORTED:
        return (-EINTR);

    case STATUS_BUFFER_OVERFLOW:
    case STATUS_INVALID_BUFFER_SIZE:
        return (-EMSGSIZE);

    case STATUS_ADDRESS_ALREADY_EXISTS:
        return (-EADDRINUSE);
    }

    if (NT_SUCCESS (Status))
        return 0;

    return (-EINVAL);
}