#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */

/* Variables and functions */
 int /*<<< orphan*/  test_pack_GOPHER_ABSTRACT_ATTRIBUTE_TYPEA () ; 
 int /*<<< orphan*/  test_pack_GOPHER_ABSTRACT_ATTRIBUTE_TYPEW () ; 
 int /*<<< orphan*/  test_pack_GOPHER_ADMIN_ATTRIBUTE_TYPEA () ; 
 int /*<<< orphan*/  test_pack_GOPHER_ADMIN_ATTRIBUTE_TYPEW () ; 
 int /*<<< orphan*/  test_pack_GOPHER_ASK_ATTRIBUTE_TYPEA () ; 
 int /*<<< orphan*/  test_pack_GOPHER_ASK_ATTRIBUTE_TYPEW () ; 
 int /*<<< orphan*/  test_pack_GOPHER_ATTRIBUTE_ENUMERATORA () ; 
 int /*<<< orphan*/  test_pack_GOPHER_ATTRIBUTE_ENUMERATORW () ; 
 int /*<<< orphan*/  test_pack_GOPHER_ATTRIBUTE_TYPEA () ; 
 int /*<<< orphan*/  test_pack_GOPHER_ATTRIBUTE_TYPEW () ; 
 int /*<<< orphan*/  test_pack_GOPHER_FIND_DATAA () ; 
 int /*<<< orphan*/  test_pack_GOPHER_FIND_DATAW () ; 
 int /*<<< orphan*/  test_pack_GOPHER_GEOGRAPHICAL_LOCATION_ATTRIBUTE_TYPE () ; 
 int /*<<< orphan*/  test_pack_GOPHER_LOCATION_ATTRIBUTE_TYPEA () ; 
 int /*<<< orphan*/  test_pack_GOPHER_LOCATION_ATTRIBUTE_TYPEW () ; 
 int /*<<< orphan*/  test_pack_GOPHER_MOD_DATE_ATTRIBUTE_TYPE () ; 
 int /*<<< orphan*/  test_pack_GOPHER_ORGANIZATION_ATTRIBUTE_TYPEA () ; 
 int /*<<< orphan*/  test_pack_GOPHER_ORGANIZATION_ATTRIBUTE_TYPEW () ; 
 int /*<<< orphan*/  test_pack_GOPHER_PROVIDER_ATTRIBUTE_TYPEA () ; 
 int /*<<< orphan*/  test_pack_GOPHER_PROVIDER_ATTRIBUTE_TYPEW () ; 
 int /*<<< orphan*/  test_pack_GOPHER_SCORE_ATTRIBUTE_TYPE () ; 
 int /*<<< orphan*/  test_pack_GOPHER_SCORE_RANGE_ATTRIBUTE_TYPE () ; 
 int /*<<< orphan*/  test_pack_GOPHER_SITE_ATTRIBUTE_TYPEA () ; 
 int /*<<< orphan*/  test_pack_GOPHER_SITE_ATTRIBUTE_TYPEW () ; 
 int /*<<< orphan*/  test_pack_GOPHER_TIMEZONE_ATTRIBUTE_TYPE () ; 
 int /*<<< orphan*/  test_pack_GOPHER_TTL_ATTRIBUTE_TYPE () ; 
 int /*<<< orphan*/  test_pack_GOPHER_UNKNOWN_ATTRIBUTE_TYPEA () ; 
 int /*<<< orphan*/  test_pack_GOPHER_UNKNOWN_ATTRIBUTE_TYPEW () ; 
 int /*<<< orphan*/  test_pack_GOPHER_VERONICA_ATTRIBUTE_TYPE () ; 
 int /*<<< orphan*/  test_pack_GOPHER_VERSION_ATTRIBUTE_TYPEA () ; 
 int /*<<< orphan*/  test_pack_GOPHER_VERSION_ATTRIBUTE_TYPEW () ; 
 int /*<<< orphan*/  test_pack_GOPHER_VIEW_ATTRIBUTE_TYPEA () ; 
 int /*<<< orphan*/  test_pack_GOPHER_VIEW_ATTRIBUTE_TYPEW () ; 
 int /*<<< orphan*/  test_pack_GROUPID () ; 
 int /*<<< orphan*/  test_pack_HINTERNET () ; 
 int /*<<< orphan*/  test_pack_HTTP_VERSION_INFO () ; 
 int /*<<< orphan*/  test_pack_INTERNET_ASYNC_RESULT () ; 
 int /*<<< orphan*/  test_pack_INTERNET_AUTH_NOTIFY_DATA () ; 
 int /*<<< orphan*/  test_pack_INTERNET_BUFFERSA () ; 
 int /*<<< orphan*/  test_pack_INTERNET_BUFFERSW () ; 
 int /*<<< orphan*/  test_pack_INTERNET_CACHE_ENTRY_INFOA () ; 
 int /*<<< orphan*/  test_pack_INTERNET_CACHE_ENTRY_INFOW () ; 
 int /*<<< orphan*/  test_pack_INTERNET_CERTIFICATE_INFOA () ; 
 int /*<<< orphan*/  test_pack_INTERNET_CERTIFICATE_INFOW () ; 
 int /*<<< orphan*/  test_pack_INTERNET_CONNECTED_INFO () ; 
 int /*<<< orphan*/  test_pack_INTERNET_PORT () ; 
 int /*<<< orphan*/  test_pack_INTERNET_PROXY_INFOA () ; 
 int /*<<< orphan*/  test_pack_INTERNET_PROXY_INFOW () ; 
 int /*<<< orphan*/  test_pack_INTERNET_STATUS_CALLBACK () ; 
 int /*<<< orphan*/  test_pack_INTERNET_VERSION_INFO () ; 
 int /*<<< orphan*/  test_pack_LPGOPHER_ABSTRACT_ATTRIBUTE_TYPEA () ; 
 int /*<<< orphan*/  test_pack_LPGOPHER_ABSTRACT_ATTRIBUTE_TYPEW () ; 
 int /*<<< orphan*/  test_pack_LPGOPHER_ADMIN_ATTRIBUTE_TYPEA () ; 
 int /*<<< orphan*/  test_pack_LPGOPHER_ADMIN_ATTRIBUTE_TYPEW () ; 
 int /*<<< orphan*/  test_pack_LPGOPHER_ASK_ATTRIBUTE_TYPEA () ; 
 int /*<<< orphan*/  test_pack_LPGOPHER_ASK_ATTRIBUTE_TYPEW () ; 
 int /*<<< orphan*/  test_pack_LPGOPHER_ATTRIBUTE_TYPEA () ; 
 int /*<<< orphan*/  test_pack_LPGOPHER_ATTRIBUTE_TYPEW () ; 
 int /*<<< orphan*/  test_pack_LPGOPHER_FIND_DATAA () ; 
 int /*<<< orphan*/  test_pack_LPGOPHER_FIND_DATAW () ; 
 int /*<<< orphan*/  test_pack_LPGOPHER_GEOGRAPHICAL_LOCATION_ATTRIBUTE_TYPE () ; 
 int /*<<< orphan*/  test_pack_LPGOPHER_LOCATION_ATTRIBUTE_TYPEA () ; 
 int /*<<< orphan*/  test_pack_LPGOPHER_LOCATION_ATTRIBUTE_TYPEW () ; 
 int /*<<< orphan*/  test_pack_LPGOPHER_MOD_DATE_ATTRIBUTE_TYPE () ; 
 int /*<<< orphan*/  test_pack_LPGOPHER_ORGANIZATION_ATTRIBUTE_TYPEA () ; 
 int /*<<< orphan*/  test_pack_LPGOPHER_ORGANIZATION_ATTRIBUTE_TYPEW () ; 
 int /*<<< orphan*/  test_pack_LPGOPHER_PROVIDER_ATTRIBUTE_TYPEA () ; 
 int /*<<< orphan*/  test_pack_LPGOPHER_PROVIDER_ATTRIBUTE_TYPEW () ; 
 int /*<<< orphan*/  test_pack_LPGOPHER_SCORE_ATTRIBUTE_TYPE () ; 
 int /*<<< orphan*/  test_pack_LPGOPHER_SCORE_RANGE_ATTRIBUTE_TYPE () ; 
 int /*<<< orphan*/  test_pack_LPGOPHER_SITE_ATTRIBUTE_TYPEA () ; 
 int /*<<< orphan*/  test_pack_LPGOPHER_SITE_ATTRIBUTE_TYPEW () ; 
 int /*<<< orphan*/  test_pack_LPGOPHER_TIMEZONE_ATTRIBUTE_TYPE () ; 
 int /*<<< orphan*/  test_pack_LPGOPHER_TTL_ATTRIBUTE_TYPE () ; 
 int /*<<< orphan*/  test_pack_LPGOPHER_UNKNOWN_ATTRIBUTE_TYPEA () ; 
 int /*<<< orphan*/  test_pack_LPGOPHER_UNKNOWN_ATTRIBUTE_TYPEW () ; 
 int /*<<< orphan*/  test_pack_LPGOPHER_VERONICA_ATTRIBUTE_TYPE () ; 
 int /*<<< orphan*/  test_pack_LPGOPHER_VERSION_ATTRIBUTE_TYPEA () ; 
 int /*<<< orphan*/  test_pack_LPGOPHER_VERSION_ATTRIBUTE_TYPEW () ; 
 int /*<<< orphan*/  test_pack_LPGOPHER_VIEW_ATTRIBUTE_TYPEA () ; 
 int /*<<< orphan*/  test_pack_LPGOPHER_VIEW_ATTRIBUTE_TYPEW () ; 
 int /*<<< orphan*/  test_pack_LPHINTERNET () ; 
 int /*<<< orphan*/  test_pack_LPHTTP_VERSION_INFO () ; 
 int /*<<< orphan*/  test_pack_LPINTERNET_ASYNC_RESULT () ; 
 int /*<<< orphan*/  test_pack_LPINTERNET_BUFFERSA () ; 
 int /*<<< orphan*/  test_pack_LPINTERNET_BUFFERSW () ; 
 int /*<<< orphan*/  test_pack_LPINTERNET_CACHE_ENTRY_INFOA () ; 
 int /*<<< orphan*/  test_pack_LPINTERNET_CACHE_ENTRY_INFOW () ; 
 int /*<<< orphan*/  test_pack_LPINTERNET_CERTIFICATE_INFOA () ; 
 int /*<<< orphan*/  test_pack_LPINTERNET_CERTIFICATE_INFOW () ; 
 int /*<<< orphan*/  test_pack_LPINTERNET_CONNECTED_INFO () ; 
 int /*<<< orphan*/  test_pack_LPINTERNET_PORT () ; 
 int /*<<< orphan*/  test_pack_LPINTERNET_PROXY_INFOA () ; 
 int /*<<< orphan*/  test_pack_LPINTERNET_PROXY_INFOW () ; 
 int /*<<< orphan*/  test_pack_LPINTERNET_STATUS_CALLBACK () ; 
 int /*<<< orphan*/  test_pack_LPINTERNET_VERSION_INFO () ; 
 int /*<<< orphan*/  test_pack_LPURL_COMPONENTSA () ; 
 int /*<<< orphan*/  test_pack_LPURL_COMPONENTSW () ; 
 int /*<<< orphan*/  test_pack_PFN_AUTH_NOTIFY () ; 
 int /*<<< orphan*/  test_pack_PFN_DIAL_HANDLER () ; 
 int /*<<< orphan*/  test_pack_URL_COMPONENTSA () ; 
 int /*<<< orphan*/  test_pack_URL_COMPONENTSW () ; 

__attribute__((used)) static void test_pack(void)
{
    test_pack_GOPHER_ABSTRACT_ATTRIBUTE_TYPEA();
    test_pack_GOPHER_ABSTRACT_ATTRIBUTE_TYPEW();
    test_pack_GOPHER_ADMIN_ATTRIBUTE_TYPEA();
    test_pack_GOPHER_ADMIN_ATTRIBUTE_TYPEW();
    test_pack_GOPHER_ASK_ATTRIBUTE_TYPEA();
    test_pack_GOPHER_ASK_ATTRIBUTE_TYPEW();
    test_pack_GOPHER_ATTRIBUTE_ENUMERATORA();
    test_pack_GOPHER_ATTRIBUTE_ENUMERATORW();
    test_pack_GOPHER_ATTRIBUTE_TYPEA();
    test_pack_GOPHER_ATTRIBUTE_TYPEW();
    test_pack_GOPHER_FIND_DATAA();
    test_pack_GOPHER_FIND_DATAW();
    test_pack_GOPHER_GEOGRAPHICAL_LOCATION_ATTRIBUTE_TYPE();
    test_pack_GOPHER_LOCATION_ATTRIBUTE_TYPEA();
    test_pack_GOPHER_LOCATION_ATTRIBUTE_TYPEW();
    test_pack_GOPHER_MOD_DATE_ATTRIBUTE_TYPE();
    test_pack_GOPHER_ORGANIZATION_ATTRIBUTE_TYPEA();
    test_pack_GOPHER_ORGANIZATION_ATTRIBUTE_TYPEW();
    test_pack_GOPHER_PROVIDER_ATTRIBUTE_TYPEA();
    test_pack_GOPHER_PROVIDER_ATTRIBUTE_TYPEW();
    test_pack_GOPHER_SCORE_ATTRIBUTE_TYPE();
    test_pack_GOPHER_SCORE_RANGE_ATTRIBUTE_TYPE();
    test_pack_GOPHER_SITE_ATTRIBUTE_TYPEA();
    test_pack_GOPHER_SITE_ATTRIBUTE_TYPEW();
    test_pack_GOPHER_TIMEZONE_ATTRIBUTE_TYPE();
    test_pack_GOPHER_TTL_ATTRIBUTE_TYPE();
    test_pack_GOPHER_UNKNOWN_ATTRIBUTE_TYPEA();
    test_pack_GOPHER_UNKNOWN_ATTRIBUTE_TYPEW();
    test_pack_GOPHER_VERONICA_ATTRIBUTE_TYPE();
    test_pack_GOPHER_VERSION_ATTRIBUTE_TYPEA();
    test_pack_GOPHER_VERSION_ATTRIBUTE_TYPEW();
    test_pack_GOPHER_VIEW_ATTRIBUTE_TYPEA();
    test_pack_GOPHER_VIEW_ATTRIBUTE_TYPEW();
    test_pack_GROUPID();
    test_pack_HINTERNET();
    test_pack_HTTP_VERSION_INFO();
    test_pack_INTERNET_ASYNC_RESULT();
    test_pack_INTERNET_AUTH_NOTIFY_DATA();
    test_pack_INTERNET_BUFFERSA();
    test_pack_INTERNET_BUFFERSW();
    test_pack_INTERNET_CACHE_ENTRY_INFOA();
    test_pack_INTERNET_CACHE_ENTRY_INFOW();
    test_pack_INTERNET_CERTIFICATE_INFOA();
    test_pack_INTERNET_CERTIFICATE_INFOW();
    test_pack_INTERNET_CONNECTED_INFO();
    test_pack_INTERNET_PORT();
    test_pack_INTERNET_PROXY_INFOA();
    test_pack_INTERNET_PROXY_INFOW();
    test_pack_INTERNET_STATUS_CALLBACK();
    test_pack_INTERNET_VERSION_INFO();
    test_pack_LPGOPHER_ABSTRACT_ATTRIBUTE_TYPEA();
    test_pack_LPGOPHER_ABSTRACT_ATTRIBUTE_TYPEW();
    test_pack_LPGOPHER_ADMIN_ATTRIBUTE_TYPEA();
    test_pack_LPGOPHER_ADMIN_ATTRIBUTE_TYPEW();
    test_pack_LPGOPHER_ASK_ATTRIBUTE_TYPEA();
    test_pack_LPGOPHER_ASK_ATTRIBUTE_TYPEW();
    test_pack_LPGOPHER_ATTRIBUTE_TYPEA();
    test_pack_LPGOPHER_ATTRIBUTE_TYPEW();
    test_pack_LPGOPHER_FIND_DATAA();
    test_pack_LPGOPHER_FIND_DATAW();
    test_pack_LPGOPHER_GEOGRAPHICAL_LOCATION_ATTRIBUTE_TYPE();
    test_pack_LPGOPHER_LOCATION_ATTRIBUTE_TYPEA();
    test_pack_LPGOPHER_LOCATION_ATTRIBUTE_TYPEW();
    test_pack_LPGOPHER_MOD_DATE_ATTRIBUTE_TYPE();
    test_pack_LPGOPHER_ORGANIZATION_ATTRIBUTE_TYPEA();
    test_pack_LPGOPHER_ORGANIZATION_ATTRIBUTE_TYPEW();
    test_pack_LPGOPHER_PROVIDER_ATTRIBUTE_TYPEA();
    test_pack_LPGOPHER_PROVIDER_ATTRIBUTE_TYPEW();
    test_pack_LPGOPHER_SCORE_ATTRIBUTE_TYPE();
    test_pack_LPGOPHER_SCORE_RANGE_ATTRIBUTE_TYPE();
    test_pack_LPGOPHER_SITE_ATTRIBUTE_TYPEA();
    test_pack_LPGOPHER_SITE_ATTRIBUTE_TYPEW();
    test_pack_LPGOPHER_TIMEZONE_ATTRIBUTE_TYPE();
    test_pack_LPGOPHER_TTL_ATTRIBUTE_TYPE();
    test_pack_LPGOPHER_UNKNOWN_ATTRIBUTE_TYPEA();
    test_pack_LPGOPHER_UNKNOWN_ATTRIBUTE_TYPEW();
    test_pack_LPGOPHER_VERONICA_ATTRIBUTE_TYPE();
    test_pack_LPGOPHER_VERSION_ATTRIBUTE_TYPEA();
    test_pack_LPGOPHER_VERSION_ATTRIBUTE_TYPEW();
    test_pack_LPGOPHER_VIEW_ATTRIBUTE_TYPEA();
    test_pack_LPGOPHER_VIEW_ATTRIBUTE_TYPEW();
    test_pack_LPHINTERNET();
    test_pack_LPHTTP_VERSION_INFO();
    test_pack_LPINTERNET_ASYNC_RESULT();
    test_pack_LPINTERNET_BUFFERSA();
    test_pack_LPINTERNET_BUFFERSW();
    test_pack_LPINTERNET_CACHE_ENTRY_INFOA();
    test_pack_LPINTERNET_CACHE_ENTRY_INFOW();
    test_pack_LPINTERNET_CERTIFICATE_INFOA();
    test_pack_LPINTERNET_CERTIFICATE_INFOW();
    test_pack_LPINTERNET_CONNECTED_INFO();
    test_pack_LPINTERNET_PORT();
    test_pack_LPINTERNET_PROXY_INFOA();
    test_pack_LPINTERNET_PROXY_INFOW();
    test_pack_LPINTERNET_STATUS_CALLBACK();
    test_pack_LPINTERNET_VERSION_INFO();
    test_pack_LPURL_COMPONENTSA();
    test_pack_LPURL_COMPONENTSW();
    test_pack_PFN_AUTH_NOTIFY();
    test_pack_PFN_DIAL_HANDLER();
    test_pack_URL_COMPONENTSA();
    test_pack_URL_COMPONENTSW();
}