#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  enum wined3d_texture_op { ____Placeholder_wined3d_texture_op } wined3d_texture_op ;

/* Variables and functions */
 int /*<<< orphan*/  FIXME (char*,int) ; 
#define  WINED3D_TOP_ADD 153 
#define  WINED3D_TOP_ADD_SIGNED 152 
#define  WINED3D_TOP_ADD_SIGNED_2X 151 
#define  WINED3D_TOP_ADD_SMOOTH 150 
#define  WINED3D_TOP_BLEND_CURRENT_ALPHA 149 
#define  WINED3D_TOP_BLEND_DIFFUSE_ALPHA 148 
#define  WINED3D_TOP_BLEND_FACTOR_ALPHA 147 
#define  WINED3D_TOP_BLEND_TEXTURE_ALPHA 146 
#define  WINED3D_TOP_BLEND_TEXTURE_ALPHA_PM 145 
#define  WINED3D_TOP_BUMPENVMAP 144 
#define  WINED3D_TOP_BUMPENVMAP_LUMINANCE 143 
#define  WINED3D_TOP_DISABLE 142 
#define  WINED3D_TOP_DOTPRODUCT3 141 
#define  WINED3D_TOP_LERP 140 
#define  WINED3D_TOP_MODULATE 139 
#define  WINED3D_TOP_MODULATE_2X 138 
#define  WINED3D_TOP_MODULATE_4X 137 
#define  WINED3D_TOP_MODULATE_ALPHA_ADD_COLOR 136 
#define  WINED3D_TOP_MODULATE_COLOR_ADD_ALPHA 135 
#define  WINED3D_TOP_MODULATE_INVALPHA_ADD_COLOR 134 
#define  WINED3D_TOP_MODULATE_INVCOLOR_ADD_ALPHA 133 
#define  WINED3D_TOP_MULTIPLY_ADD 132 
#define  WINED3D_TOP_PREMODULATE 131 
#define  WINED3D_TOP_SELECT_ARG1 130 
#define  WINED3D_TOP_SELECT_ARG2 129 
#define  WINED3D_TOP_SUBTRACT 128 

const char *debug_d3dtop(enum wined3d_texture_op d3dtop)
{
    switch (d3dtop)
    {
#define D3DTOP_TO_STR(u) case u: return #u
        D3DTOP_TO_STR(WINED3D_TOP_DISABLE);
        D3DTOP_TO_STR(WINED3D_TOP_SELECT_ARG1);
        D3DTOP_TO_STR(WINED3D_TOP_SELECT_ARG2);
        D3DTOP_TO_STR(WINED3D_TOP_MODULATE);
        D3DTOP_TO_STR(WINED3D_TOP_MODULATE_2X);
        D3DTOP_TO_STR(WINED3D_TOP_MODULATE_4X);
        D3DTOP_TO_STR(WINED3D_TOP_ADD);
        D3DTOP_TO_STR(WINED3D_TOP_ADD_SIGNED);
        D3DTOP_TO_STR(WINED3D_TOP_ADD_SIGNED_2X);
        D3DTOP_TO_STR(WINED3D_TOP_SUBTRACT);
        D3DTOP_TO_STR(WINED3D_TOP_ADD_SMOOTH);
        D3DTOP_TO_STR(WINED3D_TOP_BLEND_DIFFUSE_ALPHA);
        D3DTOP_TO_STR(WINED3D_TOP_BLEND_TEXTURE_ALPHA);
        D3DTOP_TO_STR(WINED3D_TOP_BLEND_FACTOR_ALPHA);
        D3DTOP_TO_STR(WINED3D_TOP_BLEND_TEXTURE_ALPHA_PM);
        D3DTOP_TO_STR(WINED3D_TOP_BLEND_CURRENT_ALPHA);
        D3DTOP_TO_STR(WINED3D_TOP_PREMODULATE);
        D3DTOP_TO_STR(WINED3D_TOP_MODULATE_ALPHA_ADD_COLOR);
        D3DTOP_TO_STR(WINED3D_TOP_MODULATE_COLOR_ADD_ALPHA);
        D3DTOP_TO_STR(WINED3D_TOP_MODULATE_INVALPHA_ADD_COLOR);
        D3DTOP_TO_STR(WINED3D_TOP_MODULATE_INVCOLOR_ADD_ALPHA);
        D3DTOP_TO_STR(WINED3D_TOP_BUMPENVMAP);
        D3DTOP_TO_STR(WINED3D_TOP_BUMPENVMAP_LUMINANCE);
        D3DTOP_TO_STR(WINED3D_TOP_DOTPRODUCT3);
        D3DTOP_TO_STR(WINED3D_TOP_MULTIPLY_ADD);
        D3DTOP_TO_STR(WINED3D_TOP_LERP);
#undef D3DTOP_TO_STR
        default:
            FIXME("Unrecognized texture op %#x.\n", d3dtop);
            return "unrecognized";
    }
}