#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */

/* Variables and functions */
 int /*<<< orphan*/  test_pack_ACCESSTIMEOUT () ; 
 int /*<<< orphan*/  test_pack_ANIMATIONINFO () ; 
 int /*<<< orphan*/  test_pack_CBTACTIVATESTRUCT () ; 
 int /*<<< orphan*/  test_pack_CBT_CREATEWNDA () ; 
 int /*<<< orphan*/  test_pack_CBT_CREATEWNDW () ; 
 int /*<<< orphan*/  test_pack_CLIENTCREATESTRUCT () ; 
 int /*<<< orphan*/  test_pack_COMBOBOXINFO () ; 
 int /*<<< orphan*/  test_pack_COMPAREITEMSTRUCT () ; 
 int /*<<< orphan*/  test_pack_COPYDATASTRUCT () ; 
 int /*<<< orphan*/  test_pack_CREATESTRUCTA () ; 
 int /*<<< orphan*/  test_pack_CREATESTRUCTW () ; 
 int /*<<< orphan*/  test_pack_CURSORINFO () ; 
 int /*<<< orphan*/  test_pack_CWPRETSTRUCT () ; 
 int /*<<< orphan*/  test_pack_CWPSTRUCT () ; 
 int /*<<< orphan*/  test_pack_DEBUGHOOKINFO () ; 
 int /*<<< orphan*/  test_pack_DELETEITEMSTRUCT () ; 
 int /*<<< orphan*/  test_pack_DESKTOPENUMPROCA () ; 
 int /*<<< orphan*/  test_pack_DESKTOPENUMPROCW () ; 
 int /*<<< orphan*/  test_pack_DLGITEMTEMPLATE () ; 
 int /*<<< orphan*/  test_pack_DLGPROC () ; 
 int /*<<< orphan*/  test_pack_DLGTEMPLATE () ; 
 int /*<<< orphan*/  test_pack_DRAWITEMSTRUCT () ; 
 int /*<<< orphan*/  test_pack_DRAWSTATEPROC () ; 
 int /*<<< orphan*/  test_pack_DRAWTEXTPARAMS () ; 
 int /*<<< orphan*/  test_pack_EDITWORDBREAKPROCA () ; 
 int /*<<< orphan*/  test_pack_EDITWORDBREAKPROCW () ; 
 int /*<<< orphan*/  test_pack_EVENTMSG () ; 
 int /*<<< orphan*/  test_pack_FILTERKEYS () ; 
 int /*<<< orphan*/  test_pack_FLASHWINFO () ; 
 int /*<<< orphan*/  test_pack_GRAYSTRINGPROC () ; 
 int /*<<< orphan*/  test_pack_GUITHREADINFO () ; 
 int /*<<< orphan*/  test_pack_HARDWAREHOOKSTRUCT () ; 
 int /*<<< orphan*/  test_pack_HARDWAREINPUT () ; 
 int /*<<< orphan*/  test_pack_HDEVNOTIFY () ; 
 int /*<<< orphan*/  test_pack_HDWP () ; 
 int /*<<< orphan*/  test_pack_HELPINFO () ; 
 int /*<<< orphan*/  test_pack_HELPWININFOA () ; 
 int /*<<< orphan*/  test_pack_HELPWININFOW () ; 
 int /*<<< orphan*/  test_pack_HIGHCONTRASTA () ; 
 int /*<<< orphan*/  test_pack_HIGHCONTRASTW () ; 
 int /*<<< orphan*/  test_pack_HOOKPROC () ; 
 int /*<<< orphan*/  test_pack_ICONINFO () ; 
 int /*<<< orphan*/  test_pack_ICONMETRICSA () ; 
 int /*<<< orphan*/  test_pack_ICONMETRICSW () ; 
 int /*<<< orphan*/  test_pack_INPUT () ; 
 int /*<<< orphan*/  test_pack_KBDLLHOOKSTRUCT () ; 
 int /*<<< orphan*/  test_pack_KEYBDINPUT () ; 
 int /*<<< orphan*/  test_pack_LPACCESSTIMEOUT () ; 
 int /*<<< orphan*/  test_pack_LPANIMATIONINFO () ; 
 int /*<<< orphan*/  test_pack_LPCBTACTIVATESTRUCT () ; 
 int /*<<< orphan*/  test_pack_LPCBT_CREATEWNDA () ; 
 int /*<<< orphan*/  test_pack_LPCBT_CREATEWNDW () ; 
 int /*<<< orphan*/  test_pack_LPCDLGTEMPLATEA () ; 
 int /*<<< orphan*/  test_pack_LPCDLGTEMPLATEW () ; 
 int /*<<< orphan*/  test_pack_LPCLIENTCREATESTRUCT () ; 
 int /*<<< orphan*/  test_pack_LPCMENUINFO () ; 
 int /*<<< orphan*/  test_pack_LPCMENUITEMINFOA () ; 
 int /*<<< orphan*/  test_pack_LPCMENUITEMINFOW () ; 
 int /*<<< orphan*/  test_pack_LPCOMBOBOXINFO () ; 
 int /*<<< orphan*/  test_pack_LPCOMPAREITEMSTRUCT () ; 
 int /*<<< orphan*/  test_pack_LPCREATESTRUCTA () ; 
 int /*<<< orphan*/  test_pack_LPCREATESTRUCTW () ; 
 int /*<<< orphan*/  test_pack_LPCSCROLLINFO () ; 
 int /*<<< orphan*/  test_pack_LPCURSORINFO () ; 
 int /*<<< orphan*/  test_pack_LPCWPRETSTRUCT () ; 
 int /*<<< orphan*/  test_pack_LPCWPSTRUCT () ; 
 int /*<<< orphan*/  test_pack_LPDEBUGHOOKINFO () ; 
 int /*<<< orphan*/  test_pack_LPDELETEITEMSTRUCT () ; 
 int /*<<< orphan*/  test_pack_LPDLGITEMTEMPLATEA () ; 
 int /*<<< orphan*/  test_pack_LPDLGITEMTEMPLATEW () ; 
 int /*<<< orphan*/  test_pack_LPDLGTEMPLATEA () ; 
 int /*<<< orphan*/  test_pack_LPDLGTEMPLATEW () ; 
 int /*<<< orphan*/  test_pack_LPDRAWITEMSTRUCT () ; 
 int /*<<< orphan*/  test_pack_LPDRAWTEXTPARAMS () ; 
 int /*<<< orphan*/  test_pack_LPEVENTMSG () ; 
 int /*<<< orphan*/  test_pack_LPFILTERKEYS () ; 
 int /*<<< orphan*/  test_pack_LPGUITHREADINFO () ; 
 int /*<<< orphan*/  test_pack_LPHARDWAREHOOKSTRUCT () ; 
 int /*<<< orphan*/  test_pack_LPHARDWAREINPUT () ; 
 int /*<<< orphan*/  test_pack_LPHELPINFO () ; 
 int /*<<< orphan*/  test_pack_LPHELPWININFOA () ; 
 int /*<<< orphan*/  test_pack_LPHELPWININFOW () ; 
 int /*<<< orphan*/  test_pack_LPHIGHCONTRASTA () ; 
 int /*<<< orphan*/  test_pack_LPHIGHCONTRASTW () ; 
 int /*<<< orphan*/  test_pack_LPICONMETRICSA () ; 
 int /*<<< orphan*/  test_pack_LPICONMETRICSW () ; 
 int /*<<< orphan*/  test_pack_LPINPUT () ; 
 int /*<<< orphan*/  test_pack_LPKBDLLHOOKSTRUCT () ; 
 int /*<<< orphan*/  test_pack_LPKEYBDINPUT () ; 
 int /*<<< orphan*/  test_pack_LPMDICREATESTRUCTA () ; 
 int /*<<< orphan*/  test_pack_LPMDICREATESTRUCTW () ; 
 int /*<<< orphan*/  test_pack_LPMDINEXTMENU () ; 
 int /*<<< orphan*/  test_pack_LPMEASUREITEMSTRUCT () ; 
 int /*<<< orphan*/  test_pack_LPMENUINFO () ; 
 int /*<<< orphan*/  test_pack_LPMENUITEMINFOA () ; 
 int /*<<< orphan*/  test_pack_LPMENUITEMINFOW () ; 
 int /*<<< orphan*/  test_pack_LPMINIMIZEDMETRICS () ; 
 int /*<<< orphan*/  test_pack_LPMINMAXINFO () ; 
 int /*<<< orphan*/  test_pack_LPMONITORINFO () ; 
 int /*<<< orphan*/  test_pack_LPMONITORINFOEXA () ; 
 int /*<<< orphan*/  test_pack_LPMONITORINFOEXW () ; 
 int /*<<< orphan*/  test_pack_LPMOUSEHOOKSTRUCT () ; 
 int /*<<< orphan*/  test_pack_LPMOUSEINPUT () ; 
 int /*<<< orphan*/  test_pack_LPMOUSEKEYS () ; 
 int /*<<< orphan*/  test_pack_LPMSG () ; 
 int /*<<< orphan*/  test_pack_LPMSGBOXPARAMSA () ; 
 int /*<<< orphan*/  test_pack_LPMSGBOXPARAMSW () ; 
 int /*<<< orphan*/  test_pack_LPMSLLHOOKSTRUCT () ; 
 int /*<<< orphan*/  test_pack_LPMULTIKEYHELPA () ; 
 int /*<<< orphan*/  test_pack_LPMULTIKEYHELPW () ; 
 int /*<<< orphan*/  test_pack_LPNCCALCSIZE_PARAMS () ; 
 int /*<<< orphan*/  test_pack_LPNMHDR () ; 
 int /*<<< orphan*/  test_pack_LPNONCLIENTMETRICSA () ; 
 int /*<<< orphan*/  test_pack_LPNONCLIENTMETRICSW () ; 
 int /*<<< orphan*/  test_pack_LPPAINTSTRUCT () ; 
 int /*<<< orphan*/  test_pack_LPSCROLLINFO () ; 
 int /*<<< orphan*/  test_pack_LPSERIALKEYSA () ; 
 int /*<<< orphan*/  test_pack_LPSERIALKEYSW () ; 
 int /*<<< orphan*/  test_pack_LPSOUNDSENTRYA () ; 
 int /*<<< orphan*/  test_pack_LPSOUNDSENTRYW () ; 
 int /*<<< orphan*/  test_pack_LPSTICKYKEYS () ; 
 int /*<<< orphan*/  test_pack_LPSTYLESTRUCT () ; 
 int /*<<< orphan*/  test_pack_LPTITLEBARINFO () ; 
 int /*<<< orphan*/  test_pack_LPTOGGLEKEYS () ; 
 int /*<<< orphan*/  test_pack_LPTPMPARAMS () ; 
 int /*<<< orphan*/  test_pack_LPTRACKMOUSEEVENT () ; 
 int /*<<< orphan*/  test_pack_LPWINDOWINFO () ; 
 int /*<<< orphan*/  test_pack_LPWINDOWPLACEMENT () ; 
 int /*<<< orphan*/  test_pack_LPWINDOWPOS () ; 
 int /*<<< orphan*/  test_pack_LPWNDCLASSA () ; 
 int /*<<< orphan*/  test_pack_LPWNDCLASSEXA () ; 
 int /*<<< orphan*/  test_pack_LPWNDCLASSEXW () ; 
 int /*<<< orphan*/  test_pack_LPWNDCLASSW () ; 
 int /*<<< orphan*/  test_pack_MDICREATESTRUCTA () ; 
 int /*<<< orphan*/  test_pack_MDICREATESTRUCTW () ; 
 int /*<<< orphan*/  test_pack_MDINEXTMENU () ; 
 int /*<<< orphan*/  test_pack_MEASUREITEMSTRUCT () ; 
 int /*<<< orphan*/  test_pack_MENUINFO () ; 
 int /*<<< orphan*/  test_pack_MENUITEMINFOA () ; 
 int /*<<< orphan*/  test_pack_MENUITEMINFOW () ; 
 int /*<<< orphan*/  test_pack_MENUITEMTEMPLATE () ; 
 int /*<<< orphan*/  test_pack_MENUITEMTEMPLATEHEADER () ; 
 int /*<<< orphan*/  test_pack_MINIMIZEDMETRICS () ; 
 int /*<<< orphan*/  test_pack_MINMAXINFO () ; 
 int /*<<< orphan*/  test_pack_MONITORENUMPROC () ; 
 int /*<<< orphan*/  test_pack_MONITORINFO () ; 
 int /*<<< orphan*/  test_pack_MONITORINFOEXA () ; 
 int /*<<< orphan*/  test_pack_MONITORINFOEXW () ; 
 int /*<<< orphan*/  test_pack_MOUSEHOOKSTRUCT () ; 
 int /*<<< orphan*/  test_pack_MOUSEINPUT () ; 
 int /*<<< orphan*/  test_pack_MOUSEKEYS () ; 
 int /*<<< orphan*/  test_pack_MSG () ; 
 int /*<<< orphan*/  test_pack_MSGBOXCALLBACK () ; 
 int /*<<< orphan*/  test_pack_MSGBOXPARAMSA () ; 
 int /*<<< orphan*/  test_pack_MSGBOXPARAMSW () ; 
 int /*<<< orphan*/  test_pack_MSLLHOOKSTRUCT () ; 
 int /*<<< orphan*/  test_pack_MULTIKEYHELPA () ; 
 int /*<<< orphan*/  test_pack_MULTIKEYHELPW () ; 
 int /*<<< orphan*/  test_pack_NAMEENUMPROCA () ; 
 int /*<<< orphan*/  test_pack_NAMEENUMPROCW () ; 
 int /*<<< orphan*/  test_pack_NCCALCSIZE_PARAMS () ; 
 int /*<<< orphan*/  test_pack_NMHDR () ; 
 int /*<<< orphan*/  test_pack_NONCLIENTMETRICSA () ; 
 int /*<<< orphan*/  test_pack_NONCLIENTMETRICSW () ; 
 int /*<<< orphan*/  test_pack_PAINTSTRUCT () ; 
 int /*<<< orphan*/  test_pack_PCOMBOBOXINFO () ; 
 int /*<<< orphan*/  test_pack_PCOMPAREITEMSTRUCT () ; 
 int /*<<< orphan*/  test_pack_PCOPYDATASTRUCT () ; 
 int /*<<< orphan*/  test_pack_PCURSORINFO () ; 
 int /*<<< orphan*/  test_pack_PCWPRETSTRUCT () ; 
 int /*<<< orphan*/  test_pack_PCWPSTRUCT () ; 
 int /*<<< orphan*/  test_pack_PDEBUGHOOKINFO () ; 
 int /*<<< orphan*/  test_pack_PDELETEITEMSTRUCT () ; 
 int /*<<< orphan*/  test_pack_PDLGITEMTEMPLATEA () ; 
 int /*<<< orphan*/  test_pack_PDLGITEMTEMPLATEW () ; 
 int /*<<< orphan*/  test_pack_PDRAWITEMSTRUCT () ; 
 int /*<<< orphan*/  test_pack_PEVENTMSG () ; 
 int /*<<< orphan*/  test_pack_PFLASHWINFO () ; 
 int /*<<< orphan*/  test_pack_PGUITHREADINFO () ; 
 int /*<<< orphan*/  test_pack_PHARDWAREHOOKSTRUCT () ; 
 int /*<<< orphan*/  test_pack_PHARDWAREINPUT () ; 
 int /*<<< orphan*/  test_pack_PHDEVNOTIFY () ; 
 int /*<<< orphan*/  test_pack_PHELPWININFOA () ; 
 int /*<<< orphan*/  test_pack_PHELPWININFOW () ; 
 int /*<<< orphan*/  test_pack_PICONINFO () ; 
 int /*<<< orphan*/  test_pack_PICONMETRICSA () ; 
 int /*<<< orphan*/  test_pack_PICONMETRICSW () ; 
 int /*<<< orphan*/  test_pack_PINPUT () ; 
 int /*<<< orphan*/  test_pack_PKBDLLHOOKSTRUCT () ; 
 int /*<<< orphan*/  test_pack_PKEYBDINPUT () ; 
 int /*<<< orphan*/  test_pack_PMDINEXTMENU () ; 
 int /*<<< orphan*/  test_pack_PMEASUREITEMSTRUCT () ; 
 int /*<<< orphan*/  test_pack_PMENUITEMTEMPLATE () ; 
 int /*<<< orphan*/  test_pack_PMENUITEMTEMPLATEHEADER () ; 
 int /*<<< orphan*/  test_pack_PMINIMIZEDMETRICS () ; 
 int /*<<< orphan*/  test_pack_PMINMAXINFO () ; 
 int /*<<< orphan*/  test_pack_PMOUSEHOOKSTRUCT () ; 
 int /*<<< orphan*/  test_pack_PMOUSEINPUT () ; 
 int /*<<< orphan*/  test_pack_PMSG () ; 
 int /*<<< orphan*/  test_pack_PMSGBOXPARAMSA () ; 
 int /*<<< orphan*/  test_pack_PMSGBOXPARAMSW () ; 
 int /*<<< orphan*/  test_pack_PMSLLHOOKSTRUCT () ; 
 int /*<<< orphan*/  test_pack_PMULTIKEYHELPA () ; 
 int /*<<< orphan*/  test_pack_PMULTIKEYHELPW () ; 
 int /*<<< orphan*/  test_pack_PNONCLIENTMETRICSA () ; 
 int /*<<< orphan*/  test_pack_PNONCLIENTMETRICSW () ; 
 int /*<<< orphan*/  test_pack_PPAINTSTRUCT () ; 
 int /*<<< orphan*/  test_pack_PROPENUMPROCA () ; 
 int /*<<< orphan*/  test_pack_PROPENUMPROCEXA () ; 
 int /*<<< orphan*/  test_pack_PROPENUMPROCEXW () ; 
 int /*<<< orphan*/  test_pack_PROPENUMPROCW () ; 
 int /*<<< orphan*/  test_pack_PTITLEBARINFO () ; 
 int /*<<< orphan*/  test_pack_PUSEROBJECTFLAGS () ; 
 int /*<<< orphan*/  test_pack_PWINDOWINFO () ; 
 int /*<<< orphan*/  test_pack_PWINDOWPLACEMENT () ; 
 int /*<<< orphan*/  test_pack_PWINDOWPOS () ; 
 int /*<<< orphan*/  test_pack_PWNDCLASSA () ; 
 int /*<<< orphan*/  test_pack_PWNDCLASSEXA () ; 
 int /*<<< orphan*/  test_pack_PWNDCLASSEXW () ; 
 int /*<<< orphan*/  test_pack_PWNDCLASSW () ; 
 int /*<<< orphan*/  test_pack_SCROLLINFO () ; 
 int /*<<< orphan*/  test_pack_SENDASYNCPROC () ; 
 int /*<<< orphan*/  test_pack_SERIALKEYSA () ; 
 int /*<<< orphan*/  test_pack_SERIALKEYSW () ; 
 int /*<<< orphan*/  test_pack_SOUNDSENTRYA () ; 
 int /*<<< orphan*/  test_pack_SOUNDSENTRYW () ; 
 int /*<<< orphan*/  test_pack_STICKYKEYS () ; 
 int /*<<< orphan*/  test_pack_STYLESTRUCT () ; 
 int /*<<< orphan*/  test_pack_TIMERPROC () ; 
 int /*<<< orphan*/  test_pack_TITLEBARINFO () ; 
 int /*<<< orphan*/  test_pack_TOGGLEKEYS () ; 
 int /*<<< orphan*/  test_pack_TPMPARAMS () ; 
 int /*<<< orphan*/  test_pack_TRACKMOUSEEVENT () ; 
 int /*<<< orphan*/  test_pack_USEROBJECTFLAGS () ; 
 int /*<<< orphan*/  test_pack_WINDOWINFO () ; 
 int /*<<< orphan*/  test_pack_WINDOWPLACEMENT () ; 
 int /*<<< orphan*/  test_pack_WINDOWPOS () ; 
 int /*<<< orphan*/  test_pack_WINEVENTPROC () ; 
 int /*<<< orphan*/  test_pack_WINSTAENUMPROCA () ; 
 int /*<<< orphan*/  test_pack_WINSTAENUMPROCW () ; 
 int /*<<< orphan*/  test_pack_WNDCLASSA () ; 
 int /*<<< orphan*/  test_pack_WNDCLASSEXA () ; 
 int /*<<< orphan*/  test_pack_WNDCLASSEXW () ; 
 int /*<<< orphan*/  test_pack_WNDCLASSW () ; 
 int /*<<< orphan*/  test_pack_WNDENUMPROC () ; 
 int /*<<< orphan*/  test_pack_WNDPROC () ; 

__attribute__((used)) static void test_pack(void)
{
    test_pack_ACCESSTIMEOUT();
    test_pack_ANIMATIONINFO();
    test_pack_CBTACTIVATESTRUCT();
    test_pack_CBT_CREATEWNDA();
    test_pack_CBT_CREATEWNDW();
    test_pack_CLIENTCREATESTRUCT();
    test_pack_COMBOBOXINFO();
    test_pack_COMPAREITEMSTRUCT();
    test_pack_COPYDATASTRUCT();
    test_pack_CREATESTRUCTA();
    test_pack_CREATESTRUCTW();
    test_pack_CURSORINFO();
    test_pack_CWPRETSTRUCT();
    test_pack_CWPSTRUCT();
    test_pack_DEBUGHOOKINFO();
    test_pack_DELETEITEMSTRUCT();
    test_pack_DESKTOPENUMPROCA();
    test_pack_DESKTOPENUMPROCW();
    test_pack_DLGITEMTEMPLATE();
    test_pack_DLGPROC();
    test_pack_DLGTEMPLATE();
    test_pack_DRAWITEMSTRUCT();
    test_pack_DRAWSTATEPROC();
    test_pack_DRAWTEXTPARAMS();
    test_pack_EDITWORDBREAKPROCA();
    test_pack_EDITWORDBREAKPROCW();
    test_pack_EVENTMSG();
    test_pack_FILTERKEYS();
    test_pack_FLASHWINFO();
    test_pack_GRAYSTRINGPROC();
    test_pack_GUITHREADINFO();
    test_pack_HARDWAREHOOKSTRUCT();
    test_pack_HARDWAREINPUT();
    test_pack_HDEVNOTIFY();
    test_pack_HDWP();
    test_pack_HELPINFO();
    test_pack_HELPWININFOA();
    test_pack_HELPWININFOW();
    test_pack_HIGHCONTRASTA();
    test_pack_HIGHCONTRASTW();
    test_pack_HOOKPROC();
    test_pack_ICONINFO();
    test_pack_ICONMETRICSA();
    test_pack_ICONMETRICSW();
    test_pack_INPUT();
    test_pack_KBDLLHOOKSTRUCT();
    test_pack_KEYBDINPUT();
    test_pack_LPACCESSTIMEOUT();
    test_pack_LPANIMATIONINFO();
    test_pack_LPCBTACTIVATESTRUCT();
    test_pack_LPCBT_CREATEWNDA();
    test_pack_LPCBT_CREATEWNDW();
    test_pack_LPCDLGTEMPLATEA();
    test_pack_LPCDLGTEMPLATEW();
    test_pack_LPCLIENTCREATESTRUCT();
    test_pack_LPCMENUINFO();
    test_pack_LPCMENUITEMINFOA();
    test_pack_LPCMENUITEMINFOW();
    test_pack_LPCOMBOBOXINFO();
    test_pack_LPCOMPAREITEMSTRUCT();
    test_pack_LPCREATESTRUCTA();
    test_pack_LPCREATESTRUCTW();
    test_pack_LPCSCROLLINFO();
    test_pack_LPCURSORINFO();
    test_pack_LPCWPRETSTRUCT();
    test_pack_LPCWPSTRUCT();
    test_pack_LPDEBUGHOOKINFO();
    test_pack_LPDELETEITEMSTRUCT();
    test_pack_LPDLGITEMTEMPLATEA();
    test_pack_LPDLGITEMTEMPLATEW();
    test_pack_LPDLGTEMPLATEA();
    test_pack_LPDLGTEMPLATEW();
    test_pack_LPDRAWITEMSTRUCT();
    test_pack_LPDRAWTEXTPARAMS();
    test_pack_LPEVENTMSG();
    test_pack_LPFILTERKEYS();
    test_pack_LPGUITHREADINFO();
    test_pack_LPHARDWAREHOOKSTRUCT();
    test_pack_LPHARDWAREINPUT();
    test_pack_LPHELPINFO();
    test_pack_LPHELPWININFOA();
    test_pack_LPHELPWININFOW();
    test_pack_LPHIGHCONTRASTA();
    test_pack_LPHIGHCONTRASTW();
    test_pack_LPICONMETRICSA();
    test_pack_LPICONMETRICSW();
    test_pack_LPINPUT();
    test_pack_LPKBDLLHOOKSTRUCT();
    test_pack_LPKEYBDINPUT();
    test_pack_LPMDICREATESTRUCTA();
    test_pack_LPMDICREATESTRUCTW();
    test_pack_LPMDINEXTMENU();
    test_pack_LPMEASUREITEMSTRUCT();
    test_pack_LPMENUINFO();
    test_pack_LPMENUITEMINFOA();
    test_pack_LPMENUITEMINFOW();
    test_pack_LPMINIMIZEDMETRICS();
    test_pack_LPMINMAXINFO();
    test_pack_LPMONITORINFO();
    test_pack_LPMONITORINFOEXA();
    test_pack_LPMONITORINFOEXW();
    test_pack_LPMOUSEHOOKSTRUCT();
    test_pack_LPMOUSEINPUT();
    test_pack_LPMOUSEKEYS();
    test_pack_LPMSG();
    test_pack_LPMSGBOXPARAMSA();
    test_pack_LPMSGBOXPARAMSW();
    test_pack_LPMSLLHOOKSTRUCT();
    test_pack_LPMULTIKEYHELPA();
    test_pack_LPMULTIKEYHELPW();
    test_pack_LPNCCALCSIZE_PARAMS();
    test_pack_LPNMHDR();
    test_pack_LPNONCLIENTMETRICSA();
    test_pack_LPNONCLIENTMETRICSW();
    test_pack_LPPAINTSTRUCT();
    test_pack_LPSCROLLINFO();
    test_pack_LPSERIALKEYSA();
    test_pack_LPSERIALKEYSW();
    test_pack_LPSOUNDSENTRYA();
    test_pack_LPSOUNDSENTRYW();
    test_pack_LPSTICKYKEYS();
    test_pack_LPSTYLESTRUCT();
    test_pack_LPTITLEBARINFO();
    test_pack_LPTOGGLEKEYS();
    test_pack_LPTPMPARAMS();
    test_pack_LPTRACKMOUSEEVENT();
    test_pack_LPWINDOWINFO();
    test_pack_LPWINDOWPLACEMENT();
    test_pack_LPWINDOWPOS();
    test_pack_LPWNDCLASSA();
    test_pack_LPWNDCLASSEXA();
    test_pack_LPWNDCLASSEXW();
    test_pack_LPWNDCLASSW();
    test_pack_MDICREATESTRUCTA();
    test_pack_MDICREATESTRUCTW();
    test_pack_MDINEXTMENU();
    test_pack_MEASUREITEMSTRUCT();
    test_pack_MENUINFO();
    test_pack_MENUITEMINFOA();
    test_pack_MENUITEMINFOW();
    test_pack_MENUITEMTEMPLATE();
    test_pack_MENUITEMTEMPLATEHEADER();
    test_pack_MINIMIZEDMETRICS();
    test_pack_MINMAXINFO();
    test_pack_MONITORENUMPROC();
    test_pack_MONITORINFO();
    test_pack_MONITORINFOEXA();
    test_pack_MONITORINFOEXW();
    test_pack_MOUSEHOOKSTRUCT();
    test_pack_MOUSEINPUT();
    test_pack_MOUSEKEYS();
    test_pack_MSG();
    test_pack_MSGBOXCALLBACK();
    test_pack_MSGBOXPARAMSA();
    test_pack_MSGBOXPARAMSW();
    test_pack_MSLLHOOKSTRUCT();
    test_pack_MULTIKEYHELPA();
    test_pack_MULTIKEYHELPW();
    test_pack_NAMEENUMPROCA();
    test_pack_NAMEENUMPROCW();
    test_pack_NCCALCSIZE_PARAMS();
    test_pack_NMHDR();
    test_pack_NONCLIENTMETRICSA();
    test_pack_NONCLIENTMETRICSW();
    test_pack_PAINTSTRUCT();
    test_pack_PCOMBOBOXINFO();
    test_pack_PCOMPAREITEMSTRUCT();
    test_pack_PCOPYDATASTRUCT();
    test_pack_PCURSORINFO();
    test_pack_PCWPRETSTRUCT();
    test_pack_PCWPSTRUCT();
    test_pack_PDEBUGHOOKINFO();
    test_pack_PDELETEITEMSTRUCT();
    test_pack_PDLGITEMTEMPLATEA();
    test_pack_PDLGITEMTEMPLATEW();
    test_pack_PDRAWITEMSTRUCT();
    test_pack_PEVENTMSG();
    test_pack_PFLASHWINFO();
    test_pack_PGUITHREADINFO();
    test_pack_PHARDWAREHOOKSTRUCT();
    test_pack_PHARDWAREINPUT();
    test_pack_PHDEVNOTIFY();
    test_pack_PHELPWININFOA();
    test_pack_PHELPWININFOW();
    test_pack_PICONINFO();
    test_pack_PICONMETRICSA();
    test_pack_PICONMETRICSW();
    test_pack_PINPUT();
    test_pack_PKBDLLHOOKSTRUCT();
    test_pack_PKEYBDINPUT();
    test_pack_PMDINEXTMENU();
    test_pack_PMEASUREITEMSTRUCT();
    test_pack_PMENUITEMTEMPLATE();
    test_pack_PMENUITEMTEMPLATEHEADER();
    test_pack_PMINIMIZEDMETRICS();
    test_pack_PMINMAXINFO();
    test_pack_PMOUSEHOOKSTRUCT();
    test_pack_PMOUSEINPUT();
    test_pack_PMSG();
    test_pack_PMSGBOXPARAMSA();
    test_pack_PMSGBOXPARAMSW();
    test_pack_PMSLLHOOKSTRUCT();
    test_pack_PMULTIKEYHELPA();
    test_pack_PMULTIKEYHELPW();
    test_pack_PNONCLIENTMETRICSA();
    test_pack_PNONCLIENTMETRICSW();
    test_pack_PPAINTSTRUCT();
    test_pack_PROPENUMPROCA();
    test_pack_PROPENUMPROCEXA();
    test_pack_PROPENUMPROCEXW();
    test_pack_PROPENUMPROCW();
    test_pack_PTITLEBARINFO();
    test_pack_PUSEROBJECTFLAGS();
    test_pack_PWINDOWINFO();
    test_pack_PWINDOWPLACEMENT();
    test_pack_PWINDOWPOS();
    test_pack_PWNDCLASSA();
    test_pack_PWNDCLASSEXA();
    test_pack_PWNDCLASSEXW();
    test_pack_PWNDCLASSW();
    test_pack_SCROLLINFO();
    test_pack_SENDASYNCPROC();
    test_pack_SERIALKEYSA();
    test_pack_SERIALKEYSW();
    test_pack_SOUNDSENTRYA();
    test_pack_SOUNDSENTRYW();
    test_pack_STICKYKEYS();
    test_pack_STYLESTRUCT();
    test_pack_TIMERPROC();
    test_pack_TITLEBARINFO();
    test_pack_TOGGLEKEYS();
    test_pack_TPMPARAMS();
    test_pack_TRACKMOUSEEVENT();
    test_pack_USEROBJECTFLAGS();
    test_pack_WINDOWINFO();
    test_pack_WINDOWPLACEMENT();
    test_pack_WINDOWPOS();
    test_pack_WINEVENTPROC();
    test_pack_WINSTAENUMPROCA();
    test_pack_WINSTAENUMPROCW();
    test_pack_WNDCLASSA();
    test_pack_WNDCLASSEXA();
    test_pack_WNDCLASSEXW();
    test_pack_WNDCLASSW();
    test_pack_WNDENUMPROC();
    test_pack_WNDPROC();
}