#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  int MMRESULT ;

/* Variables and functions */
#define  JOYERR_NOCANDO 166 
#define  JOYERR_PARMS 165 
#define  JOYERR_UNPLUGGED 164 
#define  MIDIERR_INVALIDSETUP 163 
#define  MIDIERR_NODEVICE 162 
#define  MIDIERR_NOTREADY 161 
#define  MIDIERR_STILLPLAYING 160 
#define  MIDIERR_UNPREPARED 159 
#define  MIXERR_INVALCONTROL 158 
#define  MIXERR_INVALLINE 157 
#define  MIXERR_INVALVALUE 156 
#define  MMIOERR_CANNOTCLOSE 155 
#define  MMIOERR_CANNOTEXPAND 154 
#define  MMIOERR_CANNOTOPEN 153 
#define  MMIOERR_CANNOTREAD 152 
#define  MMIOERR_CANNOTSEEK 151 
#define  MMIOERR_CANNOTWRITE 150 
#define  MMIOERR_CHUNKNOTFOUND 149 
#define  MMIOERR_FILENOTFOUND 148 
#define  MMIOERR_OUTOFMEMORY 147 
#define  MMIOERR_UNBUFFERED 146 
#define  MMSYSERR_ALLOCATED 145 
#define  MMSYSERR_BADDEVICEID 144 
#define  MMSYSERR_BADERRNUM 143 
#define  MMSYSERR_ERROR 142 
#define  MMSYSERR_INVALFLAG 141 
#define  MMSYSERR_INVALHANDLE 140 
#define  MMSYSERR_INVALPARAM 139 
#define  MMSYSERR_NODRIVER 138 
#define  MMSYSERR_NOERROR 137 
#define  MMSYSERR_NOMEM 136 
#define  MMSYSERR_NOTENABLED 135 
#define  MMSYSERR_NOTSUPPORTED 134 
#define  TIMERR_NOCANDO 133 
#define  TIMERR_STRUCT 132 
#define  WAVERR_BADFORMAT 131 
#define  WAVERR_STILLPLAYING 130 
#define  WAVERR_SYNC 129 
#define  WAVERR_UNPREPARED 128 
 int /*<<< orphan*/  sprintf (char*,char*,int) ; 

const char* mmsys_error(MMRESULT error)
{
#define ERR_TO_STR(dev) case dev: return #dev
    static char	unknown[32];
    switch (error) {
    ERR_TO_STR(MMSYSERR_NOERROR);
    ERR_TO_STR(MMSYSERR_ERROR);
    ERR_TO_STR(MMSYSERR_BADDEVICEID);
    ERR_TO_STR(MMSYSERR_NOTENABLED);
    ERR_TO_STR(MMSYSERR_ALLOCATED);
    ERR_TO_STR(MMSYSERR_INVALHANDLE);
    ERR_TO_STR(MMSYSERR_NODRIVER);
    ERR_TO_STR(MMSYSERR_NOMEM);
    ERR_TO_STR(MMSYSERR_NOTSUPPORTED);
    ERR_TO_STR(MMSYSERR_BADERRNUM);
    ERR_TO_STR(MMSYSERR_INVALFLAG);
    ERR_TO_STR(MMSYSERR_INVALPARAM);
    ERR_TO_STR(WAVERR_BADFORMAT);
    ERR_TO_STR(WAVERR_STILLPLAYING);
    ERR_TO_STR(WAVERR_UNPREPARED);
    ERR_TO_STR(WAVERR_SYNC);
    ERR_TO_STR(MIDIERR_UNPREPARED);
    ERR_TO_STR(MIDIERR_STILLPLAYING);
    ERR_TO_STR(MIDIERR_NOTREADY);
    ERR_TO_STR(MIDIERR_NODEVICE);
    ERR_TO_STR(MIDIERR_INVALIDSETUP);
    ERR_TO_STR(TIMERR_NOCANDO);
    ERR_TO_STR(TIMERR_STRUCT);
    ERR_TO_STR(JOYERR_PARMS);
    ERR_TO_STR(JOYERR_NOCANDO);
    ERR_TO_STR(JOYERR_UNPLUGGED);
    ERR_TO_STR(MIXERR_INVALLINE);
    ERR_TO_STR(MIXERR_INVALCONTROL);
    ERR_TO_STR(MIXERR_INVALVALUE);
    ERR_TO_STR(MMIOERR_FILENOTFOUND);
    ERR_TO_STR(MMIOERR_OUTOFMEMORY);
    ERR_TO_STR(MMIOERR_CANNOTOPEN);
    ERR_TO_STR(MMIOERR_CANNOTCLOSE);
    ERR_TO_STR(MMIOERR_CANNOTREAD);
    ERR_TO_STR(MMIOERR_CANNOTWRITE);
    ERR_TO_STR(MMIOERR_CANNOTSEEK);
    ERR_TO_STR(MMIOERR_CANNOTEXPAND);
    ERR_TO_STR(MMIOERR_CHUNKNOTFOUND);
    ERR_TO_STR(MMIOERR_UNBUFFERED);
    }
    sprintf(unknown, "Unknown(0x%08x)", error);
    return unknown;
#undef ERR_TO_STR
}