#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */

/* Variables and functions */
 int /*<<< orphan*/  test_pack_ACTCTXA () ; 
 int /*<<< orphan*/  test_pack_ACTCTXW () ; 
 int /*<<< orphan*/  test_pack_ACTCTX_SECTION_KEYED_DATA () ; 
 int /*<<< orphan*/  test_pack_ACTCTX_SECTION_KEYED_DATA_2600 () ; 
 int /*<<< orphan*/  test_pack_ACTCTX_SECTION_KEYED_DATA_ASSEMBLY_METADATA () ; 
 int /*<<< orphan*/  test_pack_ACTIVATION_CONTEXT_BASIC_INFORMATION () ; 
 int /*<<< orphan*/  test_pack_BY_HANDLE_FILE_INFORMATION () ; 
 int /*<<< orphan*/  test_pack_COMMCONFIG () ; 
 int /*<<< orphan*/  test_pack_COMMPROP () ; 
 int /*<<< orphan*/  test_pack_COMMTIMEOUTS () ; 
 int /*<<< orphan*/  test_pack_COMSTAT () ; 
 int /*<<< orphan*/  test_pack_CREATE_PROCESS_DEBUG_INFO () ; 
 int /*<<< orphan*/  test_pack_CREATE_THREAD_DEBUG_INFO () ; 
 int /*<<< orphan*/  test_pack_CRITICAL_SECTION () ; 
 int /*<<< orphan*/  test_pack_CRITICAL_SECTION_DEBUG () ; 
 int /*<<< orphan*/  test_pack_DCB () ; 
 int /*<<< orphan*/  test_pack_DEBUG_EVENT () ; 
 int /*<<< orphan*/  test_pack_ENUMRESLANGPROCA () ; 
 int /*<<< orphan*/  test_pack_ENUMRESLANGPROCW () ; 
 int /*<<< orphan*/  test_pack_ENUMRESNAMEPROCA () ; 
 int /*<<< orphan*/  test_pack_ENUMRESNAMEPROCW () ; 
 int /*<<< orphan*/  test_pack_ENUMRESTYPEPROCA () ; 
 int /*<<< orphan*/  test_pack_ENUMRESTYPEPROCW () ; 
 int /*<<< orphan*/  test_pack_EXCEPTION_DEBUG_INFO () ; 
 int /*<<< orphan*/  test_pack_EXIT_PROCESS_DEBUG_INFO () ; 
 int /*<<< orphan*/  test_pack_EXIT_THREAD_DEBUG_INFO () ; 
 int /*<<< orphan*/  test_pack_HW_PROFILE_INFOA () ; 
 int /*<<< orphan*/  test_pack_HW_PROFILE_INFOW () ; 
 int /*<<< orphan*/  test_pack_LOAD_DLL_DEBUG_INFO () ; 
 int /*<<< orphan*/  test_pack_LPBY_HANDLE_FILE_INFORMATION () ; 
 int /*<<< orphan*/  test_pack_LPCOMMCONFIG () ; 
 int /*<<< orphan*/  test_pack_LPCOMMPROP () ; 
 int /*<<< orphan*/  test_pack_LPCOMMTIMEOUTS () ; 
 int /*<<< orphan*/  test_pack_LPCOMSTAT () ; 
 int /*<<< orphan*/  test_pack_LPCRITICAL_SECTION () ; 
 int /*<<< orphan*/  test_pack_LPCRITICAL_SECTION_DEBUG () ; 
 int /*<<< orphan*/  test_pack_LPDCB () ; 
 int /*<<< orphan*/  test_pack_LPDEBUG_EVENT () ; 
 int /*<<< orphan*/  test_pack_LPEXCEPTION_POINTERS () ; 
 int /*<<< orphan*/  test_pack_LPEXCEPTION_RECORD () ; 
 int /*<<< orphan*/  test_pack_LPFIBER_START_ROUTINE () ; 
 int /*<<< orphan*/  test_pack_LPHW_PROFILE_INFOA () ; 
 int /*<<< orphan*/  test_pack_LPHW_PROFILE_INFOW () ; 
 int /*<<< orphan*/  test_pack_LPLONG () ; 
 int /*<<< orphan*/  test_pack_LPMEMORYSTATUS () ; 
 int /*<<< orphan*/  test_pack_LPMEMORYSTATUSEX () ; 
 int /*<<< orphan*/  test_pack_LPOFSTRUCT () ; 
 int /*<<< orphan*/  test_pack_LPOSVERSIONINFOA () ; 
 int /*<<< orphan*/  test_pack_LPOSVERSIONINFOEXA () ; 
 int /*<<< orphan*/  test_pack_LPOSVERSIONINFOEXW () ; 
 int /*<<< orphan*/  test_pack_LPOSVERSIONINFOW () ; 
 int /*<<< orphan*/  test_pack_LPOVERLAPPED () ; 
 int /*<<< orphan*/  test_pack_LPOVERLAPPED_COMPLETION_ROUTINE () ; 
 int /*<<< orphan*/  test_pack_LPPROCESS_HEAP_ENTRY () ; 
 int /*<<< orphan*/  test_pack_LPPROCESS_INFORMATION () ; 
 int /*<<< orphan*/  test_pack_LPPROGRESS_ROUTINE () ; 
 int /*<<< orphan*/  test_pack_LPSECURITY_ATTRIBUTES () ; 
 int /*<<< orphan*/  test_pack_LPSTARTUPINFOA () ; 
 int /*<<< orphan*/  test_pack_LPSTARTUPINFOW () ; 
 int /*<<< orphan*/  test_pack_LPSYSTEMTIME () ; 
 int /*<<< orphan*/  test_pack_LPSYSTEM_INFO () ; 
 int /*<<< orphan*/  test_pack_LPSYSTEM_POWER_STATUS () ; 
 int /*<<< orphan*/  test_pack_LPTHREAD_START_ROUTINE () ; 
 int /*<<< orphan*/  test_pack_LPTIME_ZONE_INFORMATION () ; 
 int /*<<< orphan*/  test_pack_LPVOID () ; 
 int /*<<< orphan*/  test_pack_LPWIN32_FILE_ATTRIBUTE_DATA () ; 
 int /*<<< orphan*/  test_pack_LPWIN32_FIND_DATAA () ; 
 int /*<<< orphan*/  test_pack_LPWIN32_FIND_DATAW () ; 
 int /*<<< orphan*/  test_pack_LPWIN32_STREAM_ID () ; 
 int /*<<< orphan*/  test_pack_MEMORYSTATUS () ; 
 int /*<<< orphan*/  test_pack_MEMORYSTATUSEX () ; 
 int /*<<< orphan*/  test_pack_OFSTRUCT () ; 
 int /*<<< orphan*/  test_pack_OSVERSIONINFOA () ; 
 int /*<<< orphan*/  test_pack_OSVERSIONINFOEXA () ; 
 int /*<<< orphan*/  test_pack_OSVERSIONINFOEXW () ; 
 int /*<<< orphan*/  test_pack_OSVERSIONINFOW () ; 
 int /*<<< orphan*/  test_pack_OUTPUT_DEBUG_STRING_INFO () ; 
 int /*<<< orphan*/  test_pack_PACTCTXA () ; 
 int /*<<< orphan*/  test_pack_PACTCTXW () ; 
 int /*<<< orphan*/  test_pack_PACTCTX_SECTION_KEYED_DATA () ; 
 int /*<<< orphan*/  test_pack_PACTCTX_SECTION_KEYED_DATA_2600 () ; 
 int /*<<< orphan*/  test_pack_PACTCTX_SECTION_KEYED_DATA_ASSEMBLY_METADATA () ; 
 int /*<<< orphan*/  test_pack_PACTIVATION_CONTEXT_BASIC_INFORMATION () ; 
 int /*<<< orphan*/  test_pack_PAPCFUNC () ; 
 int /*<<< orphan*/  test_pack_PBY_HANDLE_FILE_INFORMATION () ; 
 int /*<<< orphan*/  test_pack_PCACTCTXA () ; 
 int /*<<< orphan*/  test_pack_PCACTCTXW () ; 
 int /*<<< orphan*/  test_pack_PCACTCTX_SECTION_KEYED_DATA () ; 
 int /*<<< orphan*/  test_pack_PCACTCTX_SECTION_KEYED_DATA_2600 () ; 
 int /*<<< orphan*/  test_pack_PCACTCTX_SECTION_KEYED_DATA_ASSEMBLY_METADATA () ; 
 int /*<<< orphan*/  test_pack_PCRITICAL_SECTION () ; 
 int /*<<< orphan*/  test_pack_PCRITICAL_SECTION_DEBUG () ; 
 int /*<<< orphan*/  test_pack_PFIBER_START_ROUTINE () ; 
 int /*<<< orphan*/  test_pack_PHKEY () ; 
 int /*<<< orphan*/  test_pack_POFSTRUCT () ; 
 int /*<<< orphan*/  test_pack_POSVERSIONINFOA () ; 
 int /*<<< orphan*/  test_pack_POSVERSIONINFOEXA () ; 
 int /*<<< orphan*/  test_pack_POSVERSIONINFOEXW () ; 
 int /*<<< orphan*/  test_pack_POSVERSIONINFOW () ; 
 int /*<<< orphan*/  test_pack_PPROCESS_HEAP_ENTRY () ; 
 int /*<<< orphan*/  test_pack_PPROCESS_INFORMATION () ; 
 int /*<<< orphan*/  test_pack_PQUERYACTCTXW_FUNC () ; 
 int /*<<< orphan*/  test_pack_PROCESS_HEAP_ENTRY () ; 
 int /*<<< orphan*/  test_pack_PROCESS_INFORMATION () ; 
 int /*<<< orphan*/  test_pack_PSECURITY_ATTRIBUTES () ; 
 int /*<<< orphan*/  test_pack_PSYSTEMTIME () ; 
 int /*<<< orphan*/  test_pack_PTIMERAPCROUTINE () ; 
 int /*<<< orphan*/  test_pack_PTIME_ZONE_INFORMATION () ; 
 int /*<<< orphan*/  test_pack_PWIN32_FIND_DATAA () ; 
 int /*<<< orphan*/  test_pack_PWIN32_FIND_DATAW () ; 
 int /*<<< orphan*/  test_pack_RIP_INFO () ; 
 int /*<<< orphan*/  test_pack_SECURITY_ATTRIBUTES () ; 
 int /*<<< orphan*/  test_pack_STARTUPINFOA () ; 
 int /*<<< orphan*/  test_pack_STARTUPINFOW () ; 
 int /*<<< orphan*/  test_pack_SYSTEMTIME () ; 
 int /*<<< orphan*/  test_pack_SYSTEM_INFO () ; 
 int /*<<< orphan*/  test_pack_SYSTEM_POWER_STATUS () ; 
 int /*<<< orphan*/  test_pack_TIME_ZONE_INFORMATION () ; 
 int /*<<< orphan*/  test_pack_UNLOAD_DLL_DEBUG_INFO () ; 
 int /*<<< orphan*/  test_pack_WAITORTIMERCALLBACK () ; 
 int /*<<< orphan*/  test_pack_WIN32_FILE_ATTRIBUTE_DATA () ; 
 int /*<<< orphan*/  test_pack_WIN32_FIND_DATAA () ; 
 int /*<<< orphan*/  test_pack_WIN32_FIND_DATAW () ; 
 int /*<<< orphan*/  test_pack_WIN32_STREAM_ID () ; 

__attribute__((used)) static void test_pack(void)
{
    test_pack_ACTCTXA();
    test_pack_ACTCTXW();
    test_pack_ACTCTX_SECTION_KEYED_DATA();
    test_pack_ACTCTX_SECTION_KEYED_DATA_2600();
    test_pack_ACTCTX_SECTION_KEYED_DATA_ASSEMBLY_METADATA();
    test_pack_ACTIVATION_CONTEXT_BASIC_INFORMATION();
    test_pack_BY_HANDLE_FILE_INFORMATION();
    test_pack_COMMCONFIG();
    test_pack_COMMPROP();
    test_pack_COMMTIMEOUTS();
    test_pack_COMSTAT();
    test_pack_CREATE_PROCESS_DEBUG_INFO();
    test_pack_CREATE_THREAD_DEBUG_INFO();
    test_pack_CRITICAL_SECTION();
    test_pack_CRITICAL_SECTION_DEBUG();
    test_pack_DCB();
    test_pack_DEBUG_EVENT();
    test_pack_ENUMRESLANGPROCA();
    test_pack_ENUMRESLANGPROCW();
    test_pack_ENUMRESNAMEPROCA();
    test_pack_ENUMRESNAMEPROCW();
    test_pack_ENUMRESTYPEPROCA();
    test_pack_ENUMRESTYPEPROCW();
    test_pack_EXCEPTION_DEBUG_INFO();
    test_pack_EXIT_PROCESS_DEBUG_INFO();
    test_pack_EXIT_THREAD_DEBUG_INFO();
    test_pack_HW_PROFILE_INFOA();
    test_pack_HW_PROFILE_INFOW();
    test_pack_LOAD_DLL_DEBUG_INFO();
    test_pack_LPBY_HANDLE_FILE_INFORMATION();
    test_pack_LPCOMMCONFIG();
    test_pack_LPCOMMPROP();
    test_pack_LPCOMMTIMEOUTS();
    test_pack_LPCOMSTAT();
    test_pack_LPCRITICAL_SECTION();
    test_pack_LPCRITICAL_SECTION_DEBUG();
    test_pack_LPDCB();
    test_pack_LPDEBUG_EVENT();
    test_pack_LPEXCEPTION_POINTERS();
    test_pack_LPEXCEPTION_RECORD();
    test_pack_LPFIBER_START_ROUTINE();
    test_pack_LPHW_PROFILE_INFOA();
    test_pack_LPHW_PROFILE_INFOW();
    test_pack_LPLONG();
    test_pack_LPMEMORYSTATUS();
    test_pack_LPMEMORYSTATUSEX();
    test_pack_LPOFSTRUCT();
    test_pack_LPOSVERSIONINFOA();
    test_pack_LPOSVERSIONINFOEXA();
    test_pack_LPOSVERSIONINFOEXW();
    test_pack_LPOSVERSIONINFOW();
    test_pack_LPOVERLAPPED();
    test_pack_LPOVERLAPPED_COMPLETION_ROUTINE();
    test_pack_LPPROCESS_HEAP_ENTRY();
    test_pack_LPPROCESS_INFORMATION();
    test_pack_LPPROGRESS_ROUTINE();
    test_pack_LPSECURITY_ATTRIBUTES();
    test_pack_LPSTARTUPINFOA();
    test_pack_LPSTARTUPINFOW();
    test_pack_LPSYSTEMTIME();
    test_pack_LPSYSTEM_INFO();
    test_pack_LPSYSTEM_POWER_STATUS();
    test_pack_LPTHREAD_START_ROUTINE();
    test_pack_LPTIME_ZONE_INFORMATION();
    test_pack_LPVOID();
    test_pack_LPWIN32_FILE_ATTRIBUTE_DATA();
    test_pack_LPWIN32_FIND_DATAA();
    test_pack_LPWIN32_FIND_DATAW();
    test_pack_LPWIN32_STREAM_ID();
    test_pack_MEMORYSTATUS();
    test_pack_MEMORYSTATUSEX();
    test_pack_OFSTRUCT();
    test_pack_OSVERSIONINFOA();
    test_pack_OSVERSIONINFOEXA();
    test_pack_OSVERSIONINFOEXW();
    test_pack_OSVERSIONINFOW();
    test_pack_OUTPUT_DEBUG_STRING_INFO();
    test_pack_PACTCTXA();
    test_pack_PACTCTXW();
    test_pack_PACTCTX_SECTION_KEYED_DATA();
    test_pack_PACTCTX_SECTION_KEYED_DATA_2600();
    test_pack_PACTCTX_SECTION_KEYED_DATA_ASSEMBLY_METADATA();
    test_pack_PACTIVATION_CONTEXT_BASIC_INFORMATION();
    test_pack_PAPCFUNC();
    test_pack_PBY_HANDLE_FILE_INFORMATION();
    test_pack_PCACTCTXA();
    test_pack_PCACTCTXW();
    test_pack_PCACTCTX_SECTION_KEYED_DATA();
    test_pack_PCACTCTX_SECTION_KEYED_DATA_2600();
    test_pack_PCACTCTX_SECTION_KEYED_DATA_ASSEMBLY_METADATA();
    test_pack_PCRITICAL_SECTION();
    test_pack_PCRITICAL_SECTION_DEBUG();
    test_pack_PFIBER_START_ROUTINE();
    test_pack_PHKEY();
    test_pack_POFSTRUCT();
    test_pack_POSVERSIONINFOA();
    test_pack_POSVERSIONINFOEXA();
    test_pack_POSVERSIONINFOEXW();
    test_pack_POSVERSIONINFOW();
    test_pack_PPROCESS_HEAP_ENTRY();
    test_pack_PPROCESS_INFORMATION();
    test_pack_PQUERYACTCTXW_FUNC();
    test_pack_PROCESS_HEAP_ENTRY();
    test_pack_PROCESS_INFORMATION();
    test_pack_PSECURITY_ATTRIBUTES();
    test_pack_PSYSTEMTIME();
    test_pack_PTIMERAPCROUTINE();
    test_pack_PTIME_ZONE_INFORMATION();
    test_pack_PWIN32_FIND_DATAA();
    test_pack_PWIN32_FIND_DATAW();
    test_pack_RIP_INFO();
    test_pack_SECURITY_ATTRIBUTES();
    test_pack_STARTUPINFOA();
    test_pack_STARTUPINFOW();
    test_pack_SYSTEMTIME();
    test_pack_SYSTEM_INFO();
    test_pack_SYSTEM_POWER_STATUS();
    test_pack_TIME_ZONE_INFORMATION();
    test_pack_UNLOAD_DLL_DEBUG_INFO();
    test_pack_WAITORTIMERCALLBACK();
    test_pack_WIN32_FILE_ATTRIBUTE_DATA();
    test_pack_WIN32_FIND_DATAA();
    test_pack_WIN32_FIND_DATAW();
    test_pack_WIN32_STREAM_ID();
}