#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */

/* Variables and functions */
#define  CSIDL_ADMINTOOLS 185 
#define  CSIDL_ALTSTARTUP 184 
#define  CSIDL_APPDATA 183 
#define  CSIDL_BITBUCKET 182 
#define  CSIDL_CDBURN_AREA 181 
#define  CSIDL_COMMON_ADMINTOOLS 180 
#define  CSIDL_COMMON_ALTSTARTUP 179 
#define  CSIDL_COMMON_APPDATA 178 
#define  CSIDL_COMMON_DESKTOPDIRECTORY 177 
#define  CSIDL_COMMON_DOCUMENTS 176 
#define  CSIDL_COMMON_FAVORITES 175 
#define  CSIDL_COMMON_MUSIC 174 
#define  CSIDL_COMMON_OEM_LINKS 173 
#define  CSIDL_COMMON_PICTURES 172 
#define  CSIDL_COMMON_PROGRAMS 171 
#define  CSIDL_COMMON_STARTMENU 170 
#define  CSIDL_COMMON_STARTUP 169 
#define  CSIDL_COMMON_TEMPLATES 168 
#define  CSIDL_COMMON_VIDEO 167 
#define  CSIDL_COMPUTERSNEARME 166 
#define  CSIDL_CONNECTIONS 165 
#define  CSIDL_CONTROLS 164 
#define  CSIDL_COOKIES 163 
#define  CSIDL_DESKTOP 162 
#define  CSIDL_DESKTOPDIRECTORY 161 
#define  CSIDL_DRIVES 160 
#define  CSIDL_FAVORITES 159 
#define  CSIDL_FONTS 158 
#define  CSIDL_HISTORY 157 
#define  CSIDL_INTERNET 156 
#define  CSIDL_INTERNET_CACHE 155 
#define  CSIDL_LOCAL_APPDATA 154 
#define  CSIDL_MYMUSIC 153 
#define  CSIDL_MYPICTURES 152 
#define  CSIDL_MYVIDEO 151 
#define  CSIDL_NETHOOD 150 
#define  CSIDL_NETWORK 149 
#define  CSIDL_PERSONAL 148 
#define  CSIDL_PRINTERS 147 
#define  CSIDL_PRINTHOOD 146 
#define  CSIDL_PROFILE 145 
#define  CSIDL_PROFILES 144 
#define  CSIDL_PROGRAMS 143 
#define  CSIDL_PROGRAM_FILES 142 
#define  CSIDL_PROGRAM_FILESX86 141 
#define  CSIDL_PROGRAM_FILES_COMMON 140 
#define  CSIDL_PROGRAM_FILES_COMMONX86 139 
#define  CSIDL_RECENT 138 
#define  CSIDL_RESOURCES 137 
#define  CSIDL_RESOURCES_LOCALIZED 136 
#define  CSIDL_SENDTO 135 
#define  CSIDL_STARTMENU 134 
#define  CSIDL_STARTUP 133 
#define  CSIDL_SYSTEM 132 
#define  CSIDL_SYSTEMX86 131 
#define  CSIDL_TEMPLATES 130 
#define  CSIDL_WINDOWS 129 
#define  OLD_CSIDL_MYDOCUMENTS 128 
 int /*<<< orphan*/  sprintf (char*,char*,int) ; 

__attribute__((used)) static const char *getFolderName(int folder)
{
    static char unknown[32];

#define CSIDL_TO_STR(x) case x: return#x;
    switch (folder)
    {
    CSIDL_TO_STR(CSIDL_DESKTOP);
    CSIDL_TO_STR(CSIDL_INTERNET);
    CSIDL_TO_STR(CSIDL_PROGRAMS);
    CSIDL_TO_STR(CSIDL_CONTROLS);
    CSIDL_TO_STR(CSIDL_PRINTERS);
    CSIDL_TO_STR(CSIDL_PERSONAL);
    CSIDL_TO_STR(CSIDL_FAVORITES);
    CSIDL_TO_STR(CSIDL_STARTUP);
    CSIDL_TO_STR(CSIDL_RECENT);
    CSIDL_TO_STR(CSIDL_SENDTO);
    CSIDL_TO_STR(CSIDL_BITBUCKET);
    CSIDL_TO_STR(CSIDL_STARTMENU);
    CSIDL_TO_STR(OLD_CSIDL_MYDOCUMENTS);
    CSIDL_TO_STR(CSIDL_MYMUSIC);
    CSIDL_TO_STR(CSIDL_MYVIDEO);
    CSIDL_TO_STR(CSIDL_DESKTOPDIRECTORY);
    CSIDL_TO_STR(CSIDL_DRIVES);
    CSIDL_TO_STR(CSIDL_NETWORK);
    CSIDL_TO_STR(CSIDL_NETHOOD);
    CSIDL_TO_STR(CSIDL_FONTS);
    CSIDL_TO_STR(CSIDL_TEMPLATES);
    CSIDL_TO_STR(CSIDL_COMMON_STARTMENU);
    CSIDL_TO_STR(CSIDL_COMMON_PROGRAMS);
    CSIDL_TO_STR(CSIDL_COMMON_STARTUP);
    CSIDL_TO_STR(CSIDL_COMMON_DESKTOPDIRECTORY);
    CSIDL_TO_STR(CSIDL_APPDATA);
    CSIDL_TO_STR(CSIDL_PRINTHOOD);
    CSIDL_TO_STR(CSIDL_LOCAL_APPDATA);
    CSIDL_TO_STR(CSIDL_ALTSTARTUP);
    CSIDL_TO_STR(CSIDL_COMMON_ALTSTARTUP);
    CSIDL_TO_STR(CSIDL_COMMON_FAVORITES);
    CSIDL_TO_STR(CSIDL_INTERNET_CACHE);
    CSIDL_TO_STR(CSIDL_COOKIES);
    CSIDL_TO_STR(CSIDL_HISTORY);
    CSIDL_TO_STR(CSIDL_COMMON_APPDATA);
    CSIDL_TO_STR(CSIDL_WINDOWS);
    CSIDL_TO_STR(CSIDL_SYSTEM);
    CSIDL_TO_STR(CSIDL_PROGRAM_FILES);
    CSIDL_TO_STR(CSIDL_MYPICTURES);
    CSIDL_TO_STR(CSIDL_PROFILE);
    CSIDL_TO_STR(CSIDL_SYSTEMX86);
    CSIDL_TO_STR(CSIDL_PROGRAM_FILESX86);
    CSIDL_TO_STR(CSIDL_PROGRAM_FILES_COMMON);
    CSIDL_TO_STR(CSIDL_PROGRAM_FILES_COMMONX86);
    CSIDL_TO_STR(CSIDL_COMMON_TEMPLATES);
    CSIDL_TO_STR(CSIDL_COMMON_DOCUMENTS);
    CSIDL_TO_STR(CSIDL_COMMON_ADMINTOOLS);
    CSIDL_TO_STR(CSIDL_ADMINTOOLS);
    CSIDL_TO_STR(CSIDL_CONNECTIONS);
    CSIDL_TO_STR(CSIDL_PROFILES);
    CSIDL_TO_STR(CSIDL_COMMON_MUSIC);
    CSIDL_TO_STR(CSIDL_COMMON_PICTURES);
    CSIDL_TO_STR(CSIDL_COMMON_VIDEO);
    CSIDL_TO_STR(CSIDL_RESOURCES);
    CSIDL_TO_STR(CSIDL_RESOURCES_LOCALIZED);
    CSIDL_TO_STR(CSIDL_COMMON_OEM_LINKS);
    CSIDL_TO_STR(CSIDL_CDBURN_AREA);
    CSIDL_TO_STR(CSIDL_COMPUTERSNEARME);
#undef CSIDL_TO_STR
    default:
        sprintf(unknown, "unknown (0x%04x)", folder);
        return unknown;
    }
}