#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */

/* Variables and functions */
 int /*<<< orphan*/  test_pack_ACCESS_ALLOWED_ACE () ; 
 int /*<<< orphan*/  test_pack_ACCESS_DENIED_ACE () ; 
 int /*<<< orphan*/  test_pack_ACCESS_MASK () ; 
 int /*<<< orphan*/  test_pack_ACE_HEADER () ; 
 int /*<<< orphan*/  test_pack_ACL () ; 
 int /*<<< orphan*/  test_pack_ACL_REVISION_INFORMATION () ; 
 int /*<<< orphan*/  test_pack_ACL_SIZE_INFORMATION () ; 
 int /*<<< orphan*/  test_pack_ATOM () ; 
 int /*<<< orphan*/  test_pack_BOOL () ; 
 int /*<<< orphan*/  test_pack_BOOLEAN () ; 
 int /*<<< orphan*/  test_pack_BYTE () ; 
 int /*<<< orphan*/  test_pack_CCHAR () ; 
 int /*<<< orphan*/  test_pack_CHAR () ; 
 int /*<<< orphan*/  test_pack_COLORREF () ; 
 int /*<<< orphan*/  test_pack_DWORD () ; 
 int /*<<< orphan*/  test_pack_DWORD32 () ; 
 int /*<<< orphan*/  test_pack_DWORD64 () ; 
 int /*<<< orphan*/  test_pack_DWORDLONG () ; 
 int /*<<< orphan*/  test_pack_DWORD_PTR () ; 
 int /*<<< orphan*/  test_pack_EXCEPTION_POINTERS () ; 
 int /*<<< orphan*/  test_pack_EXCEPTION_RECORD () ; 
 int /*<<< orphan*/  test_pack_EXECUTION_STATE () ; 
 int /*<<< orphan*/  test_pack_FARPROC () ; 
 int /*<<< orphan*/  test_pack_FLOAT () ; 
 int /*<<< orphan*/  test_pack_FPO_DATA () ; 
 int /*<<< orphan*/  test_pack_GENERIC_MAPPING () ; 
 int /*<<< orphan*/  test_pack_GLOBALHANDLE () ; 
 int /*<<< orphan*/  test_pack_HALF_PTR () ; 
 int /*<<< orphan*/  test_pack_HANDLE () ; 
 int /*<<< orphan*/  test_pack_HCURSOR () ; 
 int /*<<< orphan*/  test_pack_HFILE () ; 
 int /*<<< orphan*/  test_pack_HGDIOBJ () ; 
 int /*<<< orphan*/  test_pack_HGLOBAL () ; 
 int /*<<< orphan*/  test_pack_HLOCAL () ; 
 int /*<<< orphan*/  test_pack_HMODULE () ; 
 int /*<<< orphan*/  test_pack_HRESULT () ; 
 int /*<<< orphan*/  test_pack_IMAGE_ARCHIVE_MEMBER_HEADER () ; 
 int /*<<< orphan*/  test_pack_IMAGE_AUX_SYMBOL () ; 
 int /*<<< orphan*/  test_pack_IMAGE_BASE_RELOCATION () ; 
 int /*<<< orphan*/  test_pack_IMAGE_BOUND_FORWARDER_REF () ; 
 int /*<<< orphan*/  test_pack_IMAGE_BOUND_IMPORT_DESCRIPTOR () ; 
 int /*<<< orphan*/  test_pack_IMAGE_COFF_SYMBOLS_HEADER () ; 
 int /*<<< orphan*/  test_pack_IMAGE_DATA_DIRECTORY () ; 
 int /*<<< orphan*/  test_pack_IMAGE_DEBUG_DIRECTORY () ; 
 int /*<<< orphan*/  test_pack_IMAGE_DEBUG_MISC () ; 
 int /*<<< orphan*/  test_pack_IMAGE_DOS_HEADER () ; 
 int /*<<< orphan*/  test_pack_IMAGE_EXPORT_DIRECTORY () ; 
 int /*<<< orphan*/  test_pack_IMAGE_FILE_HEADER () ; 
 int /*<<< orphan*/  test_pack_IMAGE_FUNCTION_ENTRY () ; 
 int /*<<< orphan*/  test_pack_IMAGE_IMPORT_BY_NAME () ; 
 int /*<<< orphan*/  test_pack_IMAGE_IMPORT_DESCRIPTOR () ; 
 int /*<<< orphan*/  test_pack_IMAGE_LINENUMBER () ; 
 int /*<<< orphan*/  test_pack_IMAGE_LOAD_CONFIG_DIRECTORY () ; 
 int /*<<< orphan*/  test_pack_IMAGE_LOAD_CONFIG_DIRECTORY32 () ; 
 int /*<<< orphan*/  test_pack_IMAGE_LOAD_CONFIG_DIRECTORY64 () ; 
 int /*<<< orphan*/  test_pack_IMAGE_NT_HEADERS () ; 
 int /*<<< orphan*/  test_pack_IMAGE_NT_HEADERS32 () ; 
 int /*<<< orphan*/  test_pack_IMAGE_NT_HEADERS64 () ; 
 int /*<<< orphan*/  test_pack_IMAGE_OPTIONAL_HEADER () ; 
 int /*<<< orphan*/  test_pack_IMAGE_OPTIONAL_HEADER32 () ; 
 int /*<<< orphan*/  test_pack_IMAGE_OPTIONAL_HEADER64 () ; 
 int /*<<< orphan*/  test_pack_IMAGE_OS2_HEADER () ; 
 int /*<<< orphan*/  test_pack_IMAGE_RELOCATION () ; 
 int /*<<< orphan*/  test_pack_IMAGE_RESOURCE_DATA_ENTRY () ; 
 int /*<<< orphan*/  test_pack_IMAGE_RESOURCE_DIRECTORY () ; 
 int /*<<< orphan*/  test_pack_IMAGE_RESOURCE_DIRECTORY_ENTRY () ; 
 int /*<<< orphan*/  test_pack_IMAGE_RESOURCE_DIRECTORY_STRING () ; 
 int /*<<< orphan*/  test_pack_IMAGE_RESOURCE_DIR_STRING_U () ; 
 int /*<<< orphan*/  test_pack_IMAGE_SECTION_HEADER () ; 
 int /*<<< orphan*/  test_pack_IMAGE_SEPARATE_DEBUG_HEADER () ; 
 int /*<<< orphan*/  test_pack_IMAGE_SYMBOL () ; 
 int /*<<< orphan*/  test_pack_IMAGE_THUNK_DATA () ; 
 int /*<<< orphan*/  test_pack_IMAGE_TLS_DIRECTORY () ; 
 int /*<<< orphan*/  test_pack_IMAGE_TLS_DIRECTORY32 () ; 
 int /*<<< orphan*/  test_pack_IMAGE_TLS_DIRECTORY64 () ; 
 int /*<<< orphan*/  test_pack_IMAGE_VXD_HEADER () ; 
 int /*<<< orphan*/  test_pack_INT () ; 
 int /*<<< orphan*/  test_pack_INT16 () ; 
 int /*<<< orphan*/  test_pack_INT32 () ; 
 int /*<<< orphan*/  test_pack_INT64 () ; 
 int /*<<< orphan*/  test_pack_INT8 () ; 
 int /*<<< orphan*/  test_pack_INT_PTR () ; 
 int /*<<< orphan*/  test_pack_IO_COUNTERS () ; 
 int /*<<< orphan*/  test_pack_LANGID () ; 
 int /*<<< orphan*/  test_pack_LARGE_INTEGER () ; 
 int /*<<< orphan*/  test_pack_LCID () ; 
 int /*<<< orphan*/  test_pack_LIST_ENTRY () ; 
 int /*<<< orphan*/  test_pack_LOCALHANDLE () ; 
 int /*<<< orphan*/  test_pack_LONG () ; 
 int /*<<< orphan*/  test_pack_LONG32 () ; 
 int /*<<< orphan*/  test_pack_LONG64 () ; 
 int /*<<< orphan*/  test_pack_LONGLONG () ; 
 int /*<<< orphan*/  test_pack_LONG_PTR () ; 
 int /*<<< orphan*/  test_pack_LPARAM () ; 
 int /*<<< orphan*/  test_pack_LPCRECT () ; 
 int /*<<< orphan*/  test_pack_LPCRECTL () ; 
 int /*<<< orphan*/  test_pack_LPCVOID () ; 
 int /*<<< orphan*/  test_pack_LPPOINT () ; 
 int /*<<< orphan*/  test_pack_LPRECT () ; 
 int /*<<< orphan*/  test_pack_LPRECTL () ; 
 int /*<<< orphan*/  test_pack_LPSIZE () ; 
 int /*<<< orphan*/  test_pack_LRESULT () ; 
 int /*<<< orphan*/  test_pack_LUID () ; 
 int /*<<< orphan*/  test_pack_LUID_AND_ATTRIBUTES () ; 
 int /*<<< orphan*/  test_pack_MEMORY_BASIC_INFORMATION () ; 
 int /*<<< orphan*/  test_pack_MESSAGE_RESOURCE_BLOCK () ; 
 int /*<<< orphan*/  test_pack_MESSAGE_RESOURCE_DATA () ; 
 int /*<<< orphan*/  test_pack_MESSAGE_RESOURCE_ENTRY () ; 
 int /*<<< orphan*/  test_pack_NT_TIB () ; 
 int /*<<< orphan*/  test_pack_OBJECT_TYPE_LIST () ; 
 int /*<<< orphan*/  test_pack_PACCESS_ALLOWED_ACE () ; 
 int /*<<< orphan*/  test_pack_PACCESS_DENIED_ACE () ; 
 int /*<<< orphan*/  test_pack_PACCESS_TOKEN () ; 
 int /*<<< orphan*/  test_pack_PACE_HEADER () ; 
 int /*<<< orphan*/  test_pack_PACL () ; 
 int /*<<< orphan*/  test_pack_PACL_REVISION_INFORMATION () ; 
 int /*<<< orphan*/  test_pack_PACL_SIZE_INFORMATION () ; 
 int /*<<< orphan*/  test_pack_PCCH () ; 
 int /*<<< orphan*/  test_pack_PCH () ; 
 int /*<<< orphan*/  test_pack_PCSTR () ; 
 int /*<<< orphan*/  test_pack_PCWCH () ; 
 int /*<<< orphan*/  test_pack_PCWSTR () ; 
 int /*<<< orphan*/  test_pack_PEXCEPTION_POINTERS () ; 
 int /*<<< orphan*/  test_pack_PEXCEPTION_RECORD () ; 
 int /*<<< orphan*/  test_pack_PFPO_DATA () ; 
 int /*<<< orphan*/  test_pack_PGENERIC_MAPPING () ; 
 int /*<<< orphan*/  test_pack_PHANDLE () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_ARCHIVE_MEMBER_HEADER () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_AUX_SYMBOL () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_BASE_RELOCATION () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_BOUND_FORWARDER_REF () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_BOUND_IMPORT_DESCRIPTOR () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_COFF_SYMBOLS_HEADER () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_DATA_DIRECTORY () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_DEBUG_DIRECTORY () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_DEBUG_MISC () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_DOS_HEADER () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_EXPORT_DIRECTORY () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_FILE_HEADER () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_FUNCTION_ENTRY () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_IMPORT_BY_NAME () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_IMPORT_DESCRIPTOR () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_LINENUMBER () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_LOAD_CONFIG_DIRECTORY () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_NT_HEADERS () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_NT_HEADERS32 () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_NT_HEADERS64 () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_OPTIONAL_HEADER () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_OPTIONAL_HEADER32 () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_OPTIONAL_HEADER64 () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_OS2_HEADER () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_RELOCATION () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_RESOURCE_DATA_ENTRY () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_RESOURCE_DIRECTORY () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_RESOURCE_DIRECTORY_ENTRY () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_RESOURCE_DIRECTORY_STRING () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_RESOURCE_DIR_STRING_U () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_SECTION_HEADER () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_SEPARATE_DEBUG_HEADER () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_SYMBOL () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_THUNK_DATA () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_TLS_CALLBACK () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_TLS_DIRECTORY () ; 
 int /*<<< orphan*/  test_pack_PIMAGE_VXD_HEADER () ; 
 int /*<<< orphan*/  test_pack_PIO_COUNTERS () ; 
 int /*<<< orphan*/  test_pack_PISECURITY_DESCRIPTOR () ; 
 int /*<<< orphan*/  test_pack_PISECURITY_DESCRIPTOR_RELATIVE () ; 
 int /*<<< orphan*/  test_pack_PISID () ; 
 int /*<<< orphan*/  test_pack_PLARGE_INTEGER () ; 
 int /*<<< orphan*/  test_pack_PLIST_ENTRY () ; 
 int /*<<< orphan*/  test_pack_PLUID () ; 
 int /*<<< orphan*/  test_pack_PLUID_AND_ATTRIBUTES () ; 
 int /*<<< orphan*/  test_pack_PMEMORY_BASIC_INFORMATION () ; 
 int /*<<< orphan*/  test_pack_PMESSAGE_RESOURCE_BLOCK () ; 
 int /*<<< orphan*/  test_pack_PMESSAGE_RESOURCE_DATA () ; 
 int /*<<< orphan*/  test_pack_PMESSAGE_RESOURCE_ENTRY () ; 
 int /*<<< orphan*/  test_pack_PNT_TIB () ; 
 int /*<<< orphan*/  test_pack_POBJECT_TYPE_LIST () ; 
 int /*<<< orphan*/  test_pack_POINT () ; 
 int /*<<< orphan*/  test_pack_POINTL () ; 
 int /*<<< orphan*/  test_pack_PPOINT () ; 
 int /*<<< orphan*/  test_pack_PPOINTL () ; 
 int /*<<< orphan*/  test_pack_PPRIVILEGE_SET () ; 
 int /*<<< orphan*/  test_pack_PRECT () ; 
 int /*<<< orphan*/  test_pack_PRECTL () ; 
 int /*<<< orphan*/  test_pack_PRIVILEGE_SET () ; 
 int /*<<< orphan*/  test_pack_PRLIST_ENTRY () ; 
 int /*<<< orphan*/  test_pack_PROC () ; 
 int /*<<< orphan*/  test_pack_PRTL_CRITICAL_SECTION () ; 
 int /*<<< orphan*/  test_pack_PRTL_CRITICAL_SECTION_DEBUG () ; 
 int /*<<< orphan*/  test_pack_PRTL_OSVERSIONINFOEXW () ; 
 int /*<<< orphan*/  test_pack_PRTL_OSVERSIONINFOW () ; 
 int /*<<< orphan*/  test_pack_PRTL_RESOURCE_DEBUG () ; 
 int /*<<< orphan*/  test_pack_PSECURITY_DESCRIPTOR () ; 
 int /*<<< orphan*/  test_pack_PSECURITY_QUALITY_OF_SERVICE () ; 
 int /*<<< orphan*/  test_pack_PSID () ; 
 int /*<<< orphan*/  test_pack_PSID_IDENTIFIER_AUTHORITY () ; 
 int /*<<< orphan*/  test_pack_PSINGLE_LIST_ENTRY () ; 
 int /*<<< orphan*/  test_pack_PSIZE () ; 
 int /*<<< orphan*/  test_pack_PSTR () ; 
 int /*<<< orphan*/  test_pack_PSYSTEM_ALARM_ACE () ; 
 int /*<<< orphan*/  test_pack_PSYSTEM_AUDIT_ACE () ; 
 int /*<<< orphan*/  test_pack_PSZ () ; 
 int /*<<< orphan*/  test_pack_PTOKEN_GROUPS () ; 
 int /*<<< orphan*/  test_pack_PTOKEN_PRIVILEGES () ; 
 int /*<<< orphan*/  test_pack_PTOKEN_USER () ; 
 int /*<<< orphan*/  test_pack_PULARGE_INTEGER () ; 
 int /*<<< orphan*/  test_pack_PVECTORED_EXCEPTION_HANDLER () ; 
 int /*<<< orphan*/  test_pack_PVOID () ; 
 int /*<<< orphan*/  test_pack_PWCH () ; 
 int /*<<< orphan*/  test_pack_PWSTR () ; 
 int /*<<< orphan*/  test_pack_RECT () ; 
 int /*<<< orphan*/  test_pack_RECTL () ; 
 int /*<<< orphan*/  test_pack_RTL_CRITICAL_SECTION () ; 
 int /*<<< orphan*/  test_pack_RTL_CRITICAL_SECTION_DEBUG () ; 
 int /*<<< orphan*/  test_pack_RTL_OSVERSIONINFOEXW () ; 
 int /*<<< orphan*/  test_pack_RTL_OSVERSIONINFOW () ; 
 int /*<<< orphan*/  test_pack_RTL_RESOURCE_DEBUG () ; 
 int /*<<< orphan*/  test_pack_SECURITY_CONTEXT_TRACKING_MODE () ; 
 int /*<<< orphan*/  test_pack_SECURITY_DESCRIPTOR () ; 
 int /*<<< orphan*/  test_pack_SECURITY_DESCRIPTOR_CONTROL () ; 
 int /*<<< orphan*/  test_pack_SECURITY_DESCRIPTOR_RELATIVE () ; 
 int /*<<< orphan*/  test_pack_SECURITY_INFORMATION () ; 
 int /*<<< orphan*/  test_pack_SECURITY_QUALITY_OF_SERVICE () ; 
 int /*<<< orphan*/  test_pack_SHORT () ; 
 int /*<<< orphan*/  test_pack_SID () ; 
 int /*<<< orphan*/  test_pack_SID_AND_ATTRIBUTES () ; 
 int /*<<< orphan*/  test_pack_SID_IDENTIFIER_AUTHORITY () ; 
 int /*<<< orphan*/  test_pack_SINGLE_LIST_ENTRY () ; 
 int /*<<< orphan*/  test_pack_SIZE () ; 
 int /*<<< orphan*/  test_pack_SIZEL () ; 
 int /*<<< orphan*/  test_pack_SIZE_T () ; 
 int /*<<< orphan*/  test_pack_SSIZE_T () ; 
 int /*<<< orphan*/  test_pack_SYSTEM_ALARM_ACE () ; 
 int /*<<< orphan*/  test_pack_SYSTEM_AUDIT_ACE () ; 
 int /*<<< orphan*/  test_pack_TOKEN_DEFAULT_DACL () ; 
 int /*<<< orphan*/  test_pack_TOKEN_GROUPS () ; 
 int /*<<< orphan*/  test_pack_TOKEN_OWNER () ; 
 int /*<<< orphan*/  test_pack_TOKEN_PRIMARY_GROUP () ; 
 int /*<<< orphan*/  test_pack_TOKEN_PRIVILEGES () ; 
 int /*<<< orphan*/  test_pack_TOKEN_SOURCE () ; 
 int /*<<< orphan*/  test_pack_TOKEN_STATISTICS () ; 
 int /*<<< orphan*/  test_pack_TOKEN_USER () ; 
 int /*<<< orphan*/  test_pack_UCHAR () ; 
 int /*<<< orphan*/  test_pack_UHALF_PTR () ; 
 int /*<<< orphan*/  test_pack_UINT () ; 
 int /*<<< orphan*/  test_pack_UINT16 () ; 
 int /*<<< orphan*/  test_pack_UINT32 () ; 
 int /*<<< orphan*/  test_pack_UINT64 () ; 
 int /*<<< orphan*/  test_pack_UINT8 () ; 
 int /*<<< orphan*/  test_pack_UINT_PTR () ; 
 int /*<<< orphan*/  test_pack_ULARGE_INTEGER () ; 
 int /*<<< orphan*/  test_pack_ULONG () ; 
 int /*<<< orphan*/  test_pack_ULONG32 () ; 
 int /*<<< orphan*/  test_pack_ULONG64 () ; 
 int /*<<< orphan*/  test_pack_ULONGLONG () ; 
 int /*<<< orphan*/  test_pack_ULONG_PTR () ; 
 int /*<<< orphan*/  test_pack_USHORT () ; 
 int /*<<< orphan*/  test_pack_WAITORTIMERCALLBACKFUNC () ; 
 int /*<<< orphan*/  test_pack_WCHAR () ; 
 int /*<<< orphan*/  test_pack_WORD () ; 
 int /*<<< orphan*/  test_pack_WPARAM () ; 

__attribute__((used)) static void test_pack(void)
{
    test_pack_ACCESS_ALLOWED_ACE();
    test_pack_ACCESS_DENIED_ACE();
    test_pack_ACCESS_MASK();
    test_pack_ACE_HEADER();
    test_pack_ACL();
    test_pack_ACL_REVISION_INFORMATION();
    test_pack_ACL_SIZE_INFORMATION();
    test_pack_ATOM();
    test_pack_BOOL();
    test_pack_BOOLEAN();
    test_pack_BYTE();
    test_pack_CCHAR();
    test_pack_CHAR();
    test_pack_COLORREF();
    test_pack_DWORD();
    test_pack_DWORD32();
    test_pack_DWORD64();
    test_pack_DWORDLONG();
    test_pack_DWORD_PTR();
    test_pack_EXCEPTION_POINTERS();
    test_pack_EXCEPTION_RECORD();
    test_pack_EXECUTION_STATE();
    test_pack_FARPROC();
    test_pack_FLOAT();
    test_pack_FPO_DATA();
    test_pack_GENERIC_MAPPING();
    test_pack_GLOBALHANDLE();
    test_pack_HALF_PTR();
    test_pack_HANDLE();
    test_pack_HCURSOR();
    test_pack_HFILE();
    test_pack_HGDIOBJ();
    test_pack_HGLOBAL();
    test_pack_HLOCAL();
    test_pack_HMODULE();
    test_pack_HRESULT();
    test_pack_IMAGE_ARCHIVE_MEMBER_HEADER();
    test_pack_IMAGE_AUX_SYMBOL();
    test_pack_IMAGE_BASE_RELOCATION();
    test_pack_IMAGE_BOUND_FORWARDER_REF();
    test_pack_IMAGE_BOUND_IMPORT_DESCRIPTOR();
    test_pack_IMAGE_COFF_SYMBOLS_HEADER();
    test_pack_IMAGE_DATA_DIRECTORY();
    test_pack_IMAGE_DEBUG_DIRECTORY();
    test_pack_IMAGE_DEBUG_MISC();
    test_pack_IMAGE_DOS_HEADER();
    test_pack_IMAGE_EXPORT_DIRECTORY();
    test_pack_IMAGE_FILE_HEADER();
    test_pack_IMAGE_FUNCTION_ENTRY();
    test_pack_IMAGE_IMPORT_BY_NAME();
    test_pack_IMAGE_IMPORT_DESCRIPTOR();
    test_pack_IMAGE_LINENUMBER();
    test_pack_IMAGE_LOAD_CONFIG_DIRECTORY();
    test_pack_IMAGE_LOAD_CONFIG_DIRECTORY32();
    test_pack_IMAGE_LOAD_CONFIG_DIRECTORY64();
    test_pack_IMAGE_NT_HEADERS();
    test_pack_IMAGE_NT_HEADERS32();
    test_pack_IMAGE_NT_HEADERS64();
    test_pack_IMAGE_OPTIONAL_HEADER();
    test_pack_IMAGE_OPTIONAL_HEADER32();
    test_pack_IMAGE_OPTIONAL_HEADER64();
    test_pack_IMAGE_OS2_HEADER();
    test_pack_IMAGE_RELOCATION();
    test_pack_IMAGE_RESOURCE_DATA_ENTRY();
    test_pack_IMAGE_RESOURCE_DIRECTORY();
    test_pack_IMAGE_RESOURCE_DIRECTORY_ENTRY();
    test_pack_IMAGE_RESOURCE_DIRECTORY_STRING();
    test_pack_IMAGE_RESOURCE_DIR_STRING_U();
    test_pack_IMAGE_SECTION_HEADER();
    test_pack_IMAGE_SEPARATE_DEBUG_HEADER();
    test_pack_IMAGE_SYMBOL();
    test_pack_IMAGE_THUNK_DATA();
    test_pack_IMAGE_TLS_DIRECTORY();
    test_pack_IMAGE_TLS_DIRECTORY32();
    test_pack_IMAGE_TLS_DIRECTORY64();
    test_pack_IMAGE_VXD_HEADER();
    test_pack_INT();
    test_pack_INT16();
    test_pack_INT32();
    test_pack_INT64();
    test_pack_INT8();
    test_pack_INT_PTR();
    test_pack_IO_COUNTERS();
    test_pack_LANGID();
    test_pack_LARGE_INTEGER();
    test_pack_LCID();
    test_pack_LIST_ENTRY();
    test_pack_LOCALHANDLE();
    test_pack_LONG();
    test_pack_LONG32();
    test_pack_LONG64();
    test_pack_LONGLONG();
    test_pack_LONG_PTR();
    test_pack_LPARAM();
    test_pack_LPCRECT();
    test_pack_LPCRECTL();
    test_pack_LPCVOID();
    test_pack_LPPOINT();
    test_pack_LPRECT();
    test_pack_LPRECTL();
    test_pack_LPSIZE();
    test_pack_LRESULT();
    test_pack_LUID();
    test_pack_LUID_AND_ATTRIBUTES();
    test_pack_MEMORY_BASIC_INFORMATION();
    test_pack_MESSAGE_RESOURCE_BLOCK();
    test_pack_MESSAGE_RESOURCE_DATA();
    test_pack_MESSAGE_RESOURCE_ENTRY();
    test_pack_NT_TIB();
    test_pack_OBJECT_TYPE_LIST();
    test_pack_PACCESS_ALLOWED_ACE();
    test_pack_PACCESS_DENIED_ACE();
    test_pack_PACCESS_TOKEN();
    test_pack_PACE_HEADER();
    test_pack_PACL();
    test_pack_PACL_REVISION_INFORMATION();
    test_pack_PACL_SIZE_INFORMATION();
    test_pack_PCCH();
    test_pack_PCH();
    test_pack_PCSTR();
    test_pack_PCWCH();
    test_pack_PCWSTR();
    test_pack_PEXCEPTION_POINTERS();
    test_pack_PEXCEPTION_RECORD();
    test_pack_PFPO_DATA();
    test_pack_PGENERIC_MAPPING();
    test_pack_PHANDLE();
    test_pack_PIMAGE_ARCHIVE_MEMBER_HEADER();
    test_pack_PIMAGE_AUX_SYMBOL();
    test_pack_PIMAGE_BASE_RELOCATION();
    test_pack_PIMAGE_BOUND_FORWARDER_REF();
    test_pack_PIMAGE_BOUND_IMPORT_DESCRIPTOR();
    test_pack_PIMAGE_COFF_SYMBOLS_HEADER();
    test_pack_PIMAGE_DATA_DIRECTORY();
    test_pack_PIMAGE_DEBUG_DIRECTORY();
    test_pack_PIMAGE_DEBUG_MISC();
    test_pack_PIMAGE_DOS_HEADER();
    test_pack_PIMAGE_EXPORT_DIRECTORY();
    test_pack_PIMAGE_FILE_HEADER();
    test_pack_PIMAGE_FUNCTION_ENTRY();
    test_pack_PIMAGE_IMPORT_BY_NAME();
    test_pack_PIMAGE_IMPORT_DESCRIPTOR();
    test_pack_PIMAGE_LINENUMBER();
    test_pack_PIMAGE_LOAD_CONFIG_DIRECTORY();
    test_pack_PIMAGE_NT_HEADERS();
    test_pack_PIMAGE_NT_HEADERS32();
    test_pack_PIMAGE_NT_HEADERS64();
    test_pack_PIMAGE_OPTIONAL_HEADER();
    test_pack_PIMAGE_OPTIONAL_HEADER32();
    test_pack_PIMAGE_OPTIONAL_HEADER64();
    test_pack_PIMAGE_OS2_HEADER();
    test_pack_PIMAGE_RELOCATION();
    test_pack_PIMAGE_RESOURCE_DATA_ENTRY();
    test_pack_PIMAGE_RESOURCE_DIRECTORY();
    test_pack_PIMAGE_RESOURCE_DIRECTORY_ENTRY();
    test_pack_PIMAGE_RESOURCE_DIRECTORY_STRING();
    test_pack_PIMAGE_RESOURCE_DIR_STRING_U();
    test_pack_PIMAGE_SECTION_HEADER();
    test_pack_PIMAGE_SEPARATE_DEBUG_HEADER();
    test_pack_PIMAGE_SYMBOL();
    test_pack_PIMAGE_THUNK_DATA();
    test_pack_PIMAGE_TLS_CALLBACK();
    test_pack_PIMAGE_TLS_DIRECTORY();
    test_pack_PIMAGE_VXD_HEADER();
    test_pack_PIO_COUNTERS();
    test_pack_PISECURITY_DESCRIPTOR();
    test_pack_PISECURITY_DESCRIPTOR_RELATIVE();
    test_pack_PISID();
    test_pack_PLARGE_INTEGER();
    test_pack_PLIST_ENTRY();
    test_pack_PLUID();
    test_pack_PLUID_AND_ATTRIBUTES();
    test_pack_PMEMORY_BASIC_INFORMATION();
    test_pack_PMESSAGE_RESOURCE_BLOCK();
    test_pack_PMESSAGE_RESOURCE_DATA();
    test_pack_PMESSAGE_RESOURCE_ENTRY();
    test_pack_PNT_TIB();
    test_pack_POBJECT_TYPE_LIST();
    test_pack_POINT();
    test_pack_POINTL();
    test_pack_PPOINT();
    test_pack_PPOINTL();
    test_pack_PPRIVILEGE_SET();
    test_pack_PRECT();
    test_pack_PRECTL();
    test_pack_PRIVILEGE_SET();
    test_pack_PRLIST_ENTRY();
    test_pack_PROC();
    test_pack_PRTL_CRITICAL_SECTION();
    test_pack_PRTL_CRITICAL_SECTION_DEBUG();
    test_pack_PRTL_OSVERSIONINFOEXW();
    test_pack_PRTL_OSVERSIONINFOW();
    test_pack_PRTL_RESOURCE_DEBUG();
    test_pack_PSECURITY_DESCRIPTOR();
    test_pack_PSECURITY_QUALITY_OF_SERVICE();
    test_pack_PSID();
    test_pack_PSID_IDENTIFIER_AUTHORITY();
    test_pack_PSINGLE_LIST_ENTRY();
    test_pack_PSIZE();
    test_pack_PSTR();
    test_pack_PSYSTEM_ALARM_ACE();
    test_pack_PSYSTEM_AUDIT_ACE();
    test_pack_PSZ();
    test_pack_PTOKEN_GROUPS();
    test_pack_PTOKEN_PRIVILEGES();
    test_pack_PTOKEN_USER();
    test_pack_PULARGE_INTEGER();
    test_pack_PVECTORED_EXCEPTION_HANDLER();
    test_pack_PVOID();
    test_pack_PWCH();
    test_pack_PWSTR();
    test_pack_RECT();
    test_pack_RECTL();
    test_pack_RTL_CRITICAL_SECTION();
    test_pack_RTL_CRITICAL_SECTION_DEBUG();
    test_pack_RTL_OSVERSIONINFOEXW();
    test_pack_RTL_OSVERSIONINFOW();
    test_pack_RTL_RESOURCE_DEBUG();
    test_pack_SECURITY_CONTEXT_TRACKING_MODE();
    test_pack_SECURITY_DESCRIPTOR();
    test_pack_SECURITY_DESCRIPTOR_CONTROL();
    test_pack_SECURITY_DESCRIPTOR_RELATIVE();
    test_pack_SECURITY_INFORMATION();
    test_pack_SECURITY_QUALITY_OF_SERVICE();
    test_pack_SHORT();
    test_pack_SID();
    test_pack_SID_AND_ATTRIBUTES();
    test_pack_SID_IDENTIFIER_AUTHORITY();
    test_pack_SINGLE_LIST_ENTRY();
    test_pack_SIZE();
    test_pack_SIZEL();
    test_pack_SIZE_T();
    test_pack_SSIZE_T();
    test_pack_SYSTEM_ALARM_ACE();
    test_pack_SYSTEM_AUDIT_ACE();
    test_pack_TOKEN_DEFAULT_DACL();
    test_pack_TOKEN_GROUPS();
    test_pack_TOKEN_OWNER();
    test_pack_TOKEN_PRIMARY_GROUP();
    test_pack_TOKEN_PRIVILEGES();
    test_pack_TOKEN_SOURCE();
    test_pack_TOKEN_STATISTICS();
    test_pack_TOKEN_USER();
    test_pack_UCHAR();
    test_pack_UHALF_PTR();
    test_pack_UINT();
    test_pack_UINT16();
    test_pack_UINT32();
    test_pack_UINT64();
    test_pack_UINT8();
    test_pack_UINT_PTR();
    test_pack_ULARGE_INTEGER();
    test_pack_ULONG();
    test_pack_ULONG32();
    test_pack_ULONG64();
    test_pack_ULONGLONG();
    test_pack_ULONG_PTR();
    test_pack_USHORT();
    test_pack_WAITORTIMERCALLBACKFUNC();
    test_pack_WCHAR();
    test_pack_WORD();
    test_pack_WPARAM();
}