#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
struct vt_device {struct vga_softc* vd_softc; } ;
struct vga_softc {int dummy; } ;

/* Variables and functions */
 int /*<<< orphan*/  REG_WRITE1 (struct vga_softc*,int /*<<< orphan*/ ,int) ; 
 int /*<<< orphan*/  VGA_CRTC_ADDRESS ; 
 int /*<<< orphan*/  VGA_CRTC_DATA ; 
 int VGA_CRTC_EHB_CR ; 
 int /*<<< orphan*/  VGA_CRTC_EHR_EHB ; 
 int VGA_CRTC_END_HORIZ_BLANK ; 
 int VGA_CRTC_END_HORIZ_RETRACE ; 
 int VGA_CRTC_END_VERT_BLANK ; 
 int VGA_CRTC_HORIZ_DISP_END ; 
 int VGA_CRTC_HORIZ_TOTAL ; 
 int VGA_CRTC_LINE_COMPARE ; 
 int VGA_CRTC_MAX_SCAN_LINE ; 
 int VGA_CRTC_MC_AW ; 
 int VGA_CRTC_MC_CMS ; 
 int VGA_CRTC_MC_SRS ; 
 int VGA_CRTC_MC_WB ; 
 int VGA_CRTC_MODE_CONTROL ; 
 int VGA_CRTC_MSL_LC9 ; 
 int VGA_CRTC_OFFSET ; 
 int VGA_CRTC_OF_LC8 ; 
 int VGA_CRTC_OF_VBS8 ; 
 int VGA_CRTC_OF_VDE8 ; 
 int VGA_CRTC_OF_VRS8 ; 
 int VGA_CRTC_OF_VT9 ; 
 int VGA_CRTC_OVERFLOW ; 
 int VGA_CRTC_START_HORIZ_BLANK ; 
 int VGA_CRTC_START_HORIZ_RETRACE ; 
 int VGA_CRTC_START_VERT_BLANK ; 
 int VGA_CRTC_VERT_DISPLAY_END ; 
 int VGA_CRTC_VERT_RETRACE_END ; 
 int VGA_CRTC_VERT_RETRACE_START ; 
 int VGA_CRTC_VERT_TOTAL ; 
 int /*<<< orphan*/  VGA_GC_ADDRESS ; 
 int VGA_GC_BIT_MASK ; 
 int VGA_GC_COLOR_COMPARE ; 
 int VGA_GC_COLOR_DONT_CARE ; 
 int /*<<< orphan*/  VGA_GC_DATA ; 
 int VGA_GC_DATA_ROTATE ; 
 int VGA_GC_ENABLE_SET_RESET ; 
 int VGA_GC_MISCELLANEOUS ; 
 int VGA_GC_MISC_GA ; 
 int VGA_GC_MODE ; 
 int VGA_GC_READ_MAP_SELECT ; 
 int VGA_GC_SET_RESET ; 
 int /*<<< orphan*/  VGA_GEN_FEATURE_CTRL_W ; 
 int /*<<< orphan*/  VGA_GEN_MISC_OUTPUT_W ; 
 int VGA_GEN_MO_ER ; 
 int VGA_GEN_MO_HSP ; 
 int VGA_GEN_MO_IOA ; 
 int VGA_GEN_MO_PB ; 
 int VGA_GEN_MO_VSP ; 
 int /*<<< orphan*/  VGA_SEQ_ADDRESS ; 
 int VGA_SEQ_CHAR_MAP_SELECT ; 
 int VGA_SEQ_CLOCKING_MODE ; 
 int VGA_SEQ_CM_89 ; 
 int /*<<< orphan*/  VGA_SEQ_DATA ; 
 int VGA_SEQ_MAP_MASK ; 
 int VGA_SEQ_MEMORY_MODE ; 
 int VGA_SEQ_MM_EM ; 
 int VGA_SEQ_MM_EM0 ; 
 int VGA_SEQ_MM_EM1 ; 
 int VGA_SEQ_MM_EM2 ; 
 int VGA_SEQ_MM_EM3 ; 
 int VGA_SEQ_MM_OE ; 

__attribute__((used)) static void
vga_initialize_graphics(struct vt_device *vd)
{
	struct vga_softc *sc = vd->vd_softc;

	/* Clock select. */
	REG_WRITE1(sc, VGA_GEN_MISC_OUTPUT_W, VGA_GEN_MO_VSP | VGA_GEN_MO_HSP |
	    VGA_GEN_MO_PB | VGA_GEN_MO_ER | VGA_GEN_MO_IOA);
	/* Set sequencer clocking and memory mode. */
	REG_WRITE1(sc, VGA_SEQ_ADDRESS, VGA_SEQ_CLOCKING_MODE);
	REG_WRITE1(sc, VGA_SEQ_DATA, VGA_SEQ_CM_89);
	REG_WRITE1(sc, VGA_SEQ_ADDRESS, VGA_SEQ_MEMORY_MODE);
	REG_WRITE1(sc, VGA_SEQ_DATA, VGA_SEQ_MM_OE | VGA_SEQ_MM_EM);

	/* Set the graphics controller in graphics mode. */
	REG_WRITE1(sc, VGA_GC_ADDRESS, VGA_GC_MISCELLANEOUS);
	REG_WRITE1(sc, VGA_GC_DATA, 0x04 + VGA_GC_MISC_GA);
	/* Program the CRT controller. */
	REG_WRITE1(sc, VGA_CRTC_ADDRESS, VGA_CRTC_HORIZ_TOTAL);
	REG_WRITE1(sc, VGA_CRTC_DATA, 0x5f);			/* 760 */
	REG_WRITE1(sc, VGA_CRTC_ADDRESS, VGA_CRTC_HORIZ_DISP_END);
	REG_WRITE1(sc, VGA_CRTC_DATA, 0x4f);			/* 640 - 8 */
	REG_WRITE1(sc, VGA_CRTC_ADDRESS, VGA_CRTC_START_HORIZ_BLANK);
	REG_WRITE1(sc, VGA_CRTC_DATA, 0x50);			/* 640 */
	REG_WRITE1(sc, VGA_CRTC_ADDRESS, VGA_CRTC_END_HORIZ_BLANK);
	REG_WRITE1(sc, VGA_CRTC_DATA, VGA_CRTC_EHB_CR + 2);
	REG_WRITE1(sc, VGA_CRTC_ADDRESS, VGA_CRTC_START_HORIZ_RETRACE);
	REG_WRITE1(sc, VGA_CRTC_DATA, 0x54);			/* 672 */
	REG_WRITE1(sc, VGA_CRTC_ADDRESS, VGA_CRTC_END_HORIZ_RETRACE);
	REG_WRITE1(sc, VGA_CRTC_DATA, VGA_CRTC_EHR_EHB + 0);
	REG_WRITE1(sc, VGA_CRTC_ADDRESS, VGA_CRTC_VERT_TOTAL);
	REG_WRITE1(sc, VGA_CRTC_DATA, 0x0b);			/* 523 */
	REG_WRITE1(sc, VGA_CRTC_ADDRESS, VGA_CRTC_OVERFLOW);
	REG_WRITE1(sc, VGA_CRTC_DATA, VGA_CRTC_OF_VT9 | VGA_CRTC_OF_LC8 |
	    VGA_CRTC_OF_VBS8 | VGA_CRTC_OF_VRS8 | VGA_CRTC_OF_VDE8);
	REG_WRITE1(sc, VGA_CRTC_ADDRESS, VGA_CRTC_MAX_SCAN_LINE);
	REG_WRITE1(sc, VGA_CRTC_DATA, VGA_CRTC_MSL_LC9);
	REG_WRITE1(sc, VGA_CRTC_ADDRESS, VGA_CRTC_VERT_RETRACE_START);
	REG_WRITE1(sc, VGA_CRTC_DATA, 0xea);			/* 480 + 10 */
	REG_WRITE1(sc, VGA_CRTC_ADDRESS, VGA_CRTC_VERT_RETRACE_END);
	REG_WRITE1(sc, VGA_CRTC_DATA, 0x0c);
	REG_WRITE1(sc, VGA_CRTC_ADDRESS, VGA_CRTC_VERT_DISPLAY_END);
	REG_WRITE1(sc, VGA_CRTC_DATA, 0xdf);			/* 480 - 1*/
	REG_WRITE1(sc, VGA_CRTC_ADDRESS, VGA_CRTC_OFFSET);
	REG_WRITE1(sc, VGA_CRTC_DATA, 0x28);
	REG_WRITE1(sc, VGA_CRTC_ADDRESS, VGA_CRTC_START_VERT_BLANK);
	REG_WRITE1(sc, VGA_CRTC_DATA, 0xe7);			/* 480 + 7 */
	REG_WRITE1(sc, VGA_CRTC_ADDRESS, VGA_CRTC_END_VERT_BLANK);
	REG_WRITE1(sc, VGA_CRTC_DATA, 0x04);
	REG_WRITE1(sc, VGA_CRTC_ADDRESS, VGA_CRTC_MODE_CONTROL);
	REG_WRITE1(sc, VGA_CRTC_DATA, VGA_CRTC_MC_WB | VGA_CRTC_MC_AW |
	    VGA_CRTC_MC_SRS | VGA_CRTC_MC_CMS);
	REG_WRITE1(sc, VGA_CRTC_ADDRESS, VGA_CRTC_LINE_COMPARE);
	REG_WRITE1(sc, VGA_CRTC_DATA, 0xff);			/* 480 + 31 */

	REG_WRITE1(sc, VGA_GEN_FEATURE_CTRL_W, 0);

	REG_WRITE1(sc, VGA_SEQ_ADDRESS, VGA_SEQ_MAP_MASK);
	REG_WRITE1(sc, VGA_SEQ_DATA, VGA_SEQ_MM_EM3 | VGA_SEQ_MM_EM2 |
	    VGA_SEQ_MM_EM1 | VGA_SEQ_MM_EM0);
	REG_WRITE1(sc, VGA_SEQ_ADDRESS, VGA_SEQ_CHAR_MAP_SELECT);
	REG_WRITE1(sc, VGA_SEQ_DATA, 0);

	REG_WRITE1(sc, VGA_GC_ADDRESS, VGA_GC_SET_RESET);
	REG_WRITE1(sc, VGA_GC_DATA, 0);
	REG_WRITE1(sc, VGA_GC_ADDRESS, VGA_GC_ENABLE_SET_RESET);
	REG_WRITE1(sc, VGA_GC_DATA, 0x0f);
	REG_WRITE1(sc, VGA_GC_ADDRESS, VGA_GC_COLOR_COMPARE);
	REG_WRITE1(sc, VGA_GC_DATA, 0);
	REG_WRITE1(sc, VGA_GC_ADDRESS, VGA_GC_DATA_ROTATE);
	REG_WRITE1(sc, VGA_GC_DATA, 0);
	REG_WRITE1(sc, VGA_GC_ADDRESS, VGA_GC_READ_MAP_SELECT);
	REG_WRITE1(sc, VGA_GC_DATA, 0);
	REG_WRITE1(sc, VGA_GC_ADDRESS, VGA_GC_MODE);
	REG_WRITE1(sc, VGA_GC_DATA, 0);
	REG_WRITE1(sc, VGA_GC_ADDRESS, VGA_GC_COLOR_DONT_CARE);
	REG_WRITE1(sc, VGA_GC_DATA, 0x0f);
	REG_WRITE1(sc, VGA_GC_ADDRESS, VGA_GC_BIT_MASK);
	REG_WRITE1(sc, VGA_GC_DATA, 0xff);
}