#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */

/* Variables and functions */
 int /*<<< orphan*/  test_pack_ABC () ; 
 int /*<<< orphan*/  test_pack_ABCFLOAT () ; 
 int /*<<< orphan*/  test_pack_ABORTPROC () ; 
 int /*<<< orphan*/  test_pack_BITMAP () ; 
 int /*<<< orphan*/  test_pack_BITMAPCOREHEADER () ; 
 int /*<<< orphan*/  test_pack_BITMAPCOREINFO () ; 
 int /*<<< orphan*/  test_pack_BITMAPFILEHEADER () ; 
 int /*<<< orphan*/  test_pack_BITMAPINFO () ; 
 int /*<<< orphan*/  test_pack_BITMAPINFOHEADER () ; 
 int /*<<< orphan*/  test_pack_BITMAPV4HEADER () ; 
 int /*<<< orphan*/  test_pack_BITMAPV5HEADER () ; 
 int /*<<< orphan*/  test_pack_BLENDFUNCTION () ; 
 int /*<<< orphan*/  test_pack_CHARSETINFO () ; 
 int /*<<< orphan*/  test_pack_CIEXYZ () ; 
 int /*<<< orphan*/  test_pack_CIEXYZTRIPLE () ; 
 int /*<<< orphan*/  test_pack_COLOR16 () ; 
 int /*<<< orphan*/  test_pack_COLORADJUSTMENT () ; 
 int /*<<< orphan*/  test_pack_DEVMODEA () ; 
 int /*<<< orphan*/  test_pack_DEVMODEW () ; 
 int /*<<< orphan*/  test_pack_DIBSECTION () ; 
 int /*<<< orphan*/  test_pack_DISPLAY_DEVICEA () ; 
 int /*<<< orphan*/  test_pack_DISPLAY_DEVICEW () ; 
 int /*<<< orphan*/  test_pack_DOCINFOA () ; 
 int /*<<< orphan*/  test_pack_DOCINFOW () ; 
 int /*<<< orphan*/  test_pack_EMR () ; 
 int /*<<< orphan*/  test_pack_EMRABORTPATH () ; 
 int /*<<< orphan*/  test_pack_EMRANGLEARC () ; 
 int /*<<< orphan*/  test_pack_EMRARC () ; 
 int /*<<< orphan*/  test_pack_EMRARCTO () ; 
 int /*<<< orphan*/  test_pack_EMRBEGINPATH () ; 
 int /*<<< orphan*/  test_pack_EMRBITBLT () ; 
 int /*<<< orphan*/  test_pack_EMRCHORD () ; 
 int /*<<< orphan*/  test_pack_EMRCLOSEFIGURE () ; 
 int /*<<< orphan*/  test_pack_EMRCREATEBRUSHINDIRECT () ; 
 int /*<<< orphan*/  test_pack_EMRCREATECOLORSPACE () ; 
 int /*<<< orphan*/  test_pack_EMRCREATECOLORSPACEW () ; 
 int /*<<< orphan*/  test_pack_EMRCREATEDIBPATTERNBRUSHPT () ; 
 int /*<<< orphan*/  test_pack_EMRCREATEMONOBRUSH () ; 
 int /*<<< orphan*/  test_pack_EMRCREATEPEN () ; 
 int /*<<< orphan*/  test_pack_EMRDELETECOLORSPACE () ; 
 int /*<<< orphan*/  test_pack_EMRDELETEOBJECT () ; 
 int /*<<< orphan*/  test_pack_EMRELLIPSE () ; 
 int /*<<< orphan*/  test_pack_EMRENDPATH () ; 
 int /*<<< orphan*/  test_pack_EMREOF () ; 
 int /*<<< orphan*/  test_pack_EMREXCLUDECLIPRECT () ; 
 int /*<<< orphan*/  test_pack_EMREXTCREATEFONTINDIRECTW () ; 
 int /*<<< orphan*/  test_pack_EMREXTCREATEPEN () ; 
 int /*<<< orphan*/  test_pack_EMREXTFLOODFILL () ; 
 int /*<<< orphan*/  test_pack_EMREXTSELECTCLIPRGN () ; 
 int /*<<< orphan*/  test_pack_EMREXTTEXTOUTA () ; 
 int /*<<< orphan*/  test_pack_EMREXTTEXTOUTW () ; 
 int /*<<< orphan*/  test_pack_EMRFILLPATH () ; 
 int /*<<< orphan*/  test_pack_EMRFILLRGN () ; 
 int /*<<< orphan*/  test_pack_EMRFLATTENPATH () ; 
 int /*<<< orphan*/  test_pack_EMRFORMAT () ; 
 int /*<<< orphan*/  test_pack_EMRFRAMERGN () ; 
 int /*<<< orphan*/  test_pack_EMRGDICOMMENT () ; 
 int /*<<< orphan*/  test_pack_EMRGLSBOUNDEDRECORD () ; 
 int /*<<< orphan*/  test_pack_EMRGLSRECORD () ; 
 int /*<<< orphan*/  test_pack_EMRINTERSECTCLIPRECT () ; 
 int /*<<< orphan*/  test_pack_EMRINVERTRGN () ; 
 int /*<<< orphan*/  test_pack_EMRLINETO () ; 
 int /*<<< orphan*/  test_pack_EMRMASKBLT () ; 
 int /*<<< orphan*/  test_pack_EMRMODIFYWORLDTRANSFORM () ; 
 int /*<<< orphan*/  test_pack_EMRMOVETOEX () ; 
 int /*<<< orphan*/  test_pack_EMROFFSETCLIPRGN () ; 
 int /*<<< orphan*/  test_pack_EMRPAINTRGN () ; 
 int /*<<< orphan*/  test_pack_EMRPIE () ; 
 int /*<<< orphan*/  test_pack_EMRPIXELFORMAT () ; 
 int /*<<< orphan*/  test_pack_EMRPLGBLT () ; 
 int /*<<< orphan*/  test_pack_EMRPOLYBEZIER () ; 
 int /*<<< orphan*/  test_pack_EMRPOLYBEZIER16 () ; 
 int /*<<< orphan*/  test_pack_EMRPOLYBEZIERTO () ; 
 int /*<<< orphan*/  test_pack_EMRPOLYBEZIERTO16 () ; 
 int /*<<< orphan*/  test_pack_EMRPOLYDRAW () ; 
 int /*<<< orphan*/  test_pack_EMRPOLYDRAW16 () ; 
 int /*<<< orphan*/  test_pack_EMRPOLYGON () ; 
 int /*<<< orphan*/  test_pack_EMRPOLYGON16 () ; 
 int /*<<< orphan*/  test_pack_EMRPOLYLINE () ; 
 int /*<<< orphan*/  test_pack_EMRPOLYLINE16 () ; 
 int /*<<< orphan*/  test_pack_EMRPOLYLINETO () ; 
 int /*<<< orphan*/  test_pack_EMRPOLYLINETO16 () ; 
 int /*<<< orphan*/  test_pack_EMRPOLYPOLYGON () ; 
 int /*<<< orphan*/  test_pack_EMRPOLYPOLYGON16 () ; 
 int /*<<< orphan*/  test_pack_EMRPOLYPOLYLINE () ; 
 int /*<<< orphan*/  test_pack_EMRPOLYPOLYLINE16 () ; 
 int /*<<< orphan*/  test_pack_EMRPOLYTEXTOUTA () ; 
 int /*<<< orphan*/  test_pack_EMRPOLYTEXTOUTW () ; 
 int /*<<< orphan*/  test_pack_EMRREALIZEPALETTE () ; 
 int /*<<< orphan*/  test_pack_EMRRECTANGLE () ; 
 int /*<<< orphan*/  test_pack_EMRRESIZEPALETTE () ; 
 int /*<<< orphan*/  test_pack_EMRRESTOREDC () ; 
 int /*<<< orphan*/  test_pack_EMRROUNDRECT () ; 
 int /*<<< orphan*/  test_pack_EMRSAVEDC () ; 
 int /*<<< orphan*/  test_pack_EMRSCALEVIEWPORTEXTEX () ; 
 int /*<<< orphan*/  test_pack_EMRSCALEWINDOWEXTEX () ; 
 int /*<<< orphan*/  test_pack_EMRSELECTCLIPPATH () ; 
 int /*<<< orphan*/  test_pack_EMRSELECTCOLORSPACE () ; 
 int /*<<< orphan*/  test_pack_EMRSELECTOBJECT () ; 
 int /*<<< orphan*/  test_pack_EMRSELECTPALETTE () ; 
 int /*<<< orphan*/  test_pack_EMRSETARCDIRECTION () ; 
 int /*<<< orphan*/  test_pack_EMRSETBKCOLOR () ; 
 int /*<<< orphan*/  test_pack_EMRSETBKMODE () ; 
 int /*<<< orphan*/  test_pack_EMRSETBRUSHORGEX () ; 
 int /*<<< orphan*/  test_pack_EMRSETCOLORADJUSTMENT () ; 
 int /*<<< orphan*/  test_pack_EMRSETCOLORSPACE () ; 
 int /*<<< orphan*/  test_pack_EMRSETDIBITSTODEVICE () ; 
 int /*<<< orphan*/  test_pack_EMRSETICMMODE () ; 
 int /*<<< orphan*/  test_pack_EMRSETLAYOUT () ; 
 int /*<<< orphan*/  test_pack_EMRSETMAPMODE () ; 
 int /*<<< orphan*/  test_pack_EMRSETMAPPERFLAGS () ; 
 int /*<<< orphan*/  test_pack_EMRSETMETARGN () ; 
 int /*<<< orphan*/  test_pack_EMRSETMITERLIMIT () ; 
 int /*<<< orphan*/  test_pack_EMRSETPIXELV () ; 
 int /*<<< orphan*/  test_pack_EMRSETPOLYFILLMODE () ; 
 int /*<<< orphan*/  test_pack_EMRSETROP2 () ; 
 int /*<<< orphan*/  test_pack_EMRSETSTRETCHBLTMODE () ; 
 int /*<<< orphan*/  test_pack_EMRSETTEXTALIGN () ; 
 int /*<<< orphan*/  test_pack_EMRSETTEXTCOLOR () ; 
 int /*<<< orphan*/  test_pack_EMRSETVIEWPORTEXTEX () ; 
 int /*<<< orphan*/  test_pack_EMRSETVIEWPORTORGEX () ; 
 int /*<<< orphan*/  test_pack_EMRSETWINDOWEXTEX () ; 
 int /*<<< orphan*/  test_pack_EMRSETWINDOWORGEX () ; 
 int /*<<< orphan*/  test_pack_EMRSETWORLDTRANSFORM () ; 
 int /*<<< orphan*/  test_pack_EMRSTRETCHBLT () ; 
 int /*<<< orphan*/  test_pack_EMRSTRETCHDIBITS () ; 
 int /*<<< orphan*/  test_pack_EMRSTROKEANDFILLPATH () ; 
 int /*<<< orphan*/  test_pack_EMRSTROKEPATH () ; 
 int /*<<< orphan*/  test_pack_EMRTEXT () ; 
 int /*<<< orphan*/  test_pack_EMRWIDENPATH () ; 
 int /*<<< orphan*/  test_pack_ENHMETAHEADER () ; 
 int /*<<< orphan*/  test_pack_ENHMETARECORD () ; 
 int /*<<< orphan*/  test_pack_ENHMFENUMPROC () ; 
 int /*<<< orphan*/  test_pack_ENUMLOGFONTA () ; 
 int /*<<< orphan*/  test_pack_ENUMLOGFONTEXA () ; 
 int /*<<< orphan*/  test_pack_ENUMLOGFONTEXW () ; 
 int /*<<< orphan*/  test_pack_ENUMLOGFONTW () ; 
 int /*<<< orphan*/  test_pack_EXTLOGFONTA () ; 
 int /*<<< orphan*/  test_pack_EXTLOGFONTW () ; 
 int /*<<< orphan*/  test_pack_EXTLOGPEN () ; 
 int /*<<< orphan*/  test_pack_FIXED () ; 
 int /*<<< orphan*/  test_pack_FONTENUMPROCA () ; 
 int /*<<< orphan*/  test_pack_FONTENUMPROCW () ; 
 int /*<<< orphan*/  test_pack_FONTSIGNATURE () ; 
 int /*<<< orphan*/  test_pack_FXPT16DOT16 () ; 
 int /*<<< orphan*/  test_pack_FXPT2DOT30 () ; 
 int /*<<< orphan*/  test_pack_GCP_RESULTSA () ; 
 int /*<<< orphan*/  test_pack_GCP_RESULTSW () ; 
 int /*<<< orphan*/  test_pack_GLYPHMETRICS () ; 
 int /*<<< orphan*/  test_pack_GLYPHMETRICSFLOAT () ; 
 int /*<<< orphan*/  test_pack_GOBJENUMPROC () ; 
 int /*<<< orphan*/  test_pack_GRADIENT_RECT () ; 
 int /*<<< orphan*/  test_pack_GRADIENT_TRIANGLE () ; 
 int /*<<< orphan*/  test_pack_HANDLETABLE () ; 
 int /*<<< orphan*/  test_pack_ICMENUMPROCA () ; 
 int /*<<< orphan*/  test_pack_ICMENUMPROCW () ; 
 int /*<<< orphan*/  test_pack_KERNINGPAIR () ; 
 int /*<<< orphan*/  test_pack_LAYERPLANEDESCRIPTOR () ; 
 int /*<<< orphan*/  test_pack_LCSCSTYPE () ; 
 int /*<<< orphan*/  test_pack_LCSGAMUTMATCH () ; 
 int /*<<< orphan*/  test_pack_LINEDDAPROC () ; 
 int /*<<< orphan*/  test_pack_LOCALESIGNATURE () ; 
 int /*<<< orphan*/  test_pack_LOGBRUSH () ; 
 int /*<<< orphan*/  test_pack_LOGCOLORSPACEA () ; 
 int /*<<< orphan*/  test_pack_LOGCOLORSPACEW () ; 
 int /*<<< orphan*/  test_pack_LOGFONTA () ; 
 int /*<<< orphan*/  test_pack_LOGFONTW () ; 
 int /*<<< orphan*/  test_pack_LOGPEN () ; 
 int /*<<< orphan*/  test_pack_LPABC () ; 
 int /*<<< orphan*/  test_pack_LPABCFLOAT () ; 
 int /*<<< orphan*/  test_pack_LPBITMAP () ; 
 int /*<<< orphan*/  test_pack_LPBITMAPCOREHEADER () ; 
 int /*<<< orphan*/  test_pack_LPBITMAPCOREINFO () ; 
 int /*<<< orphan*/  test_pack_LPBITMAPFILEHEADER () ; 
 int /*<<< orphan*/  test_pack_LPBITMAPINFO () ; 
 int /*<<< orphan*/  test_pack_LPBITMAPINFOHEADER () ; 
 int /*<<< orphan*/  test_pack_LPBITMAPV5HEADER () ; 
 int /*<<< orphan*/  test_pack_LPCHARSETINFO () ; 
 int /*<<< orphan*/  test_pack_LPCIEXYZ () ; 
 int /*<<< orphan*/  test_pack_LPCIEXYZTRIPLE () ; 
 int /*<<< orphan*/  test_pack_LPCOLORADJUSTMENT () ; 
 int /*<<< orphan*/  test_pack_LPDEVMODEA () ; 
 int /*<<< orphan*/  test_pack_LPDEVMODEW () ; 
 int /*<<< orphan*/  test_pack_LPDIBSECTION () ; 
 int /*<<< orphan*/  test_pack_LPDISPLAY_DEVICEA () ; 
 int /*<<< orphan*/  test_pack_LPDISPLAY_DEVICEW () ; 
 int /*<<< orphan*/  test_pack_LPDOCINFOA () ; 
 int /*<<< orphan*/  test_pack_LPDOCINFOW () ; 
 int /*<<< orphan*/  test_pack_LPENHMETAHEADER () ; 
 int /*<<< orphan*/  test_pack_LPENHMETARECORD () ; 
 int /*<<< orphan*/  test_pack_LPENUMLOGFONTA () ; 
 int /*<<< orphan*/  test_pack_LPENUMLOGFONTEXA () ; 
 int /*<<< orphan*/  test_pack_LPENUMLOGFONTEXW () ; 
 int /*<<< orphan*/  test_pack_LPENUMLOGFONTW () ; 
 int /*<<< orphan*/  test_pack_LPEXTLOGFONTA () ; 
 int /*<<< orphan*/  test_pack_LPEXTLOGFONTW () ; 
 int /*<<< orphan*/  test_pack_LPEXTLOGPEN () ; 
 int /*<<< orphan*/  test_pack_LPFONTSIGNATURE () ; 
 int /*<<< orphan*/  test_pack_LPGCP_RESULTSA () ; 
 int /*<<< orphan*/  test_pack_LPGCP_RESULTSW () ; 
 int /*<<< orphan*/  test_pack_LPGLYPHMETRICS () ; 
 int /*<<< orphan*/  test_pack_LPGLYPHMETRICSFLOAT () ; 
 int /*<<< orphan*/  test_pack_LPGRADIENT_RECT () ; 
 int /*<<< orphan*/  test_pack_LPGRADIENT_TRIANGLE () ; 
 int /*<<< orphan*/  test_pack_LPHANDLETABLE () ; 
 int /*<<< orphan*/  test_pack_LPKERNINGPAIR () ; 
 int /*<<< orphan*/  test_pack_LPLAYERPLANEDESCRIPTOR () ; 
 int /*<<< orphan*/  test_pack_LPLOCALESIGNATURE () ; 
 int /*<<< orphan*/  test_pack_LPLOGBRUSH () ; 
 int /*<<< orphan*/  test_pack_LPLOGCOLORSPACEA () ; 
 int /*<<< orphan*/  test_pack_LPLOGCOLORSPACEW () ; 
 int /*<<< orphan*/  test_pack_LPLOGFONTA () ; 
 int /*<<< orphan*/  test_pack_LPLOGFONTW () ; 
 int /*<<< orphan*/  test_pack_LPLOGPEN () ; 
 int /*<<< orphan*/  test_pack_LPMAT2 () ; 
 int /*<<< orphan*/  test_pack_LPMETAFILEPICT () ; 
 int /*<<< orphan*/  test_pack_LPMETAHEADER () ; 
 int /*<<< orphan*/  test_pack_LPMETARECORD () ; 
 int /*<<< orphan*/  test_pack_LPNEWTEXTMETRICA () ; 
 int /*<<< orphan*/  test_pack_LPNEWTEXTMETRICW () ; 
 int /*<<< orphan*/  test_pack_LPOUTLINETEXTMETRICA () ; 
 int /*<<< orphan*/  test_pack_LPOUTLINETEXTMETRICW () ; 
 int /*<<< orphan*/  test_pack_LPPANOSE () ; 
 int /*<<< orphan*/  test_pack_LPPELARRAY () ; 
 int /*<<< orphan*/  test_pack_LPPIXELFORMATDESCRIPTOR () ; 
 int /*<<< orphan*/  test_pack_LPPOINTFX () ; 
 int /*<<< orphan*/  test_pack_LPPOLYTEXTA () ; 
 int /*<<< orphan*/  test_pack_LPPOLYTEXTW () ; 
 int /*<<< orphan*/  test_pack_LPRASTERIZER_STATUS () ; 
 int /*<<< orphan*/  test_pack_LPRGBQUAD () ; 
 int /*<<< orphan*/  test_pack_LPRGNDATA () ; 
 int /*<<< orphan*/  test_pack_LPTEXTMETRICA () ; 
 int /*<<< orphan*/  test_pack_LPTEXTMETRICW () ; 
 int /*<<< orphan*/  test_pack_LPTRIVERTEX () ; 
 int /*<<< orphan*/  test_pack_LPTTPOLYCURVE () ; 
 int /*<<< orphan*/  test_pack_LPTTPOLYGONHEADER () ; 
 int /*<<< orphan*/  test_pack_LPXFORM () ; 
 int /*<<< orphan*/  test_pack_MAT2 () ; 
 int /*<<< orphan*/  test_pack_METAFILEPICT () ; 
 int /*<<< orphan*/  test_pack_METAHEADER () ; 
 int /*<<< orphan*/  test_pack_METARECORD () ; 
 int /*<<< orphan*/  test_pack_MFENUMPROC () ; 
 int /*<<< orphan*/  test_pack_NEWTEXTMETRICA () ; 
 int /*<<< orphan*/  test_pack_NEWTEXTMETRICEXA () ; 
 int /*<<< orphan*/  test_pack_NEWTEXTMETRICEXW () ; 
 int /*<<< orphan*/  test_pack_NEWTEXTMETRICW () ; 
 int /*<<< orphan*/  test_pack_NPEXTLOGPEN () ; 
 int /*<<< orphan*/  test_pack_OLDFONTENUMPROCA () ; 
 int /*<<< orphan*/  test_pack_OLDFONTENUMPROCW () ; 
 int /*<<< orphan*/  test_pack_OUTLINETEXTMETRICA () ; 
 int /*<<< orphan*/  test_pack_OUTLINETEXTMETRICW () ; 
 int /*<<< orphan*/  test_pack_PABC () ; 
 int /*<<< orphan*/  test_pack_PABCFLOAT () ; 
 int /*<<< orphan*/  test_pack_PANOSE () ; 
 int /*<<< orphan*/  test_pack_PATTERN () ; 
 int /*<<< orphan*/  test_pack_PBITMAP () ; 
 int /*<<< orphan*/  test_pack_PBITMAPCOREHEADER () ; 
 int /*<<< orphan*/  test_pack_PBITMAPCOREINFO () ; 
 int /*<<< orphan*/  test_pack_PBITMAPFILEHEADER () ; 
 int /*<<< orphan*/  test_pack_PBITMAPINFO () ; 
 int /*<<< orphan*/  test_pack_PBITMAPINFOHEADER () ; 
 int /*<<< orphan*/  test_pack_PBITMAPV4HEADER () ; 
 int /*<<< orphan*/  test_pack_PBITMAPV5HEADER () ; 
 int /*<<< orphan*/  test_pack_PBLENDFUNCTION () ; 
 int /*<<< orphan*/  test_pack_PCHARSETINFO () ; 
 int /*<<< orphan*/  test_pack_PCOLORADJUSTMENT () ; 
 int /*<<< orphan*/  test_pack_PDEVMODEA () ; 
 int /*<<< orphan*/  test_pack_PDEVMODEW () ; 
 int /*<<< orphan*/  test_pack_PDIBSECTION () ; 
 int /*<<< orphan*/  test_pack_PDISPLAY_DEVICEA () ; 
 int /*<<< orphan*/  test_pack_PDISPLAY_DEVICEW () ; 
 int /*<<< orphan*/  test_pack_PELARRAY () ; 
 int /*<<< orphan*/  test_pack_PEMR () ; 
 int /*<<< orphan*/  test_pack_PEMRABORTPATH () ; 
 int /*<<< orphan*/  test_pack_PEMRANGLEARC () ; 
 int /*<<< orphan*/  test_pack_PEMRARC () ; 
 int /*<<< orphan*/  test_pack_PEMRARCTO () ; 
 int /*<<< orphan*/  test_pack_PEMRBEGINPATH () ; 
 int /*<<< orphan*/  test_pack_PEMRBITBLT () ; 
 int /*<<< orphan*/  test_pack_PEMRCHORD () ; 
 int /*<<< orphan*/  test_pack_PEMRCLOSEFIGURE () ; 
 int /*<<< orphan*/  test_pack_PEMRCREATEBRUSHINDIRECT () ; 
 int /*<<< orphan*/  test_pack_PEMRCREATECOLORSPACE () ; 
 int /*<<< orphan*/  test_pack_PEMRCREATECOLORSPACEW () ; 
 int /*<<< orphan*/  test_pack_PEMRCREATEDIBPATTERNBRUSHPT () ; 
 int /*<<< orphan*/  test_pack_PEMRCREATEMONOBRUSH () ; 
 int /*<<< orphan*/  test_pack_PEMRCREATEPALETTE () ; 
 int /*<<< orphan*/  test_pack_PEMRCREATEPEN () ; 
 int /*<<< orphan*/  test_pack_PEMRDELETECOLORSPACE () ; 
 int /*<<< orphan*/  test_pack_PEMRDELETEOBJECT () ; 
 int /*<<< orphan*/  test_pack_PEMRELLIPSE () ; 
 int /*<<< orphan*/  test_pack_PEMRENDPATH () ; 
 int /*<<< orphan*/  test_pack_PEMREOF () ; 
 int /*<<< orphan*/  test_pack_PEMREXCLUDECLIPRECT () ; 
 int /*<<< orphan*/  test_pack_PEMREXTCREATEFONTINDIRECTW () ; 
 int /*<<< orphan*/  test_pack_PEMREXTCREATEPEN () ; 
 int /*<<< orphan*/  test_pack_PEMREXTFLOODFILL () ; 
 int /*<<< orphan*/  test_pack_PEMREXTSELECTCLIPRGN () ; 
 int /*<<< orphan*/  test_pack_PEMREXTTEXTOUTA () ; 
 int /*<<< orphan*/  test_pack_PEMREXTTEXTOUTW () ; 
 int /*<<< orphan*/  test_pack_PEMRFILLPATH () ; 
 int /*<<< orphan*/  test_pack_PEMRFILLRGN () ; 
 int /*<<< orphan*/  test_pack_PEMRFLATTENPATH () ; 
 int /*<<< orphan*/  test_pack_PEMRFORMAT () ; 
 int /*<<< orphan*/  test_pack_PEMRFRAMERGN () ; 
 int /*<<< orphan*/  test_pack_PEMRGDICOMMENT () ; 
 int /*<<< orphan*/  test_pack_PEMRGLSBOUNDEDRECORD () ; 
 int /*<<< orphan*/  test_pack_PEMRGLSRECORD () ; 
 int /*<<< orphan*/  test_pack_PEMRINTERSECTCLIPRECT () ; 
 int /*<<< orphan*/  test_pack_PEMRINVERTRGN () ; 
 int /*<<< orphan*/  test_pack_PEMRLINETO () ; 
 int /*<<< orphan*/  test_pack_PEMRMASKBLT () ; 
 int /*<<< orphan*/  test_pack_PEMRMODIFYWORLDTRANSFORM () ; 
 int /*<<< orphan*/  test_pack_PEMRMOVETOEX () ; 
 int /*<<< orphan*/  test_pack_PEMROFFSETCLIPRGN () ; 
 int /*<<< orphan*/  test_pack_PEMRPAINTRGN () ; 
 int /*<<< orphan*/  test_pack_PEMRPIE () ; 
 int /*<<< orphan*/  test_pack_PEMRPIXELFORMAT () ; 
 int /*<<< orphan*/  test_pack_PEMRPLGBLT () ; 
 int /*<<< orphan*/  test_pack_PEMRPOLYBEZIER () ; 
 int /*<<< orphan*/  test_pack_PEMRPOLYBEZIER16 () ; 
 int /*<<< orphan*/  test_pack_PEMRPOLYBEZIERTO () ; 
 int /*<<< orphan*/  test_pack_PEMRPOLYBEZIERTO16 () ; 
 int /*<<< orphan*/  test_pack_PEMRPOLYDRAW () ; 
 int /*<<< orphan*/  test_pack_PEMRPOLYDRAW16 () ; 
 int /*<<< orphan*/  test_pack_PEMRPOLYGON () ; 
 int /*<<< orphan*/  test_pack_PEMRPOLYGON16 () ; 
 int /*<<< orphan*/  test_pack_PEMRPOLYLINE () ; 
 int /*<<< orphan*/  test_pack_PEMRPOLYLINE16 () ; 
 int /*<<< orphan*/  test_pack_PEMRPOLYLINETO () ; 
 int /*<<< orphan*/  test_pack_PEMRPOLYLINETO16 () ; 
 int /*<<< orphan*/  test_pack_PEMRPOLYPOLYGON () ; 
 int /*<<< orphan*/  test_pack_PEMRPOLYPOLYGON16 () ; 
 int /*<<< orphan*/  test_pack_PEMRPOLYPOLYLINE () ; 
 int /*<<< orphan*/  test_pack_PEMRPOLYPOLYLINE16 () ; 
 int /*<<< orphan*/  test_pack_PEMRPOLYTEXTOUTA () ; 
 int /*<<< orphan*/  test_pack_PEMRPOLYTEXTOUTW () ; 
 int /*<<< orphan*/  test_pack_PEMRREALIZEPALETTE () ; 
 int /*<<< orphan*/  test_pack_PEMRRECTANGLE () ; 
 int /*<<< orphan*/  test_pack_PEMRRESIZEPALETTE () ; 
 int /*<<< orphan*/  test_pack_PEMRRESTOREDC () ; 
 int /*<<< orphan*/  test_pack_PEMRROUNDRECT () ; 
 int /*<<< orphan*/  test_pack_PEMRSAVEDC () ; 
 int /*<<< orphan*/  test_pack_PEMRSCALEVIEWPORTEXTEX () ; 
 int /*<<< orphan*/  test_pack_PEMRSCALEWINDOWEXTEX () ; 
 int /*<<< orphan*/  test_pack_PEMRSELECTCLIPPATH () ; 
 int /*<<< orphan*/  test_pack_PEMRSELECTCOLORSPACE () ; 
 int /*<<< orphan*/  test_pack_PEMRSELECTOBJECT () ; 
 int /*<<< orphan*/  test_pack_PEMRSELECTPALETTE () ; 
 int /*<<< orphan*/  test_pack_PEMRSETARCDIRECTION () ; 
 int /*<<< orphan*/  test_pack_PEMRSETBKCOLOR () ; 
 int /*<<< orphan*/  test_pack_PEMRSETBKMODE () ; 
 int /*<<< orphan*/  test_pack_PEMRSETBRUSHORGEX () ; 
 int /*<<< orphan*/  test_pack_PEMRSETCOLORADJUSTMENT () ; 
 int /*<<< orphan*/  test_pack_PEMRSETCOLORSPACE () ; 
 int /*<<< orphan*/  test_pack_PEMRSETDIBITSTODEVICE () ; 
 int /*<<< orphan*/  test_pack_PEMRSETICMMODE () ; 
 int /*<<< orphan*/  test_pack_PEMRSETLAYOUT () ; 
 int /*<<< orphan*/  test_pack_PEMRSETMAPMODE () ; 
 int /*<<< orphan*/  test_pack_PEMRSETMAPPERFLAGS () ; 
 int /*<<< orphan*/  test_pack_PEMRSETMETARGN () ; 
 int /*<<< orphan*/  test_pack_PEMRSETMITERLIMIT () ; 
 int /*<<< orphan*/  test_pack_PEMRSETPALETTEENTRIES () ; 
 int /*<<< orphan*/  test_pack_PEMRSETPIXELV () ; 
 int /*<<< orphan*/  test_pack_PEMRSETPOLYFILLMODE () ; 
 int /*<<< orphan*/  test_pack_PEMRSETROP2 () ; 
 int /*<<< orphan*/  test_pack_PEMRSETSTRETCHBLTMODE () ; 
 int /*<<< orphan*/  test_pack_PEMRSETTEXTALIGN () ; 
 int /*<<< orphan*/  test_pack_PEMRSETTEXTCOLOR () ; 
 int /*<<< orphan*/  test_pack_PEMRSETVIEWPORTEXTEX () ; 
 int /*<<< orphan*/  test_pack_PEMRSETVIEWPORTORGEX () ; 
 int /*<<< orphan*/  test_pack_PEMRSETWINDOWEXTEX () ; 
 int /*<<< orphan*/  test_pack_PEMRSETWINDOWORGEX () ; 
 int /*<<< orphan*/  test_pack_PEMRSETWORLDTRANSFORM () ; 
 int /*<<< orphan*/  test_pack_PEMRSTRETCHBLT () ; 
 int /*<<< orphan*/  test_pack_PEMRSTRETCHDIBITS () ; 
 int /*<<< orphan*/  test_pack_PEMRSTROKEANDFILLPATH () ; 
 int /*<<< orphan*/  test_pack_PEMRSTROKEPATH () ; 
 int /*<<< orphan*/  test_pack_PEMRTEXT () ; 
 int /*<<< orphan*/  test_pack_PEMRWIDENPATH () ; 
 int /*<<< orphan*/  test_pack_PENHMETAHEADER () ; 
 int /*<<< orphan*/  test_pack_PEXTLOGFONTA () ; 
 int /*<<< orphan*/  test_pack_PEXTLOGFONTW () ; 
 int /*<<< orphan*/  test_pack_PEXTLOGPEN () ; 
 int /*<<< orphan*/  test_pack_PFONTSIGNATURE () ; 
 int /*<<< orphan*/  test_pack_PGLYPHMETRICSFLOAT () ; 
 int /*<<< orphan*/  test_pack_PGRADIENT_RECT () ; 
 int /*<<< orphan*/  test_pack_PGRADIENT_TRIANGLE () ; 
 int /*<<< orphan*/  test_pack_PHANDLETABLE () ; 
 int /*<<< orphan*/  test_pack_PIXELFORMATDESCRIPTOR () ; 
 int /*<<< orphan*/  test_pack_PLAYERPLANEDESCRIPTOR () ; 
 int /*<<< orphan*/  test_pack_PLOCALESIGNATURE () ; 
 int /*<<< orphan*/  test_pack_PLOGBRUSH () ; 
 int /*<<< orphan*/  test_pack_PLOGFONTA () ; 
 int /*<<< orphan*/  test_pack_PLOGFONTW () ; 
 int /*<<< orphan*/  test_pack_PMETAHEADER () ; 
 int /*<<< orphan*/  test_pack_PMETARECORD () ; 
 int /*<<< orphan*/  test_pack_PNEWTEXTMETRICA () ; 
 int /*<<< orphan*/  test_pack_PNEWTEXTMETRICW () ; 
 int /*<<< orphan*/  test_pack_POINTFLOAT () ; 
 int /*<<< orphan*/  test_pack_POINTFX () ; 
 int /*<<< orphan*/  test_pack_POLYTEXTA () ; 
 int /*<<< orphan*/  test_pack_POLYTEXTW () ; 
 int /*<<< orphan*/  test_pack_POUTLINETEXTMETRICA () ; 
 int /*<<< orphan*/  test_pack_POUTLINETEXTMETRICW () ; 
 int /*<<< orphan*/  test_pack_PPELARRAY () ; 
 int /*<<< orphan*/  test_pack_PPIXELFORMATDESCRIPTOR () ; 
 int /*<<< orphan*/  test_pack_PPOINTFLOAT () ; 
 int /*<<< orphan*/  test_pack_PPOLYTEXTA () ; 
 int /*<<< orphan*/  test_pack_PPOLYTEXTW () ; 
 int /*<<< orphan*/  test_pack_PRGNDATA () ; 
 int /*<<< orphan*/  test_pack_PRGNDATAHEADER () ; 
 int /*<<< orphan*/  test_pack_PTEXTMETRICA () ; 
 int /*<<< orphan*/  test_pack_PTEXTMETRICW () ; 
 int /*<<< orphan*/  test_pack_PTRIVERTEX () ; 
 int /*<<< orphan*/  test_pack_PXFORM () ; 
 int /*<<< orphan*/  test_pack_RASTERIZER_STATUS () ; 
 int /*<<< orphan*/  test_pack_RGBQUAD () ; 
 int /*<<< orphan*/  test_pack_RGBTRIPLE () ; 
 int /*<<< orphan*/  test_pack_RGNDATA () ; 
 int /*<<< orphan*/  test_pack_RGNDATAHEADER () ; 
 int /*<<< orphan*/  test_pack_TEXTMETRICA () ; 
 int /*<<< orphan*/  test_pack_TEXTMETRICW () ; 
 int /*<<< orphan*/  test_pack_TRIVERTEX () ; 
 int /*<<< orphan*/  test_pack_TTPOLYCURVE () ; 
 int /*<<< orphan*/  test_pack_TTPOLYGONHEADER () ; 
 int /*<<< orphan*/  test_pack_XFORM () ; 

__attribute__((used)) static void test_pack(void)
{
    test_pack_ABC();
    test_pack_ABCFLOAT();
    test_pack_ABORTPROC();
    test_pack_BITMAP();
    test_pack_BITMAPCOREHEADER();
    test_pack_BITMAPCOREINFO();
    test_pack_BITMAPFILEHEADER();
    test_pack_BITMAPINFO();
    test_pack_BITMAPINFOHEADER();
    test_pack_BITMAPV4HEADER();
    test_pack_BITMAPV5HEADER();
    test_pack_BLENDFUNCTION();
    test_pack_CHARSETINFO();
    test_pack_CIEXYZ();
    test_pack_CIEXYZTRIPLE();
    test_pack_COLOR16();
    test_pack_COLORADJUSTMENT();
    test_pack_DEVMODEA();
    test_pack_DEVMODEW();
    test_pack_DIBSECTION();
    test_pack_DISPLAY_DEVICEA();
    test_pack_DISPLAY_DEVICEW();
    test_pack_DOCINFOA();
    test_pack_DOCINFOW();
    test_pack_EMR();
    test_pack_EMRABORTPATH();
    test_pack_EMRANGLEARC();
    test_pack_EMRARC();
    test_pack_EMRARCTO();
    test_pack_EMRBEGINPATH();
    test_pack_EMRBITBLT();
    test_pack_EMRCHORD();
    test_pack_EMRCLOSEFIGURE();
    test_pack_EMRCREATEBRUSHINDIRECT();
    test_pack_EMRCREATECOLORSPACE();
    test_pack_EMRCREATECOLORSPACEW();
    test_pack_EMRCREATEDIBPATTERNBRUSHPT();
    test_pack_EMRCREATEMONOBRUSH();
    test_pack_EMRCREATEPEN();
    test_pack_EMRDELETECOLORSPACE();
    test_pack_EMRDELETEOBJECT();
    test_pack_EMRELLIPSE();
    test_pack_EMRENDPATH();
    test_pack_EMREOF();
    test_pack_EMREXCLUDECLIPRECT();
    test_pack_EMREXTCREATEFONTINDIRECTW();
    test_pack_EMREXTCREATEPEN();
    test_pack_EMREXTFLOODFILL();
    test_pack_EMREXTSELECTCLIPRGN();
    test_pack_EMREXTTEXTOUTA();
    test_pack_EMREXTTEXTOUTW();
    test_pack_EMRFILLPATH();
    test_pack_EMRFILLRGN();
    test_pack_EMRFLATTENPATH();
    test_pack_EMRFORMAT();
    test_pack_EMRFRAMERGN();
    test_pack_EMRGDICOMMENT();
    test_pack_EMRGLSBOUNDEDRECORD();
    test_pack_EMRGLSRECORD();
    test_pack_EMRINTERSECTCLIPRECT();
    test_pack_EMRINVERTRGN();
    test_pack_EMRLINETO();
    test_pack_EMRMASKBLT();
    test_pack_EMRMODIFYWORLDTRANSFORM();
    test_pack_EMRMOVETOEX();
    test_pack_EMROFFSETCLIPRGN();
    test_pack_EMRPAINTRGN();
    test_pack_EMRPIE();
    test_pack_EMRPIXELFORMAT();
    test_pack_EMRPLGBLT();
    test_pack_EMRPOLYBEZIER();
    test_pack_EMRPOLYBEZIER16();
    test_pack_EMRPOLYBEZIERTO();
    test_pack_EMRPOLYBEZIERTO16();
    test_pack_EMRPOLYDRAW();
    test_pack_EMRPOLYDRAW16();
    test_pack_EMRPOLYGON();
    test_pack_EMRPOLYGON16();
    test_pack_EMRPOLYLINE();
    test_pack_EMRPOLYLINE16();
    test_pack_EMRPOLYLINETO();
    test_pack_EMRPOLYLINETO16();
    test_pack_EMRPOLYPOLYGON();
    test_pack_EMRPOLYPOLYGON16();
    test_pack_EMRPOLYPOLYLINE();
    test_pack_EMRPOLYPOLYLINE16();
    test_pack_EMRPOLYTEXTOUTA();
    test_pack_EMRPOLYTEXTOUTW();
    test_pack_EMRREALIZEPALETTE();
    test_pack_EMRRECTANGLE();
    test_pack_EMRRESIZEPALETTE();
    test_pack_EMRRESTOREDC();
    test_pack_EMRROUNDRECT();
    test_pack_EMRSAVEDC();
    test_pack_EMRSCALEVIEWPORTEXTEX();
    test_pack_EMRSCALEWINDOWEXTEX();
    test_pack_EMRSELECTCLIPPATH();
    test_pack_EMRSELECTCOLORSPACE();
    test_pack_EMRSELECTOBJECT();
    test_pack_EMRSELECTPALETTE();
    test_pack_EMRSETARCDIRECTION();
    test_pack_EMRSETBKCOLOR();
    test_pack_EMRSETBKMODE();
    test_pack_EMRSETBRUSHORGEX();
    test_pack_EMRSETCOLORADJUSTMENT();
    test_pack_EMRSETCOLORSPACE();
    test_pack_EMRSETDIBITSTODEVICE();
    test_pack_EMRSETICMMODE();
    test_pack_EMRSETLAYOUT();
    test_pack_EMRSETMAPMODE();
    test_pack_EMRSETMAPPERFLAGS();
    test_pack_EMRSETMETARGN();
    test_pack_EMRSETMITERLIMIT();
    test_pack_EMRSETPIXELV();
    test_pack_EMRSETPOLYFILLMODE();
    test_pack_EMRSETROP2();
    test_pack_EMRSETSTRETCHBLTMODE();
    test_pack_EMRSETTEXTALIGN();
    test_pack_EMRSETTEXTCOLOR();
    test_pack_EMRSETVIEWPORTEXTEX();
    test_pack_EMRSETVIEWPORTORGEX();
    test_pack_EMRSETWINDOWEXTEX();
    test_pack_EMRSETWINDOWORGEX();
    test_pack_EMRSETWORLDTRANSFORM();
    test_pack_EMRSTRETCHBLT();
    test_pack_EMRSTRETCHDIBITS();
    test_pack_EMRSTROKEANDFILLPATH();
    test_pack_EMRSTROKEPATH();
    test_pack_EMRTEXT();
    test_pack_EMRWIDENPATH();
    test_pack_ENHMETAHEADER();
    test_pack_ENHMETARECORD();
    test_pack_ENHMFENUMPROC();
    test_pack_ENUMLOGFONTA();
    test_pack_ENUMLOGFONTEXA();
    test_pack_ENUMLOGFONTEXW();
    test_pack_ENUMLOGFONTW();
    test_pack_EXTLOGFONTA();
    test_pack_EXTLOGFONTW();
    test_pack_EXTLOGPEN();
    test_pack_FIXED();
    test_pack_FONTENUMPROCA();
    test_pack_FONTENUMPROCW();
    test_pack_FONTSIGNATURE();
    test_pack_FXPT16DOT16();
    test_pack_FXPT2DOT30();
    test_pack_GCP_RESULTSA();
    test_pack_GCP_RESULTSW();
    test_pack_GLYPHMETRICS();
    test_pack_GLYPHMETRICSFLOAT();
    test_pack_GOBJENUMPROC();
    test_pack_GRADIENT_RECT();
    test_pack_GRADIENT_TRIANGLE();
    test_pack_HANDLETABLE();
    test_pack_ICMENUMPROCA();
    test_pack_ICMENUMPROCW();
    test_pack_KERNINGPAIR();
    test_pack_LAYERPLANEDESCRIPTOR();
    test_pack_LCSCSTYPE();
    test_pack_LCSGAMUTMATCH();
    test_pack_LINEDDAPROC();
    test_pack_LOCALESIGNATURE();
    test_pack_LOGBRUSH();
    test_pack_LOGCOLORSPACEA();
    test_pack_LOGCOLORSPACEW();
    test_pack_LOGFONTA();
    test_pack_LOGFONTW();
    test_pack_LOGPEN();
    test_pack_LPABC();
    test_pack_LPABCFLOAT();
    test_pack_LPBITMAP();
    test_pack_LPBITMAPCOREHEADER();
    test_pack_LPBITMAPCOREINFO();
    test_pack_LPBITMAPFILEHEADER();
    test_pack_LPBITMAPINFO();
    test_pack_LPBITMAPINFOHEADER();
    test_pack_LPBITMAPV5HEADER();
    test_pack_LPCHARSETINFO();
    test_pack_LPCIEXYZ();
    test_pack_LPCIEXYZTRIPLE();
    test_pack_LPCOLORADJUSTMENT();
    test_pack_LPDEVMODEA();
    test_pack_LPDEVMODEW();
    test_pack_LPDIBSECTION();
    test_pack_LPDISPLAY_DEVICEA();
    test_pack_LPDISPLAY_DEVICEW();
    test_pack_LPDOCINFOA();
    test_pack_LPDOCINFOW();
    test_pack_LPENHMETAHEADER();
    test_pack_LPENHMETARECORD();
    test_pack_LPENUMLOGFONTA();
    test_pack_LPENUMLOGFONTEXA();
    test_pack_LPENUMLOGFONTEXW();
    test_pack_LPENUMLOGFONTW();
    test_pack_LPEXTLOGFONTA();
    test_pack_LPEXTLOGFONTW();
    test_pack_LPEXTLOGPEN();
    test_pack_LPFONTSIGNATURE();
    test_pack_LPGCP_RESULTSA();
    test_pack_LPGCP_RESULTSW();
    test_pack_LPGLYPHMETRICS();
    test_pack_LPGLYPHMETRICSFLOAT();
    test_pack_LPGRADIENT_RECT();
    test_pack_LPGRADIENT_TRIANGLE();
    test_pack_LPHANDLETABLE();
    test_pack_LPKERNINGPAIR();
    test_pack_LPLAYERPLANEDESCRIPTOR();
    test_pack_LPLOCALESIGNATURE();
    test_pack_LPLOGBRUSH();
    test_pack_LPLOGCOLORSPACEA();
    test_pack_LPLOGCOLORSPACEW();
    test_pack_LPLOGFONTA();
    test_pack_LPLOGFONTW();
    test_pack_LPLOGPEN();
    test_pack_LPMAT2();
    test_pack_LPMETAFILEPICT();
    test_pack_LPMETAHEADER();
    test_pack_LPMETARECORD();
    test_pack_LPNEWTEXTMETRICA();
    test_pack_LPNEWTEXTMETRICW();
    test_pack_LPOUTLINETEXTMETRICA();
    test_pack_LPOUTLINETEXTMETRICW();
    test_pack_LPPANOSE();
    test_pack_LPPELARRAY();
    test_pack_LPPIXELFORMATDESCRIPTOR();
    test_pack_LPPOINTFX();
    test_pack_LPPOLYTEXTA();
    test_pack_LPPOLYTEXTW();
    test_pack_LPRASTERIZER_STATUS();
    test_pack_LPRGBQUAD();
    test_pack_LPRGNDATA();
    test_pack_LPTEXTMETRICA();
    test_pack_LPTEXTMETRICW();
    test_pack_LPTRIVERTEX();
    test_pack_LPTTPOLYCURVE();
    test_pack_LPTTPOLYGONHEADER();
    test_pack_LPXFORM();
    test_pack_MAT2();
    test_pack_METAFILEPICT();
    test_pack_METAHEADER();
    test_pack_METARECORD();
    test_pack_MFENUMPROC();
    test_pack_NEWTEXTMETRICA();
    test_pack_NEWTEXTMETRICEXA();
    test_pack_NEWTEXTMETRICEXW();
    test_pack_NEWTEXTMETRICW();
    test_pack_NPEXTLOGPEN();
    test_pack_OLDFONTENUMPROCA();
    test_pack_OLDFONTENUMPROCW();
    test_pack_OUTLINETEXTMETRICA();
    test_pack_OUTLINETEXTMETRICW();
    test_pack_PABC();
    test_pack_PABCFLOAT();
    test_pack_PANOSE();
    test_pack_PATTERN();
    test_pack_PBITMAP();
    test_pack_PBITMAPCOREHEADER();
    test_pack_PBITMAPCOREINFO();
    test_pack_PBITMAPFILEHEADER();
    test_pack_PBITMAPINFO();
    test_pack_PBITMAPINFOHEADER();
    test_pack_PBITMAPV4HEADER();
    test_pack_PBITMAPV5HEADER();
    test_pack_PBLENDFUNCTION();
    test_pack_PCHARSETINFO();
    test_pack_PCOLORADJUSTMENT();
    test_pack_PDEVMODEA();
    test_pack_PDEVMODEW();
    test_pack_PDIBSECTION();
    test_pack_PDISPLAY_DEVICEA();
    test_pack_PDISPLAY_DEVICEW();
    test_pack_PELARRAY();
    test_pack_PEMR();
    test_pack_PEMRABORTPATH();
    test_pack_PEMRANGLEARC();
    test_pack_PEMRARC();
    test_pack_PEMRARCTO();
    test_pack_PEMRBEGINPATH();
    test_pack_PEMRBITBLT();
    test_pack_PEMRCHORD();
    test_pack_PEMRCLOSEFIGURE();
    test_pack_PEMRCREATEBRUSHINDIRECT();
    test_pack_PEMRCREATECOLORSPACE();
    test_pack_PEMRCREATECOLORSPACEW();
    test_pack_PEMRCREATEDIBPATTERNBRUSHPT();
    test_pack_PEMRCREATEMONOBRUSH();
    test_pack_PEMRCREATEPALETTE();
    test_pack_PEMRCREATEPEN();
    test_pack_PEMRDELETECOLORSPACE();
    test_pack_PEMRDELETEOBJECT();
    test_pack_PEMRELLIPSE();
    test_pack_PEMRENDPATH();
    test_pack_PEMREOF();
    test_pack_PEMREXCLUDECLIPRECT();
    test_pack_PEMREXTCREATEFONTINDIRECTW();
    test_pack_PEMREXTCREATEPEN();
    test_pack_PEMREXTFLOODFILL();
    test_pack_PEMREXTSELECTCLIPRGN();
    test_pack_PEMREXTTEXTOUTA();
    test_pack_PEMREXTTEXTOUTW();
    test_pack_PEMRFILLPATH();
    test_pack_PEMRFILLRGN();
    test_pack_PEMRFLATTENPATH();
    test_pack_PEMRFORMAT();
    test_pack_PEMRFRAMERGN();
    test_pack_PEMRGDICOMMENT();
    test_pack_PEMRGLSBOUNDEDRECORD();
    test_pack_PEMRGLSRECORD();
    test_pack_PEMRINTERSECTCLIPRECT();
    test_pack_PEMRINVERTRGN();
    test_pack_PEMRLINETO();
    test_pack_PEMRMASKBLT();
    test_pack_PEMRMODIFYWORLDTRANSFORM();
    test_pack_PEMRMOVETOEX();
    test_pack_PEMROFFSETCLIPRGN();
    test_pack_PEMRPAINTRGN();
    test_pack_PEMRPIE();
    test_pack_PEMRPIXELFORMAT();
    test_pack_PEMRPLGBLT();
    test_pack_PEMRPOLYBEZIER();
    test_pack_PEMRPOLYBEZIER16();
    test_pack_PEMRPOLYBEZIERTO();
    test_pack_PEMRPOLYBEZIERTO16();
    test_pack_PEMRPOLYDRAW();
    test_pack_PEMRPOLYDRAW16();
    test_pack_PEMRPOLYGON();
    test_pack_PEMRPOLYGON16();
    test_pack_PEMRPOLYLINE();
    test_pack_PEMRPOLYLINE16();
    test_pack_PEMRPOLYLINETO();
    test_pack_PEMRPOLYLINETO16();
    test_pack_PEMRPOLYPOLYGON();
    test_pack_PEMRPOLYPOLYGON16();
    test_pack_PEMRPOLYPOLYLINE();
    test_pack_PEMRPOLYPOLYLINE16();
    test_pack_PEMRPOLYTEXTOUTA();
    test_pack_PEMRPOLYTEXTOUTW();
    test_pack_PEMRREALIZEPALETTE();
    test_pack_PEMRRECTANGLE();
    test_pack_PEMRRESIZEPALETTE();
    test_pack_PEMRRESTOREDC();
    test_pack_PEMRROUNDRECT();
    test_pack_PEMRSAVEDC();
    test_pack_PEMRSCALEVIEWPORTEXTEX();
    test_pack_PEMRSCALEWINDOWEXTEX();
    test_pack_PEMRSELECTCLIPPATH();
    test_pack_PEMRSELECTCOLORSPACE();
    test_pack_PEMRSELECTOBJECT();
    test_pack_PEMRSELECTPALETTE();
    test_pack_PEMRSETARCDIRECTION();
    test_pack_PEMRSETBKCOLOR();
    test_pack_PEMRSETBKMODE();
    test_pack_PEMRSETBRUSHORGEX();
    test_pack_PEMRSETCOLORADJUSTMENT();
    test_pack_PEMRSETCOLORSPACE();
    test_pack_PEMRSETDIBITSTODEVICE();
    test_pack_PEMRSETICMMODE();
    test_pack_PEMRSETLAYOUT();
    test_pack_PEMRSETMAPMODE();
    test_pack_PEMRSETMAPPERFLAGS();
    test_pack_PEMRSETMETARGN();
    test_pack_PEMRSETMITERLIMIT();
    test_pack_PEMRSETPALETTEENTRIES();
    test_pack_PEMRSETPIXELV();
    test_pack_PEMRSETPOLYFILLMODE();
    test_pack_PEMRSETROP2();
    test_pack_PEMRSETSTRETCHBLTMODE();
    test_pack_PEMRSETTEXTALIGN();
    test_pack_PEMRSETTEXTCOLOR();
    test_pack_PEMRSETVIEWPORTEXTEX();
    test_pack_PEMRSETVIEWPORTORGEX();
    test_pack_PEMRSETWINDOWEXTEX();
    test_pack_PEMRSETWINDOWORGEX();
    test_pack_PEMRSETWORLDTRANSFORM();
    test_pack_PEMRSTRETCHBLT();
    test_pack_PEMRSTRETCHDIBITS();
    test_pack_PEMRSTROKEANDFILLPATH();
    test_pack_PEMRSTROKEPATH();
    test_pack_PEMRTEXT();
    test_pack_PEMRWIDENPATH();
    test_pack_PENHMETAHEADER();
    test_pack_PEXTLOGFONTA();
    test_pack_PEXTLOGFONTW();
    test_pack_PEXTLOGPEN();
    test_pack_PFONTSIGNATURE();
    test_pack_PGLYPHMETRICSFLOAT();
    test_pack_PGRADIENT_RECT();
    test_pack_PGRADIENT_TRIANGLE();
    test_pack_PHANDLETABLE();
    test_pack_PIXELFORMATDESCRIPTOR();
    test_pack_PLAYERPLANEDESCRIPTOR();
    test_pack_PLOCALESIGNATURE();
    test_pack_PLOGBRUSH();
    test_pack_PLOGFONTA();
    test_pack_PLOGFONTW();
    test_pack_PMETAHEADER();
    test_pack_PMETARECORD();
    test_pack_PNEWTEXTMETRICA();
    test_pack_PNEWTEXTMETRICW();
    test_pack_POINTFLOAT();
    test_pack_POINTFX();
    test_pack_POLYTEXTA();
    test_pack_POLYTEXTW();
    test_pack_POUTLINETEXTMETRICA();
    test_pack_POUTLINETEXTMETRICW();
    test_pack_PPELARRAY();
    test_pack_PPIXELFORMATDESCRIPTOR();
    test_pack_PPOINTFLOAT();
    test_pack_PPOLYTEXTA();
    test_pack_PPOLYTEXTW();
    test_pack_PRGNDATA();
    test_pack_PRGNDATAHEADER();
    test_pack_PTEXTMETRICA();
    test_pack_PTEXTMETRICW();
    test_pack_PTRIVERTEX();
    test_pack_PXFORM();
    test_pack_RASTERIZER_STATUS();
    test_pack_RGBQUAD();
    test_pack_RGBTRIPLE();
    test_pack_RGNDATA();
    test_pack_RGNDATAHEADER();
    test_pack_TEXTMETRICA();
    test_pack_TEXTMETRICW();
    test_pack_TRIVERTEX();
    test_pack_TTPOLYCURVE();
    test_pack_TTPOLYGONHEADER();
    test_pack_XFORM();
}