#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */
typedef  struct TYPE_2__   TYPE_1__ ;

/* Type definitions */
struct TYPE_2__ {void* sharedapi; void* moduleapi; } ;

/* Variables and functions */
 int /*<<< orphan*/  AbortBlock ; 
 int /*<<< orphan*/  Alloc ; 
 int /*<<< orphan*/  AutoMemory ; 
 int /*<<< orphan*/  BlockClient ; 
 int /*<<< orphan*/  BlockClientOnKeys ; 
 int /*<<< orphan*/  BlockedClientDisconnected ; 
 int /*<<< orphan*/  Call ; 
 int /*<<< orphan*/  CallReplyArrayElement ; 
 int /*<<< orphan*/  CallReplyInteger ; 
 int /*<<< orphan*/  CallReplyLength ; 
 int /*<<< orphan*/  CallReplyProto ; 
 int /*<<< orphan*/  CallReplyStringPtr ; 
 int /*<<< orphan*/  CallReplyType ; 
 int /*<<< orphan*/  Calloc ; 
 int /*<<< orphan*/  CloseKey ; 
 int /*<<< orphan*/  CommandFilterArgDelete ; 
 int /*<<< orphan*/  CommandFilterArgGet ; 
 int /*<<< orphan*/  CommandFilterArgInsert ; 
 int /*<<< orphan*/  CommandFilterArgReplace ; 
 int /*<<< orphan*/  CommandFilterArgsCount ; 
 int /*<<< orphan*/  CreateCommand ; 
 int /*<<< orphan*/  CreateDataType ; 
 int /*<<< orphan*/  CreateDict ; 
 int /*<<< orphan*/  CreateString ; 
 int /*<<< orphan*/  CreateStringFromCallReply ; 
 int /*<<< orphan*/  CreateStringFromLongLong ; 
 int /*<<< orphan*/  CreateStringFromString ; 
 int /*<<< orphan*/  CreateStringPrintf ; 
 int /*<<< orphan*/  CreateTimer ; 
 int /*<<< orphan*/  DbSize ; 
 int /*<<< orphan*/  DeleteKey ; 
 int /*<<< orphan*/  DictCompare ; 
 int /*<<< orphan*/  DictCompareC ; 
 int /*<<< orphan*/  DictDel ; 
 int /*<<< orphan*/  DictDelC ; 
 int /*<<< orphan*/  DictGet ; 
 int /*<<< orphan*/  DictGetC ; 
 int /*<<< orphan*/  DictIteratorReseek ; 
 int /*<<< orphan*/  DictIteratorReseekC ; 
 int /*<<< orphan*/  DictIteratorStart ; 
 int /*<<< orphan*/  DictIteratorStartC ; 
 int /*<<< orphan*/  DictIteratorStop ; 
 int /*<<< orphan*/  DictNext ; 
 int /*<<< orphan*/  DictNextC ; 
 int /*<<< orphan*/  DictPrev ; 
 int /*<<< orphan*/  DictPrevC ; 
 int /*<<< orphan*/  DictReplace ; 
 int /*<<< orphan*/  DictReplaceC ; 
 int /*<<< orphan*/  DictSet ; 
 int /*<<< orphan*/  DictSetC ; 
 int /*<<< orphan*/  DictSize ; 
 int /*<<< orphan*/  DigestAddLongLong ; 
 int /*<<< orphan*/  DigestAddStringBuffer ; 
 int /*<<< orphan*/  DigestEndSequence ; 
 int /*<<< orphan*/  EmitAOF ; 
 int /*<<< orphan*/  ExitFromChild ; 
 int /*<<< orphan*/  ExportSharedAPI ; 
 int /*<<< orphan*/  Fork ; 
 int /*<<< orphan*/  Free ; 
 int /*<<< orphan*/  FreeCallReply ; 
 int /*<<< orphan*/  FreeClusterNodesList ; 
 int /*<<< orphan*/  FreeDict ; 
 int /*<<< orphan*/  FreeString ; 
 int /*<<< orphan*/  FreeThreadSafeContext ; 
 int /*<<< orphan*/  GetBlockedClientHandle ; 
 int /*<<< orphan*/  GetBlockedClientPrivateData ; 
 int /*<<< orphan*/  GetBlockedClientReadyKey ; 
 int /*<<< orphan*/  GetClientId ; 
 int /*<<< orphan*/  GetClientInfoById ; 
 int /*<<< orphan*/  GetClusterNodeInfo ; 
 int /*<<< orphan*/  GetClusterNodesList ; 
 int /*<<< orphan*/  GetClusterSize ; 
 int /*<<< orphan*/  GetContextFlags ; 
 int /*<<< orphan*/  GetContextFromIO ; 
 int /*<<< orphan*/  GetExpire ; 
 int /*<<< orphan*/  GetKeyNameFromIO ; 
 int /*<<< orphan*/  GetKeyNameFromModuleKey ; 
 int /*<<< orphan*/  GetLRUOrLFU ; 
 int /*<<< orphan*/  GetMyClusterID ; 
 int /*<<< orphan*/  GetNotifyKeyspaceEvents ; 
 int /*<<< orphan*/  GetRandomBytes ; 
 int /*<<< orphan*/  GetRandomHexChars ; 
 int /*<<< orphan*/  GetSelectedDb ; 
 int /*<<< orphan*/  GetSharedAPI ; 
 int /*<<< orphan*/  GetThreadSafeContext ; 
 int /*<<< orphan*/  GetTimerInfo ; 
 int /*<<< orphan*/  HashGet ; 
 int /*<<< orphan*/  HashSet ; 
 int /*<<< orphan*/  InfoAddFieldCString ; 
 int /*<<< orphan*/  InfoAddFieldDouble ; 
 int /*<<< orphan*/  InfoAddFieldLongLong ; 
 int /*<<< orphan*/  InfoAddFieldString ; 
 int /*<<< orphan*/  InfoAddFieldULongLong ; 
 int /*<<< orphan*/  InfoAddSection ; 
 int /*<<< orphan*/  InfoBeginDictField ; 
 int /*<<< orphan*/  InfoEndDictField ; 
 int /*<<< orphan*/  IsBlockedReplyRequest ; 
 int /*<<< orphan*/  IsBlockedTimeoutRequest ; 
 int /*<<< orphan*/  IsIOError ; 
 int /*<<< orphan*/  IsKeysPositionRequest ; 
 int /*<<< orphan*/  IsModuleNameBusy ; 
 int /*<<< orphan*/  KeyAtPos ; 
 int /*<<< orphan*/  KeyType ; 
 int /*<<< orphan*/  KillForkChild ; 
 int /*<<< orphan*/  LatencyAddSample ; 
 int /*<<< orphan*/  ListPop ; 
 int /*<<< orphan*/  ListPush ; 
 int /*<<< orphan*/  LoadDouble ; 
 int /*<<< orphan*/  LoadFloat ; 
 int /*<<< orphan*/  LoadLongDouble ; 
 int /*<<< orphan*/  LoadSigned ; 
 int /*<<< orphan*/  LoadString ; 
 int /*<<< orphan*/  LoadStringBuffer ; 
 int /*<<< orphan*/  LoadUnsigned ; 
 int /*<<< orphan*/  Log ; 
 int /*<<< orphan*/  LogIOError ; 
 int /*<<< orphan*/  Milliseconds ; 
 int /*<<< orphan*/  ModuleTypeGetType ; 
 int /*<<< orphan*/  ModuleTypeGetValue ; 
 int /*<<< orphan*/  ModuleTypeSetValue ; 
 int /*<<< orphan*/  NotifyKeyspaceEvent ; 
 int /*<<< orphan*/  OpenKey ; 
 int /*<<< orphan*/  PoolAlloc ; 
 int /*<<< orphan*/  PublishMessage ; 
 int /*<<< orphan*/  REGISTER_API (int /*<<< orphan*/ ) ; 
 int /*<<< orphan*/  RandomKey ; 
 int /*<<< orphan*/  Realloc ; 
 int /*<<< orphan*/  RegisterClusterMessageReceiver ; 
 int /*<<< orphan*/  RegisterCommandFilter ; 
 int /*<<< orphan*/  RegisterInfoFunc ; 
 int /*<<< orphan*/  Replicate ; 
 int /*<<< orphan*/  ReplicateVerbatim ; 
 int /*<<< orphan*/  ReplySetArrayLength ; 
 int /*<<< orphan*/  ReplyWithArray ; 
 int /*<<< orphan*/  ReplyWithCString ; 
 int /*<<< orphan*/  ReplyWithCallReply ; 
 int /*<<< orphan*/  ReplyWithDouble ; 
 int /*<<< orphan*/  ReplyWithEmptyArray ; 
 int /*<<< orphan*/  ReplyWithEmptyString ; 
 int /*<<< orphan*/  ReplyWithError ; 
 int /*<<< orphan*/  ReplyWithLongLong ; 
 int /*<<< orphan*/  ReplyWithNull ; 
 int /*<<< orphan*/  ReplyWithNullArray ; 
 int /*<<< orphan*/  ReplyWithSimpleString ; 
 int /*<<< orphan*/  ReplyWithString ; 
 int /*<<< orphan*/  ReplyWithStringBuffer ; 
 int /*<<< orphan*/  ReplyWithVerbatimString ; 
 int /*<<< orphan*/  ResetDataset ; 
 int /*<<< orphan*/  RetainString ; 
 int /*<<< orphan*/  SaveDouble ; 
 int /*<<< orphan*/  SaveFloat ; 
 int /*<<< orphan*/  SaveLongDouble ; 
 int /*<<< orphan*/  SaveSigned ; 
 int /*<<< orphan*/  SaveString ; 
 int /*<<< orphan*/  SaveStringBuffer ; 
 int /*<<< orphan*/  SaveUnsigned ; 
 int /*<<< orphan*/  SelectDb ; 
 int /*<<< orphan*/  SendClusterMessage ; 
 int /*<<< orphan*/  SetClusterFlags ; 
 int /*<<< orphan*/  SetDisconnectCallback ; 
 int /*<<< orphan*/  SetExpire ; 
 int /*<<< orphan*/  SetLRUOrLFU ; 
 int /*<<< orphan*/  SetModuleAttribs ; 
 int /*<<< orphan*/  SetModuleOptions ; 
 int /*<<< orphan*/  SignalKeyAsReady ; 
 int /*<<< orphan*/  SignalModifiedKey ; 
 int /*<<< orphan*/  StopTimer ; 
 int /*<<< orphan*/  Strdup ; 
 int /*<<< orphan*/  StringAppendBuffer ; 
 int /*<<< orphan*/  StringCompare ; 
 int /*<<< orphan*/  StringDMA ; 
 int /*<<< orphan*/  StringPtrLen ; 
 int /*<<< orphan*/  StringSet ; 
 int /*<<< orphan*/  StringToDouble ; 
 int /*<<< orphan*/  StringToLongLong ; 
 int /*<<< orphan*/  StringTruncate ; 
 int /*<<< orphan*/  SubscribeToKeyspaceEvents ; 
 int /*<<< orphan*/  SubscribeToServerEvent ; 
 int /*<<< orphan*/  ThreadSafeContextLock ; 
 int /*<<< orphan*/  ThreadSafeContextUnlock ; 
 int /*<<< orphan*/  UnblockClient ; 
 int /*<<< orphan*/  UnlinkKey ; 
 int /*<<< orphan*/  UnregisterCommandFilter ; 
 int /*<<< orphan*/  ValueLength ; 
 int /*<<< orphan*/  WrongArity ; 
 int /*<<< orphan*/  ZsetAdd ; 
 int /*<<< orphan*/  ZsetFirstInLexRange ; 
 int /*<<< orphan*/  ZsetFirstInScoreRange ; 
 int /*<<< orphan*/  ZsetIncrby ; 
 int /*<<< orphan*/  ZsetLastInLexRange ; 
 int /*<<< orphan*/  ZsetLastInScoreRange ; 
 int /*<<< orphan*/  ZsetRangeCurrentElement ; 
 int /*<<< orphan*/  ZsetRangeEndReached ; 
 int /*<<< orphan*/  ZsetRangeNext ; 
 int /*<<< orphan*/  ZsetRangePrev ; 
 int /*<<< orphan*/  ZsetRangeStop ; 
 int /*<<< orphan*/  ZsetRem ; 
 int /*<<< orphan*/  ZsetScore ; 
 int /*<<< orphan*/  _Assert ; 
 void* dictCreate (int /*<<< orphan*/ *,int /*<<< orphan*/ *) ; 
 int /*<<< orphan*/  moduleAPIDictType ; 
 TYPE_1__ server ; 

void moduleRegisterCoreAPI(void) {
    server.moduleapi = dictCreate(&moduleAPIDictType,NULL);
    server.sharedapi = dictCreate(&moduleAPIDictType,NULL);
    REGISTER_API(Alloc);
    REGISTER_API(Calloc);
    REGISTER_API(Realloc);
    REGISTER_API(Free);
    REGISTER_API(Strdup);
    REGISTER_API(CreateCommand);
    REGISTER_API(SetModuleAttribs);
    REGISTER_API(IsModuleNameBusy);
    REGISTER_API(WrongArity);
    REGISTER_API(ReplyWithLongLong);
    REGISTER_API(ReplyWithError);
    REGISTER_API(ReplyWithSimpleString);
    REGISTER_API(ReplyWithArray);
    REGISTER_API(ReplyWithNullArray);
    REGISTER_API(ReplyWithEmptyArray);
    REGISTER_API(ReplySetArrayLength);
    REGISTER_API(ReplyWithString);
    REGISTER_API(ReplyWithEmptyString);
    REGISTER_API(ReplyWithVerbatimString);
    REGISTER_API(ReplyWithStringBuffer);
    REGISTER_API(ReplyWithCString);
    REGISTER_API(ReplyWithNull);
    REGISTER_API(ReplyWithCallReply);
    REGISTER_API(ReplyWithDouble);
    REGISTER_API(GetSelectedDb);
    REGISTER_API(SelectDb);
    REGISTER_API(OpenKey);
    REGISTER_API(CloseKey);
    REGISTER_API(KeyType);
    REGISTER_API(ValueLength);
    REGISTER_API(ListPush);
    REGISTER_API(ListPop);
    REGISTER_API(StringToLongLong);
    REGISTER_API(StringToDouble);
    REGISTER_API(Call);
    REGISTER_API(CallReplyProto);
    REGISTER_API(FreeCallReply);
    REGISTER_API(CallReplyInteger);
    REGISTER_API(CallReplyType);
    REGISTER_API(CallReplyLength);
    REGISTER_API(CallReplyArrayElement);
    REGISTER_API(CallReplyStringPtr);
    REGISTER_API(CreateStringFromCallReply);
    REGISTER_API(CreateString);
    REGISTER_API(CreateStringFromLongLong);
    REGISTER_API(CreateStringFromString);
    REGISTER_API(CreateStringPrintf);
    REGISTER_API(FreeString);
    REGISTER_API(StringPtrLen);
    REGISTER_API(AutoMemory);
    REGISTER_API(Replicate);
    REGISTER_API(ReplicateVerbatim);
    REGISTER_API(DeleteKey);
    REGISTER_API(UnlinkKey);
    REGISTER_API(StringSet);
    REGISTER_API(StringDMA);
    REGISTER_API(StringTruncate);
    REGISTER_API(SetExpire);
    REGISTER_API(GetExpire);
    REGISTER_API(ResetDataset);
    REGISTER_API(DbSize);
    REGISTER_API(RandomKey);
    REGISTER_API(ZsetAdd);
    REGISTER_API(ZsetIncrby);
    REGISTER_API(ZsetScore);
    REGISTER_API(ZsetRem);
    REGISTER_API(ZsetRangeStop);
    REGISTER_API(ZsetFirstInScoreRange);
    REGISTER_API(ZsetLastInScoreRange);
    REGISTER_API(ZsetFirstInLexRange);
    REGISTER_API(ZsetLastInLexRange);
    REGISTER_API(ZsetRangeCurrentElement);
    REGISTER_API(ZsetRangeNext);
    REGISTER_API(ZsetRangePrev);
    REGISTER_API(ZsetRangeEndReached);
    REGISTER_API(HashSet);
    REGISTER_API(HashGet);
    REGISTER_API(IsKeysPositionRequest);
    REGISTER_API(KeyAtPos);
    REGISTER_API(GetClientId);
    REGISTER_API(GetContextFlags);
    REGISTER_API(PoolAlloc);
    REGISTER_API(CreateDataType);
    REGISTER_API(ModuleTypeSetValue);
    REGISTER_API(ModuleTypeGetType);
    REGISTER_API(ModuleTypeGetValue);
    REGISTER_API(IsIOError);
    REGISTER_API(SetModuleOptions);
    REGISTER_API(SignalModifiedKey);
    REGISTER_API(SaveUnsigned);
    REGISTER_API(LoadUnsigned);
    REGISTER_API(SaveSigned);
    REGISTER_API(LoadSigned);
    REGISTER_API(SaveString);
    REGISTER_API(SaveStringBuffer);
    REGISTER_API(LoadString);
    REGISTER_API(LoadStringBuffer);
    REGISTER_API(SaveDouble);
    REGISTER_API(LoadDouble);
    REGISTER_API(SaveFloat);
    REGISTER_API(LoadFloat);
    REGISTER_API(SaveLongDouble);
    REGISTER_API(LoadLongDouble);
    REGISTER_API(EmitAOF);
    REGISTER_API(Log);
    REGISTER_API(LogIOError);
    REGISTER_API(_Assert);
    REGISTER_API(LatencyAddSample);
    REGISTER_API(StringAppendBuffer);
    REGISTER_API(RetainString);
    REGISTER_API(StringCompare);
    REGISTER_API(GetContextFromIO);
    REGISTER_API(GetKeyNameFromIO);
    REGISTER_API(GetKeyNameFromModuleKey);
    REGISTER_API(BlockClient);
    REGISTER_API(UnblockClient);
    REGISTER_API(IsBlockedReplyRequest);
    REGISTER_API(IsBlockedTimeoutRequest);
    REGISTER_API(GetBlockedClientPrivateData);
    REGISTER_API(AbortBlock);
    REGISTER_API(Milliseconds);
    REGISTER_API(GetThreadSafeContext);
    REGISTER_API(FreeThreadSafeContext);
    REGISTER_API(ThreadSafeContextLock);
    REGISTER_API(ThreadSafeContextUnlock);
    REGISTER_API(DigestAddStringBuffer);
    REGISTER_API(DigestAddLongLong);
    REGISTER_API(DigestEndSequence);
    REGISTER_API(NotifyKeyspaceEvent);
    REGISTER_API(GetNotifyKeyspaceEvents);
    REGISTER_API(SubscribeToKeyspaceEvents);
    REGISTER_API(RegisterClusterMessageReceiver);
    REGISTER_API(SendClusterMessage);
    REGISTER_API(GetClusterNodeInfo);
    REGISTER_API(GetClusterNodesList);
    REGISTER_API(FreeClusterNodesList);
    REGISTER_API(CreateTimer);
    REGISTER_API(StopTimer);
    REGISTER_API(GetTimerInfo);
    REGISTER_API(GetMyClusterID);
    REGISTER_API(GetClusterSize);
    REGISTER_API(GetRandomBytes);
    REGISTER_API(GetRandomHexChars);
    REGISTER_API(BlockedClientDisconnected);
    REGISTER_API(SetDisconnectCallback);
    REGISTER_API(GetBlockedClientHandle);
    REGISTER_API(SetClusterFlags);
    REGISTER_API(CreateDict);
    REGISTER_API(FreeDict);
    REGISTER_API(DictSize);
    REGISTER_API(DictSetC);
    REGISTER_API(DictReplaceC);
    REGISTER_API(DictSet);
    REGISTER_API(DictReplace);
    REGISTER_API(DictGetC);
    REGISTER_API(DictGet);
    REGISTER_API(DictDelC);
    REGISTER_API(DictDel);
    REGISTER_API(DictIteratorStartC);
    REGISTER_API(DictIteratorStart);
    REGISTER_API(DictIteratorStop);
    REGISTER_API(DictIteratorReseekC);
    REGISTER_API(DictIteratorReseek);
    REGISTER_API(DictNextC);
    REGISTER_API(DictPrevC);
    REGISTER_API(DictNext);
    REGISTER_API(DictPrev);
    REGISTER_API(DictCompareC);
    REGISTER_API(DictCompare);
    REGISTER_API(ExportSharedAPI);
    REGISTER_API(GetSharedAPI);
    REGISTER_API(RegisterCommandFilter);
    REGISTER_API(UnregisterCommandFilter);
    REGISTER_API(CommandFilterArgsCount);
    REGISTER_API(CommandFilterArgGet);
    REGISTER_API(CommandFilterArgInsert);
    REGISTER_API(CommandFilterArgReplace);
    REGISTER_API(CommandFilterArgDelete);
    REGISTER_API(Fork);
    REGISTER_API(ExitFromChild);
    REGISTER_API(KillForkChild);
    REGISTER_API(RegisterInfoFunc);
    REGISTER_API(InfoAddSection);
    REGISTER_API(InfoBeginDictField);
    REGISTER_API(InfoEndDictField);
    REGISTER_API(InfoAddFieldString);
    REGISTER_API(InfoAddFieldCString);
    REGISTER_API(InfoAddFieldDouble);
    REGISTER_API(InfoAddFieldLongLong);
    REGISTER_API(InfoAddFieldULongLong);
    REGISTER_API(GetClientInfoById);
    REGISTER_API(PublishMessage);
    REGISTER_API(SubscribeToServerEvent);
    REGISTER_API(SetLRUOrLFU);
    REGISTER_API(GetLRUOrLFU);
    REGISTER_API(BlockClientOnKeys);
    REGISTER_API(SignalKeyAsReady);
    REGISTER_API(GetBlockedClientReadyKey);
}