#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
struct device {int dummy; } ;

/* Variables and functions */
#define  AFE_ADD6A_UL_SRC_MON0 265 
#define  AFE_ADDA6_SRC_DEBUG_MON0 264 
#define  AFE_ADDA6_UL_SRC_MON1 263 
#define  AFE_ADDA_DL_SDM_FIFO_MON 262 
#define  AFE_ADDA_DL_SDM_OUT_MON 261 
#define  AFE_ADDA_DL_SRC_LCH_MON 260 
#define  AFE_ADDA_DL_SRC_RCH_MON 259 
#define  AFE_ADDA_MTKAIF_MON0 258 
#define  AFE_ADDA_MTKAIF_MON1 257 
#define  AFE_ADDA_SRC_DEBUG_MON0 256 
#define  AFE_ADDA_SRC_DEBUG_MON1 255 
#define  AFE_ADDA_UL_SRC_MON0 254 
#define  AFE_ADDA_UL_SRC_MON1 253 
#define  AFE_ASRC_2CH_CON0 252 
#define  AFE_ASRC_2CH_CON12 251 
#define  AFE_ASRC_2CH_CON13 250 
#define  AFE_ASRC_2CH_CON2 249 
#define  AFE_ASRC_2CH_CON3 248 
#define  AFE_ASRC_2CH_CON4 247 
#define  AFE_ASRC_2CH_CON5 246 
#define  AFE_ASRC_2CH_CON7 245 
#define  AFE_ASRC_2CH_CON8 244 
#define  AFE_AUD_PAD_TOP 243 
#define  AFE_AWB2_CUR 242 
#define  AFE_AWB2_CUR_MSB 241 
#define  AFE_AWB2_END 240 
#define  AFE_AWB_CUR 239 
#define  AFE_AWB_CUR_MSB 238 
#define  AFE_AWB_END 237 
#define  AFE_BUS_MON0 236 
#define  AFE_CBIP_MON0 235 
#define  AFE_CBIP_SLV_DECODER_MON0 234 
#define  AFE_CBIP_SLV_MUX_MON0 233 
#define  AFE_CONNSYS_I2S_MON 232 
#define  AFE_DAC_MON 231 
#define  AFE_DL1_CUR 230 
#define  AFE_DL1_CUR_MSB 229 
#define  AFE_DL1_END 228 
#define  AFE_DL2_CUR 227 
#define  AFE_DL2_CUR_MSB 226 
#define  AFE_DL2_END 225 
#define  AFE_DL3_CUR 224 
#define  AFE_DL3_CUR_MSB 223 
#define  AFE_DL3_END 222 
#define  AFE_GAIN1_CUR 221 
#define  AFE_GAIN2_CUR 220 
#define  AFE_GENERAL1_ASRC_2CH_CON0 219 
#define  AFE_GENERAL1_ASRC_2CH_CON12 218 
#define  AFE_GENERAL1_ASRC_2CH_CON13 217 
#define  AFE_GENERAL1_ASRC_2CH_CON2 216 
#define  AFE_GENERAL1_ASRC_2CH_CON3 215 
#define  AFE_GENERAL1_ASRC_2CH_CON4 214 
#define  AFE_GENERAL1_ASRC_2CH_CON5 213 
#define  AFE_GENERAL1_ASRC_2CH_CON7 212 
#define  AFE_GENERAL1_ASRC_2CH_CON8 211 
#define  AFE_GENERAL2_ASRC_2CH_CON0 210 
#define  AFE_GENERAL2_ASRC_2CH_CON12 209 
#define  AFE_GENERAL2_ASRC_2CH_CON13 208 
#define  AFE_GENERAL2_ASRC_2CH_CON2 207 
#define  AFE_GENERAL2_ASRC_2CH_CON3 206 
#define  AFE_GENERAL2_ASRC_2CH_CON4 205 
#define  AFE_GENERAL2_ASRC_2CH_CON5 204 
#define  AFE_GENERAL2_ASRC_2CH_CON7 203 
#define  AFE_GENERAL2_ASRC_2CH_CON8 202 
#define  AFE_HDMI_OUT_CON0 201 
#define  AFE_HDMI_OUT_CUR 200 
#define  AFE_HDMI_OUT_CUR_MSB 199 
#define  AFE_HDMI_OUT_END 198 
#define  AFE_I2S_MON 197 
#define  AFE_IRQ0_MCU_CNT_MON 196 
#define  AFE_IRQ11_MCU_CNT_MON 195 
#define  AFE_IRQ12_MCU_CNT_MON 194 
#define  AFE_IRQ1_MCU_CNT_MON 193 
#define  AFE_IRQ1_MCU_EN_CNT_MON 192 
#define  AFE_IRQ2_MCU_CNT_MON 191 
#define  AFE_IRQ3_MCU_CNT_MON 190 
#define  AFE_IRQ4_MCU_CNT_MON 189 
#define  AFE_IRQ5_MCU_CNT_MON 188 
#define  AFE_IRQ6_MCU_CNT_MON 187 
#define  AFE_IRQ7_MCU_CNT_MON 186 
#define  AFE_IRQ8_MCU_CNT_MON 185 
#define  AFE_IRQ_MCU_CLR 184 
#define  AFE_IRQ_MCU_MON2 183 
#define  AFE_IRQ_MCU_STATUS 182 
#define  AFE_MEMIF_MON0 181 
#define  AFE_MEMIF_MON1 180 
#define  AFE_MEMIF_MON12 179 
#define  AFE_MEMIF_MON13 178 
#define  AFE_MEMIF_MON14 177 
#define  AFE_MEMIF_MON15 176 
#define  AFE_MEMIF_MON16 175 
#define  AFE_MEMIF_MON17 174 
#define  AFE_MEMIF_MON18 173 
#define  AFE_MEMIF_MON19 172 
#define  AFE_MEMIF_MON2 171 
#define  AFE_MEMIF_MON20 170 
#define  AFE_MEMIF_MON21 169 
#define  AFE_MEMIF_MON22 168 
#define  AFE_MEMIF_MON23 167 
#define  AFE_MEMIF_MON24 166 
#define  AFE_MEMIF_MON3 165 
#define  AFE_MEMIF_MON4 164 
#define  AFE_MEMIF_MON5 163 
#define  AFE_MEMIF_MON6 162 
#define  AFE_MEMIF_MON7 161 
#define  AFE_MEMIF_MON8 160 
#define  AFE_MEMIF_MON9 159 
#define  AFE_MOD_DAI_CUR 158 
#define  AFE_MOD_DAI_CUR_MSB 157 
#define  AFE_MOD_DAI_END 156 
#define  AFE_MRGIF_MON0 155 
#define  AFE_MRGIF_MON1 154 
#define  AFE_MRGIF_MON2 153 
#define  AFE_SIDETONE_COEFF 152 
#define  AFE_SIDETONE_CON0 151 
#define  AFE_SIDETONE_MON 150 
#define  AFE_SRAM_DELSEL_CON0 149 
#define  AFE_SRAM_DELSEL_CON2 148 
#define  AFE_SRAM_DELSEL_CON3 147 
#define  AFE_VUL2_CUR 146 
#define  AFE_VUL2_CUR_MSB 145 
#define  AFE_VUL2_END 144 
#define  AFE_VUL_CUR 143 
#define  AFE_VUL_CUR_MSB 142 
#define  AFE_VUL_D2_CUR 141 
#define  AFE_VUL_D2_CUR_MSB 140 
#define  AFE_VUL_D2_END 139 
#define  AFE_VUL_END 138 
#define  AUDIO_TOP_CON0 137 
#define  AUDIO_TOP_CON1 136 
#define  AUDIO_TOP_CON3 135 
#define  AUDIO_TOP_DBG_MON0 134 
#define  AUDIO_TOP_DBG_MON1 133 
#define  FPGA_CFG0 132 
#define  FPGA_CFG1 131 
#define  FPGA_CFG2 130 
#define  FPGA_CFG3 129 
#define  PCM_INTF_CON2 128 

__attribute__((used)) static bool mt8183_is_volatile_reg(struct device *dev, unsigned int reg)
{
	/* these auto-gen reg has read-only bit, so put it as volatile */
	/* volatile reg cannot be cached, so cannot be set when power off */
	switch (reg) {
	case AUDIO_TOP_CON0:	/* reg bit controlled by CCF */
	case AUDIO_TOP_CON1:	/* reg bit controlled by CCF */
	case AUDIO_TOP_CON3:
	case AFE_DL1_CUR:
	case AFE_DL1_END:
	case AFE_DL2_CUR:
	case AFE_DL2_END:
	case AFE_AWB_END:
	case AFE_AWB_CUR:
	case AFE_VUL_END:
	case AFE_VUL_CUR:
	case AFE_MEMIF_MON0:
	case AFE_MEMIF_MON1:
	case AFE_MEMIF_MON2:
	case AFE_MEMIF_MON3:
	case AFE_MEMIF_MON4:
	case AFE_MEMIF_MON5:
	case AFE_MEMIF_MON6:
	case AFE_MEMIF_MON7:
	case AFE_MEMIF_MON8:
	case AFE_MEMIF_MON9:
	case AFE_ADDA_SRC_DEBUG_MON0:
	case AFE_ADDA_SRC_DEBUG_MON1:
	case AFE_ADDA_UL_SRC_MON0:
	case AFE_ADDA_UL_SRC_MON1:
	case AFE_SIDETONE_MON:
	case AFE_SIDETONE_CON0:
	case AFE_SIDETONE_COEFF:
	case AFE_BUS_MON0:
	case AFE_MRGIF_MON0:
	case AFE_MRGIF_MON1:
	case AFE_MRGIF_MON2:
	case AFE_I2S_MON:
	case AFE_DAC_MON:
	case AFE_VUL2_END:
	case AFE_VUL2_CUR:
	case AFE_IRQ0_MCU_CNT_MON:
	case AFE_IRQ6_MCU_CNT_MON:
	case AFE_MOD_DAI_END:
	case AFE_MOD_DAI_CUR:
	case AFE_VUL_D2_END:
	case AFE_VUL_D2_CUR:
	case AFE_DL3_CUR:
	case AFE_DL3_END:
	case AFE_HDMI_OUT_CON0:
	case AFE_HDMI_OUT_CUR:
	case AFE_HDMI_OUT_END:
	case AFE_IRQ3_MCU_CNT_MON:
	case AFE_IRQ4_MCU_CNT_MON:
	case AFE_IRQ_MCU_STATUS:
	case AFE_IRQ_MCU_CLR:
	case AFE_IRQ_MCU_MON2:
	case AFE_IRQ1_MCU_CNT_MON:
	case AFE_IRQ2_MCU_CNT_MON:
	case AFE_IRQ1_MCU_EN_CNT_MON:
	case AFE_IRQ5_MCU_CNT_MON:
	case AFE_IRQ7_MCU_CNT_MON:
	case AFE_GAIN1_CUR:
	case AFE_GAIN2_CUR:
	case AFE_SRAM_DELSEL_CON0:
	case AFE_SRAM_DELSEL_CON2:
	case AFE_SRAM_DELSEL_CON3:
	case AFE_ASRC_2CH_CON12:
	case AFE_ASRC_2CH_CON13:
	case PCM_INTF_CON2:
	case FPGA_CFG0:
	case FPGA_CFG1:
	case FPGA_CFG2:
	case FPGA_CFG3:
	case AUDIO_TOP_DBG_MON0:
	case AUDIO_TOP_DBG_MON1:
	case AFE_IRQ8_MCU_CNT_MON:
	case AFE_IRQ11_MCU_CNT_MON:
	case AFE_IRQ12_MCU_CNT_MON:
	case AFE_CBIP_MON0:
	case AFE_CBIP_SLV_MUX_MON0:
	case AFE_CBIP_SLV_DECODER_MON0:
	case AFE_ADDA6_SRC_DEBUG_MON0:
	case AFE_ADD6A_UL_SRC_MON0:
	case AFE_ADDA6_UL_SRC_MON1:
	case AFE_DL1_CUR_MSB:
	case AFE_DL2_CUR_MSB:
	case AFE_AWB_CUR_MSB:
	case AFE_VUL_CUR_MSB:
	case AFE_VUL2_CUR_MSB:
	case AFE_MOD_DAI_CUR_MSB:
	case AFE_VUL_D2_CUR_MSB:
	case AFE_DL3_CUR_MSB:
	case AFE_HDMI_OUT_CUR_MSB:
	case AFE_AWB2_END:
	case AFE_AWB2_CUR:
	case AFE_AWB2_CUR_MSB:
	case AFE_ADDA_DL_SDM_FIFO_MON:
	case AFE_ADDA_DL_SRC_LCH_MON:
	case AFE_ADDA_DL_SRC_RCH_MON:
	case AFE_ADDA_DL_SDM_OUT_MON:
	case AFE_CONNSYS_I2S_MON:
	case AFE_ASRC_2CH_CON0:
	case AFE_ASRC_2CH_CON2:
	case AFE_ASRC_2CH_CON3:
	case AFE_ASRC_2CH_CON4:
	case AFE_ASRC_2CH_CON5:
	case AFE_ASRC_2CH_CON7:
	case AFE_ASRC_2CH_CON8:
	case AFE_MEMIF_MON12:
	case AFE_MEMIF_MON13:
	case AFE_MEMIF_MON14:
	case AFE_MEMIF_MON15:
	case AFE_MEMIF_MON16:
	case AFE_MEMIF_MON17:
	case AFE_MEMIF_MON18:
	case AFE_MEMIF_MON19:
	case AFE_MEMIF_MON20:
	case AFE_MEMIF_MON21:
	case AFE_MEMIF_MON22:
	case AFE_MEMIF_MON23:
	case AFE_MEMIF_MON24:
	case AFE_ADDA_MTKAIF_MON0:
	case AFE_ADDA_MTKAIF_MON1:
	case AFE_AUD_PAD_TOP:
	case AFE_GENERAL1_ASRC_2CH_CON0:
	case AFE_GENERAL1_ASRC_2CH_CON2:
	case AFE_GENERAL1_ASRC_2CH_CON3:
	case AFE_GENERAL1_ASRC_2CH_CON4:
	case AFE_GENERAL1_ASRC_2CH_CON5:
	case AFE_GENERAL1_ASRC_2CH_CON7:
	case AFE_GENERAL1_ASRC_2CH_CON8:
	case AFE_GENERAL1_ASRC_2CH_CON12:
	case AFE_GENERAL1_ASRC_2CH_CON13:
	case AFE_GENERAL2_ASRC_2CH_CON0:
	case AFE_GENERAL2_ASRC_2CH_CON2:
	case AFE_GENERAL2_ASRC_2CH_CON3:
	case AFE_GENERAL2_ASRC_2CH_CON4:
	case AFE_GENERAL2_ASRC_2CH_CON5:
	case AFE_GENERAL2_ASRC_2CH_CON7:
	case AFE_GENERAL2_ASRC_2CH_CON8:
	case AFE_GENERAL2_ASRC_2CH_CON12:
	case AFE_GENERAL2_ASRC_2CH_CON13:
		return true;
	default:
		return false;
	};
}