#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
struct device {int dummy; } ;

/* Variables and functions */
#define  ARIZONA_ACCESSORY_DETECT_MODE_1 796 
#define  ARIZONA_ADC_DIGITAL_VOLUME_1L 795 
#define  ARIZONA_ADC_DIGITAL_VOLUME_1R 794 
#define  ARIZONA_ADC_DIGITAL_VOLUME_2L 793 
#define  ARIZONA_ADC_DIGITAL_VOLUME_2R 792 
#define  ARIZONA_AIF1TX1MIX_INPUT_1_SOURCE 791 
#define  ARIZONA_AIF1TX1MIX_INPUT_1_VOLUME 790 
#define  ARIZONA_AIF1TX1MIX_INPUT_2_SOURCE 789 
#define  ARIZONA_AIF1TX1MIX_INPUT_2_VOLUME 788 
#define  ARIZONA_AIF1TX1MIX_INPUT_3_SOURCE 787 
#define  ARIZONA_AIF1TX1MIX_INPUT_3_VOLUME 786 
#define  ARIZONA_AIF1TX1MIX_INPUT_4_SOURCE 785 
#define  ARIZONA_AIF1TX1MIX_INPUT_4_VOLUME 784 
#define  ARIZONA_AIF1TX2MIX_INPUT_1_SOURCE 783 
#define  ARIZONA_AIF1TX2MIX_INPUT_1_VOLUME 782 
#define  ARIZONA_AIF1TX2MIX_INPUT_2_SOURCE 781 
#define  ARIZONA_AIF1TX2MIX_INPUT_2_VOLUME 780 
#define  ARIZONA_AIF1TX2MIX_INPUT_3_SOURCE 779 
#define  ARIZONA_AIF1TX2MIX_INPUT_3_VOLUME 778 
#define  ARIZONA_AIF1TX2MIX_INPUT_4_SOURCE 777 
#define  ARIZONA_AIF1TX2MIX_INPUT_4_VOLUME 776 
#define  ARIZONA_AIF1TX3MIX_INPUT_1_SOURCE 775 
#define  ARIZONA_AIF1TX3MIX_INPUT_1_VOLUME 774 
#define  ARIZONA_AIF1TX3MIX_INPUT_2_SOURCE 773 
#define  ARIZONA_AIF1TX3MIX_INPUT_2_VOLUME 772 
#define  ARIZONA_AIF1TX3MIX_INPUT_3_SOURCE 771 
#define  ARIZONA_AIF1TX3MIX_INPUT_3_VOLUME 770 
#define  ARIZONA_AIF1TX3MIX_INPUT_4_SOURCE 769 
#define  ARIZONA_AIF1TX3MIX_INPUT_4_VOLUME 768 
#define  ARIZONA_AIF1TX4MIX_INPUT_1_SOURCE 767 
#define  ARIZONA_AIF1TX4MIX_INPUT_1_VOLUME 766 
#define  ARIZONA_AIF1TX4MIX_INPUT_2_SOURCE 765 
#define  ARIZONA_AIF1TX4MIX_INPUT_2_VOLUME 764 
#define  ARIZONA_AIF1TX4MIX_INPUT_3_SOURCE 763 
#define  ARIZONA_AIF1TX4MIX_INPUT_3_VOLUME 762 
#define  ARIZONA_AIF1TX4MIX_INPUT_4_SOURCE 761 
#define  ARIZONA_AIF1TX4MIX_INPUT_4_VOLUME 760 
#define  ARIZONA_AIF1TX5MIX_INPUT_1_SOURCE 759 
#define  ARIZONA_AIF1TX5MIX_INPUT_1_VOLUME 758 
#define  ARIZONA_AIF1TX5MIX_INPUT_2_SOURCE 757 
#define  ARIZONA_AIF1TX5MIX_INPUT_2_VOLUME 756 
#define  ARIZONA_AIF1TX5MIX_INPUT_3_SOURCE 755 
#define  ARIZONA_AIF1TX5MIX_INPUT_3_VOLUME 754 
#define  ARIZONA_AIF1TX5MIX_INPUT_4_SOURCE 753 
#define  ARIZONA_AIF1TX5MIX_INPUT_4_VOLUME 752 
#define  ARIZONA_AIF1TX6MIX_INPUT_1_SOURCE 751 
#define  ARIZONA_AIF1TX6MIX_INPUT_1_VOLUME 750 
#define  ARIZONA_AIF1TX6MIX_INPUT_2_SOURCE 749 
#define  ARIZONA_AIF1TX6MIX_INPUT_2_VOLUME 748 
#define  ARIZONA_AIF1TX6MIX_INPUT_3_SOURCE 747 
#define  ARIZONA_AIF1TX6MIX_INPUT_3_VOLUME 746 
#define  ARIZONA_AIF1TX6MIX_INPUT_4_SOURCE 745 
#define  ARIZONA_AIF1TX6MIX_INPUT_4_VOLUME 744 
#define  ARIZONA_AIF1TX7MIX_INPUT_1_SOURCE 743 
#define  ARIZONA_AIF1TX7MIX_INPUT_1_VOLUME 742 
#define  ARIZONA_AIF1TX7MIX_INPUT_2_SOURCE 741 
#define  ARIZONA_AIF1TX7MIX_INPUT_2_VOLUME 740 
#define  ARIZONA_AIF1TX7MIX_INPUT_3_SOURCE 739 
#define  ARIZONA_AIF1TX7MIX_INPUT_3_VOLUME 738 
#define  ARIZONA_AIF1TX7MIX_INPUT_4_SOURCE 737 
#define  ARIZONA_AIF1TX7MIX_INPUT_4_VOLUME 736 
#define  ARIZONA_AIF1TX8MIX_INPUT_1_SOURCE 735 
#define  ARIZONA_AIF1TX8MIX_INPUT_1_VOLUME 734 
#define  ARIZONA_AIF1TX8MIX_INPUT_2_SOURCE 733 
#define  ARIZONA_AIF1TX8MIX_INPUT_2_VOLUME 732 
#define  ARIZONA_AIF1TX8MIX_INPUT_3_SOURCE 731 
#define  ARIZONA_AIF1TX8MIX_INPUT_3_VOLUME 730 
#define  ARIZONA_AIF1TX8MIX_INPUT_4_SOURCE 729 
#define  ARIZONA_AIF1TX8MIX_INPUT_4_VOLUME 728 
#define  ARIZONA_AIF1_BCLK_CTRL 727 
#define  ARIZONA_AIF1_FORMAT 726 
#define  ARIZONA_AIF1_FRAME_CTRL_1 725 
#define  ARIZONA_AIF1_FRAME_CTRL_10 724 
#define  ARIZONA_AIF1_FRAME_CTRL_11 723 
#define  ARIZONA_AIF1_FRAME_CTRL_12 722 
#define  ARIZONA_AIF1_FRAME_CTRL_13 721 
#define  ARIZONA_AIF1_FRAME_CTRL_14 720 
#define  ARIZONA_AIF1_FRAME_CTRL_15 719 
#define  ARIZONA_AIF1_FRAME_CTRL_16 718 
#define  ARIZONA_AIF1_FRAME_CTRL_17 717 
#define  ARIZONA_AIF1_FRAME_CTRL_18 716 
#define  ARIZONA_AIF1_FRAME_CTRL_2 715 
#define  ARIZONA_AIF1_FRAME_CTRL_3 714 
#define  ARIZONA_AIF1_FRAME_CTRL_4 713 
#define  ARIZONA_AIF1_FRAME_CTRL_5 712 
#define  ARIZONA_AIF1_FRAME_CTRL_6 711 
#define  ARIZONA_AIF1_FRAME_CTRL_7 710 
#define  ARIZONA_AIF1_FRAME_CTRL_8 709 
#define  ARIZONA_AIF1_FRAME_CTRL_9 708 
#define  ARIZONA_AIF1_RATE_CTRL 707 
#define  ARIZONA_AIF1_RX_BCLK_RATE 706 
#define  ARIZONA_AIF1_RX_ENABLES 705 
#define  ARIZONA_AIF1_RX_PIN_CTRL 704 
#define  ARIZONA_AIF1_TX_BCLK_RATE 703 
#define  ARIZONA_AIF1_TX_ENABLES 702 
#define  ARIZONA_AIF1_TX_PIN_CTRL 701 
#define  ARIZONA_AIF2TX1MIX_INPUT_1_SOURCE 700 
#define  ARIZONA_AIF2TX1MIX_INPUT_1_VOLUME 699 
#define  ARIZONA_AIF2TX1MIX_INPUT_2_SOURCE 698 
#define  ARIZONA_AIF2TX1MIX_INPUT_2_VOLUME 697 
#define  ARIZONA_AIF2TX1MIX_INPUT_3_SOURCE 696 
#define  ARIZONA_AIF2TX1MIX_INPUT_3_VOLUME 695 
#define  ARIZONA_AIF2TX1MIX_INPUT_4_SOURCE 694 
#define  ARIZONA_AIF2TX1MIX_INPUT_4_VOLUME 693 
#define  ARIZONA_AIF2TX2MIX_INPUT_1_SOURCE 692 
#define  ARIZONA_AIF2TX2MIX_INPUT_1_VOLUME 691 
#define  ARIZONA_AIF2TX2MIX_INPUT_2_SOURCE 690 
#define  ARIZONA_AIF2TX2MIX_INPUT_2_VOLUME 689 
#define  ARIZONA_AIF2TX2MIX_INPUT_3_SOURCE 688 
#define  ARIZONA_AIF2TX2MIX_INPUT_3_VOLUME 687 
#define  ARIZONA_AIF2TX2MIX_INPUT_4_SOURCE 686 
#define  ARIZONA_AIF2TX2MIX_INPUT_4_VOLUME 685 
#define  ARIZONA_AIF2_BCLK_CTRL 684 
#define  ARIZONA_AIF2_FORMAT 683 
#define  ARIZONA_AIF2_FRAME_CTRL_1 682 
#define  ARIZONA_AIF2_FRAME_CTRL_11 681 
#define  ARIZONA_AIF2_FRAME_CTRL_12 680 
#define  ARIZONA_AIF2_FRAME_CTRL_2 679 
#define  ARIZONA_AIF2_FRAME_CTRL_3 678 
#define  ARIZONA_AIF2_FRAME_CTRL_4 677 
#define  ARIZONA_AIF2_RATE_CTRL 676 
#define  ARIZONA_AIF2_RX_BCLK_RATE 675 
#define  ARIZONA_AIF2_RX_ENABLES 674 
#define  ARIZONA_AIF2_RX_PIN_CTRL 673 
#define  ARIZONA_AIF2_TX_BCLK_RATE 672 
#define  ARIZONA_AIF2_TX_ENABLES 671 
#define  ARIZONA_AIF2_TX_PIN_CTRL 670 
#define  ARIZONA_ALWAYS_ON_TRIGGERS_SEQUENCE_SELECT_3 669 
#define  ARIZONA_ALWAYS_ON_TRIGGERS_SEQUENCE_SELECT_4 668 
#define  ARIZONA_ALWAYS_ON_TRIGGERS_SEQUENCE_SELECT_5 667 
#define  ARIZONA_ALWAYS_ON_TRIGGERS_SEQUENCE_SELECT_6 666 
#define  ARIZONA_AOD_IRQ1 665 
#define  ARIZONA_AOD_IRQ2 664 
#define  ARIZONA_AOD_IRQ_MASK_IRQ1 663 
#define  ARIZONA_AOD_IRQ_MASK_IRQ2 662 
#define  ARIZONA_AOD_IRQ_RAW_STATUS 661 
#define  ARIZONA_AOD_WKUP_AND_TRIG 660 
#define  ARIZONA_ASYNC_CLOCK_1 659 
#define  ARIZONA_ASYNC_SAMPLE_RATE_1 658 
#define  ARIZONA_ASYNC_SAMPLE_RATE_1_STATUS 657 
#define  ARIZONA_CLOCK_32K_1 656 
#define  ARIZONA_COMFORT_NOISE_GENERATOR 655 
#define  ARIZONA_CTRL_IF_I2C1_CFG_1 654 
#define  ARIZONA_DAC_AEC_CONTROL_1 653 
#define  ARIZONA_DAC_DIGITAL_VOLUME_1L 652 
#define  ARIZONA_DAC_DIGITAL_VOLUME_1R 651 
#define  ARIZONA_DAC_DIGITAL_VOLUME_3L 650 
#define  ARIZONA_DAC_DIGITAL_VOLUME_4L 649 
#define  ARIZONA_DAC_DIGITAL_VOLUME_5L 648 
#define  ARIZONA_DAC_DIGITAL_VOLUME_5R 647 
#define  ARIZONA_DAC_VOLUME_LIMIT_1L 646 
#define  ARIZONA_DAC_VOLUME_LIMIT_1R 645 
#define  ARIZONA_DAC_VOLUME_LIMIT_3L 644 
#define  ARIZONA_DAC_VOLUME_LIMIT_5L 643 
#define  ARIZONA_DAC_VOLUME_LIMIT_5R 642 
#define  ARIZONA_DEVICE_REVISION 641 
#define  ARIZONA_DMIC1L_CONTROL 640 
#define  ARIZONA_DMIC1R_CONTROL 639 
#define  ARIZONA_DMIC2L_CONTROL 638 
#define  ARIZONA_DMIC2R_CONTROL 637 
#define  ARIZONA_DRC1LMIX_INPUT_1_SOURCE 636 
#define  ARIZONA_DRC1LMIX_INPUT_1_VOLUME 635 
#define  ARIZONA_DRC1LMIX_INPUT_2_SOURCE 634 
#define  ARIZONA_DRC1LMIX_INPUT_2_VOLUME 633 
#define  ARIZONA_DRC1LMIX_INPUT_3_SOURCE 632 
#define  ARIZONA_DRC1LMIX_INPUT_3_VOLUME 631 
#define  ARIZONA_DRC1LMIX_INPUT_4_SOURCE 630 
#define  ARIZONA_DRC1LMIX_INPUT_4_VOLUME 629 
#define  ARIZONA_DRC1RMIX_INPUT_1_SOURCE 628 
#define  ARIZONA_DRC1RMIX_INPUT_1_VOLUME 627 
#define  ARIZONA_DRC1RMIX_INPUT_2_SOURCE 626 
#define  ARIZONA_DRC1RMIX_INPUT_2_VOLUME 625 
#define  ARIZONA_DRC1RMIX_INPUT_3_SOURCE 624 
#define  ARIZONA_DRC1RMIX_INPUT_3_VOLUME 623 
#define  ARIZONA_DRC1RMIX_INPUT_4_SOURCE 622 
#define  ARIZONA_DRC1RMIX_INPUT_4_VOLUME 621 
#define  ARIZONA_DRC1_CTRL1 620 
#define  ARIZONA_DRC1_CTRL2 619 
#define  ARIZONA_DRC1_CTRL3 618 
#define  ARIZONA_DRC1_CTRL4 617 
#define  ARIZONA_DRC1_CTRL5 616 
#define  ARIZONA_DYNAMIC_FREQUENCY_SCALING_1 615 
#define  ARIZONA_EQ1MIX_INPUT_1_SOURCE 614 
#define  ARIZONA_EQ1MIX_INPUT_1_VOLUME 613 
#define  ARIZONA_EQ1MIX_INPUT_2_SOURCE 612 
#define  ARIZONA_EQ1MIX_INPUT_2_VOLUME 611 
#define  ARIZONA_EQ1MIX_INPUT_3_SOURCE 610 
#define  ARIZONA_EQ1MIX_INPUT_3_VOLUME 609 
#define  ARIZONA_EQ1MIX_INPUT_4_SOURCE 608 
#define  ARIZONA_EQ1MIX_INPUT_4_VOLUME 607 
#define  ARIZONA_EQ1_1 606 
#define  ARIZONA_EQ1_10 605 
#define  ARIZONA_EQ1_11 604 
#define  ARIZONA_EQ1_12 603 
#define  ARIZONA_EQ1_13 602 
#define  ARIZONA_EQ1_14 601 
#define  ARIZONA_EQ1_15 600 
#define  ARIZONA_EQ1_16 599 
#define  ARIZONA_EQ1_17 598 
#define  ARIZONA_EQ1_18 597 
#define  ARIZONA_EQ1_19 596 
#define  ARIZONA_EQ1_2 595 
#define  ARIZONA_EQ1_20 594 
#define  ARIZONA_EQ1_21 593 
#define  ARIZONA_EQ1_3 592 
#define  ARIZONA_EQ1_4 591 
#define  ARIZONA_EQ1_5 590 
#define  ARIZONA_EQ1_6 589 
#define  ARIZONA_EQ1_7 588 
#define  ARIZONA_EQ1_8 587 
#define  ARIZONA_EQ1_9 586 
#define  ARIZONA_EQ2MIX_INPUT_1_SOURCE 585 
#define  ARIZONA_EQ2MIX_INPUT_1_VOLUME 584 
#define  ARIZONA_EQ2MIX_INPUT_2_SOURCE 583 
#define  ARIZONA_EQ2MIX_INPUT_2_VOLUME 582 
#define  ARIZONA_EQ2MIX_INPUT_3_SOURCE 581 
#define  ARIZONA_EQ2MIX_INPUT_3_VOLUME 580 
#define  ARIZONA_EQ2MIX_INPUT_4_SOURCE 579 
#define  ARIZONA_EQ2MIX_INPUT_4_VOLUME 578 
#define  ARIZONA_EQ2_1 577 
#define  ARIZONA_EQ2_10 576 
#define  ARIZONA_EQ2_11 575 
#define  ARIZONA_EQ2_12 574 
#define  ARIZONA_EQ2_13 573 
#define  ARIZONA_EQ2_14 572 
#define  ARIZONA_EQ2_15 571 
#define  ARIZONA_EQ2_16 570 
#define  ARIZONA_EQ2_17 569 
#define  ARIZONA_EQ2_18 568 
#define  ARIZONA_EQ2_19 567 
#define  ARIZONA_EQ2_2 566 
#define  ARIZONA_EQ2_20 565 
#define  ARIZONA_EQ2_21 564 
#define  ARIZONA_EQ2_3 563 
#define  ARIZONA_EQ2_4 562 
#define  ARIZONA_EQ2_5 561 
#define  ARIZONA_EQ2_6 560 
#define  ARIZONA_EQ2_7 559 
#define  ARIZONA_EQ2_8 558 
#define  ARIZONA_EQ2_9 557 
#define  ARIZONA_EQ3MIX_INPUT_1_SOURCE 556 
#define  ARIZONA_EQ3MIX_INPUT_1_VOLUME 555 
#define  ARIZONA_EQ3MIX_INPUT_2_SOURCE 554 
#define  ARIZONA_EQ3MIX_INPUT_2_VOLUME 553 
#define  ARIZONA_EQ3MIX_INPUT_3_SOURCE 552 
#define  ARIZONA_EQ3MIX_INPUT_3_VOLUME 551 
#define  ARIZONA_EQ3MIX_INPUT_4_SOURCE 550 
#define  ARIZONA_EQ3MIX_INPUT_4_VOLUME 549 
#define  ARIZONA_EQ3_1 548 
#define  ARIZONA_EQ3_10 547 
#define  ARIZONA_EQ3_11 546 
#define  ARIZONA_EQ3_12 545 
#define  ARIZONA_EQ3_13 544 
#define  ARIZONA_EQ3_14 543 
#define  ARIZONA_EQ3_15 542 
#define  ARIZONA_EQ3_16 541 
#define  ARIZONA_EQ3_17 540 
#define  ARIZONA_EQ3_18 539 
#define  ARIZONA_EQ3_19 538 
#define  ARIZONA_EQ3_2 537 
#define  ARIZONA_EQ3_20 536 
#define  ARIZONA_EQ3_21 535 
#define  ARIZONA_EQ3_3 534 
#define  ARIZONA_EQ3_4 533 
#define  ARIZONA_EQ3_5 532 
#define  ARIZONA_EQ3_6 531 
#define  ARIZONA_EQ3_7 530 
#define  ARIZONA_EQ3_8 529 
#define  ARIZONA_EQ3_9 528 
#define  ARIZONA_EQ4MIX_INPUT_1_SOURCE 527 
#define  ARIZONA_EQ4MIX_INPUT_1_VOLUME 526 
#define  ARIZONA_EQ4MIX_INPUT_2_SOURCE 525 
#define  ARIZONA_EQ4MIX_INPUT_2_VOLUME 524 
#define  ARIZONA_EQ4MIX_INPUT_3_SOURCE 523 
#define  ARIZONA_EQ4MIX_INPUT_3_VOLUME 522 
#define  ARIZONA_EQ4MIX_INPUT_4_SOURCE 521 
#define  ARIZONA_EQ4MIX_INPUT_4_VOLUME 520 
#define  ARIZONA_EQ4_1 519 
#define  ARIZONA_EQ4_10 518 
#define  ARIZONA_EQ4_11 517 
#define  ARIZONA_EQ4_12 516 
#define  ARIZONA_EQ4_13 515 
#define  ARIZONA_EQ4_14 514 
#define  ARIZONA_EQ4_15 513 
#define  ARIZONA_EQ4_16 512 
#define  ARIZONA_EQ4_17 511 
#define  ARIZONA_EQ4_18 510 
#define  ARIZONA_EQ4_19 509 
#define  ARIZONA_EQ4_2 508 
#define  ARIZONA_EQ4_20 507 
#define  ARIZONA_EQ4_21 506 
#define  ARIZONA_EQ4_3 505 
#define  ARIZONA_EQ4_4 504 
#define  ARIZONA_EQ4_5 503 
#define  ARIZONA_EQ4_6 502 
#define  ARIZONA_EQ4_7 501 
#define  ARIZONA_EQ4_8 500 
#define  ARIZONA_EQ4_9 499 
#define  ARIZONA_FLL1_CONTROL_1 498 
#define  ARIZONA_FLL1_CONTROL_2 497 
#define  ARIZONA_FLL1_CONTROL_3 496 
#define  ARIZONA_FLL1_CONTROL_4 495 
#define  ARIZONA_FLL1_CONTROL_5 494 
#define  ARIZONA_FLL1_CONTROL_6 493 
#define  ARIZONA_FLL1_GPIO_CLOCK 492 
#define  ARIZONA_FLL1_LOOP_FILTER_TEST_1 491 
#define  ARIZONA_FLL1_NCO_TEST_0 490 
#define  ARIZONA_FLL1_SPREAD_SPECTRUM 489 
#define  ARIZONA_FLL1_SYNCHRONISER_1 488 
#define  ARIZONA_FLL1_SYNCHRONISER_2 487 
#define  ARIZONA_FLL1_SYNCHRONISER_3 486 
#define  ARIZONA_FLL1_SYNCHRONISER_4 485 
#define  ARIZONA_FLL1_SYNCHRONISER_5 484 
#define  ARIZONA_FLL1_SYNCHRONISER_6 483 
#define  ARIZONA_FLL2_CONTROL_1 482 
#define  ARIZONA_FLL2_CONTROL_2 481 
#define  ARIZONA_FLL2_CONTROL_3 480 
#define  ARIZONA_FLL2_CONTROL_4 479 
#define  ARIZONA_FLL2_CONTROL_5 478 
#define  ARIZONA_FLL2_CONTROL_6 477 
#define  ARIZONA_FLL2_GPIO_CLOCK 476 
#define  ARIZONA_FLL2_LOOP_FILTER_TEST_1 475 
#define  ARIZONA_FLL2_NCO_TEST_0 474 
#define  ARIZONA_FLL2_SPREAD_SPECTRUM 473 
#define  ARIZONA_FLL2_SYNCHRONISER_1 472 
#define  ARIZONA_FLL2_SYNCHRONISER_2 471 
#define  ARIZONA_FLL2_SYNCHRONISER_3 470 
#define  ARIZONA_FLL2_SYNCHRONISER_4 469 
#define  ARIZONA_FLL2_SYNCHRONISER_5 468 
#define  ARIZONA_FLL2_SYNCHRONISER_6 467 
#define  ARIZONA_FX_CTRL1 466 
#define  ARIZONA_FX_CTRL2 465 
#define  ARIZONA_GPIO1_CTRL 464 
#define  ARIZONA_GPIO2_CTRL 463 
#define  ARIZONA_GPIO3_CTRL 462 
#define  ARIZONA_GPIO4_CTRL 461 
#define  ARIZONA_GPIO5_CTRL 460 
#define  ARIZONA_GPIO_DEBOUNCE_CONFIG 459 
#define  ARIZONA_HAPTICS_CONTROL_1 458 
#define  ARIZONA_HAPTICS_CONTROL_2 457 
#define  ARIZONA_HAPTICS_PHASE_1_DURATION 456 
#define  ARIZONA_HAPTICS_PHASE_1_INTENSITY 455 
#define  ARIZONA_HAPTICS_PHASE_2_DURATION 454 
#define  ARIZONA_HAPTICS_PHASE_2_INTENSITY 453 
#define  ARIZONA_HAPTICS_PHASE_3_DURATION 452 
#define  ARIZONA_HAPTICS_PHASE_3_INTENSITY 451 
#define  ARIZONA_HAPTICS_STATUS 450 
#define  ARIZONA_HEADPHONE_DETECT_1 449 
#define  ARIZONA_HEADPHONE_DETECT_2 448 
#define  ARIZONA_HPLP1MIX_INPUT_1_SOURCE 447 
#define  ARIZONA_HPLP1MIX_INPUT_1_VOLUME 446 
#define  ARIZONA_HPLP1MIX_INPUT_2_SOURCE 445 
#define  ARIZONA_HPLP1MIX_INPUT_2_VOLUME 444 
#define  ARIZONA_HPLP1MIX_INPUT_3_SOURCE 443 
#define  ARIZONA_HPLP1MIX_INPUT_3_VOLUME 442 
#define  ARIZONA_HPLP1MIX_INPUT_4_SOURCE 441 
#define  ARIZONA_HPLP1MIX_INPUT_4_VOLUME 440 
#define  ARIZONA_HPLP2MIX_INPUT_1_SOURCE 439 
#define  ARIZONA_HPLP2MIX_INPUT_1_VOLUME 438 
#define  ARIZONA_HPLP2MIX_INPUT_2_SOURCE 437 
#define  ARIZONA_HPLP2MIX_INPUT_2_VOLUME 436 
#define  ARIZONA_HPLP2MIX_INPUT_3_SOURCE 435 
#define  ARIZONA_HPLP2MIX_INPUT_3_VOLUME 434 
#define  ARIZONA_HPLP2MIX_INPUT_4_SOURCE 433 
#define  ARIZONA_HPLP2MIX_INPUT_4_VOLUME 432 
#define  ARIZONA_HPLP3MIX_INPUT_1_SOURCE 431 
#define  ARIZONA_HPLP3MIX_INPUT_1_VOLUME 430 
#define  ARIZONA_HPLP3MIX_INPUT_2_SOURCE 429 
#define  ARIZONA_HPLP3MIX_INPUT_2_VOLUME 428 
#define  ARIZONA_HPLP3MIX_INPUT_3_SOURCE 427 
#define  ARIZONA_HPLP3MIX_INPUT_3_VOLUME 426 
#define  ARIZONA_HPLP3MIX_INPUT_4_SOURCE 425 
#define  ARIZONA_HPLP3MIX_INPUT_4_VOLUME 424 
#define  ARIZONA_HPLP4MIX_INPUT_1_SOURCE 423 
#define  ARIZONA_HPLP4MIX_INPUT_1_VOLUME 422 
#define  ARIZONA_HPLP4MIX_INPUT_2_SOURCE 421 
#define  ARIZONA_HPLP4MIX_INPUT_2_VOLUME 420 
#define  ARIZONA_HPLP4MIX_INPUT_3_SOURCE 419 
#define  ARIZONA_HPLP4MIX_INPUT_3_VOLUME 418 
#define  ARIZONA_HPLP4MIX_INPUT_4_SOURCE 417 
#define  ARIZONA_HPLP4MIX_INPUT_4_VOLUME 416 
#define  ARIZONA_HPLPF1_1 415 
#define  ARIZONA_HPLPF1_2 414 
#define  ARIZONA_HPLPF2_1 413 
#define  ARIZONA_HPLPF2_2 412 
#define  ARIZONA_HPLPF3_1 411 
#define  ARIZONA_HPLPF3_2 410 
#define  ARIZONA_HPLPF4_1 409 
#define  ARIZONA_HPLPF4_2 408 
#define  ARIZONA_HP_CTRL_1L 407 
#define  ARIZONA_HP_CTRL_1R 406 
#define  ARIZONA_IN1L_CONTROL 405 
#define  ARIZONA_IN1R_CONTROL 404 
#define  ARIZONA_IN2L_CONTROL 403 
#define  ARIZONA_IN2R_CONTROL 402 
#define  ARIZONA_INPUT_ENABLES 401 
#define  ARIZONA_INPUT_ENABLES_STATUS 400 
#define  ARIZONA_INPUT_RATE 399 
#define  ARIZONA_INPUT_VOLUME_RAMP 398 
#define  ARIZONA_INTERRUPT_CONTROL 397 
#define  ARIZONA_INTERRUPT_RAW_STATUS_3 396 
#define  ARIZONA_INTERRUPT_RAW_STATUS_4 395 
#define  ARIZONA_INTERRUPT_RAW_STATUS_5 394 
#define  ARIZONA_INTERRUPT_RAW_STATUS_6 393 
#define  ARIZONA_INTERRUPT_RAW_STATUS_7 392 
#define  ARIZONA_INTERRUPT_RAW_STATUS_8 391 
#define  ARIZONA_INTERRUPT_STATUS_1 390 
#define  ARIZONA_INTERRUPT_STATUS_1_MASK 389 
#define  ARIZONA_INTERRUPT_STATUS_2 388 
#define  ARIZONA_INTERRUPT_STATUS_2_MASK 387 
#define  ARIZONA_INTERRUPT_STATUS_3 386 
#define  ARIZONA_INTERRUPT_STATUS_3_MASK 385 
#define  ARIZONA_INTERRUPT_STATUS_4 384 
#define  ARIZONA_INTERRUPT_STATUS_4_MASK 383 
#define  ARIZONA_INTERRUPT_STATUS_5 382 
#define  ARIZONA_INTERRUPT_STATUS_5_MASK 381 
#define  ARIZONA_IRQ2_CONTROL 380 
#define  ARIZONA_IRQ2_STATUS_1 379 
#define  ARIZONA_IRQ2_STATUS_1_MASK 378 
#define  ARIZONA_IRQ2_STATUS_3 377 
#define  ARIZONA_IRQ2_STATUS_3_MASK 376 
#define  ARIZONA_IRQ2_STATUS_4 375 
#define  ARIZONA_IRQ2_STATUS_4_MASK 374 
#define  ARIZONA_IRQ2_STATUS_5 373 
#define  ARIZONA_IRQ2_STATUS_5_MASK 372 
#define  ARIZONA_IRQ_CTRL_1 371 
#define  ARIZONA_IRQ_PIN_STATUS 370 
#define  ARIZONA_ISOLATION_CONTROL 369 
#define  ARIZONA_ISRC1DEC1MIX_INPUT_1_SOURCE 368 
#define  ARIZONA_ISRC1DEC2MIX_INPUT_1_SOURCE 367 
#define  ARIZONA_ISRC1INT1MIX_INPUT_1_SOURCE 366 
#define  ARIZONA_ISRC1INT2MIX_INPUT_1_SOURCE 365 
#define  ARIZONA_ISRC2DEC1MIX_INPUT_1_SOURCE 364 
#define  ARIZONA_ISRC2DEC2MIX_INPUT_1_SOURCE 363 
#define  ARIZONA_ISRC2INT1MIX_INPUT_1_SOURCE 362 
#define  ARIZONA_ISRC2INT2MIX_INPUT_1_SOURCE 361 
#define  ARIZONA_ISRC_1_CTRL_1 360 
#define  ARIZONA_ISRC_1_CTRL_2 359 
#define  ARIZONA_ISRC_1_CTRL_3 358 
#define  ARIZONA_ISRC_2_CTRL_1 357 
#define  ARIZONA_ISRC_2_CTRL_2 356 
#define  ARIZONA_ISRC_2_CTRL_3 355 
#define  ARIZONA_JACK_DETECT_ANALOGUE 354 
#define  ARIZONA_JACK_DETECT_DEBOUNCE 353 
#define  ARIZONA_LDO1_CONTROL_1 352 
#define  ARIZONA_LDO1_CONTROL_2 351 
#define  ARIZONA_LDO2_CONTROL_1 350 
#define  ARIZONA_MICMIX_INPUT_1_SOURCE 349 
#define  ARIZONA_MICMIX_INPUT_1_VOLUME 348 
#define  ARIZONA_MICMIX_INPUT_2_SOURCE 347 
#define  ARIZONA_MICMIX_INPUT_2_VOLUME 346 
#define  ARIZONA_MICMIX_INPUT_3_SOURCE 345 
#define  ARIZONA_MICMIX_INPUT_3_VOLUME 344 
#define  ARIZONA_MICMIX_INPUT_4_SOURCE 343 
#define  ARIZONA_MICMIX_INPUT_4_VOLUME 342 
#define  ARIZONA_MIC_BIAS_CTRL_1 341 
#define  ARIZONA_MIC_BIAS_CTRL_2 340 
#define  ARIZONA_MIC_BIAS_CTRL_3 339 
#define  ARIZONA_MIC_CHARGE_PUMP_1 338 
#define  ARIZONA_MIC_DETECT_1 337 
#define  ARIZONA_MIC_DETECT_2 336 
#define  ARIZONA_MIC_DETECT_3 335 
#define  ARIZONA_MIC_NOISE_MIX_CONTROL_1 334 
#define  ARIZONA_MISC_PAD_CTRL_1 333 
#define  ARIZONA_MISC_PAD_CTRL_2 332 
#define  ARIZONA_MISC_PAD_CTRL_3 331 
#define  ARIZONA_MISC_PAD_CTRL_4 330 
#define  ARIZONA_MISC_PAD_CTRL_5 329 
#define  ARIZONA_NOISEMIX_INPUT_1_SOURCE 328 
#define  ARIZONA_NOISEMIX_INPUT_1_VOLUME 327 
#define  ARIZONA_NOISEMIX_INPUT_2_SOURCE 326 
#define  ARIZONA_NOISEMIX_INPUT_2_VOLUME 325 
#define  ARIZONA_NOISEMIX_INPUT_3_SOURCE 324 
#define  ARIZONA_NOISEMIX_INPUT_3_VOLUME 323 
#define  ARIZONA_NOISEMIX_INPUT_4_SOURCE 322 
#define  ARIZONA_NOISEMIX_INPUT_4_VOLUME 321 
#define  ARIZONA_NOISE_GATE_CONTROL 320 
#define  ARIZONA_NOISE_GATE_SELECT_1L 319 
#define  ARIZONA_NOISE_GATE_SELECT_1R 318 
#define  ARIZONA_NOISE_GATE_SELECT_3L 317 
#define  ARIZONA_NOISE_GATE_SELECT_4L 316 
#define  ARIZONA_NOISE_GATE_SELECT_5L 315 
#define  ARIZONA_NOISE_GATE_SELECT_5R 314 
#define  ARIZONA_OUT1LMIX_INPUT_1_SOURCE 313 
#define  ARIZONA_OUT1LMIX_INPUT_1_VOLUME 312 
#define  ARIZONA_OUT1LMIX_INPUT_2_SOURCE 311 
#define  ARIZONA_OUT1LMIX_INPUT_2_VOLUME 310 
#define  ARIZONA_OUT1LMIX_INPUT_3_SOURCE 309 
#define  ARIZONA_OUT1LMIX_INPUT_3_VOLUME 308 
#define  ARIZONA_OUT1LMIX_INPUT_4_SOURCE 307 
#define  ARIZONA_OUT1LMIX_INPUT_4_VOLUME 306 
#define  ARIZONA_OUT1RMIX_INPUT_1_SOURCE 305 
#define  ARIZONA_OUT1RMIX_INPUT_1_VOLUME 304 
#define  ARIZONA_OUT1RMIX_INPUT_2_SOURCE 303 
#define  ARIZONA_OUT1RMIX_INPUT_2_VOLUME 302 
#define  ARIZONA_OUT1RMIX_INPUT_3_SOURCE 301 
#define  ARIZONA_OUT1RMIX_INPUT_3_VOLUME 300 
#define  ARIZONA_OUT1RMIX_INPUT_4_SOURCE 299 
#define  ARIZONA_OUT1RMIX_INPUT_4_VOLUME 298 
#define  ARIZONA_OUT3LMIX_INPUT_1_SOURCE 297 
#define  ARIZONA_OUT3LMIX_INPUT_1_VOLUME 296 
#define  ARIZONA_OUT3LMIX_INPUT_2_SOURCE 295 
#define  ARIZONA_OUT3LMIX_INPUT_2_VOLUME 294 
#define  ARIZONA_OUT3LMIX_INPUT_3_SOURCE 293 
#define  ARIZONA_OUT3LMIX_INPUT_3_VOLUME 292 
#define  ARIZONA_OUT3LMIX_INPUT_4_SOURCE 291 
#define  ARIZONA_OUT3LMIX_INPUT_4_VOLUME 290 
#define  ARIZONA_OUT4LMIX_INPUT_1_SOURCE 289 
#define  ARIZONA_OUT4LMIX_INPUT_1_VOLUME 288 
#define  ARIZONA_OUT4LMIX_INPUT_2_SOURCE 287 
#define  ARIZONA_OUT4LMIX_INPUT_2_VOLUME 286 
#define  ARIZONA_OUT4LMIX_INPUT_3_SOURCE 285 
#define  ARIZONA_OUT4LMIX_INPUT_3_VOLUME 284 
#define  ARIZONA_OUT4LMIX_INPUT_4_SOURCE 283 
#define  ARIZONA_OUT4LMIX_INPUT_4_VOLUME 282 
#define  ARIZONA_OUT5LMIX_INPUT_1_SOURCE 281 
#define  ARIZONA_OUT5LMIX_INPUT_1_VOLUME 280 
#define  ARIZONA_OUT5LMIX_INPUT_2_SOURCE 279 
#define  ARIZONA_OUT5LMIX_INPUT_2_VOLUME 278 
#define  ARIZONA_OUT5LMIX_INPUT_3_SOURCE 277 
#define  ARIZONA_OUT5LMIX_INPUT_3_VOLUME 276 
#define  ARIZONA_OUT5LMIX_INPUT_4_SOURCE 275 
#define  ARIZONA_OUT5LMIX_INPUT_4_VOLUME 274 
#define  ARIZONA_OUT5RMIX_INPUT_1_SOURCE 273 
#define  ARIZONA_OUT5RMIX_INPUT_1_VOLUME 272 
#define  ARIZONA_OUT5RMIX_INPUT_2_SOURCE 271 
#define  ARIZONA_OUT5RMIX_INPUT_2_VOLUME 270 
#define  ARIZONA_OUT5RMIX_INPUT_3_SOURCE 269 
#define  ARIZONA_OUT5RMIX_INPUT_3_VOLUME 268 
#define  ARIZONA_OUT5RMIX_INPUT_4_SOURCE 267 
#define  ARIZONA_OUT5RMIX_INPUT_4_VOLUME 266 
#define  ARIZONA_OUTPUT_ASYNC_CLOCK 265 
#define  ARIZONA_OUTPUT_ENABLES_1 264 
#define  ARIZONA_OUTPUT_PATH_CONFIG_1L 263 
#define  ARIZONA_OUTPUT_PATH_CONFIG_1R 262 
#define  ARIZONA_OUTPUT_PATH_CONFIG_3L 261 
#define  ARIZONA_OUTPUT_PATH_CONFIG_4L 260 
#define  ARIZONA_OUTPUT_PATH_CONFIG_5L 259 
#define  ARIZONA_OUTPUT_RATE_1 258 
#define  ARIZONA_OUTPUT_STATUS_1 257 
#define  ARIZONA_OUTPUT_SYSTEM_CLOCK 256 
#define  ARIZONA_OUTPUT_VOLUME_RAMP 255 
#define  ARIZONA_OUT_VOLUME_4L 254 
#define  ARIZONA_PDM_SPK1_CTRL_1 253 
#define  ARIZONA_PDM_SPK1_CTRL_2 252 
#define  ARIZONA_PWM1MIX_INPUT_1_SOURCE 251 
#define  ARIZONA_PWM1MIX_INPUT_1_VOLUME 250 
#define  ARIZONA_PWM1MIX_INPUT_2_SOURCE 249 
#define  ARIZONA_PWM1MIX_INPUT_2_VOLUME 248 
#define  ARIZONA_PWM1MIX_INPUT_3_SOURCE 247 
#define  ARIZONA_PWM1MIX_INPUT_3_VOLUME 246 
#define  ARIZONA_PWM1MIX_INPUT_4_SOURCE 245 
#define  ARIZONA_PWM1MIX_INPUT_4_VOLUME 244 
#define  ARIZONA_PWM2MIX_INPUT_1_SOURCE 243 
#define  ARIZONA_PWM2MIX_INPUT_1_VOLUME 242 
#define  ARIZONA_PWM2MIX_INPUT_2_SOURCE 241 
#define  ARIZONA_PWM2MIX_INPUT_2_VOLUME 240 
#define  ARIZONA_PWM2MIX_INPUT_3_SOURCE 239 
#define  ARIZONA_PWM2MIX_INPUT_3_VOLUME 238 
#define  ARIZONA_PWM2MIX_INPUT_4_SOURCE 237 
#define  ARIZONA_PWM2MIX_INPUT_4_VOLUME 236 
#define  ARIZONA_PWM_DRIVE_1 235 
#define  ARIZONA_PWM_DRIVE_2 234 
#define  ARIZONA_PWM_DRIVE_3 233 
#define  ARIZONA_RATE_ESTIMATOR_1 232 
#define  ARIZONA_RATE_ESTIMATOR_2 231 
#define  ARIZONA_RATE_ESTIMATOR_3 230 
#define  ARIZONA_RATE_ESTIMATOR_4 229 
#define  ARIZONA_RATE_ESTIMATOR_5 228 
#define  ARIZONA_RAW_OUTPUT_STATUS_1 227 
#define  ARIZONA_SAMPLE_RATE_1 226 
#define  ARIZONA_SAMPLE_RATE_1_STATUS 225 
#define  ARIZONA_SAMPLE_RATE_2 224 
#define  ARIZONA_SAMPLE_RATE_2_STATUS 223 
#define  ARIZONA_SAMPLE_RATE_3 222 
#define  ARIZONA_SAMPLE_RATE_3_STATUS 221 
#define  ARIZONA_SAMPLE_RATE_SEQUENCE_SELECT_1 220 
#define  ARIZONA_SAMPLE_RATE_SEQUENCE_SELECT_2 219 
#define  ARIZONA_SAMPLE_RATE_SEQUENCE_SELECT_3 218 
#define  ARIZONA_SAMPLE_RATE_SEQUENCE_SELECT_4 217 
#define  ARIZONA_SEQUENCE_CONTROL 216 
#define  ARIZONA_SLIMBUS_FRAMER_REF_GEAR 215 
#define  ARIZONA_SLIMBUS_RATES_1 214 
#define  ARIZONA_SLIMBUS_RATES_2 213 
#define  ARIZONA_SLIMBUS_RATES_3 212 
#define  ARIZONA_SLIMBUS_RATES_4 211 
#define  ARIZONA_SLIMBUS_RATES_5 210 
#define  ARIZONA_SLIMBUS_RATES_6 209 
#define  ARIZONA_SLIMBUS_RATES_7 208 
#define  ARIZONA_SLIMBUS_RATES_8 207 
#define  ARIZONA_SLIMBUS_RX_CHANNEL_ENABLE 206 
#define  ARIZONA_SLIMBUS_RX_PORT_STATUS 205 
#define  ARIZONA_SLIMBUS_TX_CHANNEL_ENABLE 204 
#define  ARIZONA_SLIMBUS_TX_PORT_STATUS 203 
#define  ARIZONA_SLIMTX1MIX_INPUT_1_SOURCE 202 
#define  ARIZONA_SLIMTX1MIX_INPUT_1_VOLUME 201 
#define  ARIZONA_SLIMTX1MIX_INPUT_2_SOURCE 200 
#define  ARIZONA_SLIMTX1MIX_INPUT_2_VOLUME 199 
#define  ARIZONA_SLIMTX1MIX_INPUT_3_SOURCE 198 
#define  ARIZONA_SLIMTX1MIX_INPUT_3_VOLUME 197 
#define  ARIZONA_SLIMTX1MIX_INPUT_4_SOURCE 196 
#define  ARIZONA_SLIMTX1MIX_INPUT_4_VOLUME 195 
#define  ARIZONA_SLIMTX2MIX_INPUT_1_SOURCE 194 
#define  ARIZONA_SLIMTX2MIX_INPUT_1_VOLUME 193 
#define  ARIZONA_SLIMTX2MIX_INPUT_2_SOURCE 192 
#define  ARIZONA_SLIMTX2MIX_INPUT_2_VOLUME 191 
#define  ARIZONA_SLIMTX2MIX_INPUT_3_SOURCE 190 
#define  ARIZONA_SLIMTX2MIX_INPUT_3_VOLUME 189 
#define  ARIZONA_SLIMTX2MIX_INPUT_4_SOURCE 188 
#define  ARIZONA_SLIMTX2MIX_INPUT_4_VOLUME 187 
#define  ARIZONA_SLIMTX3MIX_INPUT_1_SOURCE 186 
#define  ARIZONA_SLIMTX3MIX_INPUT_1_VOLUME 185 
#define  ARIZONA_SLIMTX3MIX_INPUT_2_SOURCE 184 
#define  ARIZONA_SLIMTX3MIX_INPUT_2_VOLUME 183 
#define  ARIZONA_SLIMTX3MIX_INPUT_3_SOURCE 182 
#define  ARIZONA_SLIMTX3MIX_INPUT_3_VOLUME 181 
#define  ARIZONA_SLIMTX3MIX_INPUT_4_SOURCE 180 
#define  ARIZONA_SLIMTX3MIX_INPUT_4_VOLUME 179 
#define  ARIZONA_SLIMTX4MIX_INPUT_1_SOURCE 178 
#define  ARIZONA_SLIMTX4MIX_INPUT_1_VOLUME 177 
#define  ARIZONA_SLIMTX4MIX_INPUT_2_SOURCE 176 
#define  ARIZONA_SLIMTX4MIX_INPUT_2_VOLUME 175 
#define  ARIZONA_SLIMTX4MIX_INPUT_3_SOURCE 174 
#define  ARIZONA_SLIMTX4MIX_INPUT_3_VOLUME 173 
#define  ARIZONA_SLIMTX4MIX_INPUT_4_SOURCE 172 
#define  ARIZONA_SLIMTX4MIX_INPUT_4_VOLUME 171 
#define  ARIZONA_SLIMTX5MIX_INPUT_1_SOURCE 170 
#define  ARIZONA_SLIMTX5MIX_INPUT_1_VOLUME 169 
#define  ARIZONA_SLIMTX5MIX_INPUT_2_SOURCE 168 
#define  ARIZONA_SLIMTX5MIX_INPUT_2_VOLUME 167 
#define  ARIZONA_SLIMTX5MIX_INPUT_3_SOURCE 166 
#define  ARIZONA_SLIMTX5MIX_INPUT_3_VOLUME 165 
#define  ARIZONA_SLIMTX5MIX_INPUT_4_SOURCE 164 
#define  ARIZONA_SLIMTX5MIX_INPUT_4_VOLUME 163 
#define  ARIZONA_SLIMTX6MIX_INPUT_1_SOURCE 162 
#define  ARIZONA_SLIMTX6MIX_INPUT_1_VOLUME 161 
#define  ARIZONA_SLIMTX6MIX_INPUT_2_SOURCE 160 
#define  ARIZONA_SLIMTX6MIX_INPUT_2_VOLUME 159 
#define  ARIZONA_SLIMTX6MIX_INPUT_3_SOURCE 158 
#define  ARIZONA_SLIMTX6MIX_INPUT_3_VOLUME 157 
#define  ARIZONA_SLIMTX6MIX_INPUT_4_SOURCE 156 
#define  ARIZONA_SLIMTX6MIX_INPUT_4_VOLUME 155 
#define  ARIZONA_SLIMTX7MIX_INPUT_1_SOURCE 154 
#define  ARIZONA_SLIMTX7MIX_INPUT_1_VOLUME 153 
#define  ARIZONA_SLIMTX7MIX_INPUT_2_SOURCE 152 
#define  ARIZONA_SLIMTX7MIX_INPUT_2_VOLUME 151 
#define  ARIZONA_SLIMTX7MIX_INPUT_3_SOURCE 150 
#define  ARIZONA_SLIMTX7MIX_INPUT_3_VOLUME 149 
#define  ARIZONA_SLIMTX7MIX_INPUT_4_SOURCE 148 
#define  ARIZONA_SLIMTX7MIX_INPUT_4_VOLUME 147 
#define  ARIZONA_SLIMTX8MIX_INPUT_1_SOURCE 146 
#define  ARIZONA_SLIMTX8MIX_INPUT_1_VOLUME 145 
#define  ARIZONA_SLIMTX8MIX_INPUT_2_SOURCE 144 
#define  ARIZONA_SLIMTX8MIX_INPUT_2_VOLUME 143 
#define  ARIZONA_SLIMTX8MIX_INPUT_3_SOURCE 142 
#define  ARIZONA_SLIMTX8MIX_INPUT_3_VOLUME 141 
#define  ARIZONA_SLIMTX8MIX_INPUT_4_SOURCE 140 
#define  ARIZONA_SLIMTX8MIX_INPUT_4_VOLUME 139 
#define  ARIZONA_SOFTWARE_RESET 138 
#define  ARIZONA_SYSTEM_CLOCK_1 137 
#define  ARIZONA_TONE_GENERATOR_1 136 
#define  ARIZONA_TONE_GENERATOR_2 135 
#define  ARIZONA_TONE_GENERATOR_3 134 
#define  ARIZONA_TONE_GENERATOR_4 133 
#define  ARIZONA_TONE_GENERATOR_5 132 
#define  ARIZONA_WAKE_CONTROL 131 
#define  ARIZONA_WRITE_SEQUENCER_CTRL_0 130 
#define  ARIZONA_WRITE_SEQUENCER_CTRL_1 129 
#define  ARIZONA_WRITE_SEQUENCER_CTRL_2 128 

__attribute__((used)) static bool wm8997_readable_register(struct device *dev, unsigned int reg)
{
	switch (reg) {
	case ARIZONA_SOFTWARE_RESET:
	case ARIZONA_DEVICE_REVISION:
	case ARIZONA_CTRL_IF_I2C1_CFG_1:
	case ARIZONA_WRITE_SEQUENCER_CTRL_0:
	case ARIZONA_WRITE_SEQUENCER_CTRL_1:
	case ARIZONA_WRITE_SEQUENCER_CTRL_2:
	case ARIZONA_TONE_GENERATOR_1:
	case ARIZONA_TONE_GENERATOR_2:
	case ARIZONA_TONE_GENERATOR_3:
	case ARIZONA_TONE_GENERATOR_4:
	case ARIZONA_TONE_GENERATOR_5:
	case ARIZONA_PWM_DRIVE_1:
	case ARIZONA_PWM_DRIVE_2:
	case ARIZONA_PWM_DRIVE_3:
	case ARIZONA_WAKE_CONTROL:
	case ARIZONA_SEQUENCE_CONTROL:
	case ARIZONA_SAMPLE_RATE_SEQUENCE_SELECT_1:
	case ARIZONA_SAMPLE_RATE_SEQUENCE_SELECT_2:
	case ARIZONA_SAMPLE_RATE_SEQUENCE_SELECT_3:
	case ARIZONA_SAMPLE_RATE_SEQUENCE_SELECT_4:
	case ARIZONA_ALWAYS_ON_TRIGGERS_SEQUENCE_SELECT_3:
	case ARIZONA_ALWAYS_ON_TRIGGERS_SEQUENCE_SELECT_4:
	case ARIZONA_ALWAYS_ON_TRIGGERS_SEQUENCE_SELECT_5:
	case ARIZONA_ALWAYS_ON_TRIGGERS_SEQUENCE_SELECT_6:
	case ARIZONA_COMFORT_NOISE_GENERATOR:
	case ARIZONA_HAPTICS_CONTROL_1:
	case ARIZONA_HAPTICS_CONTROL_2:
	case ARIZONA_HAPTICS_PHASE_1_INTENSITY:
	case ARIZONA_HAPTICS_PHASE_1_DURATION:
	case ARIZONA_HAPTICS_PHASE_2_INTENSITY:
	case ARIZONA_HAPTICS_PHASE_2_DURATION:
	case ARIZONA_HAPTICS_PHASE_3_INTENSITY:
	case ARIZONA_HAPTICS_PHASE_3_DURATION:
	case ARIZONA_HAPTICS_STATUS:
	case ARIZONA_CLOCK_32K_1:
	case ARIZONA_SYSTEM_CLOCK_1:
	case ARIZONA_SAMPLE_RATE_1:
	case ARIZONA_SAMPLE_RATE_2:
	case ARIZONA_SAMPLE_RATE_3:
	case ARIZONA_SAMPLE_RATE_1_STATUS:
	case ARIZONA_SAMPLE_RATE_2_STATUS:
	case ARIZONA_SAMPLE_RATE_3_STATUS:
	case ARIZONA_ASYNC_CLOCK_1:
	case ARIZONA_ASYNC_SAMPLE_RATE_1:
	case ARIZONA_ASYNC_SAMPLE_RATE_1_STATUS:
	case ARIZONA_OUTPUT_SYSTEM_CLOCK:
	case ARIZONA_OUTPUT_ASYNC_CLOCK:
	case ARIZONA_RATE_ESTIMATOR_1:
	case ARIZONA_RATE_ESTIMATOR_2:
	case ARIZONA_RATE_ESTIMATOR_3:
	case ARIZONA_RATE_ESTIMATOR_4:
	case ARIZONA_RATE_ESTIMATOR_5:
	case ARIZONA_DYNAMIC_FREQUENCY_SCALING_1:
	case ARIZONA_FLL1_CONTROL_1:
	case ARIZONA_FLL1_CONTROL_2:
	case ARIZONA_FLL1_CONTROL_3:
	case ARIZONA_FLL1_CONTROL_4:
	case ARIZONA_FLL1_CONTROL_5:
	case ARIZONA_FLL1_CONTROL_6:
	case ARIZONA_FLL1_LOOP_FILTER_TEST_1:
	case ARIZONA_FLL1_NCO_TEST_0:
	case ARIZONA_FLL1_SYNCHRONISER_1:
	case ARIZONA_FLL1_SYNCHRONISER_2:
	case ARIZONA_FLL1_SYNCHRONISER_3:
	case ARIZONA_FLL1_SYNCHRONISER_4:
	case ARIZONA_FLL1_SYNCHRONISER_5:
	case ARIZONA_FLL1_SYNCHRONISER_6:
	case ARIZONA_FLL1_SPREAD_SPECTRUM:
	case ARIZONA_FLL1_GPIO_CLOCK:
	case ARIZONA_FLL2_CONTROL_1:
	case ARIZONA_FLL2_CONTROL_2:
	case ARIZONA_FLL2_CONTROL_3:
	case ARIZONA_FLL2_CONTROL_4:
	case ARIZONA_FLL2_CONTROL_5:
	case ARIZONA_FLL2_CONTROL_6:
	case ARIZONA_FLL2_LOOP_FILTER_TEST_1:
	case ARIZONA_FLL2_NCO_TEST_0:
	case ARIZONA_FLL2_SYNCHRONISER_1:
	case ARIZONA_FLL2_SYNCHRONISER_2:
	case ARIZONA_FLL2_SYNCHRONISER_3:
	case ARIZONA_FLL2_SYNCHRONISER_4:
	case ARIZONA_FLL2_SYNCHRONISER_5:
	case ARIZONA_FLL2_SYNCHRONISER_6:
	case ARIZONA_FLL2_SPREAD_SPECTRUM:
	case ARIZONA_FLL2_GPIO_CLOCK:
	case ARIZONA_MIC_CHARGE_PUMP_1:
	case ARIZONA_LDO1_CONTROL_1:
	case ARIZONA_LDO1_CONTROL_2:
	case ARIZONA_LDO2_CONTROL_1:
	case ARIZONA_MIC_BIAS_CTRL_1:
	case ARIZONA_MIC_BIAS_CTRL_2:
	case ARIZONA_MIC_BIAS_CTRL_3:
	case ARIZONA_HP_CTRL_1L:
	case ARIZONA_HP_CTRL_1R:
	case ARIZONA_ACCESSORY_DETECT_MODE_1:
	case ARIZONA_HEADPHONE_DETECT_1:
	case ARIZONA_HEADPHONE_DETECT_2:
	case ARIZONA_MIC_DETECT_1:
	case ARIZONA_MIC_DETECT_2:
	case ARIZONA_MIC_DETECT_3:
	case ARIZONA_MIC_NOISE_MIX_CONTROL_1:
	case ARIZONA_ISOLATION_CONTROL:
	case ARIZONA_JACK_DETECT_ANALOGUE:
	case ARIZONA_INPUT_ENABLES:
	case ARIZONA_INPUT_ENABLES_STATUS:
	case ARIZONA_INPUT_RATE:
	case ARIZONA_INPUT_VOLUME_RAMP:
	case ARIZONA_IN1L_CONTROL:
	case ARIZONA_ADC_DIGITAL_VOLUME_1L:
	case ARIZONA_DMIC1L_CONTROL:
	case ARIZONA_IN1R_CONTROL:
	case ARIZONA_ADC_DIGITAL_VOLUME_1R:
	case ARIZONA_DMIC1R_CONTROL:
	case ARIZONA_IN2L_CONTROL:
	case ARIZONA_ADC_DIGITAL_VOLUME_2L:
	case ARIZONA_DMIC2L_CONTROL:
	case ARIZONA_IN2R_CONTROL:
	case ARIZONA_ADC_DIGITAL_VOLUME_2R:
	case ARIZONA_DMIC2R_CONTROL:
	case ARIZONA_OUTPUT_ENABLES_1:
	case ARIZONA_OUTPUT_STATUS_1:
	case ARIZONA_RAW_OUTPUT_STATUS_1:
	case ARIZONA_OUTPUT_RATE_1:
	case ARIZONA_OUTPUT_VOLUME_RAMP:
	case ARIZONA_OUTPUT_PATH_CONFIG_1L:
	case ARIZONA_DAC_DIGITAL_VOLUME_1L:
	case ARIZONA_DAC_VOLUME_LIMIT_1L:
	case ARIZONA_NOISE_GATE_SELECT_1L:
	case ARIZONA_OUTPUT_PATH_CONFIG_1R:
	case ARIZONA_DAC_DIGITAL_VOLUME_1R:
	case ARIZONA_DAC_VOLUME_LIMIT_1R:
	case ARIZONA_NOISE_GATE_SELECT_1R:
	case ARIZONA_OUTPUT_PATH_CONFIG_3L:
	case ARIZONA_DAC_DIGITAL_VOLUME_3L:
	case ARIZONA_DAC_VOLUME_LIMIT_3L:
	case ARIZONA_NOISE_GATE_SELECT_3L:
	case ARIZONA_OUTPUT_PATH_CONFIG_4L:
	case ARIZONA_DAC_DIGITAL_VOLUME_4L:
	case ARIZONA_OUT_VOLUME_4L:
	case ARIZONA_NOISE_GATE_SELECT_4L:
	case ARIZONA_OUTPUT_PATH_CONFIG_5L:
	case ARIZONA_DAC_DIGITAL_VOLUME_5L:
	case ARIZONA_DAC_VOLUME_LIMIT_5L:
	case ARIZONA_NOISE_GATE_SELECT_5L:
	case ARIZONA_DAC_DIGITAL_VOLUME_5R:
	case ARIZONA_DAC_VOLUME_LIMIT_5R:
	case ARIZONA_NOISE_GATE_SELECT_5R:
	case ARIZONA_DAC_AEC_CONTROL_1:
	case ARIZONA_NOISE_GATE_CONTROL:
	case ARIZONA_PDM_SPK1_CTRL_1:
	case ARIZONA_PDM_SPK1_CTRL_2:
	case ARIZONA_AIF1_BCLK_CTRL:
	case ARIZONA_AIF1_TX_PIN_CTRL:
	case ARIZONA_AIF1_RX_PIN_CTRL:
	case ARIZONA_AIF1_RATE_CTRL:
	case ARIZONA_AIF1_FORMAT:
	case ARIZONA_AIF1_TX_BCLK_RATE:
	case ARIZONA_AIF1_RX_BCLK_RATE:
	case ARIZONA_AIF1_FRAME_CTRL_1:
	case ARIZONA_AIF1_FRAME_CTRL_2:
	case ARIZONA_AIF1_FRAME_CTRL_3:
	case ARIZONA_AIF1_FRAME_CTRL_4:
	case ARIZONA_AIF1_FRAME_CTRL_5:
	case ARIZONA_AIF1_FRAME_CTRL_6:
	case ARIZONA_AIF1_FRAME_CTRL_7:
	case ARIZONA_AIF1_FRAME_CTRL_8:
	case ARIZONA_AIF1_FRAME_CTRL_9:
	case ARIZONA_AIF1_FRAME_CTRL_10:
	case ARIZONA_AIF1_FRAME_CTRL_11:
	case ARIZONA_AIF1_FRAME_CTRL_12:
	case ARIZONA_AIF1_FRAME_CTRL_13:
	case ARIZONA_AIF1_FRAME_CTRL_14:
	case ARIZONA_AIF1_FRAME_CTRL_15:
	case ARIZONA_AIF1_FRAME_CTRL_16:
	case ARIZONA_AIF1_FRAME_CTRL_17:
	case ARIZONA_AIF1_FRAME_CTRL_18:
	case ARIZONA_AIF1_TX_ENABLES:
	case ARIZONA_AIF1_RX_ENABLES:
	case ARIZONA_AIF2_BCLK_CTRL:
	case ARIZONA_AIF2_TX_PIN_CTRL:
	case ARIZONA_AIF2_RX_PIN_CTRL:
	case ARIZONA_AIF2_RATE_CTRL:
	case ARIZONA_AIF2_FORMAT:
	case ARIZONA_AIF2_TX_BCLK_RATE:
	case ARIZONA_AIF2_RX_BCLK_RATE:
	case ARIZONA_AIF2_FRAME_CTRL_1:
	case ARIZONA_AIF2_FRAME_CTRL_2:
	case ARIZONA_AIF2_FRAME_CTRL_3:
	case ARIZONA_AIF2_FRAME_CTRL_4:
	case ARIZONA_AIF2_FRAME_CTRL_11:
	case ARIZONA_AIF2_FRAME_CTRL_12:
	case ARIZONA_AIF2_TX_ENABLES:
	case ARIZONA_AIF2_RX_ENABLES:
	case ARIZONA_SLIMBUS_FRAMER_REF_GEAR:
	case ARIZONA_SLIMBUS_RATES_1:
	case ARIZONA_SLIMBUS_RATES_2:
	case ARIZONA_SLIMBUS_RATES_3:
	case ARIZONA_SLIMBUS_RATES_4:
	case ARIZONA_SLIMBUS_RATES_5:
	case ARIZONA_SLIMBUS_RATES_6:
	case ARIZONA_SLIMBUS_RATES_7:
	case ARIZONA_SLIMBUS_RATES_8:
	case ARIZONA_SLIMBUS_RX_CHANNEL_ENABLE:
	case ARIZONA_SLIMBUS_TX_CHANNEL_ENABLE:
	case ARIZONA_SLIMBUS_RX_PORT_STATUS:
	case ARIZONA_SLIMBUS_TX_PORT_STATUS:
	case ARIZONA_PWM1MIX_INPUT_1_SOURCE:
	case ARIZONA_PWM1MIX_INPUT_1_VOLUME:
	case ARIZONA_PWM1MIX_INPUT_2_SOURCE:
	case ARIZONA_PWM1MIX_INPUT_2_VOLUME:
	case ARIZONA_PWM1MIX_INPUT_3_SOURCE:
	case ARIZONA_PWM1MIX_INPUT_3_VOLUME:
	case ARIZONA_PWM1MIX_INPUT_4_SOURCE:
	case ARIZONA_PWM1MIX_INPUT_4_VOLUME:
	case ARIZONA_PWM2MIX_INPUT_1_SOURCE:
	case ARIZONA_PWM2MIX_INPUT_1_VOLUME:
	case ARIZONA_PWM2MIX_INPUT_2_SOURCE:
	case ARIZONA_PWM2MIX_INPUT_2_VOLUME:
	case ARIZONA_PWM2MIX_INPUT_3_SOURCE:
	case ARIZONA_PWM2MIX_INPUT_3_VOLUME:
	case ARIZONA_PWM2MIX_INPUT_4_SOURCE:
	case ARIZONA_PWM2MIX_INPUT_4_VOLUME:
	case ARIZONA_MICMIX_INPUT_1_SOURCE:
	case ARIZONA_MICMIX_INPUT_1_VOLUME:
	case ARIZONA_MICMIX_INPUT_2_SOURCE:
	case ARIZONA_MICMIX_INPUT_2_VOLUME:
	case ARIZONA_MICMIX_INPUT_3_SOURCE:
	case ARIZONA_MICMIX_INPUT_3_VOLUME:
	case ARIZONA_MICMIX_INPUT_4_SOURCE:
	case ARIZONA_MICMIX_INPUT_4_VOLUME:
	case ARIZONA_NOISEMIX_INPUT_1_SOURCE:
	case ARIZONA_NOISEMIX_INPUT_1_VOLUME:
	case ARIZONA_NOISEMIX_INPUT_2_SOURCE:
	case ARIZONA_NOISEMIX_INPUT_2_VOLUME:
	case ARIZONA_NOISEMIX_INPUT_3_SOURCE:
	case ARIZONA_NOISEMIX_INPUT_3_VOLUME:
	case ARIZONA_NOISEMIX_INPUT_4_SOURCE:
	case ARIZONA_NOISEMIX_INPUT_4_VOLUME:
	case ARIZONA_OUT1LMIX_INPUT_1_SOURCE:
	case ARIZONA_OUT1LMIX_INPUT_1_VOLUME:
	case ARIZONA_OUT1LMIX_INPUT_2_SOURCE:
	case ARIZONA_OUT1LMIX_INPUT_2_VOLUME:
	case ARIZONA_OUT1LMIX_INPUT_3_SOURCE:
	case ARIZONA_OUT1LMIX_INPUT_3_VOLUME:
	case ARIZONA_OUT1LMIX_INPUT_4_SOURCE:
	case ARIZONA_OUT1LMIX_INPUT_4_VOLUME:
	case ARIZONA_OUT1RMIX_INPUT_1_SOURCE:
	case ARIZONA_OUT1RMIX_INPUT_1_VOLUME:
	case ARIZONA_OUT1RMIX_INPUT_2_SOURCE:
	case ARIZONA_OUT1RMIX_INPUT_2_VOLUME:
	case ARIZONA_OUT1RMIX_INPUT_3_SOURCE:
	case ARIZONA_OUT1RMIX_INPUT_3_VOLUME:
	case ARIZONA_OUT1RMIX_INPUT_4_SOURCE:
	case ARIZONA_OUT1RMIX_INPUT_4_VOLUME:
	case ARIZONA_OUT3LMIX_INPUT_1_SOURCE:
	case ARIZONA_OUT3LMIX_INPUT_1_VOLUME:
	case ARIZONA_OUT3LMIX_INPUT_2_SOURCE:
	case ARIZONA_OUT3LMIX_INPUT_2_VOLUME:
	case ARIZONA_OUT3LMIX_INPUT_3_SOURCE:
	case ARIZONA_OUT3LMIX_INPUT_3_VOLUME:
	case ARIZONA_OUT3LMIX_INPUT_4_SOURCE:
	case ARIZONA_OUT3LMIX_INPUT_4_VOLUME:
	case ARIZONA_OUT4LMIX_INPUT_1_SOURCE:
	case ARIZONA_OUT4LMIX_INPUT_1_VOLUME:
	case ARIZONA_OUT4LMIX_INPUT_2_SOURCE:
	case ARIZONA_OUT4LMIX_INPUT_2_VOLUME:
	case ARIZONA_OUT4LMIX_INPUT_3_SOURCE:
	case ARIZONA_OUT4LMIX_INPUT_3_VOLUME:
	case ARIZONA_OUT4LMIX_INPUT_4_SOURCE:
	case ARIZONA_OUT4LMIX_INPUT_4_VOLUME:
	case ARIZONA_OUT5LMIX_INPUT_1_SOURCE:
	case ARIZONA_OUT5LMIX_INPUT_1_VOLUME:
	case ARIZONA_OUT5LMIX_INPUT_2_SOURCE:
	case ARIZONA_OUT5LMIX_INPUT_2_VOLUME:
	case ARIZONA_OUT5LMIX_INPUT_3_SOURCE:
	case ARIZONA_OUT5LMIX_INPUT_3_VOLUME:
	case ARIZONA_OUT5LMIX_INPUT_4_SOURCE:
	case ARIZONA_OUT5LMIX_INPUT_4_VOLUME:
	case ARIZONA_OUT5RMIX_INPUT_1_SOURCE:
	case ARIZONA_OUT5RMIX_INPUT_1_VOLUME:
	case ARIZONA_OUT5RMIX_INPUT_2_SOURCE:
	case ARIZONA_OUT5RMIX_INPUT_2_VOLUME:
	case ARIZONA_OUT5RMIX_INPUT_3_SOURCE:
	case ARIZONA_OUT5RMIX_INPUT_3_VOLUME:
	case ARIZONA_OUT5RMIX_INPUT_4_SOURCE:
	case ARIZONA_OUT5RMIX_INPUT_4_VOLUME:
	case ARIZONA_AIF1TX1MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF1TX1MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF1TX1MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF1TX1MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF1TX1MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF1TX1MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF1TX1MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF1TX1MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF1TX2MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF1TX2MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF1TX2MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF1TX2MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF1TX2MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF1TX2MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF1TX2MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF1TX2MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF1TX3MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF1TX3MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF1TX3MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF1TX3MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF1TX3MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF1TX3MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF1TX3MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF1TX3MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF1TX4MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF1TX4MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF1TX4MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF1TX4MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF1TX4MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF1TX4MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF1TX4MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF1TX4MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF1TX5MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF1TX5MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF1TX5MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF1TX5MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF1TX5MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF1TX5MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF1TX5MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF1TX5MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF1TX6MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF1TX6MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF1TX6MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF1TX6MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF1TX6MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF1TX6MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF1TX6MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF1TX6MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF1TX7MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF1TX7MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF1TX7MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF1TX7MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF1TX7MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF1TX7MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF1TX7MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF1TX7MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF1TX8MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF1TX8MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF1TX8MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF1TX8MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF1TX8MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF1TX8MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF1TX8MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF1TX8MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF2TX1MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF2TX1MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF2TX1MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF2TX1MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF2TX1MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF2TX1MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF2TX1MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF2TX1MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF2TX2MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF2TX2MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF2TX2MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF2TX2MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF2TX2MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF2TX2MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF2TX2MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF2TX2MIX_INPUT_4_VOLUME:
	case ARIZONA_SLIMTX1MIX_INPUT_1_SOURCE:
	case ARIZONA_SLIMTX1MIX_INPUT_1_VOLUME:
	case ARIZONA_SLIMTX1MIX_INPUT_2_SOURCE:
	case ARIZONA_SLIMTX1MIX_INPUT_2_VOLUME:
	case ARIZONA_SLIMTX1MIX_INPUT_3_SOURCE:
	case ARIZONA_SLIMTX1MIX_INPUT_3_VOLUME:
	case ARIZONA_SLIMTX1MIX_INPUT_4_SOURCE:
	case ARIZONA_SLIMTX1MIX_INPUT_4_VOLUME:
	case ARIZONA_SLIMTX2MIX_INPUT_1_SOURCE:
	case ARIZONA_SLIMTX2MIX_INPUT_1_VOLUME:
	case ARIZONA_SLIMTX2MIX_INPUT_2_SOURCE:
	case ARIZONA_SLIMTX2MIX_INPUT_2_VOLUME:
	case ARIZONA_SLIMTX2MIX_INPUT_3_SOURCE:
	case ARIZONA_SLIMTX2MIX_INPUT_3_VOLUME:
	case ARIZONA_SLIMTX2MIX_INPUT_4_SOURCE:
	case ARIZONA_SLIMTX2MIX_INPUT_4_VOLUME:
	case ARIZONA_SLIMTX3MIX_INPUT_1_SOURCE:
	case ARIZONA_SLIMTX3MIX_INPUT_1_VOLUME:
	case ARIZONA_SLIMTX3MIX_INPUT_2_SOURCE:
	case ARIZONA_SLIMTX3MIX_INPUT_2_VOLUME:
	case ARIZONA_SLIMTX3MIX_INPUT_3_SOURCE:
	case ARIZONA_SLIMTX3MIX_INPUT_3_VOLUME:
	case ARIZONA_SLIMTX3MIX_INPUT_4_SOURCE:
	case ARIZONA_SLIMTX3MIX_INPUT_4_VOLUME:
	case ARIZONA_SLIMTX4MIX_INPUT_1_SOURCE:
	case ARIZONA_SLIMTX4MIX_INPUT_1_VOLUME:
	case ARIZONA_SLIMTX4MIX_INPUT_2_SOURCE:
	case ARIZONA_SLIMTX4MIX_INPUT_2_VOLUME:
	case ARIZONA_SLIMTX4MIX_INPUT_3_SOURCE:
	case ARIZONA_SLIMTX4MIX_INPUT_3_VOLUME:
	case ARIZONA_SLIMTX4MIX_INPUT_4_SOURCE:
	case ARIZONA_SLIMTX4MIX_INPUT_4_VOLUME:
	case ARIZONA_SLIMTX5MIX_INPUT_1_SOURCE:
	case ARIZONA_SLIMTX5MIX_INPUT_1_VOLUME:
	case ARIZONA_SLIMTX5MIX_INPUT_2_SOURCE:
	case ARIZONA_SLIMTX5MIX_INPUT_2_VOLUME:
	case ARIZONA_SLIMTX5MIX_INPUT_3_SOURCE:
	case ARIZONA_SLIMTX5MIX_INPUT_3_VOLUME:
	case ARIZONA_SLIMTX5MIX_INPUT_4_SOURCE:
	case ARIZONA_SLIMTX5MIX_INPUT_4_VOLUME:
	case ARIZONA_SLIMTX6MIX_INPUT_1_SOURCE:
	case ARIZONA_SLIMTX6MIX_INPUT_1_VOLUME:
	case ARIZONA_SLIMTX6MIX_INPUT_2_SOURCE:
	case ARIZONA_SLIMTX6MIX_INPUT_2_VOLUME:
	case ARIZONA_SLIMTX6MIX_INPUT_3_SOURCE:
	case ARIZONA_SLIMTX6MIX_INPUT_3_VOLUME:
	case ARIZONA_SLIMTX6MIX_INPUT_4_SOURCE:
	case ARIZONA_SLIMTX6MIX_INPUT_4_VOLUME:
	case ARIZONA_SLIMTX7MIX_INPUT_1_SOURCE:
	case ARIZONA_SLIMTX7MIX_INPUT_1_VOLUME:
	case ARIZONA_SLIMTX7MIX_INPUT_2_SOURCE:
	case ARIZONA_SLIMTX7MIX_INPUT_2_VOLUME:
	case ARIZONA_SLIMTX7MIX_INPUT_3_SOURCE:
	case ARIZONA_SLIMTX7MIX_INPUT_3_VOLUME:
	case ARIZONA_SLIMTX7MIX_INPUT_4_SOURCE:
	case ARIZONA_SLIMTX7MIX_INPUT_4_VOLUME:
	case ARIZONA_SLIMTX8MIX_INPUT_1_SOURCE:
	case ARIZONA_SLIMTX8MIX_INPUT_1_VOLUME:
	case ARIZONA_SLIMTX8MIX_INPUT_2_SOURCE:
	case ARIZONA_SLIMTX8MIX_INPUT_2_VOLUME:
	case ARIZONA_SLIMTX8MIX_INPUT_3_SOURCE:
	case ARIZONA_SLIMTX8MIX_INPUT_3_VOLUME:
	case ARIZONA_SLIMTX8MIX_INPUT_4_SOURCE:
	case ARIZONA_SLIMTX8MIX_INPUT_4_VOLUME:
	case ARIZONA_EQ1MIX_INPUT_1_SOURCE:
	case ARIZONA_EQ1MIX_INPUT_1_VOLUME:
	case ARIZONA_EQ1MIX_INPUT_2_SOURCE:
	case ARIZONA_EQ1MIX_INPUT_2_VOLUME:
	case ARIZONA_EQ1MIX_INPUT_3_SOURCE:
	case ARIZONA_EQ1MIX_INPUT_3_VOLUME:
	case ARIZONA_EQ1MIX_INPUT_4_SOURCE:
	case ARIZONA_EQ1MIX_INPUT_4_VOLUME:
	case ARIZONA_EQ2MIX_INPUT_1_SOURCE:
	case ARIZONA_EQ2MIX_INPUT_1_VOLUME:
	case ARIZONA_EQ2MIX_INPUT_2_SOURCE:
	case ARIZONA_EQ2MIX_INPUT_2_VOLUME:
	case ARIZONA_EQ2MIX_INPUT_3_SOURCE:
	case ARIZONA_EQ2MIX_INPUT_3_VOLUME:
	case ARIZONA_EQ2MIX_INPUT_4_SOURCE:
	case ARIZONA_EQ2MIX_INPUT_4_VOLUME:
	case ARIZONA_EQ3MIX_INPUT_1_SOURCE:
	case ARIZONA_EQ3MIX_INPUT_1_VOLUME:
	case ARIZONA_EQ3MIX_INPUT_2_SOURCE:
	case ARIZONA_EQ3MIX_INPUT_2_VOLUME:
	case ARIZONA_EQ3MIX_INPUT_3_SOURCE:
	case ARIZONA_EQ3MIX_INPUT_3_VOLUME:
	case ARIZONA_EQ3MIX_INPUT_4_SOURCE:
	case ARIZONA_EQ3MIX_INPUT_4_VOLUME:
	case ARIZONA_EQ4MIX_INPUT_1_SOURCE:
	case ARIZONA_EQ4MIX_INPUT_1_VOLUME:
	case ARIZONA_EQ4MIX_INPUT_2_SOURCE:
	case ARIZONA_EQ4MIX_INPUT_2_VOLUME:
	case ARIZONA_EQ4MIX_INPUT_3_SOURCE:
	case ARIZONA_EQ4MIX_INPUT_3_VOLUME:
	case ARIZONA_EQ4MIX_INPUT_4_SOURCE:
	case ARIZONA_EQ4MIX_INPUT_4_VOLUME:
	case ARIZONA_DRC1LMIX_INPUT_1_SOURCE:
	case ARIZONA_DRC1LMIX_INPUT_1_VOLUME:
	case ARIZONA_DRC1LMIX_INPUT_2_SOURCE:
	case ARIZONA_DRC1LMIX_INPUT_2_VOLUME:
	case ARIZONA_DRC1LMIX_INPUT_3_SOURCE:
	case ARIZONA_DRC1LMIX_INPUT_3_VOLUME:
	case ARIZONA_DRC1LMIX_INPUT_4_SOURCE:
	case ARIZONA_DRC1LMIX_INPUT_4_VOLUME:
	case ARIZONA_DRC1RMIX_INPUT_1_SOURCE:
	case ARIZONA_DRC1RMIX_INPUT_1_VOLUME:
	case ARIZONA_DRC1RMIX_INPUT_2_SOURCE:
	case ARIZONA_DRC1RMIX_INPUT_2_VOLUME:
	case ARIZONA_DRC1RMIX_INPUT_3_SOURCE:
	case ARIZONA_DRC1RMIX_INPUT_3_VOLUME:
	case ARIZONA_DRC1RMIX_INPUT_4_SOURCE:
	case ARIZONA_DRC1RMIX_INPUT_4_VOLUME:
	case ARIZONA_HPLP1MIX_INPUT_1_SOURCE:
	case ARIZONA_HPLP1MIX_INPUT_1_VOLUME:
	case ARIZONA_HPLP1MIX_INPUT_2_SOURCE:
	case ARIZONA_HPLP1MIX_INPUT_2_VOLUME:
	case ARIZONA_HPLP1MIX_INPUT_3_SOURCE:
	case ARIZONA_HPLP1MIX_INPUT_3_VOLUME:
	case ARIZONA_HPLP1MIX_INPUT_4_SOURCE:
	case ARIZONA_HPLP1MIX_INPUT_4_VOLUME:
	case ARIZONA_HPLP2MIX_INPUT_1_SOURCE:
	case ARIZONA_HPLP2MIX_INPUT_1_VOLUME:
	case ARIZONA_HPLP2MIX_INPUT_2_SOURCE:
	case ARIZONA_HPLP2MIX_INPUT_2_VOLUME:
	case ARIZONA_HPLP2MIX_INPUT_3_SOURCE:
	case ARIZONA_HPLP2MIX_INPUT_3_VOLUME:
	case ARIZONA_HPLP2MIX_INPUT_4_SOURCE:
	case ARIZONA_HPLP2MIX_INPUT_4_VOLUME:
	case ARIZONA_HPLP3MIX_INPUT_1_SOURCE:
	case ARIZONA_HPLP3MIX_INPUT_1_VOLUME:
	case ARIZONA_HPLP3MIX_INPUT_2_SOURCE:
	case ARIZONA_HPLP3MIX_INPUT_2_VOLUME:
	case ARIZONA_HPLP3MIX_INPUT_3_SOURCE:
	case ARIZONA_HPLP3MIX_INPUT_3_VOLUME:
	case ARIZONA_HPLP3MIX_INPUT_4_SOURCE:
	case ARIZONA_HPLP3MIX_INPUT_4_VOLUME:
	case ARIZONA_HPLP4MIX_INPUT_1_SOURCE:
	case ARIZONA_HPLP4MIX_INPUT_1_VOLUME:
	case ARIZONA_HPLP4MIX_INPUT_2_SOURCE:
	case ARIZONA_HPLP4MIX_INPUT_2_VOLUME:
	case ARIZONA_HPLP4MIX_INPUT_3_SOURCE:
	case ARIZONA_HPLP4MIX_INPUT_3_VOLUME:
	case ARIZONA_HPLP4MIX_INPUT_4_SOURCE:
	case ARIZONA_HPLP4MIX_INPUT_4_VOLUME:
	case ARIZONA_ISRC1DEC1MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC1DEC2MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC1INT1MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC1INT2MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC2DEC1MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC2DEC2MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC2INT1MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC2INT2MIX_INPUT_1_SOURCE:
	case ARIZONA_GPIO1_CTRL:
	case ARIZONA_GPIO2_CTRL:
	case ARIZONA_GPIO3_CTRL:
	case ARIZONA_GPIO4_CTRL:
	case ARIZONA_GPIO5_CTRL:
	case ARIZONA_IRQ_CTRL_1:
	case ARIZONA_GPIO_DEBOUNCE_CONFIG:
	case ARIZONA_MISC_PAD_CTRL_1:
	case ARIZONA_MISC_PAD_CTRL_2:
	case ARIZONA_MISC_PAD_CTRL_3:
	case ARIZONA_MISC_PAD_CTRL_4:
	case ARIZONA_MISC_PAD_CTRL_5:
	case ARIZONA_INTERRUPT_STATUS_1:
	case ARIZONA_INTERRUPT_STATUS_2:
	case ARIZONA_INTERRUPT_STATUS_3:
	case ARIZONA_INTERRUPT_STATUS_4:
	case ARIZONA_INTERRUPT_STATUS_5:
	case ARIZONA_INTERRUPT_STATUS_1_MASK:
	case ARIZONA_INTERRUPT_STATUS_2_MASK:
	case ARIZONA_INTERRUPT_STATUS_3_MASK:
	case ARIZONA_INTERRUPT_STATUS_4_MASK:
	case ARIZONA_INTERRUPT_STATUS_5_MASK:
	case ARIZONA_INTERRUPT_CONTROL:
	case ARIZONA_IRQ2_STATUS_1:
	case ARIZONA_IRQ2_STATUS_3:
	case ARIZONA_IRQ2_STATUS_4:
	case ARIZONA_IRQ2_STATUS_5:
	case ARIZONA_IRQ2_STATUS_1_MASK:
	case ARIZONA_IRQ2_STATUS_3_MASK:
	case ARIZONA_IRQ2_STATUS_4_MASK:
	case ARIZONA_IRQ2_STATUS_5_MASK:
	case ARIZONA_IRQ2_CONTROL:
	case ARIZONA_INTERRUPT_RAW_STATUS_3:
	case ARIZONA_INTERRUPT_RAW_STATUS_4:
	case ARIZONA_INTERRUPT_RAW_STATUS_5:
	case ARIZONA_INTERRUPT_RAW_STATUS_6:
	case ARIZONA_INTERRUPT_RAW_STATUS_7:
	case ARIZONA_INTERRUPT_RAW_STATUS_8:
	case ARIZONA_IRQ_PIN_STATUS:
	case ARIZONA_AOD_WKUP_AND_TRIG:
	case ARIZONA_AOD_IRQ1:
	case ARIZONA_AOD_IRQ2:
	case ARIZONA_AOD_IRQ_MASK_IRQ1:
	case ARIZONA_AOD_IRQ_MASK_IRQ2:
	case ARIZONA_AOD_IRQ_RAW_STATUS:
	case ARIZONA_JACK_DETECT_DEBOUNCE:
	case ARIZONA_FX_CTRL1:
	case ARIZONA_FX_CTRL2:
	case ARIZONA_EQ1_1:
	case ARIZONA_EQ1_2:
	case ARIZONA_EQ1_3:
	case ARIZONA_EQ1_4:
	case ARIZONA_EQ1_5:
	case ARIZONA_EQ1_6:
	case ARIZONA_EQ1_7:
	case ARIZONA_EQ1_8:
	case ARIZONA_EQ1_9:
	case ARIZONA_EQ1_10:
	case ARIZONA_EQ1_11:
	case ARIZONA_EQ1_12:
	case ARIZONA_EQ1_13:
	case ARIZONA_EQ1_14:
	case ARIZONA_EQ1_15:
	case ARIZONA_EQ1_16:
	case ARIZONA_EQ1_17:
	case ARIZONA_EQ1_18:
	case ARIZONA_EQ1_19:
	case ARIZONA_EQ1_20:
	case ARIZONA_EQ1_21:
	case ARIZONA_EQ2_1:
	case ARIZONA_EQ2_2:
	case ARIZONA_EQ2_3:
	case ARIZONA_EQ2_4:
	case ARIZONA_EQ2_5:
	case ARIZONA_EQ2_6:
	case ARIZONA_EQ2_7:
	case ARIZONA_EQ2_8:
	case ARIZONA_EQ2_9:
	case ARIZONA_EQ2_10:
	case ARIZONA_EQ2_11:
	case ARIZONA_EQ2_12:
	case ARIZONA_EQ2_13:
	case ARIZONA_EQ2_14:
	case ARIZONA_EQ2_15:
	case ARIZONA_EQ2_16:
	case ARIZONA_EQ2_17:
	case ARIZONA_EQ2_18:
	case ARIZONA_EQ2_19:
	case ARIZONA_EQ2_20:
	case ARIZONA_EQ2_21:
	case ARIZONA_EQ3_1:
	case ARIZONA_EQ3_2:
	case ARIZONA_EQ3_3:
	case ARIZONA_EQ3_4:
	case ARIZONA_EQ3_5:
	case ARIZONA_EQ3_6:
	case ARIZONA_EQ3_7:
	case ARIZONA_EQ3_8:
	case ARIZONA_EQ3_9:
	case ARIZONA_EQ3_10:
	case ARIZONA_EQ3_11:
	case ARIZONA_EQ3_12:
	case ARIZONA_EQ3_13:
	case ARIZONA_EQ3_14:
	case ARIZONA_EQ3_15:
	case ARIZONA_EQ3_16:
	case ARIZONA_EQ3_17:
	case ARIZONA_EQ3_18:
	case ARIZONA_EQ3_19:
	case ARIZONA_EQ3_20:
	case ARIZONA_EQ3_21:
	case ARIZONA_EQ4_1:
	case ARIZONA_EQ4_2:
	case ARIZONA_EQ4_3:
	case ARIZONA_EQ4_4:
	case ARIZONA_EQ4_5:
	case ARIZONA_EQ4_6:
	case ARIZONA_EQ4_7:
	case ARIZONA_EQ4_8:
	case ARIZONA_EQ4_9:
	case ARIZONA_EQ4_10:
	case ARIZONA_EQ4_11:
	case ARIZONA_EQ4_12:
	case ARIZONA_EQ4_13:
	case ARIZONA_EQ4_14:
	case ARIZONA_EQ4_15:
	case ARIZONA_EQ4_16:
	case ARIZONA_EQ4_17:
	case ARIZONA_EQ4_18:
	case ARIZONA_EQ4_19:
	case ARIZONA_EQ4_20:
	case ARIZONA_EQ4_21:
	case ARIZONA_DRC1_CTRL1:
	case ARIZONA_DRC1_CTRL2:
	case ARIZONA_DRC1_CTRL3:
	case ARIZONA_DRC1_CTRL4:
	case ARIZONA_DRC1_CTRL5:
	case ARIZONA_HPLPF1_1:
	case ARIZONA_HPLPF1_2:
	case ARIZONA_HPLPF2_1:
	case ARIZONA_HPLPF2_2:
	case ARIZONA_HPLPF3_1:
	case ARIZONA_HPLPF3_2:
	case ARIZONA_HPLPF4_1:
	case ARIZONA_HPLPF4_2:
	case ARIZONA_ISRC_1_CTRL_1:
	case ARIZONA_ISRC_1_CTRL_2:
	case ARIZONA_ISRC_1_CTRL_3:
	case ARIZONA_ISRC_2_CTRL_1:
	case ARIZONA_ISRC_2_CTRL_2:
	case ARIZONA_ISRC_2_CTRL_3:
		return true;
	default:
		return false;
	}
}