#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
struct device {int dummy; } ;

/* Variables and functions */
#define  ARIZONA_AOD_IRQ1 294 
#define  ARIZONA_AOD_IRQ2 293 
#define  ARIZONA_AOD_IRQ_RAW_STATUS 292 
#define  ARIZONA_AOD_WKUP_AND_TRIG 291 
#define  ARIZONA_ASRC_STATUS 290 
#define  ARIZONA_ASYNC_SAMPLE_RATE_1_STATUS 289 
#define  ARIZONA_ASYNC_SAMPLE_RATE_2_STATUS 288 
#define  ARIZONA_CLOCK_CONTROL 287 
#define  ARIZONA_DEVICE_REVISION 286 
#define  ARIZONA_DSP1_CLOCKING_1 285 
#define  ARIZONA_DSP1_EXTERNAL_START_SELECT_1 284 
#define  ARIZONA_DSP1_RDMA_BUFFER_1 283 
#define  ARIZONA_DSP1_RDMA_BUFFER_2 282 
#define  ARIZONA_DSP1_RDMA_BUFFER_3 281 
#define  ARIZONA_DSP1_RDMA_BUFFER_4 280 
#define  ARIZONA_DSP1_RDMA_BUFFER_5 279 
#define  ARIZONA_DSP1_RDMA_BUFFER_6 278 
#define  ARIZONA_DSP1_RDMA_CONFIG_1 277 
#define  ARIZONA_DSP1_RDMA_OFFSET_1 276 
#define  ARIZONA_DSP1_SCRATCH_0 275 
#define  ARIZONA_DSP1_SCRATCH_1 274 
#define  ARIZONA_DSP1_SCRATCH_2 273 
#define  ARIZONA_DSP1_SCRATCH_3 272 
#define  ARIZONA_DSP1_STATUS_1 271 
#define  ARIZONA_DSP1_STATUS_2 270 
#define  ARIZONA_DSP1_STATUS_3 269 
#define  ARIZONA_DSP1_STATUS_4 268 
#define  ARIZONA_DSP1_WDMA_BUFFER_1 267 
#define  ARIZONA_DSP1_WDMA_BUFFER_2 266 
#define  ARIZONA_DSP1_WDMA_BUFFER_3 265 
#define  ARIZONA_DSP1_WDMA_BUFFER_4 264 
#define  ARIZONA_DSP1_WDMA_BUFFER_5 263 
#define  ARIZONA_DSP1_WDMA_BUFFER_6 262 
#define  ARIZONA_DSP1_WDMA_BUFFER_7 261 
#define  ARIZONA_DSP1_WDMA_BUFFER_8 260 
#define  ARIZONA_DSP1_WDMA_CONFIG_1 259 
#define  ARIZONA_DSP1_WDMA_CONFIG_2 258 
#define  ARIZONA_DSP1_WDMA_OFFSET_1 257 
#define  ARIZONA_DSP2_CLOCKING_1 256 
#define  ARIZONA_DSP2_EXTERNAL_START_SELECT_1 255 
#define  ARIZONA_DSP2_RDMA_BUFFER_1 254 
#define  ARIZONA_DSP2_RDMA_BUFFER_2 253 
#define  ARIZONA_DSP2_RDMA_BUFFER_3 252 
#define  ARIZONA_DSP2_RDMA_BUFFER_4 251 
#define  ARIZONA_DSP2_RDMA_BUFFER_5 250 
#define  ARIZONA_DSP2_RDMA_BUFFER_6 249 
#define  ARIZONA_DSP2_RDMA_CONFIG_1 248 
#define  ARIZONA_DSP2_RDMA_OFFSET_1 247 
#define  ARIZONA_DSP2_SCRATCH_0 246 
#define  ARIZONA_DSP2_SCRATCH_1 245 
#define  ARIZONA_DSP2_SCRATCH_2 244 
#define  ARIZONA_DSP2_SCRATCH_3 243 
#define  ARIZONA_DSP2_STATUS_1 242 
#define  ARIZONA_DSP2_STATUS_2 241 
#define  ARIZONA_DSP2_STATUS_3 240 
#define  ARIZONA_DSP2_STATUS_4 239 
#define  ARIZONA_DSP2_WDMA_BUFFER_1 238 
#define  ARIZONA_DSP2_WDMA_BUFFER_2 237 
#define  ARIZONA_DSP2_WDMA_BUFFER_3 236 
#define  ARIZONA_DSP2_WDMA_BUFFER_4 235 
#define  ARIZONA_DSP2_WDMA_BUFFER_5 234 
#define  ARIZONA_DSP2_WDMA_BUFFER_6 233 
#define  ARIZONA_DSP2_WDMA_BUFFER_7 232 
#define  ARIZONA_DSP2_WDMA_BUFFER_8 231 
#define  ARIZONA_DSP2_WDMA_CONFIG_1 230 
#define  ARIZONA_DSP2_WDMA_CONFIG_2 229 
#define  ARIZONA_DSP2_WDMA_OFFSET_1 228 
#define  ARIZONA_DSP3_CLOCKING_1 227 
#define  ARIZONA_DSP3_EXTERNAL_START_SELECT_1 226 
#define  ARIZONA_DSP3_RDMA_BUFFER_1 225 
#define  ARIZONA_DSP3_RDMA_BUFFER_2 224 
#define  ARIZONA_DSP3_RDMA_BUFFER_3 223 
#define  ARIZONA_DSP3_RDMA_BUFFER_4 222 
#define  ARIZONA_DSP3_RDMA_BUFFER_5 221 
#define  ARIZONA_DSP3_RDMA_BUFFER_6 220 
#define  ARIZONA_DSP3_RDMA_CONFIG_1 219 
#define  ARIZONA_DSP3_RDMA_OFFSET_1 218 
#define  ARIZONA_DSP3_SCRATCH_0 217 
#define  ARIZONA_DSP3_SCRATCH_1 216 
#define  ARIZONA_DSP3_SCRATCH_2 215 
#define  ARIZONA_DSP3_SCRATCH_3 214 
#define  ARIZONA_DSP3_STATUS_1 213 
#define  ARIZONA_DSP3_STATUS_2 212 
#define  ARIZONA_DSP3_STATUS_3 211 
#define  ARIZONA_DSP3_STATUS_4 210 
#define  ARIZONA_DSP3_WDMA_BUFFER_1 209 
#define  ARIZONA_DSP3_WDMA_BUFFER_2 208 
#define  ARIZONA_DSP3_WDMA_BUFFER_3 207 
#define  ARIZONA_DSP3_WDMA_BUFFER_4 206 
#define  ARIZONA_DSP3_WDMA_BUFFER_5 205 
#define  ARIZONA_DSP3_WDMA_BUFFER_6 204 
#define  ARIZONA_DSP3_WDMA_BUFFER_7 203 
#define  ARIZONA_DSP3_WDMA_BUFFER_8 202 
#define  ARIZONA_DSP3_WDMA_CONFIG_1 201 
#define  ARIZONA_DSP3_WDMA_CONFIG_2 200 
#define  ARIZONA_DSP3_WDMA_OFFSET_1 199 
#define  ARIZONA_DSP4_CLOCKING_1 198 
#define  ARIZONA_DSP4_EXTERNAL_START_SELECT_1 197 
#define  ARIZONA_DSP4_RDMA_BUFFER_1 196 
#define  ARIZONA_DSP4_RDMA_BUFFER_2 195 
#define  ARIZONA_DSP4_RDMA_BUFFER_3 194 
#define  ARIZONA_DSP4_RDMA_BUFFER_4 193 
#define  ARIZONA_DSP4_RDMA_BUFFER_5 192 
#define  ARIZONA_DSP4_RDMA_BUFFER_6 191 
#define  ARIZONA_DSP4_RDMA_CONFIG_1 190 
#define  ARIZONA_DSP4_RDMA_OFFSET_1 189 
#define  ARIZONA_DSP4_SCRATCH_0 188 
#define  ARIZONA_DSP4_SCRATCH_1 187 
#define  ARIZONA_DSP4_SCRATCH_2 186 
#define  ARIZONA_DSP4_SCRATCH_3 185 
#define  ARIZONA_DSP4_STATUS_1 184 
#define  ARIZONA_DSP4_STATUS_2 183 
#define  ARIZONA_DSP4_STATUS_3 182 
#define  ARIZONA_DSP4_STATUS_4 181 
#define  ARIZONA_DSP4_WDMA_BUFFER_1 180 
#define  ARIZONA_DSP4_WDMA_BUFFER_2 179 
#define  ARIZONA_DSP4_WDMA_BUFFER_3 178 
#define  ARIZONA_DSP4_WDMA_BUFFER_4 177 
#define  ARIZONA_DSP4_WDMA_BUFFER_5 176 
#define  ARIZONA_DSP4_WDMA_BUFFER_6 175 
#define  ARIZONA_DSP4_WDMA_BUFFER_7 174 
#define  ARIZONA_DSP4_WDMA_BUFFER_8 173 
#define  ARIZONA_DSP4_WDMA_CONFIG_1 172 
#define  ARIZONA_DSP4_WDMA_CONFIG_2 171 
#define  ARIZONA_DSP4_WDMA_OFFSET_1 170 
#define  ARIZONA_DSP_STATUS 169 
#define  ARIZONA_FX_CTRL2 168 
#define  ARIZONA_HAPTICS_STATUS 167 
#define  ARIZONA_HEADPHONE_DETECT_2 166 
#define  ARIZONA_HP_CTRL_1L 165 
#define  ARIZONA_HP_CTRL_1R 164 
#define  ARIZONA_HP_TEST_CTRL_1 163 
#define  ARIZONA_INPUT_ENABLES_STATUS 162 
#define  ARIZONA_INTERRUPT_RAW_STATUS_2 161 
#define  ARIZONA_INTERRUPT_RAW_STATUS_3 160 
#define  ARIZONA_INTERRUPT_RAW_STATUS_4 159 
#define  ARIZONA_INTERRUPT_RAW_STATUS_5 158 
#define  ARIZONA_INTERRUPT_RAW_STATUS_6 157 
#define  ARIZONA_INTERRUPT_RAW_STATUS_7 156 
#define  ARIZONA_INTERRUPT_RAW_STATUS_8 155 
#define  ARIZONA_INTERRUPT_RAW_STATUS_9 154 
#define  ARIZONA_INTERRUPT_STATUS_1 153 
#define  ARIZONA_INTERRUPT_STATUS_2 152 
#define  ARIZONA_INTERRUPT_STATUS_3 151 
#define  ARIZONA_INTERRUPT_STATUS_4 150 
#define  ARIZONA_INTERRUPT_STATUS_5 149 
#define  ARIZONA_INTERRUPT_STATUS_6 148 
#define  ARIZONA_IRQ2_STATUS_1 147 
#define  ARIZONA_IRQ2_STATUS_2 146 
#define  ARIZONA_IRQ2_STATUS_3 145 
#define  ARIZONA_IRQ2_STATUS_4 144 
#define  ARIZONA_IRQ2_STATUS_5 143 
#define  ARIZONA_IRQ2_STATUS_6 142 
#define  ARIZONA_IRQ_PIN_STATUS 141 
#define  ARIZONA_MIC_DETECT_3 140 
#define  ARIZONA_MIC_DETECT_4 139 
#define  ARIZONA_OUTPUT_STATUS_1 138 
#define  ARIZONA_RAW_OUTPUT_STATUS_1 137 
#define  ARIZONA_SAMPLE_RATE_1_STATUS 136 
#define  ARIZONA_SAMPLE_RATE_2_STATUS 135 
#define  ARIZONA_SAMPLE_RATE_3_STATUS 134 
#define  ARIZONA_SLIMBUS_RX_PORT_STATUS 133 
#define  ARIZONA_SLIMBUS_TX_PORT_STATUS 132 
#define  ARIZONA_SOFTWARE_RESET 131 
#define  ARIZONA_WRITE_SEQUENCER_CTRL_0 130 
#define  ARIZONA_WRITE_SEQUENCER_CTRL_1 129 
#define  ARIZONA_WRITE_SEQUENCER_CTRL_2 128 
 int wm5110_is_adsp_memory (struct device*,unsigned int) ; 

__attribute__((used)) static bool wm5110_volatile_register(struct device *dev, unsigned int reg)
{
	switch (reg) {
	case ARIZONA_SOFTWARE_RESET:
	case ARIZONA_DEVICE_REVISION:
	case ARIZONA_WRITE_SEQUENCER_CTRL_0:
	case ARIZONA_WRITE_SEQUENCER_CTRL_1:
	case ARIZONA_WRITE_SEQUENCER_CTRL_2:
	case ARIZONA_HAPTICS_STATUS:
	case ARIZONA_SAMPLE_RATE_1_STATUS:
	case ARIZONA_SAMPLE_RATE_2_STATUS:
	case ARIZONA_SAMPLE_RATE_3_STATUS:
	case ARIZONA_ASYNC_SAMPLE_RATE_1_STATUS:
	case ARIZONA_ASYNC_SAMPLE_RATE_2_STATUS:
	case ARIZONA_MIC_DETECT_3:
	case ARIZONA_MIC_DETECT_4:
	case ARIZONA_HP_CTRL_1L:
	case ARIZONA_HP_CTRL_1R:
	case ARIZONA_HEADPHONE_DETECT_2:
	case ARIZONA_INPUT_ENABLES_STATUS:
	case ARIZONA_OUTPUT_STATUS_1:
	case ARIZONA_RAW_OUTPUT_STATUS_1:
	case ARIZONA_HP_TEST_CTRL_1:
	case ARIZONA_SLIMBUS_RX_PORT_STATUS:
	case ARIZONA_SLIMBUS_TX_PORT_STATUS:
	case ARIZONA_INTERRUPT_STATUS_1:
	case ARIZONA_INTERRUPT_STATUS_2:
	case ARIZONA_INTERRUPT_STATUS_3:
	case ARIZONA_INTERRUPT_STATUS_4:
	case ARIZONA_INTERRUPT_STATUS_5:
	case ARIZONA_INTERRUPT_STATUS_6:
	case ARIZONA_IRQ2_STATUS_1:
	case ARIZONA_IRQ2_STATUS_2:
	case ARIZONA_IRQ2_STATUS_3:
	case ARIZONA_IRQ2_STATUS_4:
	case ARIZONA_IRQ2_STATUS_5:
	case ARIZONA_IRQ2_STATUS_6:
	case ARIZONA_INTERRUPT_RAW_STATUS_2:
	case ARIZONA_INTERRUPT_RAW_STATUS_3:
	case ARIZONA_INTERRUPT_RAW_STATUS_4:
	case ARIZONA_INTERRUPT_RAW_STATUS_5:
	case ARIZONA_INTERRUPT_RAW_STATUS_6:
	case ARIZONA_INTERRUPT_RAW_STATUS_7:
	case ARIZONA_INTERRUPT_RAW_STATUS_8:
	case ARIZONA_INTERRUPT_RAW_STATUS_9:
	case ARIZONA_IRQ_PIN_STATUS:
	case ARIZONA_AOD_WKUP_AND_TRIG:
	case ARIZONA_AOD_IRQ1:
	case ARIZONA_AOD_IRQ2:
	case ARIZONA_AOD_IRQ_RAW_STATUS:
	case ARIZONA_FX_CTRL2:
	case ARIZONA_ASRC_STATUS:
	case ARIZONA_CLOCK_CONTROL:
	case ARIZONA_DSP_STATUS:
	case ARIZONA_DSP1_STATUS_1:
	case ARIZONA_DSP1_STATUS_2:
	case ARIZONA_DSP1_STATUS_3:
	case ARIZONA_DSP1_STATUS_4:
	case ARIZONA_DSP1_WDMA_BUFFER_1:
	case ARIZONA_DSP1_WDMA_BUFFER_2:
	case ARIZONA_DSP1_WDMA_BUFFER_3:
	case ARIZONA_DSP1_WDMA_BUFFER_4:
	case ARIZONA_DSP1_WDMA_BUFFER_5:
	case ARIZONA_DSP1_WDMA_BUFFER_6:
	case ARIZONA_DSP1_WDMA_BUFFER_7:
	case ARIZONA_DSP1_WDMA_BUFFER_8:
	case ARIZONA_DSP1_RDMA_BUFFER_1:
	case ARIZONA_DSP1_RDMA_BUFFER_2:
	case ARIZONA_DSP1_RDMA_BUFFER_3:
	case ARIZONA_DSP1_RDMA_BUFFER_4:
	case ARIZONA_DSP1_RDMA_BUFFER_5:
	case ARIZONA_DSP1_RDMA_BUFFER_6:
	case ARIZONA_DSP1_WDMA_CONFIG_1:
	case ARIZONA_DSP1_WDMA_CONFIG_2:
	case ARIZONA_DSP1_WDMA_OFFSET_1:
	case ARIZONA_DSP1_RDMA_CONFIG_1:
	case ARIZONA_DSP1_RDMA_OFFSET_1:
	case ARIZONA_DSP1_EXTERNAL_START_SELECT_1:
	case ARIZONA_DSP1_SCRATCH_0:
	case ARIZONA_DSP1_SCRATCH_1:
	case ARIZONA_DSP1_SCRATCH_2:
	case ARIZONA_DSP1_SCRATCH_3:
	case ARIZONA_DSP1_CLOCKING_1:
	case ARIZONA_DSP2_STATUS_1:
	case ARIZONA_DSP2_STATUS_2:
	case ARIZONA_DSP2_STATUS_3:
	case ARIZONA_DSP2_STATUS_4:
	case ARIZONA_DSP2_WDMA_BUFFER_1:
	case ARIZONA_DSP2_WDMA_BUFFER_2:
	case ARIZONA_DSP2_WDMA_BUFFER_3:
	case ARIZONA_DSP2_WDMA_BUFFER_4:
	case ARIZONA_DSP2_WDMA_BUFFER_5:
	case ARIZONA_DSP2_WDMA_BUFFER_6:
	case ARIZONA_DSP2_WDMA_BUFFER_7:
	case ARIZONA_DSP2_WDMA_BUFFER_8:
	case ARIZONA_DSP2_RDMA_BUFFER_1:
	case ARIZONA_DSP2_RDMA_BUFFER_2:
	case ARIZONA_DSP2_RDMA_BUFFER_3:
	case ARIZONA_DSP2_RDMA_BUFFER_4:
	case ARIZONA_DSP2_RDMA_BUFFER_5:
	case ARIZONA_DSP2_RDMA_BUFFER_6:
	case ARIZONA_DSP2_WDMA_CONFIG_1:
	case ARIZONA_DSP2_WDMA_CONFIG_2:
	case ARIZONA_DSP2_WDMA_OFFSET_1:
	case ARIZONA_DSP2_RDMA_CONFIG_1:
	case ARIZONA_DSP2_RDMA_OFFSET_1:
	case ARIZONA_DSP2_EXTERNAL_START_SELECT_1:
	case ARIZONA_DSP2_SCRATCH_0:
	case ARIZONA_DSP2_SCRATCH_1:
	case ARIZONA_DSP2_SCRATCH_2:
	case ARIZONA_DSP2_SCRATCH_3:
	case ARIZONA_DSP2_CLOCKING_1:
	case ARIZONA_DSP3_STATUS_1:
	case ARIZONA_DSP3_STATUS_2:
	case ARIZONA_DSP3_STATUS_3:
	case ARIZONA_DSP3_STATUS_4:
	case ARIZONA_DSP3_WDMA_BUFFER_1:
	case ARIZONA_DSP3_WDMA_BUFFER_2:
	case ARIZONA_DSP3_WDMA_BUFFER_3:
	case ARIZONA_DSP3_WDMA_BUFFER_4:
	case ARIZONA_DSP3_WDMA_BUFFER_5:
	case ARIZONA_DSP3_WDMA_BUFFER_6:
	case ARIZONA_DSP3_WDMA_BUFFER_7:
	case ARIZONA_DSP3_WDMA_BUFFER_8:
	case ARIZONA_DSP3_RDMA_BUFFER_1:
	case ARIZONA_DSP3_RDMA_BUFFER_2:
	case ARIZONA_DSP3_RDMA_BUFFER_3:
	case ARIZONA_DSP3_RDMA_BUFFER_4:
	case ARIZONA_DSP3_RDMA_BUFFER_5:
	case ARIZONA_DSP3_RDMA_BUFFER_6:
	case ARIZONA_DSP3_WDMA_CONFIG_1:
	case ARIZONA_DSP3_WDMA_CONFIG_2:
	case ARIZONA_DSP3_WDMA_OFFSET_1:
	case ARIZONA_DSP3_RDMA_CONFIG_1:
	case ARIZONA_DSP3_RDMA_OFFSET_1:
	case ARIZONA_DSP3_EXTERNAL_START_SELECT_1:
	case ARIZONA_DSP3_SCRATCH_0:
	case ARIZONA_DSP3_SCRATCH_1:
	case ARIZONA_DSP3_SCRATCH_2:
	case ARIZONA_DSP3_SCRATCH_3:
	case ARIZONA_DSP3_CLOCKING_1:
	case ARIZONA_DSP4_STATUS_1:
	case ARIZONA_DSP4_STATUS_2:
	case ARIZONA_DSP4_STATUS_3:
	case ARIZONA_DSP4_STATUS_4:
	case ARIZONA_DSP4_WDMA_BUFFER_1:
	case ARIZONA_DSP4_WDMA_BUFFER_2:
	case ARIZONA_DSP4_WDMA_BUFFER_3:
	case ARIZONA_DSP4_WDMA_BUFFER_4:
	case ARIZONA_DSP4_WDMA_BUFFER_5:
	case ARIZONA_DSP4_WDMA_BUFFER_6:
	case ARIZONA_DSP4_WDMA_BUFFER_7:
	case ARIZONA_DSP4_WDMA_BUFFER_8:
	case ARIZONA_DSP4_RDMA_BUFFER_1:
	case ARIZONA_DSP4_RDMA_BUFFER_2:
	case ARIZONA_DSP4_RDMA_BUFFER_3:
	case ARIZONA_DSP4_RDMA_BUFFER_4:
	case ARIZONA_DSP4_RDMA_BUFFER_5:
	case ARIZONA_DSP4_RDMA_BUFFER_6:
	case ARIZONA_DSP4_WDMA_CONFIG_1:
	case ARIZONA_DSP4_WDMA_CONFIG_2:
	case ARIZONA_DSP4_WDMA_OFFSET_1:
	case ARIZONA_DSP4_RDMA_CONFIG_1:
	case ARIZONA_DSP4_RDMA_OFFSET_1:
	case ARIZONA_DSP4_EXTERNAL_START_SELECT_1:
	case ARIZONA_DSP4_SCRATCH_0:
	case ARIZONA_DSP4_SCRATCH_1:
	case ARIZONA_DSP4_SCRATCH_2:
	case ARIZONA_DSP4_SCRATCH_3:
	case ARIZONA_DSP4_CLOCKING_1:
		return true;
	default:
		return wm5110_is_adsp_memory(dev, reg);
	}
}