#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  scalar_t__ u8 ;
typedef  scalar_t__ u32 ;
typedef  int u16 ;
struct mlx5_core_dev {int dummy; } ;

/* Variables and functions */
 int EINVAL ; 
 int EIO ; 
#define  MLX5_CMD_OP_2ERR_QP 291 
#define  MLX5_CMD_OP_2RST_QP 290 
#define  MLX5_CMD_OP_ACCESS_REG 289 
#define  MLX5_CMD_OP_ADD_VXLAN_UDP_DPORT 288 
#define  MLX5_CMD_OP_ALLOC_ENCAP_HEADER 287 
#define  MLX5_CMD_OP_ALLOC_FLOW_COUNTER 286 
#define  MLX5_CMD_OP_ALLOC_MODIFY_HEADER_CONTEXT 285 
#define  MLX5_CMD_OP_ALLOC_PD 284 
#define  MLX5_CMD_OP_ALLOC_Q_COUNTER 283 
#define  MLX5_CMD_OP_ALLOC_TRANSPORT_DOMAIN 282 
#define  MLX5_CMD_OP_ALLOC_UAR 281 
#define  MLX5_CMD_OP_ALLOC_XRCD 280 
#define  MLX5_CMD_OP_ARM_DCT_FOR_KEY_VIOLATION 279 
#define  MLX5_CMD_OP_ARM_RQ 278 
#define  MLX5_CMD_OP_ARM_XRC_SRQ 277 
#define  MLX5_CMD_OP_ARM_XRQ 276 
#define  MLX5_CMD_OP_ATTACH_TO_MCG 275 
#define  MLX5_CMD_OP_CONFIG_INT_MODERATION 274 
#define  MLX5_CMD_OP_CREATE_CQ 273 
#define  MLX5_CMD_OP_CREATE_DCT 272 
#define  MLX5_CMD_OP_CREATE_EQ 271 
#define  MLX5_CMD_OP_CREATE_FLOW_GROUP 270 
#define  MLX5_CMD_OP_CREATE_FLOW_TABLE 269 
#define  MLX5_CMD_OP_CREATE_GENERAL_OBJECT 268 
#define  MLX5_CMD_OP_CREATE_LAG 267 
#define  MLX5_CMD_OP_CREATE_MKEY 266 
#define  MLX5_CMD_OP_CREATE_PSV 265 
#define  MLX5_CMD_OP_CREATE_QOS_PARA_VPORT 264 
#define  MLX5_CMD_OP_CREATE_QP 263 
#define  MLX5_CMD_OP_CREATE_RMP 262 
#define  MLX5_CMD_OP_CREATE_RQ 261 
#define  MLX5_CMD_OP_CREATE_RQT 260 
#define  MLX5_CMD_OP_CREATE_SCHEDULING_ELEMENT 259 
#define  MLX5_CMD_OP_CREATE_SQ 258 
#define  MLX5_CMD_OP_CREATE_SRQ 257 
#define  MLX5_CMD_OP_CREATE_TIR 256 
#define  MLX5_CMD_OP_CREATE_TIS 255 
#define  MLX5_CMD_OP_CREATE_VPORT_LAG 254 
#define  MLX5_CMD_OP_CREATE_XRC_SRQ 253 
#define  MLX5_CMD_OP_CREATE_XRQ 252 
#define  MLX5_CMD_OP_DEALLOC_ENCAP_HEADER 251 
#define  MLX5_CMD_OP_DEALLOC_FLOW_COUNTER 250 
#define  MLX5_CMD_OP_DEALLOC_MODIFY_HEADER_CONTEXT 249 
#define  MLX5_CMD_OP_DEALLOC_PD 248 
#define  MLX5_CMD_OP_DEALLOC_Q_COUNTER 247 
#define  MLX5_CMD_OP_DEALLOC_TRANSPORT_DOMAIN 246 
#define  MLX5_CMD_OP_DEALLOC_UAR 245 
#define  MLX5_CMD_OP_DEALLOC_XRCD 244 
#define  MLX5_CMD_OP_DELETE_FLOW_TABLE_ENTRY 243 
#define  MLX5_CMD_OP_DELETE_L2_TABLE_ENTRY 242 
#define  MLX5_CMD_OP_DELETE_VXLAN_UDP_DPORT 241 
#define  MLX5_CMD_OP_DESTROY_CQ 240 
#define  MLX5_CMD_OP_DESTROY_DCT 239 
#define  MLX5_CMD_OP_DESTROY_EQ 238 
#define  MLX5_CMD_OP_DESTROY_FLOW_GROUP 237 
#define  MLX5_CMD_OP_DESTROY_FLOW_TABLE 236 
#define  MLX5_CMD_OP_DESTROY_GENERAL_OBJECT 235 
#define  MLX5_CMD_OP_DESTROY_LAG 234 
#define  MLX5_CMD_OP_DESTROY_MKEY 233 
#define  MLX5_CMD_OP_DESTROY_PSV 232 
#define  MLX5_CMD_OP_DESTROY_QOS_PARA_VPORT 231 
#define  MLX5_CMD_OP_DESTROY_QP 230 
#define  MLX5_CMD_OP_DESTROY_RMP 229 
#define  MLX5_CMD_OP_DESTROY_RQ 228 
#define  MLX5_CMD_OP_DESTROY_RQT 227 
#define  MLX5_CMD_OP_DESTROY_SCHEDULING_ELEMENT 226 
#define  MLX5_CMD_OP_DESTROY_SQ 225 
#define  MLX5_CMD_OP_DESTROY_SRQ 224 
#define  MLX5_CMD_OP_DESTROY_TIR 223 
#define  MLX5_CMD_OP_DESTROY_TIS 222 
#define  MLX5_CMD_OP_DESTROY_VPORT_LAG 221 
#define  MLX5_CMD_OP_DESTROY_XRC_SRQ 220 
#define  MLX5_CMD_OP_DESTROY_XRQ 219 
#define  MLX5_CMD_OP_DETACH_FROM_MCG 218 
#define  MLX5_CMD_OP_DISABLE_HCA 217 
#define  MLX5_CMD_OP_DRAIN_DCT 216 
#define  MLX5_CMD_OP_ENABLE_HCA 215 
#define  MLX5_CMD_OP_FPGA_CREATE_QP 214 
#define  MLX5_CMD_OP_FPGA_DESTROY_QP 213 
#define  MLX5_CMD_OP_FPGA_MODIFY_QP 212 
#define  MLX5_CMD_OP_FPGA_QUERY_QP 211 
#define  MLX5_CMD_OP_FPGA_QUERY_QP_COUNTERS 210 
#define  MLX5_CMD_OP_GEN_EQE 209 
#define  MLX5_CMD_OP_GET_DROPPED_PACKET_LOG 208 
#define  MLX5_CMD_OP_INIT2INIT_QP 207 
#define  MLX5_CMD_OP_INIT2RTR_QP 206 
#define  MLX5_CMD_OP_INIT_HCA 205 
#define  MLX5_CMD_OP_MAD_IFC 204 
#define  MLX5_CMD_OP_MANAGE_PAGES 203 
#define  MLX5_CMD_OP_MODIFY_CONG_PARAMS 202 
#define  MLX5_CMD_OP_MODIFY_CONG_STATUS 201 
#define  MLX5_CMD_OP_MODIFY_CQ 200 
#define  MLX5_CMD_OP_MODIFY_ESW_VPORT_CONTEXT 199 
#define  MLX5_CMD_OP_MODIFY_FLOW_TABLE 198 
#define  MLX5_CMD_OP_MODIFY_GENERAL_OBJECT 197 
#define  MLX5_CMD_OP_MODIFY_HCA_VPORT_CONTEXT 196 
#define  MLX5_CMD_OP_MODIFY_LAG 195 
#define  MLX5_CMD_OP_MODIFY_NIC_VPORT_CONTEXT 194 
#define  MLX5_CMD_OP_MODIFY_RMP 193 
#define  MLX5_CMD_OP_MODIFY_RQ 192 
#define  MLX5_CMD_OP_MODIFY_RQT 191 
#define  MLX5_CMD_OP_MODIFY_SCHEDULING_ELEMENT 190 
#define  MLX5_CMD_OP_MODIFY_SQ 189 
#define  MLX5_CMD_OP_MODIFY_TIR 188 
#define  MLX5_CMD_OP_MODIFY_TIS 187 
#define  MLX5_CMD_OP_MODIFY_VPORT_STATE 186 
#define  MLX5_CMD_OP_NOP 185 
#define  MLX5_CMD_OP_PAGE_FAULT_RESUME 184 
#define  MLX5_CMD_OP_QUERY_ADAPTER 183 
#define  MLX5_CMD_OP_QUERY_CONG_PARAMS 182 
#define  MLX5_CMD_OP_QUERY_CONG_STATISTICS 181 
#define  MLX5_CMD_OP_QUERY_CONG_STATUS 180 
#define  MLX5_CMD_OP_QUERY_CQ 179 
#define  MLX5_CMD_OP_QUERY_DCT 178 
#define  MLX5_CMD_OP_QUERY_EQ 177 
#define  MLX5_CMD_OP_QUERY_ESW_VPORT_CONTEXT 176 
#define  MLX5_CMD_OP_QUERY_FLOW_COUNTER 175 
#define  MLX5_CMD_OP_QUERY_FLOW_GROUP 174 
#define  MLX5_CMD_OP_QUERY_FLOW_TABLE 173 
#define  MLX5_CMD_OP_QUERY_FLOW_TABLE_ENTRY 172 
#define  MLX5_CMD_OP_QUERY_GENERAL_OBJECT 171 
#define  MLX5_CMD_OP_QUERY_HCA_CAP 170 
#define  MLX5_CMD_OP_QUERY_HCA_VPORT_CONTEXT 169 
#define  MLX5_CMD_OP_QUERY_HCA_VPORT_GID 168 
#define  MLX5_CMD_OP_QUERY_HCA_VPORT_PKEY 167 
#define  MLX5_CMD_OP_QUERY_ISSI 166 
#define  MLX5_CMD_OP_QUERY_L2_TABLE_ENTRY 165 
#define  MLX5_CMD_OP_QUERY_LAG 164 
#define  MLX5_CMD_OP_QUERY_MAD_DEMUX 163 
#define  MLX5_CMD_OP_QUERY_MKEY 162 
#define  MLX5_CMD_OP_QUERY_NIC_VPORT_CONTEXT 161 
#define  MLX5_CMD_OP_QUERY_PAGES 160 
#define  MLX5_CMD_OP_QUERY_QP 159 
#define  MLX5_CMD_OP_QUERY_Q_COUNTER 158 
#define  MLX5_CMD_OP_QUERY_RATE_LIMIT 157 
#define  MLX5_CMD_OP_QUERY_RMP 156 
#define  MLX5_CMD_OP_QUERY_ROCE_ADDRESS 155 
#define  MLX5_CMD_OP_QUERY_RQ 154 
#define  MLX5_CMD_OP_QUERY_RQT 153 
#define  MLX5_CMD_OP_QUERY_SCHEDULING_ELEMENT 152 
#define  MLX5_CMD_OP_QUERY_SPECIAL_CONTEXTS 151 
#define  MLX5_CMD_OP_QUERY_SQ 150 
#define  MLX5_CMD_OP_QUERY_SRQ 149 
#define  MLX5_CMD_OP_QUERY_TIR 148 
#define  MLX5_CMD_OP_QUERY_TIS 147 
#define  MLX5_CMD_OP_QUERY_VNIC_ENV 146 
#define  MLX5_CMD_OP_QUERY_VPORT_COUNTER 145 
#define  MLX5_CMD_OP_QUERY_VPORT_STATE 144 
#define  MLX5_CMD_OP_QUERY_XRC_SRQ 143 
#define  MLX5_CMD_OP_QUERY_XRQ 142 
#define  MLX5_CMD_OP_RST2INIT_QP 141 
#define  MLX5_CMD_OP_RTR2RTS_QP 140 
#define  MLX5_CMD_OP_RTS2RTS_QP 139 
#define  MLX5_CMD_OP_SET_FLOW_TABLE_ENTRY 138 
#define  MLX5_CMD_OP_SET_FLOW_TABLE_ROOT 137 
#define  MLX5_CMD_OP_SET_HCA_CAP 136 
#define  MLX5_CMD_OP_SET_ISSI 135 
#define  MLX5_CMD_OP_SET_L2_TABLE_ENTRY 134 
#define  MLX5_CMD_OP_SET_MAD_DEMUX 133 
#define  MLX5_CMD_OP_SET_PP_RATE_LIMIT 132 
#define  MLX5_CMD_OP_SET_ROCE_ADDRESS 131 
#define  MLX5_CMD_OP_SQD_RTS_QP 130 
#define  MLX5_CMD_OP_SQERR2RTS_QP 129 
#define  MLX5_CMD_OP_TEARDOWN_HCA 128 
 int MLX5_CMD_STAT_OK ; 
 scalar_t__ MLX5_DRIVER_STATUS_ABORTED ; 
 scalar_t__ MLX5_DRIVER_SYND ; 
 int /*<<< orphan*/  mlx5_core_err (struct mlx5_core_dev*,char*,int) ; 

__attribute__((used)) static int mlx5_internal_err_ret_value(struct mlx5_core_dev *dev, u16 op,
				       u32 *synd, u8 *status)
{
	*synd = 0;
	*status = 0;

	switch (op) {
	case MLX5_CMD_OP_TEARDOWN_HCA:
	case MLX5_CMD_OP_DISABLE_HCA:
	case MLX5_CMD_OP_MANAGE_PAGES:
	case MLX5_CMD_OP_DESTROY_MKEY:
	case MLX5_CMD_OP_DESTROY_EQ:
	case MLX5_CMD_OP_DESTROY_CQ:
	case MLX5_CMD_OP_DESTROY_QP:
	case MLX5_CMD_OP_DESTROY_PSV:
	case MLX5_CMD_OP_DESTROY_SRQ:
	case MLX5_CMD_OP_DESTROY_XRC_SRQ:
	case MLX5_CMD_OP_DESTROY_XRQ:
	case MLX5_CMD_OP_DESTROY_DCT:
	case MLX5_CMD_OP_DEALLOC_Q_COUNTER:
	case MLX5_CMD_OP_DESTROY_SCHEDULING_ELEMENT:
	case MLX5_CMD_OP_DESTROY_QOS_PARA_VPORT:
	case MLX5_CMD_OP_DEALLOC_PD:
	case MLX5_CMD_OP_DEALLOC_UAR:
	case MLX5_CMD_OP_DETACH_FROM_MCG:
	case MLX5_CMD_OP_DEALLOC_XRCD:
	case MLX5_CMD_OP_DEALLOC_TRANSPORT_DOMAIN:
	case MLX5_CMD_OP_DELETE_VXLAN_UDP_DPORT:
	case MLX5_CMD_OP_DELETE_L2_TABLE_ENTRY:
	case MLX5_CMD_OP_DESTROY_LAG:
	case MLX5_CMD_OP_DESTROY_VPORT_LAG:
	case MLX5_CMD_OP_DESTROY_TIR:
	case MLX5_CMD_OP_DESTROY_SQ:
	case MLX5_CMD_OP_DESTROY_RQ:
	case MLX5_CMD_OP_DESTROY_RMP:
	case MLX5_CMD_OP_DESTROY_TIS:
	case MLX5_CMD_OP_DESTROY_RQT:
	case MLX5_CMD_OP_DESTROY_FLOW_TABLE:
	case MLX5_CMD_OP_DESTROY_FLOW_GROUP:
	case MLX5_CMD_OP_DELETE_FLOW_TABLE_ENTRY:
	case MLX5_CMD_OP_DEALLOC_FLOW_COUNTER:
	case MLX5_CMD_OP_2ERR_QP:
	case MLX5_CMD_OP_2RST_QP:
	case MLX5_CMD_OP_MODIFY_NIC_VPORT_CONTEXT:
	case MLX5_CMD_OP_MODIFY_FLOW_TABLE:
	case MLX5_CMD_OP_SET_FLOW_TABLE_ENTRY:
	case MLX5_CMD_OP_SET_FLOW_TABLE_ROOT:
	case MLX5_CMD_OP_DEALLOC_ENCAP_HEADER:
	case MLX5_CMD_OP_DEALLOC_MODIFY_HEADER_CONTEXT:
	case MLX5_CMD_OP_FPGA_DESTROY_QP:
	case MLX5_CMD_OP_DESTROY_GENERAL_OBJECT:
		return MLX5_CMD_STAT_OK;

	case MLX5_CMD_OP_QUERY_HCA_CAP:
	case MLX5_CMD_OP_QUERY_ADAPTER:
	case MLX5_CMD_OP_INIT_HCA:
	case MLX5_CMD_OP_ENABLE_HCA:
	case MLX5_CMD_OP_QUERY_PAGES:
	case MLX5_CMD_OP_SET_HCA_CAP:
	case MLX5_CMD_OP_QUERY_ISSI:
	case MLX5_CMD_OP_SET_ISSI:
	case MLX5_CMD_OP_CREATE_MKEY:
	case MLX5_CMD_OP_QUERY_MKEY:
	case MLX5_CMD_OP_QUERY_SPECIAL_CONTEXTS:
	case MLX5_CMD_OP_PAGE_FAULT_RESUME:
	case MLX5_CMD_OP_CREATE_EQ:
	case MLX5_CMD_OP_QUERY_EQ:
	case MLX5_CMD_OP_GEN_EQE:
	case MLX5_CMD_OP_CREATE_CQ:
	case MLX5_CMD_OP_QUERY_CQ:
	case MLX5_CMD_OP_MODIFY_CQ:
	case MLX5_CMD_OP_CREATE_QP:
	case MLX5_CMD_OP_RST2INIT_QP:
	case MLX5_CMD_OP_INIT2RTR_QP:
	case MLX5_CMD_OP_RTR2RTS_QP:
	case MLX5_CMD_OP_RTS2RTS_QP:
	case MLX5_CMD_OP_SQERR2RTS_QP:
	case MLX5_CMD_OP_QUERY_QP:
	case MLX5_CMD_OP_SQD_RTS_QP:
	case MLX5_CMD_OP_INIT2INIT_QP:
	case MLX5_CMD_OP_CREATE_PSV:
	case MLX5_CMD_OP_CREATE_SRQ:
	case MLX5_CMD_OP_QUERY_SRQ:
	case MLX5_CMD_OP_ARM_RQ:
	case MLX5_CMD_OP_CREATE_XRC_SRQ:
	case MLX5_CMD_OP_QUERY_XRC_SRQ:
	case MLX5_CMD_OP_ARM_XRC_SRQ:
	case MLX5_CMD_OP_CREATE_XRQ:
	case MLX5_CMD_OP_QUERY_XRQ:
	case MLX5_CMD_OP_ARM_XRQ:
	case MLX5_CMD_OP_CREATE_DCT:
	case MLX5_CMD_OP_DRAIN_DCT:
	case MLX5_CMD_OP_QUERY_DCT:
	case MLX5_CMD_OP_ARM_DCT_FOR_KEY_VIOLATION:
	case MLX5_CMD_OP_QUERY_VPORT_STATE:
	case MLX5_CMD_OP_MODIFY_VPORT_STATE:
	case MLX5_CMD_OP_QUERY_ESW_VPORT_CONTEXT:
	case MLX5_CMD_OP_MODIFY_ESW_VPORT_CONTEXT:
	case MLX5_CMD_OP_QUERY_NIC_VPORT_CONTEXT:
	case MLX5_CMD_OP_QUERY_ROCE_ADDRESS:
	case MLX5_CMD_OP_SET_ROCE_ADDRESS:
	case MLX5_CMD_OP_QUERY_HCA_VPORT_CONTEXT:
	case MLX5_CMD_OP_MODIFY_HCA_VPORT_CONTEXT:
	case MLX5_CMD_OP_QUERY_HCA_VPORT_GID:
	case MLX5_CMD_OP_QUERY_HCA_VPORT_PKEY:
	case MLX5_CMD_OP_QUERY_VNIC_ENV:
	case MLX5_CMD_OP_QUERY_VPORT_COUNTER:
	case MLX5_CMD_OP_ALLOC_Q_COUNTER:
	case MLX5_CMD_OP_QUERY_Q_COUNTER:
	case MLX5_CMD_OP_SET_PP_RATE_LIMIT:
	case MLX5_CMD_OP_QUERY_RATE_LIMIT:
	case MLX5_CMD_OP_CREATE_SCHEDULING_ELEMENT:
	case MLX5_CMD_OP_QUERY_SCHEDULING_ELEMENT:
	case MLX5_CMD_OP_MODIFY_SCHEDULING_ELEMENT:
	case MLX5_CMD_OP_CREATE_QOS_PARA_VPORT:
	case MLX5_CMD_OP_ALLOC_PD:
	case MLX5_CMD_OP_ALLOC_UAR:
	case MLX5_CMD_OP_CONFIG_INT_MODERATION:
	case MLX5_CMD_OP_ACCESS_REG:
	case MLX5_CMD_OP_ATTACH_TO_MCG:
	case MLX5_CMD_OP_GET_DROPPED_PACKET_LOG:
	case MLX5_CMD_OP_MAD_IFC:
	case MLX5_CMD_OP_QUERY_MAD_DEMUX:
	case MLX5_CMD_OP_SET_MAD_DEMUX:
	case MLX5_CMD_OP_NOP:
	case MLX5_CMD_OP_ALLOC_XRCD:
	case MLX5_CMD_OP_ALLOC_TRANSPORT_DOMAIN:
	case MLX5_CMD_OP_QUERY_CONG_STATUS:
	case MLX5_CMD_OP_MODIFY_CONG_STATUS:
	case MLX5_CMD_OP_QUERY_CONG_PARAMS:
	case MLX5_CMD_OP_MODIFY_CONG_PARAMS:
	case MLX5_CMD_OP_QUERY_CONG_STATISTICS:
	case MLX5_CMD_OP_ADD_VXLAN_UDP_DPORT:
	case MLX5_CMD_OP_SET_L2_TABLE_ENTRY:
	case MLX5_CMD_OP_QUERY_L2_TABLE_ENTRY:
	case MLX5_CMD_OP_CREATE_LAG:
	case MLX5_CMD_OP_MODIFY_LAG:
	case MLX5_CMD_OP_QUERY_LAG:
	case MLX5_CMD_OP_CREATE_VPORT_LAG:
	case MLX5_CMD_OP_CREATE_TIR:
	case MLX5_CMD_OP_MODIFY_TIR:
	case MLX5_CMD_OP_QUERY_TIR:
	case MLX5_CMD_OP_CREATE_SQ:
	case MLX5_CMD_OP_MODIFY_SQ:
	case MLX5_CMD_OP_QUERY_SQ:
	case MLX5_CMD_OP_CREATE_RQ:
	case MLX5_CMD_OP_MODIFY_RQ:
	case MLX5_CMD_OP_QUERY_RQ:
	case MLX5_CMD_OP_CREATE_RMP:
	case MLX5_CMD_OP_MODIFY_RMP:
	case MLX5_CMD_OP_QUERY_RMP:
	case MLX5_CMD_OP_CREATE_TIS:
	case MLX5_CMD_OP_MODIFY_TIS:
	case MLX5_CMD_OP_QUERY_TIS:
	case MLX5_CMD_OP_CREATE_RQT:
	case MLX5_CMD_OP_MODIFY_RQT:
	case MLX5_CMD_OP_QUERY_RQT:

	case MLX5_CMD_OP_CREATE_FLOW_TABLE:
	case MLX5_CMD_OP_QUERY_FLOW_TABLE:
	case MLX5_CMD_OP_CREATE_FLOW_GROUP:
	case MLX5_CMD_OP_QUERY_FLOW_GROUP:
	case MLX5_CMD_OP_QUERY_FLOW_TABLE_ENTRY:
	case MLX5_CMD_OP_ALLOC_FLOW_COUNTER:
	case MLX5_CMD_OP_QUERY_FLOW_COUNTER:
	case MLX5_CMD_OP_ALLOC_ENCAP_HEADER:
	case MLX5_CMD_OP_ALLOC_MODIFY_HEADER_CONTEXT:
	case MLX5_CMD_OP_FPGA_CREATE_QP:
	case MLX5_CMD_OP_FPGA_MODIFY_QP:
	case MLX5_CMD_OP_FPGA_QUERY_QP:
	case MLX5_CMD_OP_FPGA_QUERY_QP_COUNTERS:
	case MLX5_CMD_OP_CREATE_GENERAL_OBJECT:
	case MLX5_CMD_OP_MODIFY_GENERAL_OBJECT:
	case MLX5_CMD_OP_QUERY_GENERAL_OBJECT:
		*status = MLX5_DRIVER_STATUS_ABORTED;
		*synd = MLX5_DRIVER_SYND;
		return -EIO;
	default:
		mlx5_core_err(dev, "Unknown FW command (%d)\n", op);
		return -EINVAL;
	}
}