#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  int u32 ;
struct isp_device {int dummy; } ;
struct isp_csi2_device {int /*<<< orphan*/  regs1; } ;

/* Variables and functions */
 int /*<<< orphan*/  ISPCSI2_PHY_IRQENABLE ; 
 int ISPCSI2_PHY_IRQENABLE_ERRCONTROL1 ; 
 int ISPCSI2_PHY_IRQENABLE_ERRCONTROL2 ; 
 int ISPCSI2_PHY_IRQENABLE_ERRCONTROL3 ; 
 int ISPCSI2_PHY_IRQENABLE_ERRCONTROL4 ; 
 int ISPCSI2_PHY_IRQENABLE_ERRCONTROL5 ; 
 int ISPCSI2_PHY_IRQENABLE_ERRESC1 ; 
 int ISPCSI2_PHY_IRQENABLE_ERRESC2 ; 
 int ISPCSI2_PHY_IRQENABLE_ERRESC3 ; 
 int ISPCSI2_PHY_IRQENABLE_ERRESC4 ; 
 int ISPCSI2_PHY_IRQENABLE_ERRESC5 ; 
 int ISPCSI2_PHY_IRQENABLE_ERRSOTHS1 ; 
 int ISPCSI2_PHY_IRQENABLE_ERRSOTHS2 ; 
 int ISPCSI2_PHY_IRQENABLE_ERRSOTHS3 ; 
 int ISPCSI2_PHY_IRQENABLE_ERRSOTHS4 ; 
 int ISPCSI2_PHY_IRQENABLE_ERRSOTHS5 ; 
 int ISPCSI2_PHY_IRQENABLE_ERRSOTSYNCHS1 ; 
 int ISPCSI2_PHY_IRQENABLE_ERRSOTSYNCHS2 ; 
 int ISPCSI2_PHY_IRQENABLE_ERRSOTSYNCHS3 ; 
 int ISPCSI2_PHY_IRQENABLE_ERRSOTSYNCHS4 ; 
 int ISPCSI2_PHY_IRQENABLE_ERRSOTSYNCHS5 ; 
 int ISPCSI2_PHY_IRQENABLE_STATEALLULPMENTER ; 
 int ISPCSI2_PHY_IRQENABLE_STATEALLULPMEXIT ; 
 int ISPCSI2_PHY_IRQENABLE_STATEULPM1 ; 
 int ISPCSI2_PHY_IRQENABLE_STATEULPM2 ; 
 int ISPCSI2_PHY_IRQENABLE_STATEULPM3 ; 
 int ISPCSI2_PHY_IRQENABLE_STATEULPM4 ; 
 int ISPCSI2_PHY_IRQENABLE_STATEULPM5 ; 
 int /*<<< orphan*/  ISPCSI2_PHY_IRQSTATUS ; 
 int isp_reg_readl (struct isp_device*,int /*<<< orphan*/ ,int /*<<< orphan*/ ) ; 
 int /*<<< orphan*/  isp_reg_writel (struct isp_device*,int,int /*<<< orphan*/ ,int /*<<< orphan*/ ) ; 

__attribute__((used)) static void csi2_irq_complexio1_set(struct isp_device *isp,
				    struct isp_csi2_device *csi2, int enable)
{
	u32 reg;
	reg = ISPCSI2_PHY_IRQENABLE_STATEALLULPMEXIT |
		ISPCSI2_PHY_IRQENABLE_STATEALLULPMENTER |
		ISPCSI2_PHY_IRQENABLE_STATEULPM5 |
		ISPCSI2_PHY_IRQENABLE_ERRCONTROL5 |
		ISPCSI2_PHY_IRQENABLE_ERRESC5 |
		ISPCSI2_PHY_IRQENABLE_ERRSOTSYNCHS5 |
		ISPCSI2_PHY_IRQENABLE_ERRSOTHS5 |
		ISPCSI2_PHY_IRQENABLE_STATEULPM4 |
		ISPCSI2_PHY_IRQENABLE_ERRCONTROL4 |
		ISPCSI2_PHY_IRQENABLE_ERRESC4 |
		ISPCSI2_PHY_IRQENABLE_ERRSOTSYNCHS4 |
		ISPCSI2_PHY_IRQENABLE_ERRSOTHS4 |
		ISPCSI2_PHY_IRQENABLE_STATEULPM3 |
		ISPCSI2_PHY_IRQENABLE_ERRCONTROL3 |
		ISPCSI2_PHY_IRQENABLE_ERRESC3 |
		ISPCSI2_PHY_IRQENABLE_ERRSOTSYNCHS3 |
		ISPCSI2_PHY_IRQENABLE_ERRSOTHS3 |
		ISPCSI2_PHY_IRQENABLE_STATEULPM2 |
		ISPCSI2_PHY_IRQENABLE_ERRCONTROL2 |
		ISPCSI2_PHY_IRQENABLE_ERRESC2 |
		ISPCSI2_PHY_IRQENABLE_ERRSOTSYNCHS2 |
		ISPCSI2_PHY_IRQENABLE_ERRSOTHS2 |
		ISPCSI2_PHY_IRQENABLE_STATEULPM1 |
		ISPCSI2_PHY_IRQENABLE_ERRCONTROL1 |
		ISPCSI2_PHY_IRQENABLE_ERRESC1 |
		ISPCSI2_PHY_IRQENABLE_ERRSOTSYNCHS1 |
		ISPCSI2_PHY_IRQENABLE_ERRSOTHS1;
	isp_reg_writel(isp, reg, csi2->regs1, ISPCSI2_PHY_IRQSTATUS);
	if (enable)
		reg |= isp_reg_readl(isp, csi2->regs1, ISPCSI2_PHY_IRQENABLE);
	else
		reg = 0;
	isp_reg_writel(isp, reg, csi2->regs1, ISPCSI2_PHY_IRQENABLE);
}