#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  int /*<<< orphan*/  uint8_t ;
typedef  enum encoder_id { ____Placeholder_encoder_id } encoder_id ;

/* Variables and functions */
 int /*<<< orphan*/  BREAK_TO_DEBUGGER () ; 
#define  ENCODER_ID_EXTERNAL_MVPU_FPGA 149 
#define  ENCODER_ID_EXTERNAL_NUTMEG 148 
#define  ENCODER_ID_EXTERNAL_TRAVIS 147 
#define  ENCODER_ID_INTERNAL_DAC1 146 
#define  ENCODER_ID_INTERNAL_DAC2 145 
#define  ENCODER_ID_INTERNAL_DDI 144 
#define  ENCODER_ID_INTERNAL_HDMI 143 
#define  ENCODER_ID_INTERNAL_KLDSCP_DAC1 142 
#define  ENCODER_ID_INTERNAL_KLDSCP_DAC2 141 
#define  ENCODER_ID_INTERNAL_KLDSCP_LVTMA 140 
#define  ENCODER_ID_INTERNAL_KLDSCP_TMDS1 139 
#define  ENCODER_ID_INTERNAL_LVDS 138 
#define  ENCODER_ID_INTERNAL_LVTM1 137 
#define  ENCODER_ID_INTERNAL_TMDS1 136 
#define  ENCODER_ID_INTERNAL_TMDS2 135 
#define  ENCODER_ID_INTERNAL_UNIPHY 134 
#define  ENCODER_ID_INTERNAL_UNIPHY1 133 
#define  ENCODER_ID_INTERNAL_UNIPHY2 132 
#define  ENCODER_ID_INTERNAL_UNIPHY3 131 
#define  ENCODER_ID_INTERNAL_VIRTUAL 130 
#define  ENCODER_ID_INTERNAL_WIRELESS 129 
#define  ENCODER_ID_UNKNOWN 128 
 int /*<<< orphan*/  ENCODER_OBJECT_ID_HDMI_INTERNAL ; 
 int /*<<< orphan*/  ENCODER_OBJECT_ID_INTERNAL_DAC1 ; 
 int /*<<< orphan*/  ENCODER_OBJECT_ID_INTERNAL_DAC2 ; 
 int /*<<< orphan*/  ENCODER_OBJECT_ID_INTERNAL_DDI ; 
 int /*<<< orphan*/  ENCODER_OBJECT_ID_INTERNAL_KLDSCP_DAC1 ; 
 int /*<<< orphan*/  ENCODER_OBJECT_ID_INTERNAL_KLDSCP_DAC2 ; 
 int /*<<< orphan*/  ENCODER_OBJECT_ID_INTERNAL_KLDSCP_LVTMA ; 
 int /*<<< orphan*/  ENCODER_OBJECT_ID_INTERNAL_KLDSCP_TMDS1 ; 
 int /*<<< orphan*/  ENCODER_OBJECT_ID_INTERNAL_LVDS ; 
 int /*<<< orphan*/  ENCODER_OBJECT_ID_INTERNAL_LVTM1 ; 
 int /*<<< orphan*/  ENCODER_OBJECT_ID_INTERNAL_TMDS1 ; 
 int /*<<< orphan*/  ENCODER_OBJECT_ID_INTERNAL_TMDS2 ; 
 int /*<<< orphan*/  ENCODER_OBJECT_ID_INTERNAL_UNIPHY ; 
 int /*<<< orphan*/  ENCODER_OBJECT_ID_INTERNAL_UNIPHY1 ; 
 int /*<<< orphan*/  ENCODER_OBJECT_ID_INTERNAL_UNIPHY2 ; 
 int /*<<< orphan*/  ENCODER_OBJECT_ID_INTERNAL_UNIPHY3 ; 
 int /*<<< orphan*/  ENCODER_OBJECT_ID_INTERNAL_VCE ; 
 int /*<<< orphan*/  ENCODER_OBJECT_ID_MVPU_FPGA ; 
 int /*<<< orphan*/  ENCODER_OBJECT_ID_NONE ; 
 int /*<<< orphan*/  ENCODER_OBJECT_ID_NUTMEG ; 
 int /*<<< orphan*/  ENCODER_OBJECT_ID_TRAVIS ; 

uint8_t dal_cmd_table_helper_encoder_id_to_atom2(
	enum encoder_id id)
{
	switch (id) {
	case ENCODER_ID_INTERNAL_LVDS:
		return ENCODER_OBJECT_ID_INTERNAL_LVDS;
	case ENCODER_ID_INTERNAL_TMDS1:
		return ENCODER_OBJECT_ID_INTERNAL_TMDS1;
	case ENCODER_ID_INTERNAL_TMDS2:
		return ENCODER_OBJECT_ID_INTERNAL_TMDS2;
	case ENCODER_ID_INTERNAL_DAC1:
		return ENCODER_OBJECT_ID_INTERNAL_DAC1;
	case ENCODER_ID_INTERNAL_DAC2:
		return ENCODER_OBJECT_ID_INTERNAL_DAC2;
	case ENCODER_ID_INTERNAL_LVTM1:
		return ENCODER_OBJECT_ID_INTERNAL_LVTM1;
	case ENCODER_ID_INTERNAL_HDMI:
		return ENCODER_OBJECT_ID_HDMI_INTERNAL;
	case ENCODER_ID_EXTERNAL_TRAVIS:
		return ENCODER_OBJECT_ID_TRAVIS;
	case ENCODER_ID_EXTERNAL_NUTMEG:
		return ENCODER_OBJECT_ID_NUTMEG;
	case ENCODER_ID_INTERNAL_KLDSCP_TMDS1:
		return ENCODER_OBJECT_ID_INTERNAL_KLDSCP_TMDS1;
	case ENCODER_ID_INTERNAL_KLDSCP_DAC1:
		return ENCODER_OBJECT_ID_INTERNAL_KLDSCP_DAC1;
	case ENCODER_ID_INTERNAL_KLDSCP_DAC2:
		return ENCODER_OBJECT_ID_INTERNAL_KLDSCP_DAC2;
	case ENCODER_ID_EXTERNAL_MVPU_FPGA:
		return ENCODER_OBJECT_ID_MVPU_FPGA;
	case ENCODER_ID_INTERNAL_DDI:
		return ENCODER_OBJECT_ID_INTERNAL_DDI;
	case ENCODER_ID_INTERNAL_UNIPHY:
		return ENCODER_OBJECT_ID_INTERNAL_UNIPHY;
	case ENCODER_ID_INTERNAL_KLDSCP_LVTMA:
		return ENCODER_OBJECT_ID_INTERNAL_KLDSCP_LVTMA;
	case ENCODER_ID_INTERNAL_UNIPHY1:
		return ENCODER_OBJECT_ID_INTERNAL_UNIPHY1;
	case ENCODER_ID_INTERNAL_UNIPHY2:
		return ENCODER_OBJECT_ID_INTERNAL_UNIPHY2;
	case ENCODER_ID_INTERNAL_UNIPHY3:
		return ENCODER_OBJECT_ID_INTERNAL_UNIPHY3;
	case ENCODER_ID_INTERNAL_WIRELESS:
		return ENCODER_OBJECT_ID_INTERNAL_VCE;
	case ENCODER_ID_INTERNAL_VIRTUAL:
		return ENCODER_OBJECT_ID_NONE;
	case ENCODER_ID_UNKNOWN:
		return ENCODER_OBJECT_ID_NONE;
	default:
		/* Invalid encoder id */
		BREAK_TO_DEBUGGER();
		return ENCODER_OBJECT_ID_NONE;
	}
}