#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
struct device {int dummy; } ;

/* Variables and functions */
#define  ARIZONA_ACCESSORY_DETECT_MODE_1 808 
#define  ARIZONA_ADC_DIGITAL_VOLUME_1L 807 
#define  ARIZONA_ADC_DIGITAL_VOLUME_1R 806 
#define  ARIZONA_ADC_DIGITAL_VOLUME_2L 805 
#define  ARIZONA_AIF1TX1MIX_INPUT_1_SOURCE 804 
#define  ARIZONA_AIF1TX1MIX_INPUT_1_VOLUME 803 
#define  ARIZONA_AIF1TX1MIX_INPUT_2_SOURCE 802 
#define  ARIZONA_AIF1TX1MIX_INPUT_2_VOLUME 801 
#define  ARIZONA_AIF1TX1MIX_INPUT_3_SOURCE 800 
#define  ARIZONA_AIF1TX1MIX_INPUT_3_VOLUME 799 
#define  ARIZONA_AIF1TX1MIX_INPUT_4_SOURCE 798 
#define  ARIZONA_AIF1TX1MIX_INPUT_4_VOLUME 797 
#define  ARIZONA_AIF1TX2MIX_INPUT_1_SOURCE 796 
#define  ARIZONA_AIF1TX2MIX_INPUT_1_VOLUME 795 
#define  ARIZONA_AIF1TX2MIX_INPUT_2_SOURCE 794 
#define  ARIZONA_AIF1TX2MIX_INPUT_2_VOLUME 793 
#define  ARIZONA_AIF1TX2MIX_INPUT_3_SOURCE 792 
#define  ARIZONA_AIF1TX2MIX_INPUT_3_VOLUME 791 
#define  ARIZONA_AIF1TX2MIX_INPUT_4_SOURCE 790 
#define  ARIZONA_AIF1TX2MIX_INPUT_4_VOLUME 789 
#define  ARIZONA_AIF1TX3MIX_INPUT_1_SOURCE 788 
#define  ARIZONA_AIF1TX3MIX_INPUT_1_VOLUME 787 
#define  ARIZONA_AIF1TX3MIX_INPUT_2_SOURCE 786 
#define  ARIZONA_AIF1TX3MIX_INPUT_2_VOLUME 785 
#define  ARIZONA_AIF1TX3MIX_INPUT_3_SOURCE 784 
#define  ARIZONA_AIF1TX3MIX_INPUT_3_VOLUME 783 
#define  ARIZONA_AIF1TX3MIX_INPUT_4_SOURCE 782 
#define  ARIZONA_AIF1TX3MIX_INPUT_4_VOLUME 781 
#define  ARIZONA_AIF1TX4MIX_INPUT_1_SOURCE 780 
#define  ARIZONA_AIF1TX4MIX_INPUT_1_VOLUME 779 
#define  ARIZONA_AIF1TX4MIX_INPUT_2_SOURCE 778 
#define  ARIZONA_AIF1TX4MIX_INPUT_2_VOLUME 777 
#define  ARIZONA_AIF1TX4MIX_INPUT_3_SOURCE 776 
#define  ARIZONA_AIF1TX4MIX_INPUT_3_VOLUME 775 
#define  ARIZONA_AIF1TX4MIX_INPUT_4_SOURCE 774 
#define  ARIZONA_AIF1TX4MIX_INPUT_4_VOLUME 773 
#define  ARIZONA_AIF1TX5MIX_INPUT_1_SOURCE 772 
#define  ARIZONA_AIF1TX5MIX_INPUT_1_VOLUME 771 
#define  ARIZONA_AIF1TX5MIX_INPUT_2_SOURCE 770 
#define  ARIZONA_AIF1TX5MIX_INPUT_2_VOLUME 769 
#define  ARIZONA_AIF1TX5MIX_INPUT_3_SOURCE 768 
#define  ARIZONA_AIF1TX5MIX_INPUT_3_VOLUME 767 
#define  ARIZONA_AIF1TX5MIX_INPUT_4_SOURCE 766 
#define  ARIZONA_AIF1TX5MIX_INPUT_4_VOLUME 765 
#define  ARIZONA_AIF1TX6MIX_INPUT_1_SOURCE 764 
#define  ARIZONA_AIF1TX6MIX_INPUT_1_VOLUME 763 
#define  ARIZONA_AIF1TX6MIX_INPUT_2_SOURCE 762 
#define  ARIZONA_AIF1TX6MIX_INPUT_2_VOLUME 761 
#define  ARIZONA_AIF1TX6MIX_INPUT_3_SOURCE 760 
#define  ARIZONA_AIF1TX6MIX_INPUT_3_VOLUME 759 
#define  ARIZONA_AIF1TX6MIX_INPUT_4_SOURCE 758 
#define  ARIZONA_AIF1TX6MIX_INPUT_4_VOLUME 757 
#define  ARIZONA_AIF1_BCLK_CTRL 756 
#define  ARIZONA_AIF1_FORMAT 755 
#define  ARIZONA_AIF1_FRAME_CTRL_1 754 
#define  ARIZONA_AIF1_FRAME_CTRL_11 753 
#define  ARIZONA_AIF1_FRAME_CTRL_12 752 
#define  ARIZONA_AIF1_FRAME_CTRL_13 751 
#define  ARIZONA_AIF1_FRAME_CTRL_14 750 
#define  ARIZONA_AIF1_FRAME_CTRL_15 749 
#define  ARIZONA_AIF1_FRAME_CTRL_16 748 
#define  ARIZONA_AIF1_FRAME_CTRL_2 747 
#define  ARIZONA_AIF1_FRAME_CTRL_3 746 
#define  ARIZONA_AIF1_FRAME_CTRL_4 745 
#define  ARIZONA_AIF1_FRAME_CTRL_5 744 
#define  ARIZONA_AIF1_FRAME_CTRL_6 743 
#define  ARIZONA_AIF1_FRAME_CTRL_7 742 
#define  ARIZONA_AIF1_FRAME_CTRL_8 741 
#define  ARIZONA_AIF1_RATE_CTRL 740 
#define  ARIZONA_AIF1_RX_BCLK_RATE 739 
#define  ARIZONA_AIF1_RX_ENABLES 738 
#define  ARIZONA_AIF1_RX_PIN_CTRL 737 
#define  ARIZONA_AIF1_TX_ENABLES 736 
#define  ARIZONA_AIF1_TX_PIN_CTRL 735 
#define  ARIZONA_AIF2TX1MIX_INPUT_1_SOURCE 734 
#define  ARIZONA_AIF2TX1MIX_INPUT_1_VOLUME 733 
#define  ARIZONA_AIF2TX1MIX_INPUT_2_SOURCE 732 
#define  ARIZONA_AIF2TX1MIX_INPUT_2_VOLUME 731 
#define  ARIZONA_AIF2TX1MIX_INPUT_3_SOURCE 730 
#define  ARIZONA_AIF2TX1MIX_INPUT_3_VOLUME 729 
#define  ARIZONA_AIF2TX1MIX_INPUT_4_SOURCE 728 
#define  ARIZONA_AIF2TX1MIX_INPUT_4_VOLUME 727 
#define  ARIZONA_AIF2TX2MIX_INPUT_1_SOURCE 726 
#define  ARIZONA_AIF2TX2MIX_INPUT_1_VOLUME 725 
#define  ARIZONA_AIF2TX2MIX_INPUT_2_SOURCE 724 
#define  ARIZONA_AIF2TX2MIX_INPUT_2_VOLUME 723 
#define  ARIZONA_AIF2TX2MIX_INPUT_3_SOURCE 722 
#define  ARIZONA_AIF2TX2MIX_INPUT_3_VOLUME 721 
#define  ARIZONA_AIF2TX2MIX_INPUT_4_SOURCE 720 
#define  ARIZONA_AIF2TX2MIX_INPUT_4_VOLUME 719 
#define  ARIZONA_AIF2TX3MIX_INPUT_1_SOURCE 718 
#define  ARIZONA_AIF2TX3MIX_INPUT_1_VOLUME 717 
#define  ARIZONA_AIF2TX3MIX_INPUT_2_SOURCE 716 
#define  ARIZONA_AIF2TX3MIX_INPUT_2_VOLUME 715 
#define  ARIZONA_AIF2TX3MIX_INPUT_3_SOURCE 714 
#define  ARIZONA_AIF2TX3MIX_INPUT_3_VOLUME 713 
#define  ARIZONA_AIF2TX3MIX_INPUT_4_SOURCE 712 
#define  ARIZONA_AIF2TX3MIX_INPUT_4_VOLUME 711 
#define  ARIZONA_AIF2TX4MIX_INPUT_1_SOURCE 710 
#define  ARIZONA_AIF2TX4MIX_INPUT_1_VOLUME 709 
#define  ARIZONA_AIF2TX4MIX_INPUT_2_SOURCE 708 
#define  ARIZONA_AIF2TX4MIX_INPUT_2_VOLUME 707 
#define  ARIZONA_AIF2TX4MIX_INPUT_3_SOURCE 706 
#define  ARIZONA_AIF2TX4MIX_INPUT_3_VOLUME 705 
#define  ARIZONA_AIF2TX4MIX_INPUT_4_SOURCE 704 
#define  ARIZONA_AIF2TX4MIX_INPUT_4_VOLUME 703 
#define  ARIZONA_AIF2TX5MIX_INPUT_1_SOURCE 702 
#define  ARIZONA_AIF2TX5MIX_INPUT_1_VOLUME 701 
#define  ARIZONA_AIF2TX5MIX_INPUT_2_SOURCE 700 
#define  ARIZONA_AIF2TX5MIX_INPUT_2_VOLUME 699 
#define  ARIZONA_AIF2TX5MIX_INPUT_3_SOURCE 698 
#define  ARIZONA_AIF2TX5MIX_INPUT_3_VOLUME 697 
#define  ARIZONA_AIF2TX5MIX_INPUT_4_SOURCE 696 
#define  ARIZONA_AIF2TX5MIX_INPUT_4_VOLUME 695 
#define  ARIZONA_AIF2TX6MIX_INPUT_1_SOURCE 694 
#define  ARIZONA_AIF2TX6MIX_INPUT_1_VOLUME 693 
#define  ARIZONA_AIF2TX6MIX_INPUT_2_SOURCE 692 
#define  ARIZONA_AIF2TX6MIX_INPUT_2_VOLUME 691 
#define  ARIZONA_AIF2TX6MIX_INPUT_3_SOURCE 690 
#define  ARIZONA_AIF2TX6MIX_INPUT_3_VOLUME 689 
#define  ARIZONA_AIF2TX6MIX_INPUT_4_SOURCE 688 
#define  ARIZONA_AIF2TX6MIX_INPUT_4_VOLUME 687 
#define  ARIZONA_AIF2_BCLK_CTRL 686 
#define  ARIZONA_AIF2_FORMAT 685 
#define  ARIZONA_AIF2_FRAME_CTRL_1 684 
#define  ARIZONA_AIF2_FRAME_CTRL_11 683 
#define  ARIZONA_AIF2_FRAME_CTRL_12 682 
#define  ARIZONA_AIF2_FRAME_CTRL_13 681 
#define  ARIZONA_AIF2_FRAME_CTRL_14 680 
#define  ARIZONA_AIF2_FRAME_CTRL_15 679 
#define  ARIZONA_AIF2_FRAME_CTRL_16 678 
#define  ARIZONA_AIF2_FRAME_CTRL_2 677 
#define  ARIZONA_AIF2_FRAME_CTRL_3 676 
#define  ARIZONA_AIF2_FRAME_CTRL_4 675 
#define  ARIZONA_AIF2_FRAME_CTRL_5 674 
#define  ARIZONA_AIF2_FRAME_CTRL_6 673 
#define  ARIZONA_AIF2_FRAME_CTRL_7 672 
#define  ARIZONA_AIF2_FRAME_CTRL_8 671 
#define  ARIZONA_AIF2_RATE_CTRL 670 
#define  ARIZONA_AIF2_RX_BCLK_RATE 669 
#define  ARIZONA_AIF2_RX_ENABLES 668 
#define  ARIZONA_AIF2_RX_PIN_CTRL 667 
#define  ARIZONA_AIF2_TX_ENABLES 666 
#define  ARIZONA_AIF2_TX_PIN_CTRL 665 
#define  ARIZONA_AIF3TX1MIX_INPUT_1_SOURCE 664 
#define  ARIZONA_AIF3TX1MIX_INPUT_1_VOLUME 663 
#define  ARIZONA_AIF3TX1MIX_INPUT_2_SOURCE 662 
#define  ARIZONA_AIF3TX1MIX_INPUT_2_VOLUME 661 
#define  ARIZONA_AIF3TX1MIX_INPUT_3_SOURCE 660 
#define  ARIZONA_AIF3TX1MIX_INPUT_3_VOLUME 659 
#define  ARIZONA_AIF3TX1MIX_INPUT_4_SOURCE 658 
#define  ARIZONA_AIF3TX1MIX_INPUT_4_VOLUME 657 
#define  ARIZONA_AIF3TX2MIX_INPUT_1_SOURCE 656 
#define  ARIZONA_AIF3TX2MIX_INPUT_1_VOLUME 655 
#define  ARIZONA_AIF3TX2MIX_INPUT_2_SOURCE 654 
#define  ARIZONA_AIF3TX2MIX_INPUT_2_VOLUME 653 
#define  ARIZONA_AIF3TX2MIX_INPUT_3_SOURCE 652 
#define  ARIZONA_AIF3TX2MIX_INPUT_3_VOLUME 651 
#define  ARIZONA_AIF3TX2MIX_INPUT_4_SOURCE 650 
#define  ARIZONA_AIF3TX2MIX_INPUT_4_VOLUME 649 
#define  ARIZONA_AIF3_BCLK_CTRL 648 
#define  ARIZONA_AIF3_FORMAT 647 
#define  ARIZONA_AIF3_FRAME_CTRL_1 646 
#define  ARIZONA_AIF3_FRAME_CTRL_11 645 
#define  ARIZONA_AIF3_FRAME_CTRL_12 644 
#define  ARIZONA_AIF3_FRAME_CTRL_2 643 
#define  ARIZONA_AIF3_FRAME_CTRL_3 642 
#define  ARIZONA_AIF3_FRAME_CTRL_4 641 
#define  ARIZONA_AIF3_RATE_CTRL 640 
#define  ARIZONA_AIF3_RX_BCLK_RATE 639 
#define  ARIZONA_AIF3_RX_ENABLES 638 
#define  ARIZONA_AIF3_RX_PIN_CTRL 637 
#define  ARIZONA_AIF3_TX_ENABLES 636 
#define  ARIZONA_AIF3_TX_PIN_CTRL 635 
#define  ARIZONA_ALWAYS_ON_TRIGGERS_SEQUENCE_SELECT_1 634 
#define  ARIZONA_ALWAYS_ON_TRIGGERS_SEQUENCE_SELECT_2 633 
#define  ARIZONA_ALWAYS_ON_TRIGGERS_SEQUENCE_SELECT_3 632 
#define  ARIZONA_ALWAYS_ON_TRIGGERS_SEQUENCE_SELECT_4 631 
#define  ARIZONA_ALWAYS_ON_TRIGGERS_SEQUENCE_SELECT_5 630 
#define  ARIZONA_ALWAYS_ON_TRIGGERS_SEQUENCE_SELECT_6 629 
#define  ARIZONA_AOD_IRQ1 628 
#define  ARIZONA_AOD_IRQ2 627 
#define  ARIZONA_AOD_IRQ_MASK_IRQ1 626 
#define  ARIZONA_AOD_IRQ_MASK_IRQ2 625 
#define  ARIZONA_AOD_IRQ_RAW_STATUS 624 
#define  ARIZONA_AOD_WKUP_AND_TRIG 623 
#define  ARIZONA_ASRC1LMIX_INPUT_1_SOURCE 622 
#define  ARIZONA_ASRC1RMIX_INPUT_1_SOURCE 621 
#define  ARIZONA_ASRC2LMIX_INPUT_1_SOURCE 620 
#define  ARIZONA_ASRC2RMIX_INPUT_1_SOURCE 619 
#define  ARIZONA_ASRC_ENABLE 618 
#define  ARIZONA_ASRC_RATE1 617 
#define  ARIZONA_ASRC_RATE2 616 
#define  ARIZONA_ASRC_STATUS 615 
#define  ARIZONA_ASYNC_CLOCK_1 614 
#define  ARIZONA_ASYNC_SAMPLE_RATE_1 613 
#define  ARIZONA_ASYNC_SAMPLE_RATE_1_STATUS 612 
#define  ARIZONA_ASYNC_SAMPLE_RATE_2 611 
#define  ARIZONA_ASYNC_SAMPLE_RATE_2_STATUS 610 
#define  ARIZONA_CLOCK_32K_1 609 
#define  ARIZONA_CTRL_IF_I2C1_CFG_1 608 
#define  ARIZONA_CTRL_IF_I2C1_CFG_2 607 
#define  ARIZONA_DAC_AEC_CONTROL_1 606 
#define  ARIZONA_DAC_AEC_CONTROL_2 605 
#define  ARIZONA_DAC_DIGITAL_VOLUME_1L 604 
#define  ARIZONA_DAC_DIGITAL_VOLUME_1R 603 
#define  ARIZONA_DAC_DIGITAL_VOLUME_2L 602 
#define  ARIZONA_DAC_DIGITAL_VOLUME_2R 601 
#define  ARIZONA_DAC_DIGITAL_VOLUME_3L 600 
#define  ARIZONA_DAC_DIGITAL_VOLUME_4L 599 
#define  ARIZONA_DAC_DIGITAL_VOLUME_4R 598 
#define  ARIZONA_DAC_DIGITAL_VOLUME_5L 597 
#define  ARIZONA_DAC_DIGITAL_VOLUME_5R 596 
#define  ARIZONA_DEVICE_REVISION 595 
#define  ARIZONA_DMIC1L_CONTROL 594 
#define  ARIZONA_DMIC1R_CONTROL 593 
#define  ARIZONA_DMIC2L_CONTROL 592 
#define  ARIZONA_DRC1LMIX_INPUT_1_SOURCE 591 
#define  ARIZONA_DRC1LMIX_INPUT_1_VOLUME 590 
#define  ARIZONA_DRC1RMIX_INPUT_1_SOURCE 589 
#define  ARIZONA_DRC1RMIX_INPUT_1_VOLUME 588 
#define  ARIZONA_DRC1_CTRL1 587 
#define  ARIZONA_DRC1_CTRL2 586 
#define  ARIZONA_DRC1_CTRL3 585 
#define  ARIZONA_DRC1_CTRL4 584 
#define  ARIZONA_DRC1_CTRL5 583 
#define  ARIZONA_DRE_CONTROL_1 582 
#define  ARIZONA_DRE_CONTROL_2 581 
#define  ARIZONA_DRE_CONTROL_3 580 
#define  ARIZONA_DRE_ENABLE 579 
#define  ARIZONA_DYNAMIC_FREQUENCY_SCALING_1 578 
#define  ARIZONA_EDRE_ENABLE 577 
#define  ARIZONA_EQ1MIX_INPUT_1_SOURCE 576 
#define  ARIZONA_EQ1MIX_INPUT_1_VOLUME 575 
#define  ARIZONA_EQ1_1 574 
#define  ARIZONA_EQ1_10 573 
#define  ARIZONA_EQ1_11 572 
#define  ARIZONA_EQ1_12 571 
#define  ARIZONA_EQ1_13 570 
#define  ARIZONA_EQ1_14 569 
#define  ARIZONA_EQ1_15 568 
#define  ARIZONA_EQ1_16 567 
#define  ARIZONA_EQ1_17 566 
#define  ARIZONA_EQ1_18 565 
#define  ARIZONA_EQ1_19 564 
#define  ARIZONA_EQ1_2 563 
#define  ARIZONA_EQ1_20 562 
#define  ARIZONA_EQ1_21 561 
#define  ARIZONA_EQ1_3 560 
#define  ARIZONA_EQ1_4 559 
#define  ARIZONA_EQ1_5 558 
#define  ARIZONA_EQ1_6 557 
#define  ARIZONA_EQ1_7 556 
#define  ARIZONA_EQ1_8 555 
#define  ARIZONA_EQ1_9 554 
#define  ARIZONA_EQ2MIX_INPUT_1_SOURCE 553 
#define  ARIZONA_EQ2MIX_INPUT_1_VOLUME 552 
#define  ARIZONA_EQ2_1 551 
#define  ARIZONA_EQ2_10 550 
#define  ARIZONA_EQ2_11 549 
#define  ARIZONA_EQ2_12 548 
#define  ARIZONA_EQ2_13 547 
#define  ARIZONA_EQ2_14 546 
#define  ARIZONA_EQ2_15 545 
#define  ARIZONA_EQ2_16 544 
#define  ARIZONA_EQ2_17 543 
#define  ARIZONA_EQ2_18 542 
#define  ARIZONA_EQ2_19 541 
#define  ARIZONA_EQ2_2 540 
#define  ARIZONA_EQ2_20 539 
#define  ARIZONA_EQ2_21 538 
#define  ARIZONA_EQ2_3 537 
#define  ARIZONA_EQ2_4 536 
#define  ARIZONA_EQ2_5 535 
#define  ARIZONA_EQ2_6 534 
#define  ARIZONA_EQ2_7 533 
#define  ARIZONA_EQ2_8 532 
#define  ARIZONA_EQ2_9 531 
#define  ARIZONA_EQ3MIX_INPUT_1_SOURCE 530 
#define  ARIZONA_EQ3MIX_INPUT_1_VOLUME 529 
#define  ARIZONA_EQ3_1 528 
#define  ARIZONA_EQ3_10 527 
#define  ARIZONA_EQ3_11 526 
#define  ARIZONA_EQ3_12 525 
#define  ARIZONA_EQ3_13 524 
#define  ARIZONA_EQ3_14 523 
#define  ARIZONA_EQ3_15 522 
#define  ARIZONA_EQ3_16 521 
#define  ARIZONA_EQ3_17 520 
#define  ARIZONA_EQ3_18 519 
#define  ARIZONA_EQ3_19 518 
#define  ARIZONA_EQ3_2 517 
#define  ARIZONA_EQ3_20 516 
#define  ARIZONA_EQ3_21 515 
#define  ARIZONA_EQ3_3 514 
#define  ARIZONA_EQ3_4 513 
#define  ARIZONA_EQ3_5 512 
#define  ARIZONA_EQ3_6 511 
#define  ARIZONA_EQ3_7 510 
#define  ARIZONA_EQ3_8 509 
#define  ARIZONA_EQ3_9 508 
#define  ARIZONA_EQ4MIX_INPUT_1_SOURCE 507 
#define  ARIZONA_EQ4MIX_INPUT_1_VOLUME 506 
#define  ARIZONA_EQ4_1 505 
#define  ARIZONA_EQ4_10 504 
#define  ARIZONA_EQ4_11 503 
#define  ARIZONA_EQ4_12 502 
#define  ARIZONA_EQ4_13 501 
#define  ARIZONA_EQ4_14 500 
#define  ARIZONA_EQ4_15 499 
#define  ARIZONA_EQ4_16 498 
#define  ARIZONA_EQ4_17 497 
#define  ARIZONA_EQ4_18 496 
#define  ARIZONA_EQ4_19 495 
#define  ARIZONA_EQ4_2 494 
#define  ARIZONA_EQ4_20 493 
#define  ARIZONA_EQ4_21 492 
#define  ARIZONA_EQ4_3 491 
#define  ARIZONA_EQ4_4 490 
#define  ARIZONA_EQ4_5 489 
#define  ARIZONA_EQ4_6 488 
#define  ARIZONA_EQ4_7 487 
#define  ARIZONA_EQ4_8 486 
#define  ARIZONA_EQ4_9 485 
#define  ARIZONA_FLL1_CONTROL_1 484 
#define  ARIZONA_FLL1_CONTROL_2 483 
#define  ARIZONA_FLL1_CONTROL_3 482 
#define  ARIZONA_FLL1_CONTROL_4 481 
#define  ARIZONA_FLL1_CONTROL_5 480 
#define  ARIZONA_FLL1_CONTROL_6 479 
#define  ARIZONA_FLL1_CONTROL_7 478 
#define  ARIZONA_FLL1_GPIO_CLOCK 477 
#define  ARIZONA_FLL1_SPREAD_SPECTRUM 476 
#define  ARIZONA_FLL1_SYNCHRONISER_1 475 
#define  ARIZONA_FLL1_SYNCHRONISER_2 474 
#define  ARIZONA_FLL1_SYNCHRONISER_3 473 
#define  ARIZONA_FLL1_SYNCHRONISER_4 472 
#define  ARIZONA_FLL1_SYNCHRONISER_5 471 
#define  ARIZONA_FLL1_SYNCHRONISER_6 470 
#define  ARIZONA_FLL1_SYNCHRONISER_7 469 
#define  ARIZONA_FLL2_CONTROL_1 468 
#define  ARIZONA_FLL2_CONTROL_2 467 
#define  ARIZONA_FLL2_CONTROL_3 466 
#define  ARIZONA_FLL2_CONTROL_4 465 
#define  ARIZONA_FLL2_CONTROL_5 464 
#define  ARIZONA_FLL2_CONTROL_6 463 
#define  ARIZONA_FLL2_CONTROL_7 462 
#define  ARIZONA_FLL2_GPIO_CLOCK 461 
#define  ARIZONA_FLL2_SPREAD_SPECTRUM 460 
#define  ARIZONA_FLL2_SYNCHRONISER_1 459 
#define  ARIZONA_FLL2_SYNCHRONISER_2 458 
#define  ARIZONA_FLL2_SYNCHRONISER_3 457 
#define  ARIZONA_FLL2_SYNCHRONISER_4 456 
#define  ARIZONA_FLL2_SYNCHRONISER_5 455 
#define  ARIZONA_FLL2_SYNCHRONISER_6 454 
#define  ARIZONA_FLL2_SYNCHRONISER_7 453 
#define  ARIZONA_FRF_COEFF_1 452 
#define  ARIZONA_FRF_COEFF_2 451 
#define  ARIZONA_FRF_COEFF_3 450 
#define  ARIZONA_FRF_COEFF_4 449 
#define  ARIZONA_FX_CTRL1 448 
#define  ARIZONA_FX_CTRL2 447 
#define  ARIZONA_GPIO1_CTRL 446 
#define  ARIZONA_GPIO2_CTRL 445 
#define  ARIZONA_GPIO3_CTRL 444 
#define  ARIZONA_GPIO4_CTRL 443 
#define  ARIZONA_GPIO5_CTRL 442 
#define  ARIZONA_GPIO_DEBOUNCE_CONFIG 441 
#define  ARIZONA_GP_SWITCH_1 440 
#define  ARIZONA_HAPTICS_CONTROL_1 439 
#define  ARIZONA_HAPTICS_CONTROL_2 438 
#define  ARIZONA_HAPTICS_PHASE_1_DURATION 437 
#define  ARIZONA_HAPTICS_PHASE_1_INTENSITY 436 
#define  ARIZONA_HAPTICS_PHASE_2_DURATION 435 
#define  ARIZONA_HAPTICS_PHASE_2_INTENSITY 434 
#define  ARIZONA_HAPTICS_PHASE_3_DURATION 433 
#define  ARIZONA_HAPTICS_PHASE_3_INTENSITY 432 
#define  ARIZONA_HAPTICS_STATUS 431 
#define  ARIZONA_HEADPHONE_DETECT_1 430 
#define  ARIZONA_HEADPHONE_DETECT_2 429 
#define  ARIZONA_HPF_CONTROL 428 
#define  ARIZONA_HPLP1MIX_INPUT_1_SOURCE 427 
#define  ARIZONA_HPLP1MIX_INPUT_1_VOLUME 426 
#define  ARIZONA_HPLP1MIX_INPUT_2_SOURCE 425 
#define  ARIZONA_HPLP1MIX_INPUT_2_VOLUME 424 
#define  ARIZONA_HPLP1MIX_INPUT_3_SOURCE 423 
#define  ARIZONA_HPLP1MIX_INPUT_3_VOLUME 422 
#define  ARIZONA_HPLP1MIX_INPUT_4_SOURCE 421 
#define  ARIZONA_HPLP1MIX_INPUT_4_VOLUME 420 
#define  ARIZONA_HPLP2MIX_INPUT_1_SOURCE 419 
#define  ARIZONA_HPLP2MIX_INPUT_1_VOLUME 418 
#define  ARIZONA_HPLP2MIX_INPUT_2_SOURCE 417 
#define  ARIZONA_HPLP2MIX_INPUT_2_VOLUME 416 
#define  ARIZONA_HPLP2MIX_INPUT_3_SOURCE 415 
#define  ARIZONA_HPLP2MIX_INPUT_3_VOLUME 414 
#define  ARIZONA_HPLP2MIX_INPUT_4_SOURCE 413 
#define  ARIZONA_HPLP2MIX_INPUT_4_VOLUME 412 
#define  ARIZONA_HPLP3MIX_INPUT_1_SOURCE 411 
#define  ARIZONA_HPLP3MIX_INPUT_1_VOLUME 410 
#define  ARIZONA_HPLP3MIX_INPUT_2_SOURCE 409 
#define  ARIZONA_HPLP3MIX_INPUT_2_VOLUME 408 
#define  ARIZONA_HPLP3MIX_INPUT_3_SOURCE 407 
#define  ARIZONA_HPLP3MIX_INPUT_3_VOLUME 406 
#define  ARIZONA_HPLP3MIX_INPUT_4_SOURCE 405 
#define  ARIZONA_HPLP3MIX_INPUT_4_VOLUME 404 
#define  ARIZONA_HPLP4MIX_INPUT_1_SOURCE 403 
#define  ARIZONA_HPLP4MIX_INPUT_1_VOLUME 402 
#define  ARIZONA_HPLP4MIX_INPUT_2_SOURCE 401 
#define  ARIZONA_HPLP4MIX_INPUT_2_VOLUME 400 
#define  ARIZONA_HPLP4MIX_INPUT_3_SOURCE 399 
#define  ARIZONA_HPLP4MIX_INPUT_3_VOLUME 398 
#define  ARIZONA_HPLP4MIX_INPUT_4_SOURCE 397 
#define  ARIZONA_HPLP4MIX_INPUT_4_VOLUME 396 
#define  ARIZONA_HPLPF1_1 395 
#define  ARIZONA_HPLPF1_2 394 
#define  ARIZONA_HPLPF2_1 393 
#define  ARIZONA_HPLPF2_2 392 
#define  ARIZONA_HPLPF3_1 391 
#define  ARIZONA_HPLPF3_2 390 
#define  ARIZONA_HPLPF4_1 389 
#define  ARIZONA_HPLPF4_2 388 
#define  ARIZONA_HP_TEST_CTRL_13 387 
#define  ARIZONA_IN1L_CONTROL 386 
#define  ARIZONA_IN1R_CONTROL 385 
#define  ARIZONA_IN2L_CONTROL 384 
#define  ARIZONA_INPUT_ENABLES 383 
#define  ARIZONA_INPUT_ENABLES_STATUS 382 
#define  ARIZONA_INPUT_RATE 381 
#define  ARIZONA_INPUT_VOLUME_RAMP 380 
#define  ARIZONA_INTERRUPT_CONTROL 379 
#define  ARIZONA_INTERRUPT_RAW_STATUS_2 378 
#define  ARIZONA_INTERRUPT_RAW_STATUS_3 377 
#define  ARIZONA_INTERRUPT_RAW_STATUS_4 376 
#define  ARIZONA_INTERRUPT_RAW_STATUS_5 375 
#define  ARIZONA_INTERRUPT_RAW_STATUS_6 374 
#define  ARIZONA_INTERRUPT_RAW_STATUS_7 373 
#define  ARIZONA_INTERRUPT_RAW_STATUS_8 372 
#define  ARIZONA_INTERRUPT_STATUS_1 371 
#define  ARIZONA_INTERRUPT_STATUS_1_MASK 370 
#define  ARIZONA_INTERRUPT_STATUS_2 369 
#define  ARIZONA_INTERRUPT_STATUS_2_MASK 368 
#define  ARIZONA_INTERRUPT_STATUS_3 367 
#define  ARIZONA_INTERRUPT_STATUS_3_MASK 366 
#define  ARIZONA_INTERRUPT_STATUS_4 365 
#define  ARIZONA_INTERRUPT_STATUS_4_MASK 364 
#define  ARIZONA_INTERRUPT_STATUS_5 363 
#define  ARIZONA_INTERRUPT_STATUS_5_MASK 362 
#define  ARIZONA_IRQ2_CONTROL 361 
#define  ARIZONA_IRQ2_STATUS_1 360 
#define  ARIZONA_IRQ2_STATUS_1_MASK 359 
#define  ARIZONA_IRQ2_STATUS_2 358 
#define  ARIZONA_IRQ2_STATUS_2_MASK 357 
#define  ARIZONA_IRQ2_STATUS_3 356 
#define  ARIZONA_IRQ2_STATUS_3_MASK 355 
#define  ARIZONA_IRQ2_STATUS_4 354 
#define  ARIZONA_IRQ2_STATUS_4_MASK 353 
#define  ARIZONA_IRQ2_STATUS_5 352 
#define  ARIZONA_IRQ2_STATUS_5_MASK 351 
#define  ARIZONA_IRQ_CTRL_1 350 
#define  ARIZONA_IRQ_PIN_STATUS 349 
#define  ARIZONA_ISOLATION_CONTROL 348 
#define  ARIZONA_ISRC1DEC1MIX_INPUT_1_SOURCE 347 
#define  ARIZONA_ISRC1DEC2MIX_INPUT_1_SOURCE 346 
#define  ARIZONA_ISRC1DEC3MIX_INPUT_1_SOURCE 345 
#define  ARIZONA_ISRC1DEC4MIX_INPUT_1_SOURCE 344 
#define  ARIZONA_ISRC1INT1MIX_INPUT_1_SOURCE 343 
#define  ARIZONA_ISRC1INT2MIX_INPUT_1_SOURCE 342 
#define  ARIZONA_ISRC1INT3MIX_INPUT_1_SOURCE 341 
#define  ARIZONA_ISRC1INT4MIX_INPUT_1_SOURCE 340 
#define  ARIZONA_ISRC2DEC1MIX_INPUT_1_SOURCE 339 
#define  ARIZONA_ISRC2DEC2MIX_INPUT_1_SOURCE 338 
#define  ARIZONA_ISRC2INT1MIX_INPUT_1_SOURCE 337 
#define  ARIZONA_ISRC2INT2MIX_INPUT_1_SOURCE 336 
#define  ARIZONA_ISRC_1_CTRL_1 335 
#define  ARIZONA_ISRC_1_CTRL_2 334 
#define  ARIZONA_ISRC_1_CTRL_3 333 
#define  ARIZONA_ISRC_2_CTRL_1 332 
#define  ARIZONA_ISRC_2_CTRL_2 331 
#define  ARIZONA_ISRC_2_CTRL_3 330 
#define  ARIZONA_JACK_DETECT_ANALOGUE 329 
#define  ARIZONA_JACK_DETECT_DEBOUNCE 328 
#define  ARIZONA_LDO1_CONTROL_1 327 
#define  ARIZONA_LDO1_CONTROL_2 326 
#define  ARIZONA_LDO2_CONTROL_1 325 
#define  ARIZONA_MICD_CLAMP_CONTROL 324 
#define  ARIZONA_MIC_BIAS_CTRL_1 323 
#define  ARIZONA_MIC_BIAS_CTRL_2 322 
#define  ARIZONA_MIC_BIAS_CTRL_3 321 
#define  ARIZONA_MIC_CHARGE_PUMP_1 320 
#define  ARIZONA_MIC_DETECT_1 319 
#define  ARIZONA_MIC_DETECT_2 318 
#define  ARIZONA_MIC_DETECT_3 317 
#define  ARIZONA_MIC_DETECT_4 316 
#define  ARIZONA_MIC_DETECT_LEVEL_1 315 
#define  ARIZONA_MIC_DETECT_LEVEL_2 314 
#define  ARIZONA_MIC_DETECT_LEVEL_3 313 
#define  ARIZONA_MIC_DETECT_LEVEL_4 312 
#define  ARIZONA_MISC_PAD_CTRL_1 311 
#define  ARIZONA_MISC_PAD_CTRL_2 310 
#define  ARIZONA_MISC_PAD_CTRL_3 309 
#define  ARIZONA_MISC_PAD_CTRL_4 308 
#define  ARIZONA_MISC_PAD_CTRL_5 307 
#define  ARIZONA_MISC_PAD_CTRL_6 306 
#define  ARIZONA_NOISE_GATE_CONTROL 305 
#define  ARIZONA_NOISE_GATE_SELECT_1L 304 
#define  ARIZONA_NOISE_GATE_SELECT_1R 303 
#define  ARIZONA_NOISE_GATE_SELECT_2L 302 
#define  ARIZONA_NOISE_GATE_SELECT_2R 301 
#define  ARIZONA_NOISE_GATE_SELECT_3L 300 
#define  ARIZONA_NOISE_GATE_SELECT_4L 299 
#define  ARIZONA_NOISE_GATE_SELECT_4R 298 
#define  ARIZONA_NOISE_GATE_SELECT_5L 297 
#define  ARIZONA_NOISE_GATE_SELECT_5R 296 
#define  ARIZONA_OUT1LMIX_INPUT_1_SOURCE 295 
#define  ARIZONA_OUT1LMIX_INPUT_1_VOLUME 294 
#define  ARIZONA_OUT1LMIX_INPUT_2_SOURCE 293 
#define  ARIZONA_OUT1LMIX_INPUT_2_VOLUME 292 
#define  ARIZONA_OUT1LMIX_INPUT_3_SOURCE 291 
#define  ARIZONA_OUT1LMIX_INPUT_3_VOLUME 290 
#define  ARIZONA_OUT1LMIX_INPUT_4_SOURCE 289 
#define  ARIZONA_OUT1LMIX_INPUT_4_VOLUME 288 
#define  ARIZONA_OUT1RMIX_INPUT_1_SOURCE 287 
#define  ARIZONA_OUT1RMIX_INPUT_1_VOLUME 286 
#define  ARIZONA_OUT1RMIX_INPUT_2_SOURCE 285 
#define  ARIZONA_OUT1RMIX_INPUT_2_VOLUME 284 
#define  ARIZONA_OUT1RMIX_INPUT_3_SOURCE 283 
#define  ARIZONA_OUT1RMIX_INPUT_3_VOLUME 282 
#define  ARIZONA_OUT1RMIX_INPUT_4_SOURCE 281 
#define  ARIZONA_OUT1RMIX_INPUT_4_VOLUME 280 
#define  ARIZONA_OUT2LMIX_INPUT_1_SOURCE 279 
#define  ARIZONA_OUT2LMIX_INPUT_1_VOLUME 278 
#define  ARIZONA_OUT2LMIX_INPUT_2_SOURCE 277 
#define  ARIZONA_OUT2LMIX_INPUT_2_VOLUME 276 
#define  ARIZONA_OUT2LMIX_INPUT_3_SOURCE 275 
#define  ARIZONA_OUT2LMIX_INPUT_3_VOLUME 274 
#define  ARIZONA_OUT2LMIX_INPUT_4_SOURCE 273 
#define  ARIZONA_OUT2LMIX_INPUT_4_VOLUME 272 
#define  ARIZONA_OUT2RMIX_INPUT_1_SOURCE 271 
#define  ARIZONA_OUT2RMIX_INPUT_1_VOLUME 270 
#define  ARIZONA_OUT2RMIX_INPUT_2_SOURCE 269 
#define  ARIZONA_OUT2RMIX_INPUT_2_VOLUME 268 
#define  ARIZONA_OUT2RMIX_INPUT_3_SOURCE 267 
#define  ARIZONA_OUT2RMIX_INPUT_3_VOLUME 266 
#define  ARIZONA_OUT2RMIX_INPUT_4_SOURCE 265 
#define  ARIZONA_OUT2RMIX_INPUT_4_VOLUME 264 
#define  ARIZONA_OUT3LMIX_INPUT_1_SOURCE 263 
#define  ARIZONA_OUT3LMIX_INPUT_1_VOLUME 262 
#define  ARIZONA_OUT3LMIX_INPUT_2_SOURCE 261 
#define  ARIZONA_OUT3LMIX_INPUT_2_VOLUME 260 
#define  ARIZONA_OUT3LMIX_INPUT_3_SOURCE 259 
#define  ARIZONA_OUT3LMIX_INPUT_3_VOLUME 258 
#define  ARIZONA_OUT3LMIX_INPUT_4_SOURCE 257 
#define  ARIZONA_OUT3LMIX_INPUT_4_VOLUME 256 
#define  ARIZONA_OUT4LMIX_INPUT_1_SOURCE 255 
#define  ARIZONA_OUT4LMIX_INPUT_1_VOLUME 254 
#define  ARIZONA_OUT4LMIX_INPUT_2_SOURCE 253 
#define  ARIZONA_OUT4LMIX_INPUT_2_VOLUME 252 
#define  ARIZONA_OUT4LMIX_INPUT_3_SOURCE 251 
#define  ARIZONA_OUT4LMIX_INPUT_3_VOLUME 250 
#define  ARIZONA_OUT4LMIX_INPUT_4_SOURCE 249 
#define  ARIZONA_OUT4LMIX_INPUT_4_VOLUME 248 
#define  ARIZONA_OUT4RMIX_INPUT_1_SOURCE 247 
#define  ARIZONA_OUT4RMIX_INPUT_1_VOLUME 246 
#define  ARIZONA_OUT4RMIX_INPUT_2_SOURCE 245 
#define  ARIZONA_OUT4RMIX_INPUT_2_VOLUME 244 
#define  ARIZONA_OUT4RMIX_INPUT_3_SOURCE 243 
#define  ARIZONA_OUT4RMIX_INPUT_3_VOLUME 242 
#define  ARIZONA_OUT4RMIX_INPUT_4_SOURCE 241 
#define  ARIZONA_OUT4RMIX_INPUT_4_VOLUME 240 
#define  ARIZONA_OUT5LMIX_INPUT_1_SOURCE 239 
#define  ARIZONA_OUT5LMIX_INPUT_1_VOLUME 238 
#define  ARIZONA_OUT5LMIX_INPUT_2_SOURCE 237 
#define  ARIZONA_OUT5LMIX_INPUT_2_VOLUME 236 
#define  ARIZONA_OUT5LMIX_INPUT_3_SOURCE 235 
#define  ARIZONA_OUT5LMIX_INPUT_3_VOLUME 234 
#define  ARIZONA_OUT5LMIX_INPUT_4_SOURCE 233 
#define  ARIZONA_OUT5LMIX_INPUT_4_VOLUME 232 
#define  ARIZONA_OUT5RMIX_INPUT_1_SOURCE 231 
#define  ARIZONA_OUT5RMIX_INPUT_1_VOLUME 230 
#define  ARIZONA_OUT5RMIX_INPUT_2_SOURCE 229 
#define  ARIZONA_OUT5RMIX_INPUT_2_VOLUME 228 
#define  ARIZONA_OUT5RMIX_INPUT_3_SOURCE 227 
#define  ARIZONA_OUT5RMIX_INPUT_3_VOLUME 226 
#define  ARIZONA_OUT5RMIX_INPUT_4_SOURCE 225 
#define  ARIZONA_OUT5RMIX_INPUT_4_VOLUME 224 
#define  ARIZONA_OUTPUT_ASYNC_CLOCK 223 
#define  ARIZONA_OUTPUT_ENABLES_1 222 
#define  ARIZONA_OUTPUT_PATH_CONFIG_1L 221 
#define  ARIZONA_OUTPUT_PATH_CONFIG_1R 220 
#define  ARIZONA_OUTPUT_PATH_CONFIG_2L 219 
#define  ARIZONA_OUTPUT_PATH_CONFIG_2R 218 
#define  ARIZONA_OUTPUT_PATH_CONFIG_3L 217 
#define  ARIZONA_OUTPUT_PATH_CONFIG_4L 216 
#define  ARIZONA_OUTPUT_PATH_CONFIG_4R 215 
#define  ARIZONA_OUTPUT_PATH_CONFIG_5L 214 
#define  ARIZONA_OUTPUT_PATH_CONFIG_5R 213 
#define  ARIZONA_OUTPUT_RATE_1 212 
#define  ARIZONA_OUTPUT_STATUS_1 211 
#define  ARIZONA_OUTPUT_SYSTEM_CLOCK 210 
#define  ARIZONA_OUTPUT_VOLUME_RAMP 209 
#define  ARIZONA_PDM_SPK1_CTRL_1 208 
#define  ARIZONA_PDM_SPK1_CTRL_2 207 
#define  ARIZONA_PWM1MIX_INPUT_1_SOURCE 206 
#define  ARIZONA_PWM1MIX_INPUT_1_VOLUME 205 
#define  ARIZONA_PWM1MIX_INPUT_2_SOURCE 204 
#define  ARIZONA_PWM1MIX_INPUT_2_VOLUME 203 
#define  ARIZONA_PWM1MIX_INPUT_3_SOURCE 202 
#define  ARIZONA_PWM1MIX_INPUT_3_VOLUME 201 
#define  ARIZONA_PWM1MIX_INPUT_4_SOURCE 200 
#define  ARIZONA_PWM1MIX_INPUT_4_VOLUME 199 
#define  ARIZONA_PWM2MIX_INPUT_1_SOURCE 198 
#define  ARIZONA_PWM2MIX_INPUT_1_VOLUME 197 
#define  ARIZONA_PWM2MIX_INPUT_2_SOURCE 196 
#define  ARIZONA_PWM2MIX_INPUT_2_VOLUME 195 
#define  ARIZONA_PWM2MIX_INPUT_3_SOURCE 194 
#define  ARIZONA_PWM2MIX_INPUT_3_VOLUME 193 
#define  ARIZONA_PWM2MIX_INPUT_4_SOURCE 192 
#define  ARIZONA_PWM2MIX_INPUT_4_VOLUME 191 
#define  ARIZONA_PWM_DRIVE_1 190 
#define  ARIZONA_PWM_DRIVE_2 189 
#define  ARIZONA_PWM_DRIVE_3 188 
#define  ARIZONA_RATE_ESTIMATOR_1 187 
#define  ARIZONA_RATE_ESTIMATOR_2 186 
#define  ARIZONA_RATE_ESTIMATOR_3 185 
#define  ARIZONA_RATE_ESTIMATOR_4 184 
#define  ARIZONA_RATE_ESTIMATOR_5 183 
#define  ARIZONA_RAW_OUTPUT_STATUS_1 182 
#define  ARIZONA_SAMPLE_RATE_1 181 
#define  ARIZONA_SAMPLE_RATE_1_STATUS 180 
#define  ARIZONA_SAMPLE_RATE_2 179 
#define  ARIZONA_SAMPLE_RATE_2_STATUS 178 
#define  ARIZONA_SAMPLE_RATE_3 177 
#define  ARIZONA_SAMPLE_RATE_3_STATUS 176 
#define  ARIZONA_SAMPLE_RATE_SEQUENCE_SELECT_1 175 
#define  ARIZONA_SAMPLE_RATE_SEQUENCE_SELECT_2 174 
#define  ARIZONA_SAMPLE_RATE_SEQUENCE_SELECT_3 173 
#define  ARIZONA_SAMPLE_RATE_SEQUENCE_SELECT_4 172 
#define  ARIZONA_SEQUENCE_CONTROL 171 
#define  ARIZONA_SLIMBUS_FRAMER_REF_GEAR 170 
#define  ARIZONA_SLIMBUS_RATES_1 169 
#define  ARIZONA_SLIMBUS_RATES_2 168 
#define  ARIZONA_SLIMBUS_RATES_5 167 
#define  ARIZONA_SLIMBUS_RATES_6 166 
#define  ARIZONA_SLIMBUS_RATES_7 165 
#define  ARIZONA_SLIMBUS_RX_CHANNEL_ENABLE 164 
#define  ARIZONA_SLIMBUS_RX_PORT_STATUS 163 
#define  ARIZONA_SLIMBUS_TX_CHANNEL_ENABLE 162 
#define  ARIZONA_SLIMBUS_TX_PORT_STATUS 161 
#define  ARIZONA_SLIMTX1MIX_INPUT_1_SOURCE 160 
#define  ARIZONA_SLIMTX1MIX_INPUT_1_VOLUME 159 
#define  ARIZONA_SLIMTX2MIX_INPUT_1_SOURCE 158 
#define  ARIZONA_SLIMTX2MIX_INPUT_1_VOLUME 157 
#define  ARIZONA_SLIMTX3MIX_INPUT_1_SOURCE 156 
#define  ARIZONA_SLIMTX3MIX_INPUT_1_VOLUME 155 
#define  ARIZONA_SLIMTX4MIX_INPUT_1_SOURCE 154 
#define  ARIZONA_SLIMTX4MIX_INPUT_1_VOLUME 153 
#define  ARIZONA_SLIMTX5MIX_INPUT_1_SOURCE 152 
#define  ARIZONA_SLIMTX5MIX_INPUT_1_VOLUME 151 
#define  ARIZONA_SLIMTX6MIX_INPUT_1_SOURCE 150 
#define  ARIZONA_SLIMTX6MIX_INPUT_1_VOLUME 149 
#define  ARIZONA_SOFTWARE_RESET 148 
#define  ARIZONA_SPD1_TX_CHANNEL_STATUS_1 147 
#define  ARIZONA_SPD1_TX_CHANNEL_STATUS_2 146 
#define  ARIZONA_SPD1_TX_CHANNEL_STATUS_3 145 
#define  ARIZONA_SPD1_TX_CONTROL 144 
#define  ARIZONA_SPDIFTX1MIX_INPUT_1_SOURCE 143 
#define  ARIZONA_SPDIFTX1MIX_INPUT_1_VOLUME 142 
#define  ARIZONA_SPDIFTX2MIX_INPUT_1_SOURCE 141 
#define  ARIZONA_SPDIFTX2MIX_INPUT_1_VOLUME 140 
#define  ARIZONA_SYSTEM_CLOCK_1 139 
#define  ARIZONA_TONE_GENERATOR_1 138 
#define  ARIZONA_TONE_GENERATOR_2 137 
#define  ARIZONA_TONE_GENERATOR_3 136 
#define  ARIZONA_TONE_GENERATOR_4 135 
#define  ARIZONA_TONE_GENERATOR_5 134 
#define  ARIZONA_V2_DAC_COMP_1 133 
#define  ARIZONA_V2_DAC_COMP_2 132 
#define  ARIZONA_WAKE_CONTROL 131 
#define  ARIZONA_WRITE_SEQUENCER_CTRL_0 130 
#define  ARIZONA_WRITE_SEQUENCER_CTRL_1 129 
#define  ARIZONA_WRITE_SEQUENCER_CTRL_2 128 

__attribute__((used)) static bool wm8998_readable_register(struct device *dev, unsigned int reg)
{
	switch (reg) {
	case ARIZONA_SOFTWARE_RESET:
	case ARIZONA_DEVICE_REVISION:
	case ARIZONA_CTRL_IF_I2C1_CFG_1:
	case ARIZONA_CTRL_IF_I2C1_CFG_2:
	case ARIZONA_WRITE_SEQUENCER_CTRL_0:
	case ARIZONA_WRITE_SEQUENCER_CTRL_1:
	case ARIZONA_WRITE_SEQUENCER_CTRL_2:
	case ARIZONA_TONE_GENERATOR_1:
	case ARIZONA_TONE_GENERATOR_2:
	case ARIZONA_TONE_GENERATOR_3:
	case ARIZONA_TONE_GENERATOR_4:
	case ARIZONA_TONE_GENERATOR_5:
	case ARIZONA_PWM_DRIVE_1:
	case ARIZONA_PWM_DRIVE_2:
	case ARIZONA_PWM_DRIVE_3:
	case ARIZONA_WAKE_CONTROL:
	case ARIZONA_SEQUENCE_CONTROL:
	case ARIZONA_SAMPLE_RATE_SEQUENCE_SELECT_1:
	case ARIZONA_SAMPLE_RATE_SEQUENCE_SELECT_2:
	case ARIZONA_SAMPLE_RATE_SEQUENCE_SELECT_3:
	case ARIZONA_SAMPLE_RATE_SEQUENCE_SELECT_4:
	case ARIZONA_ALWAYS_ON_TRIGGERS_SEQUENCE_SELECT_1:
	case ARIZONA_ALWAYS_ON_TRIGGERS_SEQUENCE_SELECT_2:
	case ARIZONA_ALWAYS_ON_TRIGGERS_SEQUENCE_SELECT_3:
	case ARIZONA_ALWAYS_ON_TRIGGERS_SEQUENCE_SELECT_4:
	case ARIZONA_ALWAYS_ON_TRIGGERS_SEQUENCE_SELECT_5:
	case ARIZONA_ALWAYS_ON_TRIGGERS_SEQUENCE_SELECT_6:
	case ARIZONA_HAPTICS_CONTROL_1:
	case ARIZONA_HAPTICS_CONTROL_2:
	case ARIZONA_HAPTICS_PHASE_1_INTENSITY:
	case ARIZONA_HAPTICS_PHASE_1_DURATION:
	case ARIZONA_HAPTICS_PHASE_2_INTENSITY:
	case ARIZONA_HAPTICS_PHASE_2_DURATION:
	case ARIZONA_HAPTICS_PHASE_3_INTENSITY:
	case ARIZONA_HAPTICS_PHASE_3_DURATION:
	case ARIZONA_HAPTICS_STATUS:
	case ARIZONA_CLOCK_32K_1:
	case ARIZONA_SYSTEM_CLOCK_1:
	case ARIZONA_SAMPLE_RATE_1:
	case ARIZONA_SAMPLE_RATE_2:
	case ARIZONA_SAMPLE_RATE_3:
	case ARIZONA_SAMPLE_RATE_1_STATUS:
	case ARIZONA_SAMPLE_RATE_2_STATUS:
	case ARIZONA_SAMPLE_RATE_3_STATUS:
	case ARIZONA_ASYNC_CLOCK_1:
	case ARIZONA_ASYNC_SAMPLE_RATE_1:
	case ARIZONA_ASYNC_SAMPLE_RATE_1_STATUS:
	case ARIZONA_ASYNC_SAMPLE_RATE_2:
	case ARIZONA_ASYNC_SAMPLE_RATE_2_STATUS:
	case ARIZONA_OUTPUT_SYSTEM_CLOCK:
	case ARIZONA_OUTPUT_ASYNC_CLOCK:
	case ARIZONA_RATE_ESTIMATOR_1:
	case ARIZONA_RATE_ESTIMATOR_2:
	case ARIZONA_RATE_ESTIMATOR_3:
	case ARIZONA_RATE_ESTIMATOR_4:
	case ARIZONA_RATE_ESTIMATOR_5:
	case ARIZONA_DYNAMIC_FREQUENCY_SCALING_1:
	case ARIZONA_FLL1_CONTROL_1:
	case ARIZONA_FLL1_CONTROL_2:
	case ARIZONA_FLL1_CONTROL_3:
	case ARIZONA_FLL1_CONTROL_4:
	case ARIZONA_FLL1_CONTROL_5:
	case ARIZONA_FLL1_CONTROL_6:
	case ARIZONA_FLL1_CONTROL_7:
	case ARIZONA_FLL1_SYNCHRONISER_1:
	case ARIZONA_FLL1_SYNCHRONISER_2:
	case ARIZONA_FLL1_SYNCHRONISER_3:
	case ARIZONA_FLL1_SYNCHRONISER_4:
	case ARIZONA_FLL1_SYNCHRONISER_5:
	case ARIZONA_FLL1_SYNCHRONISER_6:
	case ARIZONA_FLL1_SYNCHRONISER_7:
	case ARIZONA_FLL1_SPREAD_SPECTRUM:
	case ARIZONA_FLL1_GPIO_CLOCK:
	case ARIZONA_FLL2_CONTROL_1:
	case ARIZONA_FLL2_CONTROL_2:
	case ARIZONA_FLL2_CONTROL_3:
	case ARIZONA_FLL2_CONTROL_4:
	case ARIZONA_FLL2_CONTROL_5:
	case ARIZONA_FLL2_CONTROL_6:
	case ARIZONA_FLL2_CONTROL_7:
	case ARIZONA_FLL2_SYNCHRONISER_1:
	case ARIZONA_FLL2_SYNCHRONISER_2:
	case ARIZONA_FLL2_SYNCHRONISER_3:
	case ARIZONA_FLL2_SYNCHRONISER_4:
	case ARIZONA_FLL2_SYNCHRONISER_5:
	case ARIZONA_FLL2_SYNCHRONISER_6:
	case ARIZONA_FLL2_SYNCHRONISER_7:
	case ARIZONA_FLL2_SPREAD_SPECTRUM:
	case ARIZONA_FLL2_GPIO_CLOCK:
	case ARIZONA_MIC_CHARGE_PUMP_1:
	case ARIZONA_LDO1_CONTROL_1:
	case ARIZONA_LDO1_CONTROL_2:
	case ARIZONA_LDO2_CONTROL_1:
	case ARIZONA_MIC_BIAS_CTRL_1:
	case ARIZONA_MIC_BIAS_CTRL_2:
	case ARIZONA_MIC_BIAS_CTRL_3:
	case ARIZONA_ACCESSORY_DETECT_MODE_1:
	case ARIZONA_HEADPHONE_DETECT_1:
	case ARIZONA_HEADPHONE_DETECT_2:
	case ARIZONA_MICD_CLAMP_CONTROL:
	case ARIZONA_MIC_DETECT_1:
	case ARIZONA_MIC_DETECT_2:
	case ARIZONA_MIC_DETECT_3:
	case ARIZONA_MIC_DETECT_4:
	case ARIZONA_MIC_DETECT_LEVEL_1:
	case ARIZONA_MIC_DETECT_LEVEL_2:
	case ARIZONA_MIC_DETECT_LEVEL_3:
	case ARIZONA_MIC_DETECT_LEVEL_4:
	case ARIZONA_ISOLATION_CONTROL:
	case ARIZONA_JACK_DETECT_ANALOGUE:
	case ARIZONA_INPUT_ENABLES:
	case ARIZONA_INPUT_ENABLES_STATUS:
	case ARIZONA_INPUT_RATE:
	case ARIZONA_INPUT_VOLUME_RAMP:
	case ARIZONA_HPF_CONTROL:
	case ARIZONA_IN1L_CONTROL:
	case ARIZONA_ADC_DIGITAL_VOLUME_1L:
	case ARIZONA_DMIC1L_CONTROL:
	case ARIZONA_IN1R_CONTROL:
	case ARIZONA_ADC_DIGITAL_VOLUME_1R:
	case ARIZONA_DMIC1R_CONTROL:
	case ARIZONA_IN2L_CONTROL:
	case ARIZONA_ADC_DIGITAL_VOLUME_2L:
	case ARIZONA_DMIC2L_CONTROL:
	case ARIZONA_OUTPUT_ENABLES_1:
	case ARIZONA_OUTPUT_STATUS_1:
	case ARIZONA_RAW_OUTPUT_STATUS_1:
	case ARIZONA_OUTPUT_RATE_1:
	case ARIZONA_OUTPUT_VOLUME_RAMP:
	case ARIZONA_OUTPUT_PATH_CONFIG_1L:
	case ARIZONA_DAC_DIGITAL_VOLUME_1L:
	case ARIZONA_NOISE_GATE_SELECT_1L:
	case ARIZONA_OUTPUT_PATH_CONFIG_1R:
	case ARIZONA_DAC_DIGITAL_VOLUME_1R:
	case ARIZONA_NOISE_GATE_SELECT_1R:
	case ARIZONA_OUTPUT_PATH_CONFIG_2L:
	case ARIZONA_DAC_DIGITAL_VOLUME_2L:
	case ARIZONA_NOISE_GATE_SELECT_2L:
	case ARIZONA_OUTPUT_PATH_CONFIG_2R:
	case ARIZONA_DAC_DIGITAL_VOLUME_2R:
	case ARIZONA_NOISE_GATE_SELECT_2R:
	case ARIZONA_OUTPUT_PATH_CONFIG_3L:
	case ARIZONA_DAC_DIGITAL_VOLUME_3L:
	case ARIZONA_NOISE_GATE_SELECT_3L:
	case ARIZONA_OUTPUT_PATH_CONFIG_4L:
	case ARIZONA_DAC_DIGITAL_VOLUME_4L:
	case ARIZONA_NOISE_GATE_SELECT_4L:
	case ARIZONA_OUTPUT_PATH_CONFIG_4R:
	case ARIZONA_DAC_DIGITAL_VOLUME_4R:
	case ARIZONA_NOISE_GATE_SELECT_4R:
	case ARIZONA_OUTPUT_PATH_CONFIG_5L:
	case ARIZONA_DAC_DIGITAL_VOLUME_5L:
	case ARIZONA_NOISE_GATE_SELECT_5L:
	case ARIZONA_OUTPUT_PATH_CONFIG_5R:
	case ARIZONA_DAC_DIGITAL_VOLUME_5R:
	case ARIZONA_NOISE_GATE_SELECT_5R:
	case ARIZONA_DRE_ENABLE:
	case ARIZONA_DRE_CONTROL_1:
	case ARIZONA_DRE_CONTROL_2:
	case ARIZONA_DRE_CONTROL_3:
	case ARIZONA_EDRE_ENABLE:
	case ARIZONA_DAC_AEC_CONTROL_1:
	case ARIZONA_DAC_AEC_CONTROL_2:
	case ARIZONA_NOISE_GATE_CONTROL:
	case ARIZONA_PDM_SPK1_CTRL_1:
	case ARIZONA_PDM_SPK1_CTRL_2:
	case ARIZONA_HP_TEST_CTRL_13:
	case ARIZONA_AIF1_BCLK_CTRL:
	case ARIZONA_AIF1_TX_PIN_CTRL:
	case ARIZONA_AIF1_RX_PIN_CTRL:
	case ARIZONA_AIF1_RATE_CTRL:
	case ARIZONA_AIF1_FORMAT:
	case ARIZONA_AIF1_RX_BCLK_RATE:
	case ARIZONA_AIF1_FRAME_CTRL_1:
	case ARIZONA_AIF1_FRAME_CTRL_2:
	case ARIZONA_AIF1_FRAME_CTRL_3:
	case ARIZONA_AIF1_FRAME_CTRL_4:
	case ARIZONA_AIF1_FRAME_CTRL_5:
	case ARIZONA_AIF1_FRAME_CTRL_6:
	case ARIZONA_AIF1_FRAME_CTRL_7:
	case ARIZONA_AIF1_FRAME_CTRL_8:
	case ARIZONA_AIF1_FRAME_CTRL_11:
	case ARIZONA_AIF1_FRAME_CTRL_12:
	case ARIZONA_AIF1_FRAME_CTRL_13:
	case ARIZONA_AIF1_FRAME_CTRL_14:
	case ARIZONA_AIF1_FRAME_CTRL_15:
	case ARIZONA_AIF1_FRAME_CTRL_16:
	case ARIZONA_AIF1_TX_ENABLES:
	case ARIZONA_AIF1_RX_ENABLES:
	case ARIZONA_AIF2_BCLK_CTRL:
	case ARIZONA_AIF2_TX_PIN_CTRL:
	case ARIZONA_AIF2_RX_PIN_CTRL:
	case ARIZONA_AIF2_RATE_CTRL:
	case ARIZONA_AIF2_FORMAT:
	case ARIZONA_AIF2_RX_BCLK_RATE:
	case ARIZONA_AIF2_FRAME_CTRL_1:
	case ARIZONA_AIF2_FRAME_CTRL_2:
	case ARIZONA_AIF2_FRAME_CTRL_3:
	case ARIZONA_AIF2_FRAME_CTRL_4:
	case ARIZONA_AIF2_FRAME_CTRL_5:
	case ARIZONA_AIF2_FRAME_CTRL_6:
	case ARIZONA_AIF2_FRAME_CTRL_7:
	case ARIZONA_AIF2_FRAME_CTRL_8:
	case ARIZONA_AIF2_FRAME_CTRL_11:
	case ARIZONA_AIF2_FRAME_CTRL_12:
	case ARIZONA_AIF2_FRAME_CTRL_13:
	case ARIZONA_AIF2_FRAME_CTRL_14:
	case ARIZONA_AIF2_FRAME_CTRL_15:
	case ARIZONA_AIF2_FRAME_CTRL_16:
	case ARIZONA_AIF2_TX_ENABLES:
	case ARIZONA_AIF2_RX_ENABLES:
	case ARIZONA_AIF3_BCLK_CTRL:
	case ARIZONA_AIF3_TX_PIN_CTRL:
	case ARIZONA_AIF3_RX_PIN_CTRL:
	case ARIZONA_AIF3_RATE_CTRL:
	case ARIZONA_AIF3_FORMAT:
	case ARIZONA_AIF3_RX_BCLK_RATE:
	case ARIZONA_AIF3_FRAME_CTRL_1:
	case ARIZONA_AIF3_FRAME_CTRL_2:
	case ARIZONA_AIF3_FRAME_CTRL_3:
	case ARIZONA_AIF3_FRAME_CTRL_4:
	case ARIZONA_AIF3_FRAME_CTRL_11:
	case ARIZONA_AIF3_FRAME_CTRL_12:
	case ARIZONA_AIF3_TX_ENABLES:
	case ARIZONA_AIF3_RX_ENABLES:
	case ARIZONA_SPD1_TX_CONTROL:
	case ARIZONA_SPD1_TX_CHANNEL_STATUS_1:
	case ARIZONA_SPD1_TX_CHANNEL_STATUS_2:
	case ARIZONA_SPD1_TX_CHANNEL_STATUS_3:
	case ARIZONA_SLIMBUS_FRAMER_REF_GEAR:
	case ARIZONA_SLIMBUS_RATES_1:
	case ARIZONA_SLIMBUS_RATES_2:
	case ARIZONA_SLIMBUS_RATES_5:
	case ARIZONA_SLIMBUS_RATES_6:
	case ARIZONA_SLIMBUS_RATES_7:
	case ARIZONA_SLIMBUS_RX_CHANNEL_ENABLE:
	case ARIZONA_SLIMBUS_TX_CHANNEL_ENABLE:
	case ARIZONA_SLIMBUS_RX_PORT_STATUS:
	case ARIZONA_SLIMBUS_TX_PORT_STATUS:
	case ARIZONA_PWM1MIX_INPUT_1_SOURCE:
	case ARIZONA_PWM1MIX_INPUT_1_VOLUME:
	case ARIZONA_PWM1MIX_INPUT_2_SOURCE:
	case ARIZONA_PWM1MIX_INPUT_2_VOLUME:
	case ARIZONA_PWM1MIX_INPUT_3_SOURCE:
	case ARIZONA_PWM1MIX_INPUT_3_VOLUME:
	case ARIZONA_PWM1MIX_INPUT_4_SOURCE:
	case ARIZONA_PWM1MIX_INPUT_4_VOLUME:
	case ARIZONA_PWM2MIX_INPUT_1_SOURCE:
	case ARIZONA_PWM2MIX_INPUT_1_VOLUME:
	case ARIZONA_PWM2MIX_INPUT_2_SOURCE:
	case ARIZONA_PWM2MIX_INPUT_2_VOLUME:
	case ARIZONA_PWM2MIX_INPUT_3_SOURCE:
	case ARIZONA_PWM2MIX_INPUT_3_VOLUME:
	case ARIZONA_PWM2MIX_INPUT_4_SOURCE:
	case ARIZONA_PWM2MIX_INPUT_4_VOLUME:
	case ARIZONA_OUT1LMIX_INPUT_1_SOURCE:
	case ARIZONA_OUT1LMIX_INPUT_1_VOLUME:
	case ARIZONA_OUT1LMIX_INPUT_2_SOURCE:
	case ARIZONA_OUT1LMIX_INPUT_2_VOLUME:
	case ARIZONA_OUT1LMIX_INPUT_3_SOURCE:
	case ARIZONA_OUT1LMIX_INPUT_3_VOLUME:
	case ARIZONA_OUT1LMIX_INPUT_4_SOURCE:
	case ARIZONA_OUT1LMIX_INPUT_4_VOLUME:
	case ARIZONA_OUT1RMIX_INPUT_1_SOURCE:
	case ARIZONA_OUT1RMIX_INPUT_1_VOLUME:
	case ARIZONA_OUT1RMIX_INPUT_2_SOURCE:
	case ARIZONA_OUT1RMIX_INPUT_2_VOLUME:
	case ARIZONA_OUT1RMIX_INPUT_3_SOURCE:
	case ARIZONA_OUT1RMIX_INPUT_3_VOLUME:
	case ARIZONA_OUT1RMIX_INPUT_4_SOURCE:
	case ARIZONA_OUT1RMIX_INPUT_4_VOLUME:
	case ARIZONA_OUT2LMIX_INPUT_1_SOURCE:
	case ARIZONA_OUT2LMIX_INPUT_1_VOLUME:
	case ARIZONA_OUT2LMIX_INPUT_2_SOURCE:
	case ARIZONA_OUT2LMIX_INPUT_2_VOLUME:
	case ARIZONA_OUT2LMIX_INPUT_3_SOURCE:
	case ARIZONA_OUT2LMIX_INPUT_3_VOLUME:
	case ARIZONA_OUT2LMIX_INPUT_4_SOURCE:
	case ARIZONA_OUT2LMIX_INPUT_4_VOLUME:
	case ARIZONA_OUT2RMIX_INPUT_1_SOURCE:
	case ARIZONA_OUT2RMIX_INPUT_1_VOLUME:
	case ARIZONA_OUT2RMIX_INPUT_2_SOURCE:
	case ARIZONA_OUT2RMIX_INPUT_2_VOLUME:
	case ARIZONA_OUT2RMIX_INPUT_3_SOURCE:
	case ARIZONA_OUT2RMIX_INPUT_3_VOLUME:
	case ARIZONA_OUT2RMIX_INPUT_4_SOURCE:
	case ARIZONA_OUT2RMIX_INPUT_4_VOLUME:
	case ARIZONA_OUT3LMIX_INPUT_1_SOURCE:
	case ARIZONA_OUT3LMIX_INPUT_1_VOLUME:
	case ARIZONA_OUT3LMIX_INPUT_2_SOURCE:
	case ARIZONA_OUT3LMIX_INPUT_2_VOLUME:
	case ARIZONA_OUT3LMIX_INPUT_3_SOURCE:
	case ARIZONA_OUT3LMIX_INPUT_3_VOLUME:
	case ARIZONA_OUT3LMIX_INPUT_4_SOURCE:
	case ARIZONA_OUT3LMIX_INPUT_4_VOLUME:
	case ARIZONA_OUT4LMIX_INPUT_1_SOURCE:
	case ARIZONA_OUT4LMIX_INPUT_1_VOLUME:
	case ARIZONA_OUT4LMIX_INPUT_2_SOURCE:
	case ARIZONA_OUT4LMIX_INPUT_2_VOLUME:
	case ARIZONA_OUT4LMIX_INPUT_3_SOURCE:
	case ARIZONA_OUT4LMIX_INPUT_3_VOLUME:
	case ARIZONA_OUT4LMIX_INPUT_4_SOURCE:
	case ARIZONA_OUT4LMIX_INPUT_4_VOLUME:
	case ARIZONA_OUT4RMIX_INPUT_1_SOURCE:
	case ARIZONA_OUT4RMIX_INPUT_1_VOLUME:
	case ARIZONA_OUT4RMIX_INPUT_2_SOURCE:
	case ARIZONA_OUT4RMIX_INPUT_2_VOLUME:
	case ARIZONA_OUT4RMIX_INPUT_3_SOURCE:
	case ARIZONA_OUT4RMIX_INPUT_3_VOLUME:
	case ARIZONA_OUT4RMIX_INPUT_4_SOURCE:
	case ARIZONA_OUT4RMIX_INPUT_4_VOLUME:
	case ARIZONA_OUT5LMIX_INPUT_1_SOURCE:
	case ARIZONA_OUT5LMIX_INPUT_1_VOLUME:
	case ARIZONA_OUT5LMIX_INPUT_2_SOURCE:
	case ARIZONA_OUT5LMIX_INPUT_2_VOLUME:
	case ARIZONA_OUT5LMIX_INPUT_3_SOURCE:
	case ARIZONA_OUT5LMIX_INPUT_3_VOLUME:
	case ARIZONA_OUT5LMIX_INPUT_4_SOURCE:
	case ARIZONA_OUT5LMIX_INPUT_4_VOLUME:
	case ARIZONA_OUT5RMIX_INPUT_1_SOURCE:
	case ARIZONA_OUT5RMIX_INPUT_1_VOLUME:
	case ARIZONA_OUT5RMIX_INPUT_2_SOURCE:
	case ARIZONA_OUT5RMIX_INPUT_2_VOLUME:
	case ARIZONA_OUT5RMIX_INPUT_3_SOURCE:
	case ARIZONA_OUT5RMIX_INPUT_3_VOLUME:
	case ARIZONA_OUT5RMIX_INPUT_4_SOURCE:
	case ARIZONA_OUT5RMIX_INPUT_4_VOLUME:
	case ARIZONA_AIF1TX1MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF1TX1MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF1TX1MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF1TX1MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF1TX1MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF1TX1MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF1TX1MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF1TX1MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF1TX2MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF1TX2MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF1TX2MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF1TX2MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF1TX2MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF1TX2MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF1TX2MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF1TX2MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF1TX3MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF1TX3MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF1TX3MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF1TX3MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF1TX3MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF1TX3MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF1TX3MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF1TX3MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF1TX4MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF1TX4MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF1TX4MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF1TX4MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF1TX4MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF1TX4MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF1TX4MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF1TX4MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF1TX5MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF1TX5MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF1TX5MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF1TX5MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF1TX5MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF1TX5MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF1TX5MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF1TX5MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF1TX6MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF1TX6MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF1TX6MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF1TX6MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF1TX6MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF1TX6MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF1TX6MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF1TX6MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF2TX1MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF2TX1MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF2TX1MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF2TX1MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF2TX1MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF2TX1MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF2TX1MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF2TX1MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF2TX2MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF2TX2MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF2TX2MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF2TX2MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF2TX2MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF2TX2MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF2TX2MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF2TX2MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF2TX3MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF2TX3MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF2TX3MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF2TX3MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF2TX3MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF2TX3MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF2TX3MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF2TX3MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF2TX4MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF2TX4MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF2TX4MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF2TX4MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF2TX4MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF2TX4MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF2TX4MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF2TX4MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF2TX5MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF2TX5MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF2TX5MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF2TX5MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF2TX5MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF2TX5MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF2TX5MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF2TX5MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF2TX6MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF2TX6MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF2TX6MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF2TX6MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF2TX6MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF2TX6MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF2TX6MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF2TX6MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF3TX1MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF3TX1MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF3TX1MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF3TX1MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF3TX1MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF3TX1MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF3TX1MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF3TX1MIX_INPUT_4_VOLUME:
	case ARIZONA_AIF3TX2MIX_INPUT_1_SOURCE:
	case ARIZONA_AIF3TX2MIX_INPUT_1_VOLUME:
	case ARIZONA_AIF3TX2MIX_INPUT_2_SOURCE:
	case ARIZONA_AIF3TX2MIX_INPUT_2_VOLUME:
	case ARIZONA_AIF3TX2MIX_INPUT_3_SOURCE:
	case ARIZONA_AIF3TX2MIX_INPUT_3_VOLUME:
	case ARIZONA_AIF3TX2MIX_INPUT_4_SOURCE:
	case ARIZONA_AIF3TX2MIX_INPUT_4_VOLUME:
	case ARIZONA_SLIMTX1MIX_INPUT_1_SOURCE:
	case ARIZONA_SLIMTX1MIX_INPUT_1_VOLUME:
	case ARIZONA_SLIMTX2MIX_INPUT_1_SOURCE:
	case ARIZONA_SLIMTX2MIX_INPUT_1_VOLUME:
	case ARIZONA_SLIMTX3MIX_INPUT_1_SOURCE:
	case ARIZONA_SLIMTX3MIX_INPUT_1_VOLUME:
	case ARIZONA_SLIMTX4MIX_INPUT_1_SOURCE:
	case ARIZONA_SLIMTX4MIX_INPUT_1_VOLUME:
	case ARIZONA_SLIMTX5MIX_INPUT_1_SOURCE:
	case ARIZONA_SLIMTX5MIX_INPUT_1_VOLUME:
	case ARIZONA_SLIMTX6MIX_INPUT_1_SOURCE:
	case ARIZONA_SLIMTX6MIX_INPUT_1_VOLUME:
	case ARIZONA_SPDIFTX1MIX_INPUT_1_SOURCE:
	case ARIZONA_SPDIFTX1MIX_INPUT_1_VOLUME:
	case ARIZONA_SPDIFTX2MIX_INPUT_1_SOURCE:
	case ARIZONA_SPDIFTX2MIX_INPUT_1_VOLUME:
	case ARIZONA_EQ1MIX_INPUT_1_SOURCE:
	case ARIZONA_EQ1MIX_INPUT_1_VOLUME:
	case ARIZONA_EQ2MIX_INPUT_1_SOURCE:
	case ARIZONA_EQ2MIX_INPUT_1_VOLUME:
	case ARIZONA_EQ3MIX_INPUT_1_SOURCE:
	case ARIZONA_EQ3MIX_INPUT_1_VOLUME:
	case ARIZONA_EQ4MIX_INPUT_1_SOURCE:
	case ARIZONA_EQ4MIX_INPUT_1_VOLUME:
	case ARIZONA_DRC1LMIX_INPUT_1_SOURCE:
	case ARIZONA_DRC1LMIX_INPUT_1_VOLUME:
	case ARIZONA_DRC1RMIX_INPUT_1_SOURCE:
	case ARIZONA_DRC1RMIX_INPUT_1_VOLUME:
	case ARIZONA_HPLP1MIX_INPUT_1_SOURCE:
	case ARIZONA_HPLP1MIX_INPUT_1_VOLUME:
	case ARIZONA_HPLP1MIX_INPUT_2_SOURCE:
	case ARIZONA_HPLP1MIX_INPUT_2_VOLUME:
	case ARIZONA_HPLP1MIX_INPUT_3_SOURCE:
	case ARIZONA_HPLP1MIX_INPUT_3_VOLUME:
	case ARIZONA_HPLP1MIX_INPUT_4_SOURCE:
	case ARIZONA_HPLP1MIX_INPUT_4_VOLUME:
	case ARIZONA_HPLP2MIX_INPUT_1_SOURCE:
	case ARIZONA_HPLP2MIX_INPUT_1_VOLUME:
	case ARIZONA_HPLP2MIX_INPUT_2_SOURCE:
	case ARIZONA_HPLP2MIX_INPUT_2_VOLUME:
	case ARIZONA_HPLP2MIX_INPUT_3_SOURCE:
	case ARIZONA_HPLP2MIX_INPUT_3_VOLUME:
	case ARIZONA_HPLP2MIX_INPUT_4_SOURCE:
	case ARIZONA_HPLP2MIX_INPUT_4_VOLUME:
	case ARIZONA_HPLP3MIX_INPUT_1_SOURCE:
	case ARIZONA_HPLP3MIX_INPUT_1_VOLUME:
	case ARIZONA_HPLP3MIX_INPUT_2_SOURCE:
	case ARIZONA_HPLP3MIX_INPUT_2_VOLUME:
	case ARIZONA_HPLP3MIX_INPUT_3_SOURCE:
	case ARIZONA_HPLP3MIX_INPUT_3_VOLUME:
	case ARIZONA_HPLP3MIX_INPUT_4_SOURCE:
	case ARIZONA_HPLP3MIX_INPUT_4_VOLUME:
	case ARIZONA_HPLP4MIX_INPUT_1_SOURCE:
	case ARIZONA_HPLP4MIX_INPUT_1_VOLUME:
	case ARIZONA_HPLP4MIX_INPUT_2_SOURCE:
	case ARIZONA_HPLP4MIX_INPUT_2_VOLUME:
	case ARIZONA_HPLP4MIX_INPUT_3_SOURCE:
	case ARIZONA_HPLP4MIX_INPUT_3_VOLUME:
	case ARIZONA_HPLP4MIX_INPUT_4_SOURCE:
	case ARIZONA_HPLP4MIX_INPUT_4_VOLUME:
	case ARIZONA_ASRC1LMIX_INPUT_1_SOURCE:
	case ARIZONA_ASRC1RMIX_INPUT_1_SOURCE:
	case ARIZONA_ASRC2LMIX_INPUT_1_SOURCE:
	case ARIZONA_ASRC2RMIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC1DEC1MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC1DEC2MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC1DEC3MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC1DEC4MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC1INT1MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC1INT2MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC1INT3MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC1INT4MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC2DEC1MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC2DEC2MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC2INT1MIX_INPUT_1_SOURCE:
	case ARIZONA_ISRC2INT2MIX_INPUT_1_SOURCE:
	case ARIZONA_GPIO1_CTRL:
	case ARIZONA_GPIO2_CTRL:
	case ARIZONA_GPIO3_CTRL:
	case ARIZONA_GPIO4_CTRL:
	case ARIZONA_GPIO5_CTRL:
	case ARIZONA_IRQ_CTRL_1:
	case ARIZONA_GPIO_DEBOUNCE_CONFIG:
	case ARIZONA_GP_SWITCH_1:
	case ARIZONA_MISC_PAD_CTRL_1:
	case ARIZONA_MISC_PAD_CTRL_2:
	case ARIZONA_MISC_PAD_CTRL_3:
	case ARIZONA_MISC_PAD_CTRL_4:
	case ARIZONA_MISC_PAD_CTRL_5:
	case ARIZONA_MISC_PAD_CTRL_6:
	case ARIZONA_INTERRUPT_STATUS_1:
	case ARIZONA_INTERRUPT_STATUS_2:
	case ARIZONA_INTERRUPT_STATUS_3:
	case ARIZONA_INTERRUPT_STATUS_4:
	case ARIZONA_INTERRUPT_STATUS_5:
	case ARIZONA_INTERRUPT_STATUS_1_MASK:
	case ARIZONA_INTERRUPT_STATUS_2_MASK:
	case ARIZONA_INTERRUPT_STATUS_3_MASK:
	case ARIZONA_INTERRUPT_STATUS_4_MASK:
	case ARIZONA_INTERRUPT_STATUS_5_MASK:
	case ARIZONA_INTERRUPT_CONTROL:
	case ARIZONA_IRQ2_STATUS_1:
	case ARIZONA_IRQ2_STATUS_2:
	case ARIZONA_IRQ2_STATUS_3:
	case ARIZONA_IRQ2_STATUS_4:
	case ARIZONA_IRQ2_STATUS_5:
	case ARIZONA_IRQ2_STATUS_1_MASK:
	case ARIZONA_IRQ2_STATUS_2_MASK:
	case ARIZONA_IRQ2_STATUS_3_MASK:
	case ARIZONA_IRQ2_STATUS_4_MASK:
	case ARIZONA_IRQ2_STATUS_5_MASK:
	case ARIZONA_IRQ2_CONTROL:
	case ARIZONA_INTERRUPT_RAW_STATUS_2:
	case ARIZONA_INTERRUPT_RAW_STATUS_3:
	case ARIZONA_INTERRUPT_RAW_STATUS_4:
	case ARIZONA_INTERRUPT_RAW_STATUS_5:
	case ARIZONA_INTERRUPT_RAW_STATUS_6:
	case ARIZONA_INTERRUPT_RAW_STATUS_7:
	case ARIZONA_INTERRUPT_RAW_STATUS_8:
	case ARIZONA_IRQ_PIN_STATUS:
	case ARIZONA_AOD_WKUP_AND_TRIG:
	case ARIZONA_AOD_IRQ1:
	case ARIZONA_AOD_IRQ2:
	case ARIZONA_AOD_IRQ_MASK_IRQ1:
	case ARIZONA_AOD_IRQ_MASK_IRQ2:
	case ARIZONA_AOD_IRQ_RAW_STATUS:
	case ARIZONA_JACK_DETECT_DEBOUNCE:
	case ARIZONA_FX_CTRL1:
	case ARIZONA_FX_CTRL2:
	case ARIZONA_EQ1_1:
	case ARIZONA_EQ1_2:
	case ARIZONA_EQ1_3:
	case ARIZONA_EQ1_4:
	case ARIZONA_EQ1_5:
	case ARIZONA_EQ1_6:
	case ARIZONA_EQ1_7:
	case ARIZONA_EQ1_8:
	case ARIZONA_EQ1_9:
	case ARIZONA_EQ1_10:
	case ARIZONA_EQ1_11:
	case ARIZONA_EQ1_12:
	case ARIZONA_EQ1_13:
	case ARIZONA_EQ1_14:
	case ARIZONA_EQ1_15:
	case ARIZONA_EQ1_16:
	case ARIZONA_EQ1_17:
	case ARIZONA_EQ1_18:
	case ARIZONA_EQ1_19:
	case ARIZONA_EQ1_20:
	case ARIZONA_EQ1_21:
	case ARIZONA_EQ2_1:
	case ARIZONA_EQ2_2:
	case ARIZONA_EQ2_3:
	case ARIZONA_EQ2_4:
	case ARIZONA_EQ2_5:
	case ARIZONA_EQ2_6:
	case ARIZONA_EQ2_7:
	case ARIZONA_EQ2_8:
	case ARIZONA_EQ2_9:
	case ARIZONA_EQ2_10:
	case ARIZONA_EQ2_11:
	case ARIZONA_EQ2_12:
	case ARIZONA_EQ2_13:
	case ARIZONA_EQ2_14:
	case ARIZONA_EQ2_15:
	case ARIZONA_EQ2_16:
	case ARIZONA_EQ2_17:
	case ARIZONA_EQ2_18:
	case ARIZONA_EQ2_19:
	case ARIZONA_EQ2_20:
	case ARIZONA_EQ2_21:
	case ARIZONA_EQ3_1:
	case ARIZONA_EQ3_2:
	case ARIZONA_EQ3_3:
	case ARIZONA_EQ3_4:
	case ARIZONA_EQ3_5:
	case ARIZONA_EQ3_6:
	case ARIZONA_EQ3_7:
	case ARIZONA_EQ3_8:
	case ARIZONA_EQ3_9:
	case ARIZONA_EQ3_10:
	case ARIZONA_EQ3_11:
	case ARIZONA_EQ3_12:
	case ARIZONA_EQ3_13:
	case ARIZONA_EQ3_14:
	case ARIZONA_EQ3_15:
	case ARIZONA_EQ3_16:
	case ARIZONA_EQ3_17:
	case ARIZONA_EQ3_18:
	case ARIZONA_EQ3_19:
	case ARIZONA_EQ3_20:
	case ARIZONA_EQ3_21:
	case ARIZONA_EQ4_1:
	case ARIZONA_EQ4_2:
	case ARIZONA_EQ4_3:
	case ARIZONA_EQ4_4:
	case ARIZONA_EQ4_5:
	case ARIZONA_EQ4_6:
	case ARIZONA_EQ4_7:
	case ARIZONA_EQ4_8:
	case ARIZONA_EQ4_9:
	case ARIZONA_EQ4_10:
	case ARIZONA_EQ4_11:
	case ARIZONA_EQ4_12:
	case ARIZONA_EQ4_13:
	case ARIZONA_EQ4_14:
	case ARIZONA_EQ4_15:
	case ARIZONA_EQ4_16:
	case ARIZONA_EQ4_17:
	case ARIZONA_EQ4_18:
	case ARIZONA_EQ4_19:
	case ARIZONA_EQ4_20:
	case ARIZONA_EQ4_21:
	case ARIZONA_DRC1_CTRL1:
	case ARIZONA_DRC1_CTRL2:
	case ARIZONA_DRC1_CTRL3:
	case ARIZONA_DRC1_CTRL4:
	case ARIZONA_DRC1_CTRL5:
	case ARIZONA_HPLPF1_1:
	case ARIZONA_HPLPF1_2:
	case ARIZONA_HPLPF2_1:
	case ARIZONA_HPLPF2_2:
	case ARIZONA_HPLPF3_1:
	case ARIZONA_HPLPF3_2:
	case ARIZONA_HPLPF4_1:
	case ARIZONA_HPLPF4_2:
	case ARIZONA_ASRC_ENABLE:
	case ARIZONA_ASRC_STATUS:
	case ARIZONA_ASRC_RATE1:
	case ARIZONA_ASRC_RATE2:
	case ARIZONA_ISRC_1_CTRL_1:
	case ARIZONA_ISRC_1_CTRL_2:
	case ARIZONA_ISRC_1_CTRL_3:
	case ARIZONA_ISRC_2_CTRL_1:
	case ARIZONA_ISRC_2_CTRL_2:
	case ARIZONA_ISRC_2_CTRL_3:
	case ARIZONA_FRF_COEFF_1:
	case ARIZONA_FRF_COEFF_2:
	case ARIZONA_FRF_COEFF_3:
	case ARIZONA_FRF_COEFF_4:
	case ARIZONA_V2_DAC_COMP_1:
	case ARIZONA_V2_DAC_COMP_2:
		return true;
	default:
		return false;
	}
}