#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */

/* Variables and functions */
 int /*<<< orphan*/  exit (int) ; 
 int /*<<< orphan*/  fprintf (int /*<<< orphan*/ ,char*,...) ; 
 char* progname ; 
 int /*<<< orphan*/  stderr ; 

__attribute__((used)) static void
usage(bool cpu_intel)
{

	(void)fprintf(stderr,
	"Usage: %s --vm=<vmname>\n"
	"       [--cpu=<vcpu_number>]\n"
	"       [--create]\n"
	"       [--destroy]\n"
	"       [--get-all]\n"
	"       [--get-stats]\n"
	"       [--set-desc-ds]\n"
	"       [--get-desc-ds]\n"
	"       [--set-desc-es]\n"
	"       [--get-desc-es]\n"
	"       [--set-desc-gs]\n"
	"       [--get-desc-gs]\n"
	"       [--set-desc-fs]\n"
	"       [--get-desc-fs]\n"
	"       [--set-desc-cs]\n"
	"       [--get-desc-cs]\n"
	"       [--set-desc-ss]\n"
	"       [--get-desc-ss]\n"
	"       [--set-desc-tr]\n"
	"       [--get-desc-tr]\n"
	"       [--set-desc-ldtr]\n"
	"       [--get-desc-ldtr]\n"
	"       [--set-desc-gdtr]\n"
	"       [--get-desc-gdtr]\n"
	"       [--set-desc-idtr]\n"
	"       [--get-desc-idtr]\n"
	"       [--run]\n"
	"       [--capname=<capname>]\n"
	"       [--getcap]\n"
	"       [--setcap=<0|1>]\n"
	"       [--desc-base=<BASE>]\n"
	"       [--desc-limit=<LIMIT>]\n"
	"       [--desc-access=<ACCESS>]\n"
	"       [--set-cr0=<CR0>]\n"
	"       [--get-cr0]\n"
	"       [--set-cr2=<CR2>]\n"
	"       [--get-cr2]\n"
	"       [--set-cr3=<CR3>]\n"
	"       [--get-cr3]\n"
	"       [--set-cr4=<CR4>]\n"
	"       [--get-cr4]\n"
	"       [--set-dr0=<DR0>]\n"
	"       [--get-dr0]\n"
	"       [--set-dr1=<DR1>]\n"
	"       [--get-dr1]\n"
	"       [--set-dr2=<DR2>]\n"
	"       [--get-dr2]\n"
	"       [--set-dr3=<DR3>]\n"
	"       [--get-dr3]\n"
	"       [--set-dr6=<DR6>]\n"
	"       [--get-dr6]\n"
	"       [--set-dr7=<DR7>]\n"
	"       [--get-dr7]\n"
	"       [--set-rsp=<RSP>]\n"
	"       [--get-rsp]\n"
	"       [--set-rip=<RIP>]\n"
	"       [--get-rip]\n"
	"       [--get-rax]\n"
	"       [--set-rax=<RAX>]\n"
	"       [--get-rbx]\n"
	"       [--get-rcx]\n"
	"       [--get-rdx]\n"
	"       [--get-rsi]\n"
	"       [--get-rdi]\n"
	"       [--get-rbp]\n"
	"       [--get-r8]\n"
	"       [--get-r9]\n"
	"       [--get-r10]\n"
	"       [--get-r11]\n"
	"       [--get-r12]\n"
	"       [--get-r13]\n"
	"       [--get-r14]\n"
	"       [--get-r15]\n"
	"       [--set-rflags=<RFLAGS>]\n"
	"       [--get-rflags]\n"
	"       [--set-cs]\n"
	"       [--get-cs]\n"
	"       [--set-ds]\n"
	"       [--get-ds]\n"
	"       [--set-es]\n"
	"       [--get-es]\n"
	"       [--set-fs]\n"
	"       [--get-fs]\n"
	"       [--set-gs]\n"
	"       [--get-gs]\n"
	"       [--set-ss]\n"
	"       [--get-ss]\n"
	"       [--get-tr]\n"
	"       [--get-ldtr]\n"
	"       [--set-x2apic-state=<state>]\n"
	"       [--get-x2apic-state]\n"
	"       [--unassign-pptdev=<bus/slot/func>]\n"
	"       [--set-mem=<memory in units of MB>]\n"
	"       [--get-lowmem]\n"
	"       [--get-highmem]\n"
	"       [--get-gpa-pmap]\n"
	"       [--assert-lapic-lvt=<pin>]\n"
	"       [--inject-nmi]\n"
	"       [--force-reset]\n"
	"       [--force-poweroff]\n"
	"       [--get-rtc-time]\n"
	"       [--set-rtc-time=<secs>]\n"
	"       [--get-rtc-nvram]\n"
	"       [--set-rtc-nvram=<val>]\n"
	"       [--rtc-nvram-offset=<offset>]\n"
	"       [--get-active-cpus]\n"
	"       [--get-suspended-cpus]\n"
	"       [--get-intinfo]\n"
	"       [--get-eptp]\n"
	"       [--set-exception-bitmap]\n"
	"       [--get-exception-bitmap]\n"
	"       [--get-tsc-offset]\n"
	"       [--get-guest-pat]\n"
	"       [--get-io-bitmap-address]\n"
	"       [--get-msr-bitmap]\n"
	"       [--get-msr-bitmap-address]\n"
	"       [--get-guest-sysenter]\n"
	"       [--get-exit-reason]\n"
	"       [--get-cpu-topology]\n",
	progname);

	if (cpu_intel) {
		(void)fprintf(stderr,
		"       [--get-vmcs-pinbased-ctls]\n"
		"       [--get-vmcs-procbased-ctls]\n"
		"       [--get-vmcs-procbased-ctls2]\n"
		"       [--get-vmcs-entry-interruption-info]\n"
		"       [--set-vmcs-entry-interruption-info=<info>]\n"
		"       [--get-vmcs-guest-physical-address\n"
		"       [--get-vmcs-guest-linear-address\n"
		"       [--get-vmcs-host-pat]\n"
		"       [--get-vmcs-host-cr0]\n"
		"       [--get-vmcs-host-cr3]\n"
		"       [--get-vmcs-host-cr4]\n"
		"       [--get-vmcs-host-rip]\n"
		"       [--get-vmcs-host-rsp]\n"
		"       [--get-vmcs-cr0-mask]\n"
		"       [--get-vmcs-cr0-shadow]\n"
		"       [--get-vmcs-cr4-mask]\n"
		"       [--get-vmcs-cr4-shadow]\n"
		"       [--get-vmcs-cr3-targets]\n"
		"       [--get-vmcs-apic-access-address]\n"
		"       [--get-vmcs-virtual-apic-address]\n"
		"       [--get-vmcs-tpr-threshold]\n"
		"       [--get-vmcs-vpid]\n"
		"       [--get-vmcs-instruction-error]\n"
		"       [--get-vmcs-exit-ctls]\n"
		"       [--get-vmcs-entry-ctls]\n"
		"       [--get-vmcs-link]\n"
		"       [--get-vmcs-exit-qualification]\n"
		"       [--get-vmcs-exit-interruption-info]\n"
		"       [--get-vmcs-exit-interruption-error]\n"
		"       [--get-vmcs-interruptibility]\n"
		);
	} else {
		(void)fprintf(stderr,
		"       [--get-vmcb-intercepts]\n"
		"       [--get-vmcb-asid]\n"
		"       [--get-vmcb-exit-details]\n"
		"       [--get-vmcb-tlb-ctrl]\n"
		"       [--get-vmcb-virq]\n"
		"       [--get-avic-apic-bar]\n"
		"       [--get-avic-backing-page]\n"
		"       [--get-avic-table]\n"
		);
	}
	exit(1);
}