#define NULL ((void*)0)
typedef unsigned long size_t;  // Customize by platform.
typedef long intptr_t; typedef unsigned long uintptr_t;
typedef long scalar_t__;  // Either arithmetic or pointer type.
/* By default, we understand bool (as a convenience). */
typedef int bool;
#define false 0
#define true 1

/* Forward declarations */

/* Type definitions */
typedef  int /*<<< orphan*/ * GLUTproc ;

/* Variables and functions */
 int /*<<< orphan*/  glutAddMenuEntry ; 
 int /*<<< orphan*/  glutAddSubMenu ; 
 int /*<<< orphan*/  glutAttachMenu ; 
 int /*<<< orphan*/  glutBitmapCharacter ; 
 int /*<<< orphan*/  glutBitmapHeight ; 
 int /*<<< orphan*/  glutBitmapLength ; 
 int /*<<< orphan*/  glutBitmapString ; 
 int /*<<< orphan*/  glutBitmapWidth ; 
 int /*<<< orphan*/  glutButtonBoxFunc ; 
 int /*<<< orphan*/  glutChangeToMenuEntry ; 
 int /*<<< orphan*/  glutChangeToSubMenu ; 
 int /*<<< orphan*/  glutCloseFunc ; 
 int /*<<< orphan*/  glutCopyColormap ; 
 int /*<<< orphan*/  glutCreateMenu ; 
 int /*<<< orphan*/  glutCreateSubWindow ; 
 int /*<<< orphan*/  glutCreateWindow ; 
 int /*<<< orphan*/  glutDestroyMenu ; 
 int /*<<< orphan*/  glutDestroyWindow ; 
 int /*<<< orphan*/  glutDetachMenu ; 
 int /*<<< orphan*/  glutDeviceGet ; 
 int /*<<< orphan*/  glutDialsFunc ; 
 int /*<<< orphan*/  glutDisplayFunc ; 
 int /*<<< orphan*/  glutEnterGameMode ; 
 int /*<<< orphan*/  glutEntryFunc ; 
 int /*<<< orphan*/  glutEstablishOverlay ; 
 int /*<<< orphan*/  glutExit ; 
 int /*<<< orphan*/  glutExtensionSupported ; 
 int /*<<< orphan*/  glutForceJoystickFunc ; 
 int /*<<< orphan*/  glutFullScreen ; 
 int /*<<< orphan*/  glutFullScreenToggle ; 
 int /*<<< orphan*/  glutGameModeGet ; 
 int /*<<< orphan*/  glutGameModeString ; 
 int /*<<< orphan*/  glutGet ; 
 int /*<<< orphan*/  glutGetColor ; 
 int /*<<< orphan*/  glutGetMenu ; 
 int /*<<< orphan*/  glutGetMenuData ; 
 int /*<<< orphan*/  glutGetModeValues ; 
 int /*<<< orphan*/  glutGetModifiers ; 
 int /*<<< orphan*/  glutGetProcAddress ; 
 int /*<<< orphan*/  glutGetWindow ; 
 int /*<<< orphan*/  glutGetWindowData ; 
 int /*<<< orphan*/  glutHideOverlay ; 
 int /*<<< orphan*/  glutHideWindow ; 
 int /*<<< orphan*/  glutIconifyWindow ; 
 int /*<<< orphan*/  glutIdleFunc ; 
 int /*<<< orphan*/  glutIgnoreKeyRepeat ; 
 int /*<<< orphan*/  glutInit ; 
 int /*<<< orphan*/  glutInitContextFlags ; 
 int /*<<< orphan*/  glutInitContextProfile ; 
 int /*<<< orphan*/  glutInitContextVersion ; 
 int /*<<< orphan*/  glutInitDisplayMode ; 
 int /*<<< orphan*/  glutInitDisplayString ; 
 int /*<<< orphan*/  glutInitWindowPosition ; 
 int /*<<< orphan*/  glutInitWindowSize ; 
 int /*<<< orphan*/  glutJoystickFunc ; 
 int /*<<< orphan*/  glutJoystickGetCenter ; 
 int /*<<< orphan*/  glutJoystickGetDeadBand ; 
 int /*<<< orphan*/  glutJoystickGetMaxRange ; 
 int /*<<< orphan*/  glutJoystickGetMinRange ; 
 int /*<<< orphan*/  glutJoystickGetNumAxes ; 
 int /*<<< orphan*/  glutJoystickGetNumButtons ; 
 int /*<<< orphan*/  glutJoystickGetSaturation ; 
 int /*<<< orphan*/  glutJoystickNotWorking ; 
 int /*<<< orphan*/  glutJoystickSetCenter ; 
 int /*<<< orphan*/  glutJoystickSetDeadBand ; 
 int /*<<< orphan*/  glutJoystickSetMaxRange ; 
 int /*<<< orphan*/  glutJoystickSetMinRange ; 
 int /*<<< orphan*/  glutJoystickSetSaturation ; 
 int /*<<< orphan*/  glutKeyboardFunc ; 
 int /*<<< orphan*/  glutKeyboardUpFunc ; 
 int /*<<< orphan*/  glutLayerGet ; 
 int /*<<< orphan*/  glutLeaveGameMode ; 
 int /*<<< orphan*/  glutLeaveMainLoop ; 
 int /*<<< orphan*/  glutMainLoop ; 
 int /*<<< orphan*/  glutMainLoopEvent ; 
 int /*<<< orphan*/  glutMenuDestroyFunc ; 
 int /*<<< orphan*/  glutMenuStateFunc ; 
 int /*<<< orphan*/  glutMenuStatusFunc ; 
 int /*<<< orphan*/  glutMotionFunc ; 
 int /*<<< orphan*/  glutMouseFunc ; 
 int /*<<< orphan*/  glutMouseWheelFunc ; 
 int /*<<< orphan*/  glutOverlayDisplayFunc ; 
 int /*<<< orphan*/  glutPassiveMotionFunc ; 
 int /*<<< orphan*/  glutPopWindow ; 
 int /*<<< orphan*/  glutPositionWindow ; 
 int /*<<< orphan*/  glutPostOverlayRedisplay ; 
 int /*<<< orphan*/  glutPostRedisplay ; 
 int /*<<< orphan*/  glutPostWindowOverlayRedisplay ; 
 int /*<<< orphan*/  glutPostWindowRedisplay ; 
 int /*<<< orphan*/  glutPushWindow ; 
 int /*<<< orphan*/  glutRemoveMenuItem ; 
 int /*<<< orphan*/  glutRemoveOverlay ; 
 int /*<<< orphan*/  glutReportErrors ; 
 int /*<<< orphan*/  glutReshapeFunc ; 
 int /*<<< orphan*/  glutReshapeWindow ; 
 int /*<<< orphan*/  glutSetColor ; 
 int /*<<< orphan*/  glutSetCursor ; 
 int /*<<< orphan*/  glutSetIconTitle ; 
 int /*<<< orphan*/  glutSetKeyRepeat ; 
 int /*<<< orphan*/  glutSetMenu ; 
 int /*<<< orphan*/  glutSetMenuData ; 
 int /*<<< orphan*/  glutSetOption ; 
 int /*<<< orphan*/  glutSetWindow ; 
 int /*<<< orphan*/  glutSetWindowData ; 
 int /*<<< orphan*/  glutSetWindowTitle ; 
 int /*<<< orphan*/  glutSetupVideoResizing ; 
 int /*<<< orphan*/  glutShowOverlay ; 
 int /*<<< orphan*/  glutShowWindow ; 
 int /*<<< orphan*/  glutSolidCone ; 
 int /*<<< orphan*/  glutSolidCube ; 
 int /*<<< orphan*/  glutSolidCylinder ; 
 int /*<<< orphan*/  glutSolidDodecahedron ; 
 int /*<<< orphan*/  glutSolidIcosahedron ; 
 int /*<<< orphan*/  glutSolidOctahedron ; 
 int /*<<< orphan*/  glutSolidRhombicDodecahedron ; 
 int /*<<< orphan*/  glutSolidSierpinskiSponge ; 
 int /*<<< orphan*/  glutSolidSphere ; 
 int /*<<< orphan*/  glutSolidTeapot ; 
 int /*<<< orphan*/  glutSolidTetrahedron ; 
 int /*<<< orphan*/  glutSolidTorus ; 
 int /*<<< orphan*/  glutSpaceballButtonFunc ; 
 int /*<<< orphan*/  glutSpaceballMotionFunc ; 
 int /*<<< orphan*/  glutSpaceballRotateFunc ; 
 int /*<<< orphan*/  glutSpecialFunc ; 
 int /*<<< orphan*/  glutSpecialUpFunc ; 
 int /*<<< orphan*/  glutStopVideoResizing ; 
 int /*<<< orphan*/  glutStrokeCharacter ; 
 int /*<<< orphan*/  glutStrokeHeight ; 
 int /*<<< orphan*/  glutStrokeLength ; 
 int /*<<< orphan*/  glutStrokeString ; 
 int /*<<< orphan*/  glutStrokeWidth ; 
 int /*<<< orphan*/  glutSwapBuffers ; 
 int /*<<< orphan*/  glutTabletButtonFunc ; 
 int /*<<< orphan*/  glutTabletMotionFunc ; 
 int /*<<< orphan*/  glutTimerFunc ; 
 int /*<<< orphan*/  glutUseLayer ; 
 int /*<<< orphan*/  glutVideoPan ; 
 int /*<<< orphan*/  glutVideoResize ; 
 int /*<<< orphan*/  glutVideoResizeGet ; 
 int /*<<< orphan*/  glutVisibilityFunc ; 
 int /*<<< orphan*/  glutWMCloseFunc ; 
 int /*<<< orphan*/  glutWarpPointer ; 
 int /*<<< orphan*/  glutWindowStatusFunc ; 
 int /*<<< orphan*/  glutWireCone ; 
 int /*<<< orphan*/  glutWireCube ; 
 int /*<<< orphan*/  glutWireCylinder ; 
 int /*<<< orphan*/  glutWireDodecahedron ; 
 int /*<<< orphan*/  glutWireIcosahedron ; 
 int /*<<< orphan*/  glutWireOctahedron ; 
 int /*<<< orphan*/  glutWireRhombicDodecahedron ; 
 int /*<<< orphan*/  glutWireSierpinskiSponge ; 
 int /*<<< orphan*/  glutWireSphere ; 
 int /*<<< orphan*/  glutWireTeapot ; 
 int /*<<< orphan*/  glutWireTetrahedron ; 
 int /*<<< orphan*/  glutWireTorus ; 
 scalar_t__ strcmp (char const*,char*) ; 
 scalar_t__ strncmp (char const*,char*,int) ; 

__attribute__((used)) static GLUTproc fghGetGLUTProcAddress( const char* procName )
{
    /* optimization: quick initial check */
    if( strncmp( procName, "glut", 4 ) != 0 )
        return NULL;

#define CHECK_NAME(x) if( strcmp( procName, #x ) == 0) return (GLUTproc)x;
    CHECK_NAME(glutInit);
    CHECK_NAME(glutInitDisplayMode);
    CHECK_NAME(glutInitDisplayString);
    CHECK_NAME(glutInitWindowPosition);
    CHECK_NAME(glutInitWindowSize);
    CHECK_NAME(glutMainLoop);
    CHECK_NAME(glutExit);
    CHECK_NAME(glutCreateWindow);
    CHECK_NAME(glutCreateSubWindow);
    CHECK_NAME(glutDestroyWindow);
    CHECK_NAME(glutPostRedisplay);
    CHECK_NAME(glutPostWindowRedisplay);
    CHECK_NAME(glutSwapBuffers);
    CHECK_NAME(glutGetWindow);
    CHECK_NAME(glutSetWindow);
    CHECK_NAME(glutSetWindowTitle);
    CHECK_NAME(glutSetIconTitle);
    CHECK_NAME(glutPositionWindow);
    CHECK_NAME(glutReshapeWindow);
    CHECK_NAME(glutPopWindow);
    CHECK_NAME(glutPushWindow);
    CHECK_NAME(glutIconifyWindow);
    CHECK_NAME(glutShowWindow);
    CHECK_NAME(glutHideWindow);
    CHECK_NAME(glutFullScreen);
    CHECK_NAME(glutSetCursor);
    CHECK_NAME(glutWarpPointer);
    CHECK_NAME(glutEstablishOverlay);
    CHECK_NAME(glutRemoveOverlay);
    CHECK_NAME(glutUseLayer);
    CHECK_NAME(glutPostOverlayRedisplay);
    CHECK_NAME(glutPostWindowOverlayRedisplay);
    CHECK_NAME(glutShowOverlay);
    CHECK_NAME(glutHideOverlay);
    CHECK_NAME(glutCreateMenu);
    CHECK_NAME(glutDestroyMenu);
    CHECK_NAME(glutGetMenu);
    CHECK_NAME(glutSetMenu);
    CHECK_NAME(glutAddMenuEntry);
    CHECK_NAME(glutAddSubMenu);
    CHECK_NAME(glutChangeToMenuEntry);
    CHECK_NAME(glutChangeToSubMenu);
    CHECK_NAME(glutRemoveMenuItem);
    CHECK_NAME(glutAttachMenu);
    CHECK_NAME(glutDetachMenu);
    CHECK_NAME(glutDisplayFunc);
    CHECK_NAME(glutReshapeFunc);
    CHECK_NAME(glutKeyboardFunc);
    CHECK_NAME(glutMouseFunc);
    CHECK_NAME(glutMotionFunc);
    CHECK_NAME(glutPassiveMotionFunc);
    CHECK_NAME(glutEntryFunc);
    CHECK_NAME(glutVisibilityFunc);
    CHECK_NAME(glutIdleFunc);
    CHECK_NAME(glutTimerFunc);
    CHECK_NAME(glutMenuStateFunc);
    CHECK_NAME(glutSpecialFunc);
    CHECK_NAME(glutSpaceballMotionFunc);
    CHECK_NAME(glutSpaceballRotateFunc);
    CHECK_NAME(glutSpaceballButtonFunc);
    CHECK_NAME(glutButtonBoxFunc);
    CHECK_NAME(glutDialsFunc);
    CHECK_NAME(glutTabletMotionFunc);
    CHECK_NAME(glutTabletButtonFunc);
    CHECK_NAME(glutMenuStatusFunc);
    CHECK_NAME(glutOverlayDisplayFunc);
    CHECK_NAME(glutWindowStatusFunc);
    CHECK_NAME(glutKeyboardUpFunc);
    CHECK_NAME(glutSpecialUpFunc);
#if !defined(_WIN32_WCE)
    CHECK_NAME(glutJoystickFunc);
#endif /* !defined(_WIN32_WCE) */
    CHECK_NAME(glutSetColor);
    CHECK_NAME(glutGetColor);
    CHECK_NAME(glutCopyColormap);
    CHECK_NAME(glutGet);
    CHECK_NAME(glutDeviceGet);
    CHECK_NAME(glutExtensionSupported);
    CHECK_NAME(glutGetModifiers);
    CHECK_NAME(glutLayerGet);
    CHECK_NAME(glutBitmapCharacter);
    CHECK_NAME(glutBitmapWidth);
    CHECK_NAME(glutStrokeCharacter);
    CHECK_NAME(glutStrokeWidth);
    CHECK_NAME(glutBitmapLength);
    CHECK_NAME(glutStrokeLength);
    CHECK_NAME(glutWireSphere);
    CHECK_NAME(glutSolidSphere);
    CHECK_NAME(glutWireCone);
    CHECK_NAME(glutSolidCone);
    CHECK_NAME(glutWireCube);
    CHECK_NAME(glutSolidCube);
    CHECK_NAME(glutWireTorus);
    CHECK_NAME(glutSolidTorus);
    CHECK_NAME(glutWireDodecahedron);
    CHECK_NAME(glutSolidDodecahedron);
    CHECK_NAME(glutWireTeapot);
    CHECK_NAME(glutSolidTeapot);
    CHECK_NAME(glutWireOctahedron);
    CHECK_NAME(glutSolidOctahedron);
    CHECK_NAME(glutWireTetrahedron);
    CHECK_NAME(glutSolidTetrahedron);
    CHECK_NAME(glutWireIcosahedron);
    CHECK_NAME(glutSolidIcosahedron);
    CHECK_NAME(glutVideoResizeGet);
    CHECK_NAME(glutSetupVideoResizing);
    CHECK_NAME(glutStopVideoResizing);
    CHECK_NAME(glutVideoResize);
    CHECK_NAME(glutVideoPan);
    CHECK_NAME(glutReportErrors);
    CHECK_NAME(glutIgnoreKeyRepeat);
    CHECK_NAME(glutSetKeyRepeat);
#if !defined(_WIN32_WCE)
    CHECK_NAME(glutForceJoystickFunc);
    CHECK_NAME(glutGameModeString);
    CHECK_NAME(glutEnterGameMode);
    CHECK_NAME(glutLeaveGameMode);
    CHECK_NAME(glutGameModeGet);
#endif /* !defined(_WIN32_WCE) */
    /* freeglut extensions */
    CHECK_NAME(glutMainLoopEvent);
    CHECK_NAME(glutLeaveMainLoop);
    CHECK_NAME(glutCloseFunc);
    CHECK_NAME(glutWMCloseFunc);
    CHECK_NAME(glutMenuDestroyFunc);
    CHECK_NAME(glutFullScreenToggle);
    CHECK_NAME(glutSetOption);
    CHECK_NAME(glutGetModeValues);
    CHECK_NAME(glutSetWindowData);
    CHECK_NAME(glutGetWindowData);
    CHECK_NAME(glutSetMenuData);
    CHECK_NAME(glutGetMenuData);
    CHECK_NAME(glutBitmapHeight);
    CHECK_NAME(glutStrokeHeight);
    CHECK_NAME(glutBitmapString);
    CHECK_NAME(glutStrokeString);
    CHECK_NAME(glutWireRhombicDodecahedron);
    CHECK_NAME(glutSolidRhombicDodecahedron);
    CHECK_NAME(glutWireSierpinskiSponge);
    CHECK_NAME(glutSolidSierpinskiSponge);
    CHECK_NAME(glutWireCylinder);
    CHECK_NAME(glutSolidCylinder);
    CHECK_NAME(glutGetProcAddress);
    CHECK_NAME(glutMouseWheelFunc);
    CHECK_NAME(glutJoystickGetNumAxes);
    CHECK_NAME(glutJoystickGetNumButtons);
    CHECK_NAME(glutJoystickNotWorking);
    CHECK_NAME(glutJoystickGetDeadBand);
    CHECK_NAME(glutJoystickSetDeadBand);
    CHECK_NAME(glutJoystickGetSaturation);
    CHECK_NAME(glutJoystickSetSaturation);
    CHECK_NAME(glutJoystickSetMinRange);
    CHECK_NAME(glutJoystickSetMaxRange);
    CHECK_NAME(glutJoystickSetCenter);
    CHECK_NAME(glutJoystickGetMinRange);
    CHECK_NAME(glutJoystickGetMaxRange);
    CHECK_NAME(glutJoystickGetCenter);
    CHECK_NAME(glutInitContextVersion);
    CHECK_NAME(glutInitContextFlags);
    CHECK_NAME(glutInitContextProfile);
#undef CHECK_NAME

    return NULL;
}